### ISSUE TITLE
More options link in Readme.md doesn't work (404) - need updating?

### ISSUE THREAD

**Issue by Constantin07** [inspec/inspec#1001]
### Description

The "More options" link https://github.com/chef/inspec/blob/master/docs/ctl_inspec.rst in Readme.md doesn't work - gives 404 Page not found.
### InSpec and Platform Version

Latest.
### Replication Case

Try to open the https://github.com/chef/inspec/blob/master/docs/ctl_inspec.rst
### Possible Solutions

Update the link with correct location. 
### Stacktrace

None.

**Comment by chris-rock** [comment]
Thanks @Constantin07 for highlighting this issue. The correct link is https://github.com/chef/inspec/blob/master/docs/cli.rst

**Comment by Constantin07** [comment]
@chris-rock Thank you.
