### ISSUE TITLE
ip6tables

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1011]
### Description

A ip6tables resource to verify ip6 configuration as required by MITRE as requested in #563

**Comment by atomic111** [comment]
i need this resource too

**Comment by einsteinchen** [comment]
Just filling a need and not necessary a good solution:
- I copied the iptables ressource
- modify the command in the resource file (my hint: add a „6“ in iptables)
- store it in your profile in the libraries folder
- same rules apply like in iptables
As said, that is a hack and better solutions should be thought of (I spent some time but my results did not provide what I wanted, e.g. Change iptables and add a parameter for v4 and v6 - my ruby understanding seems to be limited).
And sorry if this is not really helpful for inspec as such.
BR.

Am 29.11.2017 um 10:59 schrieb Patrick Münch <notifications@github.com<mailto:notifications@github.com>>:


i need this resource too
