### ISSUE TITLE
Error output not informative

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1016]
### Description

Before https://github.com/chef/inspec/commit/9468007f269ded90a4df0b853af23587d4ce520c the errors have been displayed in the following format:

<img width="781" alt="screen shot 2016-09-04 at 6 37 22 pm" src="https://cloud.githubusercontent.com/assets/1178413/18232385/f12be39e-72ce-11e6-8c85-e3ee3f2805cc.png">

After the PR #946 the same test does not display the full result set:

<img width="741" alt="screen shot 2016-09-04 at 6 37 47 pm" src="https://cloud.githubusercontent.com/assets/1178413/18232386/f12cc066-72ce-11e6-8866-5b99b0ad5b29.png">

cc @vjeffrey 
### InSpec and Platform Version

This bug has been introduced with InSpec 0.32.0
### Replication Case

```
describe command("echo 'hellp'") do
  its('stdout') { should eq "hello" }
end
```

**Comment by vjeffrey** [comment]
sorry, and thank you for fixing it!
