### ISSUE TITLE
--no-color switch not working when invoked with "inspec exec"

### ISSUE THREAD

**Issue by Constantin07** [inspec/inspec#1024]
### Description

the --color/--no-color switch is not working when invoked with inspec exec.
It outputs in color anyway.
### InSpec and Platform Version

CentOS Linux release 7.2.1511 (Core)

Inspec versions 0.32.0, 0.33.0
### Replication Case

Run:

```
inspec exec test.rb --no-color
```

Result: the printed output in terminal is still colored.
### Possible Solutions

None.
### Stacktrace

None.

**Comment by sarahbakal** [comment]
Use case:
We're attempting to output the audit results from inspec exec to send to our external auditors. sending to text file appends the color tags and makes it difficult to read.
