### ISSUE TITLE
Multiple matchers in a describe block display only a single line

### ISSUE THREAD

**Issue by webframp** [inspec/inspec#1025]
### Description

I'm experimenting with replacing some serverspec test kitchen suites with inspec tests and overall it's great. Very fast and I love the small dsl improvements from inspec over serverspec.

Unfortunately the displayed output is not quite useful enough to include them as the default in our CI process yet. This seems related to #812 so perhaps it's a configuration I'm missing,  fixed in a future version or just my ignorance.

For a simple spec such as:

``` ruby
describe file('/tmp/home_test/.ssh/id_rsa') do
  it { should be_file }
  its('size') { should > 0 }
  its('mode') { should cmp '0600' }
end
```

the output is condensed to a single line:

```
 ✔  File /tmp/home_test/.ssh/id_rsa should be file; File /tmp/ho...
```

but I would expect it to instead display one per line like:

```
✔  File /tmp/home_test/.ssh/id_rsa should be file
✔  File /tmp/home_test/.ssh/id_rsa size should > 0
✔  File /tmp/home_test/.ssh/id_rsa mode should cmp "0600"
```

I can duplicate the describe block many times, using one matcher per describe block to get the desired output, but this seems like needless duplication.
### InSpec and Platform Version

Running on Windows 10, Powershell 5
inspec `0.29.0` from the chef-dk `17.17`
kitchen 1.11.1, kitchen-vagrant (0.20.0), kitchen-inspec (0.15.0)
Testing in an ubuntu 14.04 vm
### Replication Case

Simple test recipe:

``` ruby
file '/tmp/home_test/.ssh/id_rsa' do
  content "fake contents"
  mode '0600'
end
```

matching spec (condensed):

``` ruby
describe file('/tmp/home_test/.ssh/id_rsa') do
  it { should be_file }
  its('size') { should > 0 }
  its('mode') { should cmp '0600' }
end
```

spec (expanded):

``` ruby
describe file('/tmp/home_test/.ssh/id_rsa') do
  it { should be_file }
end

describe file('/tmp/home_test/.ssh/id_rsa') do
  its('size') { should > 0 }
end

describe file('/tmp/home_test/.ssh/id_rsa') do
  its('mode') { should cmp '0600' }
end
```
### Possible Solutions

For now I've kept a single matcher per describe block which provides the output desired, but needlessly duplicates describe blocks
### Stacktrace

none

**Comment by chris-rock** [comment]
@webframp Try to update to the latest InSpec release 0.33.0 since we improved the reporter a lot over the last weeks. Let us know if the issue persists

**Comment by webframp** [comment]
Confirmed, `0.33.0` fixes the output as expected:

```
  File /tmp/home_test/.ssh/id_rsa
     ✔  should be file
     ✔  size should > 0
```

Thanks!

**Comment by chris-rock** [comment]
Perfect @webframp Thanks for using InSpec. Let us know if you have any other issue.
