### ISSUE TITLE
Provide per-profile attribute isolation

### ISSUE THREAD

**Issue by stevendanna** [inspec/inspec#1028]
### Description

We've been moving towards a world in which profiles are isolated from each other based on their position in the dependency tree.  This work has not yet been extended to attributes (although it might be in effect to some extent because controls run in different profile contexts).

We should extend isolation to attributes.  This requires deciding on what the behavior should be for at least the following cases:

```
A
| -> B
| -> C
```

If `B`  and `C` defines attribute `foo` with default `barB` and `barC` respectively, which default should controls in `A` see and which default should be reported in metadata about A.  Currently resources are operating on a "last evaluated wins" basis.  Additionally we need to define what declaring `foo` in `A` would do to the value seen in `B` and `C`.
# Acceptance Criteria
- Functional test that shows the desired behavior for the above cases
- Functional test that shows `B` and `C` in the above case both see their locally-defined default (in absence of any other definition of `foo` in `A`)

**Comment by chris-rock** [comment]
#719

**Comment by clintoncwolfe** [comment]
@jquick can this be closed?

**Comment by jquick** [comment]
Yes attributes are profile specific now as well as their defaults. There is already another ticket to handle the namespace specific values when using an attrs file.
