### ISSUE TITLE
Implement enabled/disabled accounts detection for Unix/Linux

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1040]
### Description
#1039 introduced the mechanisms to test for enabled/disabled accounts.

```
describe user('Administrator') do
  it { should be_disabled }
end
```

This PR only implements that feature for Windows, but does not cover Linux and Unix operating systems.

**Comment by aaronlippold** [comment]
So for unix, this would be checking if the user has /sbin/nologin in /etc/passwd? We should perhaps define what 'disabled' means vs 'not_exist' or not be_enabled etc etc.

**Comment by miah** [comment]
This is tricky on UNIX. We'll have to consult the `passwd` and the `shadow` files to make this observation. We'll also have to note that this is limited to accounts active on the local system and does not include authentication services like 'AD', 'ldap', 'nis', or 'kerberos' unless we go the full [NSS](https://en.wikipedia.org/wiki/Name_Service_Switch) route.

A user is "disabled" if:
 - It has a invalid login shell 
(e.g., shell is not listed in `/etc/shells`, or is set to `/(s)bin/nologin`, `/bin/false`.)
 - It has a disabled password in `passwd`
(e.g., it is not blank, is not a string, is a single character 'x', '*', '!')
 - It has a disabled password in `shadow`
(e.g., it is not blank, is not a string, is a single character 'x', '*', '!')
 - Its password has expired through age
 - The account has expired

And a final caveat, I believe, that an account could still be 'enabled' if it has no password set, has a valid shell, and sshd is configured to authenticate users via authorized_keys and not password.

**Comment by clintoncwolfe** [comment]
My 2¢: we implemented a "federated matcher" on `aws_s3_buckert#be_public` - being clear about limitations. I think we could do that here as well.
