### ISSUE TITLE
Improve InSpec tutorial

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1045]
### Description

The current tutorial misses some details:
- [x] `clear` (linux) and `cls` (windows) command to clear the terminal
- [x] proper scrolling of terminal
- [x] style of tutorial text looks a little bit off
- [x] sometimes the shell promp is off, i can remove content of the prompt with my back key
- [x] continue to remove keys if i keep holding the back key
- [x] we need to harmonize the recording terminal size = playing terminal size
- [x] copy & paste content

**Comment by chris-rock** [comment]
The left side of the terminal is strage. Looks like the `$` is prepended with a whitespace
<img width="423" alt="screen shot 2016-09-12 at 3 15 59 pm" src="https://cloud.githubusercontent.com/assets/1178413/18437193/0014b4e8-78fc-11e6-9cfd-77605fcf90a7.png">

If I switch between `prev` and `next` I may not be able to see the command prompt anymore.
<img width="926" alt="screen shot 2016-09-12 at 3 16 27 pm" src="https://cloud.githubusercontent.com/assets/1178413/18437218/1ecb633c-78fc-11e6-9ec9-9d2976edc274.png">

**Comment by vjeffrey** [comment]
from davida (I asked her to test it out): 
- [ ]  "[in the instructions] i would expect `inspec exec examples/profile` to have a `$` in front of it to indicate it’s a command to be typed at the prompt
  ie, `$ inspec exec examples/profile`
- [x] automatically clear screen on `next`
- [ ]  "hmm also possibly keep the navigation commands up in the top part of the screen" (next/prev)
- [ ]  copy/paste
- [x]  she got stuck in the inspec shell/it was hanging
- [x]  typescript console errors
- [ ]  use left arrow and right arrow to go back/forth through characters
