### ISSUE TITLE
www: Online tutorial: safari inspec online demo bug!

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1086]

**Comment by vjeffrey** [comment]
'const declarations are not supported in strict mode'
apparently, safari doesn't understand things. silly safari.
babel should help with this.

**Comment by vjeffrey** [comment]
with babel loader and babel preset es2015, I set the webpack config to have:

```
            {
             test: /\.js$/,
             loader: 'babel',
             query: {
                presets: ['es2015']
             }
            }
```

in the `module { loaders: [` 

Builds fine in chrome/firefox, but doesn't seem to be translating the const into var as expected with babel, so still same problem in safari.

I'll keep on digging into it/trying...

**Comment by vjeffrey** [comment]
this is the branch: dr/www/es-const  haven't figured it out yet. still trying..

**Comment by vjeffrey** [comment]
https://github.com/chef/inspec/tree/vj/babelify-scripts  <-- doing babel in gulpfile works to get rid of the const...but things are still not building correctly :(
