### ISSUE TITLE
undefined method `send_request' for Compliance::API:Class

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#1088]
### Description

When attempting a legacy login I get an error that there is no `send_request` method. 
It looks like that method disappeared here: https://github.com/chef/inspec/commit/07c359431f2e803a3220b14accc42ddb4d154312

```
~/Devel/ChefProject/compliance-profiles$ inspec compliance login https://compliance-server.test --insecure --user='localadmin' --password='insecurepassword'
/Users/jmiller/.chefdk/gem/ruby/2.1.0/gems/inspec-0.35.0/lib/bundles/inspec-compliance/api.rb:21:in `legacy_login_post': undefined method `send_request' for Compliance::API:Class (NoMethodError)
    from /Users/jmiller/.chefdk/gem/ruby/2.1.0/gems/inspec-0.35.0/lib/bundles/inspec-compliance/cli.rb:217:in `login_legacy'
    from /Users/jmiller/.chefdk/gem/ruby/2.1.0/gems/inspec-0.35.0/lib/bundles/inspec-compliance/cli.rb:41:in `login'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/jmiller/.chefdk/gem/ruby/2.1.0/gems/inspec-0.35.0/bin/inspec:12:in `<top (required)>'
    from /opt/chefdk/embedded/bin/inspec:22:in `load'
    from /opt/chefdk/embedded/bin/inspec:22:in `<main>'
~/Devel/ChefProject/compliance-profiles$
```
### InSpec and Platform Version

```
~/Devel/ChefProject/compliance-profiles$ inspec version
0.35.0
~/Devel/ChefProject/compliance-profiles$ uname -a
Darwin jm01.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
~/Devel/ChefProject/compliance-profiles$
```
### Replication Case

Attempt to use `inspec` cli to login with a user/password:
`inspec compliance login https://compliance-server.test --insecure --user='user' --password='pass'`

**Comment by jeremymv2** [comment]
I understand that this might be the "legacy" method of authenticating.  However, token authentication, as I understand it, can be problematic.  For example, if a Compliance UI session logout occurs, the associated `refresh_token` is invalidated.  On the other hand the `token` is short lived (12 hours), so in a build cookbook scenario where the expectation is not to have to be required to have a user session logged in the Compliance Server, this legacy login option should be left in place as a last resort method of acquiring an access token.   `password` could be stored in environment, or vault of some sort.

**Comment by alexpop** [comment]
Thanks for the report Jeremy. I bumped into this as well and my workaround has been to copy tokens from the UI into the shell.

I'll open a PR to replace the legacy login implementation.
