### ISSUE TITLE
kernel_parameter does not show fully info when test fails

### ISSUE THREAD

**Issue by nvtkaszpir** [inspec/inspec#1093]
### Description

When using `kernel_parameter` in the test and it fails then the message is missing detailed explanation what actually failed  - unless you have insanely detailed tests.
### InSpec and Platform Version

Tinspec 0.32.0
ubuntu 15.10 testing remotely on 14.04
### Replication Case

``` ruby

title 'test kernel_parameter'

control 'test-kernel_parameter-999' do
  impact 1.0
  title 'verify certain settings in sysctl'
  desc 'tuning system/kernel'

  describe kernel_parameter('net.core.somaxconn') do
    its('value') { should be >= 18419238472 } # this should fail some random insane value to make it invalid
  end
  describe kernel_parameter('net.core.somaxconn') do
    its('value') { should be > 100 } # this should pass
  end
end

```

output:

``` bash
  ✖  test-kernel_parameter-999: verify certain settings in sysctl (1 failed)
     ✖  expected: >= 18419238472
          got:    128
     ✔  Kernel Parameter net.core.somaxconn value should be > 100

```

As we can see:
- first one fails, but does not say that it refers to `net.core.somaxconn`
- second test shows that `net.core.somaxconn` is valid.
### Possible Solutions

Verify that `kernel_parameter actually` shows full output when it fails.

Expected output something like this:

``` bash
  ✖  test-kernel_parameter-999: verify certain settings in sysctl (1 failed)
     ✖  expected: net.core.somaxconn >= 18419238472
          got:    128
     ✔  Kernel Parameter net.core.somaxconn value should be > 100

```
### Stacktrace

No stacktrace.

**Comment by chris-rock** [comment]
@nvtkaszpir that is a very good recommendation for improvement
