### ISSUE TITLE
InSpec in Visibility

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1117]
We need this https://github.com/chef-cookbooks/audit/issues/98 and the update to Visibility to still work.

**Comment by vjeffrey** [comment]
https://github.com/chef-cookbooks/audit/pull/99
https://delivery.shd.chef.co/e/Chef/#/organizations/Chef_Delivery/projects/delivery/changes/93fe5e4f-107a-4176-aaa6-0290eb9369ba/status/verify

**Comment by vjeffrey** [comment]
shd/visibility change has merged. as soon as 1.0 is released, i'll update version in audit cookbook and we can merge that too
