### ISSUE TITLE
README.md has broken link to non-existent file

### ISSUE THREAD

**Issue by rhass** [inspec/inspec#1136]
### Description

README.md has broken link to non-existent file: `InSpec makes it easy to run your tests wherever you need. More options listed here: https://github.com/chef/inspec/blob/master/docs/cli.rst` 

https://github.com/chef/inspec/search?utf8=%E2%9C%93&q=filename%3Acli.rst&type=Code
### InSpec and Platform Version

Github Master
### Replication Case

Click the link in the documentation.
### Possible Solutions

Remove or update link with the correct URI.
### Stacktrace

Not applicable.

**Comment by arlimus** [comment]
Thank you for quickly noticing!! Sorry for the inconvenience, we will have this sorted out until the website goes life (at the latest on Monday)
