### ISSUE TITLE
www: Online tutorial: update inspec tutorial to 1.0.0 version

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#1169]
It would be cool if we could update the responses so it says 1.0.0 instead of 1.0.0 beta. it's a little thing, but would be nice :)
![screen shot 2016-09-26 at 12 18 54 pm](https://cloud.githubusercontent.com/assets/10341541/18842605/8ed1cc38-83e3-11e6-92e5-8e66f504b5ff.png)

when you do inspec exec examples/profile, you see version 1.0.0 
![screen shot 2016-09-26 at 12 20 49 pm](https://cloud.githubusercontent.com/assets/10341541/18842652/c53eb416-83e3-11e6-9eba-5fcad3619d9f.png)

**Comment by chris-rock** [comment]
This is blocked by the approval of https://github.com/chef/inspec/pull/1159, @arlimus was trying to identify the issue with git not detecting the changes properly

**Comment by chris-rock** [comment]
The current approach generates files that will generate long filenames that are not supported on Windows
