### ISSUE TITLE
inspec cannot autodetect service() infrastructure on ubuntu-14

### ISSUE THREAD

**Issue by stefanandres** [inspec/inspec#1171]
## Description

```
describe service('exim4') do
  it { should be_running }
```

Fails with

```
  Service exim4
     ✖  should be running
     expected that `Service exim4` is running
```

But sysv_service('exim4') works

```
  Service exim4
     ✔  should be running
```
## Inspec Version

```
# gem2.0 list|grep inspec
inspec (1.0.0)
```
## Platform Version

Ubuntu-14

```
root@0e1460d981ab:/tmp/kitchen/manifests/default/inspec# facter|grep -i lsb
lsbdistcodename => trusty
lsbdistdescription => Ubuntu 14.04.5 LTS
lsbdistid => Ubuntu
lsbdistrelease => 14.04
lsbmajdistrelease => 14.04
os => {"name"=>"Ubuntu", "family"=>"Debian", "release"=>{"major"=>"14.04", "full"=>"14.04"}, "lsb"=>{"distcodename"=>"trusty", "distid"=>"Ubuntu", "distdescription"=>"Ubuntu 14.04.5 LTS", "distrelease"=>"14.04", "majdistrelease"=>"14.04"}}
root@0e1460d981ab:/tmp/kitchen/manifests/default/inspec# facter|grep -i docker
virtual => docker
root@0e1460d981ab:/tmp/kitchen/manifests/default/inspec#
```
## Replication Case

See above

How can I write a inspec test that covers ubuntu-14 sysv and ubuntu-16 systemd?

**Comment by stefanandres** [comment]
Hm, it also does not work with ubuntu-16. service() fails, like systemd_service() does. exim installed by apt-get install exim4 can only be detected via sysv_service() there too.

**Comment by nvtkaszpir** [comment]
Try outsude of docker?

**Comment by stefanandres** [comment]
On "native" (qemu instance) it seems to work.

```
root@inspec:/home/ubuntu# inspec exec exim_spec.rb

Target:  local://


  Service exim4
     ✔  should be running

Test Summary: 1 successful, 0 failures, 0 skipped
root@inspec:/home/ubuntu# cat exim_spec.rb
describe service('exim4') do
  it { should be_running }
end
root@inspec:/home/ubuntu#
```

What could be the reason?

**Comment by nvtkaszpir** [comment]
Of course docker, because the way the apps are launched there. Unfortunately you cannot treat everything the same. There are varous minor issues among platforms anyway. But with docker things are really ran differently. Not to mention that systemd + docker = long sad story.

It is possible to fix that, but actually inspec should detect underlying platform and then know how to handle services run witin them. Or at least give methods to handle that.

Currently I have various only_if statements to run tests which apply only to spevific platform, for example AWS, libvirt or LXC.

**Comment by chris-rock** [comment]
@nvtkaszpir Could you share your virtualization detection in https://github.com/chef/inspec/issues/1005?

**Comment by nvtkaszpir** [comment]
Already answered. I'm using third party tool named virt-what, which was designed specifically for this purpose for linux platform (although AFAIR it is possible to run it under Windows).

Unfortunately it means that this package must be installed on remote system.

**Comment by clintoncwolfe** [comment]
I"m closing this as Ubuntu 14 is EOL.
