### ISSUE TITLE
www: Online tutorial doesn't load (not building)

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1182]
This occured for some builds on certain machines that don't have all the required modules installed (e.g. NodeJS).

Please make sure:
- [x] Fail the build process if any shell command fails (e.g. `npm install`)
- [x] Add sanity checks for build steps of: tutorial, docs, and www/middleman

**Comment by vjeffrey** [comment]
should be ready @arlimus - let me know if it needs more

**Comment by chris-rock** [comment]
Do we want to use a docker based build? eg. via https://hub.docker.com/_/node/

**Comment by arlimus** [comment]
@chris-rock That might be a great alternative. Instead of requiring node/npm we could just require docker, since it's a prerequisite for our tests anyway. I like the idea :)
