### ISSUE TITLE
Online tutorial: weird behavior with backspace, invalid commands

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#1184]
As reported by @jerryaldrichiii 
<img width="940" alt="screen shot 2016-09-28 at 11 08 35 am" src="https://cloud.githubusercontent.com/assets/10341541/18919396/f7c902ae-856b-11e6-80a9-be8b03800863.png">

**Comment by vjeffrey** [comment]
this bug is killer. it's nutty. makes no sense!

**Comment by jerryaldrichiii** [comment]
You got that right @vjeffrey!

That's why I brought it up internally...I would sound like a mad man if I brought it up here.

The rabbit hole goes deep I am sure. Best I can tell it has to do with not stripping a `\r` somewhere.

For example, in Ruby:

``` ruby
[1] pry(main)> puts "foo bar baz";
foo bar baz
[2] pry(main)> puts "foo bar baz\rspam";
spambar baz
```
