### ISSUE TITLE
inspec.io ---> https

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#1189]
inspec.io does not currently support https (invalid cert).

This is because we are using a custom domain: github pages supports https as long as you are not using a custom domain (thanks to @srenatus for pointing that out!!) 

https://help.github.com/articles/securing-your-github-pages-site-with-https/
https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by arlimus** [comment]
Thank you for investigating :)

We want to stick to the inspec.io domain. The github domain for our current project would be chef.github.io/inspec which feels clumsy; the shorter inspec.github.io is possible as well, if we move the project to this group; I'm not sure if we should change github groups right now, unless we find more reasons (e.g. child projects which we want to group together).

The best way to get https for inspec.io would be to build to an extrnal host. Let's investigate this route.

**Comment by artem-sidorenko** [comment]
@arlimus there is another option as well: [gitlab pages](https://pages.gitlab.io/)

However this has the same question like you already raised, maybe even with more complications

**Comment by arlimus** [comment]
We have talked internally; We will be moving to HTTPS and will check if we set up our own buckets for hosting the site or manage to keep it here github. We'll talk to some friends at our SSL provider and see what what the next steps are.

**Comment by chris-rock** [comment]
done with https://www.inspec.io/ now
