### ISSUE TITLE
Resources on `http://inspec.io/docs/reference/resources/` are not in alphabetical order

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#1195]
### Description

Resources on `http://inspec.io/docs/reference/resources/` are not in alphabetical order. I've seen them in alphabetically order before so this may be an intermittent issue.
### Example

<img width="1439" alt="screen shot 2016-10-02 at 12 17 24 pm" src="https://cloud.githubusercontent.com/assets/13783510/19021933/95722ed2-889a-11e6-83c3-d2018673e8c0.png">

**Comment by PaulusTM** [comment]
It seems fixed already:

Firefox
<img width="1440" alt="screen shot 2016-10-06 at 15 45 00" src="https://cloud.githubusercontent.com/assets/85584/19154685/de6ab2f0-8bdb-11e6-8387-287607747036.png">

Chrome
<img width="1440" alt="screen shot 2016-10-06 at 15 46 44" src="https://cloud.githubusercontent.com/assets/85584/19154755/1f1b03ae-8bdc-11e6-9bf2-826bc60a30f4.png">

**Comment by jerryaldrichiii** [comment]
Yup, I've seen it bounce between sorted and not sorted before though.

I'll close the issue and reopen it if I see it again.
