### ISSUE TITLE
www: typo on inspec.io

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#1197]
<img width="1004" alt="screen shot 2016-10-04 at 4 57 35 pm" src="https://cloud.githubusercontent.com/assets/10341541/19092212/aff9104e-8a53-11e6-8a85-7771d508bd43.png">

**Comment by PaulusTM** [comment]
I noticed its a image file `/images/home/code-1.svg`.
Perhaps its a good idea to remove the image and change it to code?

**Comment by vjeffrey** [comment]
Andy and the CIA team are on it!

**Comment by vjeffrey** [comment]
https://chefio.atlassian.net/browse/CIA-1138

**Comment by vjeffrey** [comment]
https://github.com/chef/inspec/pull/1210
