### ISSUE TITLE
Some inconsistencies with naming across the resources

### ISSUE THREAD

**Issue by jamescott** [inspec/inspec#120]
# Configuration File Resources

Some of the resources have a `name` that includes `_config` (spelled out), whereas others are shortened to just `_conf`. 

Ones that have `_config`:

inetd_config << suggest inetd_conf
parse_config
parse_config_file
ssh_config
sshd_config

_conf:
apache_conf
audit_daemon_conf << suggest auditd_conf
limits_conf
mysql_conf
ntp_conf
postgres_conf

Only two of them are truly inconsistent, with `inetd_config` and `audit_daemon_conf` not having a name directly similar to the actual filename, like `ntp_conf` and the other `_conf` resources. Naming suggestions listed above.
# parse_config options
- suggest renaming `assignment_re` => `assign_regex` << no more guessing as to what `_re` might mean
- suggest renaming `key_vals` => `key_values` (to be consistent with `multiple_values` and to preserve the highest level of human readability)
# Miscellaneous (these are not as important)
- The name of the `login_def` (file name) resource is `login_defs` (resource name) << can both be the same (plural)? This suggestion changes the resource filename to login_defs.rb
- The name of the `processes` resource << can it be shortened to just `process`? It also seems that one can test just a single "process"
- There is an `/etc/group` => `etc_group` resource, there is an `/etc/passwd` => `passwd` resource ... could the `passwd` resource be named `etc_passwd`? (Note that I see why it's `etc_group`, specifically, so as to not conflict with the group resource.)

**Comment by jamescott** [comment]
Also add to potential resource renaming:

audit_daemon_rules => auditd_rules

I noticed also that the auditd_rules resource has the assignment_re matcher, suggest same rename => assign_regex

**Comment by chris-rock** [comment]
`auditd_rules`, `inetd_conf` and `auditd_conf` are done

**Comment by arlimus** [comment]
@jamescott Thank you for all your early feedback on this!
afaics our current resources are now consistent.

I also like the points you raised about `parse_config` options, let's open that as a separate issue.

**Comment by arlimus** [comment]
Referenced option names in https://github.com/chef/inspec/issues/1709
