### ISSUE TITLE
Unable to view Demo on any page other than Overview

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#1207]
### Description

Both on Firefox and Chrome I am unable to "Try the Demo" on any page other than the Overview page
### Replication Case

Navigate to any links on the side bar (save for Overview) and click "Try the Demo"

**Comment by vjeffrey** [comment]
related to #1166

**Comment by jerryaldrichiii** [comment]
This is no longer an issue :smile:
