### ISSUE TITLE
Listing profiles on the Supermarket should return all profiles

### ISSUE THREAD

**Issue by robbkidd** [inspec/inspec#1219]
### Description

`inspec supermarket profiles` currently [uses the only query parameter](https://github.com/chef/inspec/blob/725e0a1bc50008c8ad252bd8d5c833a7af20c606/lib/bundles/inspec-supermarket/api.rb#L15) the Supermarket tools API offers at the moment: `q=`. Sadly, this means that the returned list of profiles is limited to the number of _tools_ that mention the words "compliance profile" in their descriptions. So users are not seeing a complete list of profiles available.
### InSpec and Platform Version

```
> inspec version
1.0.0
```

Supermarket version 2.8.27.
### Replication Case

```
> inspec supermarket profiles
== Available profiles:

 * nathenharvey/tmp-compliance-profile
 * sliim/chef-client-hardening
 * dev-sec/cis-docker-benchmark
 * dev-sec/nginx-hardening
 * hardening/os-hardening
 * hardening/ssh-hardening
```

Note, this is not a [complete list of compliance profiles currently on the Supermarket](https://supermarket.chef.io/tools?type=compliance_profile) (10 at the time of this writing). These profiles appear because they contain the words "compliance profile" in their descriptions.
### Possible Solutions

After a fix for chef/supermarket#1454 is released, [the request parameters for the search](https://github.com/chef/inspec/blob/725e0a1bc50008c8ad252bd8d5c833a7af20c606/lib/bundles/inspec-supermarket/api.rb#L15) in `inspec supermarket` can be updated. Pending the Supermarket release, the params will probably look like:

``` diff
def self.profiles(supermarket_url = SUPERMARKET_URL)
      url = "#{supermarket_url}/api/v1/tools-search"
-       _success, data = get(url, { q: 'compliance_profile' })
+       _success, data = get(url, { type: 'compliance_profile' })
      if !data.nil?
```

**Comment by alexpop** [comment]
Robb, ok to close this issue based on merged PR https://github.com/chef/inspec/pull/1254 and issue https://github.com/chef/inspec/issues/1255 ?

**Comment by robbkidd** [comment]
Tuning back in after Summit, my opinion is that this issue is _not_ fixed. My understanding of PR #1254 is that the results will be whichever compliance profiles that appear in the latest 100 tools updated in a Supermarket. That might yield happy-enough results today, but I don't think it correctly or fully addresses the issue described here.
