### ISSUE TITLE
Move InSpec Community to https://community-slack.chef.io/

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1222]
We've been using Gitter as the main community channel for InSpec. We really liked Gitter and it was very helpful for us. To ease the interaction with the Chef ecosystem (Chef, Habitat & InSpec) we are going to harmonize our customer interactions. Therefore we migrate from Gitter to https://community-slack.chef.io/

The following steps:
- [x] Create InSpec community in Chef Community Slack
- [x] Add documentation on our inspec.io page, reference to https://community-slack.chef.io/
- [x] Add slack button to Github page
- [x] Remove Gitter badge 
- [x] Announce the migration in Gitter channel

**Comment by arlimus** [comment]
The inspec.io page links to community currently; are you looking for something more specific in the second subtask?

**Comment by chris-rock** [comment]
That looks great, second task is done then.

**Comment by The-Alchemist** [comment]
I was trying to join the Chef Slack community, but it looks like it's invite-only.  The 'Contact Us' link at the bottom of the Slack page (https://chefcommunity.slack.com/help/contact) just directs to the login page.

Only `@progress.com` and `@chef.io` email addresses can sign-in automatically without an invite.

Is there a contact?  Thanks!
