### ISSUE TITLE
Link to robert_config.rb is broken on inspec.io

### ISSUE THREAD

**Issue by chris-redekop** [inspec/inspec#1226]
### Description

The example resource, http://inspec.io/docs/reference/examples/profile/libraries/gordon_config.rb, pointed to by http://inspec.io/docs/reference/dsl_resource/ , cannot be found.

**Comment by chris-rock** [comment]
Thanks, the correct URL is https://github.com/chef/inspec/blob/master/examples/profile/libraries/gordon_config.rb

**Comment by martinisoft** [comment]
Was just about to report this 👍

**Comment by martinisoft** [comment]
Is there any way I can help with fixing the link? I can see a gh-pages branch but not sure how I can contribute to that.

**Comment by chris-rock** [comment]
we always generate gh-pages. We source content from `docs` and `web` directory. In this case its located here: https://github.com/chef/inspec/blob/f7b85c047f8ea5fcde759860da1dae3e04c3dbb4/docs/dsl_resource.md
