### ISSUE TITLE
When testing 'command' resource, runner outputs anything after a space with the assertions

### ISSUE THREAD

**Issue by davidcpell** [inspec/inspec#1234]
### Description

I have a test that looks like this:

``` ruby
describe command('/opt/McAfee/agent/bin/masvc status') do
  its('exit_status') { should eq 0 }
  its('stderr') { should match /Process is running/ }
end
```

When I run the tests, the output looks like this:

```
  Command /opt/McAfee/agent/bin/masvc
     ✔  status exit_status should eq 0
     ✔  status stderr should match /Process is running/
```

Note that the final word in the command string (`status`) gets cut off from the title line and placed at the beginning of the actual test assertion.

Is this intended? I would've expected this:

```
  Command /opt/McAfee/agent/bin/masvc service
     ✔  exit_status should eq 0
     ✔  stderr should match /Process is running/
```

...perhaps with quotation marks at the beginning and end. Notice the same behavior when testing `echo`:

``` ruby
describe command('echo hello world') do
  its('exit_status') { should eq 0 }
end
```

```
  Command echo
     ✔  hello world exit_status should eq 0
```
### InSpec and Platform Version

InSpec 0.35.0
Windows 7 Enterprise
### Replication Case
1. Start a new cookbook 
2. Add an InSpec test with a command that has a space somewhere in it

**Comment by chris-rock** [comment]
Thanks @davidcpell we are working on improved reporting and rewrite the current CLI reported being based on our json output. This will fix it! It may take some weeks to roll that in

**Comment by jeremymv2** [comment]
I noticed the same for file testing when there's a space in the path, for instance: 'File C:/Program Files/foo/baz'

**Comment by clintoncwolfe** [comment]
related #4043

**Comment by Vasu1105** [comment]
I am closing this @clintoncwolfe I don't see this behaviour in latest InSpec
here is the output for echo
```
describe command('echo hello world') do
  its('exit_status') { should eq 0 }
end
````

```
  Command: `echo hello world`
     ✔  exit_status is expected to eq 0
```
