### ISSUE TITLE
warn when overriding a core resource

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1235]
If users write custom profiles, they may overwrite core resources. Resources are scoped now, but it may lead to unexpected behavior. Therefore we should warn users if they decide to use the same name as a core resource e.g.

```
describe service({datacenter: 'ha-datacenter', host: 'localhost'}) do
...
end
```

**Comment by clintoncwolfe** [comment]
We do warn, at runtime and in check:
https://github.com/inspec/inspec/blob/9cbd7c395f80a17ddc4098a20dd85864f3a1cfb5/lib/inspec/plugin/v1/plugin_types/resource.rb#L153
