### ISSUE TITLE
Run profiles from private supermarket

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1236]
We support private supermarket in profile dependencies via `inspec.yml`:

```
depends
  - name: hardening/ssh-hardening 
    supermarket_url: https://supermarket.my.com
```

The issue is we cannot call those profiles from `inspec exec` directly.

**Option 1:**

```
# store the server in .inspec/supermarket/config
$ inspec supermarket login SERVER
# retrieves profiles from private supermarket
$ inspec supermarket profiles
# run from private supermarket
$ inspec exec supermarket://myprofile
```

Con: cannot mix public and private supermarket profiles

**Option 2:**

```
$ inspec supermarket profiles --supermarket-url SERVER
$ inspec exec supermarket://myprofile --supermarket-url SERVER
```

Aha! Link: https://chef.aha.io/features/SH-2197

**Comment by chris-rock** [comment]
cc @jeremymv2

**Comment by stevendanna** [comment]
Maybe combine option 1 and option 2?  i.e. Use command line options if they are given, followed by  `.inspec/supermarket/config` if it exists, followed by public supermarket default.

**Comment by chris-rock** [comment]
It feels like we are addressing a similar problem as in https://github.com/chef/inspec/issues/1237 If we threat Supermarket server a profile location, and we run a profile, could use:

```
inspec exec -l SUPERMARKET_SERVER myprofile1 
```

This would also allow us to do the following:

```
inspec exec -l SUPERMARKET_SERVER -l PRIVATE_SUPERMARKET_SERVER myprofile1 profile2 
```

**Comment by chris-rock** [comment]
Or we use a run-list like approach with `inspec exec run.yml`

The `run.yml` could look like the following:

```
run
  - name: hardening/ssh-hardening 
    supermarket_url: https://supermarket.my.com
```

**Comment by jeremymv2** [comment]
I think that is in the same spirit as `Berksfile` for Chef cookbooks that is really simple and works well:

Format:

```
cookbook {name}, {version_constraint}, {options}
```

Examples:

```
cookbook "nginx", ">= 0.101.2"
cookbook "artifact", path: "/Users/reset/code/artifact-cookbook"
cookbook "mysql", git: "https://github.com/opscode-cookbooks/mysql.git", branch: "foodcritic"
cookbook "artifact", github: "RiotGames/artifact-cookbook", tag: "0.9.8"
cookbook "keeping_secrets", github: "RiotGames/keeping_secrets-cookbook", protocol: :ssh
```

Adapting for inspec becomes a matter of enumerating all the key words for sources and their various options. `.yml` is probably easier to consume though..

**Comment by chris-rock** [comment]
An idea from @arlimus 
`inspec exec hardening/ssh-hardening -o supermarket_url=https://supermarket.my.com hardening/os-hardening -o supermarket_url=https://supermarket2.my.com`

**Comment by jcarapet** [comment]
+1 on this feature. I have been looking for an easy option to run profiles from private supermarket outside of our test-kitchen suite. Secondary enhancement would be to have `inspec supermarket upload profile_name` an option, but probably better served when separating out plugngs.

**Comment by rylarson** [comment]
@jcarapet Can you explain how you are able to run profiles from private supermarket inside of test kitchen?

**Comment by mhedgpeth** [comment]
+1 on this feature; this would really help us

**Comment by jcarapet** [comment]
@rylarson we actually never did. Kept having trouble recognizing the git tags. What we ended up doing was writing build job to tarball profiles, and upload to a remote repo. Now just reference the tarballs in inspec.yml as dependencies. If you want more info, happy to talk, but don't want to pollute this issue.

**Comment by rylarson** [comment]
@jcarapet I think `kitchen-inspec` will work fine if the inspec folks merge this pull request:

https://github.com/chef/inspec/pull/1595

Part of the InSpec Supermarket API client class was broken and unconditionally looked for profiles on public supermarket only.

**Comment by walterdolce** [comment]
I'm very much looking forward to this. At the moment the following works only for public InSpec profile repositories:
```
inspec exec https://github.com/{{username_or_org}}/{{private_inspec_profile_repo}} -t docker://{{docker_container_id}} 
```

**Comment by Stromweld** [comment]
hoping to reopen this as I believe it is a good example of usin g private supermarket for inspec profiles.

**Comment by clintoncwolfe** [comment]
Why not simply this:
```
inspec exec supermarket://mysupermarket.mydomain.com/myprofile 
```
