### ISSUE TITLE
Inspec check/archive fails with controls using File.read

### ISSUE THREAD

**Issue by jburandt** [inspec/inspec#1238]
**### Description**

I'm writing a control that will read the contents of a file and verify that the only strings that are listed in there are the ones I am checking for using File.read, and that will determine the pass/fail of the test. 

However, when I run inspec check against it, the check fails because I need root privilege to be able to read the file. Due to the nature of inspec check should it be required that the necessary files are there and readable to pass a check, even if I am not performing an actual test? 

I seem to have a similar issue with files that do not exist, getting a nil value for where a tested file should be. Here is my code below:

```
control 'auth-1.0' do
  impact 0.5
  title 'Remote Root Login'
  desc "disallow remote root login or allow only without password"

  FILE = file('/etc/securetty')
  describe FILE do
    it { should exist }
  end
  existing = Set.new(File.read("/etc/securetty").split("\n").map(&:strip)) # array of file's lines with whitespace stripped
  required = Set.new(%w(console tty1 tty2 tty3 tty4 tty5 tty6)) # lines that should be in the file
  describe (required <= existing) do # all required entries must be in file
    it { should eq true }
  end
  (existing - required).each do |line| # for each stripped line in the file that's not required...
    describe (line.empty? || line.start_with?('#')) do # it should be empty or a comment
      it { should eq true }
    end
  end
end
```

**### InSpec and Platform Version**

0.34.1

**### Replication Case**

Running the code above.

**### Possible Solutions**

Perhaps there is a way to do this using the file resource. 

**### Stacktrace**

Please include the stacktrace output or link to a gist of it, if there is one.

rhel6-standard-audit/controls/auth.rb:18:in `read': Permission denied @ rb_sysopen - /etc/securetty (Errno::EACCES)
from rhel6-standard-audit/controls/auth.rb:18:in`block in load_with_context'
from /home/jordan/.chefdk/gem/ruby/2.1.0/gems/inspec-0.34.1/lib/inspec/rule.rb:33:in `instance_eval'

**Comment by chris-rock** [comment]
@jburandt Thanks for the issue. We recommend not to use local ruby File method, because that prevents InSpec from running that profile remotely.

During the inspec check call, we load the ruby file an evaluate the script in order to read all controls. In cases where you use plain ruby instead of InSpec resources, this code will be executed, which happens in your case. To prevent this behavior, you could use the following instead:

```
control 'auth-1.0' do
  impact 0.5
  title 'Remote Root Login'
  desc "disallow remote root login or allow only without password"

  securetty = file('/etc/securetty')
  describe securetty do
    it { should exist }
  end

  existing = Set.new(securetty.content.split("\n").map(&:strip)) # array of file's lines with whitespace stripped
  required = Set.new(%w(console tty1 tty2 tty3 tty4 tty5 tty6)) # lines that should be in the file

  # all required entries must be in file
  describe (required <= existing) do
    it { should eq true }
  end

  (existing - required).each do |line| # for each stripped line in the file that's not required...
    describe (line.empty? || line.start_with?('#')) do # it should be empty or a comment
      it { should eq true }
    end
  end
end
```

This will not touch the file. In order to improve the readability of the test results and the expected results, I would propose to use:

```
control 'auth-1.0' do
  impact 0.5
  title 'Remote Root Login'
  desc "disallow remote root login or allow only without password"

  securetty = file('/etc/securetty')
  describe securetty do
    it { should exist }
  end

  existing = parse_config(securetty.content).params.keys
  required = %w(console tty1 tty2 tty3 tty4 tty5 tty6)

  # all required entries must be in securetty config
  describe existing do
    required.each { |item|
      it { should include item }
    }
  end

  # display all not required entries
  describe existing - required do
    it { should eq [] }
  end
end

```

**Comment by chris-rock** [comment]
@jburandt anything else we can help with?

**Comment by jburandt** [comment]
I think that will do it, thank you for the insight.
