### ISSUE TITLE
Cannot deploy website

### ISSUE THREAD

**Issue by ryankeairns** [inspec/inspec#1249]
### Description

After making a small change to the inspec.io webiste, I was unable to complete the 'Releasing' step in the README.
### Replication Case

When I run the `bundle exec rake www` command I see the following error:

![screenshot 2016-10-25 16 06 18](https://cloud.githubusercontent.com/assets/446285/19704383/0b99abdc-9acd-11e6-86f6-57cf49d719e9.png)

Side note: it is not clear which directory to run the bundle commands from (I had presumed /www since that is where the site and README are located, but it should be the repo root)

**Comment by chris-rock** [comment]
At this point, you need to checkout the gh-pages branch before the execution:

```
➜  inspec git:(master) git checkout gh-pages
Branch gh-pages set up to track remote branch gh-pages from origin.
Switched to a new branch 'gh-pages'
➜  inspec git:(gh-pages) ✗ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
➜  inspec git:(master) bundle exec rake www 
```

The rake script needs to be executed from root directory.

**Comment by chris-rock** [comment]
@ryankeairns I pushed the latest update

**Comment by clintoncwolfe** [comment]
Closing as stale
