### ISSUE TITLE
Passing attributes to inherited profiles

### ISSUE THREAD

**Issue by vikatgithub** [inspec/inspec#1250]
### Description

I am using a 2 level hierarchy of profiles. I pass a attributes yml file to the top level profile. 

inspec exec [profile path] --attrs [attrib file path]

But these attributes are not visible in the inherited profile.

Is there any other setting besides 'depends' section in inspec.yml that is required for this to work?
### InSpec and Platform Version

InSpec 1.0

**Comment by gsaslis** [comment]
+1

**Comment by chris-rock** [comment]
I can confirm that issue. You are doing everything right. This is an issue in InSpec

**Comment by vikatgithub** [comment]
Thanks @chris-rock.
