### ISSUE TITLE
Using arrays as expected values

### ISSUE THREAD

**Issue by vikatgithub** [inspec/inspec#1251]
### Description

I have a profile to check a config file with groups and users in this format:

```
Group1:"Description"
  User1
  User2
```

By using custom assignment_re and group_re, I can do a check like this:

```
its ("Group1") { should include "User1" }
```

But this not precludes a 'User3' from being there in Group1. What is desired is a way to compare the entire list so that any unwanted users are flagged as failure. Something like:

```
its("Group1") { should be_subset_of  ["User1", "User2"] }
```

Is there a way to achive this?
### InSpec and Platform Version

InSpec 1.0

**Comment by chris-rock** [comment]
@vikatgithub Could you share a sample of the source file? I assume you use `parse_config`? Have you tried the `multiple_values: true`?

```
options = {
  assignment_re: /^\s*([^:]*?)\s*:\s*(.*?)\s*$/,
  multiple_values: true
}
```

**Comment by vikatgithub** [comment]
@chris-rock I have implemented a sample profile with a custom matcher 'be_subset_of' to compare two lists: https://github.com/vikatgithub/inspec.examples

I need this matcher in several of my profiles. What is the best way to share it in multiple profiles? Profile inheritance? (I have not tried that yet)

Is there any other better way to do this with the existing matchers?

**Comment by clintoncwolfe** [comment]
This appears to be stale, and the answer we'd give today is likely different.  Please re-open if you need more help on this.
