### ISSUE TITLE
inetd_conf resource error

### ISSUE THREAD

**Issue by humboldtux** [inspec/inspec#1253]
### Description

When i execute the following example from the documentation:

``` ruby
describe inetd_conf do
  its('shell') { should eq nil }
  its('login') { should eq nil }
  its('exec') { should eq nil }
end
```

I get the following error:

```
inetd.conf exec 
     wrong number of arguments (given 0, expected 1+)
```
### InSpec and Platform Version

InSpec 1.2.0 installed via ChefDF, on Debian 8.6.

**Comment by Anirudh-Gupta** [comment]
@humboldtux You need to give the inetd_conf path along with it.

```
  describe inetd_conf('path') do
      its('service_name') { should eq 'value' }
  end
```

**Comment by humboldtux** [comment]
@Anirudh-Gupta thank you for your help but:
- You don't need to specify a path when using the defaut inetd conf path (/etc/inetd.conf), look at the end of http://inspec.io/docs/reference/resources/inetd_conf/ for an example.
- _shell_ and _login_ services are not returning error, it's just a problem with _exec_
- Actually, i don't even have an /etc/inetd.conf file on my test server, but i tested with a sample conf file, and i got the exact same error.
- If i replace _exec_ by _exec2_, _foobar_ or even _exec\s_ the test is executed and inspec is not raising an error.

I think that _exec_ is something like a reserved keyword that prevents it from being used in such a spec.

**Comment by chris-rock** [comment]
@humboldtux just added the following to inetd.conf as test

```
login   stream  tcp6    nowait  root    /usr/sbin/in.rlogind    in.rlogind
telnet  stream  tcp6    nowait  root    /usr/sbin/in.telnetd    in.telnetd
shell   stream  tcp nowait  root    /usr/sbin/in.rshd   in.rshd
shell   stream  tcp6    nowait  root    /usr/sbin/in.rshd   in.rshd
exec    stream  tcp nowait  root    /usr/sbin/in.rexecd in.rexecd 
```

Then I used the `inspec shell` to test it:

```
b inspec shell -t docker://1de218c4b67c
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

inspec> inetd_conf.shell
=> ["stream", "tcp6", "nowait", "root", "/usr/sbin/in.rshd", "in.rshd"]
inspec> inetd_conf.exec
=> ["stream", "tcp", "nowait", "root", "/usr/sbin/in.rexecd", "in.rexecd"]
inspec> inetd_conf.login
=> ["stream", "tcp6", "nowait", "root", "/usr/sbin/in.rlogind", "in.rlogind"]
inspec>
```

Now testing `shell` and `login`:

```
inspec> describe inetd_conf do
inspec>   its('shell') { should eq nil }  
inspec>   its('login') { should eq nil }  
inspec> end  

Profile: inspec-shell
Version: unknown



  inetd.conf shell
     ✖  should eq nil

     expected: nil
          got: ["stream", "tcp6", "nowait", "root", "/usr/sbin/in.rshd", "in.rshd"]

     (compared using ==)

     ✖  should eq nil

     expected: nil
          got: ["stream", "tcp6", "nowait", "root", "/usr/sbin/in.rlogind", "in.rlogind"]

     (compared using ==)


Test Summary: 0 successful, 2 failures, 0 skipped
inspec> 
```

Now lets test `exec`

```
inspec> describe inetd_conf do
inspec>   its('exec') { should eq nil }  
inspec> end   

Profile: inspec-shell
Version: unknown



  inetd.conf exec
     ✖  wrong number of arguments (0 for 1+)

Test Summary: 0 successful, 1 failures, 0 skipped
inspec>
```

Therefore I can confirm that this issue only happens in combination with RSpec its. Another issue related to https://github.com/chef/inspec/issues/875

**Comment by humboldtux** [comment]
Thank you @chris-rock for the extensive report. It reminds me i need to use the inspec shell a little bit more.
