### ISSUE TITLE
inspec supermarket profiles - update for new supermarket api

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#1255]
In PR https://github.com/chef/inspec/pull/1254 an intermediate fix for issue https://github.com/chef/inspec/issues/1219 has been merged.

As the issue suggests, once https://github.com/chef/supermarket/issues/1454 is implemented, we should update inspec to use the new supermarket search api call.

Adding the solution @robbkidd mentioned in https://github.com/chef/inspec/issues/1219:

---
### Possible Solutions

After a fix for chef/supermarket#1454 is released, [the request parameters for the search](https://github.com/chef/inspec/blob/725e0a1bc50008c8ad252bd8d5c833a7af20c606/lib/bundles/inspec-supermarket/api.rb#L15) in `inspec supermarket` can be updated. Pending the Supermarket release, the params will probably look like:

``` diff
def self.profiles(supermarket_url = SUPERMARKET_URL)
      url = "#{supermarket_url}/api/v1/tools-search"
-       _success, data = get(url, { q: 'compliance_profile' })
+       _success, data = get(url, { type: 'compliance_profile' })
      if !data.nil?
```

**Comment by robbkidd** [comment]
Prospective fix for chef/supermarket#1454 opened for review in chef/supermarket#1463. Would love :eyes: and feedback.
