### ISSUE TITLE
apt resource fails corner cases with optional second column

### ISSUE THREAD

**Issue by grimm26** [inspec/inspec#1261]
### Description

If a deb source line is something like:
`deb      [arch=amd64] "http://apt.somewhere.com" trusty default`
or
`deb      [trusted=yes] "https://packages.chef.io/stable-apt" trusty main`
the read_debs method is thrown off and puts `arch=amd64` or `trusted=yes` as the url, etc etc.
### InSpec and Platform Version

inspec 1.2.0 on OSX El Capitan (running with kitchen-inspec on various debian platforms).
### Replication Case

Have an entry in an apt source list like the one I describe above.
### Possible Solutions

Have the parser handle something in the "second column" that is not a URL and drop it if so.
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
@grimm26 Great finding. We need to adapt this regular expression then https://github.com/chef/inspec/blob/master/lib/resources/apt.rb#L92
