### ISSUE TITLE
Undefined method `users` for group resource

### ISSUE THREAD

**Issue by artem-sidorenko** [inspec/inspec#1266]
### Description

If you try to use `its('users')` on the `group` resource like [described](http://inspec.io/docs/reference/resources/group/) in the docs, you will get an error `undefined method 'users' for Group`:

```bash
...
 Group docker                                                                                                  
     ✔  should exist                                                                                            
     ✖  undefined method `users' for Group docker:#<Class:0x00000003cc0710>                          
...
```

### InSpec and Platform Version

```bash
$ inspec version                                                          
1.2.0
```

Verified on Centos 7, ubuntu 16.04

### Replication Case

Create a group `docker`, user `vagrant`. Add `vagrant` to `docker`. Use following inspec test to verify it:

```ruby
describe group('docker') do
  it { should exist }
  its('users') { should cmp 'vagrant' }
end
```

**Comment by chris-rock** [comment]
@artem-sidorenko That feature has not been implemented and is an error in our documentation caused by the fact that the cmp resource is a shared partial: https://github.com/chef/inspec/blob/master/docs/resources/group.md.erb#L39

**Comment by chris-rock** [comment]
Lets assume we would implement the `users` method, shouldn't it be something like:

```
describe group('docker') do
  it { should exist }
  its('users') { should include 'vagrant' }
end
```

**Comment by chris-rock** [comment]
We should at least fix the documentation

**Comment by Nik08** [comment]
After verification it seems that this issue does not exist in the [existing group resource doc](https://docs.chef.io/inspec/resources/group/). So this could be closed.
