### ISSUE TITLE
Output of describe command is sometimes broken

### ISSUE THREAD

**Issue by artem-sidorenko** [inspec/inspec#1275]
### Description

Output of describe command is sometimes broken. If you use the example of replication case, you get following output:

```bash
  Command lpstat
     ✔  -v exit_status should eq 0
     ✔  -v stderr should eq ""
     ✔  -v stdout should include "device for vagrantprinter2: lpd://192.168.10.6"
```

Expected output:
```bash
  Command lpstat -v
     ✔  exit_status should eq 0
     ✔  stderr should eq ""
     ✔  stdout should include "device for vagrantprinter1: lpd://192.168.10.5"
     ✔  stdout should include "device for vagrantprinter2: lpd://192.168.10.6"
```

I see here two problems:
 - The argument to the command is not on the line with command itself, but on the lines with tests (dup of #1234)
 - One of stdout tests is suppressed, however it gets checked and works properly in case of failures

### InSpec and Platform Version

```bash
$ gem list | grep inspec
inspec (1.3.0, 1.2.0)
kitchen-inspec (0.15.2)
$ inspec version
1.3.0
$ gem list | grep test-kitchen
test-kitchen (1.13.2)
```

### Replication Case

Create following or similar test:
```ruby
describe command('lpstat -v') do
  its(:exit_status) { should eq 0 }
  its(:stderr) { should eq '' }
  its(:stdout) do
    should include 'device for vagrantprinter1: lpd://192.168.10.5'
    should include 'device for vagrantprinter2: lpd://192.168.10.6'
  end
end
```

You can also use [this PR](https://github.com/biola/chef-cups/pull/17) and just `ktichen verify default-bento-ubuntu-1604`

**Comment by chris-rock** [comment]
@artem-sidorenko Is this a duplicate of https://github.com/chef/inspec/issues/1234?

**Comment by artem-sidorenko** [comment]
@chris-rock the first issue - yes, the second - not. I've updated the description

**Comment by artem-sidorenko** [comment]
it looks like it was resolved at some point
