### ISSUE TITLE
support JUnit format

### ISSUE THREAD

**Issue by jkerry** [inspec/inspec#1301]
### Description

JUnit output format support would be nice to allow for CI systems like jenkins to aggregate and report run status

### InSpec and Platform Version

inspec version: 1.4.1
OS: Any

### Replication Case

--format JUnit should be supported

### Possible Solutions

Looking at the source it seems like a more robust abstracted format layer might be justified before this is added although this should be simple enough since on a first glance most of the action is in the cli and base_cli files.

### Stacktrace

N/A. Feature request

**Comment by chrisevett** [comment]
+1

**Comment by stevaaa** [comment]
👍 
I'm looking for that tooooooooo :(
