### ISSUE TITLE
is this a typo....  inpsec?

### ISSUE THREAD

**Issue by poshpaws** [inspec/inspec#1309]
### Description
when running a check on my profile , I get a strange stacktrace that seems to sugest a typeo :

$inspec check IGM_CIS-RHEL6-L1
/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/bundles/inspec-compliance/target.rb:43:in `resolve': uninitialized constant Compliance::Fetcher::Inpsec (NameError)
Did you mean?  Inspec
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/utils/plugin_registry.rb:18:in `block in resolve'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/utils/plugin_registry.rb:17:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/utils/plugin_registry.rb:17:in `resolve'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/fetcher.rb:12:in `resolve'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/cached_fetcher.rb:12:in `initialize'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/requirement.rb:85:in `new'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/requirement.rb:85:in `fetcher'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/requirement.rb:63:in `resolved_source'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/resolver.rb:59:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/resolver.rb:31:in `resolve'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:349:in `generate_lockfile'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:336:in `lockfile'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:354:in `load_dependencies'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:312:in `locked_dependencies'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:132:in `load_libraries'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:386:in `load_checks_params'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:380:in `load_params'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:104:in `params'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:269:in `controls_count'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/profile.rb:240:in `check'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/lib/inspec/cli.rb:68:in `check'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.4.1/bin/inspec:12:in `<top (required)>'
	from /usr/local/bin/inspec:22:in `load'
	from /usr/local/bin/inspec:22:in `<main>'

### InSpec and Platform Version

OS X 11.12 , inspec 1.4.1

### Replication Case
create a new profile , include a known compliance profile , run inspec check.

### Possible Solutions
looks like a typo in Compliance::Fetcher

### Stacktrace

as above

**Comment by alexpop** [comment]
It was indeed, sorry about that. Looking at the CHANGELOG, it looks like it was fixed in 1.5.0. Can you please update?

**Comment by poshpaws** [comment]
sorry for the noob question , can you point me at a package for 1.5.0 or is it a gem to install ?

**Comment by alexpop** [comment]
It's just a gem install.

**Comment by poshpaws** [comment]
confirmed fixed in 1.5.0
