### ISSUE TITLE
parse_config resource check fails for dotted property name

### ISSUE THREAD

**Issue by vikatgithub** [inspec/inspec#1330]
### Description

The 'parse_config' resource checks fails if the config file property name has dots

### InSpec and Platform Version
InSpec 1.4.1

### Replication Case

If the config file has key value pairs like: 

```module.user.name = 'foo'```

The parse_config check like this:

```its ('module.user.name') {  should eq 'foo' }```

will fail with following error:

```undefined method 'user' for nil:NilClass```

### Possible Reason
The 'method_missing' in PConfig class is treating the property name as chained method calls.

**Comment by chris-rock** [comment]
This is related to https://github.com/chef/inspec/issues/875. Right now, you need to use `its (['module','user','name']) { should eq 'foo' }`

```
describe json('/paht/to/name.json') do
  its('name') { should eq 'hello' }
  its(['meta','creator']) { should eq 'John Doe' }
  its(['array', 1]) { should eq 'one' }
end
```

Reference:
- http://inspec.io/docs/reference/resources/json/
