### ISSUE TITLE
Document package repositories

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1344]
### Description

While a download page is great, often users just want to use package repositories. Since we have this available, we should document this on our website/readme.

Further information is available at https://docs.chef.io/packages.html

**Comment by jaxxstorm** [comment]
@chris-rock I'm happy to contribute here, where do you want this putting?

**Comment by aaronlippold** [comment]
👍

**Comment by adamleff** [comment]
I opened PR #1894 to create a standalone downloads page with links to our main downloads site, the Habitat Depot, and a link to the chef docs that explain how to use your system's package manager.
