### ISSUE TITLE
"Soft Pass" Feature

### ISSUE THREAD

**Issue by emilyay** [inspec/inspec#1346]
Currently, "if" and "only_if" can be used to execute tests only when certain criteria is satisfied. If the criteria is not satisfied, then the test is skipped. The output indicates the test was skipped due to only_if conditions and it is counted as a skipped test. However, it would be nice to implement a "soft pass" feature that you can use with "if/only_if" that would output information that the test is not applicable and mark it as passed. Specifically, I have a use case in mind where you implement a control for a specific file that executes a test on the file if present but otherwise reports that the test is not applicable because the file is not present but is marked as a pass. This type of use case is applicable to implementing a lot of the controls from the CIS Docker 1.11 Benchmark, where certain files may not necessarily be present on the system running Docker. If the files are present, then certain tests need to be executed otherwise the controls are not applicable. The output would be more meaningful if it indicated why the test was skipped and the results would make more sense if they marked that test as passed, since it would not be necessary for anyone auditing to go in and make changes. 

Right now, it is possible to use "describe.one" to workaround this issue, but this method does not output the ideal set of information. For the use case described, It would mark the overall test as passed because the file did not exist and not indicate any information about the second test that could have been executed on the file. This result does not make the user aware that there was a "real" test to be executed that ended up not being applicable. In the case where the control comes from a document like the CIS Benchmarks, this result might also be confusing if the user expected the output to be from the "real" test. @chris-rock @arlimus @aaronlippold

**Comment by chris-rock** [comment]
@emilyh315 I like the idea to have an informational control. Do you have a specific example that we can use to discuss a solution?

**Comment by emilyay** [comment]
From the CIS Docker 1.11.0 Benchmark v1.0.0:
Control 1.11 Audit Docker files and directories - docker.socket (Scored)
Audit: If the file does not exist this recommendation is not applicable. If the file exists, verify that there is an audit rule corresponding to the file.

Current workaround:

`  if docker.socket
      rule = '-w ' + docker.socket + ' -p rwxa -k docker'
      describe auditd_rules do
         its(:lines) { should include(rule) }
      end
   else
      describe file(docker.socket) do
         it { should_not exist }
      end
   end`

The output right now will say pass if the file exists and the appropriate audit rule is there, or it will pass if the file is not there. It doesn't really make sense to see pass because the file does not exist because it doesn't line up with what the test is supposed to be doing. Ideally, I would like the 'else' to be:

`else
   soft_pass('Control is not applicable because file does not exist')`

Then I would like the number of soft passes to be kept separate from regular passes, but to be marked as a pass for determining score. Soft passes would be something of interest to track while you are testing over time, so it's easier to track the changes that occurred to make these tests become applicable.

**Comment by aaronlippold** [comment]
@chris-rock did this ever get started by the way?

**Comment by clintoncwolfe** [comment]
Refs #3017

**Comment by clintoncwolfe** [comment]
I'm going to close this, as most of the needs are covered by #3017 and further discussion should occur there.
