### ISSUE TITLE
Allow use of `include_controls` multiple times

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1353]
### Description

Currently we do not support calling `include_controls` multiple times for the same profile. Therefore the following example will not provide the expected results:

```
include_controls 'cis-amazonlinux-2014.09-2015.03-level1' do
  control 'xccdf_org.cisecurity.benchmarks_rule_1.5.2_AWS_Set_Permissions_on_etcgrub.conf' do
    impact 1.0
    describe file("/etc/grub.conf") do
      it { should exist }
    end
  end
end

include_controls 'cis-amazonlinux-2014.09-2015.03-level1' do
  skip_control 'xccdf_org.cisecurity.benchmarks_rule_1.5.3_Set_Boot_Loader_Password'
end
```

### Possible Solutions

From the user perspective it should not matter if I call `include_controls` multiple times, since all controls have a unique identifier per profile.

### InSpec and Platform Version

1.7.2

**Comment by clintoncwolfe** [comment]
I believe this would cause serious implementation issues, and we do not have a known use case for this.
