### ISSUE TITLE
Port resource on Linux should try ss as well

### ISSUE THREAD

**Issue by nevins-b** [inspec/inspec#1356]
### Description

Currently the port resource for linux uses netstat, on newer verions (like Centos 7) netstat has been replaced by ss.

### InSpec and Platform Version

- inspect 1.72
- Centos 7
### Replication Case

with centos/7 platform
```
describe port(22) do
  it { should be_listening }
end
```
### Possible Solutions

If netstat is not available try ss

**Comment by chris-rock** [comment]
Great idea @nevins-b Are you pushing a PR to add this support?

**Comment by nevins-b** [comment]
I've started coding up a solution, I'll submit a PR once I have it closer to ready.

**Comment by aalmenar** [comment]
This issue it's not really en enhancement but a bug, because since debian 8 and centos 8 and ubuntu 16.04 net-tools are no longer installed as default.

**Comment by aalmenar** [comment]
This pull request #2110 should solve this.

**Comment by adamleff** [comment]
That's true! Please let us know if there are any issues with the new functionality.
