### ISSUE TITLE
verifiy input parameter of `user` resources

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#137]
```
describe user(nil) do
...
end
```

should throw an error and fail the test

**Comment by arlimus** [comment]
Agreed! This is also a bit broad, changing the title to focus on the `user` resource.

**Comment by adamleff** [comment]
I think this is another good case of where resources should be able to throw exceptions that descend from one of two classes (`Inspec::Exceptions::ResourceSkipped` or `Inspec::Exceptions::ResourceErrored`) with a message and properly show that in the appropriate output formatter. Yet another reference to #1205 :)

**Comment by pwelch** [comment]
Closing this issue because there has been no traction on it for a while or it is no longer relevant. If this issue is still relevant, please reopen. Thanks!

Looks like this was addressed on #1205
