### ISSUE TITLE
Writing custom resources documentation

### ISSUE THREAD

**Issue by jaxxstorm** [inspec/inspec#1375]
### Description

I'm trying to write a library that detects a value that is used by multiple controls and other libraries. I think maybe my ruby newbiness may be holding me back, but I wondered if maybe a quicker pointer would help.

I want to write a new resource for a custom application we use internally (it's very unlikely this will be open sourced, otherwise I'd contribute it back). I want to be able to get a parameter/variable from a command, and then use that across _multiple_ profiles as a value. For example:

```
# a method to return the value we want
def my_value
  return my_value
end

# then we can use this in controls!

describe config do
  its('value_name') { should eq(my_value) }
end

```

Is there an easy way to load this resource inside a profile? How does the directory structure look? Is this even possible as part of the profile/plugin system?

I could write a gem (I think?) but that seems like a lot of work. Is there a directory I can just drop the resource in to make this work? Any methods which need to be returned?

If you can point me in the right direction, I'd be quite happy to document this.

I see a couple of issues related to this, such as https://github.com/chef/inspec/issues/353 and there's also a blogpost [here](https://tech.spaceapegames.com/2016/09/23/custom-inspec-resources/), but no official docs that I can see.

### InSpec and Platform Version

1.7.1

### Possible Solutions

Ideally it'd be possible to just load a custom resource with `require` somehow, but there doesn't seem to be much documentation on that at the moment

**Comment by chris-rock** [comment]
@jaxxstorm A sample profile is available here: https://github.com/chef/inspec/tree/master/examples/profile You need to create a `libraries` directory and place your InSpec resources there. This is documented here: http://inspec.io/docs/reference/dsl_resource/ 

Do you want to use the same resource in multiple profiles?

**Comment by clintoncwolfe** [comment]
As there has been no traffic on this issue in a while, we're closing it.  If you have any further questions / discussion, please re-open!
