### ISSUE TITLE
apache_conf resource does not include files from *.d directories when using conf_path parameter

### ISSUE THREAD

**Issue by carldjohnston** [inspec/inspec#1394]
### Description

apache_conf resource does not include files from *.d directories when using conf_path parameter.

### InSpec and Platform Version

InSpec version 1.7.1 on Oracle Linux 7.3

### Replication Case

Install httpd on an EL7 flavor of linux.  Then we'll test for something that's included into the `/etc/httpd/conf.d/autoindex.conf` file in a default install.

From within inspec shell (on an EL7.3 system) showing normal behavior (no conf_path):
```
inspec> describe apache_conf do
inspec>   its('DefaultIcon') { should cmp '/icons/unknown.gif' }
inspec> end

Profile: inspec-shell
Version: unknown


  Apache Config
     ✔  /etc/httpd/conf/httpd.conf DefaultIcon should cmp == "/icons/unknown.gif"

Test Summary: 1 successful, 0 failures, 0 skipped
```
Again from within inspec shell (on an EL7.3 system) showing broken behavior (with conf_path pointed to default location):
```
inspec> describe apache_conf('/etc/httpd/conf/httpd.conf') do
inspec>   its('DefaultIcon') { should cmp '/icons/unknown.gif' }
inspec> end
find_files(): exit 1 from `find /etc/httpd/conf/conf.modules.d/*.conf -maxdepth 1 -type f`
find_files(): exit 1 from `find /etc/httpd/conf/conf.d/*.conf -maxdepth 1 -type f`

Profile: inspec-shell
Version: unknown


  Apache Config
     ∅  /etc/httpd/conf/httpd.conf DefaultIcon should cmp == "/icons/unknown.gif"

     expected: "/icons/unknown.gif"
          got:

     (compared using `cmp` matcher)


Test Summary: 0 successful, 1 failures, 0 skipped
```
### Possible Solutions

It appears that line 24 of the apache_conf resource (https://github.com/chef/inspec/blob/master/lib/resources/apache_conf.rb#L24) might need to trim the `conf/` folder on EL7 to end up with `conf_dir = '/etc/httpd'`

**Comment by chris-rock** [comment]
@carldjohnston Are you saying we need to update the directories here: https://github.com/chef/inspec/blob/master/lib/resources/apache.rb#L12-L24?

**Comment by carldjohnston** [comment]
Hi @chris-rock, I think that code in apache.rb only gets called when we don't specify a conf_path and it does get the correct conf_dir.
If we specify a conf_path then this line in apache_conf.rb just takes the PWD of the httpd.conf file as the conf_dir, which is incorrect (and behaves differently from above):
https://github.com/chef/inspec/blob/master/lib/resources/apache_conf.rb#L24

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
