### ISSUE TITLE
base/ssh compliance profile: /etc/ssh should be 0755

### ISSUE THREAD

**Issue by rjhornsby** [inspec/inspec#1397]
(Apologies, this was the closest place I could find to log an issue related to chef compliance. Please redirect me as appropriate.)

### Description

The permissions of `/etc/ssh` should be `0755`, and this is what ssh-baseline ensures[1].

However, the Chef Compliance dashboard, base/ssh profile, seems to be confused on this item.

![screenshot 2017-01-03 12 29 02](https://cloud.githubusercontent.com/assets/5077610/21646184/bbe05fb2-d25a-11e6-8e66-f281092b071e.png)

Chef compliance says the permissions should be 0755, but fails the test stating `/etc/ssh` should *not* be readable by others. These two states are exclusive and cannot coexist.

I don't think the problem is with the ssh-baseline cookbook or the tests it uses, but rather with the chef compliance profile.

[1] https://github.com/dev-sec/ssh-baseline/blob/master/controls/sshd_spec.rb#L64

### InSpec and Platform Version

Chef Compliance 1.7.7
base/ssh profile version 1.1.0

### Possible Solutions

The base/ssh compliance profile should perhaps be testing for "File /etc/ssh should not be **writable** by others"

**Comment by chris-rock** [comment]
@rjhornsby Thank you for highlighting this issue. We are going to fix this in Chef Compliance. Going forward, we are going to contribute our base profiles to the dev-sec project. This allows us to have a better public review process.

**Comment by jerryaldrichiii** [comment]
@rjhornsby, thanks again for finding this. The issue has been fixed in Chef Compliance and will ship with the next release: `>1.11.5`
