### ISSUE TITLE
Inspec os audit resource missing CentOS

### ISSUE THREAD

**Issue by gscho** [inspec/inspec#1398]
### Description
Inspec os resource should include a symbol for centOS.
ie: `os[:centos]`

### InSpec and Platform Version
Inspec v 1.0.0

http://inspec.io/docs/reference/resources/os/

**Comment by chris-rock** [comment]
Since CentOS is a Redhat system, you can detect it via

```
# Start a centos system eg. `docker run -it centos:7 /bin/bash`

$ b inspec shell -t docker://6215801ac482
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

inspec> os.params
=> {:name=>"centos", :family=>"redhat", :release=>"7.2.1511", :arch=>"x86_64"}
inspec> os.redhat?
=> true
inspec> os.name == 'centos'
=> true
inspec> exit
$ 
```

What is missing for you?

**Comment by gscho** [comment]
My mistake. 
I'll submit a pull request to include it in the os resource documentation the same way other downstream distros are.
