### ISSUE TITLE
Add a way to retry a test if failing

### ISSUE THREAD

**Issue by guilhem** [inspec/inspec#1404]
### Description

Currently, we are using serverspec with https://github.com/NoRedInk/rspec-retry gem
It would be wonderful if _inspec_ was having a way to do the same.

### Why the hell do we need that?

We are using it to test some orchestration framework (like _marathon_) and this need some time to scale resources and make it ready.

### Possible (crapy) Solutions

Adding a `sleep` instead of a retry. It was our previous behavior but it makes tests really slower.

**Comment by jason-riddle** [comment]
Any update on this?

**Comment by adamleff** [comment]
Hi @jason-riddle and @guilhem. Thanks for submitting this issue and following up on it.

The InSpec team discussed this and there are currently no plans to add this feature to InSpec. The focus on the InSpec core is to perform the testing the user requires via a profile and to do that as efficiently and accurately as possible. Adding retry logic to InSpec increases the maintenance burden and complexity of the InSpec core.

Instead, we'd like to see this retry logic added to whatever is using InSpec to perform the tests. For example, if using Test Kitchen, adding retry logic to `kitchen-inspec` feels like a pretty reasonable proposal. Outside of Test Kitchen, wrapping InSpec with some other tool that first checks to see if the host in a 'ready state' (which could mean different things to different people) is another possibility. One could even use `train` (the underlying transport library that InSpec itself uses) to perform that check.

Thanks again for your suggestion, and thanks for using InSpec!

~Adam
