### ISSUE TITLE
Inspec does not allow passing `auth_methods` to the `Train` driver

### ISSUE THREAD

**Issue by greenantdotcom** [inspec/inspec#1409]
### Description

In working on a Chef recipe for an installation of [DUO's MFA implementation](https://duo.com/docs/duounix#public-key-authentication), and specifically the flavor of disallowing passwords.

While running `kitchen verify`, all phases before run smoothly until `inspec` was invoked to verify the installation. Run after run, this error would come out at that stage:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Transport error, can't connect to 'ssh' backend: SSH session could not be established] on openssh-server-centos-73
```

The `kitchen.log` backtrace is included below, which traces back into `inspec`.

After much debugging, I have found that the reason for this is that `Train` does not expect this server's particular combination and refuses to make the connection as the `:auth_methods` do not align with the server's configured announcement of `[publickey,keyboard-interactive]`.

### InSpec and Platform Version

* InSpec 1.7.2
* macOS Sierra 10.12.2
* Ruby 2.2.5
### Replication Case

With an OpenSSH server [>= 6.2](http://www.openssh.com/txt/release-6.2), you can set the `AuthorizationMethods` value to a value that will allow you to play with the use case.

Specifically, the instructions from DUO include…

```
PubkeyAuthentication yes
PasswordAuthentication no
AuthenticationMethods publickey,keyboard-interactive
```

Only the `AuthenticationMethods` value should be needed to create various reproducible cases.

#### MVP

In an minimalist sense, what is needed is the ability to pass along additional options to the Train driver.

I got this working in the `ssh-auth-methods` branch at https://github.com/greenantdotcom/inspec/tree/ssh-auth-methods, which allows for a new command line option for any command that accepts a `target`, such as `exec`, to accept `auth_methods` which will ultimately get passed through to Train.

#### Target goal

Exposing more of the SSH or WinRM flags would helpful, but quite possibly/probably not by adding a ton of flags which could get ugly, and worst, tightly couple `inspec` and `train`.

Instead, what would be interesting would be to pass a config file or something which heads straight for the driver, probably setting it as a base before other command line driver values clobber the config file.

### Stacktrace

```
E, [2017-01-08T20:27:27.194222 #70706] ERROR -- Kitchen: -Composite Exception--
E, [2017-01-08T20:27:27.194243 #70706] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-01-08T20:27:27.194260 #70706] ERROR -- Kitchen: Message: Failed to complete #verify action: [Transport error, can't connect to 'ssh' backend: SSH session could not be established] on openssh-server-centos-73
E, [2017-01-08T20:27:27.194276 #70706] ERROR -- Kitchen: ----------------------
E, [2017-01-08T20:27:27.194290 #70706] ERROR -- Kitchen: ------Backtrace-------
E, [2017-01-08T20:27:27.194305 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/inspec/backend.rb:46:in `rescue in create'
E, [2017-01-08T20:27:27.194331 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/inspec/backend.rb:16:in `create'
E, [2017-01-08T20:27:27.194347 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/inspec/runner.rb:64:in `configure_transport'
E, [2017-01-08T20:27:27.194361 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.7.2/lib/inspec/runner.rb:56:in `initialize'
E, [2017-01-08T20:27:27.194376 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:80:in `new'
E, [2017-01-08T20:27:27.194385 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-inspec-0.17.0/lib/kitchen/verifier/inspec.rb:80:in `call'
E, [2017-01-08T20:27:27.194393 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:434:in `block in verify_action'
E, [2017-01-08T20:27:27.194401 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-01-08T20:27:27.194409 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-01-08T20:27:27.194417 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-01-08T20:27:27.194425 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:488:in `action'
E, [2017-01-08T20:27:27.194432 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:426:in `verify_action'
E, [2017-01-08T20:27:27.194440 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-01-08T20:27:27.194452 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:358:in `each'
E, [2017-01-08T20:27:27.194460 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-01-08T20:27:27.194468 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/instance.rb:157:in `verify'
E, [2017-01-08T20:27:27.194476 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/command.rb:197:in `public_send'
E, [2017-01-08T20:27:27.194484 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-01-08T20:27:27.194492 #70706] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.14.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-01-08T20:27:27.194500 #70706] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by chris-rock** [comment]
@greenantdotcom This is a really good discussion. We could find a balance and have the most common settings available via CLI. Once you need more advanced configuration we could use a json or yml file as input to configure the targets.

cc @arlimus

**Comment by mattlqx** [comment]
Ran into this as well trying to get some smoke testing with InSpec added into my Chef Automate Workflow. :(

**Comment by woneill** [comment]
Also ran into this while testing Yubico PAM module for SSH

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
