### ISSUE TITLE
un-wrapped "<command> is not supported" output outside JSON

### ISSUE THREAD

**Issue by rjhornsby** [inspec/inspec#1411]
### Description

When running `inspec check --format json` there's a possibility that a warning is output outside of the json object, confusing any JSON parsers which are expecting only JSON. Specifically, we're seeing this confuse the JSON parser of the Chef Compliance server when uploading an inspec profile in certain cases. The parser error causes the `POST` to fail, which bubbles up into an HTTP/500 reply from the compliance server to the API caller. In the case of trying to upload an inspec profile, the caller is the compliance server itself.

### InSpec and Platform Version

Using primarily inspec 1.7.2 (what ships with chefdk and chef compliance server). I ran the replication test against inspec 1.9.0 and it is still outputting the warning outside of the JSON.

For the record, Chef compliance server is version 1.7.7.

### Replication Case

The easiest way I know how to demonstrate a replication case is to run `inspec check` against the dev-sec ssh-baseline profile.

```
$ inspec check --format json https://github.com/dev-sec/ssh-baseline/archive/master.tar.gz
`command(ssh).exist?` is not suported on your OS:
{"summary":{"valid":true,"timestamp":"2017-01-12T19:48:46-06:00","location":"https://github.com/dev-sec/ssh-baseline/archive/master.tar.gz","profile":"ssh-baseline","controls":67},"errors":[],"warnings":[]}
```

Notice how the first line of what should be JSON is a backtick. The JSON doesn't begin until the second line of output.

### Possible Solutions

The problem is in [command.rb](https://github.com/chef/inspec/blob/master/lib/resources/command.rb#L57). While ruby's `warn` is supposed to write this _is not supported_ message to `stderr`, under certain conditions the chef compliance server, while trying to validate an uploaded inspec profile before committing it to disk permanently, reads the warning and the json string together (from `stdout`?) and tries to process both together as JSON. The JSON parser can't understand the backtick and the chef compliance API caller gets back `HTTP/500`.

I think the solution is to not use `warn` in this way. The JSON response already contains placeholder arrays for errors and warnings. When the `--format json` directive is passed to inspec, any warnings or errors should be pushed into the corresponding array.

### Stacktrace

There's no inspec stacktrace, as inspec believes itself to be behaving properly. I understand that in the above explanation, I seem to be talking about chef compliance server but I don't think the bug is a problem with compliance server. I think it's in the way that inspec is handling this (and maybe other?) warnings when the output is supposed to be a JSON object.

To be fair, I'm still trying to understand why it appears that Chef compliance server is sometimes treating the `warn` as `stderr` (and everything works peachy), and sometimes treats it as `stdout` (and it breaks because the JSON parser trying to evaluate the `inspec check` result doesn't know how to handle the first input character of a backtick).

I think either way, it still comes down to that inspec shouldn't be writing output that's not wrapped in JSON when JSON format was requested.

**Comment by rjhornsby** [comment]
So as not to confuse things, I didn't want to add this part until I was sure. This morning I was able to confirm that the unusual behavior where the chef compliance server (running on CentOS) treats or sees the _is not supported_ message as part of `stdout` happens when you run the `inspec upload ...` command from Windows.

I do not know why it behaves this way. The `inspec check --format json` is being run _by_ the compliance server _on_ the compliance server, after the profile is initially uploaded. It seems to matter whether `inspec upload` is run from Windows, or run from a *nix system.

**Comment by lijoyoung** [comment]
I am facing the same issue. Is there any fix or workaround for this yet?  Thanks!

**Comment by adamleff** [comment]
This warning should be commended out, replaced with a TODO to raise an exception that properly skips the resource (once #1205 is addressed). Logging as a bug for our backlog. Thanks @rjhornsby and others for your patience.

**Comment by clintoncwolfe** [comment]
At this point (4.3.2), we detect when the reporting is going to a JSON destination and send all logs to STDERR.
