### ISSUE TITLE
Compliance server actions do not auth correctly with refresh token

### ISSUE THREAD

**Issue by brentm5** [inspec/inspec#1414]
### Description

If you login to a compliance server with a refresh token the token will only be valid for the max age before a token expires.  This happens because the login action simply takes the refresh token and generates a token which gets saved with the configuration on disk.

### InSpec and Platform Version

All Versions of inspec

### Replication Case

run the following with valid values `inspec compliance login inspec compliance login <compliance address> --user='<user>' --refresh_token='<refresh_token>'`
Wait an hour or so
Try to run `inspec compliance profiles` or any other command that requires auth to compliance

### Possible Solutions

The solution is to actually implement how the refresh_tokens get used instead of  just using them to generate a token.

**Comment by chris-rock** [comment]
Thank you @brentm5 Indeed, this is annoying.

**Comment by jerryaldrichiii** [comment]
@brentm5, is this still an issue?

**Comment by clintoncwolfe** [comment]
As Compliance is no longer a current product, and the behavior described appears to be as intended, we're going to close this for now.
