### ISSUE TITLE
New Inspec.io is crashing on Edge if window is resized to a smaller window

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1420]
### Description

inspec.io is crashing on Windows 10 Edge. Users report, it also happens on Windows 10 Mobile.

### Replication Case

Open Edge on Windows and resize the window. It seems to happen only if the Windows is resized to less than 770px.
![capture2](https://cloud.githubusercontent.com/assets/1178413/22148032/2049c232-df0c-11e6-8672-88f3e5c16336.PNG)

### Possible Solutions

Unclear. Possibly we need to hide some canvas elements.

**Comment by chris-rock** [comment]
@hannah-radish do you have an idea?

**Comment by hannah-radish** [comment]
Hi @chris-rock I pushed a few changes a few weeks ago, I'm not sure if it fixed this issue. 
I was unable to recreate this issue for IE11 on my Virtualbox. Would you be able to let me know if you are still experiencing this issue, and what the console error is? Thanks!

**Comment by hannah-radish** [comment]
@chris-rock Still trying to diagnose the issue. 
Resizes perfectly fine for IE10, IE11. This issue is only happening for Edge

**Comment by hannah-radish** [comment]
@chris-rock Solved the problem. Clip-path is widely unsupported, but the use of clip-path with a media query made Edge confused to where it refused to load the site when resized to specific breakpoints. Anyways, fix is in https://github.com/chef/inspec/pull/1512.
