### ISSUE TITLE
Wrong rendering of InSpec.io header

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1421]
### Description

If the window is resized, the download button is a little bit off.

![capture](https://cloud.githubusercontent.com/assets/1178413/22147360/850b2b88-df08-11e6-80f6-7b02bbe5236f.PNG)

**Comment by hannah-radish** [comment]
@chris-rock WIP, these changes will be reflected once I am done working on https://github.com/chef/inspec/pull/1512

**Comment by hannah-radish** [comment]
@chris-rock this issue is resolved in https://github.com/chef/inspec/pull/1512
