### ISSUE TITLE
Can't find train plugin "https" with no direction on what to do

### ISSUE THREAD

**Issue by mhedgpeth** [inspec/inspec#1425]
### Description

I'm running this command after just having installed InSpec with the msi installer on windows:

```
inspec exec -t https://github.com/mhedgpeth/chef-client-profile
```

I get the following error, which doesn't provide any actionable direction for me:

```
Can't find train plugin "http". Please install it first.
```

### InSpec and Platform Version

InSpec version 1.7.2 on Windows 10

### Replication Case

Run the command in the description after installing InSpec from the MSI installer

### Possible Solutions

There is a way to load train plugins but I don't know what that is. The error message is not clear.

At the same time, these plugins should probably be shipped with the installer.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
@mhedgpeth https is not a backend. You try to download a profile from https, run the url directly:

```
inspec exec https://github.com/mhedgpeth/chef-client-profile
```

The `-t` options gives you the ability to run the profile against a remote machine. eg.:

```
inspec exec https://github.com/mhedgpeth/chef-client-profile -t ssh://user@host:port -i /path/to/key
```
