### ISSUE TITLE
Inspec.io and IE11

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1437]
Hi,

The new inspec.io site is having background and stylesheet issues when being viewed in IE11 at least on my MITRE box. Just thought I would let you know it is casing issues in not only the header but also in the mid-page code examples etc.

Aaron

**Comment by hannah-radish** [comment]
Hi @aaronlippold, thanks for this! Would love to fix this. I was unable to recreate this issue for IE11 on my virtualbox. Would you be able to provide a screenshot? Appreciate your help!

**Comment by hannah-radish** [comment]
IE10, IE11 and Edge support for stylesheet once I'm completed with https://github.com/chef/inspec/pull/1512
