### ISSUE TITLE
Inspec.io - Add InSpec Resources drop-down?

### ISSUE THREAD

**Issue by davidcpell** [inspec/inspec#1440]
### Description

It would be great if, while browsing the InSpec resources in the docs at inspec.io, a drop-down with each resource could open up in the left navigation like it used to when the docs were at docs.chef.io. As it is now, you have to click back to the main resources index each time you want to go from one resource to another.

**Comment by arlimus** [comment]
Kudos @davidcpell !!
@hannah-radish sounds like a great idea 😁

**Comment by hannah-radish** [comment]
hey @arlimus could you help me with the dynamic pages for resources to load in :side_bars in the yml?

**Comment by hannah-radish** [comment]
Will address this ticket for upcoming inspec.io redesign
