### ISSUE TITLE
Better UX for regular expression on output

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1446]
### Description

Let's assume we run the following test:

```
describe command(\"apparmor_status\").stdout.match(/^(\\d+).*unconfined/)[1] do
   it { should cmp == 0 }
 end
```

we run a regular expression on `stdout` and compare the result of a match. I would prefer something as part of the language to avoid especially `[1]`. Although this works is unreadable. First, lets split up the problem into two: 1) fetching data, 2) running a regular expression on it.

```
output = command(\"apparmor_status\").stdout
describe output.match(/^(\\d+).*unconfined/)[1] do
   it { should cmp == 0 }
 end
```

We should not try to abstract ruby regex handling.

### InSpec and Platform Version

1.10

### Possible Solutions

Need to be discussed. Maybe the solution is to write custom resources and handle the problem there. This path would allow us to reuse plain ruby and reuse available concepts in InSpec.

**Comment by clintoncwolfe** [comment]
Today, we'd typically recommend property-matcher syntax, like this:

```
  describe command('/do/something') do
    its('stdout') { should match /expect_regex/ }
  end
```

The `match` universal matcher is one of the supported matchers.  We don't have to pick apart the results of `String#match`.

Unless there is a concern I am missing, I'll close this; please feel free to re-open, of course.
