### ISSUE TITLE
Requesting cron resource

### ISSUE THREAD

**Issue by erenfro** [inspec/inspec#1461]
### Description

ServerSpec supports the resource for cron, however it is limited in ways that could be improved, such as being able to do checks against the system-wide /etc/cron.d files. For the remaining directories, like /etc/cron.hourly and /etc/cron.daily, those are just regular scripts in place so they can easily be validated with existing matchers, but cron has a specific structure and should be testable.

Eventually I would also like to see resources for systemd as well, especially somewhat related to this request, systemd.timer units.

**Comment by adamleff** [comment]
@erenfro Hi, Eric. Thanks for your suggestion.

I recently added a `crontab` resource but is currently limited to user crontabs.

For your use case, are you looking for a resource that reads in *all* the cron.d files and returns all the entries, or the ability to specify a particular file and just read in the entries from that one file?

I suppose I could see supporting both - if you don't supply a filename, we read in everything. But I'd love to hear your perspective. This should be a pretty easy resource to code up given it will look a lot like the existing crontab resource.

**Comment by erenfro** [comment]
In my case, specific files that exist in /etc/cron.d and can verify certain values.
Specifically, each type of value for the schedule, just as you can set them with chef, what user to run as, and what command to run.

For the other /etc/cron.*/ directories, those are just scripts, so wouldn't likely need a specific InSpec function for that as they could be compared with the file resource.

**Comment by erenfro** [comment]
I don't know what's been done for the user crontabs, but similar checking would be essential, the only difference would be only checking a schedule and command, no user. How to differentiate between a each user's crontab and a cron.d entry though, would be curious. Ideally you'd want to verify exact specifics, because user crontabs have many values, as can a cron.d file entry.

**Comment by jeffbyrnes** [comment]
I don’t recall when it was intro’d, but there’s now a [`crontab`](https://www.inspec.io/docs/reference/resources/crontab/) resource. It only checks the system & user crontabs, not anything in `/etc/cron.d` but it’s a start!

**Comment by linusguan** [comment]
I second this request. 
@adamleff As a system engineer, I generally don't use user crontab for servers and use system crontab instead, it's just easier to manage this way.
I usually store entries in `/etc/cron.d/` but it could be beneficial to also support `/etc/cron.daily/`, `/etc/cron.deny`, `/etc/cron.hourly/`, `/etc/cron.monthly/`, `/etc/cron.weekly/` and `/etc/crontab`
Something like this would be great:
```
describe crontab('system') do
  its('commands') { should include '/path/to/some/script' }
end
```

@jeffbyrnes I think it only checks for user crontabs.

**Comment by miah** [comment]
Hello =)

The crontab resource has been updated to support system crontabs! You'll find this change in our [1.48.0](https://github.com/chef/inspec/blob/master/CHANGELOG.md#v1480-2017-12-07) release.

Example use:
```
describe crontab(user: 'root') do
  its('commands') { should include '/path/to/some/script' }
  its('user') { should be 'root' }
end

describe crontab(path: '/etc/cron.d/some_crontab') do
  its('commands') { should include '/path/to/some/script' }
end
```
