### ISSUE TITLE
Functional tests are unstable in travis builds

### ISSUE THREAD

**Issue by jkerry** [inspec/inspec#1463]
### Description

The last 2 pull requests I've submitted have been temporarily blocked by failing functional tests in Travis. These tests eventually pass by re-running the build

### InSpec and Platform Version

N/A

### Replication Case

Submit a pull request when master is green. In theory you should get some failures on repeated runs

### Possible Solutions

RCA unstable functional tests and shore them up

### Stacktrace

N/A

**Comment by adamleff** [comment]
@jkerry just wanted to acknowledge this issue and let you know we've got it. Since starting my new role with the InSpec team, this has annoyed me for quite a bit. I will definitely look into this as soon as I'm able.

**Comment by jkerry** [comment]
Great!  let me know if there's any way I can assist.

**Comment by adamleff** [comment]
@arlimus fixed a whole bunch of these and this happens way less often. We'll triage them as they occur, but the frequency is now much lower.

**Comment by jkerry** [comment]
Awesome.  Thanks for knocking it out
