### ISSUE TITLE
Add events.inspec.io and download.inspec.io

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1465]
As requested by @ubergeekgirl

cc @hannah-radish

**Comment by ubergeekgirl** [comment]
downloads.inspec.io

**Comment by hannah-radish** [comment]
Hi @ubergeekgirl, I'm not sure how events.chef.io is built or how the content is managed, but is there an API that we can fetch the latest event data from and display in events.inspec.io?

Regarding downloads.inspec.io, do you mean bringing the packages over to inspec.io so the user does not have to go to downloads.chef.io to download Inspec?

**Comment by adamleff** [comment]
@hannah-radish I think the ask was to have an actual domain called `downloads.inspec.io` and have it go to our downloads page. The way the site is currently set up (using GitHub pages), this isn't possible, and the need that preceded this issue (creation of the InSpec conference cards) I think is done now -- the cards are already printed.

I think we can close this issue.

**Comment by hannah-radish** [comment]
@adamleff I just got off a zoom with Jessica, and I added a redirect from inspec.io/downloads (what's on the cards) to downloads.chef.io.

I'm going to leave this ticket open, if it's alright with you, to remind myself to work on the events stuff once marketing is ready.

**Comment by adamleff** [comment]
Fine with me 🙂

**Comment by nathenharvey** [comment]
It looks like inspec.io/downloads is currently a 404.  It would good if either or both of the following worked:

downloads.inspec.io does a 301 redirect to https://downloads.chef.io/inspec

inspec.io/downloads does a 301 redirect to https://downloads.chef.io/inspec

The events portion of this ticket is captured in #1492 so I think this ticket's title could be updated to remove the bit about downloads.

**Comment by nathenharvey** [comment]
the reason behind the request, as @adamleff mentioned, is that we are printing some InSpec reference cards to give out at conferences and meetups.  The easier the URLs are to remember the better.  Additionally, following a common convention across all of our project sites will help (downloads.chef.io, downloads.inspec.io, downloads.habitat.sh)

**Comment by arlimus** [comment]
Moved to https://github.com/inspec/inspec/issues/3289
