### ISSUE TITLE
Create url for demo that can be pointed to from outbound campaigns

### ISSUE THREAD

**Issue by jaselit** [inspec/inspec#1485]
### Description

the demo needs a unique url, not http://inspec.io/#. The issue is that we are trying to do outbound campaigns for trying the inspec demo, but we have no url to point to. How quickly can this be resolved? we have campaigns scheduled in the next week or two.

once this is done can you please notify me that the change has been made. Thanks!

Jason

### InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment]
Site released, /tutorial.html is now a thing  💥
