### ISSUE TITLE
InSpec Shell should support custom resources

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1486]
### Description

InSpec shell doesn't load my custom resources.

### InSpec and Platform Version

all

### Replication Case

Just run inspec shell, there is no option to tell it which dependency profile to pull or include nor resource to load locally.

### Possible Solutions

Add an option to load resource packs.

**Comment by aaronlippold** [comment]
This would be key to an effective way to develop resources easily - for example - our work on the inspec-aws resources.
