### ISSUE TITLE
Create a page of 'supported or maintained profiles' for compliance server

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1498]
A few users of compliance server have been asking what profiles do I get when I download and use Compliance Server or Chef Automate. 

We should have a list of profiles that are bundled so folks know what they get out of the box and what they would have to maintain or create themselves.

"@shoekstra 
sure, am interested in what comes bundled with Compliance so I don’t create for myself what I could get when using Compliance in the future, e.g. if Compliance comes bundled with CIS benchmarks but not STIG, I may create my own STIG profiles but not CIS profiles."

Also, we should, provide some position of what level of effort is behind each profile, such as, for the CIS profiles, we InSpec will maintain the profile to at least X level, the DISA STIG profiles are a best effort 'autogenerated' profile from the SCAP content ... etc so folks know to what degree they can or should baseline off of the profiles given their situation.

**Comment by adamleff** [comment]
@arlimus I think this is a great suggestion and we should be more transparent with our users with at least what commercial profiles are available, and some statement about how we keep them updated, etc. I don't necessarily think we should maintain this list on inspec.io but rather on a chef.io page about Automate.  What are your thoughts?

**Comment by arlimus** [comment]
We have not managed to complete this work and most of the commercial kit has now moved to Automate. We have a list of commercially supported profiles and versions that are now more visible and distinguished. This should cover the use-case. Thank you for bringing this up!
