### ISSUE TITLE
InSpec Profiles for Chef Server, Automate and Compliance - CIS and DOD/IC

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1499]
We should create two sets of profile to support the ongoing use and deployment of the Chef product suite. 

1. CIS Compliance for all three products to support commercial clients
2. DOD Compliance to support other clients for all three products

These profiles should show that the installers and chef recipes that install Server, automate and compliance server setup and configure the services to meet the requirements of either a CIS Benchmark standard or a DOD / IC compliance standard.

So as I see it, you would have three options.
a) standard install 
b) CIS Benchmark Install
c) DOD/IC Install

I would think that once we have the CIS version - it would make sense to just make that the standard install.

This would greatly help speed of adoption and be a great way to show how and why our product suite adds value :)

**Comment by adamleff** [comment]
@aaronlippold I'm going to close this issue since it doesn't really affect the core InSpec project. I'd recommend talking to @arlimus or @chris-rock to determine where best to log this. Thanks!

**Comment by aaronlippold** [comment]
No problem. It was a placeholder for the conversation to get the issue
worked out.
