### ISSUE TITLE
Colours and symbols broken on Windows

### ISSUE THREAD

**Issue by trickyearlobe** [inspec/inspec#1508]
### Description

* Passing inspec tests display white on a red backround instead of green on black.
* Failing inspec tests display white on black instead of red on black
* Fancy UTF-8 checkmarks show as ? or box character (depends which terminal used)

### InSpec and Platform Version

* Inspec 1.11.0, 1.14.1
* Windows 2012R2, Windows 2008R2, Windows 10
* Powershell, ConEmu

### Replication Case

Make some sample tests with passing and failing cases
Run ```inspec exec <path to tests>```

### Possible Solutions

Pull request will follow which detects OS and uses:-

* Basic ANSI colors instead of extended colors
* Standard [PASS] [FAIL] messages instead of fancy UTF8 checkmarks.

**Comment by adamleff** [comment]
Closing, fixed in #1510.
