### ISSUE TITLE
rb-readline 0.5.4 breaks functional tests

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1515]
### Description

When running `rake test:functional` with a Gemfile.lock containing rb-readline 0.5.4, some shell tests break as so:

inspec shell tests::shell#test_0007_runs anonymous tests that fail [/Users/aleff/projects/inspec/test/functional/inspec_shell_test.rb:166]:
Expected "Welcome to the interactive InSpec Shell\nTo find out how to use it, type: \u0001\e[1m\u0002help\u0001\e[0m\u0002\n\nYou are currently running on:\n\n    OS platform:  \u0001\e[1m\u0002mac_os_x\u0001\e[0m\u0002\n    OS family:  \u0001\e[1m\u0002darwin\u0001\e[0m\u0002\n    OS release: \u0001\e[1m\u000210.12.3\u0001\e[0m\u0002\n\n\e[0G\e[?1034hError: no implicit conversion of nil into String\n/Users/aleff/.chefdk/gem/ruby/2.3.0/gems/rb-readline-0.5.4/lib/rbreadline.rb:2398:in `initialize'\n

Locking to 0.5.3 does not show the same issue.

### InSpec and Platform Version

InSpec master, Mac OS X, rb-readline 0.5.4

### Replication Case

 * remove Gemfile.lock
 * run `bundle install`
 * run `bundle exec rake test:functional`

### Possible Solutions

Will likely require a PR submitted to rb-readline, need to find the bug first.

**Comment by adamleff** [comment]
ConnorAtherton/rb-readline#135 submitted in hopes of fixing this upstream.

While we could fix this by pinning to 0.5.3, the omnibus rb-readline software definition defaults to pulling from master, so we'd need to change it there too and ensure that ChefDK builds don't cause issues. Since pry requires readilne, it will have a tendency to get loaded/activated first, so if 0.5.4 is in the gem path, it will likely get loaded first before bundler or something else attempts to activate 0.5.3, which will fail.

**Comment by Devon21** [comment]
I have a simiar issue, not sure if its the same. Let me know if its the same
` /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.3/lib/rbreadline.rb:13: warning: constant ::Fixnum is deprecated /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/profile_context.rb:148:in `instance_eval': /etc/sensu/plugins/inspec-cis-apache13.rb:123: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError) from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/profile_context.rb:148:in `load_with_context' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/profile_context.rb:132:in `load_control_file' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/profile.rb:160:in `block in collect_tests' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/profile.rb:157:in `each' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/profile.rb:157:in `collect_tests' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/runner.rb:89:in `block in load' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/runner.rb:78:in `each' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/runner.rb:78:in `load' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/runner.rb:99:in `run' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/base_cli.rb:83:in `run_tests' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/lib/inspec/cli.rb:158:in `exec' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start' from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.46.2/bin/inspec:12:in `<top (required)>' from /opt/sensu/embedded/bin/inspec:22:in `load' from /opt/sensu/embedded/bin/inspec:22:in `<main>' Check failed to run: 743: unexpected token at '', ["/opt/sensu/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse'", "/opt/sensu/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse'", "/etc/sensu/plugins/check-inspec.rb:56:in `inspec'", "/etc/sensu/plugins/check-inspec.rb:60:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.0.1/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
`

**Comment by adamleff** [comment]
@Devon21 I think the rb-readline component here is unrelated. This looks like your real error:

```
/etc/sensu/plugins/inspec-cis-apache13.rb:123: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
```

That looks like you're missing an `end` somewhere in `/etc/sensu/plugins/inspec-cis-apache13.rb`

**Comment by clintoncwolfe** [comment]
Functional tests pass today at inspec v3.2.6 and rb-readline 0.5.5  - closing.
