### ISSUE TITLE
IIS app pool resource

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1517]
### Description

Right now, InSpec cannot verify the IIS App Pool configuration

```
describe iis_app_pool('Default App Pool') do
  it{ should exist }
  its('identity_type') { should eq 'ApplicationPoolIdentity' }
end
```

We should also consider merging the `iis_website` and `iis_app_pool` into one `iis` resource and provide a `iis.website` and `iis.app_pool` instead. This would be analog to our `yum` resource.

### References

* https://www.iis.net/learn/manage/configuring-security/application-pool-identities
* http://serverspec.org/resource_types.html#iis_app_pool

**Comment by chrisevett** [comment]
@chris-rock ill have time this week to implement this feature and make the requested changes to iis_website as well

**Comment by chris-rock** [comment]
@chrisevett Awesome, that would be so helpful!

**Comment by chris-rock** [comment]
fixed by https://github.com/chef/inspec/pull/1905
