### ISSUE TITLE
Extend IIS application configuration parsing

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1518]
### Description

We need an InSpec resources to cover configuration available via [AppCmd](https://www.iis.net/learn/get-started/getting-started-with-iis/getting-started-with-appcmdexe). Instead of using `AppCmd` directly, we should continue to use (Web Server (IIS) Administration Cmdlets in Windows PowerShell)[https://technet.microsoft.com/en-us/library/ee790599.aspx]. This would allow us to read the following configuration parameters:

- `authentication mode` https://forums.iis.net/t/1146296.aspx?How+to+set+authentication+with+appcmd+exe+or+ServerManager
- `forms.cookieless` https://technet.microsoft.com/en-us/library/cc732830(v=ws.10).aspx
- `forms.protection` https://technet.microsoft.com/en-us/library/cc731804(v=ws.10).aspx
- `retail` and `debug` https://technet.microsoft.com/en-us/library/cc725812(v=ws.10).aspx
- `customErrors` https://forums.iis.net/t/1170090.aspx?Configuring+NET+settings+by+editing+config+files+manually
- `trace` https://technet.microsoft.com/en-us/library/cc725786(v=ws.10).aspx
- `cookieless` https://technet.microsoft.com/en-us/library/cc754725(v=ws.10).aspx
- `machineKey` https://technet.microsoft.com/en-us/library/cc772271(v=ws.10).aspx
- `trust` https://technet.microsoft.com/en-us/library/cc753658(v=ws.10).aspx
- `httpErrors` https://www.iis.net/configreference/system.webserver/httperrors

We need to identify a good syntax to retrieve and use the configuration values

**Comment by tarcinil** [comment]
@chris-rock 

I have looked into this a little bit, tell me what you think?

I conceived functions like this that would take a filter and start doing the same work as `iis_app`.  The filter would be XPath for IIS

Docs for `Get-WebConfiguration`: https://technet.microsoft.com/en-us/library/ee790561.aspx

```ruby 
    def iis_config(filter)
      command = "Import-Module WebAdministration; Get-WebConfiguration #{filter} -PSPath IIS:\\sites\\#{@site_name}\#{@path}"
      cmd = inspec.command(command)

      begin
        app = cmd.stdout.strip
      rescue StandardError => e
        raise ResourceSkipped ...
      end

      app
    end
```

I am going to use `authentication mode` and `forms.cookieless` as examples:

```powershell
# Mode
PS C:\Users\Administrator> Get-WebConfiguration -Filter /system.web/authentication/@mode -PSPath 'IIS:\sites\Default Web
 Site\inspec'
Windows

# Forms.Cookieless
PS C:\Users\Administrator> Get-WebConfiguration -Filter /system.web/authentication/forms/@cookieless -PSPath 'IIS:\sites
\Default Web Site\inspec'
UseDeviceProfile
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
