### ISSUE TITLE
Request for Discussion: better error handling for file read failures

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1528]
There have been a few issues lately, including most recently #1474, where the failure for train to read a file (due to permissions, for example) causes what I believe to be incorrect InSpec results.

Example: if a user does a `should_not match` on a file that the user cannot read and that file contains the pattern, the test will succeed, but when run as root, it will not.

```
[vagrant@localhost ~]$ ls -l /tmp/root-only.txt
-rw-------. 1 root root 4 Mar  2 13:00 /tmp/root-only.txt

[vagrant@localhost ~]$ sudo cat /tmp/root-only.txt
foo

[vagrant@localhost ~]$ cat /tmp/control.rb
describe file('/tmp/root-only.txt') do
  its('content') { should_not match /foo/ }
end

[vagrant@localhost ~]$ inspec exec /tmp/control.rb

Target:  local://


  File /tmp/root-only.txt
     ✔  content should not match /foo/

Test Summary: 1 successful, 0 failures, 0 skipped

[vagrant@localhost ~]$ sudo inspec exec /tmp/control.rb

Target:  local://


  File /tmp/root-only.txt
     ∅  content should not match /foo/
     expected "foo\n" not to match /foo/
     Diff:
     @@ -1,2 +1,2 @@
     -/foo/
     +foo


Test Summary: 0 successful, 1 failures, 0 skipped
```

Seeking opinions on how we should handle. Should train raise an exception and inspec propagate it so the user gets proper output? I don't think a user should have to modify tests to include permission checks when they want to check the content.

/cc @chef/inspec-maintainers

**Comment by chris-rock** [comment]
@adamleff I think one of the first steps is to handle exceptions properly as pointed out in https://github.com/chef/inspec/issues/1205. Once we have the exception why something is failed, we can think about the error message.

**Comment by adamleff** [comment]
@chris-rock yeah, I looked through #1205 already. I definitely believe `skip_resource` is the wrong approach for something like this. If something underlying raises an exception, the exception should bubble-up but should not stop the run. This is already standard RSpec behavior:

```
$ cat test_spec.rb
describe 'exception tests' do
  it 'should not stop the rspec run on an exception' do
    raise 'here is an exception'
  end
  it 'has a second example that should still run' do
    expect(1).to eq(1)
  end
end

$ rspec -fd -c ./test_spec.rb

exception tests
  should not stop the rspec run on an exception (FAILED - 1)
  has a second example that should still run

Failures:

  1) exception tests should not stop the rspec run on an exception
     Failure/Error: raise 'here is an exception'

     RuntimeError:
       here is an exception
     # ./test_spec.rb:3:in `block (2 levels) in <top (required)>'

Finished in 0.00129 seconds (files took 0.08113 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./test_spec.rb:2 # exception tests should not stop the rspec run on an exception
```

**Comment by arlimus** [comment]
Fully agree with the feedback given here. File read errors should be reported as errors. Proper ruby exceptions now create the desired result so that these conditions are neither reported as skipped nor as having read incorrect values.
