### ISSUE TITLE
Profiling for controls

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1529]
### Description

I would be good to do some basic profiling around controls. InSpec could output the amount of time each control takes during execution. This could be highlighted if a report is shown in a debug mode.

**Comment by trevor-vaughan** [comment]
After spending quite some time trying to figure out why my scans were so slow, this would be REALLY helpful.

That said, I would have it be part of the `debug` log level, but I would also add a `--benchmark` option to `--exec` so that we could see it in real time without all the chaff.

**Comment by tarcinil** [comment]
How does this differ from run_time that exists under the json/yaml reporters?  Is this needed anymore?

**Comment by chris-rock** [comment]
@tarcinil I think the description lacks of more detail. You're right that the run_time is offering the data already. It would be nice if the cli output allows an optional `--benchmark` and shows all the stats at the end like:

```
$ inspec exec https://github.com/dev-sec/ssh-baseline --benchmark

Profile: DevSec SSH Baseline (ssh-baseline)
Version: 2.3.2
Target:  local://

  ✔  ssh-01: client: Check ssh_config owner, group and permissions.
     ✔  File /etc/ssh/ssh_config should exist
     ✔  File /etc/ssh/ssh_config should be file
     ✔  File /etc/ssh/ssh_config should be owned by "root"
     ✔  File /etc/ssh/ssh_config should be grouped into "wheel"
     ✔  File /etc/ssh/ssh_config should not be executable
     ✔  File /etc/ssh/ssh_config should be readable by owner
     ✔  File /etc/ssh/ssh_config should be readable by group
     ✔  File /etc/ssh/ssh_config should be readable by other
     ✔  File /etc/ssh/ssh_config should be writable by owner
     ✔  File /etc/ssh/ssh_config should not be writable by group
     ✔  File /etc/ssh/ssh_config should not be writable by other

...

  ✔  sshd-47: Server: DebianBanner
     ✔  SSHD Configuration content should not match /DebianBanner/
  ✔  sshd-48: Server: DH primes
     ✔  Bash command test $(awk '$5 < 2047 && $5 ~ /^[0-9]+$/ { print $5 }' /etc/ssh/moduli | uniq | wc -c) -eq 0 exit_status should eq 0
     ✔  Bash command test $(awk '$5 < 2047 && $5 ~ /^[0-9]+$/ { print $5 }' /etc/ssh/moduli | uniq | wc -c) -eq 0 stdout should eq ""
     ✔  Bash command test $(awk '$5 < 2047 && $5 ~ /^[0-9]+$/ { print $5 }' /etc/ssh/moduli | uniq | wc -c) -eq 0 stderr should eq ""


Profile Summary: 4 successful controls, 62 control failures, 2 controls skipped
Test Summary: 35 successful, 63 failures, 2 skipped

Benchmark Results:
sshd-1                        0.11s
sshd-47                     0.01s

``` 

The results should be ordered by time as default.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please reopen the issue and continue the discussion.

Thank you!
__Chef InSpec Team__
