### ISSUE TITLE
Option to disable Diff output within exec

### ISSUE THREAD

**Issue by senorcinco** [inspec/inspec#1535]
### Description

When running `inspec exec`, I'd like the ability to disable the Diff output on failed tests.

### InSpec and Platform Version

Inspec 1.7.1 on Mac OS X 10.9.5

### Replication Case

    /opt/inspec/bin/inspec exec cis_oracle_db_12c_test.rb -t ssh://oracle@dbserver01.example.com

    Target:  ssh://oracle@dbserver01.example.com:22

    ×  cis-oracle-db-12c-3-4: 3.4 Ensure 'PASSWORD_REUSE_MAX' Is Greater than or Equal to '20' (Scored) (
       expected: ""
          got: "DEFAULT\nPASSWORD_REUSE_MAX\nUNLIMITED\n\nORA_STIG_PROFILE\nPASSWORD_REUSE_MAX\n10"
     
     (compared using ==)
     
     Diff:
     @@ -1 +1,8 @@
     +DEFAULT
     +PASSWORD_REUSE_MAX
     +UNLIMITED
     +
     +ORA_STIG_PROFILE
     +PASSWORD_REUSE_MAX
     +10
     )
     ×  Oracle SQLPlus query: SELECT PROFILE, RESOURCE_NAME, LIMIT
     FROM DBA_PROFILES
     WHERE RESOURCE_NAME='PASSWORD_REUSE_MAX'
     AND
     (
     LIMIT = 'DEFAULT'
     OR LIMIT = 'UNLIMITED'
     OR LIMIT < 20
     ); output should eq ""
     
     expected: ""
          got: "DEFAULT\nPASSWORD_REUSE_MAX\nUNLIMITED\n\nORA_STIG_PROFILE\nPASSWORD_REUSE_MAX\n10"
     
     (compared using ==)
     
     Diff:
     @@ -1 +1,8 @@
     +DEFAULT
     +PASSWORD_REUSE_MAX
     +UNLIMITED
     +
     +ORA_STIG_PROFILE
     +PASSWORD_REUSE_MAX
     +10
     
    ✔  cis-oracle-db-12c-3-7: 3.7 Ensure 'DBA_USERS.PASSWORD' Is Not Set to 'EXTERNAL' for Any User (Scored)
      ✔  Oracle SQLPlus query: SELECT USERNAME FROM DBA_USERS WHERE PASSWORD='EXTERNAL'; output should eq ""

    Profile Summary: 1 successful, 1 failures, 0 skipped

### Possible Solutions

    /opt/inspec/bin/inspec exec cis_oracle_db_12c_test.rb --no-diff -t ssh://oracle@dbserver01.example.com

    Target:  ssh://oracle@dbserver01.example.com:22

    ×  cis-oracle-db-12c-3-4: 3.4 Ensure 'PASSWORD_REUSE_MAX' Is Greater than or Equal to '20' (Scored) (
     ×  Oracle SQLPlus query: SELECT PROFILE, RESOURCE_NAME, LIMIT
     FROM DBA_PROFILES
     WHERE RESOURCE_NAME='PASSWORD_REUSE_MAX'
     AND
     (
     LIMIT = 'DEFAULT'
     OR LIMIT = 'UNLIMITED'
     OR LIMIT < 20
     ); output should eq ""
     
     expected: ""
          got: "DEFAULT\nPASSWORD_REUSE_MAX\nUNLIMITED\n\nORA_STIG_PROFILE\nPASSWORD_REUSE_MAX\n10"

    ✔  cis-oracle-db-12c-3-7: 3.7 Ensure 'DBA_USERS.PASSWORD' Is Not Set to 'EXTERNAL' for Any User (Scored)
      ✔  Oracle SQLPlus query: SELECT USERNAME FROM DBA_USERS WHERE PASSWORD='EXTERNAL'; output should eq ""

    Profile Summary: 1 successful, 1 failures, 0 skipped

**Comment by aaronlippold** [comment]
👍 Having been working with more profile development this week, I second this. I would even say a --compressed output could be as simple as:

```/opt/inspec/bin/inspec exec cis_oracle_db_12c_test.rb --no-diff -t ssh://oracle@dbserver01.example.com

Target:  ssh://oracle@dbserver01.example.com:22

×  cis-oracle-db-12c-3-4: 3.4 Ensure 'PASSWORD_REUSE_MAX' Is Greater than or Equal to '20'
 expected: ""
      got: "DEFAULT\nPASSWORD_REUSE_MAX\nUNLIMITED\n\nORA_STIG_PROFILE\nPASSWORD_REUSE_MAX\n10"

✔  cis-oracle-db-12c-3-7: 3.7 Ensure 'DBA_USERS.PASSWORD' Is Not Set to 'EXTERNAL' for Any User (Scored)
  ✔  Oracle SQLPlus query: SELECT USERNAME FROM DBA_USERS WHERE PASSWORD='EXTERNAL'; output should eq ""
...
...
...
```
Profile Summary: 1 successful, 1 failures, 0 skipped

**Comment by arothian** [comment]
Somewhat related use case, is if a check is being performed on a file with sensitive data, it would be great if none of the comparison content is shown at all. I think this probably mostly applies to the file resource. I'm thinking something along the lines of the common 'sensitive' flag that exists in chef for resources - https://docs.chef.io/resource_common.html

**Comment by Kamrad117** [comment]
Also looking into this, for now hacked with class variable.
Idea was to skip http response body validation if response status differs from '200' 

```ruby
control "MOBILE CONFIGS" do

  SITE_URL = ENV['TEST_SITE_URL']
  SSL_VERIFY = ENV['TEST_SSL_VERIFY'].nil? ? false : true

  TestHelper::MOBILE_CONFIGS_PARAMS.each do |name, options|
    urls = TestHelper.compose_config_urls(options[:pattern_path].to_s, SITE_URL)
    urls.each do |url|

      response = http(url, ssl_verify: SSL_VERIFY)
      describe response do

        after(:each) do |example|
          if example.exception
            @@previous_failed = true
          else
            @@previous_failed = false
          end
        end

        it "Status should cmp == 200" do
          expect(response.status).to cmp 200
        end

        it "Body should include '#{options[:testee]}' key" do
          fail "Skipping body validation due to status != 200" if @@previous_failed
          expect(response.body.force_encoding(Encoding::UTF_8)).to include(options[:testee])
        end
      end
    end
  end
end
```

Gives output: 

```
×  http GET on https://canary.horizon.tv/content/unified/RO/ron/ios/terms.js Status should cmp == 200

     expected: 200
          got: 404

     (compared using `cmp` matcher)

     ×  http GET on https://canary.horizon.tv/content/unified/RO/ron/ios/terms.js Body should include 'replayTerms' key
     Skipping body validation due to status != 200
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Comment by james-stocks** [comment]
Hi @kekaichinose -

Can we look at this one again please? Another customer has asked for this. 
If it was an option for the `file` resource and the default behaviour of outputting the full content was left unchanged, that would be fine.

**Comment by kekaichinose** [comment]
@james-stocks Thanks for bringing this to our attention. I'll add this feature request to the backlog though as priorities dictate, it may be awhile till we get to this.

**Comment by james-stocks** [comment]
@kekaichinose thanks!
I think there might be 2 reasons that the diff output is undesirable: 1. it causes huge compliance reports that waste storage and [hit API limits](https://github.com/chef/automate/issues/1417)  and 2. it might contain sensitive or personally-identifying data.

**Comment by paulcalabro** [comment]
Yeah, the diff is causing huge file sizes for me. It would be great if this was optional.

**Comment by kekaichinose** [comment]
@james-stocks we're slammed with tasks for end of Q3 right now. I'll look at prioritizing this in Q4. Thanks!
