### ISSUE TITLE
"inspec version" waits for connection timeout inside firewall

### ISSUE THREAD

**Issue by makotots** [inspec/inspec#1537]
### Description

`inspec version` command waits for timeout inside certain firewall setup.

### InSpec and Platform Version

InSpec: 1.16.0
Operating System distribution: Debian 7.0 (Wheezy) 

### Replication Case

I live in such a firewall where connection to https://rubygems.org/ times out:

```
$ time curl --connect-timeout 90 https://rubygems.org/
curl: (28) connect() timed out!

real    1m30.019s
user    0m0.004s
sys     0m0.004s
$
```

This causes `inspec version` to wait for timeout too:

```
$ time inspec version
1.16.0

real    1m0.816s <--- HERE
user    0m0.704s
sys     0m0.072s
$
```

### Possible Solutions

https://github.com/chef/inspec/issues/1538 makes `inspec version` return quickly:

```
$ time inspec version
1.16.0

real    0m1.303s <--- HERE
user    0m0.664s
sys     0m0.100s
$
```

**Comment by adamleff** [comment]
Thanks for opening this issue and for PR #1538 which will correct this.
