### ISSUE TITLE
inspec outputs full hash when testing ini style file option with [header]

### ISSUE THREAD

**Issue by shoekstra** [inspec/inspec#1541]
### Description

When testing config in a mysql conf file with a `[mysqld]` header using the `mysql_conf` resource, the entire hash is returned in the test result instead of just the config option being tested.  This could affect other INI style files too.

Instead of seeing:

```
  {"log_bin"=>"/var/log/mysql/mariadb-bin", "sync_binlog"=>"0"}
     ✔  ["sync_binlog"] should eq "0"
```

I would expect to see this (as you would without the ini style section header):

```
  MySQL Configuration
     ✔  sync_binlog should eq nil
```

### InSpec and Platform Version

inspec 1.16.1 on CentOS Linux release 7.3.1611 (Core)

### Replication Case

Create a test file (I used `/tmp/my.cnf`):

```
[mysqld]
log_bin = /var/log/mysql/mariadb-bin
sync_binlog = 0
```

Using InSpec shell:

```
inspec> describe mysql_conf('/tmp/my.cnf').mysqld do its(['sync_binlog']) { should eq '0' } end

Profile: inspec-shell
Version: (not specified)

  {"log_bin"=>"/var/log/mysql/mariadb-bin", "sync_binlog"=>"0"}
     ✔  ["sync_binlog"] should eq "0"

Test Summary: 1 successful, 0 failures, 0 skipped
```

**Comment by adamleff** [comment]
@shoekstra when #1544 is merged and released, to correct this issue, you'll want to access the data as such:

```
describe mysql_conf('/tmp/my.cnf') do
  its('mysqld.expire_logs_days') { should cmp 10 }
end

  MySQL Configuration
     ✔  mysqld.expire_logs_days should cmp == 10
```

We'll look at #1543 separately.
