### ISSUE TITLE
Properly output resource names in CLI output

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1546]
When a resource name is more than two items when split into an array, the items after the 2nd element roll into the example output.

```
inspec> mysql_conf('/tmp/my.cnf')
=> MySQL Configuration at /tmp/my.cnf

inspec> describe mysql_conf('/tmp/my.cnf') do
inspec>   its('mysqld') { should_not be nil }
inspec> end

Profile: inspec-shell
Version: (not specified)

  MySQL Configuration
     ✔  at /tmp/my.cnf mysqld should not equal nil
```

In this case, `at /tmp/my.cnf` should be on the same line as `MySQL Configuration`

**Comment by chris-rock** [comment]
@adamleff I propose we built the CLI reporter on top of our JSON reporter. Similar to what we've done with the JUnit reporter. This would allow us to load a json report and display that on CLI, too.

**Comment by chris-rock** [comment]
Please have a look at #532, #742, #839 too

**Comment by chris-rock** [comment]
Colors in travis are broken, too :-(
<img width="903" alt="screen shot 2017-03-07 at 10 18 17 am" src="https://cloud.githubusercontent.com/assets/1178413/23649654/81572a2e-031f-11e7-934a-7c8c01e1f72f.png">

**Comment by jkerry** [comment]
If I recall correctly one drawback of consuming the JSON reporter is that there will be no in progress reporting on the CLI. All of your data will dump at the end. If you go that route id suggest some kind of progress or work indicator with a cli toggle while the run is processing
