### ISSUE TITLE
Need better error message for improper inspec.yml formatting

### ISSUE THREAD

**Issue by graham1228** [inspec/inspec#1549]
### Description

If your inspec.yml file is not formatted properly you will receive an error that give little direction to what the issue is. InSpec should have a better error message.

### InSpec and Platform Version

InSpec 1.7.2
Red Hat Enterprise Linux Server release 7.3 (Maipo) 
kernel 3.10.0-514.el7.x86_64

### Replication Case

1. Create a inspec.yml file with the following
https://gist.github.com/graham1228/ede5971d7d5543ce88e52189dd43fd03

2. Execute a inspec check
`
inspec check inspec_test
`
### Possible Solutions

Add a better error message so the end user will have a better idea of what the actual problem is.

### Stacktrace

https://gist.github.com/graham1228/3282a888609fe10d99b396380d93548f

**Comment by adamleff** [comment]
Thanks for the issue, @graham1228! We can definitely make this better.

**Comment by adamleff** [comment]
New output will be:

```
"Unable to parse inspec.yml: line 8, could not find expected ':' while scanning a simple key"
```

... giving the user a clear indication that the error is caused by inspec.yml rather than getting a full stacktrack from the YAML parser.
