### ISSUE TITLE
Verify Chef Automate is reach-able after login

### ISSUE THREAD

**Issue by ffpollock** [inspec/inspec#1557]
### Description

remfpollock01:supported fpollock$ inspec compliance profiles
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.11.0/lib/bundles/inspec-compliance/http.rb:70:in `send_request': Unable to parse URI: automate.automate-demo.com/compliance/profiles/workstation-1 (RuntimeError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.11.0/lib/bundles/inspec-compliance/http.rb:20:in `get'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.11.0/lib/bundles/inspec-compliance/api.rb:16:in `profiles'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.11.0/lib/bundles/inspec-compliance/cli.rb:94:in `profiles'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.11.0/bin/inspec:12:in `<top (required)>'
	from /opt/chefdk/bin/inspec:59:in `load'
	from /opt/chefdk/bin/inspec:59:in `<main>'

Used a URL without HTTPS infront

### InSpec and Platform Version

remfpollock01:supported fpollock$ inspec version
1.11.0

### Replication Case

inspec compliance login_automate automate.automate-demo.com --user='workstation-1' --ent='automate-demo' --usertoken='KA2S39rZmpZ2xcaMTeh2tAb8svge3ob0gouXhHvNTQA'

### Possible Solutions

verify that the URL is properly formatted or reacheable

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment]
Additional URI validations were added in 1.25 and 1.26... I cannot reproduce this anymore. Please let me know if this is still an issue.
