### ISSUE TITLE
No suites run with kitchen inspec if `inspec_tests` directive is not specified.

### ISSUE THREAD

**Issue by iancward** [inspec/inspec#1565]
### Description

The documentation for kitchen-inspec provides information on how to pull suites from a Chef Compliance Server, and how to pull suites from Supermarket; however, it does not clearly provide information on how to use an inspec suite from a local cookbook.

### InSpec and Platform Version

inspec: 1.16.1
kitchen-inspec: 0.17.0
platform version: workstation is Fedora 25, running tests against a RHEL 7.1 server.

### Replication Case

Put inspec tests in a cookbook, following instructions on http://inspec.io/docs/reference/plugin_kitchen_inspec.html/, ensuring that the folder structure is correct. When I run `kitchen verify`, no suites are executed (0 successful, 0 failures, 0 skipped). Since I was not pulling suites from a compliance server nor from Supermarket, did not include an `inspec_specs` directive; however, no suites were run.

### Possible Solutions

I think the easiest solution would be to update the documentation to indicate that, when a user intends to pull a suite from a local cookbook, the `inspec_tests` directive is still needed (this should probably be in a section with the folder structure information).

Or maybe the intent was that in the absence of this directive, kitchen-inspec should still search for suites to run (since the documentation here and in kitchen-inspec doesn't explicitly state that it's required). In this case, kitchen-inspec should probably be updated to actually run the suites available automatically.

### Stacktrace

N/A.

**Comment by adamleff** [comment]
Thanks for raising this issue. We'll get the docs updated to be clearer on that, and to be on par with the docs in the kitchen-inspec README on GitHub which is a bit more clear.
