### ISSUE TITLE
YAML file extensions support only (.yml)

### ISSUE THREAD

**Issue by mr-exz** [inspec/inspec#1569]
### Description

Ignoring loading of attributes files

```
inspec exec ./test.rb --attrs ./test.yaml 
example.com should
     ∅  eq "example2.com"

     expected: "example2.com"
          got: "example.com"

     (compared using ==)
```

### InSpec and Platform Version
os: CentOS 7
inspec: 1.16.1

### Possible Solutions

here: https://github.com/chef/inspec/blob/725e0a1bc50008c8ad252bd8d5c833a7af20c606/lib/inspec/secrets/yaml.rb

You use filter for file name ```target.end_with?('.yml')```

But in wiki for YAML file we have both extensions https://en.wikipedia.org/wiki/YAML

```
Filename extension	.yaml, .yml
```

It make me confused, maybe it good for you to remove this filter for file name, because people can use other name.

**Comment by chris-rock** [comment]
Agreed @mr-exz Are you going to open a PR to fix that?

**Comment by mr-exz** [comment]
ok i'll try do it

**Comment by mr-exz** [comment]
create PR #1575

**Comment by adamleff** [comment]
New PR for this is #1589.

**Comment by mr-exz** [comment]
Thx, i forgot to linked it

**Comment by adamleff** [comment]
No worries!
