### ISSUE TITLE
Fix-up www build processes due to Gemfile change

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1586]
In #1585, the simulator gems were moved into the `www` Gemfile since they're not needed for omnibus / gem builds and were causing issues in Chef's jenkins infrastructure for multiple projects.

We need to update Rakefiles, build processes, and documentation for building the website, ensuring we can kick off the whole build from the `www` subdirectory.

**Comment by chris-rock** [comment]
That is solved via #1585
