### ISSUE TITLE
Update to the profile definition to include a primary reference

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1592]
### Description

I think we should consider updating the definition of a profile to include a primary reference which all the controls of the profile can include by default. We may not actually call it a 'reference' we could call it 'guidance' to be more in line with the general nature of the inspec.yaml file. 

name: ssh
title: Basic SSH
```guidance: 'http://<...>/myguidance.pdf'```
maintainer: Chef Software, Inc.
copyright: Chef Software, Inc.
copyright_email: support@chef.io
license: Proprietary, All rights reserved
summary: Verify that SSH Server and SSH Client are configured securely
version: 1.0.0
supports:
  - os-family: linux
depends:
  - name: profile
    path: ../path/to/profile

### InSpec and Platform Version
Core
### Possible Solutions

As a look the control object construction and I consider the definition of the control adding a ref 'http://<...>/myguidance.pdf' to every control seems to be a lot of unneeded repeated data. Especially when we consider the case of an inherited profile. If I were to dereference a control object that was part of an inherited profile object then I would expect the result of the ```profile.guidance``` to return an array of ```[guidanceA, guidanceB]``` but the profile.controlA.guidance to return ```guidanceA``` and so forth.

**Comment by adamleff** [comment]
I'm definitely not opposed to additional metadata if there's a use case present for it. Anything to allow the receivers of compliance reports to better understand the results is a huge :100: from me. But I'd like to tease out this current experience a bit more for some better shared understanding.

From what I'm reading, it sounds like you are building a profile based on a reference document and you find yourself adding the same `ref` entry to each and every control in that profile, and that feels tiresome and repetitive... am I accurately stating the experience? If that's the case, I definitely agree that there might be a better user-experience here for us to explore. 

If we wish for an entry such as this to "filter down" to each individual control, I'm personally against adding this to inspec.yml. We're just one step away from a GitHub issue asking us to support setting a global `ref` in inspec.yml but being able to disable it on a per-control basis, and I'm not crazy about that experience. I'd rather see this as a top-level DSL keyword in each controls file, and any control in that file would inherit that `ref`.

```
title "profile 1, subsection 2c"
ref 'foo doc', url: 'http://some.url.to.foo.doc.biz'

control 'foo-1-2c-1' do
   ... blah blah blah ...
  # 'foo doc' ref is inherited here
end

control 'foo-1-2c-2' do
   ref 'another doc about this control', url: 'http://a.different.url.which.gets.merged.with.the.other.ref'
   ... blah blah blah
end
```

Also, I'm against coming up with another name for it if it's truly a reference. Let's just call it what it is and merge entries... so a control would inherit from a top-level ref, and could supply its own, which would be merged into an array of refs.

Not saying we're actually going to do this 🙂  ... just airing out my own thoughts after having read this suggestion. Paging @arlimus and @chris-rock to chime in.

**Comment by aaronlippold** [comment]
Hi Adam, the Para2 is correct. And my further thoughts were generated from thinking about what the object structure - in a formal sense - would expect as we look at inheritance and instance variables of objects in the inheritance chain.

I think - as a middle ground - the top level DSL ref in each control file would be fine. 

Again, not a huge issue, copy and paste works fine just wondering if it was an area we might look at and possibly improve our implementation and or undying object model.

From the user perspective, I was saying, I am reaping this action over and over, this sucks, I only want to do this once ... :)

**Comment by adamleff** [comment]
Paging @arlimus and @chris-rock to weigh in on this.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
