### ISSUE TITLE
Processes for port resource should be a string if it's array with single element

### ISSUE THREAD

**Issue by szymonpk** [inspec/inspec#1605]
### Description

Suggested by @adamleff on slack. If processes for port is single-element array it should be possible to do:

```
  describe port(port) do
    it { should be_listening }
    its(:processes) { should match(/nginx/) }
    its(:protocols) { should include("tcp") }
  end
```

### InSpec and Platform Version

```
$ inspec version
1.17.0
```

### Possible Solutions

As suggested, If processes for port is single-element array it should be a string..

### Stacktrace

```
     ∅  processes should match /nginx/
     expected ["nginx"] to match /nginx/
     Diff:
     @@ -1,2 +1,2 @@
     -/nginx/
     +["nginx"]
```

**Comment by adamleff** [comment]
This is likely not something we'll be able to change without making the experience unpredictable... methods that exist on a String won't necessarily exist on an Array which could cause nasty Ruby errors should the result set change.

Potential workarounds:
 * use the `cmp` matcher which will strip the single element out of the array before comparison
 * call `.first` on the attribute you want to compare against in case there is more than one item in the array

We're totally open to additional suggestions, but for now, I'm going to close this issue as the `cmp` matcher will likely be what works best here. I've also proposed a new accessor for `FilterTable` in #1678 that will return single items as long as there is only one match.
