### ISSUE TITLE
Resource class inheritance error

### ISSUE THREAD

**Issue by 4-20ma** [inspec/inspec#1613]
### Description

I'm having trouble with custom resource class inheritance.

ResourceC inherits correctly from ResourceB, but ResourceA does not properly inherit from ResourceB.

It appears the resources are loaded alphabetically; inheriting from a resource with filename alphabetically before the current file loads properly whereas an error is generated for a filename later in the alphabet.

I can't figure out how to properly load the parent resource class (require, require_relative, include do not seem to work).

### InSpec and Platform Version

ruby 2.3.1p112
inspec-1.18.0
chefdk-1.2.22 with version-pinned inspec-1.11.0
OS X 10.12.3
$ brew --version
Homebrew 1.1.11-203-g1ba401039
Homebrew/homebrew-core (git revision 8c0ba; last commit 2017-03-30)

### Replication Case

Refer to [inspec-resource-error](https://github.com/4-20ma/inspec-resource-error).
### Possible Solutions

My work-around is to strategically rename the file of the parent class to load before the child class.

### Stacktrace

Included in my [inspec-resource-error](https://github.com/4-20ma/inspec-resource-error) and below:

```
    libraries/resource_a.rb:14:in `load_with_context': uninitialized constant #<Class:#<#<Class:0x007f82167d6910>:0x007f82167d6758>>::ResourceB (NameError)
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile_context.rb:146:in `instance_eval'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile_context.rb:146:in `load_with_context'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile_context.rb:135:in `load_library_file'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile_context.rb:124:in `block in load_libraries'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile_context.rb:122:in `each'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile_context.rb:122:in `load_libraries'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile.rb:171:in `load_libraries'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile.rb:425:in `load_checks_params'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile.rb:419:in `load_params'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile.rb:134:in `params'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile.rb:299:in `controls_count'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/profile.rb:270:in `check'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/lib/inspec/cli.rb:69:in `check'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    	from /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/inspec-1.18.0/bin/inspec:12:in `<top (required)>'
    	from /Users/me/.rbenv/versions/2.3.1/bin/inspec:23:in `load'
    	from /Users/me/.rbenv/versions/2.3.1/bin/inspec:23:in `<main>'
```

**Comment by adamleff** [comment]
@4-20ma thanks for submitting this issue. This is indeed a tricky one, and we see this issue with library files in Chef Cookbooks as well.

I'm not sure there's an easy fix or if it's something we'll be able to tackle near future. The most common workaround is the one you've already identified - naming in such a way to alter the load order and limiting inheritance where possible. I've frequently named my "base" class file with an underscore as the first character to make sure it gets loaded first.

Just wanted you to know we've received your issue and we'll keep it open in hopes that there is an easy solution for you. Thanks again for submitting.

**Comment by 4-20ma** [comment]
@adamleff thanks for confirming the issue. I thought I was doing something wrong with something as simple as multiple level class inheritance (related resources made sense to refactor and apply DRY) and failing to require the right library (still not sure why this doesn't work). I can work around it through appropriate file naming.

Is it possible for this to be documented in the custom resource documentation as a known issue with the suggested work-around? It's not a big deal to rename the files, but I wouldn't want someone else to have to stumble through it.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
