### ISSUE TITLE
Wrong regexp for Chef automate URL

### ISSUE THREAD

**Issue by yurylevin** [inspec/inspec#1614]
File https://github.com/chef/inspec/blob/master/lib/bundles/inspec-compliance/target.rb contains wrong regexp for uploading compliance profiles"

    def compliance_profile_name
      m = %r{^#{@config['server']}/owners/(?<owner>[^/]+)/compliance/(?<id>[^/]+)/tar$}.match(@target)
      "#{m[:owner]}/#{m[:id]}"
    end

That regexp matches standalone Compliance server, but not server, embedded into Chef automate.

Please, fix.

Thanks,
Yury.

**Comment by mhedgpeth** [comment]
I'm not sure what level of support the inspec gem currently has with automate, but it doesn't appear to be working for us. This is using 1.16

**Comment by adamleff** [comment]
InSpec 1.25 and later have fixes for the right URLs for both the Chef Compliance and the Chef Automate profile stores. This should be fixed now, but please reopen this issue you're still experiencing problems.
