### ISSUE TITLE
Extend the postgres_session resource with a 'psql' method to enable server level checks

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1629]
### Description

Many of the security checks for postgres require you to use the 'psql' command find out data about the installed RDMS. To ensure that we can capture these controls in the 'inspec style' of the DSL I suggest that we add a method to the postgres_session resource so that we can execute these system level tests.

Also, adding these function to the DSL resources ensures that users do not have to set environment vars, or .dotfiles to store password information for elevated privilege commands and or try to push the same onto a remote node for remote test execution ( i.e. PGPASSWORD or ~/.pgpass etc )

Examples of such checks are:
```
V-72841
As the database administrator, run the following SQL: 
$ psql -c "SHOW port" 
If the currently defined port configuration is deemed prohibited, this is a finding.
```
```
V-72845
To list the version of installed PostgreSQL using psql: 
$ sudo su - postgres 
$ psql --version 
```
```
V-72855
Only owners of objects can change them. To view all functions, triggers, and trigger 
procedures, their ownership and source, as the database administrator (shown here 
as "postgres") run the following SQL:
$ sudo su - postgres
$ psql -x -c "\df+"
Only the OS database owner user (shown here as "postgres") or a PostgreSQL 
superuser can change links to external software. As the database administrator 
(shown here as "postgres"), check the permissions of configuration files for 
the database:
$ sudo su - postgres
$ ls -la ${PGDATA?}
If any files are not owned by the database owner or have permissions allowing 
others to modify (write) configuration files, this is a finding.
```
```
V-72859
$ sudo su - postgres
$ psql -c '\du'
Review all roles and their associated privileges. If any roles' privileges exceed 
those documented, this is a finding.
Next, as the database administrator (shown here as "postgres"), check the configured 
privileges for tables and columns by
running the following SQL:
$ sudo su - postgres
$ psql -c '\dp'
Review all access privileges and column access privileges list. If any roles' privileges 
exceed those documented, this is a finding. 
```
Right now we can accomplish this test using the command resource and a little trick from here: https://github.com/chef/inspec/blob/master/lib/resources/postgres_session.rb#L47 and using attributes and #{} in the command string but I think the below example is more where we should go.

```
note: {DB} could be an optional param 
describe postgres_session(USER,PASS,{DB}).psql("SHOW ports") do 
  its ('stdout') { should include '5432'}
end
```

In the more complex examples, V-72855 and V-72859, we will have to use an 'each' itterator and use a an attribute with an array or hash of accepted values to test that these values and only these values exist in the returned dataset. ( very close to some of the Windows user checks in the CIS Benchmarks )

To read the full text of the control checks, please see the attached pdf.
[Postgres-9-stig.pdf](https://github.com/chef/inspec/files/895092/Postgres-9-stig.pdf)

Like examples exist for the MySQL STIG, the Oracle STIG all other RDMS. 

I would suggest that we add the 'rdms command function' to each of the resources so folks do not have to hack and pass via the command resource.

**Comment by adamleff** [comment]
This can be accomplished with the `query` method on the `postgres_session` resource.
