### ISSUE TITLE
Extend the package and packages resource to include a 'latest' param in the verbs.

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1630]
### Description
Some of the tests I have been working on implementing in the benchmarks are displaying a common theme of ensuring the currently installed version of the package is the 'latest' available from your package repo and is at least version x and is not a devel, rc or other pre GA package release. 

We have mostly all the elements in place to fully code these checks in inspec - with the 'patch' plugin - and existing resources, however, I feel that we should move the patch resource work into the mainline and then extend the package and packages resource to use both the package and patch resources to provide the natural test statements of the InSpec DSL.

### Example Tests
```
V-72845
If new packages are available for PostgreSQL, they can be reviewed in the package manager appropriate for the server operating system: 
To list the version of installed PostgreSQL using psql: 
$ sudo su - postgres 
$ psql --version 
To list the current version of software for RPM: 
$ rpm -qa | grep postgres 
...
If PostgreSQL is not at the latest version, this is a finding. 
If PostgreSQL is not at the latest version and the evaluated version has CVEs (IAVAs), then this is a CAT I finding. 
 ```
The spirt of the test is trying to get us to this:
```
describe package('x') do
  its ('version') { should be 'latest' }
  its ('version') { should be >= 9.5 }
  its ('version') { should_not include /DEV||RC/}
end
```
[Postgres-9-stig.pdf](https://github.com/chef/inspec/files/895092/Postgres-9-stig.pdf)

**Comment by aaronlippold** [comment]
@chris-rock @arlimus Was a decision on if we wanted to merge the patching work into the package and packages resources reached?

**Comment by adamleff** [comment]
I'm concerned that supporting `latest` will lead to possibly-incorrect audit results. What `latest` means could differ on each host depending on what repository/repositories the OS package manager is configured to use. If a host is configured to use a stale repo, and the latest PostgreSQL package there is 9.2, that's not really "latest" - but it is for that particular host.

From a security/audit standpoint, it feels like we should be expecting an exact version number to be used in these cases.

**Comment by aaronlippold** [comment]
@adamleff I hear you. What latest means will differ from host to host, but that is a good thing. It is actually changing from distro version to distro version right? Which is the expected behavior.  

So most guidance and even vendors will back patch the distro supported version - RHEL for example - the maintained major version of a package and do a version lock on the major version. All the below - just to outline my thinking / perspective - is that the below is exactly what the majority of security guidance would prescribe given an enterprise supported, vendor maintained baseline. 
```
describe package('x') do
  its ('version') { should be 'latest' }
  its ('version') { should be >= 9.5 }
  its ('version') { should_not include /DEV||RC/}
  its('repo') { should match /PGSQL_REPO/ } # future cool
  its('cve') { should be nil } # future cool
end
```
We are not always on 'latest' ( in terms of the upstream version number) when it comes to operational systems and in fact usually are not on the "latest" version number because the "professional open source" workflow process is about both security, stability and binary compatibility, etc etc. 

So the guidance from the audit standpoint is:
- use only the vendor supported package ( per the SLA )
- use the repo that is "approved" for the organization
- use the latest package available from the approved repo from the approved vendor, that:
  a. maintains operational function
  b. ... next rule
  c. ... next rule

**Comment by adamleff** [comment]
Even with that explanation, I'm still 👎  on introducing a `latest` keyword. How a host's package repository is configured should not determine whether the host is compliant or not. If a host gets configured to use both a vendor-provided repo and a secondary repo, and there's a newer package in the secondary repo and someone `yum update`'s that host, then they'll have a newer package than what is required by the audit criteria you defined.

Properly defining the package version is the only way to make the tests accurate and meet the audit criteria you're defining. Using attributes to alter the version between hosts, or using the `os` resource to dynamically define the package version depending on the OS version, is likely the right way to go.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
