### ISSUE TITLE
os_env resource on remote hosts

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1641]
### Description

( related? https://github.com/chef/inspec/issues/236 )

The os_env resource does not seem to be functioning correctly when doing remote tests. When I use the resource in the 'inspec shell' on the target host it returns the correct content, but when I use it to preform a remote test on that same host, it returns 'nil'.

Update: I also tried running this remotely with the --sudo flag - same error.

### InSpec and Platform Version

current

### Replication Case
```
describe os_env('http_proxy') do
    its('content') { should eq 'http://gatekeeper.mitre.org:80' }
end
```
When I test remotely I get:

```
inspec exec proxy.rb -t docker://b6e7899f7aff
WARN: Unresolved specs during Gem::Specification.reset:
      thor (~> 0.19)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Profile: tests from proxy.rb
Version: (not specified)
Target:  docker://b6e7899f7aff8628240b03669fdb771f6f09007ffdeccc482329919041f0d11c

  Environment variable
     ✔  PATH split should not include ""
     ✔  PATH split should not include "."
  Environment variable
     ∅  http_proxy content should eq "http://gatekeeper.mitre.org:80"
     
expected: "http://gatekeeper.mitre.org:80"
          got: nil

     (compared using ==)

Test Summary: 2 successful, 1 failures, 0 skipped
```
When I use the shell on the container I get:

```
inspec> describe os_env('http_proxy') do
inspec>   its('content') { should eq 'https://gatekeeper.mitre.org:80' }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Environment variable
     ✔  http_proxy content should eq "https://gatekeeper.mitre.org:80"

Test Summary: 1 successful, 0 failures, 0 skipped
```
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment]
@aaronlippold I think this is similar to the recently-closed issue #1784. InSpec does not use a login shell to do its work, so if you are setting your `http_proxy` variables in something like `/etc/profile.d`, then that would explain this behavior. Unfortunately, your replication steps did not detail where these variables are set.

Given that this works inside the shell on the container (and that means you're in a login shell), I believe this confirms my hypothesis. There are currently no plans to change the shell behavior (as it could affect our ability to reliably get STDOUT and STDERR separately), so I'm going to close this issue for now.

**Comment by aaronlippold** [comment]
If I recall the environment variables for being set in something like that the user bash RC or bash. Profile

**Comment by aaronlippold** [comment]
However another user was having the same issue and the trick was basically finding the right place on the remote host to set the environment variables so inspec would find them. The conversation is in the slack Channel
