### ISSUE TITLE
sshd_config resource not responding to expected commands

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1642]
### Description

I have these tests:

```
describe sshd_config do
  it { should exist }
  it { should be_file }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its('mode') { should cmp '0600' }
end
```

Which I would expect to work with either with 'ssh_config' or 'sshd_config' resource. 

Really all resources of this nature that are abstracting the specific path of a config file to ensure an active test on the config file used by the running process to avoid the 'stale validation' problem or the attack vector or mistake of the process running on the system with a non-standard config file location. 

In reality to have a fully flushed test case I would actually have both blocks run, one to cover the passive test and one to cover the active test. 

### InSpec and Platform Version

1.19.2

### Replication Case

Generate these two blocks of tests.

```
describe file('/etc/ssh/sshd_config') do
  it { should exist }
  it { should be_file }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its('mode') { should cmp '0600' }
end

describe sshd_config do
  it { should exist }
  it { should be_file }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its('mode') { should cmp '0600' }
end
```
Result:
```
  File /etc/ssh/sshd_config
     ✔  should exist
     ✔  should be file
     ✔  should be owned by "root"
     ✔  should be grouped into "root"
     ✔  mode should cmp == "0600"
  SSH Configuration
     ∅  should exist
     expected SSH Configuration to exist but it does not respond to either `exist?` or `exists?`
     ∅  should be file
     expected SSH Configuration to respond to `file?`
     ∅  should be owned by "root"
     expected SSH Configuration to respond to `owned_by?`
     ∅  should be grouped into "root"
     expected SSH Configuration to respond to `grouped_into?`
     ∅  wrong number of arguments (given 1, expected 0)
```
### Possible Solutions

I believe it is valid that the end user should expect both blocks to produce the same results as we should prefer that they use the second block as per the DSL style guide.

Possible end state that address the concept of both 'passive' and 'active' testing with respect to both the service and the running process.

```
describe sshd_config.config do
  it { should exist }
  it { should be_file }
  it { should be_owned_by 'root' }
  it { should be_grouped_into 'root' }
  its('mode') { should cmp '0600' }
end
```

**Comment by aaronlippold** [comment]
This brings up another thought that perhaps one of the backend things we could have the resource WARN: on is that a well established service - such as SSHD or APACHE or any process that has a well known standard config file location, etc. is using a non-standard config file location.

**Comment by aaronlippold** [comment]
After talking with @arlimus on this, the better solution path would be to add a method to the resource such that we could have ```sshd_config.file do``` or ```sshd_config.config do ``` to say 'the file that this service / resource is using' so we don't have unexpected side-effects.

@arlimus the more I look at this I think all resources should have this method on them.

**Comment by adamleff** [comment]
I disagree with this approach. The `sshd_config` resource tests the configuration of SSHD. The fact that we do so by reading in a file is an implementation detail that the user should not have to worry about. In fact, if it became possible for us to *actively* test the SSHD process configuration by interrogating the running SSHD process without needing to read in a config file, we should be able to switch out the underlying mechanism for this resource without the user even noticing.

I would tentatively support a `#file` method that returns a InSpec File resource for resources where we're interrogating a file, but assuming that all resources should have this method on them (or a similar method) is jumping the gun, in my opinion. I'd rather understand the use cases before any blanket changes like that are considered.

Personally, I'd rather we expose a method that returns a string that indicates what config file we read from (in the event we read from a file) and let the user make the determination on how best to use that. Exposing the implementation details is a code smell to me.

**Comment by aaronlippold** [comment]
I agree with you that we could put this under the covers and perhaps just add a 'should_be used_by' or something along those lines.

The example here is what we were thinking : https://askubuntu.com/questions/369389/how-do-i-check-that-a-configuration-file-has-been-read 

In my viewpoint, the use case is to ensure  we can validate that a process was started with the config file that was expected. The risk that we are trying to cover is that an insider, a hacker, malware etc. could compromise a system and change the config files that process are using. 

What I am suggesting is that on the back end we implement a way to actually interrogate the active process to find out which config file was actually read when the process started and thusly be able to validate that the compliance tests that we are running are both set correctly in the expected config file and the config file that was used when the process started. If they are not then we have a possible breach. 

SSHD, httpd, nginix, etc are all good targets for this type of attack. This is what @arlimus and I mean when we say the 'active' test or validation and the 'passive' test. Active actually asks the process to report which file it read and tests that file, the passive test uses the expected configuration file.

**Comment by adamleff** [comment]
Yes, @aaronlippold, I understand the use case and the implications... and I do know the difference between active and passive assertions. 🙂 

However, in terms of "doing one thing and doing it well," I am still against adding file-like methods to the `sshd_config` resource. Until we have resources that have the capabilities of doing both active and passive checks, exposing implementation-level details to the end user will only cause backward compatibility issues in the future when we decide to change the actual implementation itself. The contract between InSpec and the user is that if they want to check an sshd configuration parameter, they can use the `sshd_config` resource and know that the configuration is the way they intend.

Again, I would support a method that returns the path to the file that was read when the resource was instantiated and then the user can take that information to create additional controls and assertions.

**Comment by adamleff** [comment]
@arlimus and @chris-rock, this requires your input. I'm still opposed to making the `ssh(?d)_config` resources look/feel like `file` resources, and I dislike methods on resources returning other resource objects since that feels too implementation-heavy for an end-user (and backs us into a corner should we want to change resource implementation in the future).

I'm all for a method that returns the filename though and then a user can take that and use that in a `file` resource.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
