### ISSUE TITLE
Extend the 'kernel_module' resource to support blacklisting

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1643]
### Description

I believe it would be useful to add support for checking the blacklisting of modules. 

It seems that there are a few ways to accomplish this:

1. Via a fake install, see: https://wiki.debian.org/KernelModuleBlacklisting
2. Using the blacklist command in modprobe.d/ see: https://linux-audit.com/kernel-hardening-disable-and-blacklist-linux-modules/

In the end I think, regardless of the approach used, I think we could have the resource just get a list of the 'blacklisted' modules to keep in memory. I am assuming that we really should not need to know which approach was used from the validation perspective. 

```
modprobe --showconfig | grep "^install" | grep "/bin" | grep true
modprobe --showconfig | grep "^install" | grep "/bin" | grep false
modprobe --showconfig | grep blacklist
```

### InSpec and Platform Version

all

### Current
I would like to change this so that the we could have this as the standard inspec description:
```
describe kernel_module('freevxfs') do
  it { should_not be_loaded }
  it { should be_disabled }
  it { should be_blacklisted }
end
```
So that we don't have to write tests that are specially tied to an implementation strategy on the platform/system and also to ensure that no matter which way the module is blacklisted, I actually find it.

To ensure this at the moment I have to write multiple tests:
```
describe.one do 
  describe command('/sbin/modprobe -n -v freevxfs') do
    its(:stdout) { should match /install \/bin\/true/ }
  end
  describe command('/sbin/modprobe -n -v freevxfs') do
    its(:stdout) { should match /install \/bin\/false/ }
  end
  describe command('/sbin/modprobe --showconfig | grep blacklist') do
    its(:stdout) { should contain /freevxfs/ }
  end
end
```

**Comment by adamleff** [comment]
PR #1798 in flight for this.
