### ISSUE TITLE
gem resource :chef symbol isn't valid on Windows

### ISSUE THREAD

**Issue by kpersohn** [inspec/inspec#1645]
### Description

On Windows platforms, `:chef` does not resolve to the correct `gem_binary` location causing InSpec to fail to find gems installed to Chef Omnibus embedded Ruby. 

### InSpec and Platform Version

1.19.1
Windows 7 x64

### Replication Case

```
  describe gem('chef-vault', :chef) do
    it { should be_installed }
  end
```
fails; however this works:
```
  describe gem('chef-vault', 'C:\opscode\chef\embedded\bin\gem.cmd') do
    it { should be_installed }
  end
```

### Possible Solutions

Perhaps https://github.com/chef/inspec/blob/master/lib/resources/gem.rb#L26 just needs `.cmd` appended?

@nvwls Thoughts?

**Comment by adamleff** [comment]
@kpersohn thanks for submitting this issue! I've put forth #1650 to fix this.
