### ISSUE TITLE
RFC: Harmonize vendoring mechanism

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1659]
### Description

As the following example demonstrates, the vendoring process just downloads the profile as is (e.g. git, tar or zip). This has a couple of disadvantages:

 - difficult to browse through archives via text editor
 - tars in tars is not a preferred approach
 - hashs are different for the same profile for different packaging (See #1658)

```
examples/acme-inspec-profile
├── LICENSE
├── README.md
├── controls
│   ├── hardening.rb
│   ├── patch.rb
│   └── ssl.rb
├── inspec.lock
├── inspec.yml
└── vendor
    ├── 32fc687e121e85857078fda71d5b65f57a01c1b3cac86847c036f391e92de48d.tar.gz
    ├── 9615e20f6ee30c09a953ff2b14688652d7632eb1
    │   └── d20170413-28720-qwlh39
    │       ├── CONTRIBUTING.md
    │       ├── ChefCompliance.png
    │       ├── Gemfile
    │       ├── InSpec+Update.png
    │       ├── LICENSE
    │       ├── README.md
    │       ├── Rakefile
    │       ├── Windows+Update.png
    │       ├── controls
    │       │   └── patches.rb
    │       ├── inspec.yml
    │       └── libraries
    │           └── windows_updates.rb
    └── d84b1cef6a0aa99656030c3e8a9cbe749feef014
        └── d20170413-28720-1gvalg4
            ├── CHANGELOG.md
            ├── Gemfile
            ├── LICENSE
            ├── README.md
            ├── Rakefile
            ├── controls
            │   ├── ssh_spec.rb
            │   └── sshd_spec.rb
            ├── inspec.yml
            └── libraries
                └── ssh_crypto.rb

16 directories, 44 files
```

### Possible Solutions

Going forward, we should extract all tars and place pure directories. Therefore archives will be extracted and git history will be removed. In combination with the hash update defined in ##1658 we could make the process way simpler. Since the hashing and the content of the vendor directory is changing, we would need to bump the version of the lockfile in `inspec.lock`.

**Comment by adamleff** [comment]
💯  on extracting content during the vendoring process instead of during exec/archive. This will also help the current situation with Habitat InSpec packages requiring elevated privileges just to extract/cache dependencies.

**Comment by stevendanna** [comment]
I'm 👍 on always extracting.  I can't remember why we went with the mixed format originally, but I think the debug-ability of the always-extracted form is definitely worth it.

Would part of this also include changing the loading code such that all profiles were always loaded from their extracted representation?  I /think/ that would negate the need for different file_providers.

**Comment by arlimus** [comment]
Make sure to include local paths: https://github.com/chef/inspec/issues/1687

**Comment by arlimus** [comment]
Fixes: https://github.com/chef/inspec/issues/2028

**Comment by jeremymv2** [comment]
@arlimus @chris-rock one thing we should keep in mind is the byte length of each entry name in the archive because of the 100 char limit: https://stackoverflow.com/a/2079165

An implementation to handle reading archives with those type entries is https://stackoverflow.com/a/19139114

As you can see, we're currently affected by this in 1.32.1:
```
/tmp$ inspec exec d594f6003f6298d576132939f4bc92410130f7e3184163e26235bdd6ed6d7cf3.tar.gz
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Frame number: 0/13

From: /Users/jmiller/.chefdk/gem/ruby/2.4.0/gems/inspec-1.32.1/lib/inspec/profile.rb @ line 63 Inspec::Profile.for_path:

    54: def self.for_path(path, opts)
    55:   file_provider = FileProvider.for_path(path)
    56:   rp = file_provider.relative_provider
    57:
    58:   # copy embedded dependecies into global cache
    59:   copy_deps_into_cache(rp, opts) unless opts[:cache].nil?
    60:
    61:   reader = Inspec::SourceReader.resolve(rp)
    62:   require 'pry';binding.pry
 => 63:   if reader.nil?
    64:     raise("Don't understand inspec profile in #{path}, it " \
    65:          "doesn't look like a supported profile structure.")
    66:   end
    67:   new(reader, opts)
    68: end

[1] pry(Inspec::Profile)> rp
=> #<Inspec::RelativeFileProvider:0x007f99dcd25348
 @files=
  ["controls/cisCentos7v2.rb",
   "README.md",
   "inspec.yml",
   "inspec.lock",
   "vendor/PaxHeaders.0/d552127c11d33306bf763fe310ca0810a417e38d27bec211865976623"],
 @parent=
  #<Inspec::TarProvider:0x007f99dcd2f4d8
   @contents=
    {"syou/ge-cis-centos7-v2/vendor/PaxHeaders.0/d552127c11d33306bf763fe310ca0810a417e38d27bec211865976623"=>nil,
```

The vendor'd path above is limited to 100 chars and contents is therefore nil
