### ISSUE TITLE
Possible error in lib/resources/processes.rb?

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1660]
### Description

```/usr/local/lib/ruby/gems/2.4.0/gems/inspec-1.20.0/lib/resources/processes.rb:29: warning: regular expression has redundant nested repeat operator '*': /^(\/[^\/]*)**(\s|$)/```

Not sure if this is just a fluke or something that should be looked at.

**Comment by adamleff** [comment]
This RegEx is no longer in use, at least in 1.26.
