### ISSUE TITLE
inspec shell: help sshd_config failing :(

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#1664]
### Description

I was playing around in the shell and noticed that help sshd_config is failing. help ssh_config works fine.

### InSpec and Platform Version
1.20

### Replication Case

open up the inspec shell
type help shhd_config

### Stacktrace

 inspec git:(master) b inspec shell -i ~/playground/vagrant-playground/.vagrant/machines/default/virtualbox/private_key -t ssh://vagrant@192.168.33.10
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  ubuntu
    OS family:  debian
    OS release: 12.04

inspec> help sshd_config
NoMethodError: undefined method `lines' for nil:NilClass
from /Users/vjeffrey/code/compliance/inspec/lib/inspec/shell.rb:83:in `print_example'
inspec> exit
➜  inspec git:(master) b inspec version
1.20.0

**Comment by adamleff** [comment]
Well, that stinks!

Probably has to do with the fact that `sshd_config` subclasses `ssh_config` I believe. Thanks for logging the issue 🙂

**Comment by adamleff** [comment]
Issue with `sshd_config` is fixed, but the core issue of `help` throwing an exception where there is no description still needs to be addressed.
