### ISSUE TITLE
RFE: postgres_session/mysql_session/mssql_session resource to handle parsing of csv returns of result sets

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1672]
### Description

Many of the control checks for postgres require you to execute a set of SQL and ensure that the rows and columns in the result set either contain, match or have a value or values - or the opposite, do not contain, match or have a value. 

I suggest that we expand the *_session resources to be able to parse cvs results sets so that we can have statements such as:

```
its('row|rows') { should|should_not be|match|contain /value(s)/ | 'nil' }
its('column|columns') { should|should_not be|match|contain /value(s)/ | 'nil' }
its('column=colname') { should|should_not be|match|contain /value(s)/ | 'nil' }
its('result_set') { should|should_not be|match|contain /value(s)/| 'nil' }
its('ERROR') { should|should_not be|match|contain /value(s)/ }
```
or the ERROR set
```
ERROR: syntax error at or near \"CREAT\"...
```
**Note** The '|' are to account for when it is logical to to switch the tense of the object to reflect the 'matcher' that is being used. i.e. ```its('row') { should_not contain '-1' }``` for example. Not that I would expect ```its('row|rows') ``` to be the actual statement :)
### InSpec and Platform Version

all

### Possible Solutions

```
psql -t -F, -A -c "select * from public.test"
1,aaaa
2,bbb
```
or
```
psql -t -F, -A -c "select * from public.test" -o /tmp/test.csv
```
mysql has similar functions and command line options.

<https://dev.mysql.com/doc/refman/5.7/en/select-into.html>

however it does not seem it has as a direct an option as postgresql does given that we would have to parse a secondary file which may or may not be a bad thing.

MSSQL also, as referenced here:

<http://stackoverflow.com/questions/425379/how-to-export-data-as-csv-format-from-sql-server-using-sqlcmd>

**Comment by aaronlippold** [comment]
row = 1 by n array
rows = n x m array
column = n x 1 array 
resultset = rows = n x m array 
ERROR is a special case, that will be a String

**Comment by adamleff** [comment]
Let's steer clear of the details of how the data might be stored or returned (i.e. the 'array' statements in the prior comment) and implementation detail of how we might collect the data, and instead talk more about the problem you're trying to solve.

Could you provide more specific problem statements as to what you're trying to solve? For example, I'm having a hard time coming up with a case where I'd run a SQL query and just match on a value from ANY column... I'd like need to care about the column name if there's more than one column.

So can we start with some stories on what you're looking to do?

Example: "I need to run a query that can return any number of rows, 3 columns, and I need to check to see that there is NOT a particular value in the 3rd column"

Example: "I need to run a query that can return any number of rows, and I want to write a test on the number of rows returned."

Example: "I need to run a query that can return any number of rows, and any number of columns, and I need to know how many rows match a particular value in column A and column C"

As I was writing those fake examples, and as I think as we dig into the specifics a bit more, we'll find that SQL is already best-suited to query the data and InSpec should likely care more about the row count returned - i.e. let SQL do the comparison/sorting/filtering, and let InSpec care more about the quantity of data returned.

**Comment by aaronlippold** [comment]
RRF: @adamleff @arlimus @chris-rock @atomic111 ( i.e. contributors to the db resources ) - am I off the mark here?

All those are valid examples, the general question in my mind is, if we say that we want users to use plain SQL to accomplish this we are diverging from the work pattern of resources. If would be like saying we just want to use the command resource for pretty much everything. 

We have other examples where we have created a resource where the command resource would work: user, users, etc_passwd, etc_group, etc_shaddow, group, os_env, file etc in order to keep the controls in the resource paradigm/model. 

In my way of thinking, if we are going to work with 'SQL statements and results' we should try to enforce the same construction and workflow paradigm as for other resources in the library.

**Comment by adamleff** [comment]
@aaronlippold speaking for me only and not my fellow maintainers, I'm going to err on using the right tool for the right job. All the resources you mentioned in your examples were created because there was a use case for getting the data in question, parsing it, and retrieving a specific value because of a need. If there was a UNIX/Linux command that solely returned the UID for a given user in /etc/passwd and it was supported cross-platform, I can guarantee we'd be using that instead of parsing the file.

A RDMBS's query engine is going to be much more effective at retrieving, sorting, and returning data than we will be able to in Ruby. So I'm asking if there is a particular use case where providing a well-crafted SQL statement and checking the row count isn't good enough, and I think it's a perfectly reasonable question to ask. Adding what you're describing adds complexity and maintenance cost, and I think we'd be perfectly happy to do it if there's a reason to do so.

**Comment by adamleff** [comment]
Closing this issue as PRs such as #1857 are in flight that address some of these concerns.

**Comment by aaronlippold** [comment]
I believe the current PR that Chris is working on covers a lot of the CSV
work then I'm talking about here in terms of being able to parse results of
database SQL commands. I think no I haven't looked deeply into everything
Chris's implementing that most of it should be covered but if not we can
use this as a reference to push out updates to the current PR he is working.
