### ISSUE TITLE
Add a --tag and --tags flag which operates just like the --controls flag does.

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1677]
### Description  

I would like to be able to pass a --tag or --tags flag to the InSpec CLI to instruct a profile to only execute controls with the provided tag or tags.

### Use Case  

Assume I have a profile or a meta-profile that supports multiple platforms which have different controls to test a higher class of controls - such as ssl or ssh or even more generically 'authentication' or 'PKI'. 

If I wanted to setup a job that ensures these groups of tests are run and reported on but I don't want the whole test suite exercised, i think this would be a very effect way to achieve that goal.

**Comment by aaronlippold** [comment]
@adamleff @arlimus @chris-rock  any thoughts on this? Given a conversation with @tvaughan, if this isn't too hard to implement, it could have very positive effect.

**Comment by aaronlippold** [comment]
Use case: 

A project has selected 51 critical controls ( i.e. controls taged with nist controls ) for the multiple application stacks and I will be using dependent profiles to run validation tests up and down the stacks ( AWS -> OS -> App -> Ports/Protocols ) and the ask is that we focus our testing on all controls for the MVP. 

Assume I have for example:
 - RHEL_7_baseline
- nginx_baseline
- aws_foundations_baseline
- application_x_baseline

And I have a list of 10 NIST tags as my critical controls: [AC-1, IA-9, SI-4, SI-4 (3), ....]

Assume also the profiles have a common shared tag in the following format:
`tag nist: ['AC-1','AC-3','rev_4]`
or
`tag nist: ['SI-4', 'SI-4 (3)', 'rev_4']`

The best approach is to create a app_x_core_baseline dependent profile which depends on the four profiles above and I can pass the list of tags. When I run `inspec exec app_x_core_baseline --tags=tags.yml ` inspec will only add the controls in each of the profiles with tags in the list, executing only the controls needed and not having to copy, hack or do trickery.

This would allow my team to build standard profiles but meet the need to 'sub-select' the 'desired core controls' for the MVP from multiple profiles via tags rather than having to hack the control name or copy and paste data to meet the use case. 

When we are beyond MVP or have met the use-case we can drop the 'execution filter' in production and run full profiles.

**Comment by jquick** [comment]
This is a interesting Idea. This would be pretty easy to add when we do the overhaul the `--controls` section.

**Comment by aaronlippold** [comment]
That is great. Please drop me a link to the overall RFC issue so I can track it

**Comment by chris-rock** [comment]
I think this is a good idea. As @jquick mentioned, we need to overhaul the current selector for controls. tags are similar but slightly more complex. We need to be careful that we deal with the various types properly.

**Comment by chris-rock** [comment]
While thinking about it, we may want to support negative filtering as well. eg. run all controls but not the ones with tag `abc`

**Comment by aaronlippold** [comment]
Totally agree.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by aaronlippold** [comment]
This also connects to updating how we add tests to the runner with --tags and --controls. In the end the updates that @jquick is working on with how we load things onto the running durning the execution should help both of these run much more efficiently.

**Comment by aaronlippold** [comment]
bumping again and putting on the community review

**Comment by aaronlippold** [comment]
bump - now that inputs are refactored - can we push on this back on the todo list?

**Comment by jerryaldrichiii** [comment]
Adding @kekaichinose to this issue :D

**Comment by kekaichinose** [comment]
Hi @aaronlippold, we unfortunately do not have any plans to address this in the near future.

We apologize that we have not addressed your issue, but if it's still something you're interested in solving, you're welcome to submit a PR for it. If you decide to submit a PR, please reference this issue so we can re-open and track it and the PR to completion.

Thank you!
__Chef InSpec Team__
