### ISSUE TITLE
Inspec Shell Enhancement - Show universal matchers on HELP MATCHERS command

### ISSUE THREAD

**Issue by hannah-radish** [inspec/inspec#1684]
### Description

Show universal matchers on **help matchers** command in the Inspec Shell. Would be cool to have a similar behavior like **help resources**

@adamleff

**Comment by hannah-radish** [comment]
@arlimus @chris-rock 
Need your input. IE: are you cool with this suggestion?

**Comment by adamleff** [comment]
This shouldn't be too hard to do, and I'd be happy to do it. We can provide helpful information on the following matchers:

* `be`
* `cmp`
* `eq`
* `include`
* `match`

... just like this page on the docs site but in abbreviated form: http://inspec.io/docs/reference/matchers/

**Comment by vjeffrey** [comment]
yes please please please!

**Comment by chris-rock** [comment]
I love that idea. We should focus on generally available matchers then. I also would love to see this attached to resource documentation, too.

To make this technically right, we need to move matcher documentation into source code and attach this to each matcher as a method. Then we can read that our similar to our resource docs.

**Comment by adamleff** [comment]
I agree with the "technically right" approach, but can we approach this iteratively first? I think having a simple "if the parameter passed in to 'help' is 'matchers'" approach to provide textual help for the 5 matchers listed above is a great MVP, and then we can iterate on it later.

**Comment by chris-rock** [comment]
@adamleff sounds like a good first iteration
