### ISSUE TITLE
vendor local profiles for archive

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1687]
### Description

We decided that local profiles `path: /path/to/profiles` are not copied over to `vendor` directory, since its easier for development. This is not true if the profile is packaged for upload to the compliance server.

### InSpec and Platform Version

1.20.0

### Replication Case

Try to run `inspec archive examples/inheritance` and take a look into the tar file

### Possible Solutions

Force vendoring of local paths and make this a default for archive generation.

**Comment by primate-2016** [comment]
Hi there - is there any update to this? We've run into this problem due to some complexities with the way we need to package profiles. Cheers.

**Comment by arlimus** [comment]
Not yet @primate-2016 but we are working on updating the vendor mechanism. This is definitely a part of it :) We are reaching to complete https://github.com/chef/inspec/issues/1659 which this falls into.

Happy to take contributions if someone is faster.

**Comment by jerryaldrichiii** [comment]
@primate-2016 when #3286 is merged and released `path://` will vendor profiles into `vendor/`. Let me know if this doesn't solve your issue.
