### ISSUE TITLE
Adding windows domain users to users resource

### ISSUE THREAD

**Issue by Happycoil** [inspec/inspec#1688]
I'm planning to take a stab at https://github.com/chef/inspec/blob/master/lib/resources/users.rb#L564, but the solution will probably look kinda strange. Do you have any work on this planned?

The obvious solution is to query Win32_UserAccount, but that has a potentially _huge_ problem in that this might return thousands (or even hundreds of thousands) of objects in some enterprises because `Domain Users` is added to the local `Users` group when a server is domain joined.

I think we can get around this potential problem by first querying all local groups for members with COM object arcana like in https://github.com/chef/inspec/pull/1681 (this doesn't recurse into domain groups), and then query Win32_UserAccount for only those users.

Since my primary goal is to enable querying local groups for domain account membership an alternative solution could be a dedicated resource like `etc_group`.

Thoughts?

cc @chris-rock

**Comment by chris-rock** [comment]
This is a dup of https://github.com/chef/inspec/issues/1218. lets move the discussion to that ticket. I think using `Win32_UserAccount` is not the best solution. We've done that before and it is really slow. Is there any reason why ADSI is not working? See https://msdn.microsoft.com/en-us/library/aa746512(v=vs.85).aspx and https://github.com/chef/inspec/blob/master/lib/resources/users.rb#L612-L613

**Comment by chris-rock** [comment]
Close this since it is a dup of #1218
