### ISSUE TITLE
systemctl is-enabled fails on Debian for SysV units

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1708]
### Description

On Debian 8, a SysV unit (such as the stock `apache2` package) will fail the `systemctl is-enabled` command because Debian 8's systemd doesn't include the `systemd-sysv-install` shim.

### InSpec and Platform Version

1.19.1

### Replication Case

**recipe:**

```ruby
package 'apache2'

service 'apache2' do
  action :enable
end
```

**test:**

```ruby
describe service('apache2') do
  it { should be_enabled }
end
```

**inspec output:**

```
  Service apache2
     ∅  should be enabled
     expected that `Service apache2` is enabled
```

**manual command run:**

```
root@default-debian-87:~# systemctl is-enabled apache2
Failed to get unit file state for apache2.service: No such file or directory
root@default-debian-87:~# echo $?
1
```

### Possible Solutions

It would be great if InSpec could detect this failure and try the init script in `/etc/init.d` as a fallback.

**Comment by jerryaldrichiii** [comment]
Great catch @adamleff! I was unable to reproduce this on Debian 8.10, but I see this is an issue on 8.7.

I can't see a way to verify the service is enabled using the `/etc/init.d/apache2` script. Any objections to catching that error and attempting `sysv_service('apache2').enabled?` instead? This uses the files in `/etc/rc*.d` which will give the answer we are looking for.

**Comment by adamleff** [comment]
That seems like a fine approach, @jerryaldrichiii. We probably want to guard against assuming that just because it fails as a systemd unit that it will work as a SysV service (i.e. we may need to do an exists check before trusting sysv_service().enabled?)

**Comment by jerryaldrichiii** [comment]
Great point. I'll make it happen. PR incoming :smile:
