### ISSUE TITLE
rename `parse_config` options for clarity

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1709]
### Description

`parse_config` options are not as declarative. This was raised by: @jamescott  in https://github.com/chef/inspec/issues/120

### InSpec and Platform Version

<=v1.21

### Possible Solutions

* change `:assignment_re`
    to `:assignment_regex`
* change `:key_vals`
    to `:key_values` to be consistent with `:multiple_values`

Opinions?

**Comment by adamleff** [comment]
No problem with that, I am all in favor of more descriptive method names and configuration keys!

We should probably support both for now, add deprecation warnings for anyone using `assignment_re` and `key_vals` outside the InSpec core resources, and open a separate issue for removing those options in InSpec 2.x.
