### ISSUE TITLE
Remove :controls from json-full report

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1716]
### Description

We need to remove the `controls` tree in our report and enforce json schema

**Comment by trevor-vaughan** [comment]
Voting for this one. I found this REALLY confusing when starting to process the report.

Should we just ignore the `controls` tree for now?

**Comment by adamleff** [comment]
NOTE TO IMPLEMENTER: since this is a breaking change, the PR should target the `release-2.0` branch, NOT `master`

**Comment by adamleff** [comment]
This should be ready to implement once @jquick completes #2415
