### ISSUE TITLE
Improve 'Test Summary" Coloring; especially "0 Failures" being in Red

### ISSUE THREAD

**Issue by polobo** [inspec/inspec#1752]
I suspect the following behavior is inherited but here's a complaint anyway...I'll be happy to post an issue elsewhere if you can give me a hint as to where.

`Test Summary: 1 successful, 0 failures, 0 skipped`

The above output, when in color, is alarming. The 0 failures show up as a nice bright red (using bash shell on Windows 10 presently).

Might I suggest that "0 failures" be output in grey instead. In a similar fashion a non-zero skipped might warrant something like a cyan output to flag its non-zero presence while leaving the existing grey for '0 skipped'. This later item being less bothersome than seeing red on a test output and having to read the result to realize that it isn't actually a problem.

Running via Chef Development Kit Version: 1.3.43

**Comment by hannah-radish** [comment]
Hi @polobo, UX designer here. That sounds like a great suggestion. Will work with our engineers on this

**Comment by trickyearlobe** [comment]
Check with `inspec version` if you have an old version of inspec lying around that's not part of the latest ChefDK. This sounds like bug #1508 and should have been fixed by PR #1510

**Comment by polobo** [comment]
v1.19.1 - but the description in bug report #1508, while similar, is not the same.  I'm not seeing buggy behavior here - my output seems to match the code.  What I'm seeing is a choice to code "0 failures" with a red foreground on a black background which makes it appear to be a bad thing when in fact having 0 failures is good; or at least neutral since the "successful" count is communicating the good results.

**Comment by polobo** [comment]
Put differently the colors for the three result outputs should differ depending on whether the corresponding count is zero or non-zero.  The existing code, when I checked a while back, didn't have any branching in place for this purpose.

**Comment by adamleff** [comment]
@polobo I completely understand what you're talking about. I frequently make the joke "if there's anything I know about computers, it's that 'red is bad'", so I can understand having InSpec display red text even when there are no errors be perceived as incorrect.

While it would be a relatively easy code change to only color the success/failure summaries green/red respectively only if the count > 0, I'm going to defer to @hannah-radish (our UX genius). If she gives a 👍  then it should be an easy PR to take on.

**Comment by adamleff** [comment]
@polobo I just merged PR #2094 that makes the summary colors conditional on the results as you suggested. It will be part of the next InSpec release!
