### ISSUE TITLE
add an --output option to the exec command to allow redirection of results to be in a file.

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1754]
### Description  

@dant had asked in the #inspec channel how to redirect output of junit format results to a file. Of course we can do this via a simple `| tee file` command or a `> file` but my first assumption was to just use the `--output` switch. Oops, not there :) and it should be.

**Comment by jquick** [comment]
With the new reporter work https://github.com/chef/inspec/pull/2464 you can now set an output path for each format.
