### ISSUE TITLE
Skip tests if profile is not supported instead of throwing an exception

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1756]
### Description

Run a profile that is not supported, eg.
```
# run this on a mac
$ inspec exec https://github.com/dev-sec/linux-baseline
This OS/platform (mac_os_x) is not supported by this profile.
```

This is causing issues in audit cookbook, if multiple profiles are executed with the same InSpec runner.

### InSpec and Platform Version

1.20.0

### Replication Case

Run non-supported profile and supported profile via `inspec exec` 

### Possible Solutions

If the profile is not supported, all test should be skipped instead.

**Comment by jquick** [comment]
Fixed via https://github.com/inspec/inspec/pull/3495
