### ISSUE TITLE
Custom resource from documentation example does not work

### ISSUE THREAD

**Issue by mschuchard** [inspec/inspec#1757]
### Description

Custom resources should work in InSpec

### InSpec and Platform Version

1.2.0 RHEL6

### Replication Case

Using https://github.com/chef/inspec/blob/master/examples/profile/libraries/gordon_config.rb and test:

```ruby
describe gordon_config do
  it { expect(subject).to_not exist }
end
```

### Possible Solutions

Serverspec deals with this issue here:
https://github.com/mizzy/serverspec/blob/377641274f9b9d418040353d7e4a1ed01219db85/lib/serverspec/helper/type.rb

However, this kind of workaround does not appear in the documentation for InSpec, which implies this is not required when inheriting from `InSpec.resource(1)`.

I should note that even trying that kind of workaround, an RSpec error for example groups is then raised, so it is not a full solution.

### Stacktrace

> controls/gordon_config_spec.rb:1:in `load_with_context': undefined local variable or method `gordon_config' for #<#<Class:0x00000003e14418>:0x00000003e0fc38> (NameError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile.rb:113:in `block in collect_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile.rb:110:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/profile.rb:110:in `collect_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/runner.rb:85:in `block in load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/runner.rb:79:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/runner.rb:79:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/runner.rb:95:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/base_cli.rb:84:in `run_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/lib/inspec/cli.rb:164:in `exec'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.2.0/bin/inspec:12:in `<top (required)>'
	from /opt/chefdk/embedded/bin/inspec:22:in `load'
	from /opt/chefdk/embedded/bin/inspec:22:in `<main>'

**Comment by adamleff** [comment]
@mschuchard Thanks for submitting this issue.

InSpec v1.2.0 is quite old, indeed. Could you please try to reproduce this issue on a later version such as 1.20.0 or later? I have a number of profiles that use custom resources that are working without issue.

If you're still having problems after upgrading, please supply a gist of the exact custom resource and a control using that resource (redacting any sensitive material as needed) so we can try to reproduce.

Also, I'm afraid InSpec does not support RSpec-style shared example groups or similar functionality. That could be contributing to your troubles.

**Comment by mschuchard** [comment]
Right, I missed the `0` somehow in the minor version and thought it was 1.20.0 even though it is 1.2.0, which would be "not that old". I will upgrade today to 1.22.0 and see what happens.

**Comment by mschuchard** [comment]
Issue still exists in 1.22. Is this maybe a problem with the documentation instead that the verbatim example is not working?

**Comment by adamleff** [comment]
@mschuchard I'm afraid I'm unable to reproduce this.  Here's what I did:

 * create a new profile with `inspec init profile gordon_test`
 * created a `libraries/gordon_config.rb` file in my profile with the content from https://github.com/chef/inspec/blob/master/examples/profile/libraries/gordon_config.rb
 * edited the `controls/example.rb` file with the following control, using the exact `describe` block from the aforementioned custom resource example:

```ruby
control 'tmp-1.0' do                        # A unique ID for this control
  impact 0.7                                # The criticality, if this control fails.
  title 'a gordon test'             # A human-readable title
  desc 'An optional description...'
  describe gordon_config do
    its('version') { should eq('1.0') }
    its('file_size') { should > 1 }
  end
end
```

 * created a `/tmp/gordon/config.yaml` file with the following content:

```yaml
version: '1.0'
foo: bar
```

 * ran `inspec check .` from my profile directory to make sure it was valid.
 * ran `inspec exec .` from my profile directory, and received the following output:

```
Profile: InSpec Profile (gordon_test)
Version: 0.1.0
Target:  local://

  ✔  tmp-1.0: a gordon test
     ✔  gordon_config version should eq "1.0"
     ✔  gordon_config file_size should > 1

Profile Summary: 1 successful, 0 failures, 0 skipped
Test Summary: 2 successful, 0 failures, 0 skipped
```

In order to troubleshoot this further, we'll need you to provide exact reproduction steps so we can see exactly where this is failing. Sorry you're running into issues.

**Comment by mschuchard** [comment]
As you probably already guessed, it was an environment issue caused by someone. Thanks for the assistance; closing.

**Comment by adamleff** [comment]
Glad you got squared away, @mschuchard. Thanks for getting back to us!
