### ISSUE TITLE
Tutorial page is available two times

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1765]
### Description

we have https://github.com/chef/inspec/blob/master/www/source/docs/tutorials.html.md and https://github.com/chef/inspec/blob/master/www/source/tutorials.html.slim which results in:

- https://www.inspec.io/tutorials/
- https://www.inspec.io/docs/tutorials/

I think https://www.inspec.io/docs/tutorials/ needs to go, since it is already outdated. This page shouldn't be linked anywhere anymore

### InSpec and Platform Version

latest

**Comment by sntxrr** [comment]
I think there is a bit of a subtlety here - I think we *may* want the left nav from the `/docs/tutorials/` version, AND keep the text from the `/tutorials/` version. I'll see about putting together a PR.

**Comment by chris-rock** [comment]
ah good idea!
