### ISSUE TITLE
Error during profile upload

### ISSUE THREAD

**Issue by SteveDelFante** [inspec/inspec#1777]
### Description

I am trying to upload a cusotm profile from a Windows workstation to Compliance server. 

Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/workstation-1/compliance/secureprofile_scd/tar."
C:\Users\chef>  SEE the rest below.

### InSpec and Platform Version
 inspec version 1.11.0 
Windows server 2012 r2 This windows server is within the wombat/bjc cluster

### Replication Case

Log into Chef Compliance:

C:\Users\chef> inspec compliance login https://ec2-52-207-216-200.compute-1.amazonaws.com --insecure --user='workstation-1' --token='eyJhbGc
iOiJSUzI1NiIsImtpZCI6InlRRVQtTkRZUlM2cnNXTE0wS010SWJO-skipping-'

This works:
C:\Users\chef> inspec compliance profiles

== Available profiles:

 * base/apache
 * base/linux
 * base/mysql
 * base/postgres
---skipping---

Here's the Failure:
C:\Users\chef> inspec compliance upload secureprofile_scd --overwrite
Vendor dependencies of secureprofile_scd into secureprofile_scd/vendor
I, [2017-05-05T20:22:03.796780 #3292]  INFO -- : Checking profile in secureprofile_scd
I, [2017-05-05T20:22:03.796780 #3292]  INFO -- : Metadata OK.
I, [2017-05-05T20:22:03.803779 #3292]  INFO -- : Found 3 controls.
I, [2017-05-05T20:22:03.803779 #3292]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at C:/Users/chef/AppData/Local/Temp/2/secureprofile_scd20170505-3292-1fgkird.tar.gz
I, [2017-05-05T20:22:03.849744 #3292]  INFO -- : Generate archive C:/Users/chef/AppData/Local/Temp/2/secureprofile_scd20170505-3292-1fgkird.
tar.gz.
I, [2017-05-05T20:22:03.855785 #3292]  INFO -- : Finished archive generation.
Start upload to workstation-1/secureprofile_scd
Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/workstation-1/compliance/secureprofile_scd/tar."
C:\Users\chef>

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment]
Closing this issue as a duplicate - we'll track the progress in #1790 since the failing experience is the same.
