### ISSUE TITLE
undefined method `empty?' for nil:NilClass with sshd_conf

### ISSUE THREAD

**Issue by AnotherWorkingNerd** [inspec/inspec#1778]
### Description
The resource sshd_config displays `(undefined method `empty?' for nil:NilClass)` if you don't use --sudo in the inspec command line. A more descriptive error message would much more helpful.

### InSpec and Platform Version
1.23.0 on OS X 10.10.5

### Replication Case
Using the following:
`control "con42" do
  impact 1.0
  title "verify that we are using sshd v2"
  desc "Using sshd v2."
  describe sshd_config do
    its('Protocol') { should cmp 2 }
  end
end `

Using the command line `inspec exec test.rb -t ssh://example.com` results in 

> `con42: verify that we are using sshd v2 (undefined method `empty?' for nil:NilClass)
     *  SSH Configuration Protocol
     undefined method `empty?' for nil:NilClass
`

Using the command line `inspec exec test.rb --sudo -t ssh://example.com results expect results
> `  ×  con42: verify that we are using sshd v2 (
     expected: "2"
          got: nil
'

### Possible Solutions

yes, you need to use --sudo but it you don't I feel its revealed a bug somewhere along the line and a more descriptive error message would much more help. Something like "permission denied. try adding --sudo to the inspec commandline"

If you have any questions I can be reached on the inspec slack channel as @gmoore1 or at gmoore1 at gci.com

**Comment by adamleff** [comment]
@AnotherWorkingNerd You're totally right. Issue #1205 details the underlying problem in that we don't have a great way for individual resources to raise exceptions with helpful error messages like this. In the meantime, we shouldn't try to call a method like `#empty?` on something that could be nil, so I'll be happy to fix that.

Once we fix the ability to raise exceptions, we'll be able to provide better error messages for situations like this. For now, I'll at least fix this so it catches this issue and returns nil so the test still fails without a crummy Ruby error message.

**Comment by AnotherWorkingNerd** [comment]
Thanks @adamleff :)

**Comment by jerryaldrichiii** [comment]
@AnotherWorkingNerd I'm unable to reproduce this behavior.

Could you send me your `sshd_config`? Also information about the target would be awesome.

Thanks!

**Comment by jquick** [comment]
I was able to reproduce this here:
![screen shot 2017-10-05 at 9 19 21 am](https://user-images.githubusercontent.com/574637/31229328-51bc943a-a9ae-11e7-8ca9-259fc1561c39.png)
This seems to happen if the ssh user does not have read access to the /etc/ssh/sshd_config file. For now we can add a nil catch to clean it up till #1205.
