### ISSUE TITLE
Add "skip"-parameter to cli

### ISSUE THREAD

**Issue by rndmh3ro** [inspec/inspec#1781]
### Description

Currently there exists a `--controls` cli parameter that allows one to define a list of controls that will be run.
I'm proposing a new parameter `--skip-controls` that accepts a list of controls that will **not** be run.

This is useful if you only want to skip a few controls; then you don't have to add all controls except the ones you want to skip.
It can also be useful if you use a git-repo for tests and don't want to update the cli command every time new tests are added.

### InSpec and Platform Version

1.23

**Comment by chris-rock** [comment]
@rndmh3ro Great idea!

**Comment by zedtux** [comment]
I'm also looking exactly for that ! Is there a workaround or not?

**Comment by kekaichinose** [comment]
@zedtux yes there are a couple work-arounds:
1. use `--controls` to specify the controls to run; this will exclude the ones that are not in the argument. This may not be ideal as it will bloat the command, but all depends on the size of the profile too...
2. use the `skip_control` command inside the profile for the controls you want to skip. Check this out for more info: https://www.inspec.io/docs/reference/profiles (Skipping a Control from a Profile)

@rndmh3ro as the CLI is already fairly robust and there are ways to skip controls present in the profile, this parameter is not something we feel should be added to the code at this point. Thanks for the request though, and we apologize for the (really) late follow-up on this issue.

**Comment by zedtux** [comment]
> the CLI is already fairly robust

How could it be a reason to not implement something? Then the Linux kernel is already fairly robust so let's not add new drivers to not support new hardware. 😄.

---

My use case is to use the ssh-hardening profile but ignoring 1 control.
Using `--controls` will be a big pain in my ass as I will have to enumerate all the controls, excepted the one I don't want, PLUS I'll have to maintain this list so that in the case a new control is added to the profile it is not skipped.

It does look easy to implement, and have a huge benefit for the given use case that doesn't look too exotic to me.

If you closed the issue due to a time constraint, then let us implement it for you.

**Comment by miah** [comment]
@zedtux We would welcome a PR =)

**Comment by zedtux** [comment]
Thank you @miah, I will work on it soon then.

Therefore, shouldn't you reopen this issue?

**Comment by kekaichinose** [comment]
@zedtux any follow-up here? Didn't see your PR for this yet.

**Comment by zedtux** [comment]
Thank you @kekaichinose for your follow-up.

I have started yet, but it is still planed I'm doing it.
I'll be in holidays for 3 weeks starting by tomorrow 🌴 so there will be some delay on that, but I'm sure that's not a big deal, the issue has been opened in 2017, releasing this in the next 2 months should be fine.

Feel free to continue the follow-up 👍

**Comment by kekaichinose** [comment]
@zedtux I'm still working on cleaning up our issues, and want to make sure everything stays up to date. I'm going to go ahead and close this issue, but once you have a PR submitted, we can reopen it and attach it to the PR.

Have a great holiday! 🌴

**Comment by zedtux** [comment]
I don't really understand how is this better as you're hiding request IMHO ... but as you wish 🤷‍♂
