### ISSUE TITLE
Prevent `/` in profile name

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1783]
### Description

Briefly describe the issue and the expected behavior

### InSpec and Platform Version

1.22.0

### Replication Case

```
inspec init profile test/profile
Create new profile at /Users/chartmann/Development/compliance/inspec/test/profile
 * Create directory controls
 * Create file controls/example.rb
 * Create file inspec.yml
 * Create directory libraries
 * Create file README.md
 * Create file libraries/.gitkeep
➜  inspec git:(master) ✗ cat test/profile/inspec.yml 
name: test/profile
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: All Rights Reserved
summary: An InSpec Compliance Profile
version: 0.1.0
```

### Possible Solutions

* Slug the name
* `inspec check` should ensure that only slugable url characters are used

**Comment by adamleff** [comment]
Adding this as an enhancement and putting in the 2.0 milestone since this would be breaking behavior (though adding a warning now and an error later would be totally cool).

**Comment by clintoncwolfe** [comment]
Just to clarify, is it acceptable to have profiles in subdirectories so long as their names are slugged?
```
inspec init profile test/profile
Create new profile at /Users/chartmann/Development/compliance/inspec/test/profile
#...
cat test/profile/inspec.yml 
name: test_profile
```

Or is the goal here to require profiles be at the same level on the filesystem?

**Comment by adamleff** [comment]
@clintoncwolfe totally fine for there to be profiles in subdirectories and for the CLI to honor them, much like you discovered with `inspec init profile`. There just shouldn't be any non-sluggable characters in the profile name.

I just discovered that you can do `inspec init profile \{\{foo\}\}` and it will totally create a directory called `{{foo}}` and also set the profile name to `{{foo}}` in inspec.yml, which breaks horribly. We should fix that as part of this issue too... for whoever decides to pick this one up :)

**Comment by clintoncwolfe** [comment]
We'll need to actively slug, at least based on this line, which will create invalid (space and slash containing) names when the target is a local path:

https://github.com/chef/inspec/blob/29c80110a81e1bb01055407ed40038a8f082d279/lib/inspec/metadata.rb#L215

**Comment by adamleff** [comment]
Well, we have to be careful not to break existing functionality considering InSpec can run tests with those tests being a fully-fledged InSpec profile. That's where the "tests from" stuff originates. In this case, there's no metadata file and no actual "profile name" to slug... and that's probably OK.
