### ISSUE TITLE
Inspec not using linux .bashrc or .bash_profile properly

### ISSUE THREAD

**Issue by AnotherWorkingNerd** [inspec/inspec#1784]
### Description
Sorry the formatting got munged somewhere along the way.

Ok I used http://rubular.com/ to validate these regexs and of course when I try to actually them I get nowhere fast. I trying to match a version # in the form of 1.1.1.  its an env. var and it *is* set. I am using: 

control "x-123" do 
&nbsp;  impact 1.0
&nbsp;  title "Image Version"
&nbsp;  desc "get the value IMAGE_VERSION is set to."
&nbsp;  describe os_env('IMAGE_VERSION') do
&nbsp;&nbsp;    its('content') { should match /1\.[0-2.]\.[0-9]/ }   
 &nbsp; end
end `
and all I get is  < environment variable IMAGE_VERSION content should match /1\.[0-2.]\.[0-9]/  expected nil to match /1\.[0-2.]\.[0-9]/ 
After chatting with @aaronlippold on slack I think he summarized things best

> aaronlippold [9:49 AM] 
I think the fundamental issue is that the profile or resource actually has an incorrect assumption about the order of Precedence or the default shell that's being used. I'm not a hundred percent sure but that's the point of the issue :-)

BACKGROUND -- not brief. Slack conversation between @aaronlippold and myself (gmoore1)

**[8:12]** 
@gmoore1 what do you get in 'inspec shell' when you say, os_env('IMAGE_VERSION').content

gmoore1 [8:54 PM] 
Thanks @aaronlippold I hadn’t thought to use the inspec shell…DOH!.. in any case here are the results
 inspec> os_env('PATH')
=> Environment variable PATH
inspec> os_env('PATH').content
=> "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/m2automation/.local/bin:/home/m2automation/bin"
inspec> os_env('IMAGE_VERSION').content
=> "1.2.1"

**[9:12]** 
now here is the frustrating part  _it works_ in the _inspec shell_ and all I did was copy and paste.
`inspec> os_env('PATH').content
=> "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/m2automation/.local/bin:/home/m2automation/bin"
inspec> os_env('IMAGE_VERSION').content
=> "1.2.1"
inspec> describe os_env('IMAGE_VERSION') do
inspec>   its('content') { should match /1\.[0-2.]\.[0-9]/ }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Environment variable
     ✔  IMAGE_VERSION content should match /1\.[0-2.]\.[0-9]/

Test Summary: 1 successful, 0 failures, 0 skipped
inspec> `

----- May 6th -----

aaronlippold [7:20 AM] 
@gmoore1 Ok. So inspec shell finds the env var. Ok I think that is a bug. You should put in an issue for that.

[7:21] 
Copy and paste your inspec shell session and the test so we can try to reproduce.

aaronlippold [7:34 AM] 
@gmoore1 I don't seem to be having the issue. Here is what I have.

[7:34] 
 ```describe os_env('PATH') do
  its('content') { should include 'aaronl' }
end

describe os_env('IMAGE_VERSION') do
  its('content') { should match %r{^1\.[0-2.]\.[0-9]$} }
end```

[7:35] 
 ```➜  inspec git:(master) ✗ export IMAGE_VERSION=1.2.7```

[7:35] 
 ```Profile: tests from test.rb
Version: (not specified)
Target:  local://


  Environment variable
     ✔  PATH content should include "aaronl"
  Environment variable
     ✔  IMAGE_VERSION content should match /^1\.[0-2.]\.[0-9]$/

Test Summary: 2 successful, 0 failures, 0 skipped
➜  inspec git:(master) ✗```

aaronlippold [7:45 AM] 
This was locally on the host

aaronlippold [7:56 AM] 
```➜  postgresql-baseline-hardening git:(master) ✗ inspec exec ~/Desktop/inspec/test.rb -i $SSH_KEY_H -t ssh://vagrant@127.0.0.1:2222

Profile: tests from /Users/aaronl/Desktop/inspec/test.rb
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222


  Environment variable
     ✔  PATH content should include "/usr/bin"
  Environment variable
     ✔  IMAGE_VERSION content should match /^1\.[0-2.]\.[0-9]$/
     ∅  IMAGE_VERSION content.strip should eq "1.2.7"

     expected: "1.2.7"
          got: "1.2.8"

     (compared using ==)


Test Summary: 2 successful, 1 failures, 0 skipped```

[7:59] 
When I unset it in .bashrc I get:

[8:00] 
 ```  Environment variable
     ✔  PATH content should include "/usr/bin"
  Environment variable
     ∅  IMAGE_VERSION content should match /^1\.[0-2.]\.[0-9]$/
     expected nil to match /^1\.[0-2.]\.[0-9]$/
     ∅  undefined method `strip' for nil:NilClass
     Did you mean?  String

Test Summary: 1 successful, 2 failures, 0 skipped```

[8:02] 
But if I set it in .bashrc, I get:

[8:02] 
 ```Target:  ssh://vagrant@127.0.0.1:2222


  Environment variable
     ✔  PATH content should include "/usr/bin"
  Environment variable
     ✔  IMAGE_VERSION content should match /^1\.[0-2.]\.[0-9]$/
     ✔  IMAGE_VERSION content.strip should eq "1.2.7"

Test Summary: 3 successful, 0 failures, 0 skipped```

aaronlippold [8:11 AM] 
@gmoore1 but when I do a kitchen login and I am in either the bash or sh shell it seems to respect the .bash_profile but when I do a remote test with inspec it doesn't seem to source .bash_profile and only seems to respect things source'd in .bashrc. @dominik what do you think.

[8:12] 
@gmoore1 at least for now, I think this should get you moving, i.e. knowing where you have to set it until we track down this issue.

[8:12] 
Could you add my examples to your issue report to help refine it a bit. Thanks.



### InSpec and Platform Version

Inspec 1.23.0 and whatever version @aaronlippold was using


### Replication Case

**user .bashrc file** 
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

user .bash_profile
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

**in /etc/profile.d/**
file baseimage.sh contains one line `export IMAGE_VERSION=1.2.1`

### Possible Solutions

to quote @aaronlippold because he has a better idea then I do:
> I think the fundamental issue is that the profile or resource actually has an incorrect assumption
 about the order of Precedence or the default shell that's being used. I'm not a hundred percent sure 
but that's the point of the issue :-)


### Stacktrace

none

**Comment by adamleff** [comment]
@AnotherWorkingNerd Unfortunately, this is "working as designed." The contents of `/etc/profile.d` are only sourced when a login shell is used, and InSpec/Train do not use a login shell to do their work. While I don't know the original creators' intentions, I do agree with this approach; relying on user profile settings for the purposes of doing audit/infrastructure tests could lead to fragile tests and inconsistent results.

The inconsistencies between `inspec shell` and `inspec exec` in your examples are largely due to where you were running the commands and the fact that on the host, you're in a login shell so the `/etc/profile.d` content has been sourced.

For your particular use case, if the environment variable is always in the same place, using a `file` resource or the `parse_config_file` resource is likely your best bet to ensure you're actually checking the contents of the file vs. the shell's ability to source in the information.

In the future, it would be really helpful to have a more succinct issue description as it took me quite a while to parse through the formatted and unformatted text to understand the issue... much of the Slack conversation was hard to decipher. If the slack conversation is helpful to the context, please by all means include it as a follow-up comment!
