### ISSUE TITLE
Error during profile upload to Automate too

### ISSUE THREAD

**Issue by SteveDelFante** [inspec/inspec#1790]
### Description

I am trying to upload a cusotm profile from a Windows workstation to Automate server. This error is just like the one I opened for the Compliance server.
```
C:\Users\chef> inspec compliance upload secureprofile_scd --overwrite
Vendor dependencies of secureprofile_scd into secureprofile_scd/vendor
I, [2017-05-09T23:14:14.726600 #2604]  INFO -- : Checking profile in secureprofile_scd
I, [2017-05-09T23:14:14.726600 #2604]  INFO -- : Metadata OK.
I, [2017-05-09T23:14:14.730640 #2604]  INFO -- : Found 3 controls.
I, [2017-05-09T23:14:14.731638 #2604]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at C:/Users/chef/AppData/Local/Temp/2/secureprofile_scd20170509-2604-1m48gxz.tar.gz
I, [2017-05-09T23:14:15.021611 #2604]  INFO -- : Generate archive C:/Users/chef/AppData/Local/Temp/2/secureprofile_scd20170509-2604-1m48gxz.tar.gz.
I, [2017-05-09T23:14:15.027640 #2604]  INFO -- : Finished archive generation.
Start upload to workstation-1/secureprofile_scd
Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/workstation-1/compliance/secureprofile_scd/tar."
```
Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
inspec version 1.11.0
Windows server 2012 r2 This windows server is within the wombat/bjc cluster

THE REST OF THIS is just like this: https://github.com/chef/inspec/issues/1777

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
This works on Linux/Mac, so this must be an issue with Windows... Further investigation required

**Comment by seththoenen** [comment]
I'm also having a similar issue, I can't upload to Chef Automate from Windows 10.

InSpec Version: 1.26.0

Chef Automate Version: 0.8.5

Details:
```
inspec compliance upload . --overwrite
Dependencies for profile . successfully vendored to vendor
I, [2017-06-01T08:25:49.381993 #11784]  INFO -- : Checking profile in .
I, [2017-06-01T08:25:49.381993 #11784]  INFO -- : Metadata OK.
I, [2017-06-01T08:25:49.423026 #11784]  INFO -- : Found 11 controls.
I, [2017-06-01T08:25:49.424026 #11784]  INFO -- : Control definitions OK.
Profile is valid
Generate temporary profile archive at C:/Users/sthoenen/AppData/Local/Temp/srvops_mcafee20170601-11784-cd918.tar.gz
I, [2017-06-01T08:25:49.633535 #11784]  INFO -- : Generate archive C:/Users/sthoenen/AppData/Local/Temp/srvops_mcafee20170601-11784-cd918.tar.gz.
I, [2017-06-01T08:25:49.657561 #11784]  INFO -- : Finished archive generation.
Start upload to seth_thoenen/srvops_mcafee
Uploading to Chef Automate
Error during profile upload:
{"summary":{"valid":false,"timestamp":"","location":"","controls":0},"errors":null,"warnings":null}
```
When I check my profile, everything looks good:
```
Location:    .
Profile:     srvops_mcafee
Controls:    11
Timestamp:   2017-06-01T08:26:41-05:00
Valid:       true

No errors or warnings
```

**Comment by SteveDelFante** [comment]
This issue applies to Automate and Compliance server.

**Comment by SteveDelFante** [comment]
This now works when I upload to the Compliance server using inspec 1.28.1 on Window 2012 r2. Here is the successful command.

`C:\opscode\inspec\bin\inspec compliance upload secureprofile_###.zip --overwrite`

Now for the Automate UI, I believe Chris is going to enable the ability to upload zip files.

**Comment by arlimus** [comment]
Thank you @SteveDelFante for testing!
Closing with the solution to upgrade InSpec to 1.28+.

@seththoenen The update to InSpec 1.28 should resolve this problem. Please reopen this ticket in case you still encounter this issue.
