### ISSUE TITLE
registry_key failing when int value last registry node element

### ISSUE THREAD

**Issue by stonesbg** [inspec/inspec#1793]
### Description

Running inspec tests on sql server 2016 registry_key settings to validate that the customer experience is disabled

### InSpec and Platform Version

- Inspec -> 1.23.0
- Platform -> Windows Server 2012 R2

using Test-Kitchen to run tests

### Replication Case

1. Create a test that is accessing a HIVE with an integer value as the root 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130'
2. Checking for its('CustomerFeedback') { should eq 1 }

Control information is below in gist link

### Possible Solutions

I executed the powershell within the ruby registry_key and that found the following results json.

{"CustomerFeedback":{"value":1,"type":4},"EnableErrorReporting":{"value":0,"type":4},"SharedCode":{"value":"c:\\Program Files\\Micros
oft SQL Server\\130\\Shared\\","type":1},"VerSpecificRootDir":{"value":"c:\\Program Files\\Microsoft SQL Server\\130\\","type":1},"Er
rorReportingDir":{"value":"C:\\Program Files\\Microsoft SQL Server\\130\\Shared\\ErrorDumps\\","type":1},"CollectorParameters":{"valu
e":" MSSQL13.MSSQLSERVER","type":1},"TimeOfReporting":{"value":240,"type":4}}

### Stacktrace

https://gist.github.com/stonesbg/41885a138e94548d44be3fe14e3ccee1

**Comment by adamleff** [comment]
@stonesbg thanks for submitting this issue!

I'm afraid I'm having trouble reproducing this one. I set up a new Windows VM and configured the following two registry hives:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server`:
![screen shot 2017-06-02 at 15 35 07](https://cloud.githubusercontent.com/assets/3221128/26741907/5b8a2e12-47a9-11e7-8eaf-a1a25965cc1a.png)


`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130`:
![screen shot 2017-06-02 at 15 35 18](https://cloud.githubusercontent.com/assets/3221128/26741916/63797dd0-47a9-11e7-9d9d-c9b4b472d9dd.png)

I then took a part of your profile and ran it against my machine and it worked fine:

```
inspec> describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server') do
inspec>   its('CustomerFeedback') { should eq 0 }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Registry Key
     ✔  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server CustomerFeedback should eq 0

Test Summary: 1 successful, 0 failures, 0 skipped
inspec> describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130') do
inspec>   its('CustomerFeedback') { should eq 1 }
inspec>   its('CustomerFeedback') { should eq 1 }
inspec>   its('CustomerFeedback3') { should eq 1 }
inspec>   its('EnableErrorReporting') { should eq 0 }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Registry Key
     ✔  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130 CustomerFeedback should eq 1
     ✔  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130 CustomerFeedback should eq 1
     ✔  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130 CustomerFeedback3 should eq 1
     ✔  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\130 EnableErrorReporting should eq 0

Test Summary: 4 successful, 0 failures, 0 skipped
```

As you can see, all 5 tests succeeded. 

Could you provide additional detail on how to reproduce this issue?

**Comment by stonesbg** [comment]
@adamleff Sorry it has taken so long to get back to you on this.  I have installed the latest chefdk 1.5.0 and everything is working perfectly.  So might of be just been an old bug that is now resolved.

Thanks for looking into this we can close this issue off.

**Comment by adamleff** [comment]
@stonesbg no apologies necessary! I'm just glad you're squared away. Thanks for getting back to us.
