### ISSUE TITLE
inspec vendor can not find depend cis profile

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#1794]
### Description
The compliance profile cis/cis-rhel7-level1 was not found on the configured compliance server

### InSpec and Platform Version

running inspec 1.23

### Replication Case

basically log into inspec compliance login_automate

inspec vendor  then get error cant find the CIS profile.    We have a custom profile that needs to include cis profile with override.  

I can see all the cis profiles in automate /var/opt/delivery/compliance

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
Note: The following answer is only valid for Chef Automate, Chef Compliance behaves differently

Chef Automate ships with a market that includes all profiles we ship, Chef Compliance made those available under `cis` namespace which is not valid for Chef Automate. Now you need to `install` all required profiles into your user namespace. The easiest way is to use the Automate Dashboard -> Compliance -> Profiles to do that. The reason for that behavior change is that we do not want to change an internally approved profiles. Now, with Chef Automate, once the profile is installed into your namespace, this will never update without explicit user approval.

If you login via `inspec compliance login_automate` and `inspec compliance profiles` you see all profiles available for your user.

**Comment by chris-rock** [comment]
Note: The following answer is only valid for Chef Automate, Chef Compliance behaves differently

Chef Automate ships with a market that includes all profiles we ship, Chef Compliance made those available under `cis` namespace which is not valid for Chef Automate. Now you need to `install` all required profiles into your user namespace. The easiest way is to use the Automate Dashboard -> Compliance -> Profiles to do that. The reason for that behavior change is that we do not want to change an internally approved profiles. Now, with Chef Automate, once the profile is installed into your namespace, this will never update without explicit user approval.

If you login via `inspec compliance login_automate` and `inspec compliance profiles` you see all profiles available for your user.

**Comment by chris-rock** [comment]
We identified an issue in Chef Automate and this is not related to InSpec. The profile was not available under the expected namespace.
