### ISSUE TITLE
describe package failing in newer version

### ISSUE THREAD

**Issue by sarahbakal** [inspec/inspec#1797]
![package](https://cloud.githubusercontent.com/assets/27020176/25907996/a928c14e-356e-11e7-8b3c-444a2ce82c10.png)

### Description

running 

describe package('WinZip 21.0') do
   it { should be_installed }
end

working in Inspec 1.7.1 but fails in newer 1.19.1

### InSpec and Platform Version

1.19.1

### Replication Case

verifying installed application in multiple versions. Some work but most dont.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

See screenshot

**Comment by adamleff** [comment]
@sarahbakal can you please add the screenshot you referenced in your issue description? I'm not 100% clear how this is failing so it would be helpful to determine where the failure lies before I try to reproduce it. Thanks!

**Comment by sarahbakal** [comment]
![package](https://cloud.githubusercontent.com/assets/27020176/26740997/61654710-479d-11e7-9cce-954a08f16935.png)

**Comment by sarahbakal** [comment]
[cid:F8827D4B-8119-4DA0-BCF2-00C592263C65]
Sarah Bakal | Optum

Sr IT Operating System Consultant
NHS Compliance Support Services
12501 Whitewater Dr
Minnetonka, MN 55343
T   +1 952-352-2557
sarah_bakal@optum.com
www.optum.com

**Comment by sarahbakal** [comment]
@adamleff 
Having trouble adding it.

**Comment by adamleff** [comment]
@sarahbakal sent me the image directly via Slack, I'll take this one and dig into it.

**Comment by adamleff** [comment]
Hi @sarahbakal. I tried to reproduce this issue today but was unable to. It worked with one of the packages I already had installed in my test Windows VM, so I then installed WinZip v21 like you have on your machine, and it worked for me via the inspec shell:

```
 aleff@remaleff01  ~/projects/inspec   adamleff/fix-windows-package  be inspec shell --target winrm://vagrant@127.0.0.1 --password vagrant
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  Windows Server 2012 R2 Standard
    OS family:  windows
    OS release: 6.3.9600

inspec> describe package('WinZip 21.0') do
inspec>   it { should be_installed }
inspec> end

Profile: inspec-shell
Version: (not specified)

  System Package
     ✔  WinZip 21.0 should be installed

Test Summary: 1 successful, 0 failures, 0 skipped
```

Is it possible the user you're running InSpec with doesn't have access to see installed packages? I don't think that's the case based on your screenshots, but I'm grasping at straws.

This is the core Powershell command that's run under the covers, minus any filtering. What happens if you run this manually? Do you get any JSON output and is WinZip included in that output?

```
Get-ItemProperty (@("HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*", "HKCU:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*") | Where-Object { Test-Path $_ }) | Select-Object -Property DisplayName,DisplayVersion | ConvertTo-Json
```

**Comment by sarahbakal** [comment]
The manual command works and has the package i'm looking for. I'll test it a bit more through the compliance server to see if its just this single server.

**Comment by sarahbakal** [comment]
Localized issue
