### ISSUE TITLE
Feature Request Tomcat resource

### ISSUE THREAD

**Issue by atomic111** [inspec/inspec#1802]
### Description

I implement a tomcat baseline for a customer with Regex. It would be nice to have a tomcat resource or a xml resource.

**Comment by aaronlippold** [comment]
I agree, I would be happy to help with this if you want to start building
one. I also am going to start working on an NGINIX resource as well.

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by atomic111** [comment]
@aaronlippold this would also be nice to have a nginx resource. i will open an issue for this, because i implement for the same customer right now a nginx baseline with regex

**Comment by adamleff** [comment]
@atomic111 could you please add a comment to this issue with what types of tests you'd like to be able to write with a tomcat resource?

**Comment by atomic111** [comment]
@adamleff i wrote some tests for a customer, like

control 'tomcat-56' do
  impact 1.0
  title 'Disable Tomcat Web Server Signature'
  desc '\'ServerSignature Off\' tells Apache to not return the used Apache Version'

  describe bash("find ${Value:catalina.base} -name server.xml | xargs grep \"resolveHosts\"") do
    its("stdout").split { should contain(/server=" "/) }
  end
end

control 'tomcat-57' do
  impact 1.0
  title 'Add X-Frame-Options Header'
  desc 'The `X-Frame-Options` response header with the value `DENY`, informing browsers not to display the content of the web page in any frame'

  describe bash("find ${Value:catalina.base} -name web.xml | xargs grep -A1 \"x-frame-header\" | grep \"<filter-class>XFrameHeaderFilter</filter-class>\"") do
    its('content') { should match(/^\s+<filter-class>XFrameHeaderFilter</filter-class>$/) }
  end
end

control 'tomcat-58' do
  impact 1.0
  title 'Add HSTS Header'
  desc 'HTTP Strict Transport Security (HSTS) is a web security policy mechanism which helps to protect websites against protocol downgrade attacks and cookie hijacking. It allows web servers to declare that web browsers (or other complying user agents) should only interact with it using secure HTTPS connections, and never via the insecure HTTP protocol. HSTS is an IETF standards track protocol and is specified in RFC 6797.'

  describe bash("find ${Value:catalina.base} -name context.xml | xargs grep \"httpHeaderSecurity\"") do
    its('content') { should match(/^\s+<filter-name>httpHeaderSecurity</filter-name>"$/) }
  end
end

control 'tomcat-59' do
  impact 1.0
  title 'FileETag None'
  desc 'It allows remote attackers to obtain sensitive information like inode number, multipart MIME boundary, and child process through Etag header. To prevent this vulnerability, let’s implement it as below. This is required to fix for PCI compliance.'

  describe bash("find ${Value:catalina.base} -name web.xml | xargs grep \"noetag\"") do
    its('content') { should match(/^\s+<filter-name>noetag</filter-name>"$/) }
  end
end

it would be nice to have resource for this, because of the regex stuff

**Comment by adamleff** [comment]
@atomic111 makes a lot of sense - thanks for sharing some of your specific use cases. I'm going to mark this issue as a feature request and leave it in our hopper. :)

**Comment by atomic111** [comment]
@adamleff great, thank you

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
