### ISSUE TITLE
Feature Request Nginx resource

### ISSUE THREAD

**Issue by atomic111** [inspec/inspec#1804]
### Description

I implement for a customer right now a nginx baseline with regex, but it would be nice to also have a nginx resource.

**Comment by atomic111** [comment]
sorry i missed #1615

**Comment by aaronlippold** [comment]
Hi,

Yes I was going to take a look at pulling the work at the dev-sec nginix
work and start creating a resource. What do you think.

Aaron

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by atomic111** [comment]
@aaronlippold yes, good idea. i added more stuff to the customer nginx baseline. i have to push this in the dev-sec repo

**Comment by aaronlippold** [comment]
Did you get a chance to push the new stuff to the nginx code in dev-sec?


--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by atomic111** [comment]
@aaronlippold no sorry

**Comment by aaronlippold** [comment]
OK. If you could push it or just tarball it up and email it over. I would
like to let my teams use it as a reference.

Aaron

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
