### ISSUE TITLE
Should control ids allow slug url characters only?

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1817]
### Description

Currently `control ids` are simple strings. Therefore the following is valid InSpec:

```
control 'Checking /etc/missing2.rb existance' do
  impact 0
  title "Check /etc/missing2.rb"
  desc "File test in failure-success.rb"
  describe file('/etc/missing2.rb') do
    it { should be_file }
  end
end
```

I am not fan of allowing non-sluggable characters in control ids (https://en.wikipedia.org/wiki/Semantic_URL#Slug)

### Possible solution

* add a warning to `inspec check`

### InSpec and Platform Version

latest

**Comment by adamleff** [comment]
Is there a technical reason to prevent non-sluggable characters?

I'm inclined to agree with you as long as we:

 * document what's allowed
 * add the `inspec check` warning, and deprecate it
 * enforce it in the next major bump

But I'm curious as to your reasoning. :)

**Comment by clintoncwolfe** [comment]
@chris-rock are you still interested in this feature?

**Comment by clintoncwolfe** [comment]
I'm going to go ahead and close this, and the motivation isn't clear.
