### ISSUE TITLE
Inspec oracledb_session resource not connecting to the database.

### ISSUE THREAD

**Issue by Bhanukiran117** [inspec/inspec#1821]
### Description

I am using oracledb_session resource in test cases, its not connecting to the database since its using wrong connection string.

### InSpec and Platform Version

[oracle@xx~]$ inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.24.0

### Replication Case

describe oracledb_session(user: 'system', pass: 'test123',sid: 'HELLODB', sqlplus_bin: '/u00/app/oracle/product/11.2.0.4/database/bin/sqlplus').query('SELECT NAME FROM v\$database;') do
  its('stdout') { should eq('HELLODB') }
  end

Output :+1: 

     ×  Command echo "SELECT NAME FROM v\$database;" | /u00/app/oracle/product/11.2.0.4/database/bin/sqlplus -s system/test123@localhost/HELLODB stdout should eq "HELLODB"

     expected: "HELLODB"
          got: "ERROR:\nORA-12541: TNS:no listener\n\n\nSP2-0306: Invalid option.\nUsage: CONN[ECT] [{logon|/|proxy}...nnect_identifier>]\n      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]\n"

     (compared using ==)

     Diff:
     @@ -1,2 +1,9 @@
     -HELLODB
     +ERROR:
     +ORA-12541: TNS:no listener
     +
     +
     +SP2-0306: Invalid option.
     +Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM}] [edition=value]]
     +where <logon> ::= <username>[/<password>][@<connect_identifier>]
     +      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]

### Possible Solutions

Its actually trying to connect "localhost/HELLODB" connection string instead of "HELLODB"

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by aaronlippold** [comment]
@Bhanukiran117 given our work, this should resolve the issue, https://github.com/chef/inspec/pull/1827. Could you pull the branch and test it on your side given you have all the oracle resources setup already. If there are any issues, please put them on the PR conversation and I will resolve.
