### ISSUE TITLE
Unique exit code for control/profile failures

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1825]
I'd like to be able to differentiate between a "failed InSpec run" (where InSpec failed to execute profiles due to a Ruby issue, SSL issue fetching a profile, etc.) and a "successful InSpec run that encountered a profile/control failure". This will allow tools like the habitat profile creator to present more useful error messages to the user without parsing JSON.

Proposal:
 * 0: successful run, no control failures
 * 100: successful run, critical failures found
 * 101: successful run, major failures found
 * 102: successful run, minor failures found
 * anything else: unsuccessful run

**Comment by elliott-davis** [comment]
![tenor-91893169](https://cloud.githubusercontent.com/assets/1130349/26169099/1b24d790-3b02-11e7-9b2a-e7f9756e5ea9.gif)

**Comment by chris-rock** [comment]
That is a great idea @adamleff

**Comment by trevor-vaughan** [comment]
Just ran into this when running automated tests, very much a :+1:

**Comment by adamleff** [comment]
NOTE TO IMPLEMENTER: since this is a breaking change, the PR should target the `release-2.0` branch, NOT `master`

**Comment by arlimus** [comment]
great stuff!!

**Comment by adamleff** [comment]
This should be ready to implement once @jquick completes #2415

**Comment by chris-rock** [comment]
The exit codes we settled on are:

    0 run ok + all passed:
    100 run okay + failures
    101 run okay + skipped only
