### ISSUE TITLE
interface documentation issue, missing argument

### ISSUE THREAD

**Issue by humhumdurr** [inspec/inspec#1829]
joshbarker
8:41 AM
Hi guys, looks like the documentation for the interface resources needs an update (https://www.inspec.io/docs/reference/resources/interface/). It doesn't show that you need to pass a network device to the interface resource.Current looks like:

describe interface do
  it { should be_up }
  its('speed') { should eq 1000 }
  its('name') { should eq eth0 }
end

Compared to:

describe interface('eth0') do
  it { should be_up }
  its('speed') { should eq 1000 }
  its('name') { should eq eth0 }
end

**Comment by adamleff** [comment]
PR #1833 opened to address this :) Thanks!
