### ISSUE TITLE
"address" is mentioned in the doc, but not implemented

### ISSUE THREAD

**Issue by humhumdurr** [inspec/inspec#1830]
The interface resource documentation: 

https://www.inspec.io/docs/reference/resources/interface/

mentions "address", but in reality it isn't implemented yet!

Can you please implement it, with other basic checks, like: netmask? 

Thanks.

**Comment by adamleff** [comment]
@humhumdurr Thanks for the issue! I put up PR #1833 to correct the docs for now, and we'll leave this issue open as a feature request to add address and netmask when cycles permit. PRs also welcome 🙂

**Comment by mattlqx** [comment]
I can't believe this has been hanging for so long! Seems super basic to me to be able to verify interface configuration. Oh well, here's a PR. 🤓
