### ISSUE TITLE
Missing filesystem size check for InSpec

### ISSUE THREAD

**Issue by humhumdurr** [inspec/inspec#1843]
I need to check that the stdout output is >=32000
just want to check a filesystem size
that it is at least 32000 MBytes big
so far I got:

 describe command('/usr/bin/df -m / --output=size |  sed "/blocks/d; s/ *//g"') do
  its('stdout').to_i { should be >= 32000 }
 end

but the ".to.i" gives error: /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:732:in `method_missing': undefined method `to_i' for #<Class:0x000000035f5bb0> (NoMethodError)Did you mean?  to_s

solution: it would be great if InSpec would have a resource for checking filesystem size too!

**Comment by aaronlippold** [comment]
```
describe command('/usr/bin/df -m / --output=size | sed "/blocks/d; s/ *//g"') do
  its('stdout.to_i') { should be >= 32000 }
end
```
```
Profile: tests from test.rb
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222


  Command /usr/bin/df
     ✔  -m / --output=size | sed "/blocks/d; s/ *//g" stdout.to_i should be >= 32000

Test Summary: 1 successful, 0 failures, 0 skipped
```

**Comment by arlimus** [comment]
@humhumdurr There was a tiny bug with the way that `to_i` was attached. If you look at @aaronlippold 's example you can see that he pulled it in. You can also write:

```
describe command('/usr/bin/df -m / --output=size | sed "/blocks/d; s/ *//g"') do
  its('stdout') { should cmp >= 32000 }
end
```

It abstracts the `to_i` via the wonderful `cmp` operator, which does the heavy-lifting for you.

**Comment by arlimus** [comment]
Leaving this open and moving to resources request.

**Comment by arlimus** [comment]
Actually closing as a duplicate / follow-up to your other request: https://github.com/chef/inspec/issues/1831

**Comment by harsimranrajpal21** [comment]
any way to check space left on file system rather than total space??
