### ISSUE TITLE
InSpec ini resource won't parse dotted parameters

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec#1846]
### Description

InSpec does not parse parameters in ini files formatted like so:
```
[newrelic]
newrelic.license = "foo"
```

With the following spec:
```
    describe ini('/etc/php/7.1/mods-available/newrelic.ini') do
        its('newrelic.appname') { should eq 'App Name' }
        its('newrelic.license') { should eq '!TBD in an Ansible Vault!' }
    end

```

It will always return the following:
```
 INI /etc/php/7.1/mods-available/newrelic.ini
     ∅  newrelic.appname should eq "App Name"

     expected: "App Name"
          got: nil

     (compared using ==)

     ∅  newrelic.license should eq "!TBD in an Ansible Vault!"

     expected: "!TBD in an Ansible Vault!"
          got: nil

     (compared using ==)
```

This is because the `ini` resource implementation is [breaking the contract](https://github.com/chef/inspec/blob/master/lib/resources/ini.rb#L17-L19) with the [underlying class implementation](https://github.com/chef/inspec/blob/master/lib/utils/simpleconfig.rb#L13-L14).

### InSpec and Platform Version
InSpec: `1.25.1`
Platform Version: `debian/jessie64`

### Replication Case

Please use the examples above.

### Possible Solutions

Have InSpec's `ini` resource respect the underlying class contract

### Stacktrace

None available.

**Comment by walterdolce** [comment]
Hmm. By looking at InSpec's tests and after trying it works this way:
```
    describe ini('/etc/php/7.1/mods-available/newrelic.ini') do
        its(['newrelic', 'newrelic.appname']) { should eq '"App Name"' }
        its(['newrelic', 'newrelic.license']) { should eq '"!TBD in an Ansible Vault!"' }
    end
```

Which makes this issue invalid. Will close it but the docs should reflect this otherwise you might get more of those in the future :)

**Comment by axelfast** [comment]
@walterdolce I owe you a big cold 🍺
