### ISSUE TITLE
Using Automate - `compliance_profile_name': undefined method `[]' for nil:NilClass (NoMethodError) seeing 1.25.1 Inspec 

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#1848]
### Description

 /opt/chefdk/embedded/bin/inspec vendor --overwrite
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/bundles/inspec-compliance/target.rb:90:in `compliance_profile_name': undefined method `[]' for nil:NilClass (NoMethodError)
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/bundles/inspec-compliance/target.rb:69:in `resolved_source'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/cached_fetcher.rb:23:in `resolved_source'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/dependencies/requirement.rb:63:in `resolved_source'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/dependencies/resolver.rb:59:in `each'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/dependencies/resolver.rb:59:in `resolve'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/dependencies/resolver.rb:31:in `resolve'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/dependencies/dependency_set.rb:89:in `vendor'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/profile.rb:393:in `generate_lockfile'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/profile_vendor.rb:15:in `vendor!'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/base_cli.rb:159:in `vendor_deps'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/lib/inspec/cli.rb:114:in `vendor'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.25.1/bin/inspec:12:in `<top (required)>'

### InSpec and Platform Version
1.25.1 (also 1.25.0)

### Replication Case

If I role back to 1.24.0 Inspec gem no issues and vendors as it should:

/opt/chefdk/embedded/bin/inspec vendor --overwrite
Dependencies for profile /var/opt/delivery/compliance/compliance-profiles/comp_user/MITRE_CIS_WIN2012R2 successfully vendored to /var/opt/delivery/compliance/compliance-profiles/comp_user/MITRE_CIS_WIN2012R2/vendor

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment]
@timusmc96 Thanks for submitting this issue.

I'm unable to reproduce this so I think this possibly has something to do with your configuration. Would you please provide the contents of your `~/.inspec/compliance/config.json` file? Please redact your token, but please do not do a full redaction of your `server` key -- redact the hostname if needed, but I suspect something with your server entry is causing the issue.

If you'd prefer to send it to me directly, you can email it to me at `adamleff at chef dot io` or you can send it to me on the Community Slack via direct message to `@adamleff` - thanks!

**Comment by timusmc96** [comment]
{"user":"comp_user","server":"https://citauto/compliance/profiles","automate":{"ent":"company_automate_dev","token_type
":"usertoken"},"server_type":"automate","insecure":true,"token":"","version":{}}

**Comment by adamleff** [comment]
@timusmc96 That server entry looks suspicious to me. Can you remove `/profiles` from that entry so that it's just `https://citauto/compliance` and confirm if that fixes the issue or not?

**Comment by adamleff** [comment]
@timusmc96 if that doesn't correct issue, can you please try to login again to refresh your config? `inspec compliance login` if using Chef Compliance, or `inspec compliance login_automate` if using Chef Automate.
