### ISSUE TITLE
docker_container: running matcher does not work by name with linked containers

### ISSUE THREAD

**Issue by alexanderBendo** [inspec/inspec#1855]
### Description

If containers are linked the `running` test will fail for the linked container.

### InSpec and Platform Version

debian stretch
inspec 1.25 (from ChefDK 1.4.3)

### Replication Case

`docker run -d --rm --name c1 centos:7 yes`
`docker run -d --rm --name c2 --link c1:container1 centos:7 yes`

```
describe docker_container('c1') do                                       
  it { should be_running }                                                         
end
```

### Possible Solutions

The test fails because in `lib/resources/docker_container.rb` line 94 the method `container_info` filters by name doing an exact match. However, as the container status is retrieved by doing `docker ps -a --no-trunc` the actual name for container `c1` in the replication case would be `c1,c2/container1`, that is, the concatenation of all names.

In Serverspec this works because the container status is retrieved individually by name using `docker inspect`.

**Comment by leftathome** [comment]
I ran into this bug this week!  It's still here as of InSpec 1.34.1.  Found it on the very first cookbook I decided to migrate from using Serverspec to InSpec.  :(

The good news is that I fixed it just by monkey-patching `container_info()` to also check if `names` started with `opts[:name] + ","`, which should satisfy the above test case.
