### ISSUE TITLE
Cannot use http resource with custom certificate

### ISSUE THREAD

**Issue by ephracis** [inspec/inspec#1862]
### Description

We have a web server with HTTPS using a custom CA. When we run

    describe http('https://example.com') do
      its(:status) { should eq 200 }
    end

We get the following

> SSL_connect returned=1 errno=0 state=error: certificate verify failed

### InSpec and Platform Version

InSpec: 1.25.1
OS: CentOS 7.3

### Replication Case

Set up a web server using a certificate that is either self signed or signed by a CA that Ruby does not trust by default. Then use the code above to verify the ability to connect to the web server.

### Possible Solutions

Make it possible to configure InSpec to:
1. Trust a custom CA
2. Ignore self signed certificates
3. Trust the CAs configured in the underlying Operating System

**Comment by smith** [comment]
You can ignore SSL verification with:

```ruby
describe http('https://example.com', ssl_verify: false) do
  its(:status) { should eq 200 }
end
```

This is not currently documented on https://www.inspec.io/docs/reference/resources/http/ and needs to be added.

**Comment by smith** [comment]
Added docs for this in #1864.
