### ISSUE TITLE
support legacy backend configuration calls (rspec/serverspec)

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#187]
```
set :backend, :ssh
RSpec.configure do |conf|
  conf.host = ...
  conf.ssh_options = ...
end
```

**Comment by danehammer** [comment]
Is the vision of inspec to be backwards compatible to serverspec tests?

**Comment by arlimus** [comment]
I'm closing this issue because the definition was too broad and we tackled a lot of work items over the course of time. Please open new issues for serverspec backwards compatibility or migration help if you need them!

In the meantime, there is now also this wonderful guide on the inspec.io docs to help with migrations:
http://inspec.io/docs/reference/migration/

Please reach out if you have more points to add!
