### ISSUE TITLE
Inspec exec Could not parse PKey: no start line on keys that have been added to ssh-agent

### ISSUE THREAD

**Issue by wilshire461** [inspec/inspec#1877]
### Description

When using Inspec exec to ssh to another machine with a passphrase ssh-key, it always fails with the message

```
Could not parse PKey: no start line
```

This happens regardless of either adding the ssh-key to ssh-agent, or passing the key with the -i flag pointing at the private key file.

The same key is used for passwordless ssh access to our entire cluster and is working without issue..

```
[root@admin01 curc-inspec]# ssh-add -l
4096 e2:6a:51:7b:c1:a4:19:6b:b8:8e:45:d1:f0:89:c5:bc /root/.ssh/id_rsa-summit (RSA)
[root@admin01 curc-inspec]# ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-gnu]
[root@admin01 curc-inspec]# inspec exec roles/summit/shas -t ssh://shas0101 --format=progress
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Could not parse PKey: no start line
[root@admin01 curc-inspec]# ssh shas0101
Last login: Wed May 31 10:27:41 2017 from 10.225.160.12
exit
[root@admin01 curc-inspec]# inspec --version
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.24.0

Your version of InSpec is out of date! The latest version is 1.26.0.

[root@admin01 curc-inspec]# gem update inspec
Updating installed gems
Updating inspec
Fetching: train-0.24.0.gem (100%)
Successfully installed train-0.24.0
Fetching: inspec-1.26.0.gem (100%)
Successfully installed inspec-1.26.0
Parsing documentation for train-0.24.0
Installing ri documentation for train-0.24.0
Installing darkfish documentation for train-0.24.0
Parsing documentation for inspec-1.26.0
Installing ri documentation for inspec-1.26.0
Installing darkfish documentation for inspec-1.26.0
Done installing documentation for train, inspec after 16 seconds
Parsing documentation for inspec-1.26.0
Parsing documentation for train-0.24.0
Done installing documentation for inspec, train after 8 seconds
Gems updated: inspec train

[root@admin01 curc-inspec]# inspec exec roles/summit/shas -t ssh://shas0101.rc.int.colorado.edu --format=progress
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Could not parse PKey: no start line
```

### InSpec and Platform Version

V 1.24
V 1.26

### Possible Solutions

I have tried using several version of net-ssh (2.7.0, 2.5.2,4.0,4.1) and none of them solved the issue.

Any help is greatly appreciated, I was really looking forward to using this tool.

**Comment by adamleff** [comment]
@wilshire461 thanks for submitting this issue.

I'm afraid I'm unable to reproduce this issue. All of my SSH keys are password-protected and I use `ssh-agent` to store them during my session. I was successfully able to scan a host with InSpec via SSH with one of my password-protected keys.

Is it possible your private key is in a binary format instead of a PEM-style encoded format? I believe that's the issue that net-ssh is having trying to read your private key.

**Comment by wilshire461** [comment]
Adam,

Unfortunately the private key is in the PEM style format with a header and footer looking as one would expect.

```
-----BEGIN RSA PRIVATE KEY-----
....
-----END RSA PRIVATE KEY-----
```

**Comment by adamleff** [comment]
@wilshire461 bummer. Unfortunately since I'm not able to reproduce it, I'm afraid I don't know how best to proceed on either guiding you toward a fix or fixing something in InSpec.

**Comment by wilshire461** [comment]
Can go ahead and close this then, we'll look at other tools that work as advertised 😄

**Comment by adamleff** [comment]
@wilshire461 I don't think that's a completely fair comment as InSpec itself does work as advertised and we're making an effort to help solve your problem. You've obviously found yourself in an edge case with one of our upstream dependencies (`net-ssh` Ruby gem) that we haven't seen before, and without you giving me your private key, I don't know how to reproduce. We have a pretty good history of fixing problems that are brought to our attention. 🙂 

If you are willing to create a different password-protected test-only private key that shows this same issue and are willing to share it with me, I can commit to debugging this issue further and getting to the bottom of it.
