### ISSUE TITLE
how to invoke inspec runner correctly

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#1892]
### Description

I've created an inspec_handler cookbook that is able to deploy and run tests that live with my cookbooks (much the same way we are accustomed to with the audit cookbook, or minitest). (I'm in the process of getting approvals to release this cookbook to the community with an accompanying blog post). 

I'm invoking the tests via the Inspec::InspecCLI class, but the runner [exits](https://github.com/chef/inspec/blob/2dd05857cf083a0e6cca5a8ac23ed9f345710d97/lib/inspec/base_cli.rb#L83) and I'm unable to capture the exit status using this method.  How can I invoke the inspec runner in a similar way where I can provide it an array of test files and a profile-attributes arg?

```
      require 'inspec'
      require 'inspec/cli'
      args = ['exec'] + tests.to_a + %w(--attrs /tmp/node.yaml)
      Chef::Log.warn("inspec exec #{args.join(' ')}")

      begin
        res = Inspec::InspecCLI.start(args)
      rescue SystemExit => e
       # this is always triggered no matter if the tests passed or failed, no additional metadata available in error object
        log('InSpec detected errors, failing chef run'.red)
        raise('Chef Run ABORTED due to failed InSpec tests')
      end
```

**Comment by trickyearlobe** [comment]
I know the issue was closed, but this is how I run profiles which have been archived with
`inspec archive some_profile`.

I expect it will also work (perhaps needing a few mods) with a profile directory, or functional tests in TK `/tests`.

```
runner = Inspec::Runner.new(target: 'some remote target if its not a local scan')
runner.add_target('path to some profile')
runner.run
report = runner.report

do.some.thing.with(report)
```
