### ISSUE TITLE
Dynamic Severity Based on Results

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#1899]
### Description

Many policies have text like the following from the DISA STIG:

> If the value of \"-f\" is set to \"1\", the system is configured to only send
> information to the kernel log regarding the failure.
> 
> If the \"-f\" flag is not set, this is a CAT I finding.
> 
> If the \"-f\" flag is set to any value other than \"1\" or \"2\", this is a CAT II
> finding.
>
> If the \"-f\" flag is set to \"1\" but the availability concern is not documented or
> there is no monitoring of the kernel log, this is a CAT III finding.

Given this, there needs to be a way to modify the 'severity' output based on the result of the test itself.

**Comment by adamleff** [comment]
@trevor-vaughan this is a very interesting feature request. Thank you for submitting it, and thank you for giving a real-world use case. That does a great deal for us in understanding why such a feature would be helpful to the community.

Just thinking out loud a bit... I wonder if we could implement it such that an `impact` statement would be valid inside a `describe` block as well as within the `control` itself, with the following behavior:

 * the `impact` in the `control` is the default impact
 * an `impact` inside of a failed `describe` can override the `control` impact
 * in the event of a `control` with multiple `describe`s that fail, the highest impact will be reported

I'm not saying this is possible or it's what we'll do, but I wanted to jot down some ideas I had when I saw your issue. What do you think about that, @trevor-vaughan?

@arlimus / @chris-rock / @alexpop - this is a pretty interesting use case. What are your thoughts?

**Comment by arlimus** [comment]
Fully valid use-case, thank you for posting it Trevor!
One of the goals should be to achieve a system that is able to reflect these requirements without getting overly complex.

Intriguing proposal Adam, clean and understandable, thank you!! Need to think about this idea for a bit as well...
:thinking:

**Comment by trevor-vaughan** [comment]
@adamleff This sounds like a reasonable solution to me.

You may want to have both a static override `impact:` and potentially an `impact_multiplier:` which would allow you to mathematically adjust the impact on the system.

We also need cross-test dependency adjustments.

In reading the Risk Management Framework from NIST, we should be adjusting our risk based on Defense in Depth concepts.

This means that you could have a test for IPTables that, if enabled properly, can lessen the impact of local tests.

So, if I have an IPTables rule (that is active) that prevents MySQL access completely, then the fact that MySQL is bound to an external port is no longer a CAT I, but is instead a CAT III.

That should probably be broken into a separate ticket though.

**Comment by adamleff** [comment]
@trevor-vaughan the multiplier concept is a neat one but I think would greatly complicate people's understandings of the tests. They become less declarative; you can't just read a test and know what the extent of the impact will be at face-value. I'd recommend we first start with static impacts and then discuss impact multiplier in a separate feature enhancement request.

Regarding your second concern (cross-test dependency adjustments), tests need to stand on their own. Having tests depend on other tests makes the test themselves fragile. We should log that as a separate feature enhancement request as that will need some deeper discussion and analysis.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
