### ISSUE TITLE
Double inheritance does not honor the os-family and controls are running for platform that does not pertain

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#1908]
### Description

Main Profile:

company_linux_profile
         inpec.yml file has the following:
                   depends:
   - name: company_rhel6_linux_compliance
     compliance: comp_user/company_rhel6_linux_compliance
   - name: company_rhel7_linux_compliance
     compliance: comp_user/company_rhel7_linux_compliance

Now if you look at the profiles company_rhel6_linux_compliance and company_rhel7_linux_compliance

profile inspec.yml  company_rhel6_linux_compliance
supports:
   - os-family: redhat
     release: 6.0
   - os-family: redhat
     release: 6.5
   - os-family: redhat
     release: 6.6
   - os-family: redhat
     release: 6.7
   - os-family: redhat
     release: 6.8
   - os-family: redhat
     release: 6.9

profile inspec.yml  company_rhel7_linux_compliance
supports:
   - os-family: redhat
     release: 7.0
   - os-family: redhat
     release: 7.1
   - os-family: redhat
     release: 7.2
   - os-family: redhat
     release: 7.3

This causes both platforms to run on a server that may not be an OS 6.X or 7.X.

### InSpec and Platform Version

inspec 1.26.0

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

os-family should be supported so you are only dealing with one profile with many versions of OS profiles.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by timusmc96** [comment]
Let me know on this one if we can have a discussion, so I can clarify, not sure of the wording needed here.

**Comment by timusmc96** [comment]
@chris-rock what are your overall thoughts on this one?   I just want to pass timeline on what we are thinking here.  As this function is important to really simply the profiles example supporting rhel6 and rhel 7 today.  The one profile with the others depend, makes this more manageable.

**Comment by chris-rock** [comment]
Would you like to push a PR for that? The issue is located here https://github.com/chef/inspec/blob/e254f79392ad064dfdc622d16f29562e08822f35/lib/inspec/metadata.rb#L91-L103 and it references to https://github.com/chef/inspec/blob/e254f79392ad064dfdc622d16f29562e08822f35/lib/inspec/metadata.rb#L52-L79

**Comment by timusmc96** [comment]
@chris-rock thanks, let me test it out and will go from there.

**Comment by timusmc96** [comment]
@chris-rock when you get a moment lets work through this one if we can.  Thanks
