### ISSUE TITLE
How to improve output to include test names?

### ISSUE THREAD

**Issue by mostafahussein** [inspec/inspec#1911]
I have tried the following example:
```ruby
describe login_defs do
  its('PASS_MAX_DAYS') { should eq '180' }
  its('PASS_MIN_DAYS') { should eq '1' }
  its('PASS_MIN_LEN') { should eq '15' }
end
```

Which gives the following report:
```bash
Profile: tests from new_spec.rb
Version: (not specified)
Target:  local://


  login.defs PASS_MAX_DAYS
     ∅  should eq "180"
     
     expected: "180"
          got: "99999"
     
     (compared using ==)
     
     ∅  should eq "1"
     
     expected: "1"
          got: "0"
     
     (compared using ==)
     
     ∅  should eq "15"
     
     expected: "15"
          got: "5"
     
     (compared using ==)
     
Test Summary: 0 successful, 3 failures, 0 skipped
```

How could I make the output like this:
```
Profile: tests from new_spec.rb
Version: (not specified)
Target:  local://


  login.defs PASS_MAX_DAYS
     ∅  should eq "180"
     
     expected: "180"
          got: "99999"
     
     (compared using ==)
     
  login.defs PASS_MIN_DAYS
     ∅  should eq "1"
     
     expected: "1"
          got: "0"
     
     (compared using ==)
     
  login.defs PASS_MIN_LEN
     ∅  should eq "15"
     
     expected: "15"
          got: "5"
     
     (compared using ==)
     

Test Summary: 0 successful, 3 failures, 0 skipped
```
As the first output could be misleading so in the current moment I have changed the code into the code below which gives me the second output:
```ruby
describe login_defs do
  its('PASS_MAX_DAYS') { should eq '180' }
end
describe login_defs do
  its('PASS_MIN_DAYS') { should eq '1' }
end
describe login_defs do
  its('PASS_MIN_LEN') { should eq '15' }
end
```
Inspec version: `1.27.0`

Is there a better way ?

**Comment by aaronlippold** [comment]
Thanks for reporting this. We have had a discussion on the slack channel
about this but I don't think we created an issue.

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by timusmc96** [comment]
Also seeing this issue when you are using single number and the response is a double digit, in the case below fails because it is "21", but if you change this to should_be "10", this passes, the control is >= 7 days for the password.

  describe login_defs do
    its('PASS_WARN_AGE') { should be >= "7" }
  end

**Comment by clintoncwolfe** [comment]
That is indeed how InSpec reporting works.  If you want a separate subject line for each test, you'll need to put them in their individual `describe` blocks.  One improvement I might suggest would be to group the describe blocks together into a single `control` block.

**Comment by clintoncwolfe** [comment]
As there has not been any traffic on this issue in a few days, I'm closing this.  If you feel your question has not been answered, feel free to re-open!  Thanks!
