### ISSUE TITLE
Profile controls are not all being run with multiple rb files using only_if in some of them

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#1914]
### Description
Basically we have a profile with a list of controls. 

http.rb
php.rb
splunk.rb
sshd.rb
redhat_controls.rb

http.rb, php.rb, plunk.rb and sshd.rb all have only_if statements, which work great.   The redhat_controls does not have an only_if statement and is being skipped.   I renamed to controls_redhat.rb, now it seems all the controls are running.

### InSpec and Platform Version

1.26.0

client - 12.18.31

### Replication Case

create profile with multiple rb control files and include only_if statement, see if they are are checked running inspec

### Possible Solutions

Using only_if causing other controls to be skipped even though they do not have an only_if skip.   Does the order matter for the profiles

**Comment by timusmc96** [comment]
Let me know on this one if we can have a discussion, so I can clarify, not sure of the wording needed here.

**Comment by antoniobeyah** [comment]
I ran into this problem as well, only slightly different.  I am using the [dev-sec/cis-kubernetes-benchmark](/dev-sec/cis-kubernetes-benchmark) and it contains an `only_if` in each control file.  All works well until one of the only_if blocks returns false and then that is set in stone and the only_if is no longer evaluated.

References:
[1_1_master_node_api_server.rb](/dev-sec/cis-kubernetes-benchmark/blob/b8c6ed9bcb3b38d3f8ba1b06488dc5a885a419ee/controls/1_1_master_node_api_server.rb#L20-L22)
[1_2_master_node_scheduler.rb](/dev-sec/cis-kubernetes-benchmark/blob/b8c6ed9bcb3b38d3f8ba1b06488dc5a885a419ee/controls/1_2_master_node_scheduler.rb#L20-L22)

workaround:
[control_eval_context.rb](/chef/inspec/blob/1ea83f526cfd049587d9c776906f3992043d6b3d/lib/inspec/control_eval_context.rb#L134) `@skip_profile ||= !yield` -> `@skip_profile = !yield` 
[rule.rb](/chef/inspec/blob/1ea83f526cfd049587d9c776906f3992043d6b3d/lib/inspec/rule.rb#L105) <-- `@__skip_rule ||= !yield` -> `@__skip_rule = !yield`

works around the problem for me, but won't help for @timusmc96 use case

**Comment by adamleff** [comment]
Totally able to reproduce this. Created a new profile with 5 controls files, each contained a single control that looked like this:

```ruby
control 'http' do
  title 'http'
  desc 'http'
  impact 1.0

  describe 'http' do
    it { should cmp 'http' }
  end
end

only_if { 1 == 2 }
```

In my `redhat_controls.rb` I did not include the `only_if`. And yet, here's my output:

```
Profile: InSpec Profile (onlyif)
Version: 0.1.0
Target:  local://

  ✔  http: http
     ✔  http should cmp == "http"
  ↺  php: php
     ↺  Skipped control due to only_if condition.
  ↺  redhat: redhat
     ↺  Skipped control due to only_if condition.
  ↺  splunk: splunk
     ↺  Skipped control due to only_if condition.
  ↺  sshd: sshd
     ↺  Skipped control due to only_if condition.
```

In no way should the `http` control have executed. 🙁
