### ISSUE TITLE
inspec shell - help should also list available configuration objects

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#1925]
### Description
When using the interactive inspec shell the `help` command should list the available configuration objects. For example:
* `os`
* `passwd`
* `sshd_config`

Example of reading `os` object parameters:
```ruby
inspec> os.params
os.params
=> {:name=>"suse", :family=>"suse", :release=>"12.1", :arch=>"x86_64"}
```
### InSpec and Platform Version
`inspec-1.20.0-1.sles12.x86_64`

**Comment by ghost** [comment]
Also the https://www.inspec.io/docs/reference/shell/ page should also contain these information

**Comment by arlimus** [comment]
We missed to close this issue: the functionality is now included:

```
> help resources
```

will list all resources in the inspec shell. When entering the shell it will present you with the `help` command which leads to the `help resources` command and with that nice progression for users to explore this environment. Thank you for your idea, this helped get it supported in InSpec :)
