### ISSUE TITLE
inspec.yml supports doesn't support centos with os-family and a releasere

### ISSUE THREAD

**Issue by mattray** [inspec/inspec#1929]
Testing with CentOS 7.3, the inspec.yml works with
```
supports:
  - os-family: redhat
```
but not
```
supports:
  - os-family: redhat
    release: 7.3
```

### InSpec and Platform Version
Chef Development Kit Version: 1.4.3
inspec version: 1.25.1

but it appears the Chef 13.1 in kitchen is using 1.16.0
```
$ kitchen verify telstra
-----> Starting Kitchen (v1.16.0)
-----> Verifying <telstra-centos-73>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [This OS/platform (centos) is not supported by this profile.] on telstra-centos-73
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by chris-rock** [comment]
At this point in time, version is doing an exact match. In a local test with `docker run -it centos:73 /bin/bash`, I was able to restrict access, if I used:

```
name: version
title: InSpec example inheritance
version: 1.0.0
supports:
  - os-family: redhat
    release: 7.3.1611
```

You can see the exact version with `os.release`.

```
describe os do
  its('release') { should cmp >= '7.3' }
end
```

Right now, the mechanism works as designed. Nevertheless, I agree that this is annoying to list all individual release versions. @mattray I would like to close this issue in favor of #1740

**Comment by mattray** [comment]
@chris-rock I agree, #1740 is what needs to be fixed.
