### ISSUE TITLE
CIS Windows 2012 profile as a dependency fails to upload to Automate

### ISSUE THREAD

**Issue by simfish85** [inspec/inspec#1932]
### Description
On a Windows workstation, when I create an Inspec profile with a dependency on the `cis-windows2012r2-level1-memberserver` profile and attempt to upload it from the command line using `inspec compliance upload . --log_level debug` then it fails to complete and hangs on the line `[2017-06-16T06:36:26+00:00] DEBUG: Loading controls/translated-controls.rb into #<Inspec::ProfileContext:0x5586870>`

I can work around this by running `inspec vendor .` and `inspec archive .` and then uploading the resulting .tar.gz file through the Automate profiles UI.

When I tried the same thing with the `windows-baseline` profile, the upload to Automate from the CLI succeeded.  I loaded both the CIS and DevSec profiles in from the profile supermarket in the Automate UI

### InSpec and Platform Version

Inspec from master
Windows Server 2016 Datacenter as the Workstation
Automate 0.8.53
cis-windows2012r2-level1-memberserver 2.2.0 from profile supermarket

### Replication Case

In the Automate Compliance UI, get the following profiles:

- CIS Microsoft Windows Server 2012 R2 Benchmark Level 1 - Member Server
- DevSec Windows Security Baseline

On the Workstation, generate an Inspec profile with the **Inspec.yml**
```name: cis-wrapper
title: CIS Wrapper InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0

depends:
  - name: cis-windows2012r2-level1-memberserver
    compliance: delivery/cis-windows2012r2-level1-memberserver
```

**controls.rb**
`include_controls 'cis-windows2012r2-level1-memberserver'`

And then from within the directory on the workstation run `inspec compliance upload .` the stack trace of the error is shown in the section below.

When I replace `cis-windows2012r2-level1-memberserver` with `windows-baseline` the upload succeeds.

### Possible Solutions

The workaround is to use `inspec vendor` and `inspec archive` then upload via the Automate UI

### Stacktrace

```C:\Users\chef\cis-wrapper> inspec compliance upload . --log_level debug
Dependencies for profile . successfully vendored to vendor
[2017-06-16T06:36:26+00:00] DEBUG: Resolve . into cache C:/Users/chef/.inspec/cache
[2017-06-16T06:36:26+00:00] DEBUG: Dependency does not exist in the cache .
[2017-06-16T06:36:26+00:00] DEBUG: Copy C:/Users/chef/.inspec/cache/f4ff7c1d62c7046ffc063bf4bcbbca0aa103278742fd8b612a5abca694fadab6.tar.gz to cache directory
I, [2017-06-16T06:36:26.777434 #5252]  INFO -- : Checking profile in .
I, [2017-06-16T06:36:26.777434 #5252]  INFO -- : Metadata OK.
[2017-06-16T06:36:26+00:00] DEBUG: Using cached dependency for {:compliance=>"delivery/cis-windows2012r2-level1-memberserver", :url=>"https://aut-workflow-server/compliance/profiles/delivery/cis-windows2012r2-level1-memberserver/tar", :sha256=>"f4ff7c1d62c7046ffc063bf4bcbbca0aa103278742fd8b612a5abca694fadab6", :backend=>Inspec::Backend::Class @transport=Train::Transports::Local::Connection, :attributes=>nil}
[2017-06-16T06:36:26+00:00] DEBUG: Loading controls/translated-controls.rb into #<Inspec::ProfileContext:0x5586870>```

**Comment by jerryaldrichiii** [comment]
Given how long it's been I'm going to close this.

If it is still an issue then feel free to reopen.
