### ISSUE TITLE
port is_listening fails unless lsof is already installed

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#1936]
### Description

the `port` matcher works without needing additional dependencies installed.

### InSpec and Platform Version

1.28.0 / centos 6/7

### Replication Case

it returns false (not-listening) when indeed it is up.  installing `lsof` manually fixes this issue.

### Possible Solutions

the matcher should detect if lsof is installed and fall back on netstat, etc if it is not.

**Comment by adamleff** [comment]
This should no longer be an issue. For Linux variants, we first try to use `ss` and then use `netstat`.  We only use `lsof` if the OS is AIX or Darwin. Please comment here if this is still an issue with additional information we can use to troubleshoot. Thanks!
