### ISSUE TITLE
 profile cis-rhel6-level1 version 1.4.0-1 which doesn't match >= 0

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#1940]
### Description

inspec compliance upload company_cis_rhel6 --overwrite

The profile cis-rhel6-level1 from {:compliance=>"comp_user/cis-rhel6-level1", :url=>"https://cit-automate.org/compliance/profiles/comp_user/cis-rhel6-level1/tar", :sha256=>"b41dad3b5c2a91924aa332562fb8d7abd16db3a64f42277ee07cb6174db03ca8"} has a version 1.4.0-1 which doesn't match >= 0

### InSpec and Platform Version

1.28, but issue is the same for 1.26, 1.27

### Replication Case

inspec compliance upload company_cis_rhel6 --overwrite

### Possible Solutions

Seems that the -1 with these profile version is not being accounted for

### Stacktrace

The profile cis-rhel6-level1 from {:compliance=>"comp_user/cis-rhel6-level1", :url=>"https://cit-automate.org/compliance/profiles/comp_user/cis-rhel6-level1/tar", :sha256=>"b41dad3b5c2a91924aa332562fb8d7abd16db3a64f42277ee07cb6174db03ca8"} has a version 1.4.0-1 which doesn't match >= 0

**Comment by chris-rock** [comment]
I am not sure I fully understand this issue. Are you trying to upload a profile that has `1.4.0-1` as version. And the CLI is showing that error? Are you able to upload the profile via UI?

**Comment by timusmc96** [comment]
yes so I do an upload with rhel7 no issues, version is 1.1.0 for cis.  rhel6 version of cis is 1.4.0-1 and I can not upload or vendor the profile, get this error

 inspec vendor --overwrite
The profile cis-rhel6-level1 from {:compliance=>"comp_user/cis-rhel6-level1", :url=>"https://cit-automate.org/compliance/profiles/comp_user/cis-rhel6-level1/tar", :sha256=>"b41dad3b5c2a91924aa332562fb8d7abd16db3a64f42277ee07cb6174db03ca8"} has a version 1.4.0-1 which doesn't match >= 0

**Comment by chris-rock** [comment]
Understood. Thank you

**Comment by adamleff** [comment]
@chris-rock we should likely change this stuff to use `semverse` for comparisons since we're pulling it in now for use in `inspec check`, what do you think?

https://github.com/chef/inspec/blob/master/lib/inspec/dependencies/requirement.rb#L57-L59

**Comment by timusmc96** [comment]
What are your thoughts on this one?  Thanks

**Comment by adamleff** [comment]
While `1.4.0-1` is a valid SemVer version string, the `-` indicates it's a pre-release string and therefore many of the standard comparisons will not work as one would expect. The InSpec profile should use the `+` character instead to indicate the `1` is a build number, not a pre-release version number.

I'm still going to correct InSpec to properly compare/constrain SemVer versions, but ultimately this needs to be solved in the profiles themselves to not use `-` in the version string.

/cc @chris-rock @arlimus

**Comment by arlimus** [comment]
Interesting, wasn't aware of the recommendation on `+` for build version, very interesting!
For reference here:
http://semver.org/#spec-item-10
