### ISSUE TITLE
update mysql_session resource to have mysql_command method for stringbuilding of connection. 

### ISSUE THREAD

**Issue by rshade** [inspec/inspec#1942]
### Description

right now there are several options to build the mysql command in the mysql_session resource, break it out into it's own method to support unit testing. 

### InSpec and Platform Version

1.28.1
### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

break mysql command into its own method to be able to test returns.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment]
@rshade thanks for opening this issue to track the suggestion noted in https://github.com/chef/inspec/pull/1933#pullrequestreview-44674923. We should definitely do this to help the resource be more stable moving forward. I'll try and get to this myself, but if you are able to start working on it, just ping me here in this issue so we don't duplicate effort!
