### ISSUE TITLE
Directory resource says it's file

### ISSUE THREAD

**Issue by grv87** [inspec/inspec#1944]
### Description

Documentation about `directory` resource says that
> This is equivalent to using the file resource and the be_directory matcher

However, test output says about `File` and nothing about `be_directory` matcher.

### InSpec and Platform Version

inspec version: 1.28.1
host os: Windows 7 SP 1
tested os: Ubuntu Server 16.04.2

### Replication Case
```
    describe directory('/home/ubuntu/.gems') do
      it { should exist }
    end
```
Output:
```
     [PASS]  File /home/ubuntu/.gems should exist
```

I wonder whether `inspec` really checks that specified file is actually a directory.

**Comment by chris-rock** [comment]
@grv87 This is a correct assessment. We have the `it { should_not be_directory }` to test that. Right now the `directory` keyword is more an alias for `file` resource and we may want to change this. Is there anything specific that you want to use the directory resource?

**Comment by adamleff** [comment]
This is a bug. The `to_s` method defined in `lib/resources/directory.rb` that would print the resource as `Directory /path` is defined outside of the `Inspec::Resources::Directory` class, but instead on the `Inspec::Resources` module. 

I'll put up a PR to fix this right now.

**Comment by grv87** [comment]
@chris-rock, I want to be sure that specified path is actually a directory.

Current behavior deviates from documentation: when I pass regular file name to the `directory` resource, Inspec doesn't report any errors or failed test.

**Comment by adamleff** [comment]
@grv87 I agree with you, I think that's unclear... if you pass a non-directory to the `directory` resource, `it { should exist }` should not return true.

I've modified my PR #1950 to address this as well. Please take a look.

**Comment by adamleff** [comment]
@grv87 this is now fixed and will be in next week's InSpec release. Thanks for submitting this issue!
