### ISSUE TITLE
Provide naming convention for InSpec Profiles

### ISSUE THREAD

**Issue by akitada** [inspec/inspec#1945]
### Description

Please consider providing naming guide for InSpec Profiles as provided in [Chef Style Guide](https://docs.chef.io/ruby.html) for Chef Cookbooks.

Having a naming convention would help users avoid possible naming conflicts.

**Comment by chris-rock** [comment]
@akitada What do you mean by naming conventions? Where do you need guidance?

**Comment by akitada** [comment]
@chris-rock Something like [this](https://docs.chef.io/ruby.html#cookbook-naming) and [this](https://docs.chef.io/ruby.html#use-of-hyphens)

Apparently there is no convention for naming profiles. https://supermarket.chef.io/tools?type=compliance_profile

**Comment by chris-rock** [comment]
Okay, basically we want some naming conventions for inspec.yml and we may also want to have some best-practices for implementing a large amount of controls. Do you want to cover compliance use cases or integration test use cases?

**Comment by akitada** [comment]
I'd want the two because I use inspec for both purposes.

**Comment by chris-rock** [comment]
We should also implement those in `inspec check` so that we see the results all the time

**Comment by kmf** [comment]
@akitada I write Inspec controls for corresponding cookbooks in chef, so 
I made up a naming convention:  
- cookbooks: org_group_linux_administrators
- controls: org_control_group_linux_administrators.rb

but I would really prefer a style guide.

**Comment by chris-rock** [comment]
So I hear that we need a written style guide and a tool that implements verifies that style guide. Is that your understanding too?

**Comment by kmf** [comment]
Yes. Please.

**Comment by kmf** [comment]
@chris-rock is there a plan?

**Comment by kmf** [comment]
Guess this https://github.com/inspec/inspec/pull/3356 is going to solve this 🍾

**Comment by kmf** [comment]
can we close this now?
@jquick @arlimus @jerryaldrichiii
