### ISSUE TITLE
file mode is returning decimal instead of octal

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#1946]
### Description

When using the file resources mode matcher, it is matching incorrectly due to comparison of octal and decimal representations of the file mode.

### InSpec and Platform Version
inspec 1.28.1
centos 6/7

### Replication Case

```ruby
  describe file('/usr/bin/consul') do
    it { should exist }
    it { should be_file }
    its('mode') { should eq '0755' }
  end

    expected: "0755"
          got: 493
```
<img width="156" alt="screen shot 2017-06-20 at 12 21 30 pm" src="https://user-images.githubusercontent.com/1141542/27348973-087a9a32-55b3-11e7-90f0-121655a5481a.png">

**Comment by chris-rock** [comment]
Thank you for that question @kplimack 

In ruby you write octal numbers as `00765`. I assume you migrated from Serverspec and serverspec did some magic that we don't. You need to use plain ruby types to do the comparision

```
describe file('/usr/bin/consul') do
    it { should exist }
    it { should be_file }
    its('mode') { should eq 00765 }
  end
```

**Comment by kplimack** [comment]
@chris-rock that works, but it doesn't jibe with the docs https://github.com/chef/inspec/blob/master/lib/resources/file.rb#L34

**Comment by chris-rock** [comment]
That used the `cmp` matcher is smarter then the `eq` matcher. `eq` is matching for exact match, `cmp` is doing a lot of smart type conversions. By using the cmp matcher you are essentially saying you compare values if if they are of a different type. See https://github.com/chef/inspec/blob/master/test/integration/default/cmp_matcher_spec.rb and https://www.inspec.io/docs/reference/matchers/ 

Sometimes smart comparison it isn't right and therefore you can use the `eq` for those cases.

**Comment by chris-rock** [comment]
@kplimack Is there anything we can improve, otherwise I would like to close this ticket

**Comment by adamleff** [comment]
Since there hasn't been any movement on this issue, I'm going to close it for now. But if we need to re-open it @kplimack, please let us know!
