### ISSUE TITLE
Weird encoding issue when launching inspec shell

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#1967]
### Description

Weird encoding issue when launching `inspec shell`

### InSpec and Platform Version
- inspec 1.25.1
- Ubuntu 16.04.2

**Does not work in:**
 - gnome-terminal 3.18.3
 - tilix 1.6.1
 - terminator 0.98-1

**Works in:**
 - xterm

Any ideas?

![terminator](https://user-images.githubusercontent.com/78700/27539630-85b7b830-5a7d-11e7-8b20-0d4b3dc6c66e.png)
![tilix](https://user-images.githubusercontent.com/78700/27539631-85b8af7e-5a7d-11e7-9ca3-b7d219dab5ec.png)
![gnome-terminal](https://user-images.githubusercontent.com/78700/27539632-85bb1cd2-5a7d-11e7-885b-65babf9579a5.png)
![xterm](https://user-images.githubusercontent.com/78700/27539654-9b19e45a-5a7d-11e7-8011-365e83dda01e.png)

**Comment by arlimus** [comment]
Yesssss, I'm finally not the only one seeing these anymore!! Also just confirmed on Windows 10. Let's fix it :+1:

**Comment by username-is-already-taken2** [comment]
Your not the only one, really glad it's not just me.  I think Christoph thought I was nuts when I happened to mention that I get little acid house faces within my shell ;) 

![image](https://user-images.githubusercontent.com/13700297/30161399-32bcd776-93c8-11e7-96ef-27c53f14e38a.png)

I might see I can track this down, It's defiantly something to do with our fonts. At least I can troubleshoot on a machine where it's repeatable :)

**Comment by adamleff** [comment]
"little acid house faces" is how I will always refer to these now.
