### ISSUE TITLE
Add control `impact` to the json-min output.

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1972]
### Description

I am working on building out some reporting for profile results and it would be **very useful** if the control impact was added to the json-min format output. I am surprised this hasn't come up already given that the impact of a pass or fail would be a core reporting element in my way of thinking.

```
{
  "version": "1.29.0",
  "controls": [
    {
      "id": "V-72841",
      "profile_id": "tests from /Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline/controls/.",
      "status": "passed",
      "impact": "0.7", 
      "code_desc": "Command ..."
    },
    {
      "id": "V-72847",
      "profile_id": "tests from /Users/aaronl/Desktop/hardening/crunchydata/postgresql-baseline/controls/.",
      "status": "passed",
      "impact" "0.5"
      "code_desc": "File /var/lib/pgsql/9.5/data/pg_log should be directory"
    },
   ...
```

**Comment by chris-rock** [comment]
@aaronlippold From my perspective there is no reason to have this as part of `json-min`. We have `json` reporter for that use case. `json-min` has only the minimal runtime information and is optimized to work hand in hand with `inspec json /path/to/profile`

**Comment by adamleff** [comment]
Per #1973, this is not a change we'll be moving forward with in order to keep `json-min` focused on being minimalist as well as keeping to run-time results instead of control metadata. The `json` formatter will provide the information required.  Thanks!
