### ISSUE TITLE
Add ability to redact sensitive output (e.g. command resource)

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#1976]
### Description

The `command` resource can output potentially sensitive information.

### Replication Case
```
describe command('super_secret_cmd --password INTERPOLATED') do
  its('stdout') { should match /.*/ }
end

✔  Command super_secret_cmd --password INTERPOLATED stdout should match /something/
```

### Possible Solutions
  - Add a sensitive option to the `command` resource
  - Add a sensitive attribute to the InSpec DSL (so it can support other resources)

**Comment by adamleff** [comment]
Added in #2017 - closing!
