### ISSUE TITLE
InSpec + Habitat Delightful Integrations

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1981]
Starting an issue to track ideas on how InSpec and Habitat can work better together. In what ways can InSpec take advantage of data provided by Habitat and the supervisor to make writing profiles easier?

Add comments to this thread, or if you have access, add another checklist item to this description.

- [ ] use the port bindings info from hab-sup and be able to check that the ports are listening. Maybe a resource like this:

   ```ruby
   describe hab_local_port_bindings do
     it { should be_listening }
   end
   ```

   Having a `#ports` method for that resource that returns an array of bound ports could be used to feed that into other resources.

**Comment by clintoncwolfe** [comment]
Closing in favor of https://github.com/inspec/inspec-habitat/issues/15
