### ISSUE TITLE
Incompatible with PowerShell 2.0

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#1982]
### Description

Inspec is incompatible with PowerShell 2.0 due to the lack of `ConvertTo-Json` cmdlet.
The behavior of inspec on PowerShell 2.0 is misleading because it returns a null instead of error.

### InSpec and Platform Version

`inspec-1.20.0-1.sles12.x86_64`

### Replication Case

All inspec resources that utilize `ConvertTo-Json` cmdlet

### Possible Solutions

Creating a custom helper script that converts PSObjects into json format which can be used if `$PSVersionTable['PSVersion'].major -eq 2`

**Comment by ghost** [comment]
Related to https://github.com/chef/inspec/issues/660

**Comment by ghost** [comment]
In case there will not be a solution provided for PowerShell 2.0, then at least inspec should warn the end user about the incompatibility, both in the docs and when executing the affected resources on Windows node that only has PowerShell 2.0.

Affected resources (`inspec-1.30`):
* bridge
* groups
* host
* iis_app
* iis_site
* interface
* oneget
* package
* pip
* port
* registry_key
* service
* users
* windows_feature
* windows_task
* wmi

**Comment by Happycoil** [comment]
While the docs state that _"For Windows 2008 and 2008 R2 an updated Powershell (Windows Management Framework 5.0) is required."_ , they could be a lot clearer. Those platforms along with Windows 7 are the only platforms in the supported list whose default PowerShell installation is below 3.0. As far as I can remember the resources only require 3.0, not 5.0.

With PowerShell 6.0 around the corner and all OSes without PowerShell 3.0 and above by default outside of mainstream support I'd say we should just update the docs.

**Comment by chris-rock** [comment]
Thank you for the clarification. Any PR to make the docs more clear is welcome! 

I do not think that we a simple backport of ConvertTo-JSON will be enough. I assume there are a lot more edge-cases. Since Powershell can be easily updated on Windows machines, what is preventing you from doing so?

**Comment by ghost** [comment]
@chris-rock I totally agree that upgrading to PowerShell 3.0 should be the way to go and I understand that the benefit of creating such a backward compatibility is low compared to the effort and resources that are required.
If someone still out there on PowerShell 2.0, they should skip the above listed resources and use the `powershell` resource for a workaround
