### ISSUE TITLE
How to enable sudo in specific resource?

### ISSUE THREAD

**Issue by Wing924** [inspec/inspec#1983]
Hello!

I have a question. How to enable sudo in specific resource?

For example:
Because of the security issue, 
I can't give `ALL =  NOPASSWD:ALL` to inspec executing user.
When I execute `crontab` resource, it needs sudo to get details.
How to enable sudo only for this resource?

**Comment by adamleff** [comment]
Hello, @Wing924! Unfortunately, this is not currently possible nor is it currently planned to be supported. One of the reasons is that it's not possible to escalate privileges in Ruby for a single command which would cause problems when scanning locally vs. remotely.

A possible workaround is to break out the one `crontab` test into its own profile and execute two, but only use sudo with one profile.
