### ISSUE TITLE
Port matcher fails when `net-tools` not installed on Debian Jessie

### ISSUE THREAD

**Issue by jamietanna** [inspec/inspec#1990]
# Description

the port matcher works without needing additional dependencies installed.

# InSpec and Platform Version

1.25.1 and Debian Jessie (Docker: 7b0a06c805e8)

# Replication Case

it returns `false` (not-listening) when indeed it is up. installing `net-tools` manually fixes this issue.

# Possible Solutions

- Add the requirement for `net-tools`
- Document the requirement for `net-tools`
- Use some other method (built into the kernel, perhaps?) that doesn't require these dependencies.

**Comment by aalmenar** [comment]
Specinfra solved this using the ss command. This is available on all debian distros since jessie.

**Comment by aalmenar** [comment]
This pull request #2110 should solve this.

**Comment by adamleff** [comment]
That's true! Please let us know if there are any issues with the new functionality.
