### ISSUE TITLE
nginx_conf to support include by wildcard

### ISSUE THREAD

**Issue by atomic111** [inspec/inspec#1998]
### Description

i started a nginx docker container with docker run -it nginx bash and then i connected with inspec shell -t docker://<containerID> to the container. But i do not get a result with nginx_conf.params

```
atomic111:..tuff/chef_cookbooks ∅> inspec shell -t docker://elastic_heyrovsky
WARN: Unresolved specs during Gem::Specification.reset:
      thor (~> 0.19)
      rspec (~> 3)
      addressable (~> 2.4)
      winrm (~> 2.0)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  debian
    OS family:  debian
    OS release: 9.0

inspec> nginx_conf.params
=> {}
```

the nginx conf looks like:
```
root@c7c90079b007:/# cat /etc/nginx/nginx.conf 

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
```

If i do this on my arch linux host system, the nginx_conf resource is working. But it includes not the other configs, which are include in the config. see the chef-nginx-hardening. There is the 90-hardening.conf included and inspec does not read it.

### InSpec and Platform Version

inspec version is 1.30.0

I use an arch linux host system and startet the nginx docker container from hub.docker.com

### Replication Case

see above

### Possible Solutions

sorry, no plan :(

**Comment by arlimus** [comment]
This request requires the conf to read the wildcard that the user is requesting, e.g.:
```
include /etc/nginx/conf.d/*.conf;
```

**Comment by arlimus** [comment]
@jerryaldrichiii ^^ this might be an easier start into nginx 😁
