### ISSUE TITLE
RuntimeProfile overwritten when executing multiple profiles

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2004]
### Description

RuntimeProfile overwritten when executing multiple profiles, preventing a profile from reliably accessing its profile object via `inspec.profile` in a control file.

As `Inspec::Profile` objects are created, a `Inspec::RuntimeProfile` object is created its object is stored in `@backend.profile`. A single backend instance is created by `Inspec::Runner` and is passed to `Inspec::Profile` when creating the profile instance, so the last profile created wins and its RuntimeProfile instance will be the only one stored in the backend instance.

When controls are then loaded, no matter which profile they are from, the RuntimeProfile instance available via `inspec.profile` will be that of the last profile created. For example, if running `inspec exec` with three profiles, and the first profile attempts to call `inspec.profile.file`, it will fail because the file in question will not exist in the file list of the third profile.

### InSpec and Platform Version

InSpec v1.31.1

### Replication Case

 * Create two profiles, named "one" and "two"
 * Add a file: `one/files/sample.txt`
 * Add a control: `one/controls/example.rb` and call `inspec.profile.file('sample.txt')`
 * Run: `inspec exec one two` -- error recieved: `Cannot find file sample.txt in profile.`
 * Run: `inspec exec one` -- no error received.

For added detail, add a line similar to this at the type of each control file and see that the object IDs are the same and the metadata shown is from the last profile argument passed to `inspec exec`:

```ruby
puts "IN PROFILE one: (#{inspec.profile.object_id}) #{inspec.profile.instance_variable_get(:@src).metadata.inspect}\n\n"
```

### Possible Solutions

 * Create a unique backend instance for each profile instead of a single one for all profiles
 * Add a new class for tracking profile context/state, expose a DSL keyword for accessing it, and store the RuntimeProfile object there instead of on the Inspec::Backend object
 * A better idea I haven't thought of yet...?

I'd personally vote for creating a unique backend object for each target added to a runner. It shouldn't be impactful to performance with the exception of making a connection to the target per profile instead of a shared connection.

**Comment by tpcwang** [comment]
Just to provide another data point... I have a profile 'A' with files, and 'A' depends on another profile 'B'. Controls in 'A' cannot find the files in 'A' with inspec.profile.file because the code ended up looking for files in 'B'.
