### ISSUE TITLE
Inspec::Resources::Deb fails to see a package that is marked as 'held' as installed

### ISSUE THREAD

**Issue by kisoku** [inspec/inspec#2006]
### Description

Package resource fails to see debian packages marked as 'held' as being installed

### InSpec and Platform Version
```
miyamoto [14:18:26] project $ chef --version
Chef Development Kit Version: 1.5.0
chef-client version: 12.21.2
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```
The platform being tested against is Ubuntu 16.04 LTS

### Replication Case

Install a package and mark it as held

```
$ sudo apt-get install hello
$ sudo apt-mark hold hello
```

Run the following inspec test

```
describe package('hello') do
  it { should be_installed }
end
```

### Possible Solutions

Fix Inspec::Resources::Deb to permit `hold ok installed` to be a valid install status as well as `install ok installed`

### Stacktrace

**Comment by chris-rock** [comment]
Thank you @kisoku for reporting this issue. A PR is very welcome to fix this issue.
