### ISSUE TITLE
Matcher : be_in

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#2018]
### Description

It will be very very useful to have a matcher that serves the following use case

describe nginx do
  its('user') { should be_in AUTHORIZED_USER_LIST }
end

describe nginx do
  its('module') { should_not be_in VULNURABLE_MODULE_LIST }
end

describe nginx do
  its('user') { should_not be_in UNAUTHORIZED_USER_LIST }
end

### Possible Solutions
The following code in matches.rb does the job

RSpec::Matchers.define :be_in do |list|
  match do |item|
    list.include?(item)
  end

  failure_message do |item|
    "expected that `#{item}` to be in `#{list}`"
  end
end

**Comment by arlimus** [comment]
Love the direction of this @rx294 !! :)

**Comment by aaronlippold** [comment]
Hi All,

Does anyone have any thoughts on the issue around using the command
resource in the code? I was googling around and for the doing a Dir.glob()
remotely was accomplished using the Net:SSH.command option. Thinking along
those lines, I was wondering if we could use the train connection object in
the inspec runtime in a similar way and then use the train.os and or
train.family to then set the "DIR" command that is sent - i.e. `ls` for
unixies and `dir` for windows. I could be totally off base here.

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by aaronlippold** [comment]
Oops, wrong email chain...

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by rx294** [comment]
Thank you @arlimus, hope you guys can decide on the matcher's name soon...unless it can remain 'be_in' :)
