### ISSUE TITLE
mysql_session is broken

### ISSUE THREAD

**Issue by n-rodriguez** [inspec/inspec#2019]
### Description

I got this error when using `mysql_session` : `Can't connect to MySQL instance for SQL checks.`

### InSpec and Platform Version

inspec 1.31.1

### Replication Case

```
describe mysql_session('root', 'pass').query('SELECT 1') do
  its('stdout') { should eq("1\n") }
  its('stderr') { should eq('') }
end
```

### Possible Solutions

See : https://github.com/chef/inspec/pull/2020

**Comment by n-rodriguez** [comment]
Hi! You forgot to update the CHANGELOG : https://github.com/chef/inspec/blob/master/CHANGELOG.md

**Comment by adamleff** [comment]
@n-rodriguez We're going through some small changes to how we generate version numbers and update the changelog. We'll manually modify it accordingly, but this PR got merged before we started the new process, but also before we would've manually updated the changelog during our release process (which is when we normally updated the changelog - now it will auto-update after each merge to master).

**Comment by n-rodriguez** [comment]
Ok. Thank you!
