### ISSUE TITLE
kitchen verify doesn't find default inspec paths on dependant cookbooks

### ISSUE THREAD

**Issue by budgester** [inspec/inspec#2021]
When I create a CHEF cookbook (my-cookbook) with inspec tests in the default location

test/integration/default

If I include that cookbook in another cookbook and add to the inspec.yml with something like

depends:
  - name: my-cookbook
    git: git@git.mycorp.com:myorg/my-cookbook.git

The verifier does not look at test/integration/default for the inspec.yml or controls, it expects them to be in the root folder.

So either the ability to specify an addtional path attribute or to look at the default folders of a cook book would be really useful.

**Comment by budgester** [comment]
On things I've tried it to create symlinks in the base of the cookbook 

controls -> test/integration/default/controls
inspec.yml -> test/integration/default/inspec.yml

It appears that inpsec doesn't respect the symlink to the controls

`martin.stevens@martinstev-ltm1 ~/src/cookbooks/as-jenkins-server (test) $ inspec check .
WARN: Unresolved specs during Gem::Specification.reset:
      excon (>= 0.38.0)
      thor (~> 0.19)
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Location:    .
Profile:     as-jenkins-server
Controls:    0
Timestamp:   2017-07-18T14:59:56+01:00
Valid:       true

  !  No controls or tests were defined.

Summary:     0 errors, 1 warnings
martin.stevens@martinstev-ltm1 ~/src/cookbooks/as-jenkins-server (test) $ ls -la
total 32
drwxr-xr-x  13 martin.stevens  wheel   442 18 Jul 14:59 .
drwxr-xr-x  68 martin.stevens  wheel  2312 17 Jul 15:27 ..
-rw-r--r--   1 martin.stevens  wheel   228 18 Jul 14:39 .config.yml
drwxr-xr-x  14 martin.stevens  wheel   476 18 Jul 14:39 .git
-rw-r--r--   1 martin.stevens  wheel   401 18 Jul 14:39 .gitignore
drwxr-xr-x   5 martin.stevens  wheel   170 18 Jul 11:34 .kitchen
-rw-r--r--   1 martin.stevens  wheel     0 17 Jul 14:41 README.md
drwxr-xr-x   3 martin.stevens  wheel   102 17 Jul 14:41 attributes
lrwxr-xr-x   1 martin.stevens  wheel    33 18 Jul 14:59 controls -> test/integration/default/controls
lrwxr-xr-x   1 martin.stevens  wheel    35 18 Jul 13:06 inspec.yml -> test/integration/default/inspec.yml
drwxr-xr-x   5 martin.stevens  wheel   170 18 Jul 09:41 recipes
drwxr-xr-x   4 martin.stevens  wheel   136 18 Jul 09:41 spec
drwxr-xr-x   3 martin.stevens  wheel   102 18 Jul 12:51 test
martin.stevens@martinstev-ltm1 ~/src/cookbooks/as-jenkins-server (test) $ cat controls/jenkins_server_spec.rb
control 'jenkins' do
  title 'Jenkins Configuration'
  desc 'Testing file exists'
  describe file('/tmp/test.txt') do
    it { should be_file }
  end
end`

**Comment by budgester** [comment]
If I run from the test/integration/default directory everything is peachy.

`martin.stevens@martinstev-ltm1 ~/src/cookbooks/as-jenkins-server/test/integration/default (test) $ inspec check .
WARN: Unresolved specs during Gem::Specification.reset:
      excon (>= 0.38.0)
      thor (~> 0.19)
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Location:    .
Profile:     as-jenkins-server
Controls:    1
Timestamp:   2017-07-18T15:05:11+01:00
Valid:       true

No errors or warnings`

**Comment by cheeseplus** [comment]
By my reading isn't really a core inspec issue so much as `kitchen-inspec`

**Comment by adamleff** [comment]
Hi @budgester! Dependencies in InSpec must be paths to profiles. You cannot provide a path to a cookbook that contains InSpec profiles, etc. This is not something we plan on changing in the foreseeable future.
