### ISSUE TITLE
packer & inspec for windows

### ISSUE THREAD

**Issue by aidda** [inspec/inspec#2026]
I want to run inspec with a packer for windows OS.
I tried this command but it doesn't work 
`c:\opscode\chef\embedded\bin\ruby c:\opscode\chef\embedded\bin\inspec.bat\ exec c:\Downloads\test.rb`
I need to fix this to day ;)

**Comment by chris-rock** [comment]
if you installed the inspec package, you can just call out to inspec. Otherwise `c:\opscode\chef\embedded\bin\inspec.bat exec c:\Downloads\test.rb` should also work.

**Comment by cheeseplus** [comment]
Closing as answered 👍
