### ISSUE TITLE
The sticky bit function does not seem to be documented in the file resource

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#2032]

**Comment by adamleff** [comment]
@aaronlippold can you please elaborate? Are we talking about the `setuid` permissions bit you can enable on a file/directory? If so, isn't that just part of the file mode (i.e. 1777)?

**Comment by rx294** [comment]
@aaronlippold  is referring to the following method in the file resource 
    def sticky
      (mode & 01000) > 0
    end

When the sticky bit is set on a directory, files in that directory may be unlinked or renamed only by root or their owner. Without the sticky bit, anyone able to write to the directory can delete or rename files. The sticky bit is commonly found on directories, such as /tmp, that are world-writable.

This is useful for example, when testing permissions on virtual server roots.
