### ISSUE TITLE
Unable to detect running processes on Alpine-based Docker containers

### ISSUE THREAD

**Issue by MFAnderson** [inspec/inspec#2034]
### Description

When executing against a running Docker container based on Alpine Linux, `processes` appears unable to detect running processes. I am super new to InSpec so very open to the possibility I'm just doing something wrong.

### InSpec and Platform Version

InSpec 1.31.1 against Alpine 3.6 as Docker container on macOS 10.12.4

### Replication Case

Launch an Alpine container with a process running and attempt to assert the process is running with 
```ruby
describe processes(process_name) do
    it{ should exist }
end
```
Testcase implemented here https://github.com/MFAnderson/inspec-alpine-bug

**Comment by denniswalker** [comment]
Ditto.  I'm guessing the ps command is different in Alpine.  Was able to accomplish something similar using the command resource.

describe command('ps') do
    its('stdout') { should include 'influxd' }
    its('exit_status') { should eq 0 }
  end

**Comment by clintoncwolfe** [comment]
Mhmm.  Looks like Alpine has ps from busybox, which does not support the 'command' field - see 
https://github.com/gliderlabs/docker-alpine/issues/173

inspec is branching on ```inspec.os```, and requesting the command field specifically.

https://github.com/chef/inspec/blob/e6f89664bbe9dd6a1d175612ed9dd0077e22642f/lib/resources/processes.rb#L82

**Comment by clintoncwolfe** [comment]
Hrm, or maybe it isn't the 'command' option... when run manually, that seems to work without error on the current alpine  / busybox.
```
/ # cat /etc/alpine-release
3.6.2
/ # busybox | head -1
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.
/ # ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
PID   USER     TIME   COMMAND
    1 root       0:29 sh -c trap exit 0 SIGTERM; while :; do sleep 1; done
22633 root       0:00 /bin/sh
25593 root       0:00 /bin/sh
25996 root       0:00 sleep 1
25997 root       0:00 ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
```
However, @MFAnderson 's repro script does indeed work - it finds no tail process.  The exact command run by the resource does in fact "work" - but it ignores all formatting instructions.
```
[clinton@Carol inspec-alpine-bug]$ docker exec demo ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/sh -c echo foo >/tmp/foo && tail -f /tmp/foo
    5 root       0:00 tail -f /tmp/foo
  121 root       0:00 ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
```
For comparision, here's the same thing on ubuntu 14.04:
```
[clinton@Carol ~]$ docker exec ubuntu-14 ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
LABEL                             PID %CPU %MEM    VSZ   RSS TT       STAT  STARTED     TIME USER                             COMMAND
-                                   1  0.0  0.0   4460   764 ?        Ss   21:54:46 00:00:00 root                             /bin/sh -c echo foo >/tmp/foo && tail -f /tmp/foo
-                                   5  0.0  0.0   4400   684 ?        S    21:54:47 00:00:00 root                             tail -f /tmp/foo
-                                   6  0.0  0.1  15580  2160 ?        Rs   21:55:47 00:00:00 root                             ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
```

So, since the busybox ps ignores the formatting options, there is no chance that the regex at https://github.com/chef/inspec/blob/e9fecc027d7936558b55ddd2c532cbb2a101126b/lib/resources/processes.rb#L84 will ever match.  

We could special-case Alpine (or detect busybox ps, a bit more generally - though we wouldn't be able to get anything like the fields expected by the other filters on the resource); but keep in mind Alpine isn't officially supported, and there is a workaround using the `command` resource.

**Comment by adamleff** [comment]
@clintoncwolfe is spot-on... `ps` on alpine happily ignores any and all parameters you pass it, and the only it does accept is a `-o` to configure the columns to display. Alpine passes the `os.linux?` check so we try and run the standard linux `ps` command which doesn't work.

To properly support Alpine, we would need to change the ps command to something like this:

```
/ # ps -o pid,vsz,rss,tty,stat,time,ruser,args
PID   VSZ  RSS  TT     STAT TIME   RUSER    COMMAND
    1 1536 1024 136,0  S      0:00 root     /bin/sh
  360 1528    4 136,0  R      0:00 root     ps -o pid,vsz,rss,tty,stat,time,ruser,args
```

... and either add that at the top of the conditional checks (i.e. `if os[:name] == 'alpine'`), or first run `ps --help` and see if it gives us a clue that the `ps` on the box is BusyBox before we continue onto the `os.linux?` check.

I'm going to keep this open, flag it as a bug, and chat with the other maintainers to see if we want to call Alpine a supported OS and how we handle moving forward. Thanks for your patience!
