### ISSUE TITLE
nginx_conf resource does not handle multiple virtual server definitions 

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#2035]
### Description

nginx_conf resource does not parse and expose multiple virtual server definitions in the included conf files. It parses just one and adds it to params

### InSpec and Platform Version

OS: Cent 7

### Replication Case
nginx -T output (shows all included server defs)
![image](https://user-images.githubusercontent.com/17052944/28727091-bed365c4-7391-11e7-84f2-9d0894684a70.png)

nginx_conf.params output inspec shell ( includes only one of the servers)
![image](https://user-images.githubusercontent.com/17052944/28727147-d2e6eb4e-7391-11e7-9ad6-522404f716d3.png)

### Possible Solutions
update nginx_conf parser to collect all the included servers from the conf files

**Comment by arlimus** [comment]
Tested and confirmed. Having multiple server files for some reason doesn't seem to include the all the virtual servers. might be more

**Comment by rx294** [comment]
@arlimus @aaronlippold 

Here is the second parsing issue, please note that the param after the line 
add_header X-XSS-Protection "1; mode=block";
does not parsed properly
nginx -T screenshot
![image](https://user-images.githubusercontent.com/17052944/28927791-73395568-7839-11e7-9ca8-3d66a291c762.png)
inspec shell nginx_conf.params
![image](https://user-images.githubusercontent.com/17052944/28927810-81d580ba-7839-11e7-81d1-cae8249bedc6.png)

**Comment by rx294** [comment]
@arlimus @aaronlippold 
Thank you dominik for the update on nginx_conf. I makes the UI much easier :).
However the above issues are still present after the update.
