### ISSUE TITLE
The link to issues on the CONTRIBUTING.md page does not point to the issues, it points to itself

### ISSUE THREAD

**Issue by pinterl** [inspec/inspec#2039]
### Description

The link to issues on the CONTRIBUTING.md page does not point to the issues, it points to itself: https://github.com/chef/inspec/blob/master/CONTRIBUTING.md#issues

### InSpec and Platform Version

InSpec GitHub repository
"1. Reporting an issue or making a feature request **here.**"

![2017-07-31_14-48-53](https://user-images.githubusercontent.com/12851573/28800073-05fa5d2a-7600-11e7-9ee8-f504056b1d3a.png)

**Comment by adamleff** [comment]
Thanks! We'll get that fixed. Feel free to send up a pull request yourself, or I'll fix it later this week when I return from vacation 🙂
