### ISSUE TITLE
Dependency cookbook inspec in .kitchen.yml

### ISSUE THREAD

**Issue by aidda** [inspec/inspec#2042]
I`m wondering to know, is there anyway to add dependencies inspec`s cookbook to main cookbook?
For instance I have a cookbook to install an application, lets say tomcat, and I have another cookbook to do the OS hardening and the hardening cookbook has an inspec script. I`m running application cookbook with hardening, but I want to use hardening inspec inside the application cookbook.
So, do you have any suggestion?

**Comment by adamleff** [comment]
Hi @aidda, and thanks for submitting your issue!

I'm afraid I'm having a hard time understanding what you're trying to achieve. Would you mind trying to explain it a different way so we can better understand and hopefully point you in the right direction?

Ultimately, if you're trying to execute InSpec profiles as part of a Chef run, I'd strongly recommend checking out [the audit cookbook](https://github.com/chef-cookbooks/audit) as that is the supported way for executing InSpec during a Chef run.

**Comment by larry-herz** [comment]
If I am understanding the question properly, I think that the best way to do what you are suggesting, is to create (or copy) the inspec profile that you are using from your hardening cookbook into its own file, which can then be called in your .kitchen.yml as in the test suite. I have done this with both profiles stored on my compliance server and profiles hosted in git.

Not sure exactly if this is what you are looking for, but it is an easy way to make use of inspec profiles in test kitchen.

**Comment by cheeseplus** [comment]
This definitely seems like a use case for profiles, closing since we haven't heard back in a few weeks and the question has been answered.
