### ISSUE TITLE
Windows file permissions checks don't take group membership into account

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2053]
### Description

With a test like:

```ruby
describe file('c:\test.txt') do
  it { should exist }
  it { should be_readable.by_user('WIN-CIV7VMLVHLD\vagrant') }
end
```

... the test will fail unless the `vagrant` user has been granted explicit read privileges. It does not take group membership into account. This is a different experience than linux, etc. which uses tools that are capable of testing readability/writability with group membership accounted for.

Additionally, the principal must be an exact match (i.e. it must be COMPUTERNAME\username or DOMAINNAME\username) which may be difficult if wanting to test on multiple Windows machines for a non-domain account.

### InSpec and Platform Version

v1.32.1

### Replication Case

 * Create a test file with the above test, changing the computer name as necessary
 * Spin up a Windows machine with a vagrant user created
 * create file `c:\test.txt`
 * Ensure the `BUILTIN\Users` principal has read privileges on the file
 * Ensure the `vagrant` principal does NOT have direct permissions (it will inherit from `Users`)
 * Execute the test and note the failure:

```
    ×  File c:\test.txt should be readable by user WIN-CIV7VMLVHLD\vagrant
     expected File c:\test.txt to be readable by user WIN-CIV7VMLVHLD\vagrant
```

### Possible Solutions

Modify the powershell script used in some way to account for group membership. I am totally the wrong person to do this.

### Stacktrace

Not applicable.

**Comment by anniehedgpeth** [comment]
Not sure if this is related, but I'm looking for the owner of a directory like this:
```
describe directory('C:/foo/bar') do
  its('owner') { should be "#{owner_id}" }
end
```
..and it returns with this...
```
      ×  Directory C:/foo/System owner should equal "ownername"

     expected #<String:70359705587940> => "ownername"
          got #<NilClass:8> => nil
```
...even though `get-acl C:/foo/bar` returns withe the proper owner.

**Comment by adamleff** [comment]
@anniehedgpeth I replied to you in the community slack, but I don't think these two issues are related. Owner can only be a single principal, but read/write/execute permissions can cascade. Owner should always return the string, and provided your InSpec user has access to the top-level directory, it should be able to provide the owner. I'd like to pair with you on this if you need it, or we should get a new issue logged with more details repro steps. Thank you!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
