### ISSUE TITLE
File names don't match resource names

### ISSUE THREAD

**Issue by kagarmoe** [inspec/inspec#2059]
### Description

The file names don't match the resources: 
https://github.com/chef/inspec/blob/master/docs/resources/etc_passwd.md.erb => passwd
https://github.com/chef/inspec/blob/master/docs/resources/etc_shadow.md.erb => shadow

### Possible Solutions

Obvious fix.

**Comment by kagarmoe** [comment]
PR #2060

**Comment by adamleff** [comment]
Fixed in #2060
