### ISSUE TITLE
Provide ability to use non-standard gems in profiles

### ISSUE THREAD

**Issue by anweiss** [inspec/inspec#2062]
### Description

If a profile contains a custom resource with vendored dependencies, executing the profile via `docker run --rm -it -v $PWD:/share chef/inspec exec .` fails with `cannot load such file - <dep>` errors.

### InSpec and Platform Version

chef/inspec:latest -> v1.33.1

### Replication Case

1. Create profile that includes a custom resource containing vendored dependencies
2. Bind-mount the profile in to the InSpec Docker container and run an `inspec exec`

### Possible Solutions

The current workaround is to create a Dockerfile that inherits from `chef/inspec` and that installs the dependencies in to the image. However, this doesn't scale well as one ends up with Docker images for each profile that has custom resources and dependencies.

### Stacktrace

Stacktrace from custom resource (`require 'http'`)

```ruby
docker run --rm -it -v $PWD:/share chef/inspec:latest exec .
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- http (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/dsl_shared.rb:14:in `require'
	from libraries/ucp.rb:1:in `load_with_context'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile_context.rb:135:in `load_library_file'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile_context.rb:124:in `block in load_libraries'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile_context.rb:122:in `each'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile_context.rb:122:in `load_libraries'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/profile.rb:178:in `load_libraries'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/runner.rb:82:in `block in load'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/runner.rb:78:in `each'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/runner.rb:78:in `load'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/runner.rb:99:in `run'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/base_cli.rb:83:in `run_tests'
	from /usr/local/bundle/gems/inspec-1.33.1/lib/inspec/cli.rb:159:in `exec'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/inspec-1.33.1/bin/inspec:12:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:22:in `load'
	from /usr/local/bundle/bin/inspec:22:in `<main>'
```

**Comment by chris-rock** [comment]
@anweiss are you using custom ruby gems in your profile of is that a basic profile?

**Comment by anweiss** [comment]
Yea, using custom gems

**Comment by chris-rock** [comment]
We do not support custom gems in InSpec at this point of time, since the profile is not portable then.

**Comment by chris-rock** [comment]
Also be aware with using gem, since they mostly expect local execution. InSpec is intended to run locally and remotely, therefore we need to wrap those things in InSpec resources. Can you share the uses cases where you need gems for?

**Comment by anweiss** [comment]
I may have misspoke. The gem I'm depending on is this one -> https://github.com/httprb/http

**Comment by anweiss** [comment]
@chris-rock ... here's my use case -> https://github.com/docker/compliance/tree/17.06/validation/inspec/FedRAMP/Moderate/libraries

**Comment by adamleff** [comment]
I've updated the title of this and flagged this as a feature request to possibly support gems within profiles other than those that InSpec itself depends on.

Please note that InSpec can be run in a variety of manners: as a standalone gem, as an Omnibus install, as part of a Test Kitchen run, as part of Chef via the audit cookbook, as part of a Docker container as a layer... the list is almost endless 🙂  Providing the ability to vendor gems in profiles is not a terribly easy task to take on so currently we leave it up to the user to ensure that the Ruby runtime in which InSpec is executed contains the necessary gem.

I'd like to see us first support gem requirements as metadata and have InSpec validate that the gem is available and provide better error messaging if it's not (see #2113). Then we can build on that to provide custom gem support if needed.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
