### ISSUE TITLE
sshd_config mismatches on comments

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#2071]
### Description

So far this has only occured on cent6 during my testing.
the matcher is parsing comments which should be ignored and then returning arrays for config parameters containing the commented out config

#### Example config data in /etc/ssh/sshd_config
```
#AuthorizedKeysCommand none
AuthorizedKeysCommand /usr/libexec/openssh/ssh-ldap-wrapper
```

#### Inspec Results
```
 ×  SSHD Configuration authorizedkeyscommand should cmp == "/usr/libexec/openssh/ssh-ldap-wrapper"

expected: "/usr/libexec/openssh/ssh-ldap-wrapper"
got: ["/usr/libexec/openssh/ssh-ldap-wrapper", "none"]
```

### InSpec and Platform Version

* inspec 1.33.1
* centos 6

### Possible Solutions

I can get around this using the `parse_config_file` resource and providing my own regex for capture groups.

**Comment by adamleff** [comment]
@kplimack I'm afraid I have not been able to reproduce this issue. Here's what I did:

 * started a CentOS 6.8 VM using Vagrant
 * logged in, and as root, hand-edited the `/etc/ssh/sshd_config` file to include the two lines you have above
 * Connected to the VM with InSpec Shell and pulled the AuthorizedKeysCommand parameter:

```
You are currently running on:

    OS platform:  centos
    OS family:  redhat
    OS release: 6.8

inspec> sshd_config.AuthorizedKeysCommand
=> "/usr/libexec/openssh/ssh-ldap-wrapper"
```

The only way I've been able to reproduce this is by having another uncommented `AuthorizedKeysCommand` line somewhere in my config file:

```
AuthorizedKeysCommand none
... more lines here ...
#AuthorizedKeysCommand none
AuthorizedKeysCommand /usr/libexec/openssh/ssh-ldap-wrapper
```

The fact that you are saying it only happens on one particular OS leads me to believe that the sshd_config file on your CentOS 6 image has an uncommented `AuthorizedKeysCommand none` line somewhere in it that you haven't found yet. :)

I'm going to close this issue, but please comment on it or reopen it if you're still running into problems and include some additional data in order for us to reproduce.  Thanks!
