### ISSUE TITLE
describe host(...) output

### ISSUE THREAD

**Issue by gopearls42** [inspec/inspec#2085]
### Description

Is there any way to control output of inspec `host` resource to specify the port and protocol when it outputs results?

For example, I've coded:
```
  describe host("srv", port: 55001, protocol: 'tcp') do
    it { should be_reachable }
  end
```
and the output I get is:
```
Host srv
  should be reachable
```
where, in fact, I'd like to know which port connection is being checked, as in:
```
Host srv/55001/tcp
  should be reachable
```
### InSpec and Platform Version
1.32.1

**Comment by chris-rock** [comment]
@gopearls42 In order to achieve that we need to adapt the `to_s` method to return host, port and protocol in https://github.com/chef/inspec/blob/master/lib/resources/host.rb#L116

**Comment by adamleff** [comment]
@gopearls42 this is a great idea. If you feel like trying your hand at submitting a PR, the spot where @chris-rock mentioned is where the change would need to be. The logic would look something like:

```
 - default output is "Host HOSTNAME"
 - if port number isn't nil, append " port PORTNUMBER proto PROTOCOL"
```
