### ISSUE TITLE
document output and/or expected results

### ISSUE THREAD

**Issue by aw-was-here** [inspec/inspec#210]
All of the `inspec exec` examples provide no hints as to what the expected outcome should be.  For those who don't come from a Ruby universe, this is particularly confusing.  Is it just a pass/fail as a return value? Is it JSON? Is it unformatted text?  Is it rspec?  Is it TAP?  

It seems extremely realistic that someone would want to hook this up to, say, Jenkins.  But with the lack of documentation on the consumer output, many will just take a pass and move on to something else.

**Comment by chris-rock** [comment]
@aw-altiscale That is a great point. Thanks for reporting. Could you share your specific use case? I would be very interested in your expectation of the output.

I see different use cases that we need to cover in-depth:
- cli output
- json output (e.g. for jenkins)

Is there anything else I missed?

**Comment by chris-rock** [comment]
A lot has improved with #671 Please reopen, if InSpec is still not delivering all information you require.

**Comment by ghost** [comment]
Is this going to be added to https://docs.chef.io/ctl_inspec.html ?
