### ISSUE TITLE
Resource Tests appear broken on MacOS

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2102]
### Description

When running the 'resource' set of tests (which are docker-based) under MacOS (and possibly others), it always results in `0 examples, 0 failures` summary.  It may be a reporting error, or the tests may not be run at all.

### InSpec and Platform Version

```
[clinton@Carol inspec]$ git log --oneline -n 1
7a41cec7 Bump version to 1.34.3 by Chef Expeditor
[clinton@Carol inspec]$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
[clinton@Carol inspec]$ ruby --version
ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]
[clinton@Carol inspec]$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

### Replication Case

Using the command from the README (here, I have commented out all images except centos6.6 in test/test.yaml:
```
[clinton@Carol inspec]$ bundle exec rake test:resources config=test/test.yaml
/Users/clinton/.rbenv/versions/2.3.4/bin/ruby test/docker_test.rb test/resource/command_test.rb test/resource/dsl_test.rb test/resource/file_test.rb test/resource/zfs_test.rb
Running tests:
- test/resource/command_test.rb
- test/resource/dsl_test.rb
- test/resource/file_test.rb
- test/resource/zfs_test.rb

--> schedule docker centos:6.6
--> start docker centos:6.6
--> run test on docker 0a0f7040c17f20678fab72148404117a1b7b02e804bbb04a16985e548aa69c1d
--> killrm docker 0a0f7040c17f20678fab72148404117a1b7b02e804bbb04a16985e548aa69c1d


Finished in 1.99 seconds (files took 0.28769 seconds to load)
0 examples, 0 failures
```

I would expect the examples count to be non-zero (and the failures count to be non-zero as appropriate)

### Possible Solutions

It could just be a reporting error.

### Stacktrace

None.

**Comment by adamleff** [comment]
Thank you @clintoncwolfe for raising this issue!

@chef/inspec-maintainers I think we have way more coverage in the `test/integration` stuff than we do in the `test/resources` directory and we can likely just delete `test/resources` to avoid future confusion. What are your thoughts?

**Comment by arlimus** [comment]
@adamleff Great point, at the point where we are at we don't need test/resources anymore! When we initially started, we had a division between `test/integration` and `test/resources` because the latter were said to only ever run on containers while the former would easily expand into VMs and things that required longer to execute. It was an easy way to speed up tests and catch blatant resource failures earlier. I don't think we need it anymore with the current direction of testing 👍

**Comment by adamleff** [comment]
Thanks, @arlimus! 

@clintoncwolfe I'll put up a PR to get rid of these tests and update the README to avoid future confusion. Again, thanks for raising this issue.
