### ISSUE TITLE
be_linked_to resolves symlinks too deep

### ISSUE THREAD

**Issue by zbikmarc** [inspec/inspec#2106]
### Description
`be_linked_to` of `file` resource resolves links "too deep".
It may be similar or same as https://github.com/chef/inspec/issues/974

Image situation, that we have application residing in directory which name contains version, like `/opt/myApp-1.0`. We created non-versioned/latest symlink to this directory `/opt/myApp-1.0 -> /opt/myApp`. And in this directory there are few other directories, one of them is`config`. Now we want this `config` directory (and only this) also be available in `/apps/myApp/config`. And we want to check if `/apps/myApp/config` really points to `/opt/myApp/config`, so non-versioned directory of our application.

```
# tree /opt
/opt/
(... omitted ...)
├── myApp -> /opt/myApp-1.0
└── myApp-1.0
    └── config

# tree /apps
/apps/
└── myApp
    └── config -> /opt/myApp/config

# ls -ld /apps/myApp
drwxr-xr-x. 2 root root 20 Aug 30 09:02 /apps/myApp
# ls -ld /apps/myApp/config
lrwxrwxrwx. 1 root root 17 Aug 30 09:02 /apps/myApp/config -> /opt/myApp/config
```

```
irb(main):001:0> File.symlink?('/apps/myApp/config')
=> true
irb(main):002:0> File.readlink('/apps/myApp/config')
=> "/opt/myApp/config"
irb(main):003:0> File.realpath('/apps/myApp/config')
=> "/opt/myApp-1.0/config"
```

inSpec test file:
```ruby
control "check-symlink-1.0" do
  impact 1.0
  title "Check symlinks"

  describe file('/apps/myApp/config') do
    it { should be_symlink }
    it { should be_linked_to '/opt/myApp/config' }     # this should pass
    its(:link_path) { should eq '/opt/myApp/config' }  # this is only for "showcase" purposes
  end
end
```

Result of inSpec test run:
```
Profile: tests from symlink_bug.rb
Version: (not specified)
Target:  local://

  ×  check-symlink-1.0: Check symlinks (2 failed)
     ✔  File /apps/myApp/config should be symlink
     ×  File /apps/myApp/config should be linked to "/opt/myApp/config"
     expected `File /apps/myApp/config.linked_to?("/opt/myApp/config")` to return true, got false
     ×  File /apps/myApp/config link_path should eq "/opt/myApp/config"

     expected: "/opt/myApp/config"
          got: "/opt/myApp-1.0/config"

     (compared using ==)


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 1 successful, 2 failures, 0 skipped
```
### InSpec and Platform Version

```
# inspec version
1.34.1
```

### Replication Case

Create directory and symlink structure.
```bash
mkdir -p /opt/myApp-1.0/config
ln -s /opt/myApp-1.0 /opt/myApp
mkdir -p /apps/myApp
ln -s /opt/myApp/config /apps/myApp/config
```

Execute provided inspec test file.

### Possible Solutions

`be_symlink_to` should use `File.readlink` instead of `File.realpath` (This is only my assumption that it really uses `realpath`).

**Comment by adamleff** [comment]
Hi @zbikmarc and thanks for this issue!

This is definitely related to #974... the link_path that Train (our underlying connection and execution library) renders is the ultimate destination, not the first link destination. InSpec simply uses that data to complete the tests. You are correct that we use `File.realpath` today, but that's only if InSpec is scanning a local machine... if InSpec is scanning remotely, it actually shells out to `readlink` on Unix-flavored machines to get the link path.

We can't change the behavior of `be_linked_to` without breaking backward compatibility, so we'd need to perhaps add a new matcher, such as `be_first_linked_to` and teach Train how to get that first link (`File.readlink` for local connection, and whatever flags are necessary for Train to just get the first link with `readlink`)

I'll keep this issue open as a feature request. Thanks!

**Comment by adamleff** [comment]
Also @zbikmarc, while I was looking to reproduce your issue, I uncovered a bug in Train having to do with resolving links that I likely wouldn't have stumbled upon if you didn't raise your concern, so thanks for that!

https://github.com/chef/train/pull/194

**Comment by chrisLeeTW** [comment]
Hi @adamleff, does has there any good workaround right now ?

thanks.

**Comment by adamleff** [comment]
@chrisLeeTW I'm afraid I do not know of a workaround as of right now. This is still an open feature request but no one has yet implemented or proposed an implementation.

**Comment by miah** [comment]
We have `shallow_link_path` now which should resolve this issue.

https://www.inspec.io/docs/reference/resources/file/
