### ISSUE TITLE
Proper Changelog

### ISSUE THREAD

**Issue by echohack** [inspec/inspec#211]
Can the maintainers please update the CHANGELOG.md to a good format? It also appears that the CHANGELOG.md is currently out of date -- the most current version on Rubygems is 0.9.1, and the changelog only covers to 0.8.0.

Here is a good way to do a changelog:
## Release 0.1.0 YYYY/MM/DD

Initial release of example_inspec
- We added a feature, here's a short description.
- We added another feature.
- Also we fixed this bug, rejoice!

[#25] A github style reference to github issue 25.
[#431] Another github style reference.

**Comment by chris-rock** [comment]
@echohack Of course. Will do that. Thanks for bringing this up

**Comment by arlimus** [comment]
Solved in #250
