### ISSUE TITLE
inspec can not open profile in directory path with special characters

### ISSUE THREAD

**Issue by einsteinchen** [inspec/inspec#2111]
### Description

InSpec can not resolve a profile in a folder which uses special characters. 

### InSpec and Platform Version

1.31.1 on an Ubuntu 14.04 with latest core

### Replication Case

exemplarily, here is what we are doing in two steps, showing first what we want to do and that it breaks and in the second part that it is in principle working.

we are having a folder with special characters (' ', '{' and '}'), under which a subfolder holds the InSpec profile. When starting from the parentfolder with the special characters, it throws an error, see below. If executed inside the folder with special characters, it works. 
Other linux commands work as well, some python scripts reolve the folder correct as well, we have nothing tested with ruby. 
Our case was verified in the slack #inspec channel.

### Possible Solutions

No idea, looks like parsing the folder must be updated in the following file: /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.34.1/lib/inspec/profile.rb:63:in `for_path’

### Stacktrace

homedirectory/testdrive$ inspec check \{\{\ user\ \}\}/testdrive
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.34.1/lib/inspec/profile.rb:63:in `for_path’: Don’t understand inspec profile in {{ user }}/testdrive, it doesn’t look like a supported profile structure. (RuntimeError)
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.34.1/lib/inspec/profile.rb:72:in `for_fetcher’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.34.1/lib/inspec/profile.rb:78:in `for_target’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.34.1/lib/inspec/cli.rb:68:in `check’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start’
    from /opt/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.34.1/bin/inspec:12:in `<top (required)>'
    from /usr/bin/inspec:23:in `load’
    from /usr/bin/inspec:23:in `<main>'

the profile itself is ok, as far I can see from here:

homedirectory/testdrive/{{ user }}$ inspec check testdrive
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Location:    testdrive
Profile:     testdrive
Controls:    2
Timestamp:   2017-08-30T15:00:07+00:00
Valid:       true
No errors or warnings

**Comment by adamleff** [comment]
InSpec itself totally allows you to init a profile with "special" characters, like curly braces!

```
$ inspec init profile '{{characters}}'
Create new profile at /Users/aleff/profiles/{{characters}}
 * Create directory controls
 * Create file controls/example.rb
 * Create file inspec.yml
 * Create directory libraries
 * Create file README.md
 * Create file libraries/.gitkeep
```

**Comment by adamleff** [comment]
This is semi-related to #1783 where we need to ensure all profile names are sluggable names.

**Comment by adamleff** [comment]
Problem is the `Inspec::RelativeFileProvider` object for this profile is not returning any files, so the SourceReader plugins aren't matching (as they look for the existence of certain files, etc.).

**Comment by adamleff** [comment]
The problem is here: https://github.com/chef/inspec/blob/master/lib/inspec/file_provider.rb#L75

```
[15] pry(#<Inspec::DirProvider>):2> @path
=> "/Users/aleff/profiles/{{characters}}"
[16] pry(#<Inspec::DirProvider>):2> File.join(@path, '**', '*')
=> "/Users/aleff/profiles/{{characters}}/**/*"
[17] pry(#<Inspec::DirProvider>):2> Dir[File.join(@path, '**', '*')]
=> []
```

The `{` and `}` characters are getting interpreted rather than taken literally. If I escape them, it works:

```
[18] pry(#<Inspec::DirProvider>):2> Dir[File.join(Shellwords.shellescape(@path), '**', '*')]
=> ["/Users/aleff/profiles/{{characters}}/controls",
 "/Users/aleff/profiles/{{characters}}/controls/example.rb",
 "/Users/aleff/profiles/{{characters}}/inspec.yml",
 "/Users/aleff/profiles/{{characters}}/libraries",
 "/Users/aleff/profiles/{{characters}}/README.md"]
```

If I make that change in the code:

```
be inspec check ~/profiles/\{\{characters\}\}
Location:    /Users/aleff/profiles/{{characters}}
Profile:     characters
Controls:    2
Timestamp:   2017-09-05T16:06:35-04:00
Valid:       true

No errors or warnings
```

I don't know what side effects this might have, but that seems like a plausible solution to account for non-standard character directory names.
