### ISSUE TITLE
method link_target for file resource does not exist

### ISSUE THREAD

**Issue by poblahblahblah** [inspec/inspec#2114]
### Description

The `link_target` method for the file resource does not exist, even though it's in the documentation. Looking at the code base, I don't see any reference to this method beyond the documentation.

### InSpec and Platform Version

inspec version: 1.35.1
platforms: Centos 6x, Centos 7.x, Ubuntu 14.04, Ubuntu 16.04

### Replication Case

```
describe file('/etc/localtime') do
  it { should exist }
  it { should be_symlink }
  its('link_target') { should eq '/usr/share/zoneinfo/UTC' }
end
```

### Possible Solutions

If you have already ideas how to solve the issue, add them here. Here's a github search: https://github.com/chef/inspec/search?utf8=%E2%9C%93&q=link_target&type=

I can get a PR to remove this from the docs if desired.

### Stacktrace

```
  File /etc/localtime
     ✔  should exist
     ✔  should be symlink
     ∅  undefined method `link_target' for File /etc/localtime:#<Class:0x0055f3461d79e8>
     Did you mean?  link_path
```

**Comment by adamleff** [comment]
This should totally be `link_path` and not `link_target`. I'll fix the documentation.

Thanks, @poblahblahblah!
