### ISSUE TITLE
Not Red for 0 failures

### ISSUE THREAD

**Issue by anniehedgpeth** [inspec/inspec#2129]
### Description

Currently, in the below example, `88 successful` would be green, `0 failures` would be red, and `0 skipped` would be grey. 

```
Test Summary: 88 successful, 0 failures, 0 skipped
```
I would love it if `0 failures` were a non-red color if there were NO failures but still red for 1 or more failures. :)

### InSpec and Platform Version

InSpec 1.36.1
MacOS 10.12.6

**Comment by adamleff** [comment]
@anniehedgpeth I just made this change in a recent version! We had a long-standing issue #1752 which I addressed in #2094 which was released in v1.34.1. See the below screenshot:

![screen shot 2017-09-08 at 14 40 22](https://user-images.githubusercontent.com/3221128/30226350-ae4b5828-94a3-11e7-9b7c-34f37f61dd4d.png)

Can you share a screenshot of your `inspec version` output and your `inspec exec` output like I have above? Something isn't right here...

**Comment by anniehedgpeth** [comment]
Oh awesome! It looks like I just accidentally lied about my version; I'm actually on 1.31.1 - don't know how that happened! I'll update and close the issue. :-P Thanks, Adam!
