### ISSUE TITLE
Add error handling for unsupported PowerShell versions

### ISSUE THREAD

**Issue by giorgian** [inspec/inspec#2136]
### Description

When a spec that uses the helper `registry_key` is executed on a Windows machine that has PowerShell < 3.0, an error is produced ("convertFrom-Json is not recognized as the name of a cmdlet") and ignored, and the assertion wrongly fails.

It would instead be better to either support PowerShell 2.0 or to fail early, stating that PowerShell >= 3.0 is required.

### InSpec and Platform Version
Inspec 1.36.1 on all Windows servers with PowerShell 2.0

### Replication Case

On a Windows machine with PowerShell < 3.0, just run:

    registry_key(SOME_ACTUALLY_EXISTING_KEY).exists?

It will say false instead of true (or, instead of: sorry, PowerShell 2.0 is not supported)

**Comment by jerryaldrichiii** [comment]
Since PowerShell < 3.0 is not supported could we change the title of the issue to:

```
Add error handling for unsupported PowerShell versions
```

**Comment by adamleff** [comment]
I'm updating the PR title now to make it clearer. However, this is an issue across the board and I wouldn't want to copy-pasta a bunch of powershell version checks across any resource that requires powershell.

We have an open RFC regarding platform support (#1661) and as part of that RFC implementation (and as part of #1205, providing the ability to surface exception messages to the user), we should address this more globally.

I'm keeping this open as a feature request.

**Comment by jerryaldrichiii** [comment]
Going ahead and closing this, this is becoming less and less of an issue as time goes on.
