### ISSUE TITLE
Suggestion: implement file_audit resource

### ISSUE THREAD

**Issue by ViolentOr** [inspec/inspec#2139]
### Description

Sometimes (for example, pci dss compliance) it's necessary to set up file audit in windows, and, as a result, we should check that it is set correctly.
It's like this (on windows) - right click on file/directory -> security -> audit

### InSpec and Platform Version

Windows

### Possible Solutions

As a quick win i made custom resourse.
```
class FileAudit < Inspec.resource(1)
  name 'file_audit'
  desc 'Use the InSpec resource to determine Windows File Audit params'


  def initialize(path)
    @path = path
    if !inspec.file(@path).exist?
      skip_resource "Can't find file \"#{@path}\""
      return @params = {}
    end
    @rules_array = inspec.command("(get-acl #{@path} -include * -audit).getauditrules($true,$true, [System.Security.Principal.SecurityIdentifier] )").stdout.split("\r\n\r\n")
  end

  def amount
    puts "start amount\n"
    puts @rules_array.length
    return 0 if @rules_array.length == 0
    return @rules_array.length - 1
  end

  def to_s
    return '' if @rules_array.nil?
    return '' if @rules_array.empty?
    st = "---\n"
    options = {assignment_regex: /^\s*([^:]+?)\s*:\s*(.+?)\s*$/}
    @rules_array.each do |rule_str|
      rule = inspec.parse_config(rule_str, options)
      next if rule.params.empty?
      st += rule.params['IdentityReference'].nil? ? '' : rule.params['IdentityReference']
      st += ":\n"
      st += "  FileSystemRights: "
      st += rule.params['FileSystemRights'].nil? ? '' : rule.params['FileSystemRights']
      st += "\n"
      st += "  AuditFlags: "
      st += rule.params['AuditFlags'].nil? ? '' : rule.params['AuditFlags']
      st += "\n"
      #For registry TODO: Redo this crap
      st += "  RegistryRights: "
      st += rule.params['RegistryRights'].nil? ? '' : rule.params['RegistryRights']
      st += "\n"
      st += "  InheritanceFlags: "
      st += rule.params['InheritanceFlags'].nil? ? '' : rule.params['InheritanceFlags']
      st += "\n"
      st += "  PropagationFlags: "
      st += rule.params['PropagationFlags'].nil? ? '' : rule.params['PropagationFlags']
      st += "\n"
    end
    return st
  end
end
```
it can be used like this
```
  describe yaml({content: file_audit('C:\Windows\System32\winevt\Logs\Security.evtx').to_s}) do
    its(%w(S-1-1-0 FileSystemRights))  { should cmp 'Write, Delete, ChangePermissions, TakeOwnership' }
  end
  describe file_audit('C:\Windows\System32\winevt\Logs\Security.evtx') do
    its('amount') { should cmp 1 }
  end
```
I know, that it is poorly written (in my defence -- ruby is not my mother language =) ), so i won't submit this as pull request. Feel free to reuse it.

**Comment by adamleff** [comment]
Thanks for your suggestion, @ViolentOr! I'm glad to see that you used a custom resource to meet your immediate needs. That is definitely the right path when a resource you want does not yet exist in core InSpec.

I'll keep your issue opened as a feature request.

**Comment by james-stocks** [comment]
I've been working on something similar.
It's not finished or in real use yet; but the work so far is at https://github.com/james-stocks/inspec_effectiverights/blob/master/libraries/FilePermissions.rb

**Comment by kekaichinose** [comment]
This issue has aged, but this might be a prime candidate to be taken on by the Content team. @james-stocks, I'm going to close the issue on this side. Would it make sense to open a new issue, with a more current use case, for the Content team to help with? If I'm missing something here, please feel free to reopen. Thanks!
