### ISSUE TITLE
`cmp` fails when items in the arrays are out of order

### ISSUE THREAD

**Issue by Richard-The** [inspec/inspec#2155]
### Description

Comparing two arrays fail in some cases if the items are out of order. For instance,
```
∅  cookbook::recipe: service is working properly (1 failed)
   ✔  Port 1234 should be listening
   ×  Port 1234 protocols should cmp == ["tcp", "udp"]

   expected: ["tcp", "udp"]
        got: ["udp", "tcp"]

   (compared using `cmp` matcher)
```

### InSpec and Platform Version

InSpec version: 1.33.12
Operating System: CentOS Linux release 7.2.1511 (Core)

### Possible Solutions

One solution that I can think of is to sort the arrays before comparing.

**Comment by adamleff** [comment]
@richard2191 thanks for submitting this issue!

This is working as intended. In many cases, array order matters and sorting the array prior to comparing it would yield incorrect results for other users and tests.

I can think of two options to solve your issue. First, you could break it out into two tests:

```
its('protocols') { should include 'tcp' }
its('protocols') { should include 'udp' }
```

Or, you can presort the value before comparing it, like this:

```
inspec> describe port(6263) do
inspec>   its('protocols.sort') { should cmp %w(tcp tcp6) }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Port 6263
     ✔  protocols.sort should cmp == ["tcp", "tcp6"]
```

Hope that helps!
~Adam
