### ISSUE TITLE
Feature request: override inspec to run a single control/describe section

### ISSUE THREAD

**Issue by dialex** [inspec/inspec#2171]
### Description

I've used [mocha](https://mochajs.org/) on my previous project and with that framework I can append `.only` to a single test or test file and it will run just that. I could really use a similar feature on inspec.

Context: I did a small ruby hack to implement a guard and run inspec every time a test file is changed (since there's no `--watch` flag). It works great but I still have to wait for ALL unit tests to run, when I'm only interested in the result of a couple of them. This waiting makes me inefficient.

### Possible Solutions

I start my tests with a rake task, something like `rake unit`. My current workaround is to edit the rake task temporarily to have `inspec exec path/to/the/file/under/test` and run just the test file that I want.

**Comment by jerryaldrichiii** [comment]
To make sure I understand, you want to be able to add some text to tests in a file that will allow InSpec to only execute those tests. (e.g. `describe.only`) and you do not want to modify the `inspec exec` command (e.g. not using the `--controls` flag or modifying the path).

Kinda like: https://github.com/chef/inspec#or-tests-testing-for-a-or-b but not for `A || B` logic but the whole profile.

Right?

**Comment by aaronlippold** [comment]
It seems to me you want to be able to have Rake pass inSpec the --control option

**Comment by dialex** [comment]
Right, a `describe.only` usage pattern.

The workflow most of my team uses is having a window with the unit test and another with the console, constantly running the unit tests with every change -- TDD fashion. We don't want to change the Rakefile and then accidentally commit it. And that `A||B` logic doesn't solve our problem.

We only have two profiles, one for unit and another for acceptance. I don't see how profiles could help in this situation, probably because we are not actively using them. When we want to run the tests, we just do `inspec exec folder_name` and the tests get executed. It works without the `inspec.yml` too, it's just metadata after all, so that's why I don't see any added value on using the profile. I'm sure they do a lot of advanced and useful things, we either don't know or don't need it (yet).

**Comment by aavetis** [comment]
+1

**Comment by clintoncwolfe** [comment]
This can be accomplished using the `--controls` CLI option, which accepts a list or regex.
