### ISSUE TITLE
InSpec `check` and `only_if`

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#2175]
We currently execute all code in `only_if` statements during the `inspec check` operation. I have a feeling there may be little value in doing so, as the statement doesn't provide any useful input to the check command. It will execute the code in the block but it may also lead to executing code that doesn't fully compute (e.g. `nil` values because it doesn't talk to a target system). I wonder if we should ignore this block during the execution of `inspec check` to potentially prevent errors with dynamic computations.

On the upside, using `inspec check` in this case also catches potential errors when values aren't computed with the right data dynamically and may lead to better code in the long run. As a downside, users have to actually understand what is going on that is causing the failure and how to solve it, otherwise it only gets frustrating. A failure with dynamic computations at the moment (due to the nature of not catching raised failures) will lead `inspec check` to completely fail. It may be that a combination of catching failures and allowing the user to ignore the error may lead to relief as well.

**Comment by adamleff** [comment]
Since you can't pass a `--target` to an `inspec check`, and many uses of `only_if` are around os parameters, etc., I'm in full support of not executing those blocks during a check. This actually feels like a bug to me. :)
