### ISSUE TITLE
Attribute behavior during inspec check

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#2176]
Attributes may lead to complex failures during `inspec check` and all related actions.
See 

Possible solutions:
1. One universal object that returns itself on all interactions: https://github.com/chef-cookbooks/audit/issues/282#issuecomment-331418765
2. Type-specific zero-value objects (e.g. `0`, `""`, `[]`, `{}` <= with a way to return itself on every value retrieval). Use option 1 if no type is specified.

Preferences?

**Comment by adamleff** [comment]
Even though it feels ugly, I find myself gravitating toward option 1 because of the deep hash access potential (i.e. a[:b][:c][:d]) and a desire to avoid the dreaded "undefined method [] on NilClass" error all Ruby users know and "love."

**Comment by adamleff** [comment]
Option 2 feels good too, honestly. But so little of InSpec is type-specific (and we actually go out of our way to provide the "cmp" matcher to avoid it), so I'm curious about the learning hurdles our users may face with that.

**Comment by arlimus** [comment]
@adamleff The default case for non-typed attributes would be option 1, which i really like 😁 
I though of only resorting to option 2 if people specify types. What do you think?

**Comment by adamleff** [comment]
Yeah... I mean, I'm never going to argue that type specificity is a bad thing, except from a non-technologist's point of view. As long as it's an opt-in behavior and we still protect the user experience from NilClass errors, I'm all for it!

**Comment by arlimus** [comment]
Awesome, fully agreed (it is opt-in)!! Let's do it then 👍

**Comment by arlimus** [comment]
This implements option 1 ^^.
Option 2 doesn't make sense yet as the type checking hasn't been implemented yet. So let's leave it out and wrap until we revisit the rfc for attributes.

**Comment by arlimus** [comment]
Good enough for option 1 now. Option 2 when types are here.
