### ISSUE TITLE
inspec 1.38.8 breaks chef 12.17.44

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#2183]
### Description

the new `train` gem breaks dependencies of `net-ssh`.
```
 ERROR: Unable to activate train-0.27.0, because net-ssh-3.2.0 conflicts with net-ssh (~> 4.2)
```

### InSpec and Platform Version

1.38.8

### Possible Solutions

downgrade to 1.38.7

### stacktrace
```
>>>> Caused by Gem::ConflictError: Unable to activate train-0.27.0, because net-ssh-3.2.0 conflicts with net-ssh (~> 4.2)
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
/opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:214:in `try_activate'
```

**Comment by adamleff** [comment]
@kplimack thanks for raising this issue. We'll investigate to see if there's something we can do. This won't be an issue in later version of Chef 13 because uses later versions of net-ssh. I'm not sure if we can safely backport that to Chef 12, or make InSpec a little more lenient. A change between net-ssh 4.1 and 4.2 required us to do some evasive maneuvers.

I'll update this issue once we have some additional info to share.

**Comment by kplimack** [comment]
@adamleff thanks for looking into this.  unfortunately my cheffery is no where near ready for chef13, so i'm stuck supporting an older version of 12 for now.

**Comment by adamleff** [comment]
@kplimack no worries. I just put up this PR to Train which will support older net-ssh versions while still fixing the deprecation warning issue in net-ssh >= 4.2.0:

https://github.com/chef/train/pull/199

Once we get that approved and merged, I'll cut a new release of Train and InSpec.

**Comment by adamleff** [comment]
@kplimack PR https://github.com/chef/inspec/pull/2185 opened to address this by bumping Train to 0.28. I'll have a new version of InSpec released in about 10-15 minutes.
