### ISSUE TITLE
How to compare a commands String output with be-Matcher?

### ISSUE THREAD

**Issue by mgrobelin** [inspec/inspec#2187]
Hi,
i played around with InSpec and had some great moments while experimenting. Now I am stuck on a use case, which might be more likely a usage issue from my side, than a bug.

### Description

I want to check a systems amount of RAM, e.g. to be greater than 128 GB.

Using the [command](https://www.inspec.io/docs/reference/resources/command/) resource with the available ```be``` does not work, as it treats the commands output as String (inlcuding the newline).

```
control 'sys-07' do
  impact 1.0
  title 'Check amount of memory'
  desc 'Check that enough memory is available.'
  describe command("awk '/MemTotal/ {print $2}' /proc/meminfo") do
    its('stdout') { should be >= 128000000 }
    its('stderr') { should eq '' }
    its('exit_status') { should eq 0 }
  end
end
```

This test fails with the following output:

```
  ×  sys-07: Check amount of memory (1 failed)
     ×  Command awk '/MemTotal/ {print $2}' /proc/meminfo stdout should be >= 128000000
     expected: >= 128000000
          got:    "152507680\n"
```

The system has 148 GB RAM plus a bit of swap.

I expected this control to type-cast the ```command``` result properly (```"152507680\n".to_i```) and therefore pass successfully.

Using the```match``` Matcher to generate RegExp for numeric ranges might be possible, but it seems more natural to use the ```be``` Matcher to solve this task. Right?

### InSpec and Platform Version

InSpec 1.37.6, ruby 2.3.3p222

### Possible Solutions

I tried to use ```.to_i``` here and there, but it raised undefined method exceptions, e.g. like this:

```
its('stdout').to_i { should be >= 128000000 }
```

**Comment by adamleff** [comment]
Hi, @mgrobelin! Great to hear that you've had success with InSpec so far - thanks for giving it a try!

This is a pretty easy problem to solve... first, we need to strip that newline, and then we can use a slightly different matcher. Here's how I would write that test:

```ruby
its('stdout.strip') { should cmp >= 128000000 }
```

The two small changes I made were:

 * Add `.strip` to the item you're trying to match. InSpec will join these methods together for you - so it will grab the `stdout` from the command output, and then call `strip` on it to remove any whitespace and newlines from the beginning and end.
 * Change to use the `cmp` matcher. This acts just like the `be` matcher, but it handles type differences for you... `stdout` is going to return a string, so trying to do `>=` comparison won't work well.. but the `cmp` matcher will see that it looks like a number and then do the comparison after converting it for you.

You could've written it like this:

```ruby
its('stdout.strip.to_i') { should be >= 12345 }
```

... and that would work fine too... but I think the `cmp` matcher is the better fit.

I hope this helps! If not, please reply and I'll reopen the issue and continue to help. Thanks again for using InSpec!

**Comment by mgrobelin** [comment]
@adamleff Thank you for very clear explaination - it's behaving as suggested. 

Now I encounter a other (usage) issue with the ```user``` resource, obviously facing an encoding issue. 

The primary group for a user ```myuser``` shall be ```domänen-user``` (mind the german ä-Umlaut). 

My three approaches failed as follows:

1)
```
describe user('myuser') do
    its('group') { should cmp == 'domänen-benutzer' }
end

=>
     ×  User myuser group should cmp == "domänen-benutzer"
     incompatible character encodings: UTF-8 and ASCII-8BIT
```

2)
```
describe user('myuser') do
    its('group') { should cmp == 'dom\xC3\xA4nen-benutzer' }
end

=>

/usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:658:in `gsub': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:658:in `format_line'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:666:in `print_line'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:582:in `print_result'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:456:in `block in print_last_control_with_examples'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:456:in `each'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:456:in `print_last_control_with_examples'
	from /usr/local/rvm/gems/ruby-2.3.3/gems/inspec-1.37.6/lib/inspec/rspec_json_formatter.rb:408:in `close'
[...]
```

3)

```
describe user('myuser') do
    its('group.encode("utf-8")') { should match /domänen-benutzer/u }
end
=>
     ×  User myuser group.encode("utf-8") 
     undefined method `encode("utf-8")' for "dom\xC3\xA4nen-benutzer":String
```

Do you have a suggestion?

**Comment by doertedev** [comment]
I think you're facing the typical encoding problem - when you don't specify how a string is encoded before the transformation you most likely will hit a wall. I would try the encode method with two parameters instead: windows-something to utf-8.

**Comment by mgrobelin** [comment]
btw back then I solved it like so

```
  describe user('myuser') do
    it 'has primary group domänen-benutzer' do
      expect(subject.group.force_encoding(Encoding::UTF_8)).to eq('domänen-benutzer')
    end
  end
```

**Comment by paulcalabro** [comment]
> You could've written it like this:
> 
> its('stdout.strip.to_i') { should be >= 12345 }


@adamleff Out of curiosity,  how would you typecast the string below to be an integer:

```
  its(['some', 'string']) do
    should be > 0
  end
```

This is is examining some JSON field.
I tried `.to_i` and it didn't seem to work.
