### ISSUE TITLE
Inspec JSON output contains non-JSON information

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#2198]
### Description

A run of `inspec exec --format=json <profile>` > output.json results in an output file that contains non-JSON information.

The `json-min` output format is also affected.

Example Output:

```shell
#!/bin/sh
python -c 'import sys; sys.path.insert(0, "/usr/share/yum-cli"); import cli; list = cli.YumBaseCli().returnPkgLists(["updates"]);res = ["{\"name\":\""+x.name+"\", \"version\":\""+x.version+"-"+x.release+"\",\"arch\":\""+x.arch+"\",\"repository\":\""+x.repo.id+"\"}" for x in list.updates]; print "{\"available\":["+",".join(res)+"]}"'
#!/bin/sh
python -c 'import sys; sys.path.insert(0, "/usr/share/yum-cli"); import cli; list = cli.YumBaseCli().returnPkgLists(["updates"]);res = ["{\"name\":\""+x.name+"\", \"version\":\""+x.version+"-"+x.release+"\",\"arch\":\""+x.arch+"\",\"repository\":\""+x.repo.id+"\"}" for x in list.updates]; print "{\"available\":["+",".join(res)+"]}"'
{"version":"1.40.0","controls":[{"status":"passed","code_desc":"/etc/group gids shoul (...)}
```

### InSpec and Platform Version

InSpec 1.40.0 (from RPM)
CentOS 7.3

**Comment by aaronlippold** [comment]
That comes from the linux-patches resource that is being run in the rhel7
base profile. @jburns12 has resolved that issue and it is part of the
push/fix of the profile.

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by jburns12** [comment]
As a heads up...this isn't something that has been resolved quite yet. It is related to linux-patches resource in our Rhel7 profile, however.

**Comment by adamleff** [comment]
Since this doesn't appear to be an issue with InSpec itself but rather a profile that is outputting additional data to stdout, I'm going to close this issue.
