### ISSUE TITLE
How to perform a setup/init before running the real test

### ISSUE THREAD

**Issue by dialex** [inspec/inspec#2200]
### Description

My specific use case is I want to login to Azure, then execute a command, and finally assert the result on stdout.
- The login is the **test setup** or init.
- The azure command is the **test action** and uses your `bash` resource.
- The assertion is the real check.

So far I have to include the test setup with the test command and run both in a single bash command (or inspec resource). _Otherwise, it seems the test setup and command run on separate instances or sessions of bash, because when the test command executes the test setup is not there._

This messes up the test output, since instead of display just the test command, you also see the whole test setup before it. Each test output spans multiple lines and debug is cumbersome.

Am I doing something wrong or is this a missing feature?

### InSpec and Platform Version

`inspec 1.40.0`
`Ubuntu 16.04.3 LTS` (docker image)

### Example

This should work, but doesn't.

```ruby
control "Resource Group" do
  title "is provisioned"
  impact 1.0
  tag 'deployment'

  login_azure =
    'source ../scripts/common/azure.sh; '\
    'az_login "$CLIENTID" "$CLIENTSECRET" "$TENANTID"; '

  query =
    'az group list -o table'

  describe bash('echo 'connecting to azure...') do
    before do
      cmd = "#{login_azure}"
    end
  end

  describe bash(query) do
    its('stdout') { should match 'expected_regex' }
  end

  describe bash('az resource list -o table') do
    its('stdout') { should match 'another_regex' }
  end
end
```

### Possible Solutions

This is the workaround.

```ruby
  describe bash(login_azure + query) do
    its('stdout') { should match 'expected_regex' }
  end

  describe bash(login_azure + 'az resource list -o table') do
    its('stdout') { should match 'another_regex' }
  end
```

And then the test output is full of boilerplate:

```
✔  Function log_function (1.0): logs the bash function's name and the parameters received
   ✔  Bash command set -euo pipefail; source ../scripts/common/logger.sh; log_function name p1 p2 p3 stdout should match "FUNCTION: name"
   ✔  Bash command set -euo pipefail; source ../scripts/common/logger.sh; log_function name p1 p2 p3 stdout should match "PARAMS: p1 p2 p3"
   ✔  Bash command set -euo pipefail; source ../scripts/common/logger.sh; log_function name p1 p2 p3 exit_status should eq 0
   ✔  Bash command set -euo pipefail; source ../scripts/common/logger.sh; log_function name stdout should match "FUNCTION: name"
   ✔  Bash command set -euo pipefail; source ../scripts/common/logger.sh; log_function name stdout should match "PARAMS:  "
   ✔  Bash command set -euo pipefail; source ../scripts/common/logger.sh; log_function name exit_status should eq 0
```

As it should look like:

```
✔  Function log_function (1.0): logs the bash function's name and the parameters received
   ✔  Bash command 'log_function name p1 p2 p3' stdout should match "FUNCTION: name"
   ✔  Bash command 'log_function name p1 p2 p3' stdout should match "PARAMS: p1 p2 p3"
   ✔  Bash command 'log_function name p1 p2 p3' exit_status should eq 0
   ✔  Bash command 'log_function name' stdout should match "FUNCTION: name"
   ✔  Bash command 'log_function name' stdout should match "PARAMS:  "
   ✔  Bash command 'log_function name' exit_status should eq 0
```

**Comment by dialex** [comment]
Hello?

**Comment by ColinHebert** [comment]
Any info regarding this? In serverspec there is the `:pre_command` system that allows to execute a command before running the actual test (See http://serverspec.org/advanced_tips.html). What's the correct approach here?

**Comment by dave-pollock** [comment]
I'm also interested in the correct approach for test setup

**Comment by clintoncwolfe** [comment]
There is something that could be said here about avoiding modifying the test subject - inspec is intended to test and only test, no changes if possible.  So, it's unlikely setup / teardown support would ever be directly supported.

That said, if you want to run a command and not have it appear as a test, simply use the `command` resource outside of a `control` or `describe` block:

```
# In controls/lets-change-things.rb

# Executes in a subprocess on the remote target;
# no env changes will persist, but FS changes will
command('do-something') 

control 'And now we test' do
  describe command('test-something') do
    its('stdout') { should match /huzzah/ }
  end
end

command('teardown-something')
```

So, that's one way of doing it.

Specifically for @dialex 's question about Azure, however: InSpec has had support for auditing some portions of Azure since v2 - see https://github.com/inspec/inspec-azure - it might serve your needs.
