### ISSUE TITLE
os resource does not work as expected

### ISSUE THREAD

**Issue by JazJas** [inspec/inspec#2215]
### Description

when using the 'os' resource in inspec shell, it appears the os resource does not work as expected. For instance:

inspec> os[:family]
=> "debian"
inspec> os[:debian]
=> nil
inspec> os[:family] == 'debian'
=> true
inspec> os[:windows]
=> nil

os[:debian] should NOT return nil.

### InSpec and Platform Version
`#inspec version`
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.40.0

`#uname -a`
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

### Replication Case

`#inspec shell`
inspec> os[:family]
=> "debian"
inspec> os[:family] == 'debian'
=> true
inspec> os[:debian]
=> nil

### Possible Solutions

NA

### Stacktrace

NA

**Comment by JazJas** [comment]
According to https://www.inspec.io/docs/reference/resources/os/

`if os[:debian]` 
`  describe port(69) do`
`    its('processes') { should include 'in.tftpd' }`
`  end`
`elsif os[:redhat]`
`  describe port(69) do`
`    its('processes') { should include 'xinetd' }`
`  end`
`end`


os[:debian] should be of a correct syntax.

**Comment by adamleff** [comment]
This is a documentation error. The only "parameters" available for the `os` resource are:

```
inspec> os.params
=> {:name=>"mac_os_x", :family=>"darwin", :release=>"10.12.6", :arch=>"x86_64"}
```

... so `os[:debian]` won't work... however, `os.debian?` will.

We need to fix the doc bug in the last example on that page.

**Comment by adamleff** [comment]
PR #2218 submitted to fix the docs online.
