### ISSUE TITLE
Checking processes on a port resource fails in newer versions of inspec

### ISSUE THREAD

**Issue by thomascate** [inspec/inspec#2232]
### Description

Running a port resource like so, works in inspec 1.30.0 and up to 1.36.1 in some tests. 

describe port(80) do
  its('processes') { should include 'nginx' }
end

However in current versions of inspec you get this output.
  Port 80
     ∅  processes should include "nginx:"
     expected ["nginx\",1856,6),(\"nginx\",1855,6),(\"nginx\",1854,6),(\"nginx\",1853,6),(\"nginx"] to include "nginx:"

I suspect this was caused when netstat was switched with ss.

### InSpec and Platform Version

In testing one person saw the behavior as far back as 1.30.0, I wasn't able to reproduce it until I got to 1.36.1 and up.

### Replication Case

Install a service that listens on any port and check to make sure the right process is there with a simple port, processes check.
We have seen this happen on centos 7.3, ubuntu 12.04 and centos 6.7

### Stacktrace

tcate-workstation:inspec tcate$ cat /tmp/test.rb
describe port(80) do
  its('processes') { should include 'nginx:' }
end

tcate-workstation:inspec tcate$ inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 5.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
      thor (~> 0.19)
      rainbow (~> 2)
      diff-lcs (< 2.0, >= 1.2.0)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.36.1

Your version of InSpec is out of date! The latest version is 1.41.0.
tcate-workstation:inspec tcate$ inspec exec /tmp/test.rb -t ssh://vagrant@10.1.1.46 --sudo --password=vagrant
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 5.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      winrm-fs (~> 1.0)
      docker-api (~> 1.26)
      thor (~> 0.19)
      rainbow (~> 2)
      diff-lcs (< 2.0, >= 1.2.0)
      addressable (~> 2.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Profile: tests from /tmp/test.rb
Version: (not specified)
Target:  ssh://vagrant@10.1.1.46:22

  Port 80
     ∅  processes should include "nginx:"
     expected ["nginx\",1856,6),(\"nginx\",1855,6),(\"nginx\",1854,6),(\"nginx\",1853,6),(\"nginx"] to include "nginx:"

Test Summary: 0 successful, 1 failure, 0 skipped

**Comment by narkaTee** [comment]
I'm also experiencing this problem.

I was able to track down the cause of the problem:
This regexp [`/users:\(\(\"(\S+)\"/`](https://github.com/chef/inspec/blob/ca19ef55708c9e42610d6f665507d40173688da0/lib/resources/port.rb#L551) does not work correctly when multiple processes share the same fd (which is the case with nginx).

`ss -tulpen` outputs this line for nginx:
```
tcp    LISTEN     0      128                                                                  *:80                                                                  *:*      users:(("nginx",pid=583,fd=8),("nginx",pid=582,fd=8),("nginx",pid=580,fd=8),("nginx",pid=579,fd=8)) ino:14427 sk:ffff8800baf12080 <->
```

which results in this match:
[`nginx",pid=583,fd=8),("nginx",pid=582,fd=8),("nginx",pid=580,fd=8),("nginx`](https://regex101.com/r/yasjHD/1) (the page does nit support ruby regex but pcre should be compatible for this expression)

There are not tests/mocks for this case in [`/test/unit/mock/cmd/ss-tulpen`](https://github.com/chef/inspec/blob/ca19ef55708c9e42610d6f665507d40173688da0/test/unit/mock/cmd/ss-tulpen).

Edit:
Netstat did only display the first process:
```
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          14427       579/nginx: worker p
```

Edit 2: The PR that introduced this is #2110
