### ISSUE TITLE
user resource: System groups with ISO-8859-1 characters

### ISSUE THREAD

**Issue by mgrobelin** [inspec/inspec#2256]
### Description

I cannot check a users group name, if it includes ISO-8859-1 characters like ä (german a-Umlaut).

### InSpec and Platform Version

master

### Replication Case

Users on systems authenticating with an german Active Directory are receiving the default primary group named 'domänen-benutzer'. 

Besides this seems not really intended in Linux-world (one cannot ```groupadd domänen-benutzer```: groupadd: 'domänen-benutzer' is not a valid group name), it can become very real when receiving groups by LDAP/NIS..

```
[me@host ~]$ id | grep -o domänen-benutzer >> /dev/null && echo "true"
true
```

### Possible Solutions

Well, what actually would work is to force utf8 encoding on command output, but this might be a big change and break things for other people.

I personally would prefer to convert the encoding on demand within the control, like so:

```
    describe user('me') do
        its('group.force_encoding(Encoding::UTF_8)') { should cmp == 'domänen-benutzer' }
    end
```

### Stacktrace

```
    # 1) eq-Matcher
    # =>
    #×  User myuser group should eq "domänen-benutzer"
    #
    #expected: "domänen-benutzer"
    #  got: "dom\xC3\xA4nen-benutzer"
    #
    #(compared using ==)
    describe user('me') do
        its('group') { should eq 'domänen-benutzer' }
    end
    
    
    # 2) cmp-Matcher
    # =>
    #×  User myuser group should cmp == "domänen-benutzer"
    #incompatible character encodings: UTF-8 and ASCII-8BIT
    describe user('me') do
        its('group') { should cmp == 'domänen-benutzer' }
    end

    # 3) cmp-Matcher force_encoding
    # =>
    #×  User mgrobelin group.force_encoding(Encoding::UTF_8) 
    #undefined method `force_encoding(Encoding::UTF_8)' for "dom\xC3\xA4nen-benutzer":String
    describe user('me') do
        its('group.force_encoding(Encoding::UTF_8)') { should cmp == 'domänen-benutzer' }
    end    
   


```

**Comment by adamleff** [comment]
Thanks for submitting this issue, @mgrobelin.

As a workaround until we can dig into this some more, you may have better luck using the `expect` syntax where you can do more Ruby-ish things directly than you can with the `its...should` syntax. For example, something like this might work (though I haven't tested it personally

```ruby
describe user('me') do
  it 'is in the correct group' do
    expect(subject.group.force_encoding(Encoding::UTF_8)).to eq('domänen-benutzer')
  end
end
```

**Comment by mgrobelin** [comment]
Thanks for the suggestion @adamleff , workaround does fine for me! 

```
     ✔  User me home should eq "/home/me"
     ✔  User me shell should eq "/bin/bash"
     ✔  User me has primary group domänen-benutzer
```

**Comment by kekaichinose** [comment]
This issue has aged, but it appears the work-around solved the OP's ask.

We apologize that we have not made the time to address a long-term solution to this, but if it's still causing you pain with using the app, please open a new issue, making sure to provide stack trace and repro data that is relevant to the current version of Chef InSpec.

Thank you!
__Chef InSpec Team__
