### ISSUE TITLE
service.enabled? in SysV system fails if home directory have fles named S*

### ISSUE THREAD

**Issue by Wing924** [inspec/inspec#2273]
### Description

service.enabled? in SysV system fails if home directory have fles named S*

### InSpec and Platform Version
InSpec: 1.36.1
Platform Version: CentOS 6.3

### Replication Case

```ruby
#sepc.rb
describe service('network') do
  it { should be_enabled }
  it { should be_running }
end
```

execute `inspec exec spec.rb`
```
  Service network
     ✔  should be enabled
     ✔  should be running
```

Then, create a file named `STDOUT` in home directory.

execute `inspec exec spec.rb`
```
  Service network
     ∅  should be enabled
     expected that `Service network` is enabled
     ✔  should be running
```

### Possible Solutions
https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L400

AS IS:
```
enabled_services_cmd = inspec.command('find /etc/rc*.d /etc/init.d/rc*.d -name S*').stdout
```

TO BE:
```
enabled_services_cmd = inspec.command('find /etc/rc*.d /etc/init.d/rc*.d -name "S*"').stdout
```

**Comment by adamleff** [comment]
Thanks for submitting this bug, @Wing924, and the subsequent PR!
