### ISSUE TITLE
JUnit output has incorrect "class" attribute on <testcase>

### ISSUE THREAD

**Issue by rlaveycal** [inspec/inspec#2276]
### Description

Running inspec via Test-Kitchen with junit output produces an XML file with entries like:

```xml
<testcase name='Service DatadogAgent should be installed' class='datadog' time='0.383979'/>
```

I'm consuming this in Team City and it ignores the `class` attribute. From what I can see the attribute should be called `classname` (http://help.catchsoftware.com/display/ET/JUnit+Format)

### InSpec and Platform Version

1.36.1 on Windows (via ChefDK)

### Replication Case

Run inspec and output a junit file

### Possible Solutions

This is the line that generates the `class` attribute. The condition also looks strange - test for `:title` member and if it exists use the `:id` member instead?

https://github.com/chef/inspec/blob/e44de521b67c3cb0758432bb60f05510de9d1fd4/lib/inspec/rspec_json_formatter.rb#L896

**Comment by adamleff** [comment]
@rlaveycal good find, I do believe you're correct re: it being `classname` and not `class`.

Regarding the condition, InSpec supports tests inside and outside of a control. Control titles are arbitrary strings, sometimes full sentences! I believe the author's intention was to use the presence of a `title` property to determine whether or not we were in a control or just a "naked" test. I'll test to see if the ID is populated as well... either way, I'll add a comment so it's clearer to the next reader.

**Comment by adamleff** [comment]
Yeah, we do generate a unique ID if it's outside of a control structure, such as:

```
"id": "(generated from test_spec.rb:1 de0ce10e4bbbd4d0ff7a65f4234de8c1)"
```

... so the intent is to use the existence of the title to determine if we're in a control structure, that's all. Good question :)

**Comment by mgrobelin** [comment]
I am a bit worried that this might break/alter reporting for Jenkins' junit "[integration](http://kerryhouse.net/chef/2016/11/18/kitchen-inspec-jenkins.html)" users.

**Comment by rlaveycal** [comment]
[this](https://pzolee.blogs.balabit.com/2012/11/jenkins-vs-junit-xml-format/) is a bit old but says it should be `classname`. I think [this](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd) is the XSD which also says `classname`

**Comment by mgrobelin** [comment]
I just applied the suggested change within my inspec installation and observed the Jenkins report output. In sum the change breaks my so-far intention, as there seems to be some parsing magick within Jenkins Junit Plugin, which generates the links/structure within HTML markup based  on `classname` and/or `class`. 

Nevertheless reports and their relations work fine for me again, if `classname` is prefixed with the Profile's name, like here:  https://gist.github.com/mgrobelin/ed7b43725086a3834ce94bbadbe89342#file-rspec_json_formatter-rb-L904 

I also added the Control's description to the XML's Testcase `status` attribute, just to have access to that information for custom post-processing and `status` seem not to be used in Jenkins at all, so...

```xml
<testcase name='System Package strace should be installed' classname='admin-01' time='2.02911027
2'/>
```
... becomes ...

```xml
<testcase name='System Package strace should be installed' classname='my-profile.admin-01' status='Various sysadmin utilities should be available.' time='2.00
6214347'/>
```

@rlaveycal How does Team City behave if `classname` is prefixed with the Profile's name?

**Comment by adamleff** [comment]
@mgrobelin @rlaveycal Can either of you provide me documentation as to how Jenkins uses `class` instead of `classname`? I've been unsuccessful at finding anything, and therefore I'm inclined to merge the pending pull request because all documentation I can find refers only to `classname`

Please let me know ASAP if there's any reason I should hold off on merging the pending pull request.

**Comment by mgrobelin** [comment]
@adamleff Didn't see anything about `class`. For `classname` see [CaseResult.java](https://github.com/jenkinsci/junit-plugin/blob/b98cb6eba3b1207a3eba70a2e0766f3e26953b4e/src/main/java/hudson/tasks/junit/CaseResult.java#L121), [SuiteResult.java](https://github.com/jenkinsci/junit-plugin/blob/master/src/main/java/hudson/tasks/junit/SuiteResult.java#L241) and [ClassResult.java](https://github.com/jenkinsci/junit-plugin/blob/b98cb6eba3b1207a3eba70a2e0766f3e26953b4e/src/main/java/hudson/tasks/junit/ClassResult.java#L111) from [Jenkins JUnit Plugin](https://wiki.jenkins.io/display/JENKINS/JUnit+Plugin). I followed the String "`(root)`", which is displayed instead of the Control's name in hierarchy since suggested change.

+1 for hold off PR, as Jenkins > Team City

**Comment by rlaveycal** [comment]
@mgrobelin I don't understand your concern. You've highlighted code that shows that Jenkins expects `classname` and uses the suite name (or part of it) if it doesn't exist. The PR now sets classname. This is obviously going to change the behaviour of anything processing the file and break any linkages to previous test results, but that's unavoidable. The PR is implementing correct behaviour.

**Comment by mgrobelin** [comment]
@rlaveycal The concern is, that people using Jenkins will see their reports structure break. I understand that you want to receive results from Team City, but so I do with Jenkins.

My suggestion is to use `classname` in the format `ProfileName.ControlName` as shown above. This should render good results within both CI tools, if I understand [these docs](https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity) ("Interpreting test names") correctly:

* TeamCity takes the suite name from the corresponding suite message
* if the reported test name starts with the suite name, it is truncated
* the part of the test name after the last dot is treated as a test name
* the part of the test name before the last dot is treated as a class name
* the rest of the test name is treated as a package/namespace name
```

**Comment by rlaveycal** [comment]
I've run a quick test and can confirm that TeamCity is happy with the format you propose. My Test-Kitchen tests don't have an explicit profile - they're just controls. I'm assuming that a suitable default is set (ideally the parent directory rather than the full path as used for the suite name.

**Comment by mgrobelin** [comment]
Excellent! @adamleff do you adapt this in the PR?
```diff
--- a/lib/inspec/rspec_json_formatter.rb
+++ b/lib/inspec/rspec_json_formatter.rb
@@ -874,8 +874,9 @@ class InspecRspecJUnit < InspecRspecJson
   private
 
   def build_profile_xml(profile)
+    profile_name = profile[:name]
     profile_xml = REXML::Element.new('testsuite')
-    profile_xml.add_attribute('name', profile[:name])
+    profile_xml.add_attribute('name', profile_name)
     profile_xml.add_attribute('tests', count_profile_tests(profile))
     profile_xml.add_attribute('failed', count_profile_failed_tests(profile))
 
@@ -883,17 +884,25 @@ class InspecRspecJUnit < InspecRspecJson
       next if control[:results].nil?
 
       control[:results].each do |result|
-        profile_xml.add(build_result_xml(control, result))
+        profile_xml.add(build_result_xml(profile_name, control, result))
       end
     end
 
     profile_xml
   end
 
-  def build_result_xml(control, result)
+  def build_result_xml(profile_name, control, result)
     result_xml = REXML::Element.new('testcase')
     result_xml.add_attribute('name', result[:code_desc])
-    result_xml.add_attribute('class', control[:title].nil? ? 'Anonymous' : control[:id])
+    # if there is no control title, we are likely receiving test results from a
+    # "naked" test (a test not located within a control block). Therefore, rather
+    # than outputting the auto-generated ID, i.e.
+    #
+    # "(generated from test_spec.rb:1 de0ce10e4bbbd4d0ff7a65f4234de8c1)")
+    #
+    # ... we'll output "Anonymous" instead.
+    result_xml.add_attribute('classname', control[:title].nil? ? "#{profile_name}.Anonymous" : "#{profile_name}.#{control[:id]}")

```

Regarding the failing test you mentioned in the PR: it searches for`class` attribute via Xpath, which now has changed to `classname`. Change this in `test/functional/inspec_exec_junit_test.rb` line 54 col 72 and it should pass, right?

**Comment by adamleff** [comment]
@mgrobelin @rlaveycal I'm hesitant to use the profile name because there's no guarantee it won't have spaces or other odd characters in it. How would Jenkins and Team City react in that situation?

Would it be OK to use the sha256 of the profile instead? How would that look in the respective UIs?

**Comment by mgrobelin** [comment]
I played around a bit and can confirm that Jenkins Junit can more and less handle exotic profile/control names like `Some exßotic pröfile "'#<>&?:-_.`

It doesn't render perfect html results within the UI - obviously because non-URL safe chars are replaced  `#&?`) - but it also doesn't influence the working things, so in sum for me it behaves ok'ish. See https://github.com/mgrobelin/inspec-exotic-profilename/blob/master/jenkins-junit-plugin.png for a visual impression.

As it wasn't too trivial to do the escaping right, here I crafted a profile for vendoring, which might become handy for others:  https://github.com/mgrobelin/inspec-exotic-profilename

**Comment by adamleff** [comment]
@rlaveycal and @mgrobelin: thanks for the feedback, I've accepted @mgrobelin's patch and prefix the classname with the profile name and the PR is updated.
