### ISSUE TITLE
RFC: singular vs plural resources

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2277]
This originated as a discussion on https://github.com/chef/inspec-aws/issues/111 .

Consider the resources `package` and `packages`.  I call those a "singular" and a "plural" resource.  We typically say that you use the singular to identify a single resource and work with its rich properties, while you use a plural resource to search broadly and audit the collection as a whole.

There are some things worth exploring here:
 * We need to implement searching in both cases.  
 * There will always be "feature pressure" to have them match in their properties ("Why can I access property Foo on the singular resource, but I can't search for them by that property on the plural resource?")
  * Test statements are a bit nonsensical in the plural ("the packages it should not exist" does not read well)
  * It's confusing to have both a singular and a plural, especially if their behavior and features are very different
  * Should one be able to access the individual members matched by the plural resource?  Should one be able to do so and receive a first-class resource, or is this reserved for more advanced users using the `entities` approach to get at low-level data?
  * What would it mean to access a property of a list result?  Can you test against them?

The InSpec team is very interested in thoughts, and examples of control code (even / especially pseudocode) that "feels good" or "feels bad".

**Comment by TheLonelyGhost** [comment]
Can confirm that I was confused by the singular versus plural forms of, e.g., `user` vs. `users` and `package` vs. `packages`. I can see how it would be useful for fuzzy-finding a particular resource where an identifying attribute matches a certain pattern.

All that said, perhaps it would be better to include a uniform list pattern where it only gives back whether the query returned any results, how many results, and unique identifiers for each. In the case of users, it would return the number of users and a list of usernames. Then the developer is free to plug that into the more fleshed-out resource:

```ruby
user_list = users.where { username =~ /service_/i }

describe user_list do
  it { should exist } # If the list is empty, the list effectively does not exist
  its('size') { should eq 4 }
end

user_list.each do |u|
  describe user(u.username) do
    its('shell') { should match(%r{/(?:nologin|false)$}i) }
  end
end
```

**Comment by clintoncwolfe** [comment]
As FilterTable has matured, most of these questions have been addressed.  I'm closing this; if there is more to say, by all means re-open.
