### ISSUE TITLE
nginx_conf is not correctly parsing map directive

### ISSUE THREAD

**Issue by chrisLeeTW** [inspec/inspec#2278]
### Description
nginx_conf will return empty object when there are map directive in nginx.conf

### InSpec and Platform Version
inspec version : 1.43.5 via docker (https://hub.docker.com/r/chef/inspec/)
target OS platform: ubuntu
target OS family: debian
target OS release: 16.04

#### example nginx.conf
```
user www-data www-data;
pid /run/nginx.pid;
worker_processes auto;
daemon off;

events {
    use epoll;
    worker_connections 10;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type text/html;
    charset utf-8;

    access_log off;
    error_log off;
    server_tokens off;
    port_in_redirect off;
    gzip off;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    map $request_uri $fcgi_cache_enabled {
        default 0;
        "~^\/opcache-api" 1;
    }

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
```
#### enter command
```
inspec> nginx_conf.params
```
#### will return
```
=> {}
```

**Comment by adamleff** [comment]
Reproducible on current master of InSpec.

**Comment by adamleff** [comment]
Initial error is here: https://github.com/chef/inspec/blob/c2ec4b95458ab27ecf14289088bbcc4c1fcb1420/lib/utils/nginx_parser.rb#L59

```
Parslet::ParseFailed: Failed to match sequence (FILLER? EXP{0, }) at line 1 char 1.
from /Users/aleff/projects/inspec/.direnv/ruby/gems/parslet-1.5.0/lib/parslet/cause.rb:63:in `raise'
```

**Comment by adamleff** [comment]
Turns out it's not the existing of the `map` directive but rather this line:

```
        "~^\/opcache-api" 1;
```

... as it's not a valid identifier according to our existing Parslet rules. The `NginxParser` class will need to be updated to account for identifiers like this.

If you delete that line from your sample nginx.conf, you'll see that it parses. :)
