### ISSUE TITLE
Run a bash cmd before the command that needs to be asserted

### ISSUE THREAD

**Issue by dialex** [inspec/inspec#2279]
### Description

- Run command A, get result into a variable
- Use variable to build the command B string.
- Assert the stdout of running command B.

### InSpec and Platform Version

1.42.3, even though this might be a Ruby question.

### Replication Case

This is my template, from @adamleff at https://github.com/chef/inspec/pull/2017#issuecomment-340828879:

```ruby
id = 'curl ... | jq ...'
api_command = 'curl ... #{id} ... | jq .status'

describe do
  subject { bash(api_command) }
  it "should be success" do
    expect(subject.stdout).to include("success")
  end
end
```

help is appreciated 🙏

**Comment by adamleff** [comment]
Replied to @dialex via Slack, but for posterity, this can be achieved by calling the `command` resource directly:

```ruby
id = command('curl ... | jq ...').stdout.strip     # strip removes the trailing newline and any preceeding whitespace
```
