### ISSUE TITLE
inspec report time fields

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#2290]
json full report snippet:
```json
          "results": [
            {
              "status": "passed",
              "code_desc": "File /etc/hosts mode should eq 420",
              "run_time": 0.046157,
              "start_time": "2017-11-06 14:08:16 +0000"
            }
          ]
```

For inspec 2.0, can we look at reporting time into a standard time format like RFC3339?

```ruby
$ pry
[1] pry(main)> DateTime.now.rfc3339
=> "2017-11-06T14:39:18+00:00"

[2] pry(main)> Time.now.utc.strftime('%FT%TZ')
=> "2017-11-06T14:39:22Z"
```

**Comment by adamleff** [comment]
Hey, the current time format is standard in that it's the standard way Ruby prints out Time objects as a string! 🙂 

That said, I'd be in favor of adopting an RFC standard and RFC3339 is fine by me.

**Comment by chris-rock** [comment]
@adamleff I think we should make this a standard for InSpec 2.0 Thank you @alexpop for proposing this solution

**Comment by adamleff** [comment]
I've added this issue to the 2.0 milestone. This is an easy change and can be made at anytime with the PR targeted at the release-2.0 branch.

**Comment by adamleff** [comment]
This should be ready to implement once @jquick completes #2415

**Comment by jquick** [comment]
This was completed in 2.0 via #2487
