### ISSUE TITLE
multiple versions of same package errors with old version

### ISSUE THREAD

**Issue by nkk1** [inspec/inspec#2303]
### Description

I have two versions of same package
```
# rpm -qa | grep 'kernel-[24]'
kernel-4.9.34-301.alti6.x86_64
kernel-2.6.32-696.el6.x86_64
```

```
 describe package('kernel') do
  its('version') { should eq '4.9.34-301.alti6' }

 end
```

```
   ∅  kernel version should eq "4.9.34-301.alti6"

     expected: "4.9.34-301.alti6"
          got: "2.6.32-696.el6"
```

i tried with match and include matchers also still it fails

```
     ∅  kernel version should match "4.9.34-301.alti6"
     expected "2.6.32-696.el6" to match "4.9.34-301.alti6"
```

### InSpec and Platform Version

```
inspec (1.43.8, 0.35.0)
kitchen-inspec (0.19.0)
```
running on mac

### Replication Case

see above

**Comment by adamleff** [comment]
Hi @karthik-altiscale and thanks for your report.

The `package` resource only supports a single package for a given name, and on Red Hat based systems, it will be the last package listed in the output of `rpm -qia <package name>`

However, if you use the `packages` resource (plural, with an "s" at the end), you can get tabular data back (using our internal `FilterTable` system) and get at the data you're looking for.

In your case, you can write a test like this:

```ruby
describe packages('kernel').where { name == 'kernel' } do
  its('versions') { should include '4.9.34-301.alti6' }
end
```

I hope that helps!
~Adam
