### ISSUE TITLE
sshd_conf resource and downcase and or issue with the `cmp` matcher

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#2304]
### Description

When working with the SSHD conf - and I would assume other resources - it seems we need to define a pattern ( I like the idea of downcase all) for the `params` method or perhaps review the `cmp` matcher is playing nicely?

https://github.com/chef/inspec/blob/master/lib/resources/ssh_conf.rb#L44-L50 downcases the params and if I recall the expected behavor of the `cmp` matcher should account for this so that 

```
  describe sshd_config do
    its('X11Fowarding') { should cmp 'yes' }
  end
```
will work. 

At the moment - inspec is returning the params array as 

```
inspec> sshd_config.params
=> {"acceptenv"=>
  ["LANG",
   "LC_CTYPE",
   "LC_NUMERIC",
   "LC_TIME",
   "LC_COLLATE",
   "LC_MONETARY",
...
...
 "usepam"=>["yes"],
 "useprivilegeseparation"=>["yes"],
 "x11displayoffset"=>["10"],
 "x11forwarding"=>["yes"],
 "x11uselocalhost"=>["yes"]}
```
and
```
inspec> sshd_config.params('X11Forwarding')
=> nil
inspec> sshd_config.params('x11forwarding')
=> ["yes"]
```

Thoughts? I would rather avoid having to put a .downcase in the test.

**Comment by adamleff** [comment]
@aaronlippold the decision on how to handle the keys of parameters must be implemented on a resource-by-resource basis. In the case of OpenSSH configs, the keys are case-insensitive, but that's not the case in other configurations. Therefore, we cannot assume a case-insensitive match at all times.

As you noted, the `params` method of the `sshd_config` resource returns all the params as downcase. But the `params` method is a raw dump of what we know. It's not meant to be used for direct access to an individual parameter for testing.

On this line:

https://github.com/chef/inspec/blob/master/lib/resources/ssh_conf.rb#L45

... we take whatever the user passed in and downcase it so we can match it in the configuration file. That means it doesn't matter what the case of the key was, we will always match. You need to access the key directly, NOT via the `params` method:

```
inspec> sshd_config.params
=> {"authorizedkeysfile"=>[".ssh/authorized_keys"],
 "usepam"=>["yes"],
 "x11forwarding"=>["no"],
 "acceptenv"=>["LANG LC_*"],
 "subsystem"=>["sftp\t/usr/libexec/sftp-server"]}
inspec> sshd_config.X11FoRwardING
=> "no"
inspec> sshd_config.x11forwarding
=> "no"
inspec> sshd_config.X11FORWARDING
=> "no"
inspec> describe sshd_config do
inspec>   its('X11FoRwArDiNg') { should cmp 'no' }
inspec> end

Profile: inspec-shell
Version: (not specified)

  SSHD Configuration
     ✔  X11FoRwArDiNg should cmp == "no"
```

The *values* in OpenSSH configuration files *ARE* case-sensitive, and that's where the `cmp` matcher comes in to play. It only affects the value comparisons; it has nothing to do with the parameter you're searching for. That will remain a resource-by-resource decision.

Hope this helps.
~Adam
