### ISSUE TITLE
Readme: Point to sources of documentation

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#231]
Users cannot currently easily find their way to documentation when starting here on github.

**Comment by jzohrab** [comment]
@arlimus - where did you have trouble finding docs?  I can open a PR with you if you explain where the trouble was.

**Comment by arlimus** [comment]
Closing this issue now because it hasn't been confirmed by users. That said, I'm opening a different one to help connect the website's docs to InSpec's source code for docs.

**Comment by arlimus** [comment]
Created the new inspec.io to GitHub issue here: https://github.com/chef/inspec/issues/1712
