### ISSUE TITLE
Manipulate http body

### ISSUE THREAD

**Issue by scalp42** [inspec/inspec#2310]
Assuming a remote host running a `http` resource against a Consul server for example:

```ruby
# Test if Consul HTTP API returns something from remote node
describe http(%|#{consul_server}:8500/v1/status/leader|, enable_remote_worker: true) do
  its('headers.Content-Type') { should eq('application/json') }
  its('body') { should match(Resolv::IPv4::Regex) }
end
```

It's failing as Consul API returns JSON `"xx.xx.xx.xx"`. How can I manipulate the `body` here to strip quotes for example?

Even better, just parse the `body` through `JSON.parse` for example and get the string directly.

Thanks in advance!

**Comment by adamleff** [comment]
Hi @scalp42!

The problem with the `Resolv::IPv4::Regex` is that it has beginning/end of string anchors making it difficult to use in the manner you tried. 

What I would do is break out the http resource into a separate variable, and then use two resources: one to get the HTTP parameters, and one to parse the JSON, like so:

```ruby
consul_http = http(%|#{consul_server}:8500/v1/status/leader|, enable_remote_worker: true)

describe consul_http do
  its('headers.Content-Type') { should eq('application/json') }
end

describe json(consul_http.body) do
  its('ip_address_key') { should match(Resolv::IPv4::Regex) }
end
```

Hopefully that helps!
~Adam

**Comment by scalp42** [comment]
Totally makes sense @adamleff 

Thanks again 👍

**Comment by scalp42** [comment]
Update: looks like it's a no go:

```ruby
consul_http = http(%|#{consul_server}:8500/v1/status/leader|, enable_remote_worker: true)

describe consul_http do
  its('headers.Content-Type') { should eq('application/json') }
  its('status') { should eq 200 }
end

describe json(consul_http.body) do
  it { should match(Resolv::IPv4::Regex) }
end
```

The answer from Consul is just a string like `"10.10.10.10:8300"` and it appears that the `json` resource insists on a file:

```
  http GET
     ✔  on xxxxx:8500/v1/status/leader headers.Content-Type should eq "application/json"
     ✔  on xxxxx:8500/v1/status/leader status should eq 200
  Json "xx.xx.xx.xx:8300"
     ↺  Can't find file ""xx.xx.xx.xx:8300""
  Host consul.service.consul
     ✔  should be reachable
     ✔  should be resolvable
```

**Comment by adamleff** [comment]
Oh, that's funny. `"1.2.3.4"` isn't actually JSON... `{ "ip_address": "1.2.3.4" }` would be.

**Comment by adamleff** [comment]
So, we can take a slightly different approach.

**Comment by adamleff** [comment]
@scalp42 let's try a different approach. If the full body that you get back via that HTTP call is just an IP address wrapped in double-quotes, try this to see if it would work:

```ruby
consul_http = http(%|#{consul_server}:8500/v1/status/leader|, enable_remote_worker: true)

describe consul_http do
  its('headers.Content-Type') { should eq('application/json') }
  its('status') { should eq 200 }
end

ip_address = consul_http.body.strip.delete('"')

describe 'consul IP address' do
  it 'should be a valid IPv4 address' do
    expect(ip_address).to match(Resolv::IPv4::Regex)
  end
end

```

**Comment by adamleff** [comment]
I used a different syntax (`expect` instead of `should`) so I could have better control over the text output that shows up in the InSpec report. Otherwise, if there was an invalid IP address, you'd just get a message that say "foo did not match blah" instead of helpful messaging like "it should be a valid IP address"

**Comment by scalp42** [comment]
I'm wondering if it's the port `:8300` being problematic but I believe match should be fine. I tried your approach but no luck:

```
  consul IP
     ∅  address should be a valid IPv4 address
     expected "10.10.10.10:8300" to match /\A((?x-mi:0
                    |1(?:[0-9][0-9]?)?
                    |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                    |[3-9][0-9]?))\.((?x-mi:0
                    |1(?:[0-9][0-9]?)?
                    |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                    |[3-9][0-9]?))\.((?x-mi:0
                    |1(?:[0-9][0-9]?)?
                    |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                    |[3-9][0-9]?))\.((?x-mi:0
                    |1(?:[0-9][0-9]?)?
                    |2(?:[0-4][0-9]?|5[0-5]?|[6-9])?
                    |[3-9][0-9]?))\z/
 ```

(Unrelated, what is the correct syntax? `should` vs `expect`? I see examples in the doc with `should` but I believe RSpec moved away from it, just curious.)

**Comment by scalp42** [comment]
Thats what it was!

```
  consul IP
     ✔  address should be a valid IPv4 address
```

```ruby
consul_http = http(%|#{consul_server}:8500/v1/status/leader|, enable_remote_worker: true)
ip_address = consul_http.body.strip.delete('"').split(':8300').first
```

Thanks a lot @adamleff, much appreciated!

**Comment by adamleff** [comment]
it's absolutely the port causing problems!

```
[1] pry(main)> require 'resolv'
=> true
[2] pry(main)> '1.2.3.4'.match(Resolv::IPv4::Regex)
=> #<MatchData "1.2.3.4" 1:"1" 2:"2" 3:"3" 4:"4">
[3] pry(main)> '1.2.3.4:8300'.match(Resolv::IPv4::Regex)
=> nil
```

So, let's try this again :)

```ruby
ip_address = consul_http.body.strip.delete('"').split(':').first

describe 'consul IP address' do
  it 'should be a valid IPv4 address' do
    expect(ip_address).to match(Resolv::IPv4::Regex)
  end
end
```

**Comment by adamleff** [comment]
Re: `should` vs. `expect` - the InSpec project has standardized on `should` because it, combined with our use of `rspec-its`, reads more easily for non-technical people. RSpec has moved away from it but it still works and it's still our preferred language choice.

However, `expect` still works and I prefer it personally. It's user choice at this point. I wrote up a little blurb about it on the website, bottom of this page: https://www.inspec.io/docs/reference/profiles/

**Comment by scalp42** [comment]
Thanks again for the feedback, I'll share with the team.
