### ISSUE TITLE
owner and permissions problem for /etc/shadow 

### ISSUE THREAD

**Issue by sheenaajay** [inspec/inspec#2314]
### Description

Briefly describe the issue and the expected behavior

owner and permissions problem for /etc/shadow 

### InSpec and Platform Version
 inspec version -tested on 1.2.1 1.3.0 1.9.0 
centos version 7.2
Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

amazon-ebs:   ×  os-02: Check owner and permissions for /etc/shadow (5 failed)
    amazon-ebs:      ✔  File /etc/shadow should exist
    amazon-ebs:      ✔  File /etc/shadow should be file
    amazon-ebs:      ✔  File /etc/shadow should be owned by "root"
    amazon-ebs:      ×  File /etc/shadow should not be executable
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004438d30>
    amazon-ebs:      ×  File /etc/shadow should not be readable by other
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004438d30>
    amazon-ebs:      ✔  File /etc/shadow group should eq "root"
    amazon-ebs:      ×  File /etc/shadow should not be writable by owner
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004438d30>
    amazon-ebs:      ×  File /etc/shadow should not be readable by owner
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004438d30>
    amazon-ebs:      ×  File /etc/shadow should not be readable by group
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004438d30>
    amazon-ebs:   ×  os-03: Check owner and permissions for /etc/passwd (7 failed)
    amazon-ebs:      ✔  File /etc/passwd should exist
    amazon-ebs:      ✔  File /etc/passwd should be file
    amazon-ebs:      ✔  File /etc/passwd should be owned by "root"
    amazon-ebs:      ×  File /etc/passwd should not be executable
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>
    amazon-ebs:      ×  File /etc/passwd should be writable by owner
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>
    amazon-ebs:      ×  File /etc/passwd should not be writable by group
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>
    amazon-ebs:      ×  File /etc/passwd should not be writable by other
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>
    amazon-ebs:      ×  File /etc/passwd should be readable by owner
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>
    amazon-ebs:      ×  File /etc/passwd should be readable by group
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>
    amazon-ebs:      ×  File /etc/passwd should be readable by other
    amazon-ebs: undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x00000004443b68>

**Comment by sheenaajay** [comment]
similar  to this issue
https://github.com/chef/inspec/issues/1264

**Comment by adamleff** [comment]
@sheenaajay thanks for your report. This is a bug in chef/train 0.29.1 and I've opened chef/train#215 to fix it.

Depending on how you've installed InSpec (i.e. as a standalone download, or via gems, etc.), you may be able to downgrade to an earlier version. This is not an issue in Train 0.28.0.

Thanks!
~Adam
