### ISSUE TITLE
No skip example in the documentation

### ISSUE THREAD

**Issue by jjasghar** [inspec/inspec#2315]
### Description

We are missing a verbose `skip` example in the https://www.inspec.io/docs/reference/profiles/ page. I believe having them in the example profiles is helpful, but looking at the documentation would be quicker to search against.

**Comment by jjasghar** [comment]
https://github.com/chef/inspec/blob/master/docs/dsl_inspec.md#exclude-specific-test

**Comment by jjasghar** [comment]
https://github.com/chef/inspec/issues/613 is worth linking here too.

**Comment by jjasghar** [comment]
Useful example here to: https://discourse.chef.io/t/inspec-conditional-testing-based-on-node-attributes/8908/2

**Comment by adamleff** [comment]
@jjasghar we have a section for this already here: https://www.inspec.io/docs/reference/dsl_inspec/#exclude-specific-test

I recognize the docs are laid out a bit poorly, but there's an effort underway to revamp all of inspec.io. But I believe your concern is already addressed at the above link. Can you confirm?

**Comment by jjasghar** [comment]
It seems that eventually, i realized i could just write:

```ruby
control '5-1-locking-server-powerstrip' do
  title 'Lock and Securing the power strip for your server'
  impact 0.9
  desc 'Having the power strip for your server should be locked and secured.'

  tag remediation: 'Page 43 of the Example_com_Best_Practices.v1.2.0.pdf'

  ref 'http://example.com/best_practices/'

  describe "The power strip on the server" do
    skip "should have a human verify that it is locked and in a secured environment"
  end
```

And get the desired effect. It feels like this should be documented a tad bit better. If yall are working on overhauling that's awesome and looking forward to it.
