### ISSUE TITLE
INI resource documentation clarification

### ISSUE THREAD

**Issue by oblutak** [inspec/inspec#2316]
### Description

Enhance documentation to cover case where ini file has sections and how to reference the attributes

### InSpec and Platform Version

1.45.9

### Replication Case

Current doc only has simple example
```
describe ini('path') do
  its('setting_name') { should eq 'value' }
end
```

### Possible Solutions

If your ini file looks like
```
[section1]
attribute=value
```

To test the value would look something like

```
describe ini('path') do
  its(['section1','attribute']) { should eq 'value' }
end
```
The above worked for me.  Not sure if other method exists.

**Comment by oblutak** [comment]
@adamleff pointed to me that 
```
describe ini('path') do
  its('section.attribute') { should eq 'value' }
end
```
would also work.  Looks more clean and ruby'ish

**Comment by adamleff** [comment]
@oblutak thanks for submitting this issue. I've opened PR #2320 to add clarity to the docs.
