### ISSUE TITLE
undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x000000034aec98>

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#2326]
### Description

as reported by @jujugrrr in https://github.com/chef/inspec/pull/2306#issuecomment-345960533: 

Trying to use inspec 1.45.9 with train 0.29.1 I'm getting errors on the following test cases:
```
describe file('/tmp/myfile') do
  it { should be_executable.by('group') }
end
```
```
 ∅  undefined method `unix_mode_mask' for #<Train::File::Local::Unix:0x000000034aec98>
```
Rolling back to 1.44.8 and train 0.28.0 fixes the issue.

### InSpec and Platform Version

1.45.9

### Possible Solutions

Release train with https://github.com/chef/train/pull/215

**Comment by jujugrrr** [comment]
Thank you @chris-rock, I should have reported the issue rather than just comment. 👍
