### ISSUE TITLE
group resource is broken on macOS

### ISSUE THREAD

**Issue by lavahot** [inspec/inspec#2330]
### Description

The group resource looks at /etc/group like a normal UNIX machine for groups, but on macOS groups created with dscl are put into the Directory Service, which is not always reflected in the /etc/group. 

In fact, the /etc/groups reads: `Note that this file is consulted directly only when the system is running in single-user mode. At other times this information is provided by Open Directory. See the opendirectoryd(8) man page for additional information about OpenDirectory.`

### InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

### Replication Case

Chef cookbook:
```
group 'SomeGroup`
```
InSpec:
```
describe group('SomeGroup') do
  it { should exist }
end
```

### Possible Solutions

On macOS the group resource could look at `dscl . -ls /Groups` to get a more complete list of groups.

**Comment by adamleff** [comment]
Thanks for raising this issue, @lavahot! It's clear we need to make the `group` resource work properly on macOS. I've marked this as a bug and hopefully someone can submit a PR to help us, or we'll get to it as soon as we're able!

**Comment by lavahot** [comment]
Woo!
