### ISSUE TITLE
wrong grub path for rhel based os in grub_conf resource

### ISSUE THREAD

**Issue by atomic111** [inspec/inspec#2331]
### Description

There is the wrong path for rhel based OS's in grub_conf defined.

### InSpec and Platform Version

inspec version: 1.45.9
os: rhel 7.4

### Replication Case

Take a look at https://github.com/chef/inspec/blob/master/lib/resources/grub_conf.rb#L53

### Possible Solutions

@conf_path = path || '/boot/grub2/grub.cfg'

I will provide you a PR for this

**Comment by chris-rock** [comment]
Thank you for finding this issue @atomic111
