### ISSUE TITLE
auditd resource does not support auditd 2.3.2 though it claims to support >=2.3

### ISSUE THREAD

**Issue by wunzeco** [inspec/inspec#2334]
### Description
According to your documentation on `auditd` resource,
[This resource supports versions of audit >= 2.3](https://www.inspec.io/docs/reference/resources/auditd/). But it fails to run on a host with audit v2.3.2.

Here is my experience

```
12:05 $ inspec exec ./ -t $SSHCONN -i $SSHKEY --sudo --controls=cis-ubuntu-14.04-4.1.4

Profile: CIS Ubuntu Linux 14.04 LTS Benchmark Profile (cis-ubuntu-14.04-benchmark)
Version: 0.1.0
Target:  ssh://vagrant@127.0.0.1:2222

  ↺  cis-ubuntu-14.04-4.1.4: 4.1.4 Ensure events that modify date and time information are collected (Scored)
     ↺  The version of audit is outdated. The `auditd` resource supports versions of audit >= 2.3.

Profile Summary: 0 successful controls, 0 control failures, 1 control skipped
Test Summary: 0 successful, 0 failures, 1 skipped
```

### InSpec and Platform Version

- inspec (1.45.13)
- Ubuntu 14.04.4 LTS (x86_64)

### Replication Case
Steps to replicate:

On a Ubuntu 14.04 host (x86_64), 
- install auditd (the latest version is 2.3.2)
```
# apt-cache show auditd | grep Version
Version: 1:2.3.2-2ubuntu1
```
- append audit rule to `/etc/audit/audit.rules` 
```
echo '-w /etc/localtime -p wa -k time-change' >> /etc/audit/audit.rules
```
- create a control to test the above rule
```
control 'cis-ubuntu-14.04-4.1.4' do
  impact  1.0
  title   '4.1.4 Ensure events that modify date and time information are collected (Scored)'

  describe auditd do
      its('lines') { should include %r{-w /etc/localtime -p wa -k time-change} }
  end
end
```

### Possible Solutions

Looking into the code, I believe the conditional here... https://github.com/chef/inspec/blob/4b9acb4800e0be52200a09e941fd160af5c9155e/lib/resources/auditd.rb#L39 ...is incorrect. 

Here is an output of `auditctl -l` on my ubuntu 14.04 (x86_64) host
```
# auditctl -l
LIST_RULES: exit,always arch=3221225534 (0xc000003e) key=time-change syscall=adjtimex,settimeofday
LIST_RULES: exit,always arch=1073741827 (0x40000003) key=time-change syscall=stime,settimeofday,adjtimex
LIST_RULES: exit,always arch=3221225534 (0xc000003e) key=time-change syscall=clock_settime
LIST_RULES: exit,always arch=1073741827 (0x40000003) key=time-change syscall=clock_settime
LIST_RULES: exit,always watch=/etc/localtime perm=wa key=time-change
```

And version reported by auditctl as well as dpkg
```
# auditctl -v
auditctl version 2.3.2

# dpkg -l auditd | grep audit
ii  auditd                              1:2.3.2-2ubuntu1                     amd64        User space tools for security auditing

```

Hence, a conditional based on `/^LIST_RULES:/` will not work.

**Comment by wunzeco** [comment]
PR awaiting review -  https://github.com/chef/inspec/pull/2336

**Comment by james-stocks** [comment]
It would be good to increase the documented `auditd` version number up to the actual version number where the `/^LIST_RULES:/` check works.

We should also consider supporting the `/^LIST_RULES:/` output format since there are RHEL7 production hosts out there that use this format.

**Comment by mattray** [comment]
https://github.com/chef/compliance-profiles/pull/540 is related, fixes 2.4.x support

**Comment by mattray** [comment]
We can either update the documentation that 2.4 or later is required (which is RHEL 7.1 or later) or update the code to support 2.3. If you upgrade RHEL 7.0 to the latest it installs 2.8.1

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
