### ISSUE TITLE
HTTP Resource HEAD timeouts

### ISSUE THREAD

**Issue by JuananOc** [inspec/inspec#2335]
### Description

When using the http resource with head parameter, the curl command that executes gives a timeout because it´s malformed.

### InSpec and Platform Version

InSpec version: 1.43.8
Platform: Amazon Linux AMI 2017.03 (Based on RHEL Fedora)

### Replication Case

Create a describe block like this:
```
describe http('http://google.com', method: 'HEAD', enable_remote_worker: true) do
  its('status') { should eq 200 }
end
```

And execute inspec with `-l debug`. 
You will see that the command who is been executing is `curl -i -X HEAD --connect-timeout 60 'http://google.com'`

### Possible Solutions

Delete the `-X HEAD` from the method 'HEAD' of the http resource. With the `-i` it´s enough but you can add `--head` if you want.

To workaround this I used the command resource:
```
describe command("curl --head 'http://google.com'") do
  its('stdout') {should match /HTTP\/1.1 200 OK/ }
end
```

### Stacktrace

```
[2017-11-24T13:55:14+01:00] DEBUG: Registering rule (generated from test.rb:31 235b7ba485b901fc871767aa31bd44a2)
D, [2017-11-24T13:55:14.299651 #5964] DEBUG -- : [SSH] user@IP<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :verify_host_key=>false}> (curl -i -X HEAD --connect-timeout 60 'http://google.com')
```

**Comment by adamleff** [comment]
It does appear that while it returns data, the connection remains open leading to the timeout.

We cannot simply rely on `-i` giving us the headers because it will be a GET request instead of a HEAD. However, we can detect when the user asks us to perform a HEAD request and modify the command we use instead to use `-I/--head`. I'll submit a PR to do so.
