### ISSUE TITLE
Inspec CLI Support for SSH-Config File Option

### ISSUE THREAD

**Issue by darkn3rd** [inspec/inspec#2338]
### Description

This is a feature request to add an `-F` option to select a ssh-config file, so that a user could simply use:

```bash
inspec exec test.rb -t ssh://systemA -F ./ssh-config
```

Currently, one has to do something like this:

```bash
inspec exec test.rb -t ssh://vagrant@localhost -i $HOME/workspace/projectX/experiment/.vagrant/machines/systemA/virtualbox/private_key -p 2222
```

**Comment by adamleff** [comment]
That's a very interesting idea, @darkn3rd. I'm not sure if the underlying transport libraries we use support this or if we'd have to supply the logic ourselves, but I'll flag this as a feature request.

**Comment by TheLonelyGhost** [comment]
Looks like this feature request would be best suited for the [train gem](https://github.com/chef/train), which is Inspec's underlying transport library. It uses `Net::SSH` as a dependency, which has an option to use `/etc/ssh/ssh_config` and/or `~/.ssh/config` to read in default configurations with its [`Net::SSH::Config` class](https://net-ssh.github.io/net-ssh/Net/SSH/Config.html).

All this is to say it looks possible and like it wouldn't be a ton of development work, but probably better to submit the issue to the train gem first.

**Comment by adamleff** [comment]
@TheLonelyGhost yes, often we get requests in this repo for things that are best solved in Train. However, this change will likely affect both InSpec and Train as this behavior is likely something that should be opt-in, and the user experience remains with InSpec.

**Comment by hazardsec** [comment]
Any update on this? Many of the cloud images I am using have very specific SSH settings out of the box and I am having to change them to get inspec to run against the remote instances. Is there any way to add Ciphers, KexAlgorithms, or MACs since it seems to be ignoring ~/.ssh/config and /etc/ssh/ssh_config?

**Comment by JHeinzde** [comment]
This feature would also be great for me since we have an environment where multiple proxy jumps are required. This would make executing inspec on these machines a whole lot easier.

**Comment by darkn3rd** [comment]
I was curious if there was any update for this?  Note this will have to happen with Inspec as well as Train to support the underlying  `Net::SSH::Config class`.

**Comment by darkn3rd** [comment]
I hope this one gets more traction rather than collecting dust for two years: https://github.com/inspec/train/issues/462

**Comment by kekaichinose** [comment]
@clintoncwolfe I feel like this could probably implemented as an input plugin, at this point. What do you think?

**Comment by JSteeleIR** [comment]
I'd still like to see this. Having to manually pass around target ssh options makes it really difficult to chain inspec & vagrant, esp. in cases where non-standard SSH settings are needed (e.g. Cloud providers/boxes).
