### ISSUE TITLE
use --vendor-cache instead of --cache

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#2339]
### Description

With the introduction of #2309, we have two types of caches now:
- dependency cache directory
- backend caching

Therefore, I propose that we should deprecate `--cache` and use `--vendor-cache` instead, so we can make this clean for InSpec 2.0.

### InSpec and Platform Version

1.44.9

**Comment by adamleff** [comment]
I'm :+1: on this. Any change to add clarity to the CLI is a good thing.

Let's add the new flag and a deprecation warning to the old one in InSpec 1.x, and then add the removal of `--cache` to our checklist in #1728.
