### ISSUE TITLE
Only one formatter can be used

### ISSUE THREAD

**Issue by rmestrum** [inspec/inspec#2346]
### Description

When I execute a test I want the output to be available in different formats (for example html and junit) without running the test multiple times.

### InSpec and Platform Version

OS Fedora: 26
Inspec: 1.45.13

**Comment by adamleff** [comment]
Thanks for your feature request, @rmestrum. I'm currently working on a side-project to revamp the formatter/reporter section of InSpec and this is part of my work. I don't have an ETA on it, but the plan is hopefully by the end of the year or first part of January as time allows.

**Comment by terraform-ctc** [comment]
Glad to hear this functionality is coming.  In our use case, we use Jenkins to run our tests and would like to have the progress output to capture on the job's console, while still being able to save the results in junit format for jenkins.
