### ISSUE TITLE
os_env not working

### ISSUE THREAD

**Issue by atomic111** [inspec/inspec#236]
I used os_env but i don't get a result from it. I tested it in inspec shell

command('echo $PATH').stdout => "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl\n"

vs

 os_env('PATH').content => nil

**Comment by arlimus** [comment]
Thank you for reporting! Put up a MR to take care of this.
