### ISSUE TITLE
oracledb_session resource cannot be run if ORACLE_HOME is not set correctly

### ISSUE THREAD

**Issue by rmestrum** [inspec/inspec#2360]
### Description

When I use the oracledb_session resource and the ORACLE_HOME is not set correctly the test fails with  `∅  undefined method '[]' for nil:NilClass`

The test looks like 
```
sql = oracledb_session(sqlplus_bin: '/opt/oracle/app/12.1.0.2/db_1/bin/sqlplus', user: 'user', pass: 'pass', service: 'user.development.org')

describe sql.query('SELECT NAME AS VALUE FROM v$database;').row(0).column('value') do
  its('value') { should cmp 'ORCL' }
end
```

The result I was expecting was that the query is executed and the query result is validated.

### InSpec and Platform Version

InSpec: 1.45.13
OS: RHEL 6.7
Oracle: 12.1.0.2

### Possible Solutions

In issue #2005 the solution offered is to set the ORACLE_HOME in the `.bashrc` file. This is in my opinion not a correct solution. When you are executing the test on the host, the configuration of the host need to be changed on behalf of the test you need to execute.
In my opinion you should not change the host so the test can be run but the test framework should so be made that the test can be run on the host without changing the host.

A better solution is to set the ORACLE_HOME and PATH variable in the test. If these two are set `sqlplus` can be executed.
```
@oracle_home = opts[:oracle_home]
return skip_resource 'You must provide the oracle home for the session' if @oracle_home.nil?


command = %{export ORACLE_HOME=#{@oracle_home}; export PATH=$PATH:$ORACLE_HOME/bin; echo $PATH; echo "#{opts}\n#{query}\nEXIT" | #{bin} "#{@user}"/"#{@password}"@#{@host}:#{@port}/#{@service}}
```

### Stacktrace

```
D, [2017-12-01T13:52:00.243787 #9523] DEBUG -- : [SSH] root@<remote_ip><{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "password", "keyboard-interactive"], :keys_only=>nil, :keys=>nil, :password=>"<hidden>", :forward_agent=>nil, :paranoid=>false}> (echo "SET MARKUP HTML ON
SET FEEDBACK OFF
SELECT NAME AS VALUE FROM v\$database;
EXIT" | /opt/oracle/app/12.1.0.2/db_1/bin/sqlplus "user"/"pass"@localhost:1521/user.development.org)
Could not execute the sql query 
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
```

**Comment by thiagoamaciel** [comment]
+1

**Comment by reddeppas** [comment]
i think you can pass ORACLE_HOME in sqlplus_bin as below and it should work 
sqlplus_bin: 'ORACLE_HOME=\<oracle home dir\> \<sqplus bin path\>'  as a workaround

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Comment by aaronlippold** [comment]
This is still an issue and we need to reexamine how we want to resolve this issue for the oracle_session resource
