### ISSUE TITLE
Package resource passes when no packages are defined

### ISSUE THREAD

**Issue by qubitrenegade** [inspec/inspec#2373]
### Description

When describing a package and not defining a package name, the inspec test will pass.

### InSpec and Platform Version

Confirmed on 1.45.13, CentOS 6.5

### Replication Case

Create a package resource with no packages defined:

```
describe package do
  it { should be_installed }
end
```

```
System Package
✔ should be installed
```

### Possible Solutions

I think, this should fail or generate an error that "package name" is undefined for "package" control/resource

### Stacktrace

No stack trace as test passes.

Thanks!

**Comment by adamleff** [comment]
Thanks for submitting this issue, @qubitrenegade! This is totally a bug as the resource is useless without a package name.
