### ISSUE TITLE
Firewalld test fails

### ISSUE THREAD

**Issue by markri** [inspec/inspec#2383]
### Description

Try to use firewalld test. Rule is there but inspec says the rule doesnt exist

### InSpec and Platform Version

Inspec: 1.48.0
OS: Ubuntu 16.04
RVM: Ruby 2.4.1p111

Target OS:
CentOS 7.4.1708

### Replication Case

Create a script "firewall.rb"

```
control 'firewall' do
   title 'Check firewall'
   describe firewalld do
     it { should be_running }
     its('default_zone') { should eq 'public' }
     it { should have_rule_enabled('family=ipv4 service name=http accept', 'public')}
   end
end
```

Create a firewall rule on OS in firewalld

`firewall-cmd --add-rich-rule 'rule family=ipv4 service name=http accept'`

Test inspec
`inspec exec firewall.rb -t ssh://user@host --sudo`

Output is similar to:

```
~/.rvm/gems/ruby-2.4.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
~/.rvm/gems/ruby-2.4.1/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:72: warning: constant OpenSSL::Cipher::Cipher is deprecated

Profile: tests from firewall.rb (tests from firewall.rb)
Version: (not specified)
Target:  ssh://user@host:22

  ∅  firewall: Check firewall (1 failed)
     ✔  firewalld should be running
     ×  firewalld should have rule enabled "family=ipv4 service name=http accept", "public"
     expected #has_rule_enabled?("family=ipv4 service name=http accept", "public") to return true, got false
     ✔  firewalld default_zone should eq "public"

Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 2 successful, 1 failure, 0 skipped
```

With following code in regard
[https://github.com/chef/inspec/blob/7fc7942ab1d074820cdd8a7259a78e64ef2627f5/lib/resources/firewalld.rb#L87-L90](https://github.com/chef/inspec/blob/7fc7942ab1d074820cdd8a7259a78e64ef2627f5/lib/resources/firewalld.rb#L87-L90)

I executed `firewall-cmd --zone=public --query-rich-rule='rule family="ipv4" service name="http" accept'`
which results in "yes"

### Possible Solutions

Only conclusion. Target system is ok. Rule is in place, and executing the test command over there results in a positive lookup. So somewhere between te lookup and then end result its "yes" gets converted to "false"

### Stacktrace

Not applicable

**Comment by aaronlippold** [comment]
Hi.

We will look into it.

Thanks,

Aaron

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by tarcinil** [comment]
Upon my investigation, it appears line 88 of `inspec/lib/resources/firewalld.rb` is causing this, by prepending another rule onto your rule.  Thus, ending up with "rule rule family=ipv4 service name=http accept" which will return false because it will cause an error in firewall-cmd.

```
tarcinil:~/Code/inspec$ firewall-cmd --zone=public --query-rich-rule='rule rule family=ipv4 service name=http accept'
Error: list index out of range
```

@markri
It appears that the `have_rule_enabled?` method is not supposed to have `rule` string passed into it based on the unit tests.  

Your test should look like:
```
   describe firewalld do
     it { should have_rule_enabled('family=ipv4 service name=http accept', 'public')}
   end
```
I am creating a PR in the A.M. to add the rule string only when it is not already present in the method argument to allow for this use case as well as provide backward compatibility.

**Comment by markri** [comment]
Thnx, somehow overlooked the double "rule". Nevertheless, I just removed the "rule"  in my test. Just as you described. However... It still gives me this same error. I changed my initial post (script and output) to prevent confusion about it. 

So unfortunately the issue is a bit more complex

**Comment by markri** [comment]
Ok, just edited the firewalld.rb locally. As it turns out 

`firewalld_command("--zone=#{query_zone} --query-rich-rule=#{rule}") == 'yes'`

needs to be changed to

`firewalld_command("--zone=#{query_zone} --query-rich-rule='#{rule}'") == 'yes'`

In order to prevent the rule to be split up into extra arguments. That's all. I just created a PR for this
https://github.com/chef/inspec/pull/2455
