### ISSUE TITLE
Your version of InSpec is out of date! after upgrade

### ISSUE THREAD

**Issue by pinterl** [inspec/inspec#2396]
### Description

I have upgraded InSpec on my Mac. After the successful install and reboot, I still get the message:

> $ inspec version
> WARN: Unresolved specs during Gem::Specification.reset:
>       rake (>= 0)
> WARN: Clearing out unresolved specs.
> Please report a bug if this causes problems.
> 1.36.1
> 
> Your version of InSpec is out of date! The latest version is 1.48.0.

### InSpec and Platform Version

Installed inspec-1.48.0-1.dmg
Mac OS 10.12.6.

### Replication Case

I had InSpec version 1.36.1, downladed inspec-1.48.0-1.dmg and installed it.
After the successful install and reboot I still get the same message.

**Comment by jerryaldrichiii** [comment]
@pinterl interesting issue,

Could you put the output of the command: `which inspec` here?

**Comment by pinterl** [comment]
@jerryaldrichiii 
$ which inspec

> /Users/MY_USERNAME/.chefdk/gem/ruby/2.4.0/bin/inspec

**Comment by jerryaldrichiii** [comment]
@pinterl Ah, I see the issue.

Since you have ChefDK installed, the version of InSpec that is shipped with it is taking precedence. ChefDK bundles tools together to ensure functionality.

I would recommend you either wait for the next ChefDK release or use the ChefDK from the  `current` channel. https://downloads.chef.io/chefdk/current

**Comment by pinterl** [comment]
@jerryaldrichiii Thank you so much for the info. So it looks like there is no need to install InSpec separately, I can just delete the InSpec folder from "/opt" and update ChefDK only in the future. It would be nice to state this on the InSpec download page because I guess most or all InSpec users already have ChefDK installed on their workstation.

**Comment by jerryaldrichiii** [comment]
@pinterl Actually, I was surprised to learn that a significant number of people use InSpec without Chef or the ChefDK.

After switching to this role, I don't even have the ChefDK installed anymore :smile:

**Comment by jerryaldrichiii** [comment]
Mind if I close this issue to keep our backlog clean?

**Comment by pinterl** [comment]
Thank you @jerryaldrichiii, please close the issue.
