### ISSUE TITLE
executing profiles from git on remote server throwing a error

### ISSUE THREAD

**Issue by reddeppas** [inspec/inspec#2406]
### Description

When i execute profiles from http://github.com/repo/profile  on remote server . 

inspec exec $git_url --backend ${protocol} --user '${ad_domain}\\${ad_username}' --password '${ad_password}' --host ${server} --sudo --format json-min

WARN: Unrecognized content type: text/html; charset=utf-8. Assuming tar.gz 

### InSpec and Platform Version
Inspec version: 1.47
OS: Windows 2008

### Replication Case

please execute from git repo profile on remote server

### Possible Solutions

None so far.

### Stacktrace

[2017-12-20T10:50:57+00:00] WARN: Unrecognized content type: text/html; charset=utf-8. Assuming tar.gz
C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/file_provider.rb:160:in `initialize': not i
n gzip format (Zlib::GzipFile::Error)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/file_provider.rb:160:in `open'

        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/file_provider.rb:160:in `walk_
tar'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/file_provider.rb:139:in `initi
alize'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/file_provider.rb:14:in `new'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/file_provider.rb:14:in `for_pa
th'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/profile.rb:55:in `for_path'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/profile.rb:72:in `for_fetcher'

        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/profile.rb:78:in `for_target'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/lib/inspec/cli.rb:67:in `check'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_comma
nd'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.47.0/bin/inspec:12:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:61:in `load'
        from C:/opscode/inspec/bin/inspec:61:in `<main>'

**Comment by adamleff** [comment]
@reddeppas thanks for submitting this issue.

The telltale warning is this one:

`Unrecognized content type: text/html; `

This indicates to me that the URL you were attempting to use for your profile (`$git_url`) is not GitHub URL but rather something that may act like GitHub (perhaps GitHub Enterprise) or another Git system, like Altassian Bitbucket.

When you supply a URL to InSpec, it will first see if it looks like a github.com URL and then do some translation. If it can't, it will simply try to fetch the URL directly. Whatever comes back from that URL needs to be a `.tar.gz` file or `.zip` file. In this case, the server returned HTML.

If this is a GitHub Enterprise endpoint, try giving InSpec the URL to a .tar.gz release, such at `myhost.com/myrepo/myprofile/archive/master.tar.gz`.

Thanks!
Adam
