### ISSUE TITLE
Formatter/Reporter Overhaul

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2415]
## Goals

* Provide ability to output multiple formats during a single inspec exec
* Provide ability for output to go to different files per format
* Fix the annoying "split the lines after the 2nd word" formatting choice in the CLI formatter for non-control tests
* Eliminate dependence on RSpec formatter classes wherever possible
* Provide a more structured layout in the codebase for code that handles output formatting
  * well-defined inheritence
  * easy-to-find code for a given output generator
* Lay groundwork for additional reporters, such as the ability for InSpec to send direct to Automate

## High-Level Implementation Ideas

* Use the RSpec "Base" formatter to collect test results, populate a hash that can be used by the reporters
* Introduce concept of a "reporter" which will take the place of a "formatter"
  * End state: the `--format` flag will be deprecated/eliminated
* Multiple formatters can be specified on the command line, each with their own output destination
  * Only one should be able to output to STDOUT
* Carry forward the ability to still use the RSpec native "progress", "documentation", and "json" formatters
* The InSpec "json" reporter should not just be a `to_json` on the full hash collected by the RSpec formatter. It should be curated so it remains consistent and can have a schema applied against it if necessary.
* Reporters should be able to take arguments
  * Groundwork for future reporters, such as a FQDN/token to be used to send to Automate
  * This should likely not be in the first slice

## Layout

```
lib/inspec/
├── formatters
│   └── base.rb (contains the RSpec formatter code that builds the data hash for reporter use)
└── reporters
    ├── base.rb (base class for all other reporters)
    ├── cli.rb (each reporter gets its own file with its own logic)
    ├── json.rb
    ├── json_min.rb
    ├── json_rspec.rb
    └── junit.rb
```

### Single default reporter

```
inspec exec myprofile
```

The default `cli` reporter would run, outputting to STDOUT.

### Explicit default reporter

```
inspec exec myprofile --reporter cli
```

The default `cli` reporter would run, outputting to STDOUT.

### Multiple Reporters

```
inspec exec myprofile --reporter cli json:/tmp/output.json junit:/var/opt/jenkins/junit.xml
```

* 3 reporters are executed during the single exec
* The default `cli` reporter outputs to STDOUT
* The `json` reporter outputs to file `/tmp/output.json`
* The `junit` reporter outputs to file `/var/opt/jenkins/junit.xml`

### Explicit STDOUT

```
inspec exec myprofile --reporter cli:- json:/tmp/output.json
```

* The default `cli` reporter outputs to STDOUT
* The `json` reporter outputs to file `/tmp/output.json`

### Invalid multiple STDOUTs

```
inspec exec myprofile --reporter cli json
```

This should generate an error indicating that multiple reports are configured to output to STDOUT and should not be.

### Invalid multiple STDOUTs (explicit)

```
inspec exec myprofile --reporter cli:- json:-
```

This should generate an error indicating that multiple reports are configured to output to STDOUT and should not be.

## Questions/Concerns

* This approach will provide no output during long-running execs until the very end
  * We could solve this by enabling the RSpec "progress" formatter, outputting to STDERR only, enabled by default, disabled with a flag
* How do we handle arguments?
  * Initial idea was only to accept via the JSON config already implemented in InSpec.
  * Do we accept environment variables a la Terraform and Habitat?

## The silly "line-break-after-2-words" thing

Given this test:

```ruby
describe 'a thing with lots of words' do
  it 'tests properly' do
    expect(1).to eq(1)
  end
end
```

... InSpec outputs the following:

```
  a thing
     ✔  with lots of words tests properly
```

... instead of this:

```
  a thing with lots of words
     ✔  tests properly
```

## WIP

Initial work on this is in branch `adamleff/formatter-refactor` and can be used for inspiration, or tossed aside like the pile of garbage it is.

**Comment by megamorf** [comment]
See #2346 #2426 #2166 #2118
