### ISSUE TITLE
passwd  - undefinded method 'filter'

### ISSUE THREAD

**Issue by SDBrett** [inspec/inspec#2417]
### Description

When using passwd to verify unique users and also number of members in a group, I'm getting an error that 'filter' is an undefined method.

### InSpec and Platform Version

CentOS 7
Inspec 1.48.0

OSX
Inspec 1.47.0

### Replication Case

control 'count users' do
  describe passwd.filter(user: 'root') do
    its('count') {should eq 1}
  end
end

control 'count group members' do
  describe passwd.filter(gid: '10') do
    its('count') {should eq 1}
  end
end

### Stacktrace
3_Appliance_UserAccounts.rb:65:in `block in load_with_context': undefined method `filter' for /etc/passwd:#<Class:0x00000002259ed0> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/rule.rb:49:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/rule.rb:49:in `initialize'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/control_eval_context.rb:73:in `new'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/control_eval_context.rb:73:in `block (2 levels) in create'
        from 3_Appliance_UserAccounts.rb:64:in `load_with_context'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/profile_context.rb:148:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/profile_context.rb:148:in `load_with_context'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/profile_context.rb:132:in `load_control_file'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/profile.rb:160:in `block in collect_tests'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/profile.rb:157:in `each'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/profile.rb:157:in `collect_tests'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/runner.rb:89:in `block in load'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/runner.rb:78:in `each'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/runner.rb:78:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/runner.rb:99:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/base_cli.rb:83:in `run_tests'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/lib/inspec/cli.rb:158:in `exec'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/inspec-1.46.2/bin/inspec:12:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/inspec:23:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/inspec:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jerryaldrichiii** [comment]
Thanks for submitting this @SDBrett. It looks like `.filter` should be `.where`.

I also see this is incorrect in our documentation so I will fix that.

**Comment by jerryaldrichiii** [comment]
Digging further I noticed some incorrect behavior related to passing an expression `.where(user: 'root')` vs passing a block `.where { user == 'root' }`.

I will investigate, but in the meantime @SDBrett the solution to your issue is to use the following:

```
describe passwd.filter { user == 'root' } do
  its('count') {should eq 1}
end
```

**Comment by adamleff** [comment]
@jerryaldrichiii It should be `passwd.where { user == 'root }`

You don't want to call `.filter` - it doesn't exist.

**Comment by jerryaldrichiii** [comment]
Gah! I messed it up in my response :face_with_head_bandage: 

@SDBrett, @adamleff is correct it should be:

```
describe passwd.where { user == 'root' } do
  its('count') {should eq 1}
end
```

**Comment by SDBrett** [comment]
Thanks for that, the where statement is working for user
