### ISSUE TITLE
Fail resources when required content is not available

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2418]
Historically, resources have called `skip_resource` when a required component is not available, such as a command or a file not being present. In most cases, it would be more appropriate for this to be a failure since InSpec was not able to complete the assertion. With the proper handling of `Inspec::Exceptions::ResourceFailed`, we can accomplish this now.

Since this would be a breaking change, this should be targeted for a major release bump. Let's see if we can get this in for InSpec 2.0.

**Comment by clintoncwolfe** [comment]
I'm closing as a duplicate - this is covered in much more detail on #3174
