### ISSUE TITLE
specify process supervision type in service resource

### ISSUE THREAD

**Issue by willejs** [inspec/inspec#242]
The Inspec service resource determines the process supervision type based on os release version and uses a single process supervision type to check if a process is running, enabled etc. 

Given many chef cookbooks use many different process supervison tools (init, upstart, runit, etc etc) It would be better if you could override the service_mgmt instance variable to specify the specific one for your service.

Is this a design decision, or could this be changed?

**Comment by chris-rock** [comment]
@willejs The current approach was pragmatic and worked for most cases. e.g. the resource is not able to work properly in cases where you change the default init system.

I would like to have a default, but we should support an override. Ideas are welcome!

**Comment by willejs** [comment]
@chris-rock I think supporting an override would be great. 
On a side note, how does serverspec do this? does it just run the service command?
Id kindof prefer that option too.

**Comment by paulmooring** [comment]
We're hitting this with some omnibus services (we have upstart, sysv and runit services).  I'd love to a see a system that allow me to be explicit when I want, something like:

```
describe service('my_sevice1') do # implicit upstart due to platform
  it { should be_running }
end

describe sysv_service('my_service') do # explicit sysv
  it { should be_running }
end

describe runit_service('my_service') do # explicit runit
  it { should be_running }
end
```
