### ISSUE TITLE
[Documentation] exec formatter docs lacking

### ISSUE THREAD

**Issue by megamorf** [inspec/inspec#2426]
### Description

Running tests with the `inspec exec` subcommand allows you to choose from one of the following formatters:

- cli
- progress
- documentation
- json
- json-min
- junit

However, the following aspects are either not covered in the docs or very difficult to find:

1. what does each formatters output look like
2. how can they be customized (saw a few issues about providing placeholder variables for a custom formatter string)
3. is there a way to use multiple formatters at the same time, e.g. have cli formatter for pretty terminal output but also store the results as json or junit
4. without having looked at the source code I assume that cli is the default formatter since it's not specified here: https://www.inspec.io/docs/reference/cli/

**Comment by clintoncwolfe** [comment]
Hi @megamorf !  Thanks for pointing this out.  @jquick has been working on the reporting / formatting subsystem, and can likely address this.

**Comment by jquick** [comment]
This is correct. https://github.com/chef/inspec/issues/2415 will address this ticket. The default will continue to be the CLI format unless you define otherwise. Look forward to a new batch of docs describing the new "reporter" framework.

**Comment by avishefi** [comment]
Closed by #2617 ?

**Comment by clintoncwolfe** [comment]
Yes, it appears so - see https://www.inspec.io/docs/reference/reporters/
