### ISSUE TITLE
http headers documentation is incorrect

### ISSUE THREAD

**Issue by joegoggins** [inspec/inspec#2453]
### Description

The documentation on https://www.inspec.io/docs/reference/resources/http/ is incorrect.

Capitalization of http headers like `its('headers.Location') { should cmp 'http://foo.com' }` results in a false failure like:

```
  expected: "https://foo.com"
          got:
```

Because `headers.Location` is empty.

The correct way to do it is `its('headers.location') { should cmp 'http://foo.com' }`

### InSpec and Platform Version

1.45.13

### Replication Case

This will pass when the L in location is lower case (like below) and fail if it's upper case.

```
  describe http('https://api.particle.io', enable_remote_worker: true) do
    its('status') { should eq 302 }
    its('headers.location') { should cmp 'https://docs.particle.io/reference/api/' }
  end
```

### Possible Solutions

Update the documentation. Help me understand how I could have done this myself. I looked for an "update the docs" link on the Inspec docs site but couldn't find it.

**Comment by clintoncwolfe** [comment]
HI @joegoggins - thanks for catching this, and diagnosing a fix.  The doc file is located at https://github.com/chef/inspec/blob/master/docs/resources/http.md.erb , near line 84.  To make a change, fork the repo in github, clone it locally, make a branch with a name of your choice ('fix-http-docs', perhaps), make your fix, push the fix, and then open a Pull Request in the github web UI.

Thanks again!

**Comment by adamleff** [comment]
I actually think this needs a code change too.

## with local worker (i.e. Net::HTTP)

```
inspec> http('http://www.google.com').headers
=> {"date"=>"Fri, 12 Jan 2018 00:49:18 GMT",
 "expires"=>"-1",
 "cache-control"=>"private, max-age=0",
```

## with remote worker (i.e. curl)

```
inspec> http('http://www.google.com', enable_remote_worker: true).headers
=> {"Date"=>"Fri, 12 Jan 2018 00:48:30 GMT",
 "Expires"=>"-1",
 "Cache-Control"=>"private, max-age=0",
```

We should downcase the headers we receive with `curl` to match the `Net::HTTP` headers. That would happen around here: https://github.com/chef/inspec/blob/master/lib/resources/http.rb#L200

**Comment by joegoggins** [comment]
Rock on peeps! Thanks for "teaching a man to fish".

While I'd love to dig in and conquer this, I don't think I'll have the bandwidth to do so for a while.

Thus, if someone else wants to "Jump In!" or this update get cooked into a release in das future, please do so!

**Comment by adamleff** [comment]
@joegoggins @clintoncwolfe I've opened PR #2457 to make the headers hash support fetching headers using case-insensitive keys. This should fix the problem.
