### ISSUE TITLE
Key exchange algorithm - 25519 series wanted for ssh

### ISSUE THREAD

**Issue by juju4** [inspec/inspec#2472]
### Description

when user inspec from docker hub registry through ssh, I got an error
```
Transport error, can't connect to 'ssh' backend: SSH command failed (could not settle on kex algorithm)
```
net-ssh supported curve25519-sha256@libssh.org since 4.0 https://github.com/net-ssh/net-ssh/issues/214

### InSpec and Platform Version

1.50.1

### Replication Case

```
docker run -it --rm -v $(pwd):/share chef/inspec exec test.rb -t ssh://user@hostname -i /path/to/key
```
on a server with only above Kex authorized in sshd_config

### Possible Solutions

Ensure net-ssh is recent enough

Aha! Link: https://chef.aha.io/features/SH-2474

**Comment by danielpardorus-allenta** [comment]
Same here! Did you solve it?

Thanks in advance!

**Comment by slauger** [comment]
This is still an issue with inspec 3.0 and it's bundled rubygem net-ssh 4.2.0.

```
-bash# rpm -qa | grep inspec
inspec-3.0.9-1.el7.x86_64

-bash# rpm -ql inspec | grep 'net-ssh*.gem'
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/net-ssh-4.2.0/net-ssh.gemspec

-bash# inspec supermarket exec dev-sec/ssh-baseline -t ssh://intern01.example.tld -i .ssh/id_rsa
Transport error, can't connect to 'ssh' backend: SSH command failed (could not settle on kex algorithm)
```

Example SSH configuration:

```
AddressFamily any
Port 22

#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
AcceptEnv LC_*
Banner none
ChallengeResponseAuthentication no
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
Compression no
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
HostbasedAuthentication no
IgnoreRhosts yes
KexAlgorithms curve25519-sha256@libssh.org
LogLevel VERBOSE
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
MaxAuthTries 2
MaxSessions 10
MaxStartups 10:30:100
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin without-password
PrintMotd no
Protocol 2
Subsystem sftp /usr/libexec/openssh/sftp-server
SyslogFacility AUTHPRIV
UseDNS no
UsePAM yes
X11Forwarding no
```

**Comment by clintoncwolfe** [comment]
Removed docker reference, it's not relevant here

**Comment by clintoncwolfe** [comment]
This issue concerns InSpec's underlying communications library, train.  I'm not a crypto expert, but I suspect it is likely related to https://github.com/inspec/train/issues/353 .  I'd like to move discussion to the train issue if that is correct, please.

**Comment by clintoncwolfe** [comment]
I'm going to close this as a duplicate, as we have this covered on the train repo.

**Comment by james-stocks** [comment]
Re-opening - the last comments in inspec/train#353 suggest that InSpec will need to require the additional gems needed for net-ssh to work with 25519 kex algorithms

**Comment by epcim** [comment]
Any progress?

**Comment by Schwad** [comment]
Hello @epcim and thanks for checking in! I appreciate this issue has been around quite a while but I can say that it has been triaged forward into our developer backlog. Hopefully with our limited bandwidth (and community support) it is something that we can dig into soon. We'll be sure to update here as this happens! 👍
