### ISSUE TITLE
Library file load order is non-deterministic

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2474]
### Description

Load order of the library files within a profile is non-deterministic.  If library files `require` each other, errors may occur if the load order changes, especially across OS's.

I just recently observed this effect after upgrading to Mac OS High Sierra; prior to that, the file list was sorted alphabetically by the filesystem, but now it appears to be in random (but consistent) order.

### InSpec and Platform Version

Inspec 1.48.0, 1.52.1, and master (as of this writing) were all tested.  1.48.0 and 1.51.1 bisect the #2428 dependency chaining issue.

OS: Mac OS High Sierra, 10.13.2

### Replication Case

Try to run the inspec-aws resource pack integration tests.  On MacOS High Sierra, the inspec testing portion failed with a load order issue.  It's possible it would not fail for someone else, due to "lucky" filesystem list order.  In the stacktrace below, `aws_aaa_shim.rb` should have loaded before `aws_cloudwatch_log_metric_filter.rb`.

### Possible Solutions

Sort the file list before loading library files.  PR imminent.

### Stacktrace

```
[cwolfe@lodi inspec-aws]$ be rake test:aws:run:default
----> Run
AWS_PROFILE=inspec-aws-test-default bundle exec inspec exec /Users/cwolfe/sandbox/inspec/inspec-aws/test/integration/default/verify --attrs /Users/cwolfe/sandbox/inspec/inspec-aws/test/integration/default/.attribute.yml
bundler: failed to load command: inspec (/Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/inspec)
NameError: uninitialized constant #<Class:0x00007f914a11c5f0>::AwsCloudwatchLogMetricFilter::AwsResourceMixin
  libraries/aws_cloudwatch_log_metric_filter.rb:24:in `<class:AwsCloudwatchLogMetricFilter>'
  libraries/aws_cloudwatch_log_metric_filter.rb:1:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec/lib/inspec/profile_context.rb:156:in `instance_eval'
  /Users/cwolfe/sandbox/inspec/inspec/lib/inspec/profile_context.rb:156:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec/lib/inspec/profile_context.rb:145:in `load_library_file'
  /Users/cwolfe/sandbox/inspec/inspec/lib/inspec/profile_context.rb:132:in `block in load_libraries'
<--snip-->
```

Here's the OS-provided order I saw, at the [library loader](https://github.com/chef/inspec/blob/master/lib/inspec/profile_context.rb#L118):
```
[115, 124] in /Users/cwolfe/sandbox/inspec/inspec/lib/inspec/profile_context.rb
   115:     def load_libraries(libs)
   116:       lib_prefix = 'libraries' + File::SEPARATOR
   117:       autoloads = []
   118:
   119:       require 'byebug'; byebug
=> 120:       libs.sort_by! {|l| l[1] } # Sort on source path so load order is deterministic
   121:       libs.each do |content, source, line|
   122:         path = source
   123:         if source.start_with?(lib_prefix)
   124:           path = source.sub(lib_prefix, '')
(byebug) pp libs.map { |l| l[1] }
["libraries/aws_cloudwatch_log_metric_filter.rb",
 "libraries/aws_iam_users.rb",
 "libraries/aws_vpcs.rb",
 "libraries/aws_iam_role.rb",
 "libraries/aws_s3_bucket.rb",
 "libraries/aws_cloudwatch_alarm.rb",
 "libraries/aws_iam_access_keys.rb",
 "libraries/aws_iam_user.rb",
 "libraries/_aws.rb",
 "libraries/aws_ec2_instance.rb",
 "libraries/aws_iam_access_key.rb",
 "libraries/aws_vpc.rb",
 "libraries/aws_iam_root_user.rb",
 "libraries/_aws_connection.rb",
 "libraries/aws_aaa_shim.rb",
 "libraries/aws_ec2_security_groups.rb",
 "libraries/aws_sns_topic.rb",
 "libraries/_aws_resource_mixin.rb",
 "libraries/aws_iam_password_policy.rb",
 "libraries/_aws_backend_factory_mixin.rb",
 "libraries/aws_ec2_security_group.rb"]
```

**Comment by samcornwell** [comment]
This seems like a non-issue.  Why don't resources just `require` the modules they need?  My PR in inspec-aws fixes the dependency issue in inspec-aws on my machine.  I had the same dependency problem pop up when I upgraded to High Sierra.

chef/inspec-aws#199

**Comment by aaronlippold** [comment]
@samcornwell I think both approaches have a place, sorting the library load order helps us get a handle on the semi-random load order but 💯 agree that just making it standard practice to `require _aws` at the start of the resources is the safest solution.

**Comment by clintoncwolfe** [comment]
Keep in mind this is the inspec core repo, not inspec-aws.  Any resource pack author who relies on libraries will want to be able to reason about the load order.  Typically in a ruby project, you have a single point of entry - a Thor command file, or a top-level gem library that then selects files as needed, possibly auto-loading.  Inspec core is peculiar in that regard as it insists all library files (in a resource pack) be in one flat directory, and all files will be loaded - in an apparently non-deterministic way.  That makes it hard to reason about what will happen when, and defeats some common approaches to lazy loading.

inspec-aws is in an odd position.  It's about to be merged into inspec core (in the next few weeks), at which time the non-resource library files will be moved to the inspec core' `lib` area.  We may add some lazy loading at that point; the `aws-sdk` gem (regardless of version) is heavyweight, and since most inspec users won't be using the AWS resources, we'd like to avoid loading them if possible.  

I agree there are workarounds to this.  I'm not sure what the final approach will be; it may very well involve requiring the AWS facilities from every aws resource.  For now, I think sorting the library file list does no harm, and helps in some cases.
