### ISSUE TITLE
inspec.io docs do not use syntax highlighting

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2480]
### Description

The inspec.io site has a lot of ruby code in code blocks that have not specified that they are ruby. When I made a change to one of those pages to add a language to the code block it correctly identified the syntax but there is no stylesheet associated with the site to properly display Ruby syntax.

### Examples

[Docs: Apache Conf](http://localhost:4567/docs/reference/resources/apache_conf)

### Possible Solutions

- [ ] Choose / create a pygments stylesheet
- [ ] Update all the four-space indented code blocks

**Comment by adamleff** [comment]
Great suggestion - logged as a feature request for our backlog.

**Comment by burtlo** [comment]
I opened a PR. Since then the new site rolled out with highlights.js to handle the styles. I'll call this complete.
