### ISSUE TITLE
Set variable from within describe block

### ISSUE THREAD

**Issue by lorenzbausch** [inspec/inspec#2490]
### Description

I'm trying to test email dispatching and delivery with Exim on a linux target. To do so I would like to trigger an email and save the filename containing the mail to a variable.
This variable holding the filename can then be used for other tests.

### InSpec and Platform Version

InSpec: `1.51.0` running with Docker on Debian 9

### Replication Case
To do so, I wrote a control which contains two `describe` statements.

The first `describe` statement calls a `command` which triggers the mail dispatching and checks the exit code.
The second `describe` tries to find the sent mail. Since the maildir format is used a simple `command` calling `grep` does the trick to find the correct filename.
Unfortunately I'm stuck here.
Since the filename changes on every test run I'm wondering if I could save the filename to a variable and then use it for subsequent tests. E.g. checking file content, mail headers etc.
In my tries variables defined from within `describe` blocks were not available for other `describe` statements.

Is this a feasible approach? Or are any other ideas for other solutions?

**Comment by adamleff** [comment]
@lorenzbausch I think you're going to find this type of testing rather fragile and subject to race conditions. Depending on the resource, InSpec may do some work / execute some commands as the profile is loaded in and evaluated before it even starts "testing" your `describe` blocks. And when one test makes a change to a system that is then tested via another test, InSpec may work faster than the application being tested.  For example, InSpec may try to look at the resulting mail file before your MTA has a chance to spool to mail to disk.

However, if you really want to go down this path... 😄  ... just define your variables outside of your `describe` blocks. Assuming that the STDOUT of the sending command is the name of a file to check...

```ruby
send_command = command('/path/to/send/command')

describe send_command do
  its('exit_status') { should cmp 0 }
end
describe file(send_command.stdout.strip) do
  its('content') { should match(/some regex here/) }
end
```

I don't know more about your particular test scenario, but this should hopefully give you some options to pursue.

Thanks!
~Adam

**Comment by lorenzbausch** [comment]
@adamleff Thanks for your quick and detailed reply. I will try your alternative approach, it sounds promising and more reliable.
