### ISSUE TITLE
undefined method `architectures' for System Package

### ISSUE THREAD

**Issue by Wolfsrudel** [inspec/inspec#2503]
[root@c-two-mysql-sandbox-01 bin]# /usr/bin/inspec -v                                                                                                                                                                                        
1.51.2
[root@c-two-mysql-sandbox-01 bin]# /usr/bin/inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform: oracle
    OS family: redhat
    OS release: 7.4

inspec> describe package('compat-libstdc++-33') do
inspec>   its('architectures') { should include 'x86_64' }
inspec>   its('architectures') { should include 'i686' }
inspec> end  

Profile: inspec-shell
Version: (not specified)

  System Package
     ∅  undefined method `architectures' for System Package compat-libstdc++-33:#<Class:0x0000000000e56320>
     ∅  undefined method `architectures' for System Package compat-libstdc++-33:#<Class:0x0000000000e56320>

Test Summary: 0 successful, 2 failures, 0 skipped

Also `help` isn't mentioning the new `architectures`:

inspec> help package
Name: package

Description:

Use the package InSpec audit resource to test if the named package and/or package version is installed on the system.

Example:

describe package('nginx') do
  it { should be_installed }
  it { should_not be_held } # for dpkg platforms that support holding a version from being upgraded
  its('version') { should eq 1.9.5 }
end
    

Web Reference:

https://www.inspec.io/docs/reference/resources/package

**Comment by adamleff** [comment]
The “architectures” feature is implemented on the `packages` resource (plural), not the `package` resource. Can you please try that instead and report back?

**Comment by Wolfsrudel** [comment]
Oh man, sorry for that. My fault. :) Now it's working as designed.
