### ISSUE TITLE
check if a registray key exist in only_if

### ISSUE THREAD

**Issue by JazJas** [inspec/inspec#2531]
### Description
This is not a bug but rather a simple question.

I want to perform a test only if a given registray key does NOT exist.

Here is my sample code:
  only_if do
    not registry_key('HKLM\SOFTWARE\Policies\blahblah_key').exist?
  end
  describe blahblah do
    blahblah
  end

However, it appears “not registry_key('HKLM\SOFTWARE\Policies\blahblah_key').exist?” always return true regardless of whether there exists the key or not.

Can anyone tell me whether the syntax is correct, and what is the correct way to check the existance of a key?

Many thanks.
### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

NA

**Comment by jquick** [comment]
Hey @JazJas! I think you actually want the resource 'exists?' instead of the ruby exist? function. something like this should work:
```
only_if do
  not registry_key('HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power').exists?
end

describe command('whoami') do
  its(:stdout) { should match(/jquick/) }
end
```

**Comment by jquick** [comment]
Hey @JazJas, im going to close this issue. If your still having issues we can reopen this. Thanks!
