### ISSUE TITLE
document new inspec reporters

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#2546]
### Description

With #2464  we implemented #2415 but we have not documented the behavior properly. I think it could be easily its own reporter section, especially since we plan to add more reporter. It should be referenced here https://www.inspec.io/docs/reference/cli/ 

### InSpec and Platform Version

latest

### Replication Case

n/a

### Possible Solutions

document the cli

**Comment by megamorf** [comment]
See #2426 for additional feedback
