### ISSUE TITLE
Reporting to Automate

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#2547]
### Description

At this point, InSpec is not able to report to Automate standalone. At this point, InSpec needs to be embedded into Chef https://github.com/chef-cookbooks/audit to be able to report to Chef Automate.

With the introduction of #2464 we have the capability to move the reporter implementation from the audit cookbook to InSpec 2.0. This would have the following benefit:

- audit cookbook becomes simpler and easier to maintain
- `inspec` can report standalone to Chef Automate

In order to make this work, we need to:
- generate deterministic node uuid or fallback to Chef's entity uuid if present
- add some additional fields to our report, see https://github.com/chef-cookbooks/audit/blob/master/libraries/reporters/automate.rb#L101-L107
- security token to talk to automate, see https://docs.chef.io/data_collection.html

```
data_collector['root_url'] = 'https://my-automate-server.mycompany.com/data-collector/v0/'
data_collector['token'] = 'TOKEN'
```

Once we have a first iteration of this available, we need to define:
- moving to json-min or Protobuf based transport protocol to send data more efficient
- split profile metadata from report results
- do not send skipped result for operating system skips (since the profile does not apply)
- above two improvements are especially important for aggregated meta-profiles

### InSpec and Platform Version

Inspec 2.x

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

**Comment by jquick** [comment]
## Output
new automate report (json + manditory fields):
```
type: 'inspec_report'
node_name: $(hostname -a) # this will only be used as a fallback
node_uuid: platform.uuid #new on train
report_uuid:  node_uuid + timestamp
end_time: Time.now.utc.strftime('%FT%TZ')
```

Optional (ONLY set for non-chef clients). These will be set either via json-config or a config file:
```
environment: 
role:
recipes: 
```

----

## Input 
fields for the new report:
**Note** these fields will be in their own json "automate-report" section
Mandatory fields via json-config:
```
root_url: 'https://my-automate-server.mycompany.com/data-collector/v0/'
token: token
```

Optional fields via json-config:
```
node_uuid: uuid # this is a override automate can send if they have already crafted one
automate_config_path: # path to the automate config with node_name/env/role/recipes
node_name: # if not using the config 
environment: # if not using the config
role: # if not using the config
recipies: # if not using the config
```
