### ISSUE TITLE
Port resource returns arrays

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#256]
process, pid and protocol for port all get compared to an array instead of string/number causing weirdness like this

```
Port  22 pid should eq "957"
    Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

      expected: "957"
           got: [957]
```

Thanks for reporting Thomas Cate

**Comment by chris-rock** [comment]
I reviewed the implementation and the documentation. The challenge with the port resource is that is applies to all available ip addresses on the machine. From my point of view we should change the tests to reflect this behavior. This would look like the following:

```
# test port 22 on all IP addresses
describe port(22) do
    it { should be_listening }
    its('protocol') { should include('tcp') }
 end
```

In addition, we may think to extend the port variable with an IP parameter. This would enable us to just return one value instead of an array. e.g. 

```
# test port 22 for a specific IP address
describe port('0.0.0.0', 22) do
    it { should be_listening }
    its('protocol') { should eq 'tcp' }
 end
```

@thomascate @jjasghar @arlimus What do you think?

**Comment by thomascate** [comment]
I like this change. Thinking about this, people are going to be concerned about what IP things are listening on. So this would solve for "Make sure MySQL is only listening on localhost" etc.
