### ISSUE TITLE
Document IAM permissions needed for AWS resources

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#2614]
All AWS resources need IAM permissions to use them. We need to make sure that they are documented or referred to AWS documentation that states them.

Since nearly all InSpec resources use the AWS client API (as opposed to the REST API), the method names directly relate to the AWS Action needed.  So, this should be straightforward, if tedious.

In the meantime, you can use a service user with the ReadOnlyAccess (`arn:aws:iam::aws:policy/ReadOnlyAccess`) policy; that gives global read-only permission.

**Comment by clintoncwolfe** [comment]
attn: @vjeffrey

**Comment by jquick** [comment]
This is done.
