### ISSUE TITLE
Dynamic reporter error categories 

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#2615]
From @aaronlippold:

For the labeling of ‘critical’, ‘major’, ‘minor’ - we will need a way to ‘pass in’ a new category matrix. i.e. in the IC/MIL space - 1.0 would be ‘critical’, 0.0 is N/A and High >= 0.7, Medium = 0.6 - 0.4, Low <= 0.3.

I think we will find very quickly that ‘hard coding’ these will lead us to issues we could address fairly easily.

We end up having to parse the json data, check controls for impact 0.0, etc and do a translation for different labeling systems between agencies and such. IC / DOD use a mix of CAT1, CAT2,... or critical, high, med, low etc. Gov/Fed ( non-military ) uses high, med, low, na etc. Let’s make it easy to support 🙂

The use case is to support ‘Inherited Controls’ ( controls handled by someone else ) in dependent profiles the ‘top’ and ‘bottom’ of the impact are reserved for the logic cases of Critical and N/A controls and how we report and transform the data to support authorization decisions.

My suggestion is - we add the ability to ‘set’ these in the inspec.yml file as something like:

  - "critical" : [1.0]
  - "high": [0.7,0.9]
  - "medium" : [0.4,0.6]
  - "low" : [0.1,0.3]
  - "NA": [0.0]
We could also have a defaults setting which uses the base settings you have ‘hard coded’. If I just wanted to add in ‘NA’ as an example.

  - NA: [0.0]
#2487 in the formatter/base.rb -> L97-L140 is what we would need to make a bit more dynamic.
We will aslo want to update the reporters/cli.rb which has the same.

It would be useful for us to add a flag to the cli’s in general to say --report=failed or --report=skipped or --report=high or --report=critical,major such that it would only report out the controls with the category in the given class. For the use case where Joe Blow is working on building the ‘hardening’ - it can make it easier to iterate on the work.

The default case is of course --report=all

**Comment by adamleff** [comment]
I think this is too much for a single feature enhancement ticket and would suggest breaking it down.

Any changes to the way impacts are mapped to severity levels should be written up as an RFC with actual user stories / use cases. See a sample RFC template in the chef/chef-rfc project that would work well. I'll make my comments there once it's written up, but off the cuff, having this setting be in the profile is a bad idea given that InSpec can run multiple profiles and a single run shouldn't have different interpretations of impact scoring based on profile.

The ability for InSpec to only report on certain severity levels is a rather dangerous idea given that we'd be eliminating transparency in what InSpec actually executed. I'm :-1: on that personally as I think it's reasonable for someone to consume the JSON data and filter out the data they care about with tools like `jq`, but that should be a separate RFC given that it's a fundamental change to the way InSpec functions.

**Comment by aaronlippold** [comment]
@jquick Should I add in the use cases here? Thanks.

**Comment by jquick** [comment]
With the new directive of removing critical/major/minor from inspec all together makes this kind of a mute point. With inspec 2.0 we only have pass/fail and serve up the impact so whoever digests them can formulate their own.

**Comment by aaronlippold** [comment]
I hope to reopen the discussion on this at the sync call today. @jquick it would be great if you could join us.

**Comment by clintoncwolfe** [comment]
#3359 added the ability to use strings as impacts.
#3017 discusses the idea of having more, possibly finer-grained test outcomes.

I'm going to close this; if you feel more should be covered here, please re-open.  Thanks!
