### ISSUE TITLE
Service state not detected correctly on Amazon Linux 2.0

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#2639]
I suspect we're hard coding things when we're on Amazon Linux, but Amazon Linux 2.0 is systemd. 

https://travis-ci.org/chef-cookbooks/chef-client/jobs/341544040

**Comment by kekaichinose** [comment]
@clintoncwolfe I'm confused by the ref to #2901. Wouldn't that have resolved this issue?

**Comment by Vasu1105** [comment]
Closing this issue as fixed in #2901. Verified the same.
