### ISSUE TITLE
etc_group not implemented for centos

### ISSUE THREAD

**Issue by atomic111** [inspec/inspec#266]
1) /etc/group The `etc_group` resource is not supported on your OS.
     # Not yet implemented
     # /home/user/.gem/ruby/2.2.0/gems/inspec-0.9.2/lib/inspec/runner.rb:106

you can test it with "kitchen verify default-centos-64" in [chef-os-hardening](https://github.com/hardening-io/chef-os-hardening) project

**Comment by chris-rock** [comment]
@atomic111 I can confirm this is a bug. Thank you very much for reporting
