### ISSUE TITLE
Use SemVer to provide more stable versions

### ISSUE THREAD

**Issue by lehn-etracker** [inspec/inspec#2660]
### Description

We are using InSpec within our CI/CD pipeline with jenkins and junit reporting. Our Version pinning for inspec was pinned to version 1.51.0 and allowed all patch upgrades.

With release of inspec 1.51.6 the new reporter replaced the old one and broke our configuration.

#### ruby gems
  * inspec (1.51.18)
  * kitchen-inspec (0.20.0)
  * kitchen-sync (2.2.1)
  * kitchen-vagrant (1.2.1)
  * test-kitchen (1.19.2)
  * rspec (3.7.0)
  * rspec-core (3.7.1)
  * rspec-expectations (3.7.0)
  * rspec-its (1.2.0)
  * rspec-legacy_formatters (1.0.1)
  * rspec-mocks (3.7.0)
  * rspec-support (3.7.1)
  * rspec_junit_formatter (0.2.3)

#### system

  * Linux Debian Jessie

### Replication Case

- setup CI/CD environment with jenkins/junit/test-kitchen and inspec 1.51.0
- use settings:
-- format: junit
-- output: test/results/%{platform}_%{suite}_inspec.xml
- all reports are written into test/results/%{platform}_%{suite}_inspec.xml
- update InSpec gem to latest version (1.51.18)

Now, inspec reports are no more written into test/results/%{platform}_%{suite}_inspec.xml.

### Possible Solutions

If InSpec whould use [SemVer](https://semver.org/) the user has the power to decide when to get new features and breaking changes, without missing bugfixes without manual updates.

**Comment by jquick** [comment]
Thanks @lehn-etracker for this report! We will look into this issue.

**Comment by jquick** [comment]
Thanks @lehn-etracker - This should be resolved in both v1.51.21 and v2.0.17. Depending if you want to upgrade to 2.0 or not.

**Comment by jquick** [comment]
To comment about the SemVer. We do try to keep all breaking changes to a major SemVer release version like 2.0. This bug you uncovered in a few 1.x versions was not suppose to be breaking and was a regression. Please reach out if you run into any more issues!

**Comment by lehn-etracker** [comment]
@jquick We've tried out v1.51.21. There is still a little issue with creating the output path directory.

v1.51.0 did create output path, v1.51.21 doesn't

It would be perfect if next patch release of v1.51 whould create output directories again.

**Comment by jquick** [comment]
@lehn-etracker - Thanks for that feedback. I have created https://github.com/chef/inspec/issues/2771 to resolve this issue.
