### ISSUE TITLE
Example profiles for AWS and Azure

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#2663]
### Description

We need to generate some example profiles and set them into the examples directory. We can use most of @clintoncwolfe stuff here for aws: https://github.com/clintoncwolfe/inspec-cloud-demo

For azure you will probably want to pull out a bit from the integration tests/terraform.

**Comment by aaronlippold** [comment]
Hi,

Rony has the example profile and terrafrom for the CIS AWS benchmark
already. So we are good there.

A

--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
