### ISSUE TITLE
Add configuration of multiple targets

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#268]
... including importing targets from file

**Comment by AnotherNerdHere** [comment]
this would be very valuable to what I'm doing.

**Comment by supertylerc** [comment]
This would be lovely.  Right now, my only option seems to be to write a wrapper script that somehow knows which servers run which things, then shell out to InSpec to run against those things in serial.

**Comment by theist** [comment]
The only way to specify targets is CLI parameters?  It will be useful to have some DSL dedicated to it or some way to use a chef query to specify targets. I'll love to do a `knife inspec "query" -x user test_file.rb` and receive a report for each server in the query

**Comment by adamleff** [comment]
Hi, all! This issue is currently out-of-scope for InSpec. We have decided to optimize InSpec for the scanning of a single target (whether that be a host or another non-host platform) and currently have no plans to support the ability to scan multiple targets with a single InSpec command. Thank you!
