### ISSUE TITLE
inspec shell - asking a resource its available methods should be more straighforward

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2688]
### Description

When you enter InSpec shell you have some really great helper methods to get you started: `help`; `help resources`; and `help RESOURCE`.

However, if I want to explore the available methods on a resource it is rather cumbersome.

Becuase they are Ruby objects, I suggested:

```
inspec> file('/tmp').methods
=> [:skip_resource,
 :inspec,
 :resource_skipped?,
 :resource_failed?,
 :resource_exception_message,
 :fail_resource,
 :check_supports,
 :size,
...
```

Looking past the problem that its Array of Symbols and how you might 'send one of these messages' to the object it's still cluttered with methods that are related to an invocation through a test suite. By default, the `methods` method will show all the methods defined on the current object and provided by every ancestor. That's a lot of history! The `methods` method can take one optional parameter to filter the returned list of methods if you specify `false`

```
inspec> file('/tmp').methods(false)
=> []
```

An empty Array! This is because the file resource that the user is interacting with is really a dynamically generated subclassed resource coming out of the InSpec resource registry. Alright, well that means I need to say the following:

```
inspec> file('/tmp').class.superclass.instance_methods(false)
=> [:size,
 :to_s,
 :path,
 :source,
 :file,
 :directory?,
 :exist?,
 :readable?,
 :writable?,
...
```

That's the list I want but that's a rather obtuse way of going about asking for that information. I am hesitant to suggest it based on all the things that have to be explained.

### Possible Solutions

* Add a method to the dynamically generated class that performs the above operation to simplify retrieving this information. Though, I would be worried about adding another method. It also doesn't solve the problem of an Array of Symbols.

* Have the `help RESOURCE` return that information as well. It seems like this helper method could invoke that method, join the elements, and then append it to the output. Though this doesn't take into account methods that have parameters and that might leave a bad taste in a person's mouth when they start bumping up against the incorrect number of args 0 for 1 messages.

* Update the resource domain-specific language to identify these methods with parameters and usage. Then dynamically build a description from those items. Pursuing this approach requires a lot more conversation. There are some other benefits here as well. As it would probably mean you could develop documentation from the resources simply by loading the resource up.

I leave you with no good options but I feel the usability of InSpec Shell would be greatly improved with an enhancement in this area.

**Comment by burtlo** [comment]
Haha, oh right. I would probably tell someone to sort them as well. The full command would be ...

```
inspec> file('/tmp').class.superclass.instance_methods(false).sort
=> [:allowed?,
 :basename,
 :block_device?,
 :character_device?,
 :contain,
 :content,
 :directory?,
 :executable?,
 :exist?,
 :file,
 :file?,
 :file_version,
 :gid,
...
```

**Comment by aaronlippold** [comment]
I actually opened an issue on this exact topic over a year ago. Great to see it coming up again. +1 on this for me.

**Comment by aaronlippold** [comment]
It would also help us streamline documentation as well. one of my guys wrote this up for the aws resources https://github.com/rx294/inspec_aws_test_doc_generator which perhaps we could generlize

**Comment by burtlo** [comment]
@aaronlippold, please link the issue to this one. I would enjoy seeing the conversation that entailed.

Show this crazy thing to your guy: https://github.com/burtlo/inspec_docgen/blob/master/property_finder.rb
Which generated the README: https://github.com/burtlo/inspec_docgen/blob/master/README.md

It doesn't handle filter tables correctly because I didn't understand them until I finished it. But it has the potential when combined with a little more metadata to generate some real examples while not having to re-map all the 'properties' found on a resource again in the YML.

BTW, I in no way endorse this as a solution for property/matcher finding. It was an interesting experience to explore how hard it was to try and document InSpec resources.

**Comment by jquick** [comment]
I like this idea, but its going to be hard sometimes. This wont pick up filter table bindings or the dynamic ones we create like for azure.

So whats the use case here? wanting to know what you can do with a resource from the shell instead of going to the docs?

**Comment by burtlo** [comment]
@jquick a few instances where I see value:

* I am using an older version of InSpec and the docs site displays the latest release.
* I am using the current version of InSpec and find that it does not behave as the documentation describes.
* I am using the current version of InSpec and the docs are incomplete. Currently, the documentation is generated and maintained by humans in the community.
* I am using InSpec in an air-gapped environment.

**Comment by burtlo** [comment]
As minor updates to resources are merged there are no tests that ensure that the documentation passes or includes those changes. Humans intervention is required to request those changes and that creates a scenario where the documentation is going to fail. Documentation is an external resource and external resources require coordination with the release of every product.

**Comment by burtlo** [comment]
Within InSpec Shell you execute `help RESOURCE` and that resource will provide you a link to the docs page which is a great start of connecting those resources. I am a proponent of tools that teach and this is a great first step. That next step feels like properties that when defined are self-documenting.

**Comment by burtlo** [comment]
I think the use of `method_missing` in InSpec resources is an incorrect design choice. I remember when I first started working with Chef you could pause the execution with Pry and examine the available methods within the recipe context. You could see every helper method, but you were unable to see any of the available resources because they were implemented behind a similar dynamic system like `method_missing`. It was changed and now the resources will appear during a paused execution in the recipe context. 

Data that dynamically creates methods on an object can be done even in the case of a singleton. I would strongly am against a wide open interface like `method_missing`. I'm sure there are situations where this could be the right choice but in most cases I think it should be removed.

FilterTable accessors do appear as methods but not the bindings. Ultimately I think those bindings should also be present as well on the InSpec resource. The same way that `Inspec::Resource.registry` maintains a list of resources I believe an individual resource could maintain a list of the properties that it defines.

**Comment by clintoncwolfe** [comment]
(I'll be using terminology from the [InSpec Glossary](https://www.inspec.io/docs/reference/glossary/)  here)

My viewpoint, FWIW, is that Ruby-level introspection won't ever be the right answer here.  Properties, matchers, and resource criteria all appear to be methods at the Ruby level; and some of them go through aliasing.  And then you've got method_missing, which I don't like either.  Bleh.

I think it's a DSL problem.  If you want to know the available properties of a resource, the resource source code should declare a method as being a property.  Then we could have an introspection method, for use in the shell, like `properties`.  We could then extend `help RESOURCE` to list the properties, matchers, parameters, and filter criteria.

**Comment by adamleff** [comment]
I'm in 100% agreement with @clintoncwolfe. Ruby magic is the wrong choice for a variety of reasons, mostly due to design choices made within InSpec itself. A more robust DSL for defining resources and their properties will allow this sort of user-facing documentation to be generated in a sane fashion. In fact, the Chef project is doing that very thing with self-documenting custom resources' properties now and are addressing it by enhancing the DSL. I'm :-1: trying to add Ruby magic to do this with our current structure.

**Comment by burtlo** [comment]
https://github.com/chef/inspec/issues/2860
The shadow resource changed in a patch release. The new version of the docs displays the latest. Using InSpec Shell showed me what methods I could really use.

**Comment by clintoncwolfe** [comment]
This feature request has blossomed into an RFC for release 3.  Closing this after linking.
