### ISSUE TITLE
AWS connection region not always required

### ISSUE THREAD

**Issue by dee-kryvenko** [inspec/inspec#2717]
I'm not sure this is still actual after https://github.com/chef/inspec-aws going into 2.0 since it's not in chefdk yet and I can't test. But in chefdk 2.4.22 + master inspec-aws, when using `AWS_PROFILE` or EC2 instance profile or ECS task profile, I'm getting `Failed to complete #verify action: [missing region; use :region option or export region name to ENV['AWS_REGION']] on default-terraform`. This should not be the case as certain credentials types already comes with default region value. I suspect this happens because https://github.com/chef/inspec-aws/blob/master/libraries/_aws_connection.rb#L22 always overrides `region` to `nil` in case both `AWS_REGION` and `AWS_DEFAULT_REGION` were not set.

**Comment by clintoncwolfe** [comment]
Thanks for the report!  Let me give you an update on how it works in inspec 2.0, and then I'll paraphrase what I think you're asking about.

Upon merging to master, we introduced a new way of passing credentials - using the `--target aws://` option.  InSpec 2.0.16 currently supports three forms of this:
1. `-t aws://REGION/PROFILE-NAME` - explicitly specify both region and profile name
2. `-t aws://REGION` - explicitly specify region, take profile from env var `AWS_PROFILE`
3. `-t aws://` - expect region from env var `AWS_REGION` and profile from env var `AWS_PROFILE`

I think what you're saying is that with a properly setup `~/.aws/config` and `~/.aws/credentials`, you can specify the region for a given profile in the config files.  Then you should be able to merely specify the profile name, perhaps via:
4. `-t aws://` with env var AWS_PROFILE set to a profile with an implicit region
5. `-t aws:///PROFILE-NAME` where PROFILE-NAME is the name of a profile with an implicit region.

I'll say at this point that we certainly weren't expecting 4 or 5 to work - anytime I've tried implicit regions using the AWS CLI, it's never worked for me - but if it's important to you, we can look into it.  I suspect this is more ignorance on my part than anything else :)

**Comment by dee-kryvenko** [comment]
Official AWS CLI (and many 3rd party/opensource tooling around it) generally supports something they call default credentials provider chain. Here is some links

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#credentials

If I understood correctly, what you're saying is inspec looking into `--target` and then falls back to environment variables if nothing found. But `~/.aws/config` and `~/.aws/credentials` should absolutely also be honored. Also keep in mind that you might have default profile or EC2 instance profile or ECS task profile (where it should behave like `AWS_PROFILE` is set except that it was not). Generally it is better to delegate auth to `aws-sdk` rather than trying to come up with the own implementation, see https://github.com/aws/aws-sdk-ruby/blob/f857a1f5bbef9036eed2cd154b409444649bb70e/gems/aws-sdk-core/lib/aws-sdk-core/credential_provider_chain.rb#L10. In all that cases region may or may not coming in together with the credentials.

Just to give some background of my specific case, I intended to use it with kitchen, specifically with https://github.com/newcontext-oss/kitchen-terraform. Ideally I think it would be best to somehow pick up a provider from terraform, or at least being able to configure it somewhere in `.kitchen.yml`. I realize it is probably should be raised in kitchen or kitchen-terraform repository, but since I'm already here - do you think inspec 2.0 has everything to allow them to do it on their side?

**Comment by clintoncwolfe** [comment]
To be clear, we're not re-implementing the SDK's credentials loading mechanism, and we do indeed rely (indirectly, using the SDK's facilities) on the config and credentials files.  I think we're (as you said) misbehaving in the case in which no region or profile information is available from env vars or the --target option, and treating that no-creds case as an error, when instead we should be allowing the SDK to attempt a default profile, EC2 instance profile, or ECS task profile authentication.  Instead, we're setting the creds to nil, and that obviously breaks.

As for creds exchange between Terraform and InSpec in a Test Kitchen environment... We are toying with some ideas about improving data exchange between TF and InSpec (regardless of Kitchen).  We currently have various things, such as the AWS InSpec resource integration tests, exposing various things via outputs, running terraform output, then reworking that into a YAML file for consumption as an InSpec attribute file.  We'd like that to mature.

Another option within your Kitchen.yml is that it is an ERB-interpreted file, so you can inject ruby there - including even the AWS SDK if you wished, to interrogate the local creds store, and pass them to both Terraform and InSpec.

**Comment by clintoncwolfe** [comment]
Refs #2560 , rely on instance profile for creds

**Comment by skpaterson** [comment]
Tracking this issue in the new AWS resource pack here:
https://github.com/inspec/inspec-aws/issues/5
