### ISSUE TITLE
Add support for Google Cloud Platform (GCP)

### ISSUE THREAD

**Issue by tpoindessous** [inspec/inspec#2722]
Hi

I make this issue to ask (kindly ;) ) for support of the Google Cloud Platform (GCP).

I see that an project exists in https://github.com/martezr/inspec-gcp

Thanks !

**Comment by clintoncwolfe** [comment]
Hi!  As you mention, there is currently a community member working on a GCP resource pack.  That's a great place to contribute for now.  In the immediate wake of the 2.0 release, we're working on shoring up support on AWS and Azure; but GCP is certainly on our radar.

**Comment by chris-rock** [comment]
This is solved via chef/train#283 Read more about it at https://t.co/y0A7146v44 and https://github.com/inspec/inspec-gcp
