### ISSUE TITLE
InSpec 2.0.17 for macOS 10.13 doesn't work (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by tpoindessous** [inspec/inspec#2727]
### Description

After installing InSpec from macOS 10.13/64bits download, I can't launch inspec in command line, I get an error `Gem::GemNotFoundException`

### InSpec and Platform Version

- macOS 10.13.3
- https://packages.chef.io/files/stable/inspec/2.0.17/mac_os_x/10.13/inspec-2.0.17-1.dmg

### Replication Case

- Download https://packages.chef.io/files/stable/inspec/2.0.17/mac_os_x/10.13/inspec-2.0.17-1.dmg
- Install InSpec
- Launch terminal
- type `inspec`

### Stacktrace

```
/opt/inspec/embedded/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem inspec (>= 0.a) (Gem::GemNotFoundException)
	from /opt/inspec/embedded/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/local/bin/inspec:23:in `<main>'
```

**Comment by jquick** [comment]
Looking into this, for now please just use `gem install inspec` which should work for you.

**Comment by tpoindessous** [comment]
Thanks, I will try it.

I should note that I use rvm :

<17:31:58>[thomas:~]$ which ruby
/Users/thomas/.rvm/rubies/ruby-2.3.0/bin/ruby



Le jeu. 22 févr. 2018 à 16:44, Jared Quick <notifications@github.com> a
écrit :

**Comment by miah** [comment]
Thanks for the report. I'm able to reproduce this locally, and a quick workaround would be putting InSpec at the front of your path:

`PATH=/opt/inspec/bin:$PATH`
