### ISSUE TITLE
Add support for OpenStack

### ISSUE THREAD

**Issue by maxdelorme** [inspec/inspec#2735]
At the moment we have found only https://github.com/andybrucenet/inspec-openstack

Is there plan to add full support for OpenStack ?

**Comment by clintoncwolfe** [comment]
Thanks for the question!  

In the near-term, we're focused on expanding support for AWS and Azure in InSpec core.  GCP and some others are on deck.  At the same time, we're also very interested in helping community members succeed with creating support for the platforms that they are using.  So, we're happy to help with removing obstacles for OpenStack (such as, for example, adding an `openstack://` target to [Train](https://github.com/chef/train), but direct in-core support for OpenStack resources is unlikely in the near term, as far as I am aware.

Thanks!

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
