### ISSUE TITLE
aws_ec2_instance resource find by name should fail the resource if multiple instances match

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2736]
### Description

The use of the name field to find the `aws_ec2_instance` worked correctly in identifying the instance but seems to be problematic when I have instances that are now terminated that share the name.

### InSpec and Platform Version

InSpec 2.0.17, Mac 10.13.13

### Replication Case

I create an instance with the tag Name: 'webserver'. I terminate that instance.

I create a new instance with the same tag Name. I then perform the following work:

When using the `aws_ec2_instance` resource I initially started with the id value.

```ruby
describe aws_ec2_instance('i-0baf58c5558a4909f') do
  it { should be_running }
  its('image_id') { should eq 'ami-d5d7ffae' }
  its('instance_type') { should eq 't1.micro' }
```

I execute a scan for this control.

```shell
$ inspec exec . -t aws://us-east-1

Profile: InSpec Profile (training-aws-security)
Version: 0.1.0
Target:  aws://us-east-1

  EC2 Instance i-0baf58c5558a4909f
     ✔  should be running
     ✔  image_id should eq "ami-d5d7ffae"
     ✔  instance_type should eq "t1.micro"

Test Summary: 3 successful, 0 failures, 0 skipped
```

I change the control to use the tag Name field.

```ruby
describe aws_ec2_instance(name: 'webserver') do
  it { should be_running }
  its('image_id') { should eq 'ami-d5d7ffae' }
  its('instance_type') { should eq 't1.micro' }
end
```

I execute a scan for this control.

```shell
$ inspec exec . -t aws://us-east-1

Profile: InSpec Profile (training-aws-security)
Version: 0.1.0
Target:  aws://us-east-1

  EC2 Instance webserver
     ×  should be running
     expected that `EC2 Instance webserver` is running
     ✔  image_id should eq "ami-d5d7ffae"
     ✔  instance_type should eq "t1.micro"

Test Summary: 2 successful, 1 failure, 0 skipped
```

The results do not show that it is running but does show that it is using the correct image id and instance type.

**Comment by clintoncwolfe** [comment]
Looks like the issue is [here](https://github.com/chef/inspec/blob/master/lib/resources/aws/aws_ec2_instance.rb#L64), in which a tag-based search is executed, then the first result is used.  Current doctrine is for singular resources (like this one) to fail the InSpec resource if more than one AWS Resource matched the search parameters.  

`aws_ec2_instance` needs a rewrite anyway; this might be a good time to do so.

**Comment by deepakmohanakrishnan07** [comment]
I need this to be fixed as well. Is there any workaround. The problem will be solved if we just pick the latest instance (sort by the instances' launch time).

**Comment by skpaterson** [comment]
This is the behaviour in the new InSpec AWS resource pack, but let us know if not:
https://github.com/inspec/inspec-aws/blob/14f7a881f292c32803ba85be6309e93b29fc8966/libraries/aws_ec2_instance.rb#L43
