### ISSUE TITLE
Using the =~ matcher generates a RSpec should deprecation

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2739]
### Description

When I defined an individual test that uses the `=~` matcher a DEPRECATION warning is displayed. I chose this matcher because it will compare Arrays without concern for the order.

As InSpec has long since embraced the `should` method existing on every Object in Ruby it surprised me to see this DEPRECATION appear.

### InSpec and Platform Version

InSpec 2.0.17, Mac 10.13.13

### Replication Case

I want to test that my `aws_ec2_instance` has defined the correct security groups. I define the following control:

```ruby
describe aws_ec2_instance('i-0ab1d729ecb3dea97') do
  it { should be_running }
  its('security_group_ids') { should =~ [ "sg-80b2a6f7", "sg-6dbbaf1a" ] }
end
```

I run a scan with this control against the AWS platform:

```shell
$ inspec exec training-aws-security -t aws://us-east-1

Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from ./controls/aws_ec2_instance.rb:37:in `block (2 levels) in load_with_context'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

1 deprecation warning total

Profile: InSpec Profile (training-aws-security)
Version: 0.1.0
Target:  aws://us-east-1

  EC2 Instance i-0ab1d729ecb3dea97
     ✔  should be running
     ✔  security_group_ids should contain exactly "sg-80b2a6f7" and "sg-6dbbaf1a"

Test Summary: 2 successful, 0 failures, 0 skipped
```

### Possible Solutions

The other possible matchers are too brittle with regard to order. So they cannot be recommended.

```ruby 
  # These all will produce an error when the elements of the Array are not in the same order.
  its('security_group_ids') { should cmp [ sg_web_id, sg_ssh_id] }
  its('security_group_ids') { should eq [ sg_web_id, sg_ssh_id] }
  its('security_group_ids') { should match [ sg_web_id, sg_ssh_id] }
```

Suggest that I order everything:

```ruby
  # This works
  its('security_group_ids.sort') { should match [ sg_web_id, sg_ssh_id].sort }
```

Suggest that I write two test cases:

```ruby
  # This definitely works.
  its('security_group_ids') { should include sg_web_id }
  its('security_group_ids') { should include sg_ssh_id }
```

My feeling is that because the `should` method exists everywhere -- why turn back now! Bury the depreciation for the sake of the cleaner output and support the `=~`. Oh and while we're at it -- add this an example matcher to the [matcher docs](https://www.inspec.io/docs/reference/matchers/).

**Comment by clintoncwolfe** [comment]
My $0.02 is that you are actually running two tests, and (as an auditor who may not know or care what an Array is, and who prefers English-like readability over programmatic structures like `=~`), the preferred way to express your tests would be your last example:

```
  its('security_group_ids') { should include sg_web_id }
  its('security_group_ids') { should include sg_ssh_id }
```

If you have a lot of them to check, and you (or your profile author) doesn't mind a bit of readable Ruby, you can still loop that:

```
describe aws_ec2_instance('i-something') do 
   my_list_of_sgs_i_expect.each do |sg_id|
      its('security_group_ids') { should include sg_id }
   end    
end 
```
That neatly gives you (say) 27 tests if you have 27 security groups to check for, and if one is missing, you'll get a test failure with a clear error (including the sg id in question).  The failure messages from the other approaches, including `=~`, are less clear, I think.

**Comment by burtlo** [comment]
@clintoncwolfe I definitely agree with what you are saying. With that audience in mind, It makes the inspec.io [matchers document](https://www.inspec.io/docs/reference/matchers/) incredibly important to be absolutely clear how each matcher behaves. I do not think that `=~` is the clearest matcher in the toolbox.

InSpec is also an Integration testing tool for engineers. Engineers may find this matcher and prefer to use `=~` instead of some of the alternatives we're talking about here for its succinct nature.

**Comment by jquick** [comment]
I agree here with @clintoncwolfe - We should keep tests on a single layer of abstraction to make it easy to understand IMO.

**Comment by clintoncwolfe** [comment]
I just came across [contains_exactly](https://relishapp.com/rspec/rspec-expectations/v/3-7/docs/built-in-matchers/contain-exactly-matcher) - that seems to do what you want.

**Comment by burtlo** [comment]
Yes, that does work @clintoncwolfe. I'll use that going forward.

But why does `=~` generate a deprecation message?

That makes me think there are other 'matchers' used by the community that may also generate these deprecations.

**Comment by clintoncwolfe** [comment]
As an implementation detail, InSpec is based on RSpec.  I believe `=~` is provided by RSpec, and the RSpec project may deprecate features as it sees fit.

`<RSpec Soapbox>`
InSpec is not RSpec.  InSpec does not generally support arbitrary RSpec features.  On the universal (as opposed to resource-specific) matchers page, the InSpec project documents the matchers that are most commonly used in InSpec.  If a matcher is documented in InSpec, InSpec supports it (and promises not to break it in a semver sense).  If an RSpec matcher is not documented in InSpec, you are of course free to attempt to use it.  
`</RSpec Soapbox>`

If a supported matcher emits a deprecation warning or other unexpected behavior, that is a bug - if you see any, please report them - that would be awesome!

If there are RSpec matchers that you think should be supported in InSpec, that would be a great discussion.  I think you may see different audiences than we on the InSpec team (or at least I) do.

Thanks for all your thoughts on this!

**Comment by burtlo** [comment]
I was mistaken here. I knew that Ruby supported `=~` but it does not function in the same way that it functions within used within the context of `should`.


Is your statement the feeling for the project? Should they be captured here: https://www.inspec.io/docs/reference/inspec_and_friends/#sts=RSpec or https://www.inspec.io/docs/reference/matchers/ ?

Should I use `contains_exactly`?  And if you are still suggesting it should it exist in the list of supported matchers?

**Comment by burtlo** [comment]
Should the example that we are talking about be provided on this page https://www.inspec.io/docs/reference/resources/aws_ec2_instance/?

**Comment by clintoncwolfe** [comment]
Thanks for calling out the need to clarify the InSpec-RSpec relation on the "InSpec and Friends" document.  I've opened a PR with some words to that effect, #2753 .  Those are the viewpoints of the team.

You're free to use `contains_exactly`, or any other RSpec matcher you like.  It is not a _supported_ universal matcher, so if it broke, it's not likely fixing it would be a high priority - or even the InSpec project's responsibility.  Me personally suggesting `contains_exactly` isn't an endorsement, though it does seem to be well-suited in this case.

If _I_ were to add a "set-wise security group check" to `aws_ec2_instance`, I'd use the syntax above:
```
describe aws_ec2_instance('i-something') do 
   my_list_of_sgs_i_expect.each do |sg_id|
      its('security_group_ids') { should include sg_id }
   end    
end 
```
My preference there is mainly about failure messaging, and clarity.  And laziness: we already have the include matcher.

**Comment by jquick** [comment]
I am closing this issue as undocumented RSpec matchers are not supported in InSpec. Thanks for the notes and clarification on the documentation.
