### ISSUE TITLE
Terraform returns a RouteTable id that contains an extra prefix and additional characters

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2740]
### Description

I created a Terraform plan that generates a RouteTable. The resulting output ID for this route table includes an additional prefix and more characters. This may be an error on the part of Terraform as the AWS interface only supports `rtb` followed by 8 hexadecimal characters.

![image](https://user-images.githubusercontent.com/244426/36635223-f4d16078-1976-11e8-9bf8-75d543a4e905.png)

The `aws_route_table` resource correct guards against a String with the prefix ` r-rtb-66f60c1a1080289494`. 

It does NOT correctly guard against a String with more that has more than 8 hexadecimal characters. It will accept `rtb-66f60c1a1080289494` when it should reject it. That makes sense looking at the [regex](https://github.com/chef/inspec/blob/master/lib/resources/aws/aws_route_table.rb#L29) provided in the validation step.

### InSpec and Platform Version

InSpec 2.0.17, Mac 10.13.13

### Replication Case

I created a route table with the following Terraform [plan](https://github.com/learn-chef/inspec-on-aws/blob/master/main.tf). I display the output of the terraform plan:

```shell
$ terraform output

route.internet_access.id = r-rtb-66f60c1a1080289494
...
vpc.id = vpc-c707d7bc
```

I output all this content as JSON and load through a profile file or convert to YAML and load through a profile attributes. When I attempt to verify the RouteTable's existence I am presented with an error:

```ruby
content = inspec.profile.file("terraform.json")
params = JSON.parse(content)

route_table_id = params['route.internet_access.id']['value']

describe aws_route_table(route_table_id) do
  it { should exist }
end
```

I run a scan and see a failure with the `aws_route_table`:

```shell
$ inspec exec training-aws-security -t aws://us-east-1

Route Table
     ×  aws_route_table Route Table ID must be in the format "rtb-" followed by 8 hexadecimal characters.

Test Summary: 0 successful, 1 failure, 0 skipped
```

### Possible Solutions

Because the route table id that is coming in from Terraform does not appear to be in the format supported by InSpec `aws_route_table`.

I could [open an issue](https://github.com/hashicorp/terraform/issues/17427) against Terraform to ask them why it exists and if it is a bug.

I could remove the prefix `r-` and additional hexadecimal characters by building a sub-String from the third character (index 2) to the 14 character (index 13). Though, this solution is dangerous as it could lead to problems later if Terraform changed the format.

```ruby
content = inspec.profile.file("terraform.json")
params = JSON.parse(content)

route_table_id = params['route.internet_access.id']['value'][2..13]

describe aws_route_table(route_table_id) do
  it { should exist }
end
```

I could find the ID within this longer string using a regular expression:

```ruby
content = inspec.profile.file("terraform.json")
params = JSON.parse(content)

route_table_id = params['route.internet_access.id']['value'][/rtb-[a-f0-9]{8}/]

describe aws_route_table(route_table_id) do
  it { should exist }
end
```

InSpec's `aws_route_table` resource could be modified to perform the above regular expression on the given String to exact the correct sub-string. It probably should be modified to generate an error based on the current regex being too permissive with longer Strings of characters.

**Comment by clintoncwolfe** [comment]
Hi @burtlo!  Thanks for all the testing and issue reports over the last few days.

As mentioned on the [Terraform issue](https://github.com/terraform-providers/terraform-provider-aws/issues/3515) you opened, r-rtb-66f60c1a1080289494 is an identifier Terraform creates to refer to a specific route on a route table, in lieu of an identifier being created by AWS.

If you want to get a route table identifier,  you should export an `aws_route_table.NAME.id`, not `aws_route.NAME.id`.

Based on that, I'm closing this; I've opened a separate issue for the ID length validation bug.
