### ISSUE TITLE
inspec check doesn't produce warning for leading zero's in version

### ISSUE THREAD

**Issue by TheLunaticScripter** [inspec/inspec#2757]
### 🎛 Description

This a 🐛 bug report

When an inspec.yml file contains a version that has leading zero's inspec check doesn't warn against them
Example inspec.yml:
``yaml
name: semver_test
...
version: 001.001.0
```
Correct inspec.yml
```yaml
name: semver_test
...
version: 1.1.0
```

### 🌍 InSpec and Platform Version

inspec 2.0.17

### 🤔 Replication Case

Create a profile and change the version to be 001.001.0

### 💁 Possible Solutions

Validate a conversion of each part of the SemVer to an integer had same character length as original version. If it doesn't output a warning.

**Comment by jerryaldrichiii** [comment]
Great catch @TheLunaticScripter. I'm going to mark this as a bug. We should not accept leading zeros in the Major, Minor, or Patch version numbers.

https://semver.org/#spec-item-2
