### ISSUE TITLE
SELinux resource type needs to be migrated to InSpec

### ISSUE THREAD

**Issue by jinfante5** [inspec/inspec#2758]
### 🎛 Description

**Choose one:** is this a  🙋 feature request?

SELinux resource needs to be migrated to InSpec

### 🌍 InSpec and Platform Version
InSpec 2.0.17
Red Hat Enterprise Linux Server release 7.4 (Maipo)

### 🤔 Replication Case

Resource is not avaliable

### 💁 Possible Solutions

Migrate the resource to InSpec

### 💻 Stacktrace

none

**Comment by jerryaldrichiii** [comment]
Great suggestion @jinfante5! I'm going to tag this as a feature request. I also searched through the open issues and found a few that are related. I'll mention them here so it can be tracked.

https://github.com/chef/inspec/issues/563
https://github.com/chef/inspec/issues/534

**Comment by wellus** [comment]
Yep, this would a be a great feature!

**Comment by indepth15** [comment]
Any update to support Selinux?

**Comment by clintoncwolfe** [comment]
This is tracked on #534; closing as a duplicate.
