### ISSUE TITLE
netcat requirement for the 'host' resource

### ISSUE THREAD

**Issue by mmukherjee** [inspec/inspec#2759]
### 🎛 Description

**bug report**

I am trying to use the **'host'** resource, but ending up with this error -
```
+ inspec exec fastdata/controls/host_checks_dev.rb
Profile: tests from fastdata/controls/host_checks_dev.rb (tests from fastdata.controls.host_checks_dev.rb)
Version: (not specified)
Target:  local://

  ↺  host-checks: host-checks
     ↺  The following requirements are not met for this resource: netcat must be installed
```
I have built a custom inspec docker image, built on top of the inspec docker image  (from docker hub). The customisations are to install 'nc' and 'ncat' on it, apart from openssh. I am sure that the nc and ncat commands are installed on the docker container.

```
/share # nc
usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]

/share # ncat
Ncat: You must specify a host to connect to. QUITTING.
```

### 🌍 InSpec and Platform Version

```
/share # inspec -v
2.0.17
```
```
/share # uname -a
Linux 44c168eccf68 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 Linux
```

### 🤔 Replication Case

The control I am trying to execute is this -

```
control 'host-checks' do
  impact 1.0
  title 'host-checks'
  desc '
   Specify the URLs which need to be up and working.
  '
  tag 'host-checks'

  describe host('fdp.abc.com', port: 443, protocol: 'tcp') do
    it { should be_reachable }
    it { should be_resolvable }
    its('ipaddress') { should include '10.10.10.10' }
  end

end
```

**Comment by jerryaldrichiii** [comment]
Couple of questions @mmukherjee, how are you executing that control? 

Also, if you connect to the docker instance using `inspec shell -t docker://container_id` and run `inspec.command('nc').exist?` what does that output?

**Comment by jerryaldrichiii** [comment]
@mmukherjee the `host` resource is ran on the machine you are scanning with InSpec. It is that machine that must have `nc`/`netcat` installed. Is that how you are currently doing things?

**Comment by mmukherjee** [comment]
Yes @jerryaldrichiii . The command is running on the inspec container which has 'nc' and 'ncat' installed.

**Comment by jquick** [comment]
if you do a `inspec shell` and then type in:
`inspec.command('nc').exist?`
`inspec.command('ncat').exist?`

What do they return? You can also check the stdout/stderr

```
inspec> inspec.command('nc')
=> Command nc
inspec> inspec.command('nc').stdout
=> ""
inspec> inspec.command('nc').stderr
=> "usage: nc [-46AacCDdEFhklMnOortUuvz] [-K tc] [-b boundif] [-i interval] [-p source_port] [--apple-delegate-pid pid] [--apple-delegate-uuid uuid]\n\t  [-s source_ip_address] [-w timeout] [-X proxy_version]\n\t  [-x proxy_address[:port]] [hostname] [port[s]]\n"
```

**Comment by mmukherjee** [comment]
Thanks @jquick. The command output show up as 'false' despite the fact that I have explicitly installed nc/ncat on the inspec container. Please note, I am running inspec out of a docker container.

```
/share # inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      alpine
    Families:  linux, unix
    Release:   3.7.0
    Arch:      x86_64

inspec> inspec.command('nc').exist?
=> false
inspec> inspec.command('ncat').exist?
=> false
inspec>
inspec> inspec.command('nc')
=> Command nc
inspec>
inspec> inspec.command('nc').stdout
=> ""
inspec> inspec.command('nc').stderr
=> "usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-O length]\n\t  [-P proxy_username] [-p source_port] [-q seconds] [-s source]\n\t  [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]\n\t  [-x proxy_address[:port]] [destination] [port]\n"
inspec> <control-D . to move out of the shell>
/share #
/share #
/share # nc
usage: nc [-46CDdFhklNnrStUuvZz] [-I length] [-i interval] [-O length]
          [-P proxy_username] [-p source_port] [-q seconds] [-s source]
          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]
          [-x proxy_address[:port]] [destination] [port]
/share #
/share # which nc
/usr/bin/nc
/share # which ncat
/usr/bin/ncat
```

Clearly, the results aren't consistent. The 'exist' command returns false, but the stdout and stderr show expected results. Does inspec expect 'nc/ncat' to be installed in a particular location? What am I missing?

Also, thanks @jerryaldrichiii for helping me last night on this. You suggested that nc/ncat should be installed on the 'destination' machine. In this case, however, I believe we don't have a destination machine as the command runs out of a (inspec) docker container .

**Comment by mmukherjee** [comment]
More updates, I reverted to the default inspec docker container - rather than using the custom one which has nc/ncat installed. I observed that even the basic commands like - `inspec.command('mkdir').exist?` returns false.

What could I be doing wrong?

**Comment by jerryaldrichiii** [comment]
@mmukherjee the issue here is that the Docker instance that is running InSpec is Alpine Linux and I bet that `bash` doesn't exist. Thereby, causing https://github.com/chef/inspec/blob/master/lib/resources/command.rb#L53 to fail which is why things are returning `false`

This also causes https://github.com/chef/inspec/blob/master/lib/resources/host.rb#L198 to fail which is why your control is also failing.

I'm going to see what I can do to fix this for you.

Thank you for all the work you've done troubleshooting this.

**Comment by mmukherjee** [comment]
Validated on the new docker image - 2.0.36. All good. Thanks :-)
