### ISSUE TITLE
skip_control should output a message if it can't find the given control name

### ISSUE THREAD

**Issue by teknofire** [inspec/inspec#2767]
### 🎛 Description

🙋 feature request

When running `inspec check` or `inspec exec` `skip_control` should print a warning if it can't find any controls with that name.  It currently appears to just ignore the `skip_control` call and continues to process the wrapper.

If there is a large list of controls being skipped and a couple get typo'd it becomes very hard to determine which ones are not working right when using `inspec check` without having to comment out each one and find the one that doesn't change the control count.

### 🌍 InSpec and Platform Version

I'm running on OSX with Inspec version 1.51.18

### 🤔 Replication Case

Create a new profile that includes the `cis-rhel7-level2-server` profile:

```ruby
 name: skip_control_example
 title: InSpec Profile
 maintainer: The Authors
 copyright: The Authors
 copyright_email: you@example.com
 license: Apache-2.0
 summary: An InSpec Compliance Profile
 version: 0.1.0

 depends:
   - name: cis-rhel7-level2-server
     compliance: delivery/cis-rhel7-level2-server
```
create `controls/bad_controls.rb`
```ruby
include_controls 'cis-rhel7-level2-server' do
  skip_control 'xccdf_org.cisecurity.benchmarks_rule_1.1.2_Ensure_separate_partition_exists_for_tmp'
  skip_control 'BAD_NAME_xccdf_org.cisecurity.benchmarks_rule_1.6.1.1_Ensure_SELinux_is_not_disabled_in_bootloader_configuration'
  skip_control 'xccdf_org.cisecurity.benchmarks_rule_4.1.3_Ensure_auditing_for_processes_that_start_prior_to_auditd_is_enabled'
end
```

Then run `inspec check`, the top of the output will say there are 222 controls being run when it should be 221 (224 in the included profile - 3 that should be skipped).  Fix the typo by removing `BAD_NAME_` and run it again and it will show 221 controls.

```
$ inspec check skip_control_example
Location:    skip_control_example
Profile:     skip_control_example
Controls:    222
Timestamp:   2018-03-01T15:33:08-08:00
Valid:       true
```

### 💁 Possible Solutions

Either printing a warning or an error saying with the given control name that could not be found should be sufficient to figure out where the typo is happening.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by jerryaldrichiii** [comment]
@teknofire Great suggestion! I'll mark this as a feature request.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
