### ISSUE TITLE
http resource should handle connection failed (ex. port is not open)

### ISSUE THREAD

**Issue by Wing924** [inspec/inspec#2769]
### 🎛 Description

🐛 bug report

http resource raise a error when connection error.

### 🌍 InSpec and Platform Version

inspec 1.45.13
OS: centos 7

### 🤔 Replication Case

```ruby
# Assume port 12345 is closed.
describe http('http://localhost:12345', enable_remote_worker: true) do
  its('status') { should cmp 200 }
end
```
It fails with `Failed to complete #verify action: [undefined method `lines' for nil:NilClass]`

### 💁 Possible Solutions

check curl exit_status code and handle this.

**Comment by jquick** [comment]
Thanks for this report!
