### ISSUE TITLE
Inspec iptable rule tests fail when including the sudo cookbook.

### ISSUE THREAD

**Issue by marzdgzmn** [inspec/inspec#2777]
### 🎛 Description

**Choose one:** 🐛 bug report 

Inspec iptable rule tests (e.g. it { should have_rule('-A FWR -i lo -j ACCEPT') }) fails when including the sudo cookbook.

### 🌍 InSpec and Platform Version
Inspec version: 1.36.1
Platform: CentOS 7.2

### 🤔 Replication Case

Apply iptable rule using the iptable cookbook, then create inspec tests for the iptables. Include the sudo cookbook (e.g include_recipe 'sudo').

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

> I, [2018-03-05T17:10:40.354769 #24664]  INFO -- default-centos-72: -----> Setting up <default-centos-72>...
> I, [2018-03-05T17:10:40.355772 #24664]  INFO -- default-centos-72: Finished setting up <default-centos-72> (0m0.00s).
> I, [2018-03-05T17:10:40.355926 #24664]  INFO -- default-centos-72: -----> Verifying <default-centos-72>...
> I, [2018-03-05T17:10:41.020988 #24664]  INFO -- default-centos-72: Detected alternative framework tests for `inspec`
> I, [2018-03-05T17:10:41.021243 #24664]  INFO -- default-centos-72: Detected alternative framework tests for `serverspec`
> I, [2018-03-05T17:10:41.022510 #24664]  INFO -- default-centos-72: Loaded tests from {:path=>"/home/marz/rise/chef-repo/cookbooks/rise_iptables/test/integration/default/inspec"} 
> E, [2018-03-05T17:10:41.465698 #24664] ERROR -- default-centos-72: Verify failed on instance <default-centos-72>.
> E, [2018-03-05T17:10:41.465863 #24664] ERROR -- default-centos-72: ------Exception-------
> E, [2018-03-05T17:10:41.465913 #24664] ERROR -- default-centos-72: Class: Kitchen::ActionFailed
> E, [2018-03-05T17:10:41.465944 #24664] ERROR -- default-centos-72: Message: Inspec Runner returns 1
> E, [2018-03-05T17:10:41.465971 #24664] ERROR -- default-centos-72: ----------------------
> E, [2018-03-05T17:10:41.466005 #24664] ERROR -- default-centos-72: ------Backtrace-------
> E, [2018-03-05T17:10:41.466032 #24664] ERROR -- default-centos-72: /home/marz/.chefdk/gem/ruby/2.4.0/gems/kitchen-inspec-0.19.0/lib/kitchen/verifier/inspec.rb:96:in `call'
> E, [2018-03-05T17:10:41.466058 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:434:in `block in verify_action'
> E, [2018-03-05T17:10:41.466086 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
> E, [2018-03-05T17:10:41.466113 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:489:in `block in action'
> E, [2018-03-05T17:10:41.466138 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
> E, [2018-03-05T17:10:41.466164 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:488:in `action'
> E, [2018-03-05T17:10:41.466223 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:426:in `verify_action'
> E, [2018-03-05T17:10:41.466252 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:359:in `block in transition_to'
> E, [2018-03-05T17:10:41.466280 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `each'
> E, [2018-03-05T17:10:41.466314 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:358:in `transition_to'
> E, [2018-03-05T17:10:41.466342 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:157:in `verify'
> E, [2018-03-05T17:10:41.466367 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `public_send'
> E, [2018-03-05T17:10:41.466393 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
> E, [2018-03-05T17:10:41.466418 #24664] ERROR -- default-centos-72: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
> E, [2018-03-05T17:10:41.466443 #24664] ERROR -- default-centos-72: ----End Backtrace-----

**Comment by jerryaldrichiii** [comment]
@marzdgzmn I think I found the issue. I don't think it is related to the sudo cookbook.

Basically, the `iptables` InSpec resource is trying to run `iptables` but `iptables` is not in the path (due to how the transport works). Instead it should use `/usr/sbin/iptables`.

I'm working on a fix now and will update here with the solution.
