### ISSUE TITLE
Docs prefer os.family over os[:family]

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2780]
### 🎛 Description

 🙋 feature request

The documentation for the `os` resources shows usage with the 'Hash' notation. The `os` resource defines a `family` method. Most resources define methods it feels as though the `os` behaves more like the other resources if the documentation showed the `os.family` version.

### 🌍 InSpec and Platform Version

Inspec 2.0.17, Mac OSX 10.13.13

### 🤔 Replication Case

```shell
$ inspec shell
> os[:family]
=> "darwin"
> os.family
=> "darwin"
```

### 💁 Possible Solutions

Update the documentation examples

**Comment by jquick** [comment]
Yeah with the new train backend we should be using the dot notation. +1
