### ISSUE TITLE
Add `aws_ec2_instances` plural resource

### ISSUE THREAD

**Issue by trickyearlobe** [inspec/inspec#2784]
### 🎛 Description

Inspec contains singular and plural resources for various AWS objects, but seems to be missing a plural resource for EC2 instances.

Its quite helpful to have a plural resource for performing filter driven tests across large numbers of objects.

I have some basic code which

* exposes a collection of EC2 instances
* filters them using Inspec's built in FilterTable class.

I'll submit a PR for discussion and improvement.

**Comment by skpaterson** [comment]
This is available in the new InSpec AWS resource pack:
https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_ec2_instances.md
