### ISSUE TITLE
Inspec CLI returns 0 for a non-existent command

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#2787]
### 🐛 Description

inspec CLI returns 0 when a non-existent command is provided at command line.
Since it's possible to add plugin commands to inspec; it is realistic to want to test whether the command exists or not.
If the plugin command is not correctly loaded then inspec should not return 0 for that command.

### 🌍 InSpec and Platform Version

1.51.21
OSX 10.12

### 🤔 Replication Case

```
➜  my_repo git:(master) ✗ inspec party help
Could not find command "party".
➜  my_repo git:(master) ✗ echo $?
0
```

### 💁 Possible Solutions

Not sure exactly where the fix is needed; but `Could not find command` comes directly from thor so presumably inspec is not checking for and responding to thor errors in at least one place.

### 💻 Stacktrace

None, just the terminal output above

**Comment by jquick** [comment]
@james-stocks - Thanks for reporting this!
