### ISSUE TITLE
Inspec hangs when executing some windows profiles against linux machine

### ISSUE THREAD

**Issue by jcreedcmu** [inspec/inspec#279]
I'm not sure if this is representative of a deeper problem. In any case, if I put

``` ruby
control 'foo' do
  impact 1.0
  title 'abc'
  desc 'def'
  describe registry_key('blah') do
    it { should_not exist }
  end
end

control 'bar' do
  impact 1.0
  title 'abc'
  desc 'def'
  describe audit_policy do
    its('Kerberos Authentication Service') { should_not eq 'No Auditing' }
  end
end
```

in `/tmp/a.rb` and execute

``` shell
bundle exec inspec exec  /tmp/a.rb --sudo-password vagrant  --sudo  --sudo-password 'vagrant' --host 10.0.0.101 --user vagrant --password vagrant --port 22 --backend ssh
```

where an ubuntu linux vm lives at `10.0.0.101`, then inspec appears to observe one test fail (i.e. I see an `F` appear on console) but then hangs. This hang doesn't occur if I delete either rule `foo` or rule `bar`, and it doesn't occur if I remove the `--sudo` flag.

**Comment by jcreedcmu** [comment]
This appears to have been introduced by https://github.com/chef/inspec/commit/cd35d8232691674e22cfc8f25918f5788d69181c
(At least, I can't repro before that commit) so @chris-rock maybe you want to take a look at this.

**Comment by chris-rock** [comment]
@jcreedcmu Thanks for highlighting. This is for sure an annoying bug. I have a look on this!
