### ISSUE TITLE
nginx_conf resource cannot handle include of empty files

### ISSUE THREAD

**Issue by samcornwell** [inspec/inspec#2790]
### 🐛 Description

The `nginx_conf` resource will return an empty `params` if an included configuration file is empty. This also occurs if the included configuration file consists of only comments. An empty included file should have no effect. The use case where this issue occurred was where we had an `nginx.conf` include a sample configuration file which is itself completely commented out.

### 🌍 InSpec and Platform Version

2.0.32
OSX 10.13.3

### 🤔 Replication Case

The issue can be demonstrated with the following toy example of an `nginx.conf` file.

```
http {
    default_type  application/octet-stream;
}
```

Executing the following in the shell to get the parsed params using the `nginx_conf` resource:
```
inspec> nginx_conf('nginx.conf').params
=> {"http"=>[{"default_type"=>[["application/octet-stream"]]}]}
``` 

Create an empty file called `empty.conf` and add an in include statement to `nginx.conf`:
```
http {
    include empty.conf;
    default_type  application/octet-stream;
}
```

Getting the params again from the shell:
```
inspec> nginx_conf('nginx.conf').params
=> {}
```

Adding an empty `server` directive to `empty.conf`:
```
server {}
```

Getting the params from the shell now works fine:
```
inspec> nginx_conf('nginx.conf').params
=> {"http"=>[{"default_type"=>[["application/octet-stream"]], "server"=>[{}]}]}
```

### 💁 Possible Solutions
Not sure the exact fix.  Probably somewhere in [lib/utils/nginx_parser.rb](https://github.com/chef/inspec/blob/master/lib/utils/nginx_parser.rb) or [lib/resources/nginx_conf.rb](https://github.com/chef/inspec/blob/master/lib/resources/nginx_conf.rb).

### 💻 Stacktrace
See output in Replication Case.

**Comment by jquick** [comment]
@samcornwell - Thanks for reporting this!

**Comment by aaronlippold** [comment]
@jquick see: https://github.com/chef/inspec/issues/2805 @rx294 put in a small fix to cover this?

**Comment by samcornwell** [comment]
@aaronlippold 
No, these are two unrelated issues.
