### ISSUE TITLE
Allow custom reporting method within a profile

### ISSUE THREAD

**Issue by russellseymour** [inspec/inspec#2791]
### 🎛 Description

🙋 feature request?

When testing multiple resources using InSpec it is necessary to use a FilterTable. This works well when it is just one resource that is being sought, however the reporting is not so good when you need to test something across multiple resources.

For example. Take a set of 10 servers of which you want to check that the BIOS version is consistent across all of them. It is easy to get a boolean result back to show that not all machines have the same version, however to get specific information about which servers are affected and the version they are running results in a test similar to the following:

```ruby
describe my_servers.where(bios_version != '40') do
   its('bios_version') { should eq [] }
   its('name') { should eq [] }
end
```

In an ideal world the arrays would both be empty, but in reality they will not. Each of the assertions will produce there own output and they are not connected. The only saving grace is that the order of each of the arrays is the same, so it is possible to visually see the version against the server. Example output will look like:

```
[FAIL] my_servers with bios_version != '40' bios_version should eq []

expected: []
         got: ['39', 42']

[FAIL] my_servers with bios_version != '40' name should eq []

expected: []
          got: ['server-03', 'server-08']
```

In this (contrived) example there are only 2 servers that do not pass the bios_version test. However this could be hundreds or thousands and this comparison is impractical. Additionally the output is truncated by InSpec so not all the information will be available.

### 💁 Possible Solutions

One idea that I has was to be able to build into the profile a custom reporter. This would then be called when the test is run and the output would be much more readable, for example:

```
[FAIL] my_servers with bios_version != '40' name should eq []

expected: []
          got:

      name 'server-03' has a bios_version of '39'
      name 'server-08' has a bios_version of '42'
```

Additionally if this information could be output to a file so it can be analysed by another tool would be useful.

This is as far as I have got with it and I do not know practically how to achieve this. There are a few questions this rasies:
 - How do you inform the resource to use the custom reporter?
 - Would the reporter use a template to output the information? This might work as the individual information could be added in the output.

I appreciate that this is nor probably not a trivial task to accomplish and my idea may not be the ideal one. Hopefully this will generate some discussion about it.

**Comment by ViolentOr** [comment]
Feels like i had pretty similar problem a while ago (#2444 ). Or did you mean something else?

**Comment by russellseymour** [comment]
@ViolentOr That is along the lines of what I am trying to achieve. I will see if I can come up with something like that for the scenario I have.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
