### ISSUE TITLE
Support of linux mint or OS detection via distro families

### ISSUE THREAD

**Issue by artem-sidorenko** [inspec/inspec#280]
Linux Mint is a quite popular (1st place on [distrowatch](http://distrowatch.com/dwres.php?resource=popularity)) linux distro, which is based on Ubuntu LTS.

Obviously linuxmint sells itself in LSB as Mint:)

``` bash
$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
$ cat /etc/upstream-release/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```

If I try to use inspec on Mint, I get following messages for service and package resources:

``` bash
$ kitchen verify desktop-mint-172-cinnamon
-----> Starting Kitchen (v1.4.2)
.....
-----> Setting up <desktop-mint-172-cinnamon>...
       Finished setting up <desktop-mint-172-cinnamon> (0m0.00s).
-----> Verifying <desktop-mint-172-cinnamon>...
*............*.........*..*

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) System Package crossover The `package` resource is not supported on your OS yet.
     # Not yet implemented
     # /home/artem/.chefdk/gem/ruby/2.1.0/gems/inspec-0.9.5/lib/inspec/runner.rb:114

  2) System Package x11vnc The `package` resource is not supported on your OS yet.
     # Not yet implemented
     # /home/artem/.chefdk/gem/ruby/2.1.0/gems/inspec-0.9.5/lib/inspec/runner.rb:114

  3) Service x11vnc The `service` resource is not supported on your OS yet.
     # Not yet implemented
     # /home/artem/.chefdk/gem/ruby/2.1.0/gems/inspec-0.9.5/lib/inspec/runner.rb:114

  4) System Package owncloud-client The `package` resource is not supported on your OS yet.
     # Not yet implemented
     # /home/artem/.chefdk/gem/ruby/2.1.0/gems/inspec-0.9.5/lib/inspec/runner.rb:114

Finished in 0.45324 seconds (files took 1.97 seconds to load)
27 examples, 0 failures, 4 pending

       Finished verifying <desktop-mint-172-cinnamon> (0m2.16s).
-----> Kitchen is finished. (0m5.08s)
zlib(finalizer): the stream was freed prematurely.
```

Software versions:

``` bash
$ chef --version
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
$ chef exec gem list inspec

*** LOCAL GEMS ***

inspec (0.9.5, 0.9.2)
kitchen-inspec (0.9.0)
$ inspec version
0.9.5
```

I talked with @arlimus today about that and he told me about the idea to have OS detection based on families instead of LSB names. The creation of this issue was promised in this discussion:)

If you want and if it would make your life easier, I could provide you a Mint vagrant box for virtualbox (packaged by myself) which I use here.

**Comment by chris-rock** [comment]
@artem-sidorenko I love the idea of using os families if possible. We already switched to `os.linux?`and `os.windows?` in multiple places. Some resources need to be adapted to the specific os, but those are the exception.

Could you do me one favor and add a mint vagrant box to our integration tests in https://github.com/chef/inspec/blob/master/test/integration/.kitchen.yml ?

**Comment by artem-sidorenko** [comment]
@chris-rock I would do that if you could offer a hosting place for it:) really, its not a joke, I couldn't find any mint box with a stable long-term availability on the net. What about the idea to add to bento and host it in the same place like other boxes from Chef?

**Comment by chris-rock** [comment]
@artem-sidorenko yeah try adding this to bento or just push the box directly to atlas.

**Comment by artem-sidorenko** [comment]
@chris-rock I totally missed somehow that atlas is free now. #281 is there.

**Comment by juliandunn** [comment]
@artem-sidorenko I'm sure [Bento](https://github.com/chef/bento) would also appreciate a PR with your definition for Mint!

**Comment by artem-sidorenko** [comment]
@juliandunn mint has own installer and some effort is required to figure out additional options for preseed in order to get the installation fully automated with packer. Unfortunately I do not have time right now to figure out this options and prepare the packer template.
