### ISSUE TITLE
Feature request: check if AWS EC2 EBS volume is encrypted

### ISSUE THREAD

**Issue by mrcasablr** [inspec/inspec#2811]
AWS allows encrypting of EBS volumes attached to EC2 instances.  We need to have a check to verify if a volume id attached to an instance is encrypted

**Comment by jquick** [comment]
@mrcasablr - Thanks for this request!

**Comment by skpaterson** [comment]
EBS volume now has a helper method to check for encryption:
```
describe aws_ebs_volume(name: 'data-vol') do
  it { should be_encrypted }
end
```
Feel free to open an issue here if anything is missing:
https://github.com/inspec/inspec-aws/issues
