### ISSUE TITLE
Azure Terraform Testing - Example required.

### ISSUE THREAD

**Issue by virtualbubble** [inspec/inspec#2813]
### 🎛 Description

Ignore

**Comment by jquick** [comment]
@virtualbubble Hey! Not sure if you already found it but here is our Azure integration tests which use terraform:
https://github.com/chef/inspec/tree/master/test/integration/azure

**Comment by virtualbubble** [comment]
@jquick - Late response (from me) thanks that was exactly what I was looking for.
