### ISSUE TITLE
OS resource docs does not demonstrate some methods or examples

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2820]
### 🎛 Description

This is a  🙋 feature request

The docs page:

* does not demonstrate the usage of `families` to retrieve all the OS families that the target OS belongs.
* the controls defined around testing the `os.name`, `os.release`, and `os.arch` are generically using 'foo'.
* the controls defined around testing the `os.name`, `os.release`, and `os.arch` are defined in a way that is not currently in vogue with the rest of inspec:

```ruby
describe os.name do
  it { should cmp 'centos' }
end

describe os do
  its('name') { should cmp 'centos' }
end
```

* the examples should include retrieving the os build for a windows platform 

```ruby
describe os[:platform][:build] do
  it { should cmp 9600 }
end
```

Though I would prefer the following approach (Issue #2819): 

```ruby
describe os do
  its('build') { should cmp 9600 }
end
```

### 🌍 InSpec and Platform Version

InSpec 2.0.32, Mac OSX 10.13.3

**Comment by zenspider** [comment]
I'm not in a position to fix this (yet)... but I am in a position to keep it alive...

**Comment by v0lumehi** [comment]
Would be great to see this added to the Docs
