### ISSUE TITLE
inspec artifact workflow is not documented on the docs site

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2821]
### 🎛 Description

This a 🐛 bug report or a 🙋 feature request. Based on how you view the world and the importance of a user being able to use a tool through the documentation.

The `inspec artifact` subcommand enables you to generate asymmetrical keys that you can use to encrypt a profile. You can then send the public key and an encrypted profile (independently) to another party and they can extract that profile with the given public key.

None of this workflow is described in the documentation.

### 🌍 InSpec and Platform Version

InSpec 2.0.32, Mac OSX 10.13.3

#### Profile Author

```shell
# generate your keys
$ inspec artifact generate --keyname myprofilekeys
# send the public key to the intended receiver of profiles
# Sign the profile at the given path
$ inspec artifact sign-profile --profile myprofile --keyname myprofilekeys
# myprofile.iaf is created
# send myprofile.iaf to the intended receiver with the public key
```

#### Profile Receiver

```shell
# The intended receiver of the profile needs to copy the key into the same working directory where they execute the command. The packaged profile path is specified so that can be anywhere.
$ inspec artifact install-profile --infile myprofile-0.1.0.iaf --destdir /tmp/myprofile
```

### 💁 Possible Solutions

* Document it.

* Remove it.

**Comment by jquick** [comment]
Hey @burtlo - `inspec artifact` is only experimental at this point and should not be used. We will keep this undocumented until it matures and is ready for use. Thanks!
