### ISSUE TITLE
http resource when run on windows generates a stacktrace and halts the scan

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2822]
### 🎛 Description

This a 🐛 bug report

The `http` resource fails with a stacktrace on Windows.

### 🌍 InSpec and Platform Version

InSpec 2.0.32, Mac OSX 10.13.3

### 🤔 Replication Case

Define either of these resource and invoke them through a control file, profile, or shell:

```ruby
describe http('http://localhost:8080', enable_remote_worker: true) do
  its('body') { should match /Tomcat/ }
end

describe http('http://localhost:8080', enable_remote_worker: false) do
  its('body') { should match /Tomcat/ }
end
```

### 💁 Possible Solutions

It should generate an appropriate failing test case instead of raising an exception and failing the entire inspec scan. Currently on CentOS 7.4 the results with the same resource look like:

```
     ×  http GET on http://localhost:8080 body
     undefined method `lines' for nil:NilClass
```

### 💻 Stacktrace

```
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/resources/http.rb:62:in `http_method': undefined method `fetch' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/resources/http.rb:66:in `to_s'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:133:in `populate'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:258:in `create'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:421:in `set_it_up'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:385:in `subclass'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:259:in `block in define_example_group_method'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner_rspec.rb:27:in `example_group'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:305:in `rspec_skipped_block'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:266:in `get_check_example'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:282:in `block in register_rule'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:281:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:281:in `flat_map'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:281:in `register_rule'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:97:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:96:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:96:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/runner.rb:103:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/lib/inspec/cli.rb:168:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.32/bin/inspec:12:in `<top (required)>'
	from /opt/inspec/bin/inspec:76:in `load'
	from /opt/inspec/bin/inspec:76:in `<main>'
```

**Comment by jquick** [comment]
I believe the fix here would be to return the skip-resource if no body is found.

**Comment by russellseymour** [comment]
I have just had this issue myself and it does not seem to be related to what is being checked, in fact it does not get that far.

Take the following test:

```ruby
describe http('https://www.google.com') do
   its('status') { should eq 200 }
end
```
If it is run on *Linux* it works as expected and you get the following output:

```
  ✔  Test endpoints:
     ✔  http GET on https://www.google.com status should eq 200
```
However on *Windows* you get the same sort of stacktrace as seen by @burtlo.

```
C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/resources/http.rb:62:in `http_method': undefined method `fetch' for nil:NilClass (NoMethodError)
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/resources/http.rb:66:in `to_s'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:133:in `populate'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:258:in `create'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:421:in `set_it_up'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:385:in `subclass'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:259:in `block in define_example_group_method'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner_rspec.rb:27:in `example_group'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:305:in `rspec_skipped_block'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:266:in `get_check_example'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:282:in `block in register_rule'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:281:in `each'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:281:in `flat_map'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:281:in `register_rule'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:97:in `block in load'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:96:in `each'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:96:in `load'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/runner.rb:103:in `run'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/lib/inspec/cli.rb:168:in `exec'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from C:/Users/russells/workspaces/azure/azure-managed-automate/.uru/ruby/gems/inspec-2.1.54/bin/inspec:12:in `<top (required)>'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/bin/inspec:23:in `load'
        from C:/Users/russells/tools/rubies/ruby-2.4.3/bin/inspec:23:in `<main>'
```

This is testing the `status` and not the body so I think it is to do with the http resource itself running on windows.

**Comment by russellseymour** [comment]
An update to this bug. 
I can get the exact same error on Linux if the `-t azure://` is added to the command line.
Leaving this off and the http resource works as expected.

```
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/resources/http.rb:62:in `http_method': undefined method `fetch' for nil:NilClass (NoMethodError)
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/resources/http.rb:66:in `to_s'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:133:in `populate'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:258:in `create'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:421:in `set_it_up'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:385:in `subclass'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:259:in `block in define_example_group_method'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner_rspec.rb:27:in `example_group'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:305:in `rspec_skipped_block'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:266:in `get_check_example'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:282:in `block in register_rule'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:281:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:281:in `flat_map'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:281:in `register_rule'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:97:in `block in load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:96:in `each'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:96:in `load'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/runner.rb:103:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/inspec/cli.rb:168:in `exec'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/bin/inspec:12:in `<top (required)>'
        from /usr/bin/inspec:72:in `load'
        from /usr/bin/inspec:72:in `<main>'
```

This is a bit of a pain as I am not able to run all the tests in one go, I have to run the separately.

**Comment by russellseymour** [comment]
Hello @clintoncwolfe 

This is not just a Windows issue as I can recreate it in Linux as well. Please see my previous comment.

**Comment by clintoncwolfe** [comment]
A couple of things are happening here:

1. `enable_remote_worker` became mandatory in InSpec 2.0 . 
2. `enable_remote_worker` assumes the InSpec run target (as in, the `-t` value, NOT the URL being checked) has a curl command available - see [here](https://github.com/chef/inspec/blob/master/lib/resources/http.rb#L151)

If your target is azure (or any non-OS platform), `command` will certainly fail, as "do you have curl installed" is nonsensical in that context.

**Comment by clintoncwolfe** [comment]
I'm adding the `train` tag here, because our non-OS platforms should declare (somehow) that `command` is non-applicable for them.

Thanks for the catch @russellseymour , you're right, this isn't Windows-specific.

**Comment by clintoncwolfe** [comment]
I think fix here is two-fold.

First, notice when [we are not on an os](https://github.com/chef/inspec/blob/master/lib/resources/http.rb#L42), and fall back to the local worker in that case.  `inspec.platform.family != 'os'` would do it.

That leaves the case in which we are on an OS that does not have curl installed, or a curl that doesn't behave like we expect.  I suspect that our curl handling is rather windows-unfriendly.  We might want to make the logic more sophisticated, and use powershell if needed.  There are several approaches to
[fetching a URL on windows](https://serverfault.com/questions/483754/is-there-a-built-in-command-line-tool-under-windows-like-wget-curl).

**Comment by clintoncwolfe** [comment]
I'm re-adding the Windows label - not because it is fully accurate, it's not limited to there - but simply because this is an important issue for Windows users, and we need to be able to find it bye searching on that platform label.

**Comment by gonchalo620** [comment]
Instalé la versión 1.51 y el módulo http en windows funcionó correctamente. Lo que hice como  una solucion temporal fué cambiar el módulo http.rb de la versión 3.4.1 por la del 1.51. Hice una prueba y funcionó correctamente.
C:\opscode\inspec\embedded\lib\ruby\gems\2.4.0\gems\inspec-1.51.25\lib\resources\http.rb

Machine translation:
I installed version 1.51 and the http module in windows worked correctly. What I did as a temporary solution was to change the http.rb module of version 3.4.1 to that of 1.51. I did a test and it worked correctly.
C: \ opscode \ inspec \ embedded \ lib \ ruby \ gems \ 2.4.0 \ gems \ inspec-1.51.25 \ lib \ resources \ http.rb

**Comment by picatz** [comment]
Adding `supports platform: windows` fixes the local testing issue on windows (2012 R2)

<img width="577" alt="screen shot 2019-02-04 at 1 51 28 pm" src="https://user-images.githubusercontent.com/14850816/52230444-60204600-2885-11e9-9002-261b641f32d6.png">

The only line that I added to `http.rb`.
<img width="337" alt="screen shot 2019-02-04 at 1 52 40 pm" src="https://user-images.githubusercontent.com/14850816/52230445-60204600-2885-11e9-857d-de8c5b6b21fb.png">

**Comment by bgshacklett** [comment]
It's curious that the existence of that `supports platform: 'windows'` line actually seems to have an effect on how the module is loaded. With the line missing it seems that `http_method` is being called prior to `initialize(...)`, leading to `@opts` being dereferenced while its value is nil.

**Comment by nellshamrell** [comment]
I've replicated this using a Windows workstation. Here are the steps I took (based in part on https://lollyrock.com/posts/inspec-windows/)

* Created Windows workstation
* Installed InSpec
* md inspec
* cd .\inspec
* code test.rb

test.rb
```
describe http('http://localhost:8080', enable_remote_worker: true) do
  its('body') { should match /Tomcat/ }
end

describe http('http://localhost:8080', enable_remote_worker: false) do
  its('body') { should match /Tomcat/ }
end
```

* inspec exec .\test.rb

This resulted in the stack trace rather than the expected test output.

**Comment by nellshamrell** [comment]
I think I know what is going on here (including why adding the line 'supports platform: window' to http.rb fixes the issue).

(One note - this error occurs on both local and remote workers)

The key is this part of Inspec::Runner:

lib/inspec/runner.rb
```ruby
    def load
      all_controls = []

      @target_profiles.each do |profile|
        @test_collector.add_profile(profile)
        next unless profile.supports_platform?

        write_lockfile(profile) if @create_lockfile
        profile.locked_dependencies
        profile_context = profile.load_libraries

        profile_context.dependencies.list.values.each do |requirement|
          unless requirement.profile.supports_platform?
            Inspec::Log.warn "Skipping profile: '#{requirement.profile.name}'" \
             " on unsupported platform: '#{@backend.platform.name}/#{@backend.platform.release}'."
            next
          end
          @test_collector.add_profile(requirement.profile)
        end

        @attributes = profile.runner_context.attributes if @attributes.empty?
        tests = profile.collect_tests
        all_controls += tests unless tests.nil?
      end

      all_controls.each do |rule|
        register_rule(rule) unless rule.nil?
      end
    end
```

In particular:

```ruby
          unless requirement.profile.supports_platform?
            Inspec::Log.warn "Skipping profile: '#{requirement.profile.name}'" \
             " on unsupported platform: '#{@backend.platform.name}/#{@backend.platform.release}'."
            next
          end
```

As it is in the current master branch, the http resource does not support the Windows platform. Rather than returning the expected error, however, it's failing in the stack trace.

Investigating more.

**Comment by nellshamrell** [comment]
I was wrong - the key part is this section of Inspec::Runner#load

```ruby

      all_controls.each do |rule|
        register_rule(rule) unless rule.nil?
     end
```

That line does NOT return an error with this test:

```ruby
describe service('DCHP Client') do
    it { should be_installed }
    it { should be_running }
end
```

It DOES return an error with this test

```ruby
describe http('http://localhost:8080', enable_remote_worker: true) do
  its('body') { should match /Tomcat/ }
end
```

**Comment by nellshamrell** [comment]
Alright, after more evaluation - the key things happening are:

* the http resource currently is not supported on Windows (this can easily be fixed with adding "supports platform: 'windows'" to the http resource)
* the larger issue, however, seems to be that when http is used on an unsupported platform,   
```ruby
def http_method
      @opts.fetch(:method, 'GET')
end
```
is nil.
* This matters, because the to_s method on the http resource is overwritten as:
```ruby
def to_s
  "http #{http_method} on #{@url}"
end
```

* In order to print out the error that the http resource is not supported on Windows, we need the http_method to be something other than nil.


So, we need to
* Understand why http_method is set to nil when using the http resource on Windows
* Add in error handling for when http_method is nil
* Add support for windows to the http resource

**Comment by nellshamrell** [comment]
Went down a rabbit hole, but as I climbed out I found something interesting.

When running this code on Windows, @opts in the Inspec::Resources::Http class is nil, which is why when the http_method attempts to run 

```
@opts.fetch(:method, 'GET')
```

it returns the error "/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.1.10/lib/resources/http.rb:62:in `http_method': undefined method `fetch' for nil:NilClass (NoMethodError)"

Now to find out why @opts is nil...

It returns the error '

**Comment by glennsarti** [comment]
~~@nellshamrell Not sure if this is helpful or not. I know why opts is nil but I have no idea HOW it does it.  The [initialise](https://github.com/inspec/inspec/blob/master/lib/resources/http.rb#L27) method for that class is not called prior to calling `to_s`.  Verified by throwing some pry statements in there.  The initialize pry statement never tripped.~~  Whoops...should read scroll back.  Already stated above.

**Comment by glennsarti** [comment]
Also, I'm having the same error thrown for a simple usecase

Inspec: 3.7.1
OS:Windows 10 - 1803
Ruby: 2.5.1 x64 with DK
Inspec installed: Via rubygems
Remote testing: Nope...just local.

spec.rb
```
mattermost_root = 'http://localhost:8065'
describe http(mattermost_root, {}) do
  its('status') { should eq 200 }
  #its('body') { should eq 'body' }
  #its('headers.name') { should eq 'header' }
end
```

**Comment by glennsarti** [comment]
Also @nellshamrell The documentation for the http resource makes no mention that this is a unix only resource https://www.inspec.io/docs/reference/resources/http/  😞

**Comment by glennsarti** [comment]
For anyone hitting this error, you _could_ use this workaround.

NOTE - This is just a workaround, doesn't solve the actual problem, and monkey patches the http class.  Use at your own risk etc. etc.

``` ruby
# Put this in your testing file or spec_helper.rb file

# Due to https://github.com/inspec/inspec/issues/2822
# monkey patch the Inspec http resource
module Inspec::Resources
  class Http
    supports platform: 'windows'
  end
end
```

**Comment by nellshamrell** [comment]
We could add Windows support to the resource itself - but I'm trying to figure out where I can capture an error like that in the future. On a larger scale, we should have a consistent (and clear) error returned for when someone tries to run a resource on a platform that does not support. FINALLY back to working on this.

**Comment by nellshamrell** [comment]
Upon further inspection this appears to have been already fixed in this commit: 

https://github.com/inspec/inspec/commit/2857d07151f6cb57d1015b497c08f2b2b2f2d84d

This means it will fail explicitly when running on Windows, rather than returning the long backtrace.

The question now is do we want this resource to support Windows?  I'm unsure of whether that is in the scope of this issue.

**Comment by glennsarti** [comment]
> I'm unsure of whether that is in the scope of this issue.

IMO it depends on your point of view. The docs don't say it's not supported. And NOT being able to do a trivial HTTP get request, in Ruby, on Windows, when the gem needed is already there; seems a terrible oversight

Granted, the `curl` call is annoying and problematic on Windows.

**Comment by clintoncwolfe** [comment]
I'm not clear on how https://github.com/inspec/inspec/commit/2857d07151f6cb57d1015b497c08f2b2b2f2d84d fixed the issue - that only touched the inline examples, as far as I can tell. I do see that prior to that, the `supports` restriction was `unix`.

**Comment by nellshamrell** [comment]
@clintoncwolfe - I linked to the wrong commit, apologies! This commit is the one that fixed it:

https://github.com/inspec/inspec/commit/af5d6e92854eb69adc5101db84d89f4addf64d7b

**Comment by nellshamrell** [comment]
Opened a new issue to request http resource support when using Windows (#3959) , going ahead and closing this one.

**Comment by burtlo** [comment]
Farewell, my old friend.

**Comment by lmayorga1980** [comment]
@glennsarti ,

Worked by adding `support for windows`.

https://github.com/inspec/inspec/blob/master/lib/inspec/resources/http.rb#L13

![Screenshot from 2019-06-26 11-07-05](https://user-images.githubusercontent.com/3172378/60191625-a2c9c700-9802-11e9-92ef-a95ddbf967a6.png)
