### ISSUE TITLE
[BUG] Wrong supports platform in  inspec/lib/resources/audit_policy.rb

### ISSUE THREAD

**Issue by mhackethal** [inspec/inspec#2829]
### 🎛 Description

[BUG]
In the resource audit_policy there is the wrong supports platform set.
In the current files it states "supports platform: 'unix' but these test is designed for windows.

File:  inspec/lib/resources/audit_policy.rb

### 🌍 InSpec and Platform Version

Version 2.0.47 and also i see this in the current git-hub release Version 2.0.49

### 🤔 Replication Case

If you run an Audit_Policy tests against a windows system with winRM the result is always "skipped"
[SKIP] Resource Audit_policy is not  supported on platform windows_server_2016_standard/10.....

### 💁 Possible Solutions

possible Solution: Change supports platform from 'unix' to 'windows'.
At least in my tests it works as i expected.
### 💻 Stacktrace

Trace not needed think,.

**Comment by jquick** [comment]
Thanks for reporting this @mhackethal !
