### ISSUE TITLE
exec with --no-create-lockfile will generate a inspec.lock if provided before profiles

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2835]
### 🎛 Description

This a 🐛 bug report.

When you perform a scan with a profile and you do not want to generate a lockfile you can provide the `--no-create-lockfile`. Providing it before you specify the profile or control files will still generate the lockfile.

### 🌍 InSpec and Platform Version

InSpec 2.0.32, Mac OSX 10.13.3

### 🤔 Replication Case

Running it this way does not generate the lock file

```shell
$ tree tomcat
tomcat
├── README.md
├── controls
│   └── example.rb
├── inspec.yml
└── libraries

2 directories, 3 files
$ inspec exec tomcat --no-create-lockfile

Profile: InSpec Profile (tomcat)
Version: 0.1.0
Target:  local://
...
Profile Summary: 0 successful controls, 3 control failures, 0 controls skipped
Test Summary: 0 successful, 6 failures, 0 skipped
$ tree tomcat
tomcat
├── README.md
├── controls
│   └── example.rb
├── inspec.yml
└── libraries

2 directories, 3 files
```

Running it this way will generate the lock file

```shell
$ tree tomcat
tomcat
├── README.md
├── controls
│   └── example.rb
├── inspec.yml
└── libraries

2 directories, 3 files
$ inspec exec --no-create-lockfile tomcat 

Profile: InSpec Profile (tomcat)
Version: 0.1.0
Target:  local://
...
Profile Summary: 0 successful controls, 3 control failures, 0 controls skipped
Test Summary: 0 successful, 6 failures, 0 skipped
$ tree tomcat
tomcat
├── README.md
├── controls
│   └── example.rb
├── inspec.lock
├── inspec.yml
└── libraries

2 directories, 4 files
```

### 💁 Possible Solutions

I assume that all parameters can be used in any position with the command.

**Comment by jquick** [comment]
Thanks for this report @burtlo.

**Comment by jquick** [comment]
Looked into this a bit, seems to happen with any `--no` Boolean flags and it only happens directly before the first argument. Seems to be a issue with Thor. Looking to see if we can fix it on our end.

**Comment by jquick** [comment]
Looks like this is fixed in Thor https://github.com/erikhuda/thor/issues/472 version 0.20.0 should have the fix.
