### ISSUE TITLE
Allow InSpec to chain require dependencies in resources

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#2844]
### 🎛 Description

This is a old issue where if your trying to chain requires in a resource and have them be called during a `describe` block it would fail. 

For test case please see the PR here: https://github.com/chef/inspec/pull/818/files

Notes to implementer: Please use the above PR as a baseline. It will need to be rebased to reflect our current codebase.

**Comment by TheLonelyGhost** [comment]
@jquick Possibly related to #2861

**Comment by jquick** [comment]
This issue with multiple requires is working fine under the newest version of inspec 2.0. The issue with pathing and require_relative will be handled in #2861
