### ISSUE TITLE
Pip inspec resource fails on Windows when there is a new version of Pip available

### ISSUE THREAD

**Issue by jvanbrunschot-coolblue** [inspec/inspec#2855]
### 🎛 Description
[BUG]
When using the Pip resource on Windows the check fails when a new version of Pip is available.

### 🌍 InSpec and Platform Version

$ chef --version
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

Running inspec using kitchen.

### 🤔 Replication Case

Have a Windows 2016 Core box with an out-of-date Pip version. Let's say 9.0.1 and the latest version is 9.0.2.

Have a test that verifies if a Pip packages is installed, like the one in the examples for Jinja2

### 💁 Possible Solutions

https://github.com/chef/inspec/blob/master/lib/resources/pip.rb#L40

The command Inspec runs is `pip show [package_name]`. Inspec will parse the outcome of that command in key/value pairs based on a regex. It seems that is silently fails parsing the info due to the `You are using pip version 9.0.1, however version 9.0.2 is available.` message.

**Comment by jquick** [comment]
Thanks for this report @jvanbrunschot-coolblue !
