### ISSUE TITLE
Profile path appears in `inspec.yml`

### ISSUE THREAD

**Issue by johnfitzpatrick** [inspec/inspec#2856]
### 🎛 Description

**Choose one:** is this a 🐛 bug report 

There seems to be some inconsistent behaviour creating a profile using a relative path, ala `inspec init profile profiles/foo`, when using InSpec 2.0.  

It instantiates the profile in the correct directory fine, but it then uses that directory name as part of the profile name in `inspec.yml`.  I’d expect it to `.gsub(/profiles\//, "")` the command just use `foo` as the name.

When you `inspec check` the profile it throws a *warning* (and not an *error*) saying the slash isn’t permitted in InSpec 2.0.

If it allows a relative path in the command, why does it include that directory name in the profile name?  And if its says the “slash is not permitted in InSpec 2.0”, then why do I just get a *warning* and not an *error* when I’m using InSpec v2.0

### 🌍 InSpec and Platform Version

```
$ inspec detect

== Platform Details

Name:      centos
Families:  redhat, linux, unix
Release:   7.4.1708
Arch:      x86_64
```
```
[chef@ip-172-31-27-216 ~]$ inspec version
2.0.45

Your version of InSpec is out of date! The latest version is 2.1.0.
```

### 🤔 Replication Case

```
[chef@ip-172-31-27-216 ~]$ ls -l
drwxrwxr-x. 3 chef chef       25 Mar 16 13:41 profiles

#profile is created in the correct directory
[chef@ip-172-31-27-216 ~]$ inspec init profile profiles/foo
Create new profile at /home/chef/profiles/foo  
* Create file README.md
* Create directory controls
* Create file controls/example.rb
* Create file inspec.yml
* Create directory libraries


#directory name is part of the profile name
[chef@ip-172-31-27-216 ~]$ cat profiles/foo/inspec.yml
name: profiles/foo   
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0

#I'm using v2, but it says the '/' is not permitted in v2 and I just get a warning below 
[chef@ip-172-31-27-216 ~]$ inspec --version
2.0.45   

#says 'will not be permitted' above, but I only get a *warning*, not an *error*
[chef@ip-172-31-27-216 ~]$ inspec check profiles/foo
Location:    profiles/foo
Profile:     profiles/foo
Controls:    2
Timestamp:   2018-03-21T10:54:11+00:00
Valid:       true

  !  profiles/foo/inspec.yml:0:0: Your profile name (profiles/foo) contains a slash which will not be permitted in InSpec 2.0. Please change your profile name in the `inspec.yml` file.     

Summary:     0 errors, 1 warnings    

[chef@ip-172-31-27-216 ~]$
```

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by jquick** [comment]
Thanks for this report @johnfitzpatrick !

**Comment by chris-rock** [comment]
This is related to https://github.com/chef/inspec/pull/2538 @miah Any updates on this PR?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please reopen the issue and continue the discussion, making sure to provide stack trace or repro data that is relevant to the current version.

Thank you!
__Chef InSpec Team__
