### ISSUE TITLE
Project should define how it implements semantic versioning.

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2859]
### 🎛 Description

This a 🙋 feature request.

I am using InSpec 2.0.32 (2018-03-01). The release of InSpec 2.0.45 (2018-03-08) changed the interface of the `shadow` resource.

### 💁 Possible Solutions

* Should this release have been a minor release and not a patch?

It would be helpful if this project defined what it considers a major change, a minor change, and a patch change. Changing the interface of a resource feels like a minor change to me.

**Comment by clintoncwolfe** [comment]
For my part, I agree. It would be good to have a discussion on this, and then distill it into a public policy document.  

Additionally, our changelog system already watches for GitHub tags; perhaps we could extend that to version bumping as well.

**Comment by clintoncwolfe** [comment]
We do try to follow semantic versioning; the shadow incident was isolated.  We also have CI tagging in place.
