### ISSUE TITLE
Docs site always displays latest version of resources without access to older versions.

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2860]
### 🎛 Description

This a 🐛 bug report and 🙋 feature request.

I am using InSpec 2.0.32 (2018-03-01). The release of InSpec 2.0.45 (2018-03-08) changed the interface of the `shadow` resource. The documentation site was updated to describe the newer interface that is not compatible with the older interface.

### 💁 Possible Solutions

* Should the documentation be versioned along with the releases?

The documentation is always showing the latest deployed version of the website and does not display which version it is describing. It also provides no interface for me to select an older version of the documentation.

**Comment by burtlo** [comment]
@kagarmoe, I was bitten by docs that were too up-to-date.

**Comment by clintoncwolfe** [comment]
+1 for versioned docs with "latest" being the default.

**Comment by mirskiy** [comment]
This issue still affects me.
