### ISSUE TITLE
Broken ruby: require_relative and __FILE__

### ISSUE THREAD

**Issue by TheLonelyGhost** [inspec/inspec#2861]
### 🎛 Description

🐛 Bug Report

Due to how profiles are loaded, the path to a given ruby file is clobbered thereby breaking things like the `__FILE__` constant, `require_relative`, and `require './foo'`. The `__FILE__` constant from within a file in `libraries/` always assumes the path to the profile is the current working directory, even if inspec is invoking a profile in another directory (e.g., `inspec exec ./some/path/to_a/profile`). Expected result is the correct path on the filesystem for `__FILE__`.

### 🌍 InSpec and Platform Version

Affects all versions of InSpec to date and all platforms, but for the sake of consistency:

macOS 10.13.3 with InSpec v1.51.21 (via ChefDK v2.5.3)

### 🤔 Replication Case

Create a new profile with `inspec init profile test-profile` and fill it with the following files:

```ruby
# File: test-profile/controls/default.rb

describe true do
  it { should eq true }
end
```

```ruby
# File: test-profile/libraries/foo.rb
require_relative '../foo_lib'

raise 'IT WORKS!' if MySuperUsefulLibrary.should_be_true?
raise 'It failed...'
```

```ruby
# File: test-profile/foo_lib.rb

module MySuperUsefulLibrary
  def self.should_be_true?
    true
  end
end
```

Expected result:

```bash
$ inspec init profile test-profile
# [fills with files]
$ inspec exec test-profile
IT WORKS!
$ cd test-profile
$ inspec exec .
IT WORKS!
$
```

Actual result:

```bash
$ inspec init profile test-profile
# [fills with files]
$ inspec exec test-profile
libraries/foo.rb:1:in `require_relative': cannot load such file -- ([snip]) LoadError
# [some super long stack trace]
$ cd test-profile
$ inspec exec .
IT WORKS!
$
```

### 💁 Possible Solutions

[`lib/source_readers/inspec.rb` lines 54 - 73](https://github.com/chef/inspec/blob/8d8edea7f3161a15b59c0742de4b672f83ca5868/lib/source_readers/inspec.rb#L54-L73) use a [`FileProvider`](https://github.com/chef/inspec/blob/8d8edea7f3161a15b59c0742de4b672f83ca5868/lib/inspec/file_provider.rb) interface to read the contents of the profile's files into a hash, then essentially eval the content one at a time. Because it is eval'ed, some internal mechanisms Ruby uses to determine the path to that file are completely disregarded. Using Ruby's existing mechanisms for loading ruby files (e.g., `load` and `require`) would avoid that clobbering.

It looks like every fetcher follows the same heuristic:

1. download, unzip/-tar, or otherwise get the profile's source files into some temp directory for reading
2. list out each file for the profile
3. provide a method to read the contents of those files

If the `FileProvider` instead (or also) provided a path to the temp directory where the profile lives, it would vastly simplify the loading mechanisms by using ruby's built-in [`Kernel.load` method](http://ruby-doc.org/core-2.5.0/Kernel.html#method-i-load) (which even allows loading it in the context of a module, such as certain context-specific DSLs).

### 💻 Stacktrace

_N/a_

**Comment by TheLonelyGhost** [comment]
Okay, looking at the [`ZipProvider`](https://github.com/chef/inspec/blob/8d8edea7f3161a15b59c0742de4b672f83ca5868/lib/inspec/file_provider.rb#L109) and [`TarProvider`](https://github.com/chef/inspec/blob/8d8edea7f3161a15b59c0742de4b672f83ca5868/lib/inspec/file_provider.rb#L154) classes it looks like it prefers to explode (unzip or untar) them in-memory and read the contents of the files.

This gives some level of justification to why we were eval-ing the contents of files, but I'd much prefer to actually unzip them to a temp directory and read the contents that way. I am curious how that might affect speeds of testing with additional disk IO... 🤔

**Comment by clintoncwolfe** [comment]
A big +1 on this; this issue has caused me much grief when inspec-aws was a "resource pack".  Once it was moved into core, it was no longer under resource/library loading discipline, and Ruby behaved much saner.  I'm pretty sure @arlimus disagrees, though; concerns over breaking "profile encapsulation".

**Comment by TheLonelyGhost** [comment]
I completely get the argument that ruby doesn't sufficiently encapsulate when using a plugin approach to software. I'm much more a fan of how Python or Java handles imports for reasons of encapsulation.

In this case, I think it's a more complicated issue. Do we want to try to insulate ourselves from how ruby has operated for years (creating a mosh pit of all ruby source code `require`'d by any gem in a global scope) or do we want to build walls and try to sandbox it?

If we want to create a better sandbox than what ruby provides by default (and believe me, I am all for it), perhaps that should be spun off into a separate gem? It seems outside of the concern of InSpec's mission for infrastructure end-state testing.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
