### ISSUE TITLE
Defining an attribute without a default value generates a stacktrace

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2865]
### 🎛 Description

This a 🐛 bug report

Defining a profile attribute without a default value results in a stacktrace that tells the user it cannot convert the InSpec::Attribute::DEFAULT_ATTRIBUTE to String.

### 🌍 InSpec and Platform Version

InSpec 2.1.0
Workstation: Mac 10.13.3

### 🤔 Replication Case

Define an attribute without a default value that you plan to use within a control that expects a String.

```ruby
pass = attribute('pass', description: 'passphrase for the secret-key')

describe key_rsa('/home/chef/.ssh/secret-key',pass) do
  it { should be_private }
end
```

Execute a scan:

```shell
$ inspec exec myprofile --sudo -t ssh://username:password@target
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspect-2.1.0/lib/resources/key_rsa.rb:32:in `read': can't convert InSpec::Attribute::DEFAULT_ATTRIBUTE to String (InSpec::Attribute::DEFAULT_ATTRIBUTE#to_str gives InSpec::Attribute::DEFAULT_ATTRIBUTE) (TypeError)
```

### 💁 Possible Solutions

* Fail the run without generating a stacktrace.

The control should fail but not fail the run.

* Inform the user that they need to provide a default value

* Prompt the user to enter a default value at run-time.

### 💻 Stacktrace

SEE ABOVE

**Comment by clintoncwolfe** [comment]
Thanks @burtlo - that's a good catch!

**Comment by jquick** [comment]
Thanks for this. We are going to `warn` when calling a unknown default.
