### ISSUE TITLE
We should have a maintained list of known system users for the 'users' or 'platform' resource with platforms.

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#2877]
### 🎛 Description
🙋 feature request

Given that most of the major distributions maintain a list of 'Standard Users' - perhaps we could maintain this in the `users` resource or as part of the the `os.platform.<family>` resource.

* https://www.centos.org/docs//2/rhl-rg-en-7.2/s1-users-groups-standard-users.html
* https://www.debian.org/doc/manuals/securing-debian-howto/ch12.en.html

Consider the following example, in the end, I think we as a community could better maintain these 'known system / platform users' with better consistency and thus better security.

```
# Will need to have attribute updated in YML to reflect list of authorized system accounts
KNOWN_SYSTEM_ACCOUNTS = attribute(
  'known_system_accounts',
  default: [
        'root',
        'bin',
        'daemon',
        'adm',
        'lp',
        'sync',
        'shutdown',
        'halt',
        'mail',
        'operator',
        'nobody',
        'systemd-bus-proxy',
        'systemd-network',
        'dbus',
        'polkitd',
        'tss', #  Account used by the trousers package to sandbox the tcsd daemon
        'postfix', # Service Account for Postfix Mail Daemon
        'chrony', # Service Account for the Chrony Time Service
        'sshd', # Service Account for SSH
        'ec2-user', # Service Account for EC2 Access in AWS
        'sssd', # Service Account for the SSSH Authentication service
        'rpc', # Service Account RPCBind Daemon
        'unbound', # Service Account UnBound Daemon
        'ntp', # Service Account for NTPD Daemon
        'vboxadd', # known Virtualbox user
        'nfsnobody', # service account for nsfd
        'vagrant', # known service account for vagrant / Virtualbox
        'nginx', # known service account for nginx web-server
        'rpcuser', # known centos system account for nsf
        'apache', # known apache system account
        'mysql', # known mysql system account
  ],
  description: 'System accounts that support approved system activities. (Array)'
)

DISALLOWED_ACCOUNTS = attribute(
  'disallowed_accounts',
  description: 'Accounts that are not allowed on the system (Array)',
  default: [
    'games',
    'gopher',
    'ftp',
  ]
)

USER_ACCOUNTS = attribute(
  'user_accounts',
  description: 'accounts of known managed users (Array)',
  default:[]
)

ALLOWED_ACCOUNTS = attribute(
  'allowed_accounts',
  description: 'allowed accounts from USER_ACCOUNTS + KNOWN_SYSTEM_ACCOUNTS (computed Array)',
  default: (KNOWN_SYSTEM_ACCOUNTS + USER_ACCOUNTS).uniq
)

control "V-72001" do
  title "The system must not have unnecessary accounts."
  desc  "Accounts providing no operational purpose provide additional opportunities
for system compromise. Unnecessary accounts include user accounts for individuals
not requiring access to the system and application accounts for applications not
installed on the system."
  impact 0.5
  tag nist: ['CM-6', 'rev_4']
  tag "check": "Verify all accounts on the system are assigned to an active system,
application, or user account.

Obtain the list of authorized system accounts from the Information System Security
Officer (ISSO). Accounts such as \"games\" and \"gopher\" are not authorized accounts as they do not
support authorized system functions.

If the accounts on the system do not match the provided documentation, or accounts
that do not support an authorized system function are present, this is a finding."

tag "fix": "Configure the system so all accounts on the system are assigned to an
active system, application, or user account.

Remove accounts that do not support approved system activities or that allow for a
normal user to perform administrative-level actions. Document all authorized accounts on the system."

  describe "No documented disallowed users: #{DISALLOWED_ACCOUNTS}," do
    subject { DISALLOWED_ACCOUNTS }
    describe "exist that" do
      it { should_not be_in users.usernames }
    end
  end

  describe "The number of undocumented accounts" do
    subject { users.usernames - ALLOWED_ACCOUNTS }
    it { should be nil }
  end
end
```
Rather than having to maintain a list of known accounts in an attribute which will get out of sync across controls, it would be great to be able to say something like:

`inspec.os.platform[rhel].system_accounts`
or
`inspec.os.platform.family[rhel7].system_accounts`

**Comment by aaronlippold** [comment]
We could even assert that inspec already knows the platform and family so something like: 

`inspec.platform.system_accounts` should not need any params by default.

**Comment by jquick** [comment]
This would be quite a bit to maintain going forward, and really could be different users per setup. I do like the idea though. I don't think this belongs in `os` or `platform` resources though, and would rather it be defined on a profile level for your specific install.

**Comment by chris-rock** [comment]
While I see some use cases, in most cases, especially in cloud and docker environments, those user configurations will not be applicable. Therefore I agree with @jquic that the list should be packaged with the InSpec profile. 

In case you need those in multiple-profiles, I recommend using an approach that we used for the ssh-baseline https://github.com/dev-sec/ssh-baseline/blob/master/libraries/ssh_crypto.rb#L68

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
