### ISSUE TITLE
`30s cmp <= 60` should be true

### ISSUE THREAD

**Issue by rachelrice** [inspec/inspec#2880]
### 🎛 Description

`30s should cmp <= 60` is pulling in the s which doesn't allow comparison against 60. This causes an invalid failure.

```
 ✔  File /etc/ssh/sshd_config content should match /^\s*LoginGraceTime\s+(\S+)\s*(?:#.*)?$/
 ×  30s should cmp <= 60

 expected it to be <= 60
      got: 30s
```

### 🌍 InSpec and Platform Version

Have reproduced the issue with inspec-2.1.0.

### 🤔 Replication Case

Issue seen with the following control:
```
control "LoginGraceTime" do
  title "Ensure SSH LoginGraceTime is set to one minute or less"
  describe file("/etc/ssh/sshd_config") do
    its("content") { should match(/^\s*LoginGraceTime\s+(\S+)\s*(?:#.*)?$/) }
  end
  file("/etc/ssh/sshd_config").content.to_s.scan(/^\s*LoginGraceTime\s+(\S+)\s*(?:#.*)?$/).flatten.each do |entry|
    describe entry do
      it { should cmp <= 60 }
    end
  end
end
```
### 💁 Possible Solutions

cmp should support optional time values - h, m, s - in config files.

**Comment by chris-rock** [comment]
@rachelrice thank you for bringing up this question. This is not an easy problem to solve. Once we start handling dates, we need to start thinking about:
- all kind of date formats (days, d, 12:12 ...)
- parse and compare dates properly
- distinguish between date, time and duration

For now, I recommend to write a custom InSpec resource that returns a given input to seconds. Lets assume we have the following entry in `sshd_config`:

```
LoginGraceTime 1m
```
Then we could adapt the tests to:
```
# controls/test.rb
control "LoginGraceTime" do
    title "Ensure SSH LoginGraceTime is set to one minute or less"
    describe file("/etc/ssh/sshd_config") do
        its("content") { should match(/^\s*LoginGraceTime\s+(\S+)\s*(?:#.*)?$/) }
    end
    file("/etc/ssh/sshd_config").content.to_s.scan(/^\s*LoginGraceTime\s+(\S+)\s*(?:#.*)?$/).flatten.each do |entry|
        describe duration(entry) do
            its('seconds') { should cmp <= 60 }
        end
    end
end

control 'Test' do
    describe duration(sshd_config.LoginGraceTime) do
        its("seconds") { should cmp <= 60 }
    end
end
```

with the custom inspec resource:
```
# libraries/duration.rb
class Duration < Inspec.resource(1)
    name 'duration'

    desc "
        Normalize durations to seconds from sshd_config
    "

    TOKENS = {
        "m" => (60),
        "h" => (60 * 60),
        "d" => (60 * 60 * 24)
    }

    def initialize(duration)
        @duration = duration
    end

    def seconds
        parse(duration)
    end

    def parse(duration)
        time = 0
        duration.scan(/(\d+)(\w)/).each do |amount, measure|
          time += amount.to_i * TOKENS[measure]
        end
        time
    end

    def to_s
        "duration"
    end
end
[login-0.1.0.tar.gz](https://github.com/chef/inspec/files/1851330/login-0.1.0.tar.gz)

```

This will result in:
```
  ✔  LoginGraceTime: Ensure SSH LoginGraceTime is set to one minute or less
     ✔  File /etc/ssh/sshd_config content should match /^\s*LoginGraceTime\s+(\S+)\s*(?:#.*)?$/
     ✔  duration seconds should cmp <= 60
  ✔  Test: duration
     ✔  duration seconds should cmp <= 60


Profile Summary: 2 successful controls, 0 control failures, 0 controls skipped
Test Summary: 3 successful, 0 failures, 0 skipped
```

Please find attached the example profile.

[login-0.1.0.tar.gz](https://github.com/chef/inspec/files/1851332/login-0.1.0.tar.gz)

**Comment by clintoncwolfe** [comment]
As this hasn't seen any movement in a while and a solution was provided, I'm closing this.  Please do re-open if you feel more is needed here.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
