### ISSUE TITLE
Check for Terraform update for integration tests

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2884]
### 🎛 Description

🙋 feature request

We currently pin TF to 0.10.x, based needing to stay on a version that worked with the azure and aws plugins needed.  Is that still true?  TF is currently on 0.11.x, can we move to that?

### 🌍 InSpec and Platform Version

2.1.14, master tip a5ff79d30

### 🤔 Replication Case

Running `bundle exec rake test:aws` will require TF 0.10 and pinned plugins.

### 💁 Possible Solutions

Try pinning to 0.11.x, and loosening the azure and aws pins to see if the latest works.

**Comment by aaronlippold** [comment]
We have been running on the current TF without issues but @rx294 and @dromazmj would know the best answer with respect to the integration tests
