### ISSUE TITLE
 InSpec won't admit that port 5432 is listening inside a PostgreSQL container

### ISSUE THREAD

**Issue by todd-a-jacobs** [inspec/inspec#2890]
# Background
I'm trying to test a [standard PostgreSQL container][1] with InSpec 2.1.10, but I cannot get a simple port check to return true, even though Docker, netstat, and psql all report that the port is properly mapped. While it's possible this is a bug in InSpec, it's also possible that the problem exists between the keyboard and the chair.

# Repeatable Tests
## My Spec

    # port_test.rb
    describe port(5432) do
      it { should be_listening }
    end

## My Testing Commands

    container=$(docker run -d -P --rm postgres:alpine)
    inspec exec port_test.rb -t docker://$container

## My Output
>     Profile: tests from test.rb (tests from test.rb)
>     Version: (not specified)
>     Target:  docker://8caceaa7e2eefa4a2bf50a58ea1ddf9c927c08d3397e3d9ad5b60d3519971380
>    
>     Port 5432
>        ×  should be listening
>        expected `Port 5432.listening?` to return true, got false
>    
>     Test Summary: 0 successful, 1 failure, 0 skipped

## But It Should Work!
Everything but InSpec reports that things are working as expected.

    $ docker port $container
    5432/tcp -> 0.0.0.0:32770

    # from inside container using netstat
    $ docker exec $container netstat -lntp
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      -
    tcp        0      0 :::5432                 :::*                    LISTEN      -

    # on macOS Docker host; flags are the macOS equivalent to `-lntp`
    $ netstat -anv | fgrep $(docker port $container | cut -d: -f2)
    tcp6       0      0  ::1.32770              *.*                    LISTEN      131072 131072    709      0
    tcp4       0      0  *.32770                *.*                    LISTEN      131072 131072    709      0

    # connecting to database in container from host
    $ psql -V \
           -h localhost \
           -p $(docker port $container | cut -d: -f2)
    psql (PostgreSQL) 10.3

  [1]: https://hub.docker.com/_/postgres/
  [2]: https://www.inspec.io/

**Comment by todd-a-jacobs** [comment]
According to [this answer][1] on DevOps Stack Exchange:

> [T]he problem is that Apline's netstat reports a different output then other Linux eg. Ubuntu, CentOS:
> 
>     # netstat -tulpen
>     Active Internet connections (only servers)
>     Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name    
>     tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      999        108791     -                   
>     tcp6       0      0 :::5432                 :::*                    LISTEN      999        108792     -  
>
> On Alpine, the inode output is missing:
>
>     netstat -tulpen
>     Active Internet connections (only servers)
>     Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
>     tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      -
>     tcp        0      0 :::5432                 :::*                    LISTEN      -
>
> That is why InSpec is not able to parse the netstat output. It is clearly a bug in InSpec. As a mitigation, I recommend to install the iproute2 package for alpine containers via apk add iproute2. InSpec prefers ss over netstat. Please report this bug to InSpec team.

I can verify that using _postgres:latest_ instead of _postgres:alpine_ works as expected, and that adding _iproute2_ to the Alpine-based container also resolved the issue.

[1]: https://devops.stackexchange.com/a/3760/549

**Comment by aaronlippold** [comment]
We could also just adjust the the resource to detect the variant in the
platform and adjust its parsing, we've done this and other resources.
Requiring a package that's outside the standard delivery process seems a
bit outside the scope of inspec.

**Comment by todd-a-jacobs** [comment]
@aaronlippold: Agreed. I wasn't suggesting that InSpec should add packages to a target container; I was just validating that the parsing problem wasn't present in the output from iproute2. Branching on the distro, or perhaps just based on whether netstat is really BusyBox, is likely to be the right thing to do.

If the latter, the following returns exit status 0 on Alpine:

    stat $(which netstat) | grep -Eq 'File:.*busybox'

On the other hand, the existence or contents of `/etc/alpine-release` may be better for branching if the solution should be more distro- than binary-centric. I'm honestly not sure which is a better solution from an InSpec perspective, and there is certainly more than one way to do the detection.

**Comment by frezbo** [comment]
I had a similar issue with redhat docker image as it does not by default have *net-tools* or *ss* package 
I fixed it by adding those to the base image.
