### ISSUE TITLE
How to unit test inspec tests?

### ISSUE THREAD

**Issue by ibata** [inspec/inspec#2895]
what's the best way  to unit testing my inspect tests
i'm using "inspec check url" 

my test located under: test/integration/ktf_suite/controls/reach_host.rb:
```ruby
control 'reach_host' do
  impact 1.0
  title 'This is Testing Endpoint'
  describe http("url", ssl_verify: false) do
    its('status') { should eq 200 }
    its('body') { should cmp %r{<h3>some content</h3>} }
  end
end
```

```bash
$ inspec --help
Commands:
  inspec archive PATH                # archive a profile to tar.gz (default) ...
  inspec check PATH                  # verify all tests at the specified PATH
  inspec compliance SUBCOMMAND ...   # Chef Compliance commands
  inspec detect                      # detect the target OS
  inspec exec PATH(S)                # run all test files at the specified PATH.
  inspec help [COMMAND]              # Describe available commands or one spe...
  inspec init TEMPLATE ...           # Scaffolds a new project
  inspec json PATH                   # read all tests in PATH and generate a ...
  inspec shell                       # open an interactive debugging shell
  inspec supermarket SUBCOMMAND ...  # Supermarket commands
  inspec version                     # prints the version of this tool

Options:
  [--diagnose], [--no-diagnose]  # Show diagnostics (versions, configurations)
```

**Comment by clintoncwolfe** [comment]
[`inspec check`](https://www.inspec.io/docs/reference/cli/#check) performs a validity check on the code you provide.  It checks for common problems, and _avoids_ running your tests.  That's probably not enough when doing profile development.

You are likely looking for [`inspec exec`](https://www.inspec.io/docs/reference/cli/#exec), which actually does run your tests.  You can use the `-t` option to select what to run it against, such as a docker container or an ec2 instance, that you have spun up for testing.

**Comment by clintoncwolfe** [comment]
Hi! It's been a few days since an answer was provided, and there has been no more traffic on this issue, so I'm going to close it.  If you'd like to discuss further, please feel free to re-open!
