### ISSUE TITLE
Do not require resource names for AWS Config objects

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2900]
### 🎛 Description

🐛 bug report

Bug, or at least a misfeature.  `aws_config_recorder` and `aws_config_delivery_channel` currently require you to provide the name of the Recorder or Delivery Channel.  However, AWS Config Recorders and Delivery Channels are singleton-per-region (and our InSpec runs are per-region).

If the resource name was optional, the AWS API is able to list the existing recorders, and you could get the singleton recorder without specifying a name.

We should add code that throw an exception if more than one resurce is returned, in case AWS starts supporting multiple recorder.  That behavior would match our typical response when multiples match.

### 🌍 InSpec and Platform Version

2.1.17

### 💁 Possible Solutions

Don't require a resource_name; when you call `describe_config_recorder` with no args, it will return all (presumably, one or zero) recorders.

**Comment by chris-rock** [comment]
This is a very nice idea!

**Comment by clintoncwolfe** [comment]
In progress on https://github.com/chef/inspec/tree/cw/aws-config-name-by-default
