### ISSUE TITLE
oracledb_session error on a server running Oracle 12cR2

### ISSUE THREAD

**Issue by thiagoamaciel** [inspec/inspec#2907]
### Description

🐛 bug report

**The following control works in an Oracle 11g server but fails in an Oracle 12cR2 Server**

```
sql = oracledb_session(user:'system', password:'PPPPP', host:'11gServer',port:'1527',service:'orcl11g')

describe sql.query('SELECT NAME FROM v$database;').row(0).column('name') do
    its('value') { should cmp 'ORCL11G' }
end
```

**Oracle 11g server**

> inspec exec translated-controls.rb  -t ssh://YYYYY@11gServer  --password 'PPPPPP'
> 
> Profile: tests from translated-controls.rb (tests from translated-controls.rb)
> Version: (not specified)
> Target:  ssh://YYYYY@11gServer:22
> 
>   SQL Column
>      ✔  value should cmp == "ORCL11G"
> 
> Test Summary: 1 successful, 0 failures, 0 skipped

**Oracle 12cR2 Server**

> inspec exec translated-controls.rb  -t ssh://XXXXX@12cServer  --password 'PPPPPP'
> 
>   SQL Column
>      ∅  value
>      undefined method `[]' for nil:NilClass
> 
> Test Summary: 0 successful, 1 failure, 0 skipped
> 

**There is no error if i execute the command resource, calling the sqlplus, on the 12c server:**

```
describe command("sqlplus system/ppppp@12cServer:1527/orcl12c @/home/xxxx/teste.sql |grep ""ORCL12C""") do
  its(:stdout) { should match(/ORCL12C/) }
end
```

> inspec exec translated-controls.rb  -t ssh://XXXXX@12cServer  --password 'PPPPPP'
> 
>   Command sqlplus system/ppppp@12cServer:1527/orcl12c @/home/xxxx/teste.sql |grep ORCL12C
>      ✔  stdout should match /ORCL12C/
> 
> Test Summary: 1 successful, 0 failures, 0 skipped
> 

**Finally, if i configure the oracledb_session to run the sql command against the 12c instance, and calling inspec to execute on the 11gServer, it runs just fine either:**

```
sql = oracledb_session(user:'system', password:'PPPPP', host:'12cServer',port:'1527',service:'orcl12c')

describe sql.query('SELECT NAME FROM v$database;').row(0).column('name') do
    its('value') { should cmp 'ORCL12C' }
end
```

> inspec exec translated-controls.rb  -t ssh://XXXX@11gServer  --password 'PPPP'
> 
> Profile: tests from translated-controls.rb (tests from translated-controls.rb)
> Version: (not specified)
> Target:  ssh://XXXX@11gServer:22
> 
>   SQL Column
>      ✔  value should cmp == "ORCL12C"
> 
> Test Summary: 1 successful, 0 failures, 0 skipped

### 🌍 InSpec and Platform Version

Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

### **Oracle Environment**

Linux x86 64-bit (3.10.0-693.2.2.el7.x86_64)
Oracle 12.2.0.1.0 / Oracle 11.2.0.4

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
