### ISSUE TITLE
Add LXC Backend

### ISSUE THREAD

**Issue by thedrow** [inspec/inspec#2912]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Feature Request

Serverspec allows users to test LXC containers by attaching to them and executing commands.
Inspec should have the same feature.

### 🌍 InSpec and Platform Version
I'm not using InSpec right now.

**Comment by clintoncwolfe** [comment]
InSpec uses [Train](https://github.com/chef/train) to implement new transports.  From InSpec's perspective, if Train knows about the plugin, InSpec is happy.

I suggest you open a feature request against the Train repo.  Thanks!

**Comment by thedrow** [comment]
Done. https://github.com/chef/train/issues/280
