### ISSUE TITLE
unable to validate ec2 components using test-kitchen inspec for terraform builds. 

### ISSUE THREAD

**Issue by esaravanakumar89** [inspec/inspec#2916]
### 🎛 Description

**Choose one:** is this a 🐛 bug report ?

When i am trying to validate the ec2 instances using test-kitchen with kitchen-terraform am getting 
Connection expired to aws. 

### 🌍 InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
inspec - 2.1.10
test-kitchen-1.20.0
kitchen-terraform-3.3.0

### 🤔 Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

validate ec2 components using test-kitchen and also with kitchen-terraform

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

[2018-04-04T21:07:32+00:00] DEBUG: Assuming default supermarket source for {:cwd=>"./", :backend=>Inspec::Backend::Class @transport=Train::Transports::Local::Connection, :name=>"aws"}
 ------Exception-------
Class: Kitchen::ActionFailed
Message: 1 actions failed.
    Failed to complete #verify action: [execution expired] on default-test-ec2-rhel

Please see .kitchen/logs/kitchen.log for more details
 Also try running `kitchen diagnose --all` for configuration

  ------Exception-------
   Class: Kitchen::ActionFailed
   Message: 1 actions failed.
   Failed to complete #verify action: [execution expired] on default-test-ec2-rhel
D      ----------------------
D      ------Backtrace-------
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:183:in `report_errors'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command.rb:174:in `run_action'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /usr/local/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/command/action.rb:34:in `call'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:52:in `perform'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in `block in <top (required)>'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.20.0/bin/kitchen:13:in `<top (required)>'
D      /usr/local/bin/kitchen:23:in `load'
D      /usr/local/bin/kitchen:23:in `<main>'
D      ----End Backtrace-----

**Comment by clintoncwolfe** [comment]
@esaravanakumar89 , could you provide more information about how to replicate this?  Perhaps your `.kitchen.yml` ?

**Comment by esaravanakumar89** [comment]
Apologize for the delayed reply, It caused due to  wrongly configured inspec.yml. I was given depends: aws so it was trying to download the aws modules from supermarket. My machine is not having connectivity to supermarket, So it caused the issue.

**Comment by clintoncwolfe** [comment]
OK.  the AWS resources are now in core inspec since about version 2.0 .  If you have that version or later, you don't need to have a 'depends: aws' entry.  (Though you will need internet connectivity if you wish to use the resources, as they talk to the AWS API).

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
