### ISSUE TITLE
How to use "focus" like in ServerSpec?

### ISSUE THREAD

**Issue by thbar** [inspec/inspec#2917]
I'm coming from ServerSpec & starting to use InSpec for a client.

When working with ServerSpec, I will often use `focus: true` on a given example, to iterate faster while I'm still implementing it.

(this is backed by `rspec` [tag implementation](https://relishapp.com/rspec/rspec-core/v/3-7/docs/command-line/tag-option)).

I went through the `inspec exec` documentation but so far I cannot figure out how to mimic that behaviour with InSpec.

What is the recommended way to run only a couple of tests in a full suite?

Thanks!

**Comment by clintoncwolfe** [comment]
If you're placing your tests within controls (which are like `describe` blocks, but with more metadata), you can isolate the run by control name.  See the `--controls` option to [`inspec exec`](https://www.inspec.io/docs/reference/cli/#exec)

Additionally, `inspec exec` is happy to run just a single `.rb` file.  So if you have a profile with several files, you can partially isolate this way:

```
inspec exec my-profile/
# Lots of stuff, long to run
inspec exec my-profile/controls/just-one-file.rb
# Just what's in the file
```

**Comment by clintoncwolfe** [comment]
Hello! It's been a few days since an answer was provided, and there has been no more traffic on this issue, so I'm going to close it.  If you'd like to discuss further, please feel free to re-open.
