### ISSUE TITLE
aws_iam_root_user wrong number of arguments

### ISSUE THREAD

**Issue by mpostument** [inspec/inspec#2920]
### 🎛 Description

🐛 bug report

aws_iam_root_user not working as expected

### 🌍 InSpec and Platform Version

```
inspec --version
2.1.30
Ubuntu 16.04


### 🤔 Replication Case

describe aws_iam_root_user do
    its { should have_mfa_enabled }
end

### Result:

inspec exec aws-security -t aws://us-east-1
wrong number of arguments (given 0, expected 1+)

**Comment by clintoncwolfe** [comment]
This works for me, which makes me think it might be an AWS credentials issue (and then InSpec is failing to intercept the error and make a friendly message).

I see you're using `-t aws://us-east-1` to specify your credentials.  InSpec would expect that you are providing either an AWS_PROFILE env variable, or a combination of AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables.   Note that we don't yet support creds via EC2 profile - see #2560 .  Also, we don't support a default profile yet, either - see #2717 

You can check to see if your AWS creds are working by using the AWS CLI.

```
# The aws_iam_root_user MFA check is using the get-account-summary API call
aws --region us-east-1 iam get-account-summary
```
 
If that works, it's probably not a credentials issue.

**Comment by mpostument** [comment]
@clintoncwolfe I suppose credentials is fine. I am using many InSpec iam resources and some other and they work as expected, I have fails only with  aws_iam_root_user  resource

**Comment by clintoncwolfe** [comment]
Ah! I spotted it.  `its` is used to access a property, and requires a property name.  Use `it` to access matchers.  You've used `its` in your example.

This should work:
```
describe aws_iam_root_user do
    it { should have_mfa_enabled }
end
```

**Comment by mpostument** [comment]
I will try with it and let you know. 
Also I took this example from documentation. Would be nice to update

**Comment by clintoncwolfe** [comment]
Thanks, I spotted it [here](https://www.inspec.io/docs/reference/resources/aws_iam_root_user/#syntax) - we'll get that fixed.

**Comment by mpostument** [comment]
@clintoncwolfe work with it. Thanks
