### ISSUE TITLE
os_env resource returns only user's environment variable on Windows

### ISSUE THREAD

**Issue by omar-irizarry** [inspec/inspec#2940]
### 🎛 Description

🐛 bug report

os_env resource returns only the user's environment variable.  There is no way to verify system's environment variables

### 🌍 InSpec and Platform Version

InSpec Version 2.1.30
Windows 2016

### 🤔 Replication Case

Create variables as the ones in the screenshot below
![image](https://user-images.githubusercontent.com/25246117/38583531-48c70e0c-3ce1-11e8-8c19-3f4decd9266d.png)

create the following test:

```
describe os_env('TEMP') do
  its('content') { should eq 'C:\TEMP' }
end

```
run test and you will get the following output:

![image](https://user-images.githubusercontent.com/25246117/38583739-f0eb5bce-3ce1-11e8-83b5-0132408daa4e.png)

### 💁 Possible Solutions

Add a user parameter to os_env resource.

### 💻 Stacktrace

None

**Comment by clintoncwolfe** [comment]
Fixed on #2945
