### ISSUE TITLE
Unable to use mssql_session with local MS SQL

### ISSUE THREAD

**Issue by ViolentOr** [inspec/inspec#2948]
### 🎛 Description

🐛 bug report

Briefly describe the issue and the expected behavior

### 🌍 InSpec and Platform Version

inspec version 2.1.30

### 🤔 Replication Case
Inspec Resource mssql_session is unable to connect to MS SQL Server running locally (which means, that TCP/IP protocol for MSSQLSERVER is in Disabled state).

### 💁 Possible Solutions
The reason for this, that inspec always specifies host and port for sqlcmd:
```
      cmd_string = "sqlcmd -Q \"set nocount on; #{escaped_query}\" -W -w 1024 -s ','"
      cmd_string += " -U '#{@user}' -P '#{@password}'" unless @user.nil? || @password.nil?
      if @instance.nil?
        cmd_string += " -S '#{@host},#{@port}'"
      else
        cmd_string += " -S '#{@host},#{@port}\\#{@instance}'"
      end
      cmd = inspec.command(cmd_string)
```
But, it's perfectly legal to use sqlcmd locally without this information:
```
sqlcmd -Q "set nocount on; select getdate()"
-----------------------
2018-04-12 17:41:22.303
```

**Comment by ViolentOr** [comment]
Looks like replacing
```
      cmd_string = "sqlcmd -Q \"set nocount on; #{escaped_query}\" -W -w 1024 -s ','"
      cmd_string += " -U '#{@user}' -P '#{@password}'" unless @user.nil? || @password.nil?
      if @instance.nil?
        cmd_string += " -S '#{@host},#{@port}'"
      else
        cmd_string += " -S '#{@host},#{@port}\\#{@instance}'"
      end
      cmd = inspec.command(cmd_string)
```

with 
```
    cmd_string = "sqlcmd -Q \"set nocount on; #{escaped_query}\" -W -w 1024 -s ','"
    cmd_string += " -U '#{@user}' -P '#{@password}'" unless @user.nil? || @password.nil?
    if !@host.nil?
      cmd_string += " -S '#{@host}"
      if !@port.nil?
        cmd_string += ",#{@port}"
      end
      if !@instance.nil?
        cmd_string += "\\#{@instance}'"
      else
        cmd_string += "'"
      end
    end
    cmd = inspec.command(cmd_string)
```

and
```
      @host = opts[:host] || 'localhost'
      @port = opts[:port] || '1433'
```
with
```
      @host = opts[:host]
      @port = opts[:port]
```


will do the trick. But it can backfire, if someone relies on this defaults

**Comment by Happycoil** [comment]
`sqlcmd` defaults to 1433 anyway though, right?

I'm running into this with a server with multiple instances and dynamic ports. You have to specify whatever the dynamic port is for the resource to work, but if you simply leave the port out of the `sqlcmd` call the tool figures it out on its own.

Is the jump in tag still valid @TrevorBramble?

**Comment by TrevorBramble** [comment]
@Happycoil Please do jump in!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
