### ISSUE TITLE
Inspec not working with required_controls seems to have started with 1.51.15 gem

### ISSUE THREAD

**Issue by timusmc96** [inspec/inspec#2950]
### 🎛 Description

**Choose one:** is this a 🐛 bug report

The profile now is showing all the controls, for our profile and the depends one, instead of just showing the required controls.   This has been working for long time with out issue, until 1.51.15 inspec gem.

What should happen is the output should only show the required_controls listed and not all the controls from the profile.

### 🌍 InSpec and Platform Version

1.51.15 and up

Redhat6 & 7, windows 2012r2 and 2016

### 🤔 Replication Case

```ruby
require_controls 'cis-windows2012r2-level1-memberserver' do
control'xccdf_org.cisecurity.benchmarks_rule_1.1.1_L1_Ensure_Enforce_password_history_is_set_to_24_or_more_passwords' do
  title 'Set Enforce password history to 8 or more passwords'
  desc  'This policy setting determines the number of renewed, unique passwords that have to be associated with a user account before you can reuse an old password'
  tag   'CCE-3716'
  impact 1.0
  describe security_policy do
    its('PasswordHistorySize') { should be >= 8 }
  end
end
```

inspec.yml has the following depends:
```yaml
 - name: cis-windows2012r2-level1-memberserver
   compliance: comp_user/cis-windows2012r2-level1-memberserver
```
### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

EDIT: (clintoncwolfe)  add code block formatting

**Comment by timusmc96** [comment]
@aaronlippold

**Comment by jquick** [comment]
hanks for this report @timusmc96 ! This should go into the runlist overhaul for 3.0 which will only run included/required selections.

**Comment by timusmc96** [comment]
Please let me know if any more information is needed, because I feel if anyone is using required_controls they should be seeing this issue as well.  Maybe something has changed that is not documented that we have missed. Thanks

**Comment by jquick** [comment]
Is this still an issue? We are unable to reproduce with the current release.

**Comment by zenspider** [comment]
No response. Closing.
