### ISSUE TITLE
Client error, can't connect to 'ssh' backend: You must provide a value for 'host'.

### ISSUE THREAD

**Issue by wolfyy66** [inspec/inspec#2965]
Hi there,

I'm not sure if this is the best place to ask my question. Apologies upfront in case it's not and please feel free to point me in the right direction.

I have two virtual machines under vbox :
Linux server
Linux host

I have Inspec 'n the server and I'm trying to execute a script on the host using SSH
The thing is that when I use the : inspec shell -t ssh:/root@IP:PORT

All I have is this error : Client error, can't connect to 'ssh' backend: You must provide a value for 'host'.

Am I using the right command ?

**Comment by clearscreen** [comment]
You are missing the second slash after ssh. Your command should be:
inspec shell -t ssh://root@server

**Comment by wolfyy66** [comment]
I just didn't write it well in here, all apologies. I did use the second slash after ssh on the terminal and I had faced the same error..

**Comment by jquick** [comment]
That should be the proper syntax. Do you mind listing your exact example? Do you have and special characters in your strings? We just do a simple ruby URI parse on this.

**Comment by clintoncwolfe** [comment]
As I understand it you, have two guest vms, and you want one to be able to SSH to the other.  You may already have this setup, but just to be sure:

VirtualBox provides networking facilities for inter-VM communication.  You can use [internal networking](http://www.virtualbox.org/manual/ch06.html#network_internal) or [bridged networking](http://www.virtualbox.org/manual/ch06.html#network_bridged), and you can also control the DHCP server.  All of that put together means that your guest VMs will each have an IP Address, and you can configure them to talk to each other.

Determine (or preconfigure, might be easier) your IP addresses.  Pinging should work at this point. 
Then verify you can SSH from the server guest to the "host guest".  If you can, then InSpec should be able to as well, using the IP address: `-t ssh://root@198.162.1.3` (for example).

If you're providing an IP (reachable or not) and still getting that error, that would be a bug, and we'd very much like more info.  Thanks!

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
