### ISSUE TITLE
Docs: inspec check --format is undocumented

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2971]
### 🎛 Description

🐛 bug report

When running `inspec help check`, the output about the `--format` option simply says:
```
[cwolfe@lodi inspec-aux]$ be inspec help check
Usage:
  inspec check PATH

Options:
      [--format=FORMAT]
      [--profiles-path=PROFILES_PATH]  # Folder which contains referenced profiles.
...
```

The [docs website](https://www.inspec.io/docs/reference/cli/#check) is similar.

It doesn't seem to validate its value, either, so I can't use an error message to tell me what values are meaningful.  Through experimentation, I've learned `json` is a valid choice, but `progress` isn't.

```
$ inspec check some/profile/path
# Default output
$ inspec check --format=json some/profile/path
# JSON output
$ inspec check --format=progress some/profile/path
# Default output, not dotted progress format as expected
$ inspec check --format=foobar some/profile/path
# Default output, not usage error message as expected.
```

### 🌍 InSpec and Platform Version

2.1.48

**Comment by espoelstra** [comment]
Does it follow chef-client where `--format min` is the alias for dot format?
