### ISSUE TITLE
Inspec 2.1 - Windows package raises exception during inspec check

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#2979]
### 🎛 Description

This passes `inspec check` in Inspec 2.0 but raises an error in 2.1:

```
  describe package('EMET*').version do
    it { should be_installed }
    its('version') { should cmp >= '5.51' }
  end
```

The error is:

```
NoMethodError: undefined method `info' for nil:NilClass
  /Users/jamesstocks/code/project/vendor/bundle/ruby/2.5.0/gems/inspec-2.1.54/lib/resources/package.rb:76:in `version'
  my_controls.rb:1:in `block in load_with_context'
```

### 🌍 InSpec and Platform Version

2.1.54 from bundle install

**Comment by james-stocks** [comment]
This may be invalid, the control code is wrong and should probably be 

```
  describe package('EMET*') do
    it { should be_installed }
    its('version') { should cmp >= '5.51' }
  end
```

Closing.

**Comment by chris-rock** [comment]
Thank you for raising the issue @james-stocks This example has multiple issues:

let assume we have the package `emet` then the following will work:
```
describe package('EMET') do
    it { should be_installed }
    its('version') { should cmp >= '5.51' }
  end
```

The `package` resource does not support regular expressions. Therefore you need to use the `packages` resource. But at this point it is not supported on Windows.
