### ISSUE TITLE
Exceptions are not properly caught by control blocks

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2981]
### 🎛 Description

🐛 bug report

In some circumstances, if an exception is thrown in a `control` block (rather than a `describe` block), the exception is not caught, and the inspec run aborts with stacktrace.  Current doctrine is that no exception in the profile code is allowed to derail the run; rather an exception in a control should be caught and the control marked failed.

Also check to see if this is true for inspec check, inspec exec, or both.

Appears to be aggravated by https://github.com/chef/inspec/pull/2359

refs @chris-rock 

### 🌍 InSpec and Platform Version

2.1.54

### 🤔 Replication Case

Full repro profile available on branch https://github.com/chef/inspec/tree/repro-2981

Example (Explodes on MacOS with no sshd)

```
# sshd05 throws exception which is not caught, and aborts inspec with stacktrace
# Defective on 2.1.54
control 'sshd05 sshd_config resource nonexistant path with contents access control block' do
  s = sshd_config('/i/do/not/exist')
  # Next line triggers compile-time exception
  c = s.Protocol
  describe 'Test block' do
    subject { c }
    it { should be_nil }
  end
end
```

### 💁 Possible Solutions

Meditate on describe and InSpec's extensions to it.

### 💻 Stacktrace

```
[cwolfe@lodi inspec-aux]$ be inspec exec test/regression/2981-exceptions-in-control-blocks/profile-01/
bundler: failed to load command: inspec (/Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/inspec)
Inspec::Exceptions::ResourceSkipped: Can't find file: /i/do/not/exist
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/utils/file_reader.rb:11:in `read_file_content'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/resources/ssh_conf.rb:64:in `read_content'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/resources/ssh_conf.rb:69:in `read_params'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/resources/ssh_conf.rb:48:in `method_missing'
  test/regression/2981-exceptions-in-control-blocks/profile-01/controls/02-sshd_config.rb:41:in `block in load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/rule.rb:50:in `instance_eval'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/rule.rb:50:in `initialize'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/control_eval_context.rb:75:in `new'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
  test/regression/2981-exceptions-in-control-blocks/profile-01/controls/02-sshd_config.rb:38:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/profile_context.rb:158:in `instance_eval'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/profile_context.rb:158:in `load_with_context'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/profile_context.rb:142:in `load_control_file'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/profile.rb:170:in `block in collect_tests'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/profile.rb:167:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/profile.rb:167:in `collect_tests'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/runner.rb:93:in `block in load'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/runner.rb:82:in `each'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/runner.rb:82:in `load'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/runner.rb:103:in `run'
  /Users/cwolfe/sandbox/inspec/inspec-aux/lib/inspec/cli.rb:168:in `exec'
  /Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  /Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  /Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
  /Users/cwolfe/sandbox/inspec/inspec-aux/bin/inspec:12:in `<top (required)>'
  /Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/inspec:23:in `load'
  /Users/cwolfe/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/bin/inspec:23:in `<top (required)>'
```

**Comment by clintoncwolfe** [comment]
Isolated to https://github.com/chef/inspec/blob/master/lib/inspec/rule.rb#L50 .  Need to wrap that in a begin / rescue, and fail the control if it breaks.

**Comment by clintoncwolfe** [comment]
If not caught, exceptions bubble up to the global exception handler, pretty_handle_exception in lib/inspec/cli.rb .  It just prints the error and exits if it is an InSpec exception, and re-raises any other exception.

At that point, we've lost control context, and can't fail the control.

**Comment by trevor-vaughan** [comment]
@clintoncwolfe Jumping over here from #2896 and the exit code is `1`.

The triggers appear to be in `describe sshd_config` blocks

**Comment by clintoncwolfe** [comment]
It is more general than that, but we do use sshd_config as one of the test cases in the PR - see https://github.com/chef/inspec/pull/2987/files#diff-3dece6a73794c93049e4f361145a7a72

**Comment by trevor-vaughan** [comment]
It makes sense from a test perspective.

I guess I'd like to know what is broken and what is not all at once. Right now, I get a failure on `inspec-2.1.54/lib/utils/file_reader.rb:11:in `read_file_content': Can't find file: /etc/ssh/sshd_config (Inspec::Exceptions::ResourceSkipped)` and all processing stops.

Knowing that this can be ignored, I want to have `inspec check` the rest of my files and tell me **everything** that is wrong instead of having to remove files and cherry-pick all over the place. As it stands, `inspec check` just doesn't do anything useful in terms of telling me whether or not I have significant errors.

I can spin up a VM/docker container and run it but, at that point, I'll just run a scan since it won't stop at the first error.
