### ISSUE TITLE
Bad Password in Password Option causes interactive password prompt to appear instead of failure

### ISSUE THREAD

**Issue by ckehoe** [inspec/inspec#2990]
### 🎛 Description

🐛 bug report

Briefly describe the issue and the expected behavior

### 🌍 InSpec and Platform Version

1.51.21
Microsoft Windows 7

### 🤔 Replication Case
Use a bad password for the `--password` option against a valid host. Instead of failing, inspec will instead show an interactive password prompt which causes automated inspec execution to hang.
`
inspec exec C:/path/to/profile --backend=ssh --port=22 --host=111.222.333.444 --user=fakeUser --password=badP@ssw0rd! --reporter=json -l=debug
`

**Output**
fakeUser@111.222.333.444's password:
### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by clintoncwolfe** [comment]
Thanks for the report @ckehoe .  This behavior comes from the connectivity library, `train`.  I'm migrating the bug report to that repo.  Thanks!
