### ISSUE TITLE
Question: Is there a way to only check a file if it contains a string?

### ISSUE THREAD

**Issue by ry1015** [inspec/inspec#2995]
I just want to run a describe file only if its content contains a specific string.

**Comment by clintoncwolfe** [comment]
I'm not totally sure what you're asking for here, so I'll answer two ways.

Note: if you have a YAML, JSON, INI, or CSV file, you can use more specialized resources to parse the file for you.

### You want to audit whether a file has a certain string in it.

You'd use the file resource with the contents property:

```ruby
describe file('/some/path.txt') do
  its('content') { should match /good news/ }
  its('content') { should_not match /shenanigans/ }
end
```

### You want to conditionally execute a separate test based on the contents of a file

```ruby
control "A conditional control" do
  only_if { file('/some/path').content.match?(/good news/) }
  describe some_resource do
    it { should be_fabulous }
  end
end
```

Note: I played with that in `inspec shell` - it's a great way to develop stuff like that.

**Comment by ry1015** [comment]
Your conditional example is perfect! Thank you so much!
