### ISSUE TITLE
inspec check warns "no tests defined" if tests are inside a conditional block

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#2997]
### 🎛 Description

In some cases we need to iterate over multiple values from the system, and so have controls like this:

```
(users.where { username =~ /.*/}.uids.entries + groups.where { name =~ /.*/}.gids.entries).each do |entry|
    describe security_policy do
      its("SeTrustedCredManAccessPrivilege") { should_not include entry }
    end
  end
```

This causes a warning `Control my_control has no tests defined` when checked with `inspec check`

### 🌍 InSpec and Platform Version

2.1.54 from bundle install

**Comment by clintoncwolfe** [comment]
`check` works by having a dummy backend.  If you ask that backend for users and groups, what do you think a correct answer would be?  I think empty arrays are a reasonable answer.  

Your code above constructs tests, one for each entry in an array.  If the array is empty, you have no tests.

You could rewrite that in a couple of different ways, to expose the describe block at the top level (or at least at a level that won't be sensitive to the number of users on the target system).

Some ideas:
 * Move the loop inside the `describe` block.
 * Add a dummy entry to the array, perhaps 'root'

**Comment by james-stocks** [comment]
Thanks @clintoncwolfe moving the loop inside the `describe` does avoid the warning.

I'm not sure all our controls can be updated this way (I think some do require us to put conditional logic outside of the `describe`) but I'm happy if we close this issue; we can file a more specific issue if there's a case we're stuck on
