### ISSUE TITLE
Optimize InSpec detect

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#300]
We could enrich the `inspec detect` command with more valuable information. Currently we recieve the following output:

```
$ inspec detect
{"name":"mac_os_x","family":"darwin","release":"10.10.5","arch":null}
```

Especially the `family` does not reflect the power inspec offers with methods like `os.linux?` or `os.redhat?`. Therefore I propose to return an array for family. This returns all tags for an operating system like

``` json
{
    "name":"mac_os_x",
    "release":"10.10.5",
    "arch":null,
    "family":["darwin", "unix"]
}

{
    "name":"centos",
    "release":"7",
    "arch": "x86",
    "family":["linux", "unix", "redhat"]
}
```

We also should think about:
- Users are confused by the json output that may return `null`.
- We should have a json and human-readable output analog to the `--format` for exec (maybe even reuse those formatters), as highlight in a previous iteration of this issue by @arlimus 

A human-readable output may look like

``` prose
Operating System: Windows
Release:           2012 R2
Arch:                 X68
```

**Comment by arlimus** [comment]
all in all, love the idea!

Could we do:

```
inspec detect
... as suggested ...
```

```
inspec detect --format json
{ ... }
```

Moreover, this includes a sub-issue which must be treated as well: not returning null/nil.
For this case, a suggestion for output would be:

```
Operating system detection failed
```

and

```
{}
```

**Comment by arlimus** [comment]
btw: this will break chef-compliance :wink: we'll need to update that too

**Comment by arlimus** [comment]
Great update, cheers @chris-rock !
