### ISSUE TITLE
Docker Container Checks Excessively Slow

### ISSUE THREAD

**Issue by darksheer** [inspec/inspec#3003]
### 🎛 Description

 🐛 bug report 

Executing a check against a RHEL 7 host for running docker containers takes around 20-22 minutes. 

### 🌍 InSpec and Platform Version

2.1.59

### 🤔 Replication Case
Execute a control looking for existing and running containers.  The referenced YAML file used here has 20 containers. 

```ruby
control 'project_docker_containers_running' do
  title 'Check the project Docker container'
  desc 'Check the 'project  Docker container'
  tag 'production','development'
  tag ''project','os', 'docker'
  running_project_containers = yaml(content: inspec.profile.file('project_docker_containers.yml')).params
  running_project_containers.each do |s|
    describe docker_container(name: s['project_container_name']) do
    it { should exist }
    it { should be_running }
    end
  end
end
```

### 💁 Possible Solutions

Unknown at this time. 

### 💻 Stacktrace

No stack trace was supplied as it's not an execution error, but a performance issues. 

@clintoncwolfe EDIT: code block formatting

**Comment by clintoncwolfe** [comment]
Looks like each docker_container call enumerates all containers, then filters to match.  I don't know how fast that is, but it looks like if you have 20 containers running and you check them 20 times (one apiece), the implementation will execute `docker ps` 20 times, each returning 20 entries, which then gets parsed.  I'd imagine that could be done more directly.

**Comment by darksheer** [comment]
Even with the multiple calls and parsing, it shouldn't take 20 minutes.  A bash for loop would barely take 30 seconds. 

I'm still digging around to see in the code where the slowdown is...

**Comment by darksheer** [comment]
Still happening
