### ISSUE TITLE
Resource 'package' extremely slow

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3025]
### 🎛 Description

Bug report

### 🌍 InSpec and Platform Version

inspec --version
1.51.21
    OS platform: redhat
    OS family: redhat
    OS release: 7.4

### 🤔 Replication Case
Two similar checks:
```ruby
  %w(xorg-x11-apps xorg-x11-server-Xdmx xorg-x11-server-Xephyr xorg-x11-server-Xnest xorg-x11-server-Xorg xorg-x11-server-Xspice xorg-x11-server-Xvfb xorg-x11-server-common xorg-x11-server-devel xorg-x11-server-source xorg-x11-server-utils xorg-x11-util-macros xorg-x11-utils xorg-x11-xinit xorg-x11-xinit-session xorg-x11-xkb-extras xorg-x11-xkb-utils xorg-x11-xkb-utils-devel xorg-x11-xtrans-devel).each do |pkg|
    describe package(pkg) do
      it { should_not be_installed }
    end
end
```

when executed results in:
real    0m22.133s
user    0m18.788s
sys     0m3.170s

Same check with usage rpm -q:
```ruby
  %w(xorg-x11-apps xorg-x11-server-Xdmx xorg-x11-server-Xephyr xorg-x11-server-Xnest xorg-x11-server-Xorg xorg-x11-server-Xspice xorg-x11-server-Xvfb xorg-x11-server-common xorg-x11-server-devel xorg-x11-server-source xorg-x11-server-utils xorg-x11-util-macros xorg-x11-utils xorg-x11-xinit xorg-x11-xinit-session xorg-x11-xkb-extras xorg-x11-xkb-utils xorg-x11-xkb-utils-devel xorg-x11-xtrans-devel).each do |pkg|
    describe bash("rpm -q #{pkg}") do
      its('exit_status') { should eq 1 }
    end
  end
```
when executed results in:
real    0m4.456s
user    0m2.539s
sys     0m1.595s

5 times difference is bit too much

edit (@clintoncwolfe): code block formatting

**Comment by clintoncwolfe** [comment]
The `package` resource will always be a bit slower than a bare `bash` resource - you're able to know what OS you're on, and know that you only want to know installation status.  You can optimize.  So, it will always be a bit slower, but I agree, a 5x penalty seems large.

I looked into this briefly.
I found [this](https://github.com/chef/inspec/blob/master/lib/resources/package.rb#L184), in which each `package` resource queries by running `rpm-qia #{package_name}`.  I'm not sure of that behavior, but I thing that `-a` option is likely unneeded - it tells RPM to list all packacges.  I don't know the behavior when given both a package name and `-a`.

**Comment by juliandunn** [comment]
The `-a` is not necessary and introduces a performance penalty.

```
[root@b3d4e6494791 /]# time rpm -qi tar 2>&1 > /dev/null

real	0m0.028s
user	0m0.020s
sys	0m0.000s
[root@b3d4e6494791 /]# time rpm -qia tar 2>&1 > /dev/null

real	0m0.087s
user	0m0.080s
sys	0m0.000s
```
