### ISSUE TITLE
Allow file replacement in included profile

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3030]
### 🎛 Description

Feature request

We have a great feature inspec.profile.file, but it always read file from the same profile. It would be much greater feature if I could replace file in included profile.
Imagine I have profile_a with control check_a. This control uses data loaded from files/check_a.yml
Now, I include this profile_a in another profile - profile_b. I need exactly the same logic as check_a, but with another data. So it would be great if in profile_b I'll have
files/profile_a/check_a.yml
and this file would be loaded instead of original file in profile_a for included check_a.

**Comment by voroniys** [comment]
The feature is still badly needed. This is quite sad that in more than year time nothing happens with this request.

**Comment by clintoncwolfe** [comment]
Could you explain more about your use case?  We have not heard from other users that would need such functionality, and it would add complexity. Would you be able to contribute to implement it?

**Comment by zenspider** [comment]
No feedback in ~6 months... Closing.
