### ISSUE TITLE
Add 'where' filter to shadow resource

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3032]
### 🎛 Description

Feature request

The resource passwd has very usefull method where, but shadow - does not. But it would be very useful to have method where also for shadow. For instance:
shadow.where {last_change < (Time.now.to_i-7776000)/86400}
check if there are passwords not changed for more than 90 days.

**Comment by clintoncwolfe** [comment]
This feature is available in InSpec 2.x, but appears to be [undocumented](https://www.inspec.io/docs/reference/resources/shadow/).  I've opened #3034 to address that.

There is an existing open ticket, #2980, to backport the `where` method on `shadow` from the 2.x series to the 1.x series.  Based on that, I'm closing this as a duplicate.
