### ISSUE TITLE
Create Help for Subcommands

### ISSUE THREAD

**Issue by larryebaum** [inspec/inspec#305]
Commands and subcommands need help pages with examples...  include examples such as passing creds for ssh or winrm connections (inspec exec <testFile> -t user@host --password '<password>')

**Comment by chris-rock** [comment]
@larryebaum If I got you right, you would like to have some connectivity examples in our documentation, right?

**Comment by arlimus** [comment]
This is now being covered in https://github.com/chef/inspec/issues/910 .

**Comment by chris-rock** [comment]
@larryebaum We created https://github.com/chef/inspec/blob/master/docs/cli.rst Is there anything else missing for you?

**Comment by chris-rock** [comment]
Please reopen if this continues to be an isssue.
