### ISSUE TITLE
Allow skip/modification of controls to work for chain includes

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3051]
### 🎛 Description

Feature request, but may only be seen as a kind of bug.

Let assume I have following profiles:
Profile_A with controls
A-1
A-2
A-3
Profile_B which includes Profile_A and have modify control A-2 somehow and has own controls
B-1
B-2

Now, I create Profile_C and put in it:
```
include_controls 'Profile_B' do
  control 'A-1' do
     modify it somehow
  end
  skip_control 'A-3'
  skip_control 'B-1'
end
```
Naturally I'd expect that only modified A-1,A-2 and, B-2 would be executed. But in current Inspec controls
```
unmodified A-1
modified A-2
A-3
B-2
```
are executed. And there is no way how I can skip or modify controls from Profile_A in Profile_C. 
If I now create a Profile_D and include in it Profile_C I don't have any influence on controls from both Profile_A and Profile_B.

This basically make chain includes practically useless, while it could be a real killer feature. In the situation like it is now I just have to copy same controls into different profiles and if one of them has to be changed I have to change it in all profiles where they are used.

**Comment by clintoncwolfe** [comment]
Just to clarify, I added the 3.x release tag not to imply that this won't be addressed until 3.x - but rather, we're planning on looking at some closely related issues around profile inheritance in 3.x, and I'd want this issue to be involved in that discussion.  I don't know enough about the internals to say if this could be implemented in 2.x .

**Comment by voroniys** [comment]
By accident I've found kind of workaround for the described situation, although this workaround can be seen as a bug by itself. In the example above it is possible to skip control 'A-3' in Profile_C:
```
include_controls 'Profile_B' do
  skip_control 'B-1'
end
include_controls 'Profile_A' do
  control 'A-1' do
     modify it somehow
  end
  skip_control 'A-3'
end
```
The buggy part of this workaround is that in summary all tests from Profile_A will be counted double. I.e. if Profile_B has 3 controls with 2 tests each and Profile_A 5 controls each 2 tests (so 10 in total) the final summary of Profile_C will report 8 controls and 26 tests (correct number will be 16)

**Comment by PascalJanszWork** [comment]
I tried this with version 3.0.52 of Inspec and this behavior still exists. Are there any plans to address this topic?

**Comment by PascalJanszWork** [comment]
@voroniys : I used a different approach to get to a solution.

In profile B I have:
```
controls = List of controls based on a yaml file
exceptions = List of exceptions based on a array provided via attributes
include_controls 'profile A' do
  controls.each do |control|
    if exceptions.has_key? control
      skip_control "#{control}"
    else
      control "#{control}" do
       <modify> #could be yaml data from 
      end
   end
end
```
When loading profile C I add --attrs to the CLI.

Hope it helps.
