### ISSUE TITLE
Control Numbers and Display in Compliance GUI

### ISSUE THREAD

**Issue by larryebaum** [inspec/inspec#306]
Numbering controls sequentially (eg., control 'cis-fs-2.1' do, control 'cis-fs-2.2' do, control 'cis-fs-2.10' do) results in out of order display in gui:

2.1
2.10
2.2

Naming controls with leading zeros (eg., 2.01, 2.02, 2.10) preserves the ordering
.
Suspect most authors won't insert leading zeros by default and if they do (assuming 2 digits) if control sets reach three digits, they'd need to 'rework' all the controls again.

**Comment by chris-rock** [comment]
Will be solved in Chef Compliance
