### ISSUE TITLE
Make property listings in website docs more useful

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3060]
### 🎛 Description

🙋 feature request

Currently, there are sections in the resource docs that list the properties or matchers of a resource; but it's unclear what purpose they serve.  It's not a table of contents (the names are unlinked) and it's not documentation (fully documented resources have a prose description of the property, and then at least one example).

An example is in the [apache resource](https://www.inspec.io/docs/reference/resources/apache/#properties)

* 'service', 'conf_dir', 'conf_path', 'user'

Aside from the formatting issues (fixed on #3058), that doesn't do the reader any good, aside from telling you what is there.  If that's useful, those should be links to the full property information.

In the case in which we don't have full descriptions of the properties (see [`aws_ec2_instance`](https://www.inspec.io/docs/reference/resources/aws_ec2_instance/)) I do think it is useful to have a simple property list, as an interim measure.

Briefly describe the issue and the expected behavior

### 🌍 InSpec and Platform Version

2.1.72

### 💁 Possible Solutions

Merge the "Properties" and "Property Examples" sections, into a section named "Properties".  Immediately following the section title, include a list of hyperlinked property names, which link to anchors within the page.

Consider placing such a ToC at the top of the page.

Consider automating the ToC generation.

**Comment by kagarmoe** [comment]
The properties list is an index for available properties for a resource. Indexes provide faster orientation for users than examples. Linking the list to the examples is a very good idea.  Full descriptions of properties for each resource is desirable.
