### ISSUE TITLE
Inheritance / dependent profile data passthrough

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#3062]
###  Description
🐛 bug report // blocker

When you include a control in a dependent profile and modify things like `desc`, `impact` etc. the overlay correctly updates the base control data and use the new data. 

However, if you try to modify a 'tag' or 'ref' in the using `include_controls "myprofile"` - the data is not updated as expected and is still using the data from the base profile. 

This is a big issue / blocker for those that are using overlays and dependent profiles.

@jquick @chris-rock @jerryaldrichiii @arlimus - have you guys seen this before?

**Comment by chris-rock** [comment]
I think we've never had that use-case before, but it make sense from the usecase perspective. We just need to figure out the detail how this is written.

**Comment by ejaronne** [comment]
This is crucial to making my overlays relevant. For example, some folks may use a completely different banner than the DoD one in the STIG. We can make the code check properly to a different banner, but when the developer reads through the results, we pass through the check and fix text for context for them. If the check and fix test tags still show the DoD banners, this creates confusion.

**Comment by chris-rock** [comment]
@jquick is that done via #3155

**Comment by jquick** [comment]
Yes, `tag`, `ref`, and `code` are now updated correctly when using a overlay via #3155. I believe this issue is resolved. Please re-open if something is missing from the implemented solution.

**Comment by aaronlippold** [comment]
Hi,

Thank you @jquick and team for getting on this so quickly. We will do a
quick field test to ensure we have resolved the issue.

Thanks again!

Aaron
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
