### ISSUE TITLE
Generate language packs for Atom and other editors

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3075]
### 🎛 Description

🙋 feature request

Blocked by #2688

Attn @tas50 

If resources self-documented their parameters, criteria, properties, and matchers, we'd be able to generate autocomplete data for popular editors and integrate that into our builds.

### 🌍 InSpec and Platform Version
2.1.83

**Comment by tas50** [comment]
There's still a huge need for this
