### ISSUE TITLE
Configuration number comparisons

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#308]
When running against a configuration file with numbers, e.g. ssh_config with:

```
Port 22
```

The test would have to be written:

```
its('Port') { should eq '22' }
```

However users also expect to be able to write:

```
its('Port') { should eq 22 }
```

It would be great to find a way to reconcile this and help users to write the test they expect.

**Comment by chris-rock** [comment]
with #318 it is possible to write:

``` ruby
describe sshd_config do
  its('Port') { should cmp '22' }
  its('Port') { should cmp 22 }
end
```
