### ISSUE TITLE
Sequel for native SQL server connections

### ISSUE THREAD

**Issue by miah** [inspec/inspec#3088]
This is a feature request to change the way our database resources function. Currently, our database resources shell out to a client program and parse its output. Instead of requiring users to install additional software, we could connect natively through Ruby.

In the past I've used [sequel](https://github.com/jeremyevans/sequel) as it has adapters for all common databases.

We could also consider a database backend in Train. With this our database resources would be very trivial and Train users would also benefit.

**Comment by chris-rock** [comment]
That is a great idea @miah As you said, it would be preferable to have:
- train support sql as a backend
- specific sql resources for executing sql
This would allow us to write tests against a database even if you have no access to the underlying host that runs the database.

**Comment by miah** [comment]
I have several local VM's for testing my DB work, but we lack a standard cross-developer way to validate that code against databases. 

We need to have a test environment that has various database backends so that we can regularly validate this work.

**Comment by aaronlippold** [comment]
One small note on this is that we should also make sure we allow for the conection to be both interface and socket etc.
