### ISSUE TITLE
RFC: InSpec Plugins

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3089]
InSpec is covering a lot of test surface ranging from operating systems (AIX to Linux & Windows) as platforms like AWS and Azure. GCP and VmWare integration is on the horizon. Users request more and more extension points. On the other hand it becomes challenging to maintain all integration via in the core team.

## Current State

# Installation #

The current way to install plugins is complicated and involved multiple steps as well as different commands. Currently we have two ways to install a "plugin", which assumes inspec is already installed.

```bash
# Then install the `inspec-hpe-oneview` plugin via `~/.inspec/plugins` or a gem build, used for development
git clone git@github.com:mattray/inspec-hpe-oneview ~/inspec-hpe-oneview
mkdir -p ~/.inspec/plugins
ln -s ~/inspec-hpe-oneview/ ~/.inspec/plugins/inspec-hpe-oneview
inspec oneview help

# Build the `inspec-hpe-oneview` then install:
git clone https://github.com/inspec/inspec-hpe-oneview.git && cd inspec-hpe-oneview && gem build *gemspec && gem install *gem
# install gem
gem install inspec-hpe-oneview
inspec oneview help
```

Plugins are categorized into:

* **CLI plugin** which modifies or exposes commands to the `inspec` executable
* **Platform plugin** which provide transport functionality in `train`

## Integration Points

We identified a couple of integration points:
- InSpec CLI
- InSpec platform extensions
- InSpec resources

### Platform and CLI plugins will be installed via the same InSpec CLI lifecycle:

```
# install cli plugin (gem name is `inspec-iggy`)
inspec plugin install iggy
# install a plugin that extends train too (gem name is `inspec-hponeview`)
inspec plugin install hponeview
# list all available plugin
inspec plugin list
# update a plugin
inspec plugin update iggy
# uninstall a plugin
inspec plugin uninstall iggy
```

### Platform Extensions

Platform extensions may extend train. In core we maintain `train-gcp`, `train-vmware`, `train-aws`, `train-azure`. Users do not distinguish between a InSpec cli and a InSpec platform extensions. Besides adding sdks and gems, those plugins need to be able to define platform definitions and target urls.

### Resources

All resources are extended via the current inspec resource pack mechanism. https://github.com/inspec/inspec-gcp is a very good example.

## Capability definition

At this point plugin offers capabilities. At this point we have the `cli` and `platform` capabilities but we may wanna offer more capabilities in the future.

## Plugin releases

All gems need to be named by the format `inspec-*`. We download plugins from rubygems or with a local gem file. We do not auto-install plugins.

## Open questions:
- Identify our internal plugin contract for InSpec and expose the supported parts via a specific object, so that we do not need to establish guarantees for all inspec internals
- Does `inspec.yml` need to define a dependency for a plugin?

**Comment by clintoncwolfe** [comment]
Could you clarify what is current functionality and what is desired functionality?

**Comment by jquick** [comment]
We should also talk about testing on plugins and if we want to offer up core testing frameworks(Mock) to use or have them just do their own.

**Comment by arlimus** [comment]
Updated based on InSpec team feedback, thank you all!!
