### ISSUE TITLE
mount resource does not accept path with '+' sign

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3098]
### 🎛 Description

Bug report

While testing an oracle server I've found that + sign is breaking mount resource:
```
# mount |grep +asm
/dev/mapper/oracledb-asm_diag on /opt/oracle/diag/asm/+asm type xfs (rw,relatime,seclabel,attr2,inode64,noquota)
```
but
```
inspec> mount('/opt/oracle/diag/asm/+asm').mounted?
=> false
```

### 🌍 InSpec and Platform Version

inspec --version
2.1.72

**Comment by voroniys** [comment]
In fact this is the issue with inspec.backend.file:
```
inspec> file('/opt/oracle/diag/asm/+asm').mounted?
=> false
```

**Comment by voroniys** [comment]
Pull request 306 for inspec/train is created to fix this issue

**Comment by zenspider** [comment]
Fixed. Closing.
