### ISSUE TITLE
file resource link_path always traces link to the target

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3100]
### 🎛 Description

bug report
could be related to #3099
situation:
```
# ls -l /another_link /link
lrwxrwxrwx. 1 root root  4 May 31 17:47 /another_link -> /usr
lrwxrwxrwx. 1 root root 13 May 31 17:47 /link -> /another_link
```
I need to check that /link points to /another_link and I don't care where /another_link points, but it looks like impossible, because:
```
inspec> file('/link').link_path
=> "/usr"
```

### 🌍 InSpec and Platform Version

inspec --version
2.1.72

### 🤔 Replication Case

see above

**Comment by frezbo** [comment]
I have seen this behavviour when checking symlinks to `/dev/stdout`, it used to follow every symlink and it finally returned me a FD

**Comment by voroniys** [comment]
Tracing link down to the target is surely useful function,  but in inspec we need to be able to check any conditions. In current implementation it is impossible to check that symlink is pointing another symlink.
