### ISSUE TITLE
Provide 'they' and 'their' aliases for plural resources

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3109]
### 🎛 Description

🙋 feature request

When working with plural resources (those that operate on groups of platform objects, typically filtering them and auditing their properties in bulk), we currently use this sort of expression:

```ruby
describe cars.where(color: :blue) do
  it { should exist }
  its('licence_plates') { should include 'KOOL KAT' }
end
```

It's perfectly sensible for singular resources (imagine describing a single car: its license plate, it exists, etc).  But it reads awkwardly for plurals, and reflects an implementation detail, that `it`/`its` refer to the test subject instance of an RSpec Example Group.

It would be great if we could simply alias those, `it` => `they` and `its` => `their`:
```ruby
describe cars.where(color: :blue) do
  they { should exist }
  their('licence_plates') { should include 'KOOL KAT' }
end
```

Refs #3041 

### 🌍 InSpec and Platform Version

2.1.83

### 💁 Possible Solutions

Poke at `rspec-its`, likely re-open some classes to inject an alias.

**Comment by aaronlippold** [comment]
👍

**Comment by clintoncwolfe** [comment]
This was nixed.
