### ISSUE TITLE
Is it possible to test actual value of $PATH for the root user?

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3112]
### 🎛 Description

Marking this as question - not sure if this bug, enhancement or a documentation item

The compliance benchmark I am trying to apply to my RHEL7 servers includes a test of the value of `$PATH` for the root user.
This does not seem straightforward because the value of `$PATH` depends on whether you are actually `root` or just a sudo'd non-root user; and whether you are checking $PATH via an SSH remote command or actually ssh'd into a shell (note that issue #450 has the same observation from @jerryaldrichiii , though is a different issue.)
`inspec` seems to do the former - `inspec shell` shows me the same result that sending an SSH remote command would give me.

### 💁 Possible Solutions

 * I can maybe figure out some usage of `command` that gives me the "while logged in as root" value of $PATH

**Comment by james-stocks** [comment]
I cannot add labels to this issue.

**Comment by james-stocks** [comment]
This appears to be equivalent to `$PATH` when logged in as root:

```
inspec> command('bash -c \'echo $PATH\'').stdout
=> "/sbin:/bin:/usr/sbin:/usr/bin\n"
```

...but I would need the control to skip if inspec is neither running as root nor using `--sudo`

**Comment by voroniys** [comment]
I don't think it is possible without being able login as root. PATH can be changed in a lot of places, like /etc/profile, /root/.bashrc and so on. These scripts in turn can be modified to include another, non-standard scripts. And only by real login it will be assembled all together into PATH environment variable.

**Comment by james-stocks** [comment]
Thanks @voroniys - I've filed a ticket with the publisher of the benchmark I'm working with to clarify that their test is intended for for a "real login" and the value of `PATH` from a simple ssh command is n/a or would be a different test

I've found that `os_env('PATH').content` gives a result consistent with being logged in as root; but I'm unsure this will always be consistent.

I also intend to use `only_if { bash('id').stdout !~ /uid\=0\(root\)/ }` to skip the test if inspec is not currently running as root or with `--sudo`

**Comment by james-stocks** [comment]
Closing as per last comment - `os_env` appears to work (I think there will be cases where it can be tripped up, but such cases should be filed as a new and more specific issue) and I just needed an `only_if` condition on my control to avoid a false result if inspec is running as non-root.
