### ISSUE TITLE
Service resource might be missing :runlevel info

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3116]
### 🎛 Description

Seen on a RHEL7 host (`ami-223f945a` on EC2)

When I was testing in inspec shell exactly how runlevels work; I noticed the following output that looks wrong:

```
inspec> command('chkconfig --list rhnsd').stdout
=> "rhnsd          \t0:off\t1:off\t2:on\t3:on\t4:on\t5:on\t6:off\n"
inspec> service('rhnsd').runlevels
=> {}
inspec> service('rhnsd').runlevels(/.*/)
=> {}
inspec> service('rhnsd').runlevels.enabled?
=> true
inspec> service('rhnsd').runlevels.disabled?
=> true
inspec> service('rhnsd').runlevels(3, 5)
=> {}
```

(I played with other services that appear in `chkconfig --list` so this does not appear specific to `rhnsd`)

Peeking at what `:info` the service has, it appears to be missing the `:runlevels` key that the [service resource uses for this](https://github.com/inspec/inspec/blob/master/lib/resources/service.rb#L205)

### 🌍 InSpec and Platform Version

2.1.68 from bundle install
Target is RHEL7.4 on EC2 (`ami-223f945a`)

### 🤔 Replication Case

 * Create an instance of `ami-223f945a`
 * Start `inspec shell`
 * Try the commands listed above

### 💁 Possible Solutions

Not sure, not looked into why/how the runlevel info for the service isn't being picked up.
As a side note, it might be preferable for the [`runlevels` method](https://github.com/inspec/inspec/blob/master/lib/resources/service.rb#L205) to return nil rather than an empty hash here - if a user writes a control on the basis that there will be runlevels, it would be better to fail at an error here; an empty hash is meaningless given that the person writing the control expects there to be runlevel info.

Also `runlevels.enabled?` and `runlevels.disabled?` should maybe return false for an empty hash.

**Comment by james-stocks** [comment]
I think this condition isn't totally correct:

https://github.com/inspec/inspec/blob/master/lib/resources/service.rb#L139

```
        if (%w{redhat centos oracle}.include?(platform) && version >= 7) || (platform == 'fedora' && version >= 15)
          Systemd.new(inspec, service_ctl)
        else
          SysV.new(inspec, service_ctl || '/sbin/service')
        end
```

On this RHEL 7.4 host the condition is true and I get a `Systemd` .

If I hack this to give me a `SysV` instead then I get my `runlevels`

```
inspec> service('rhnsd').runlevels
JUST AS I EXPECTED
=> {0=>false, 1=>false, 2=>true, 3=>true, 4=>true, 5=>true, 6=>false}
```

**Comment by frezbo** [comment]
if this is a RHEL7.4 machine, why using `chkconfig` instead of systemd. The inspec code seems right.

**Comment by james-stocks** [comment]
@frezbo you are right. I need to support both RHEL6 and RHEL7 and missed the difference in this case. 
Thanks!
