### ISSUE TITLE
Question about testing SQL Server

### ISSUE THREAD

**Issue by parameshdsn** [inspec/inspec#3118]
Hi All, We are automating our infrastructure using ansible. We want to validate all the automation using inspec. For the same i am getting trouble to find the inspec test cases for them. I am stuck with the Database inspec test cases:
 * verify the user of the SQL services is C2WTS service account. 
 * Unable to validate the databases in sql server. 
 * Testing specific database users and roles. 

Please help me to get out of this cases. Thank you in advance.

### 🌍 InSpec and Platform Version
Windows

**Comment by jerryaldrichiii** [comment]
@parameshdsn you have a few options here. For testing queries and database specific things you can use the `mssql_session` resource see: https://www.inspec.io/docs/reference/resources/mssql_session/

For anything else, if there isn't a resource to cover it you can fallback to using the `powershell` resource see: https://www.inspec.io/docs/reference/resources/powershell/

Does that help?

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
