### ISSUE TITLE
Check drive size and format on Windows

### ISSUE THREAD

**Issue by parameshdsn** [inspec/inspec#3119]
windows float form.

**Comment by parameshdsn** [comment]
I need to check drive size and drive letters format should be displayed  using inspec test cases.

**Comment by clintoncwolfe** [comment]
To check file paths - including drive letters - one can use the [File resource](https://www.inspec.io/docs/reference/resources/file/).

```ruby
describe file('C:\\') do
  it { should exist }
end
```

While the [mount resource](https://www.inspec.io/docs/reference/resources/mount/) is usually used to detect filesystem types (what I take to be what you mean by "formatting"), unfortunately there is no support for it on Windows.  At the present time, the [powershell resource](https://www.inspec.io/docs/reference/resources/powershell/) is likely your best option.

As for drive size, again, [filesystem resource](https://www.inspec.io/docs/reference/resources/filesystem/) does not support Windows, so [powershell resource](https://www.inspec.io/docs/reference/resources/powershell/) is likely your best option.

**Comment by parameshdsn** [comment]
@clintoncwolfe  thank you so much its working. 
I want to check disk size and drive letter in single code.

**Comment by clintoncwolfe** [comment]
I'm not clear on what you're asking for - "in single code".  There is no resource that does everything you want ( though I suppose you can do anything at all in a single powershell resource).  TYpically, if you have multiple tests that are related, you group them in a control:

```ruby
control 'Verify C drive letter and size' do
  describe file('C://') do
    it { should exist }
  end

   # Whatever command you use to check disk size
  describe powershell(...) do
     # ...
  end
end
```

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
