### ISSUE TITLE
aws_iam_policy have_statement matcher docs should match implementation for key type

### ISSUE THREAD

**Issue by mikejmcfarlane** [inspec/inspec#3120]
### 🎛 Description

 🐛 bug report

Documentation (https://www.inspec.io/docs/reference/resources/aws_iam_policy/) for the `aws_iam_policy` shows some examples with the `have_statement` where the variables are plain text key value pairs. Running this produces an error. It appears that a json formatted key value pair is required.

### 🌍 InSpec and Platform Version

Inspec version 2.1.84
CentOS Linux release 7.5.1804 (Core)

Installed with `curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec`

### 🤔 Replication Case

My sample code based on that example:
```
describe aws_iam_policy('mike_test01') do
  it { should have_statement(Action: 's3:PutObject') }
end
```

produces error:
```
inspec exec inspec_test_04.rb -t aws://
Profile: tests from inspec_test_04.rb (tests from inspec_test_04.rb)
Version: (not specified)
Target:  aws://
  Policy mike_test01
     ×  should have statement {:Action=>"s3:PutObject"}
     Unrecognized criteria Action to have_statement.  Recognized criteria: Action, Effect, Resource, Sid
Test Summary: 0 successful, 1 failure, 0 skipped
```

Passing in json produces the expected working output:
```
describe aws_iam_policy('mike_test01') do
    it { should have_statement({"Effect" => "Allow", "Action" => "s3:PutObject"}) }
end
```

### 💁 Possible Solutions

Update documentation
Or, maybe the docs are right and this is a bug that needs fixing.

**Comment by clintoncwolfe** [comment]
I think modifying to accept either Strings or Symbols would probably be best.

**Comment by trickyearlobe** [comment]
You might consider down-casing and normalising to symbols or strings in the validator.

This applies to both keys and values (eg. we have an example or `allow` instead of `Allow` for the Effect field which seems a bit mean to reject)

In addition, sometimes the actual IAM policies contain inconsistent case if they have been edited by hand.
