### ISSUE TITLE
Deprecate Azure Generic Resources

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3131]
### 🎛 Description

In InSpec we want to ensure by design that we build a predictable system. That means need need to minimize runtime issues and offer a stable resource definition. The `azure_generic_resource` proofed to be not stable and do not recommend its use.

### 🌍 InSpec and Platform Version

2.x

### 🤔 Replication Case

See https://github.com/inspec/inspec/issues/3096

### 💁 Possible Solutions

Do not use the `azure_generic_resource`. Deprecate the resource.

### 💻 Stacktrace

n/a

**Comment by chris-rock** [comment]
Related discussion is https://github.com/inspec/inspec-gcp/issues/25

**Comment by hdost** [comment]
Since the warning refers to the issue could we get a reference to what should be done as the replacement for `azure_generic_resource`?

**Comment by chris-rock** [comment]
@hdost Thank you for reaching out. We are adding more and more azure resources in our [Azure Resource Pack](https://github.com/inspec/inspec-azure). We recommend to use the provided resources from there. If a resource is missing, please add an issue or open a PR to contribute a new resource for Azure.
