### ISSUE TITLE
shadow resource no longer has `passwords` property after Inspec 2.0.32

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3136]
### 🎛 Description

🐛 bug report 

The following control is no longer valid from 2.0.45 onwards:

```
  shadow.users(/.+/).entries.each do |entry|
    describe entry do
      its('passwords') { should_not eq [''] }
    end
  end
```

### 🌍 InSpec and Platform Version

1.5.21 - works
2.0.32 - works
2.0.45 - does not work

Target host is RHEL 7 instance on EC2 where `/etc/shadow` contains `"root:!!:17534:0:99999:7:::\nbin:*:16925:0:99999:7:::\ndaemon:*:16925:0:99999:7:::\nadm:*:16925:0:99999:7:::\nlp:*:16925:0:99999:7:::\nsync:*:16925:0:99999:7:::\nshutdown:*:16925:0:99999:7:::\nhalt:*:16925:0:99999:7:::\nmail:*:16925:0:99999:7:::\noperator:*:16925:0:99999:7:::\ngames:*:16925:0:99999:7:::\nftp:*:16925:0:99999:7:::\nnobody:*:16925:0:99999:7:::\nsystemd-network:!!:17534::::::\ndbus:!!:17534::::::\npolkitd:!!:17534::::::\npostfix:!!:17534::::::\nchrony:!!:17534::::::\nsshd:!!:17534::::::\nec2-user:!!:17695:0:99999:7:::\n"`

### 🤔 Replication Case

 * Get a VM with a populated `/etc/shadow` file (the offending code is not executed otherwise)
 * In `inspec shell` paste the control from the bug description

### 💁 Possible Solutions

After inspec 2.0.45 the following works: `its('password') { should_not eq '' }`
However this does not work for 1.51.21 and this profile needs to work for that as well.
Possibly the control can be re-written to avoid `password`/`passwords` or possibly I can make the control code branch on `Inspec::VERSION`

### 💻 Stacktrace

```
  /etc/shadow with user == /.+/ one entry
     ×  passwords
     undefined method `passwords' for #<#<Class:0x00007fa7798f9d28>:0x00007fa779b77cf8>
     Did you mean?  password
                    password=
```

**Comment by clintoncwolfe** [comment]
Refs #2992
