### ISSUE TITLE
Inspec report has old code for wrapped profile

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#3145]
When wrapping a profile and changing a control, the generated report still has the old `code`, `tags` and `refs`.

[myrapper-child-0.6.1.tar.gz](https://github.com/inspec/inspec/files/2103383/myrapper-child-0.6.1.tar.gz)

Let's take the above profile ^.

In the json report, control `pro1-con2` of vendored `myprofile1` is being overwritten with a different `title`, `desc`, `impact`, `tags`, `refs` and new describe block.

The json report shows the overwritten `title`, `desc` and `impact`, but `tags`, `refs` and `code` fields are from the old control.

```json
        {
          "id": "pro1-con2",
          "title": "Profile 1 - Control 2-updated",
          "desc": "Profile 1 - Control 2 description-updated",
          "impact": 0.999,
          "refs": [],
          "tags": {
            "password": null
          },
          "code": "control 'pro1-con2' do\n  impact 0.9\n  title 'Profile 1 - Control 2'\n  desc 'Profile 1 - Control 2 description'\n  tag 'password'\n  describe file('/etc/passwdddddddddd') do\n    it { should exist }\n  end\nend\n",
          "source_location": {
            "line": 12,
            "ref": "controls/profile1.rb"
          },
          "results": [
            {
              "status": "passed",
              "code_desc": "File /etc/passwd should exist",
              "run_time": 0.003082,
              "start_time": "2018-06-14T18:35:32+01:00"
            }
          ]
        }
```

### 🌍 InSpec and Platform Version

```
InSpec version 2.1.81
```

**Comment by jeremymv2** [comment]
thanks @alexpop I've validated this same behavior with 2.2.10 as well
