### ISSUE TITLE
keyword for reserving control identifier

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3150]
### 🎛 Description

When profiles are managed over time, controls are changing and updated. We discourage the reuse of the same control id since users expected the same behaviour for the same control. The https://github.com/dev-sec/nginx-baseline/pull/24 showcases an example, where a duplicate control needs to be removed but at the same time we want to ensure that future users do not reuse the same control id. 

### 🌍 InSpec and Platform Version

InSpec 2.x

### 💁 Possible Solutions

Similar to https://developers.google.com/protocol-buffers/docs/proto3#reserved we could introduce a keyword that blocks the control id to ensure that `inspec check` outputs warnings.

```
control 'id' do
  reserved
end

control 'id' { reserve }
```

another option could be:
```
reserve 'id'
reserve 'id1', 'id2'
```

**Comment by clintoncwolfe** [comment]
What should the inspec check behavior be?

**Comment by chris-rock** [comment]
This is a feature for `inspec check` to be able to enforce that no id is reused. Therefore this should lead to an inspec check error if a control tries to use the id.

**Comment by zenspider** [comment]
Not on roadmap. Closing.
