### ISSUE TITLE
Fix docs examples using matcher include with array expected value

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3162]
### 🎛 Description

🐛 bug report

Several resources have docs that use examples like this:

```
  describe fruit_cart do
    its('banana_ages') { should include ['underripe', 'just right'] }
  end
```

This is almost certainly wrong; `include` looks for a single element in an array property, or multiple elements _when passed as separate arguments_. So, the above example is expecting the 'banana_ages' property to look like `[ element, ['underripe', 'just right'] , some_other_element ]` - in other words to be an array of arrays.

If the property is shaped like a flat list - `[ 'underripe', 'just right', 'pretty dubious', 'hide it in the banana bread']`, and you wanted to see if two values were there, you would do this:

```
its('banana_ages') { should include('underripe', 'just right') }
```

That is, passing multiple args to `include`, not passing a single arg that is a multi-element array.

[RSpec Docs](https://relishapp.com/rspec/rspec-expectations/v/3-7/docs/built-in-matchers/include-matcher)

Affected resources include:

* limits_conf
* auditd
* etc_hosts_allow
* etc_hosts_deny

Thanks to @frezbo for finding these.

### 🌍 InSpec and Platform Version

2.2.16

### 💁 Possible Solutions

Doc updates.

**Comment by Vasu1105** [comment]
For `limits_conf` the example looks to be valid as the data return is array of array so it fails if I have this check
```
describe limits_conf do
  its('*') { should include('soft', 'core', '0') }
  its('student') { should include('hard', 'nproc', '20') }
end
```
```
Profile: InSpec Profile (test)
Version: 0.1.0
Target:  ssh://ec2-user@ec2-18-222-36-126.us-east-2.compute.amazonaws.com:22

  limits.conf
     ×  * is expected to include "soft", "core", and "0"
     expected [["soft", "core", "0"]] to include "soft", "core", and "0"
     ×  student is expected to include "hard", "nproc", and "20"
     expected [["hard", "nproc", "20"]] to include "hard", "nproc", and "20"

Test Summary: 0 successful, 2 failures, 0 skipped
```

The same is the case for the `etc_host_allow` and `etc_host_deny` resource 

```
describe etc_hosts_allow('/Users/vjagdale/workspace/inspec/test/fixtures/files/hosts.allow').where { daemon == 'ALL' } do
its('client_list') { should include("127.0.0.1", "[::1]") }
end
```
```
Profile: InSpec Profile (test)
Version: 0.1.0
Target:  local://

  hosts.allow Configuration with daemon == "ALL"
     ×  client_list is expected to include "127.0.0.1" and "[::1]"
     expected [["127.0.0.1", "[::1]"]] to include "127.0.0.1" and "[::1]"
```

**Comment by Vasu1105** [comment]
@clintoncwolfe please review the comments and if you agree we can close this issue.

**Comment by Vasu1105** [comment]
Closing this as the examples looks to be a valid example.
