### ISSUE TITLE
Inspec documentation missing exit code status

### ISSUE THREAD

**Issue by frezbo** [inspec/inspec#3167]
### 🎛 Description

**Choose one:**  🐛 bug report

Inspec documentation missing exit code status as per this: https://github.com/inspec/inspec/issues/1825 ?

### 💁 Possible Solutions

PR's to README

**Comment by clintoncwolfe** [comment]
The [website docs](https://www.inspec.io/docs/reference/cli/#exec) and CLI usage messages are both in fact generated from the Thor code that configures the CLI.  We'll want to add it there, if possible.
