### ISSUE TITLE
Resource oracledb_session broken if query result contains dozens of records

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3169]
### 🎛 Description

*🐛 bug report 

If result of the query contains many records html parser is broken due to repeating header entry

### 🌍 InSpec and Platform Version

2.2.16

### 🤔 Replication Case

Do a query that returns dozens of rows

### 💁 Possible Solutions

In the options for sqlplus option SET PAGESIZE 32000 needs to be added

**Comment by Nik08** [comment]
This issue seems to have been resolved in 2018 with [#3170](https://github.com/inspec/inspec/pull/3170). But I verified this again myself and this seems to be working.

I tried this:

```
sql = oracledb_session(user: 'USERNAME', password: 'PASS', service: 'XE', host: 'HOST')
describe sql.query("SELECT UPPER(VALUE) AS VALUE FROM V$PARAMETER").rows do
  its('count') { should eq 434 }
end
```

Thanks!
