### ISSUE TITLE
Merge inherited profiles for A2 report

### ISSUE THREAD

**Issue by jquick** [inspec/inspec#3183]
### 🎛 Description

🙋 feature request?

We need to merge the json report to have the parent profiles contain all control and result information from the children. We should also populate the parent depends section with the sha256 and profile inheritance details. 

### 💁 Possible Solutions

Take the current json report and merge upstream on profiles based on `parent_profile` tags. Copy over all control and result information from children if they are not set on the parent.

**Comment by clintoncwolfe** [comment]
#3203 sort of relates here, in spirit, sort of.
