### ISSUE TITLE
mysql_session password sensitivity

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#3185]
### 🎛 Description🙋 feature request

Is it possible to make it so that the mysql_session password is redacted when the name of the test is displayed?

```
✔  Command mysql -uroot -p<NOT_REDACTED> -h localhost  -s -e "show databases" exit_status should eq 0
```

**Comment by clintoncwolfe** [comment]
Quick bit of diagnostics.  We're relying on a `command` resource to run the query, see [here](https://github.com/inspec/inspec/blob/master/lib/resources/mysql_session.rb#L31).  We build up the command line, including the password, [here](https://github.com/inspec/inspec/blob/master/lib/resources/mysql_session.rb#L60).

This comes down to adding functionality to obscure the reporter output from the `command` resource, ideally selectively.

**Comment by kplimack** [comment]
@clintoncwolfe the reporter does sound like the right place to me, too.  I'm running inspec via a handler at the end of chef runs, the output of which gets emailed on failure, and I really dont like when secrets leak, so I'm +1 on getting a `sensitive` parameter for the reporter to use, and happy to help if someone can point me in the right direction.

**Comment by mengesb** [comment]
@kplimack While not a solution; a work-around is to implement mysql's secure encrypted profile file and use that via the command resource and parse the output (stdout). While not ideal, it's what I've come to do until sourcing these configs and using them with the client are available.

related: #3166

**Comment by mengesb** [comment]
Since I wrap the MySQL cookbook --

We do this bit of awful during our initialization (if true):
```ruby
require 'securerandom'

bash 'mylogin.cnf' do
  code <<-MLC
    expect -c '
    set timeout 10
    spawn mysql_config_editor set --login-path=client --host=localhost --user=root --port=#{node['my_db']['port']} --socket=#{::File.join('/var/run', "mysql-#{node['my_db']['name']}", 'mysqld.sock')} --password
    expect "password:"
    send "#{SecureRandom.base64(32)}\r"
    expect eof'
  MLC
  cwd       '/root'
  creates   '/root/.mylogin.cnf'
  sensitive true
  user      'root'
end
```

so we have tests like
```ruby
describe command('/usr/bin/mysql --login-path=client -e "SHOW DATABASES;"') do
  its('exit_status') { should eq 0 }
  its('stdout') { should include 'mysql' }
end
```

Disclaimer: if you delete the `/root/.mylogin.cnf` ... you no longer have access to the DB because the root password is completely unknown. This is acceptable in my world.

**Comment by tarcinil** [comment]
I think this should be re-opened or a new issue created.  

#3207 allows command to take an option to redact, but https://github.com/inspec/inspec/blob/master/lib/resources/mysql_session.rb#L31 does not pass any data to the command in which would enable mysql_session to redact password.

**Comment by jquick** [comment]
@jerryaldrichiii - Can you take a look at this.

**Comment by jerryaldrichiii** [comment]
Apologies all, I did not know this was assigned to me and missed a notification. I have done no work nor am I looking into this currently. I'm going to remove my assignment so expectations are set properly.

**Comment by ejaronne** [comment]
isn't this already solved by ensuring one declares the input properly in the inspec.yml using the "sensitive:" parameter?
For example: https://github.com/mitre/oracle-mysql-ee-5.7-cis-baseline/blob/8d5d86144c15fa7df9d8afa34af7f0ab136f7091/inspec.yml#L23

**Comment by Vasu1105** [comment]
@clintoncwolfe  According to my observations, this looks to be already fixed both in command and mysql_session resources using `redact_regex` option which is also documented here https://docs.chef.io/inspec/resources/command/#redacting-sensitive-commands. Also, I can see the same has been implemented in the mysql_session resource here https://github.com/inspec/inspec/blob/main/lib/inspec/resources/mysql_session.rb#L57. Let me know if anything missing here.

**Comment by Vasu1105** [comment]
@clintoncwolfe please review my recent comments and if you agree with the same we can close this issue.

**Comment by Vasu1105** [comment]
Closing this as this is already taken care of. Reopen if the issue still exists.
