### ISSUE TITLE
Using local data to test cloud resources

### ISSUE THREAD

**Issue by japneet-sahni** [inspec/inspec#3190]
### 🎛 Description
Testing Azure VM's in loop using Inspec Azure Target, gives below error
undefined method `file?' for class `NilClass'

Bug report

Briefly describe the issue and the expected behavior
My use case is to have one control file (.rb) and test multiple Azure machines which are captured in JSON. I am using Azure target in inspec exec command (-t azure://). All the credentials have been set properly.

Command : `AZURE_SUBSCRIPTION_ID="XXXXXXX" AZURE_CLIENT_ID="XXXXXXX" AZURE_CLIENT_SECRET="XXXXXXX" AZURE_TENANT_ID="XXXXXXX" inspec exec inspec-tests/integration/compute/controls/compute_spec.rb -t azure://`

Expected behavior:
The compute_spec.rb should be executed with all entries of virtual machines in present in the json file.
Actual behavior:
```
Profile: tests from inspec-tests/integration/compute/controls/compute_spec.rb (tests from inspec-tests.integration.compute.controls.compute_spec.rb)
Version: (not specified)
Target:  azure://XXXXXXX

  ×  LINUX VM: Integration test > Check that compute has been properly set and provisionned
     ×  Control Source Code Error inspec-tests/integration/compute/controls/compute_spec.rb:3
     undefined method `file?' for class `NilClass'


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
```

### 🌍 InSpec and Platform Version

Inspec : 2.2.16
Platform Version : Centos 7.4

### 🤔 Replication Case

compute_spec.rb
```
title 'Check Azure Resources'

control 'LINUX VM' do

  impact 1.0
  title 'Integration test > Check that compute has been properly set and provisionned'
  desc 'Integration test > Check that compute has been properly set and provisionned'

  json_obj = json('../test.json')
  describe json_obj do
    its('servers') { should_not eq nil }
  end
  if json_obj['servers']
    # loop over the keys array
    json_obj['servers'].each do |intern|

  compute = azure_virtual_machine(group_name: "intern['resource_group_name']", name: "intern['machine_name']")
  describe "intern['machine_name']" do
    subject {compute}
    its('location') { should cmp 'northeurope' }

    its('type') { should cmp 'Microsoft.Compute/virtualMachines' }
    its('name') { should cmp "intern['machine_name']" }
      end
    end
  end
end
```

test.json
```
{
  "servers":[
    {"resource_group_name":"xxxxxx", "machine_name":"cms-sint-dru1"},
    {"resource_group_name":"xxxxxx", "machine_name":"cms-sint-dru2"}
  ]
}
```

EDIT: (@clintoncwolfe): place code in code blocks, remove template boilerplate

**Comment by clintoncwolfe** [comment]
Can you try, in a separate control file:

```
describe file('../test.json') do
  it { should exist }
end
```

**Comment by japneet-sahni** [comment]
@clintoncwolfe : My intention is not to test the key/values in the JSON file. Rather iterate the key/values in JSON in a loop and use their values in the describe method like shown below:
azure_virtual_machine(group_name: "intern['resource_group_name']", name: "intern['machine_name']")

Another thing to notice is, I am facing this issue only if I am using Azure targets. If I use normal ssh targets, I can easily iterate values in JSON using the same snippet.

**Comment by clintoncwolfe** [comment]
ahh, I just re-read your CLI string.  This approach won't work, I'm afraid.  When you set your target to be `-t azure://`, Inspec will look for files "on the azure filesystem" which is nonsensical; and under the hood, the `json` call is just opening a file.

To use local data to drive an inspec run targeting a cloud, you'll need to use [Inspec attributes](https://www.inspec.io/docs/reference/profiles/#profile-attributes).  Convert your JSON file to a YAML file (should be straightforward), then you can do something like:

```
# server-file.yaml
server_list:
  - resource_group_name: xxxxxx
    machine_name: cms-sint-dru1
  - resource_group_name: xxxxxx,
    machine_name: cms-sint-dru2
```

```
# Your control code
servers = attribute('server_list', default:[], description: 'Array of server info')
describe servers do
  it { should_not be_empty }
end
unless servers.empty?
  # loop over the servers array
  servers.each do |intern|
     # Code unchanged
     compute = azure_virtual_machine(group_name: "intern['resource_group_name']", name: "intern['machine_name']")
     describe "intern['machine_name']" do
        subject {compute}
        its('location') { should cmp 'northeurope' }
        its('type') { should cmp 'Microsoft.Compute/virtualMachines' }
        its('name') { should cmp "intern['machine_name']" }
      end
    end
  end
```


```
# New CLI command (note --attrs)
AZURE_SUBSCRIPTION_ID="XXXXXXX" AZURE_CLIENT_ID="XXXXXXX" AZURE_CLIENT_SECRET="XXXXXXX" AZURE_TENANT_ID="XXXXXXX" inspec exec inspec-tests/integration/compute/controls/compute_spec.rb -t azure:// --attrs server-file.yaml
```

**Comment by japneet-sahni** [comment]
@clintoncwolfe : Atleast using your solution, I have made some progress, but I am getting a very weird error while running the command. PFB snapshot

![image](https://user-images.githubusercontent.com/10338163/42384126-74af1e8c-8139-11e8-8435-ee45a16b499f.png)

Contents of yml file
![image](https://user-images.githubusercontent.com/10338163/42384164-9490d02e-8139-11e8-9403-033be53a1817.png)

Contents of compute _loop.rb file
```
servers = attribute('server_list', default:[], description: 'Array of server info')

control 'COMPUTE - CMS PERF DRUPAL' do

impact 1.0
title 'Integration test that compute has been properly set and provisionned'

describe servers do
  it { should_not be_empty }
end
unless servers.empty?
  servers.each do |intern|
     compute = azure_virtual_machine(group_name: "intern['resource_group_name']", name: "intern['machine_name']")
     describe "intern['machine_name']" do
        subject {compute}
        its('location') { should cmp 'northeurope' }
        its('type') { should cmp 'Microsoft.Compute/virtualMachines' }
        its('name') { should cmp "intern['machine_name']" }
      end
    end
  end
end
```

**Comment by clintoncwolfe** [comment]
It looks like Azure doesn't like the resource group names you are sending.  The error message above has a mangled version of the regex they use; looks like they document it [here](https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups/checkexistence#uri-parameters).

From what I can see, though, your resource group names look fine.  I tried it out on [regexr](https://regexr.com/3s30j) and it matches.

I'm at a loss.

@dmccown , @trevorghess , any suggestions?

**Comment by clintoncwolfe** [comment]
Ahh, Trevor and I just spotted it.

```
compute = azure_virtual_machine(group_name: "intern['resource_group_name']", name: "intern['machine_name']")
```

That's passing the literal string `"intern['resource_group_name']"` as the group name, which Azure is rightly rejecting.  Drop the outer quotes and it should work:

```
compute = azure_virtual_machine(group_name: intern['resource_group_name'], name: intern['machine_name'])
```

Apologies, I should have caught that earlier.

**Comment by japneet-sahni** [comment]
@clintoncwolfe : Thank you so much for your help, my test cases have been made more simpler now. Marking this thread as closed.
