### ISSUE TITLE
Support 4 tests in a control with OR(AND(1,2),AND(3,4)) result logic

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3199]
### 🎛 Description

 🙋 feature request

Certain published compliance standards may use slightly complex pass/fail logic.

One example we need to support is a compliance recommendation where 4 tests (`1 2 3 4`) are given and the logic for the overall result is `OR(AND(1,2),AND(3,4)) `

Note that `1` and `2` test different things therefore they can not be 2 `it` tests inside a single `describe` block

### 💁 Possible Solutions

 https://github.com/inspec/inspec/issues/2132 appears to address this, if it's implementation permitted multiple `describe.all` blocks nested inside a `describe.one` block.

**Comment by james-stocks** [comment]
Hi @kekaichinose - 

This one got marked stale. If we're going to take time to discuss the more general problem of how to support more complex control logic then it's OK for this specific issue to be closed.

**Comment by kekaichinose** [comment]
Hi @james-stocks,

I reviewed the `describe.all` issue, and there seems to be enough comments and referenced issues/PRs that warrant us increasing the visibility on this. Would adding something like `describe.all` satisfy this issue here?

**Comment by james-stocks** [comment]
Yes https://github.com/inspec/inspec/issues/2132 would solve this. I'll make sure this specific case is captured as a comment on that issue. 

Thanks!
