### ISSUE TITLE
Best practice for determining if a file is empty

### ISSUE THREAD

**Issue by indepth15** [inspec/inspec#3220]
There are some approaches to verify if a file is empty.

**Approach 1** - using **file** resource to and read its content. Use **eq** matcher to check the output ''

```
describe file('file_path') do
  its(:contents) { should eq ' ' }
end
```

**Approach 2**  - using **file** resource to and read its content, but check null

```
describe file('file_path') do
  its(:contents) { should be nil }
end
```

**Approach 3 (uncommon)** - use **command** resource to execute the cat command

```
describe command('cat /etc/file_path') do
  its(:stdout) { should eq ' ' }
end

```
**Approach 4** - use **should be_empty**

```
describe file('file_path') do
  its(:contents) { should be_empty }
end
```

**Approach 5** - access to **size** property

```
describe file('file_path) do
  its(:size) { should eq 0} 
end
```

I'm quite new to InSpec and hopefully someone can teach me on common approach. Is there a performance impact if using any of uncommon approaches?

Your suggestion would be greatly appreciated.

**Comment by frezbo** [comment]
I would suggest approach 4:
```
~ (aws:rean-gov-sd)(kc)$ touch /tmp/dummy
~ (aws:rean-gov-sd)(kc)$ inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      fedora
    Families:  fedora, linux, unix, os
    Release:   28
    Arch:      x86_64

inspec> describe file('/tmp/dummy').content do
inspec>   it { should be_empty }  
inspec> end  

Profile: inspec-shell
Version: (not specified)


     ✔  should be empty

Test Summary: 1 successful, 0 failures, 0 skipped
inspec> 
```

**Comment by clintoncwolfe** [comment]
This appears to be answered and inactive.  Closing, but feel free to re-open if you have further discussion.  Thanks!
