### ISSUE TITLE
Consider enumerating singular resources from plurals

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3223]
### 🎛 Description

🙋 feature request

This issue is promoting a comment by @TheLonelyGhost from a comment to full issue status.  The [original comment](https://github.com/inspec/inspec/issues/2277#issuecomment-351842804) is below.

---

Can confirm that I was confused by the singular versus plural forms of, e.g., `user` vs. `users` and `package` vs. `packages`. I can see how it would be useful for fuzzy-finding a particular resource where an identifying attribute matches a certain pattern.

All that said, perhaps it would be better to include a uniform list pattern where it only gives back whether the query returned any results, how many results, and unique identifiers for each. In the case of users, it would return the number of users and a list of usernames. Then the developer is free to plug that into the more fleshed-out resource:

```ruby
user_list = users.where { username =~ /service_/i }

describe user_list do
  it { should exist } # If the list is empty, the list effectively does not exist
  its('size') { should eq 4 }
end

user_list.each do |u|
  describe user(u.username) do
    its('shell') { should match(%r{/(?:nologin|false)$}i) }
  end
end
```

---

(@clintoncwolfe again).  To summarize, the proposal is to have plural resources [know](#3165) what their associated single resource is, and which property is an identifier; using those two pieces of knowledge, plural resources could implement `each` and provide the `Enumerable` suite.

Potentially, a similar pattern could be used on other dimensions: you could list security groups associated with an AWS EC2 instance, for example.

### 🌍 InSpec and Platform Version

2.2.34

**Comment by clintoncwolfe** [comment]
Closing as a duplicate of #3621

**Comment by TheLonelyGhost** [comment]
@clintoncwolfe (I think you meant to close the issue?)
