### ISSUE TITLE
Best practices for centralizing and reusing attributes 

### ISSUE THREAD

**Issue by indepth15** [inspec/inspec#3233]
My InSpec profiles have number of ***.rb** files. Each ***.rb** contains list of controls and corresponding attributes, which other ***.rb** file may use.

Is there a reference pattern which centralizes attribute declaration which every control can reuse if needed?

**Comment by jquick** [comment]
https://github.com/inspec/inspec/issues/3176 should help with this. It allows you to define global attributes in the metadata yml file.

**Comment by clintoncwolfe** [comment]
This is now covered by the Inputs documentation at https://www.inspec.io/docs/reference/inputs/
