### ISSUE TITLE
Code field missing when using overlay profile

### ISSUE THREAD

**Issue by ejaronne** [inspec/inspec#3250]
### 🎛 Description
Code field empty when using overlay profile

🐛 bug report 

When using an overlay, the control's code is not populated in the json output.

### 🌍 InSpec and Platform Version

2.2.27

### 🤔 Replication Case

Create an overlay for any profile. Change a field for a control, such as impact, title, desc, or even a tag. Run the overlay and request json output. Viewing the json, for the control impacted, observe that the first occurrence has the overlay statement, but the second occurrence of "code:" field is empty.

### 💁 Possible Solutions

Not sure how to resolve. It is possible that this was related to a bug fix for InSpec to have it correctly accommodate tag changes in an overlay. The overlay operates, but the code field was disrupted somehow.  Note the selected json and the ' **_"code": "",_**' bug

### 💻 Stacktrace

        {
          "id": "V-71913",
          "title": "When passwords are changed a minimum of four character classes must be\nchanged.",
          "desc": "Use of a complex password helps to increase the time and resources required\nto compromise the password. Password complexity, or strength, is a measure of\nthe effectiveness of a password in resisting attempts at guessing and\nbrute-force attacks.\n\n    Password complexity is one factor of several that determines how long it\ntakes to crack a password. The more complex the password, the greater the\nnumber of possible combinations that need to be tested before the password is\ncompromised.",
          "impact": 0,
          "refs": [
            {
              "ref": []
            }
          ],
          "tags": {
            "gtitle": "SRG-OS-000072-GPOS-00040",
            "gid": "V-71913",
            "rid": "SV-86537r1_rule",
            "stig_id": "RHEL-07-010170",
            "cci": [
              "CCI-000195"
            ],
            "documentable": false,
            "nist": [
              "IA-5 (1) (b)",
              "Rev_4"
            ],
            "check": "The \"minclass\" option sets the minimum number of required\nclasses of characters for the new password (digits, upper-case, lower-case,\nothers).\n\nCheck for the value of the \"minclass\" option in\n\"/etc/security/pwquality.conf\" with the following command:\n\n# grep minclass /etc/security/pwquality.conf\nminclass = 4\n\nIf the value of \"minclass\" is set to less than \"4\", this is a finding.",
            "fix": "Configure the operating system to require the change of at least\nfour character classes when passwords are changed by setting the \"minclass\"\noption.\n\nAdd the following line to \"/etc/security/pwquality.conf conf\" (or modify the\nline to have the required value):\n\nminclass = 4",
            "fix_id": "F-78265r1_fix"
          },
          "code": "control 'V-71913' do\n\timpact 0.0\n\tend\n",
          "source_location": {
            "line": 180,
            "ref": "my-overlay/controls/my-overlay.rb"
          },
          "results": []
        },

        {
          "id": "V-71913",
          "title": "When passwords are changed a minimum of four character classes must be\nchanged.",
          "desc": "Use of a complex password helps to increase the time and resources required\nto compromise the password. Password complexity, or strength, is a measure of\nthe effectiveness of a password in resisting attempts at guessing and\nbrute-force attacks.\n\n    Password complexity is one factor of several that determines how long it\ntakes to crack a password. The more complex the password, the greater the\nnumber of possible combinations that need to be tested before the password is\ncompromised.",
          "impact": 0,
          "refs": [
            {
              "ref": []
            }
          ],
          "tags": {
            "gtitle": "SRG-OS-000072-GPOS-00040",
            "gid": "V-71913",
            "rid": "SV-86537r1_rule",
            "stig_id": "RHEL-07-010170",
            "cci": [
              "CCI-000195"
            ],
            "documentable": false,
            "nist": [
              "IA-5 (1) (b)",
              "Rev_4"
            ],
            "check": "The \"minclass\" option sets the minimum number of required\nclasses of characters for the new password (digits, upper-case, lower-case,\nothers).\n\nCheck for the value of the \"minclass\" option in\n\"/etc/security/pwquality.conf\" with the following command:\n\n# grep minclass /etc/security/pwquality.conf\nminclass = 4\n\nIf the value of \"minclass\" is set to less than \"4\", this is a finding.",
            "fix": "Configure the operating system to require the change of at least\nfour character classes when passwords are changed by setting the \"minclass\"\noption.\n\nAdd the following line to \"/etc/security/pwquality.conf conf\" (or modify the\nline to have the required value):\n\nminclass = 4",
            "fix_id": "F-78265r1_fix"
          },
          "code": "",
          "source_location": {
            "line": 180,
            "ref": "my-overlay/controls/my-overlay.rb"
          },
          "results": [
            {
              "status": "failed",
              "code_desc": "Parse Config File /etc/security/pwquality.conf minclass.to_i should cmp >= 4",
              "run_time": 0.000813171,
              "start_time": "2018-07-03T09:15:30-04:00",
              "message": "\nexpected it to be >= 4\n     got: 0\n\n(compared using `cmp` matcher)\n"
            }
          ]
        },

**Comment by jquick** [comment]
Yes, this was a change to make sure we don't show invalid code text. If you override a control you will show the override code. This does have the issue of not showing the whole picture if you only override a specific field though. We will look into seeing if we can merge them instead.

**Comment by ejaronne** [comment]
Yes please! When we display the json, we display the code as well to help both the developer and the auditor agree that the test was valid. Merging would be superb! Thanks!

**Comment by aaronlippold** [comment]
@jquick thanks. We need to keep this in place as we need to maintain the transparency of the overlay. If we can push this is actually quite an issue. Thanks for pushing it up for us.

**Comment by jquick** [comment]
For now, the working solution is to populate the profiles with the proper code found in those profiles. So you can see the different layers of override if you wish.

**Comment by aaronlippold** [comment]
@jquick So we have to use regression to find a not_nil code block with a control.id in the json structure?

**Comment by jquick** [comment]
Well you will have multiple ones now. You will have the old and the new per say. The profile will show the code for that profile, and it will show the updated code on the wrapper if set.
