### ISSUE TITLE
Question: Should we prepending `LANG=en_US.utf8` to the `command` resource commands?

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3262]
Some commands can output text that is not UTF-8 which will cause InSpec to crash.

Should we prepend `LANG=en_US.utf8` before commands in the `command` resource?

Aha! Link: https://chef.aha.io/features/SH-2207

**Comment by aaronlippold** [comment]
Hi,

This has come up enough times I think for us to abstract it in the resource
I think.

Just my two cents.

Aaron
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by jerryaldrichiii** [comment]
Just had a thought. If we implement this we may need to do some checks to make sure `LANG=en_US.utf8` is supported on the backend that `command` is run on.

**Comment by trevor-vaughan** [comment]
Ideally, it would be set to whatever the target system actually is. That way people's checks will work in their native language.

Thinking about this, it might have to default to `en_US.utf8` but be allowed to be changed per check in case someone is using a different `utf8` set for their target checks.

**Comment by aylham** [comment]
Working in a environment not set by default to `en_US.utf8` it will be a nice addition, just precise in the doc that the `stdout` will be in English. My actual workaround is :
```ruby
 25     def initialize(cmd)
 26       if cmd.nil?
 27         raise 'InSpec `command` was called with `nil` as the argument. This is not supported. Please provide a valid command instead.'
 28       end
 29       @command = cmd
 30       @commandEnv = "LANG=en_US.UTF-8 "+ cmd
 31     end
 32 
 33     def result
 34       @result ||= inspec.backend.run_command(@commandEnv)
 35     end
```
FYI this is the same problem with the yum resource as the regex look for the english output.

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
