### ISSUE TITLE
Profiles Doc Page has broken image links

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3268]
### 🎛 Description

🐛 bug report

The [profiles reference docs page](https://www.inspec.io/docs/reference/profiles/) has several mis-rendered image links.  Screenshot below.

![image](https://user-images.githubusercontent.com/156460/43651786-526fd454-9711-11e8-9d3d-1e5e12ccac17.png)

### 🌍 InSpec and Platform Version

2.2.55

**Comment by espoelstra** [comment]
I think I had noticed this on another page previously as well, but noticed this today and came here to report it but happy to upvote instead.
