### ISSUE TITLE
Bash resource should support heredoc script

### ISSUE THREAD

**Issue by gpr** [inspec/inspec#3276]
### 🎛 Description

🙋 feature request

I need to execute some complex script on the target that will generate the ouput to parse, I would expect to have the following support:

```
script = <<-EOH
  # a Bash script
EOH

describe bash(script) do
  its('property') { should eq 'output' }
end
```

### 🌍 InSpec and Platform Version

2.2.41, Ubuntu 18.04. Transport: SSH

### 💁 Possible Solutions

I tried several solutions based `inspec.bash` and `inspec.command` without success.

Currently I'm using upload to create the script on the target:

```
script = <<-EOH
  # The shell script
EOH

# Create a temporary file
tmpfile = Tempfile.new('script', '/tmp')
tmpfile_path = tmpfile.path

# Write the script
tmpfile.write(script)
tmpfile.close

# Upload it to the target
inspec.backend.upload(tmpfile_path, tmpfile_path)

# Delete the local file
tmpfile.unlink

# Execute the script
inspec.command("sh #{tmpfile_path}", path: '/bin/sh')

# Delete the target file
inspec.command("rm -f #{tmpfile_path}")

```

**Comment by zenspider** [comment]
What you're asking for "_support heredoc script_" is a standard ruby feature and works as you described:

```ruby
script = <<-EOH
  echo hello world
EOH

describe bash(script) do
  its('stdout') { should eq "hello world\n" }
end
```

results in:

```
  Bash command   echo hello world

     ✔  stdout should eq "hello world\n"
```

So, I suspect you're asking for something else instead, but there's not enough reproduction here to tell. Please advise.

**Comment by zenspider** [comment]
Closing. Feel free to reopen if you have any further issues.
