### ISSUE TITLE
Junit Jenkins Plugin doesn't display target

### ISSUE THREAD

**Issue by EkaterinaBudnikov** [inspec/inspec#3281]
### 🎛 Description - 🐛 bug report

I’m running Inspec to check some sshdconfigs. I have a loop that runs through a file with all my hosts. In Jenkins I can see the hosts (target) in the cli output of the Jenkins console. The junit reporter writes the target attribute into the junit.xml file. But the junit plugin in Jenkins doesn’t display the hosts (target) in its report. This means I just get a list of the failed tests but not where they occur. The target should be processed by the junit plugin so that it an be displayed.

<img width="890" alt="screenshot junit plugin report" src="https://user-images.githubusercontent.com/12811776/43901297-73648d3c-9be7-11e8-9dbf-2ece8bb6cbd8.png">

### 🌍 InSpec and Platform Version

InSpec version: 2.2.55
OS: Ubuntu 16.04

### 🤔 Replication Case

1) Write a control that loops over different hosts. 
2) Add junit reporter to the Inspec exec command (--reporter cli junit:/www/jenkins-ci/workspace/inspec/test-reports/junit.xml). 
3) Install junit plugin in Jenkins. 
4) Add junit as a post build action with the location '**/test-reports/*.xml' to the Jenkinsfile.
5) Run the build.
6) Look at the test result.

### 💁 Possible Solutions

Tell the junit plugin to read the target attribute from the xml.

**Comment by jquick** [comment]
Hey @EkaterinaBudnikov ! Thanks for reporting this. We do not support the Jenkins junit plugin here. It looks like that is maintained over here https://github.com/jenkinsci/junit-plugin. As you said the inspec junit.xml report does include the target so it should just be pulling that into the junit plugin code.
