### ISSUE TITLE
inspec.io website design ideas

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#3289]
### 🎛 Description

This is a collection of issues for a future website redesign of inspec.io. It aggregates and closes all other website ideas we have in this repo.

- [ ] get your InSpec swag section https://github.com/inspec/inspec/issues/1532
- [ ] events feed in events.inspec.io https://github.com/inspec/inspec/issues/1492 https://github.com/inspec/inspec/issues/1465

**Comment by kekaichinose** [comment]
Closing this issue out as we are revisiting the design updates and are considering collapsing the micro-site back into the chef.io macro-site.
