### ISSUE TITLE
Not supported on my platform - be more helpful

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#3292]
### 🎛 Description

**Choose one:** 🙋 feature request

When a resource is not supported on the platform, the report just says "[RESOURCE] is not supported on platform [PLATFORM]". This may lead to confusion for the user (e.g. firewalld running against windows, it just says not supported on windows 10, which makes us think this may just be the version of windows instead of showing that it's not meant for windows at all). 

### 🌍 InSpec and Platform Version

2.2.61

### 🤔 Replication Case

run firewalld test on windows

### 💁 Possible Solutions

Just extend it with: "It is only supported on [PLATFORMS]"

**Comment by zenspider** [comment]
DONE!
