### ISSUE TITLE
SetUp / TearDown hooks

### ISSUE THREAD

**Issue by astorath** [inspec/inspec#3295]
### 🎛 Description
**Choose one**: 🙋 feature request

As an infrastructure developer I want to use inspec as testing framework in kitchen-test environment.

[ ] Testing frameworks usually include SetUp / TearDown hooks that can prepare or clean up the environment to run tests. 
[ ] This is quite difficult to debug test cases during kitchen verify step: there are little to no information about what went wrong. I want an easy way to execute some arbitrary one-line commands during SetUp / TearDown phases and print output / status codes etc.
[ ] Adding custom methods is tearsome: I want to be able to define custom ruby methods in testsuite file directly.

### 🌍 InSpec and Platform Version
Any

**Comment by chris-rock** [comment]
@astorath Thank you for your feature request. I'd like to understand the use case a bit better. Are you aware of [kitchen-inspec](https://github.com/inspec/kitchen-inspec) and [molecule](https://github.com/metacloud/molecule/blob/69392a83ecc38e141aa1af25ca8cd4fdfd1bb244/test/scenarios/verifier/molecule/inspec/verify.yml)

**Comment by astorath** [comment]
@chris-rock, I was using `kitchen-inspec` to test my ansible and salt modules until recently. Then I switched to [bats](https://github.com/sstephenson/bats) testing framework instead of inspec (for the reasons described in the issue)

Sample scenarios are:
- apply ansible role
- verify that everything is fine
- break something (stop systemd service, for instance)
- reapply ansible role
- verify that everything is fine again
or
- apply ansible role
- verify that everything is fine
- change some setup
- reapply ansible role
- verify that everything is fine again

The key here is:
1. kitchen does run ansible role / salt module once
2. I want to test the role in different scenarios (like components version upgrade) on dirty environment, not just laboratory test on clean machine
3. So I want testing tool to be able to:
  * apply some changes to the environment
  * revert the changes, so that other tests can work in "clean" environment again

**Comment by frezbo** [comment]
Inspec is never intended to be a provisioner, it's supposed to be a testing/valiadation tool. The features you need should be included in your CI workflow in the way you need. And for the lifecycle hooks please take a look at the new lifecycle hooks feature added to TK.

**Comment by ofayans** [comment]
Hi! I would also very much appreciate this feature.

**Comment by astorath** [comment]
For anyone still searching for this in 2021:

1. You can actually use RSpec default hooks https://relishapp.com/rspec/rspec-core/v/2-14/docs/hooks/before-and-after-hooks like this: 
```ruby
describe "" do
  before(:each) do
    # setup
  end
  describe file('path') do
    it { should PROPERTY 'value' }
  end
end
```
This is not very clean because InSpec discourages nested `describe`, but it's a good option IMHO.
2. **ServerSpec** has `pre_command`, though you can always use nested `describe` as well.
3. There's also a **TestInfra** option with full power of **pytest**.

**Comment by clintoncwolfe** [comment]
Lifecycle hooks in Test Kitchen are the supported method for this need. I'm going to close this. Thanks!
