### ISSUE TITLE
Terraform data parsing issue

### ISSUE THREAD

**Issue by khaljimbo** [inspec/inspec#3299]
### 🎛 `load_with_context': undefined method `[]'

I am loading Terraform output into my InSpec so I can test my infrastructure. I have followed the instructions here: https://lollyrock.com/articles/inspec-terraform/ 

### 🌍 InSpec and Platform Version

I am running InSpec 2.2.61

### 🤔 Replication Case

This is what my code looks like
```ruby
title 'Azure Infrastructure Tests'

# load data from Terraform output
content = inspec.profile.file("terraform.json")
params = JSON.parse(content)

# Terraform output variables

AZURE_RG = params['resourceGroupName']['value']
AZURE_RGLocation = params['resourceGroupLocation']['value']
AZURE_HostName01 = params['hostName01']['value']
AZURE_HostName02 = params['hostName02']['value']
AZURE_NSG_FE = params['frontendNSGName']['value']
AZURE_NSG_BE = params['backendNSGName']['value']
AZURE_NSG_MGT = params['managementNSGName']['value']

control 'azurerm_infrastructure' do

  impact 1.0
  title 'Check the properties of the resource group' 
  desc 'A set of tests to ensure the infrastructure is built to the correct properties'

  # Start the tests

    describe azure_resource_group(name: AZURE_RG) do
    
    its('name') { should cmp AZURE_RG }
    its('location') { should cmp AZURE_RGLocation } 
    its('provisioning_state') { should cmp 'Succeeded' }
    it { should have_tags }
    its('tag_count') { should be 3 }
    its('tags') { should include 'product' }
    its('total') { should eq 21 }
    it { should have_vms }
    its('vm_count') { should eq 2 }
    it { should have_nics }
    its('nic_count') { should eq 6 }
    it { should have_nsgs }
    its('nsg_count') { should eq 1 }
    it { should have_managed_disks }
    its('managed_disk_count') { should eq 2 }
    it { should have_availibility_set }
    its('availibility_set_count') { should eq 1 }

  end
end
```

When these tests run, I get:

 [command]/usr/bin/inspec exec . -t azure:// --reporter cli junit:junit.xml
 ./controls/tests_infra.rb:10:in `load_with_context': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile_context.rb:158:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile_context.rb:158:in `load_with_context'
 ./controls/tests_infra.rb:10:in `load_with_context': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile_context.rb:142:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile_context.rb:158:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile_context.rb:158:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile.rb:171:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile_context.rb:142:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile.rb:168:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile.rb:171:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile.rb:168:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile.rb:168:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:92:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/profile.rb:168:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:81:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:92:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:81:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:81:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:102:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:81:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/cli.rb:172:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/runner.rb:102:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/lib/inspec/cli.rb:172:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/bin/inspec:12:in `<top (required)>'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.61/bin/inspec:12:in `<top (required)>'
from /usr/bin/inspec:102:in `load'
from /usr/bin/inspec:102:in `load'
from /usr/bin/inspec:102:in `<main>'
from /usr/bin/inspec:102:in `<main>'
undefined

**Comment by jerryaldrichiii** [comment]
Thanks for the info @khaljimbo. Could you do me a favor and put `require 'pry'; binding.pry` below `params = JSON.parse(content)`

Then, run your exec command again and you will be placed in a REPL (Read–Eval–Print Loop), where you can view your variables among other things. 

After entering the REPL, run `params` and place the output here.

I suspect that `params['resourceGroupLocation']['value']` is `nil`

**Comment by clintoncwolfe** [comment]
Hi! We'd love to help you more with this, but we need more information.  Since this issue has sat for several months, I'm going to close this, but feel free to re-open it if you have more to discuss on this topic.
