### ISSUE TITLE
Ability to set an attribute via the cli

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#3300]
🙋 feature request?

As part of our updates to attributes in inspec 3.x, we are also seeing more and more use of inspec in the ci/cd pipeline. The ability to pass these things only via the `attributes.yml` or via some `pipe foo` work yes, but a more stabilized approach would be great.

The ability to set an attribute from the CLI would be very useful as run / job specific data is easiest to push right form the task level. Examples would be the 'container_id'/container_name the pipeline just randomly created or a EC2 id that was just built. Further, things stored in Vault which I can request real time via a cli or perhaps a dynamic user_id or other data etc. 

`inspec exec . -t ... --attr='container_id':"${ID}" --attr=user:$USER --attrs=attributes.yml ` 

#719

**Comment by scalp42** [comment]
@aaronlippold any chance you could share how you overwrite with CLI without passing a yaml?

**Comment by aaronlippold** [comment]
@scalp42 at the moment there are only a couple of hacks which have been used to pass data via the CLI. I have looked at things like dynamically creating a yaml file and passing it to the pipeline. And there are some tricks with the Json config but both of these are brittle in my opinion so I opened this issue 2 push the community to help out with a PR to make the capability more stable.

**Comment by clintoncwolfe** [comment]
I really want this feature, as well.  

Two thoughts occur to me.

1. Attributes are specific to a particular profile.  What would the syntax be for that? (if you have a `wrapper` profile, which depends on `webserver` and `mysql` profiles, all three of which have a `user` attribute, how do you specify which you are setting?)
2. I think this should only be for scalars (strings, numbers, booleans).  If you need Arrays, hashes, and nested things, use the `--attrs=somthing.yaml` after writing a temporary YAML file (or using a shell-specific redirection trick).

**Comment by aaronlippold** [comment]
Hello, is your concern with item 2 due to the possible complexity of
escaping arrays and hashes on the command line? If so I guess that would
make sense. Although an array maybe easier to mitigate. I could see the
challenge with the hash but that's why God made single quotes right?

I agree with your first point in the fact that the primary use case for me
is to pass some Singleton string of data like a username or password a
bucket idea container name something like that dynamically to the profile
or surpass it from up the chain in a CI CD process.

For the initial capability I am totally behind Clinton's proposal and we
can look at addressing the more advanced data types in the next iteration.
However I would guess as we implement the capability we may find that we
can support most of the data types more easily than we initially assumed.

**Comment by darkn3rd** [comment]
I really would like this feature.  This is a major pain point for testing.

**Comment by scalp42** [comment]
Thanks a lot @clintoncwolfe 🎉
