### ISSUE TITLE
Describe.one scenario handling with more than one true condition

### ISSUE THREAD

**Issue by Cmouli7** [inspec/inspec#3305]
### 🎛 Description

**Choose one:** This is a 🙋 feature request?

Hi there, I am trying to build and test with inspec for scenario where test should pass for more than 1 condition being true. Example code below
.

### 🌍 InSpec and Platform Version

inspec-2.1.43-1.el7.x86_64.rpm

### 🤔 Replication Case
```ruby
describe.one do
_ describe ConfigurationA do_
_ its('setting_1') { should eq true }_
_ end_

_ describe ConfigurationB do_
_ its('setting_2') { should eq true }_
_ end_

_ describe ConfigurationC do_
_ its('setting_3') { should eq true }_
_ end_

_ describe ConfigurationD do_
_ its('setting_4') { should eq true }_
_ end_
end
```
situation can be any 2 of the above being true, test should pass... else fail.

Please can you suggest how can this be handled...

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by frezbo** [comment]
@Cmouli7 just use `describe.two`

**Comment by Cmouli7** [comment]
@frezbo - Did try that already and got No method error
 undefined method `two' for #<#<Class:0x0000000002bde640>:0x0000000002bde578> (NoMethodError)

**Comment by frezbo** [comment]
Strange I am seeing the same error too, I remember it used to work long back. @jerryaldrichiii Any thoughts?

**Comment by jerryaldrichiii** [comment]
I don't remember a `describe.two`. I only see `.one` here: https://github.com/inspec/inspec/blame/master/lib/inspec/describe.rb#L17

I also can't think of a way to say that at least two should pass without an absurd amount of permutations.  I'll flag this as a feature request though because there is value here.

**Comment by Cmouli7** [comment]
Thanks @frezbo and @jerryaldrichiii 
Got a couple of questions
1) is it good idea to handle a situation to check(and pass) when 50% of different condition are satisfied rather limiting to one or two. understand a lot of permutations isn't good but say 2/4 or 3/5 for ex.  just a thought :)
2) Just curious to know how long does a FR gets implemented to a release for use?

**Comment by clintoncwolfe** [comment]
On 1, if you're looking for a general case, one could propose syntax like this:

```
describe.threshold(2) do
  describe ...
  describe ...
  describe ...
  describe ...
end
```

Other words besides "threshold" might be better (pass_if_at_least_n_pass would be a very verbose, literal choice).  We'd check for prior art, too; if something like RSpec, ServerSpec, AwsSpec, etc implements something similar, we'd want to examine their approach (and do something similar, or intentionally avoid something we don't like).

 For 2, InSpec is open-source.   That means things generally get implemented in one of two ways:
(A) If its fits a business goal of Chef, Inc., chef engineering staff (/me waves) will work on it and submit a pull request.  The timelines for that are generally not managed publicly, but not a big secret either.  
(B) If you want / need it, and (A) doesn't apply, you get to participate in open source! Fork, branch, submit a PR, and we'll review, possibly tweaking along the way.

**Comment by jerryaldrichiii** [comment]
@Cmouli7 I'd say if you are worried about X% of tests passing I would handle that logic outside of InSpec...I'm having a hard time coming up with a scenario where that would be desirable. I was thinking of something like `describe.at_least(2)` or some such...but I'm still having trouble thinking of a use case.

Regarding time from getting marked as a feature request to release, it all depends. We triage things and work as needed (for example we are focusing on InSpec 3.0 milestones now). See: https://github.com/inspec/inspec/milestone/28

**Comment by jerryaldrichiii** [comment]
Ah, didn't hit refresh! @clintoncwolfe as usual is 100% right on all points :smile:

**Comment by Cmouli7** [comment]
@clintoncwolfe - Thanks for your response and like your proposed syntax. I will wait for it be a part of official release(if considered as a case) as i am currently trying to handle this scenario with a workaround in ruby script. @jerryaldrichiii - Can i ask what would be your proposal to handle this outside of inspec. will be great if you share as an example.

**Comment by jerryaldrichiii** [comment]
@Cmouli7 I would need more info to give an example. I can't think of a use case. If checking X% is passing, best I can think of now is using `--reporter json`, extracting the pass/fail/total, and then making a decision based on the output.

If you don't mind, try joining the Chef Community Slack (http://community-slack.chef.io/) and asking in the #inspec channel, lots of smart folks there.

**Comment by Cmouli7** [comment]
@jerryaldrichiii  this is my scenario... we have IBM MQ queues running on AWS Ec2 servers and i am trying to verify if minimum number of queues required are up and running when servers are built. for ex, we have 5 queues and will be compared with inspec stdout using command resourse

AWSMQ_queue1,2,3,4,5 and sample code i am trying to achieve

describe.one do   # wanted to try with describe.two / describe.threshold(x)

describe command(dspmq) do
 its('stdout') { should match (/AWSMQ_queue1/) }
end
describe command(dspmq) do
 its('stdout') { should match (/AWSMQ_queue2/) }
end
describe command(dspmq) do
 its('stdout') { should match (/AWSMQ_queue3/) }
end
describe command(dspmq) do
 its('stdout') { should match (/AWSMQ_queue4/) }
end
describe command(dspmq) do
 its('stdout') { should match (/AWSMQ_queue5/) }
end

end

I will also try to join the slack group and post my questions. Thanks!

**Comment by jerryaldrichiii** [comment]
That is a superb use case!

Since I can't give you a date by when/if this feature will be added. Something like this should get you by in the meantime:
 
```ruby
output = inspec.command.stdout(dspmq)

# Create a list to hold matching queue names (will return `nil` if match fails)
results = []
results << output[/AWSMQ_queue1/]
results << output[/AWSMQ_queue2/]
results << output[/AWSMQ_queue3/]
results << output[/AWSMQ_queue4/]
results << output[/AWSMQ_queue5/]

# Use expect syntax for pretty output 
# Note: We recommend should syntax..but this is a special case
# See: https://www.inspec.io/docs/reference/profiles/#should-vs-expect-syntax
describe 'IBM MQ' do
  it 'has at least 3 running queues' do
   # Remove `nil`s from the list and count remaining
    expect(results.compact.count).to be >= 3
  end
end
```

**Comment by Cmouli7** [comment]
Thanks @jerryaldrichiii . had to make below minor correction as i was getting an error
output = inspec.command(dspmq).stdout instead of 
output = inspec.command.stdout(dspmq)

**Comment by jerryaldrichiii** [comment]
Hah, yup. Sorry bout that.
