### ISSUE TITLE
Button text overflows borders.

### ISSUE THREAD

**Issue by kagarmoe** [inspec/inspec#3306]
### 🎛 Description

🐛 bug report

UI : text overflows buttons on /inspec/docs

### 🤔 Replication Case
<img width="1920" alt="screen shot 2018-08-20 at 11 37 04 am 2" src="https://user-images.githubusercontent.com/4400151/44359788-b9c6bc80-a46d-11e8-890a-63383ad1a69f.png">

### 💁 Possible Solutions

CSS fix

**Comment by clintoncwolfe** [comment]
I believe this was traced to a zoom issue?

**Comment by TrevorBramble** [comment]
@clintoncwolfe Seeing the unexpected behavior when using zoom doesn't mean it isn't a style bug. Either the box should enforce minimum dimensions or (less likely) the text should resize/reflow.
