### ISSUE TITLE
Infer "--sudo" when only given "--sudo-password"

### ISSUE THREAD

**Issue by pwelch** [inspec/inspec#3310]
### 🎛 Description
🙋 feature request

If a user needs to provide `--sudo-password` and leaves off the `--sudo` flag, assume they meant to add the `--sudo` flag.

**Comment by chris-rock** [comment]
Could we return an error if no password is provided instead?

**Comment by pwelch** [comment]
@chris-rock I think that would be a helpful feature but not what I was thinking of this issue. 

If a user does `inspec exec profile.rb <TARGET> --sudo-password=PASSWORD` then they meant to run as sudo but didn't include the flag.

**Comment by pwelch** [comment]
Fix on #3313

**Comment by jerryaldrichiii** [comment]
After speaking with the team, we've elected to add `--sudo` if using `--sudo-password` without it and warn the user (see: https://github.com/inspec/inspec/pull/3313)

I've also added https://github.com/inspec/train/issues/340 to raise an error in Train in the next major version.

**Comment by pwelch** [comment]
Closing since since @jerryaldrichiii patched it
