### ISSUE TITLE
`only_if` returns confusing title if no title in control

### ISSUE THREAD

**Issue by dmccown** [inspec/inspec#3328]
### 🎛 Description

🐛 bug report

When skipping a control with `only_if` and no title given a default title of `Operating System Detection` is given. See replication case for more details.

### 🌍 InSpec and Platform Version

* inspec (2.2.70)
* Mac OS 10.13.6

### 🤔 Replication Case

When skipping a control with `only_if`, no title specified in my control, and use the progress flag I get:

```
  1) Operating System Detection Skipped control due to only_if condition: network watcher is not enabled.
     # Not yet implemented
     #

  2) Operating System Detection Skipped control due to only_if condition: network watcher is not enabled.
     # Not yet implemented
     #
```
It looks like it always defaults to `Operating System Detection`. 

I added a title to my control, re-ran, and received the same output. 

I then remove the `--progress` flag re-run and saw:
```
  ↺  azurerm_network_watchers: Azurem Network Watchers
     ↺  Skipped control due to only_if condition: network watcher is not enabled.
```
Removing the title from the control gives me:
```
  ↺  azurerm_network_watcher: Operating System Detection
     ↺  Skipped control due to only_if condition.
```

I was confused with the default title being given. Could we have some kind of title that says your control doesn't have a title? Or default to the control name? 

### 💁 Possible Solutions

N/A

### 💻 Stacktrace

N/A

**Comment by frezbo** [comment]
@dmccown can you paste your control too?

**Comment by frezbo** [comment]
ahh I see the same, never actually paid much attention to output and most of my controls had title. Good catch

**Comment by zenspider** [comment]
This now returns "no-op".
