### ISSUE TITLE
Remove deprecated `format` option from CLI for 3.0

### ISSUE THREAD

**Issue by miah** [inspec/inspec#3339]
Looks like check, detect, and a few other cli systems support `format`, should they all use `reporter` now? Seems like `--reporter` should be everywhere for consistency.

https://github.com/inspec/inspec/blob/master/lib/inspec/base_cli.rb#L80-L121
https://github.com/inspec/inspec/blob/master/lib/inspec/cli.rb#L66
https://github.com/inspec/inspec/blob/master/lib/inspec/cli.rb#L183
https://github.com/inspec/inspec/blob/master/lib/inspec/cli.rb#L205
https://github.com/inspec/inspec/blob/master/lib/inspec/cli.rb#L258

ref: https://github.com/inspec/inspec/issues/2458

**Comment by nitrocode** [comment]
Yup. Still seeing that with this in my `.kitchen.yml` file

```
verifier:
  format: documentation
```

**Comment by miah** [comment]
Fixed by https://github.com/inspec/inspec/pull/3452
