### ISSUE TITLE
Request - improve `inspec check` warnings for use in CI

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3348]
### 🎛 Description

 🙋 feature request

Currently I use `inspec check` in CI. Any errors are a failure, otherwise any (or no) warnings is allowed as a pass.
I would like to make this more strict and fail on warnings; but there's a couple of reasons why I can't immediately do this:

 * Inspec returns 0 when there are warnings (as a workaround I can capture stdout/stderr and grep for warnings)
 * There is one warning that I cannot do anything about: `Control my_control has no tests defined` - this warning appears when all a control's tests are inside a Ruby conditional/iterator block that the mock backend can't mock

### 💁 Possible Solutions

 * Don't warn for `Control my_control has no tests defined`
 * Make `Control my_control has no tests defined` a different class of entry than warning e.g. INFO or NOTICE
 * Make the warnings I do care about (no control title, no control description, version not semver, license not SPDX format etc etc) errors and not warnings (this doesn't seem right, but it's a possibility!)
 * Improve `inspec check` to acknowledge that there are tests in the Ruby code; even if it can't parse and check them
 * Allow some option to raise/lower the level that `inspec check` will give warnings at; to exclude things like `Control my_control has no tests defined` that aren't necessarily a fault.

**Comment by clintoncwolfe** [comment]
I think that #3549, if implemented, would cover all of the needs listed on this issue. The issues are linked, so we can refer to it when implementing 3549. 

So, I'm going to close this and mark as a duplicate.  If you feel I've missed the mark, please feel free to re-open.
