### ISSUE TITLE
Feature Request: EditorConfig

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#3365]
### 🙋 When I run `inspec init` I would love an `EditorConfig` to be placed in the root

What is [EditorConfig](https://editorconfig.org)?

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

This obviously depends on **RFC inspec style guide** https://github.com/inspec/inspec/pull/3356
as soon this done we can implement this

**Comment by jerryaldrichiii** [comment]
I like the idea of EditorConfig, but I don't think I want to force it on all of our users.

That being said, a custom generator like `chef generate cookbook` sounds neat. I'll flag this as a feature request regardless.

**Comment by kmf** [comment]
@clintoncwolfe could you link to the `chef generate cookbook` Feature?
