### ISSUE TITLE
InSpec archives are not extracted during vendoring on Windows

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3368]
### 🎛 Description

this a 🐛 bug report

On Windows profiles are not extracted properly on commit 9d175279. I can confirm that it works on macOs without any issues.

```
λ bundle exec inspec version
2.2.81

λ tree trial\lb-inspec-profile
Folder PATH listing
Volume serial number is C0000100 8ECA:AF30
C:\USERS\CHRIS\INSPEC\TRIAL\LB-INSPEC-PROFILE
├───controls
└───libraries

λ bundle exec inspec vendor trial\lb-inspec-profile
Dependencies for profile trial\lb-inspec-profile successfully vendored to trial\lb-inspec-profile/vendor

λ tree trial\lb-inspec-profile
Folder PATH listing
Volume serial number is C0000100 8ECA:AF30
C:\USERS\CHRIS\INSPEC\TRIAL\LB-INSPEC-PROFILE
├───controls
├───libraries
└───vendor

λ ls trial\lb-inspec-profile\vendor\
3ed3fcda4b03936f063f65598a7a08b2e37bd7a0a805939d1c0ba861b7160cc8.tar.gz
568ed748ee0d4ccc73e5d21f61ea4e7a123e686161370ee23b983ae8cdbe141c.tar.gz
```

### 🌍 InSpec and Platform Version

2.2.81 which includes https://github.com/inspec/inspec/pull/3286

### 🤔 Replication Case

Use a profile with profile inheritance on Windows

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by clintoncwolfe** [comment]
I'd like to see a specific test case for this; appveyor passed #3286, so we must have a gap.
