### ISSUE TITLE
test/helper.rb should be refactored

### ISSUE THREAD

**Issue by miah** [inspec/inspec#3380]
### 🎛 Description

Our `test/helper.rb` is too complex, which makes it difficult to require on tests without potentially causing issues. It: sets up code coverage, sets up minitest, requires a bunch of other libraries (like json, tmpdir, tempfile), require a bunch of InSpec itself, and creates a MockLoader system.

Our helper should be _simple_ it should set up code coverage, and minitest.

### 💁 Possible Solutions

We should split up the Mockloader into its own file. Possibly create a `mock_helper.rb` and tests that use the mocking system could require that.

**Comment by clintoncwolfe** [comment]
When writing example tests for the plugin example, I found that doing `require 'inspec'` caused minitest/spec to think there were zero tests.  I was obliged to more carefully pickout which inspec library files to load.

That is part of sadness of the current helper.rb :(

**Comment by zenspider** [comment]
DONE!
