### ISSUE TITLE
Resource windows_task fails when multiple triggers defined

### ISSUE THREAD

**Issue by bpeters-mcis** [inspec/inspec#3395]
### 🎛 Description

🐛 bug report

When running an inspec test to verify the settings of a windows_task, it fails with "∅  no implicit conversion of String into Integer" if the task has multiple triggers defined.

### 🌍 InSpec and Platform Version

I've tested this with inspec versions 1.45.13, which I subsequently upgraded to 2.2.70, both have the same behavior.

Tests run on Mac OS 10.13 against both Windows 10 Pro and Windows 10 Enterprise clients.

### 🤔 Replication Case

1. Create two tasks on a Windows 10 client.  The action does not matter, but set one to have a single trigger (does not matter what the trigger is) and set the other two have two triggers (again, the actual triggers are irrelevant)
2. Create an inspec test to verify the tasks.  What you check does not matter, so a simple check for existing is sufficient)
3. Run the test.
4. Observe the following sad output:
![fail 1](https://user-images.githubusercontent.com/10499905/45552005-83c2f100-b7fd-11e8-96b4-3e180b991e1f.png)

5. Add a second trigger to the task that previously had only one.
6. Remove one trigger from the task that previously had multiple.
7. Re-run the inspect test, and notice that the failures switch like so:
![fail 2](https://user-images.githubusercontent.com/10499905/45552007-83c2f100-b7fd-11e8-9c14-dc04d04ca8df.png)

I've tested multiple tasks, triggers, actions, etc.  The only thing that seems to matter is that it will always fail if there is more than one trigger defined on the task.

### 💁 Possible Solutions

I have no brilliant suggestion at this time, sadly!

**Comment by jerryaldrichiii** [comment]
Interesting!

Thank you for such a well formatted issue. This seems like a bug to me, so I'll mark it as such.

**Comment by jerryaldrichiii** [comment]
Still a bug, and one that I saw while with a customer yesterday.

I'll assign myself and work on it when I can find time. No promises on a quick resolution though.
