### ISSUE TITLE
Global Attributes not visible in included controls?

### ISSUE THREAD

**Issue by Paladin** [inspec/inspec#3396]
### 🎛 Description

 🐛 bug report

The bug is either in the code or my understanding, cannot prove which, making this possibly a bug report on me, rather than the code.

### 🌍 InSpec and Platform Version

2.2.101

### 🤔 Replication Case

1) create two profiles, for the sake of this example, call them A and B
2) set an attribute in the inspec.yml of A
3) set a dependency in A for B
4) include_controls B in A
5) From B, attempt to read the attribute you set in A's inspec.yml

My understanding says it should be able to read it. My observation is that B gets whatever it sets as default for the call to read the attribute.

For simple example: If profile A's inspec.yml contains:

```
attributes:
  - host: 'fred'
```

and the included control from B pulls it with:

`target = attribute('host', default: 'sam')`

then the included control from B will have 'sam' in target, where my understanding of global attributes would indicate it should have 'fred', since there is nothing in B's inspec.yml that overrides it.

Am I misunderstanding it or is this a bug in global attributes?

**Comment by jquick** [comment]
The idea behind global attributes is that you can use the attributes in any control file for that profile. It is not expected that the yml attributes from profile A will override attributes on profile B. This would have unexpected overrides. If you would like to set attributes on the fly for both you will still want to use an `--attrs` file. 

Also your syntax for the yml attributes is invalid. Please see https://www.inspec.io/docs/reference/profiles/ section `Profile Attributes` for info.

**Comment by Paladin** [comment]
Apologies, when I did the copy/paste for those I used the wrong source file, didn't notice until you pointed it out. I should have caught that.

So the correct analog for "global attributes" in inspec are "module variables" in other systems rather than "global variables." OK, that helps; I get it now. Like I said, it was as likely to be a bug in my understanding as it was anything else. Might be useful in forestalling confusion among future new arrivals to avoid using the "global" descriptor because of the baggage it carries (calling them something like "profile attributes" instead) but it's probably too late to start doing that now.

Thank you for the clarification. But I see I wasn't clear about my expectations, as wrong as they were.

FWIW, the mechanism I was expecting wasn't that attributes from profile A would override those specified in profile B (I expected any attribute specified in B would still have have B's values, no matter where it was used). I was merely expecting attributes from profile A that were not specified in B to be inherited by B (and thus available to controls in B) when B was included in A.

Example::
- A includes B 
- A has attributes color->red and eyes->blue
- B has attribute eyes->brown

When running A, B's controls calling for attribute(color) would get red and for attribute(eyes) would get brown.

(And yes, that means I would expect B's controls, if B would be run as a standalone, would not see a defined attribute for color.)

**Comment by jquick** [comment]
Ah gotcha. Yes sorry for the confusion. We will try to document this better to remove any other misconceptions. Thank you for pointing this out! Closing this for now.

**Comment by aaronlippold** [comment]
Although they use case he describes would be something that would be very
useful if at all possible

**Comment by aaronlippold** [comment]
I actually expected it to work that way as well

**Comment by jquick** [comment]
You can override without `--attrs` if you really need by grabbing the attribute directly: https://github.com/inspec/inspec/blob/master/test/unit/mock/profiles/global_attributes/controls/attribute_inheritance.rb#L11 but we prefer the use of `--attrs`

**Comment by Paladin** [comment]
@aaronlippold My use case is still possible, using the --attrs option. The only "problem" I have with it is the UI doesn't feel as clean, which is hardly worrisome. It meant I needed to build what amounted to a library of profiles that didn't specify defaults for any of the attributes that I wanted them to inherit. So long as I never run them on their own, but only when included in one of the "higher-level" (for lack of a better term) profiles, it works. The itchy part of that is not being able to automatically associate a given attribute file with one of those profiles. That lack creates an opportunity for Murphy to strike.

**Comment by jquick** [comment]
@Paladin - We are going to implement name spacing in the `--attrs` file so you can do:

attr.yml
```
profile1.name = 'bob'
profile2.name = 'john'
name = 'james' # used for any other profiles
```

Which should help with any overlap and clarity.

**Comment by Paladin** [comment]
Actually, that doesn't help with my biggest problem with it. There's too much that needs to be remembered to be done manually. Now, if the attributes in the inspec.yml file could be the ones that were namespaced, *that* would help, since those attributes always come along with the profile. Failing that, having a local config file (I'll call it inspec.xml, just to differentiate it from the existing inspec.yml file) that would specify the default parameters inspec should apply when executing the profile from this location. *that* would be quite useful.

It would act like the same sort of files in other systems: the inspec executable would look for the file and if found add the parameters specified in it to the inspec exec command unless overridden on the command-line.

Example file contents:
<exec>
<target>ssh://user@example.com</target>
 <keyFile>path/to/key</keyFile>
</exec>

This would result in

 inspec exec

being run as:

inspec exec -t ssh://user@example.com -i path/to/key

That way I would never have to remember to attach things like the --attrs (or more importantly remember *which* attributes file I need to reference) to the command I'm typing, unless I'm wanting to this run different from the usual one. Think of it as a .ini file for the command. If no such file is provided, current behavior prevails, i. e., no defaults are set.

Yes, I'm lazy. ;{>}
