### ISSUE TITLE
`inspec shell` does not work when `--depends`ing on profiles that themselves have dependencies

### ISSUE THREAD

**Issue by greenantdotcom** [inspec/inspec#3411]
### 🎛 Description

🐛 bug report

`inspec shell` when used with `--depends=` on profile(s) that themselves have `depends` section defined in their `inspec.yml` file fail out with a stack trace. This complicates development of profiles that are composed of shared custom resources located in another folder.

### 🌍 InSpec and Platform Version

Confirmed in both…

`inspec` 2.2.102 / macOS 10.13.6
`ChefDK` 3.2.30-1 / `inspec` 2.2.70 / CentOS 7

### 🤔 Replication Case

Straightest path…

```bash
git clone https://github.com/inspec/inspec
cd inspec/examples/inheritance
inspec shell --depends=. # Fails with stack trace
inspec exec . # Works as expected
```

### 💁 Possible Solutions

Seemingly, the issue is that there a number of methods inside of `FileProvider` that expect a string but are receiving a symbol - I'm not sure if it's a symptom of something larger.

I intend to dig in further this evening to try to dig up more info, but wanted to get this filed in case someone had a eureka moment when reviewing it on how to get this fixed.

### 💻 Stacktrace

```
Traceback (most recent call last):
	23: from /usr/bin/inspec:292:in `<main>'
	22: from /usr/bin/inspec:292:in `load'
	21: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/bin/inspec:12:in `<top (required)>'
	20: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	19: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/cli.rb:225:in `shell_func'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/shell.rb:22:in `start'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/runner.rb:239:in `eval_with_virtual_profile'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/runner.rb:239:in `each'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/profile.rb:209:in `load_libraries'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/dependency_set.rb:64:in `each'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/dependency_set.rb:65:in `block in each'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/dependencies/requirement.rb:124:in `profile'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/profile.rb:72:in `for_fetcher'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/profile.rb:56:in `for_path'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:53:in `relative_provider'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:53:in `new'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:190:in `initialize'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:231:in `get_prefix'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:245:in `get_folder_prefix'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.2.70/lib/inspec/file_provider.rb:235:in `prefix_candidate_for': undefined method `end_with?' for :path:Symbol (NoMethodError)
```

**Comment by jerryaldrichiii** [comment]
I haven't done any work on this, so I'm going to unassign myself so expectations can be managed.

**Comment by ahelal** [comment]
i am experiencing this issue, the profile is local

**Comment by rmoles** [comment]
+1 Also seeing this issue when depending on a local copy of the `inspec-aws` resource pack in the profile inspec.yml

**Comment by samscottchef** [comment]
I am also having the issue described above

**Comment by Vasu1105** [comment]
Me and @Nik08 both tried reproducing this issue but were unable to reproduce.

What we have tried is we created Vagrant VMs using following configuration 

```
Vagrant.configure(2) do |config|
 config.vm.define "centos7" do |linux|
    linux.vm.box = "bento/centos-7"
    linux.vm.hostname = "testing.centos7"
    linux.vm.network "private_network", ip: "192.168.33.4"
    linux.ssh.insert_key = false
    linux.ssh.private_key_path = ["~/.ssh/id_ed25519", "~/.vagrant.d/insecure_private_key"]
    linux.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
 end

 config.vm.define "ubuntu20" do |linux|
    linux.vm.box = "bento/ubuntu-20.04"
    linux.vm.hostname = "testing.ubuntu20"
    linux.vm.network "private_network", ip: "192.168.33.5"
    linux.ssh.forward_agent = true
 end
end
```
we used ssh-add to add keys in the ssh-agent also we set the forward agent flag to true.
I have first ssh into the centos7 using `ssh -A vagrant@192.168.33.4`
then from there I ssh into the ubuntu20 using same `ssh -A vagrant@192.168.33.5`

Then I checked if keys are available on ubuntu20 using `ssh-add -l` and it listed all the keys.
Then I installed inspec on my Ubuntu vm and ran the inspec exec command to inspect the centos7 machine which ran successfully without giving any error.

We both are not able to reproduce this issue after trying several things.
So it must be a more environment / platform specific issue  or we are missing something in ssh forwarding? It will be great if we have details of the environment or exact steps to reproduce this issue.
