### ISSUE TITLE
Inspec skipping tests when file based resources do not exist

### ISSUE THREAD

**Issue by majormoses** [inspec/inspec#3412]
### 🎛 Description

We experienced an issue that was supposed to be caught by testing and was not because it was marked as skipped and skipped does not actually report as failures. This is a breaking change and would need to happen in the next major release.

### 🌍 InSpec and Platform Version

OS: Ubuntu 18.04

```
$ bundle info inspec
  * inspec (2.2.102)
    Summary: Infrastructure and compliance testing.
    Homepage: https://github.com/chef/inspec
    Path: /home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-2.2.102
```

### 🤔 Replication Case

```
inspec> describe json('/tmp/dummy') do
inspec>   it { should exist } 
inspec> end  

Profile: inspec-shell
Version: (not specified)

  JSON /tmp/dummy
     ↺  Can't find file: /tmp/dummy

Test Summary: 0 successful, 0 failures, 1 skipped
```

### 💁 Possible Solutions

https://github.com/inspec/inspec/blob/v2.2.111/lib/utils/file_reader.rb#L10-L12 I think this needs to change to something like this:
```
if !file.file?
  raise Inspec::Exceptions::ResourceFailed, "Can't find file: #{path}"
end
```

**Comment by clintoncwolfe** [comment]
Refs #3174

**Comment by clintoncwolfe** [comment]
I agree that "being unable to perform a test is more serious that a skip".  Not everyone agrees with that.  Please see #3174, and add your perspective there.

As a possible workaround for this situation, if you normally have no skips, you can examine inspec's exit status; if all tests passed with no skips, it will be 0; if some tests skipped but none failed, it will be 101.

Whether a skipped test should be treated as a failure is a matter of debate; see #2896 .

**Comment by jquick** [comment]
Closing this in favor of #3174

**Comment by majormoses** [comment]
> As a possible workaround for this situation, if you normally have no skips, you can examine inspec's exit status; if all tests passed with no skips, it will be 0; if some tests skipped but none failed, it will be 101.

Maybe I am not understanding what you mean by "usually". If skipped exited with a `101` it would have been mark it as failed in jenkins job, reported the status back to github, and branch protections would have prevented its merging. From my tests it always exits as `0` when its skipped.

There has not been much of a discussion on the issue but everyone who has chimed in agrees this is not desired behavior. What is the qualifier for moving forward on this? I'd hate to leave this open for a long time without being addressed simply waiting for a bunch of people that may or may not come along to speak their piece. This is a major problem with inspec and pretty much defeats the purpose of using it to verify service/application integrity if it will silently fail. Not all reasons a check can't be executed are the same but this is a very clear cut case.

**Comment by frezbo** [comment]
@majormoses this is in inspecv2 you are on old version. Coming back to the topic, we should fail a test if a file is not found, that's how compliance works. For people who wan it to be skipped we can introduce a new parameter to control that. That would satisfy both kind of users.

**Comment by majormoses** [comment]
> this is in inspecv2 you are on old version.

When I submitted it was the latest version pushed to rubygems can you elaborate what you mean?

**Comment by frezbo** [comment]
@majormoses used the `distinct_exit`  flag?

**Comment by aaronlippold** [comment]
Hi, what he means is in version one of inspec we only had exit status 1 and
0. In version two we added additional exit statuses.
https://github.com/inspec/inspec/issues/1825#issuecomment-382650911.

https://discourse.chef.io/t/inspec-2-0-release/12612

This is also documented in the inspect CLI although I think we could
document this more clearly and perhaps provide better usage examples when
integrating with jenkins CI / CD Pipelines Etc to make sure our own
internal assumptions are clearly communicated to the community.

@jquick and team had a lot of conversation about what we wanted to support
and what we are thinking about in version 3 but I think this is a great
example of making sure that when we put these kinds of things together that
we have very clear pointers to how we intended to use of these additions
for the community.

**Comment by majormoses** [comment]
From what I see [in the cli](https://github.com/inspec/inspec/blob/v2.2.112/lib/inspec/cli.rb#L223) it would be defaulting to using those distinct codes how can I validate that when `test-kitchen` runs it uses this?

**Comment by majormoses** [comment]
I have verified that I have a new enough version and added the option in my `.kitchen.yml` I see the same behavior:
```
# verify versions installed
$ bundle info kitchen-inspec
  * kitchen-inspec (0.23.1)
    Summary: A Test Kitchen Verifier for InSpec
    Homepage: http://github.com/chef/kitchen-inspec
    Path: /home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/kitchen-inspec-0.23.1

$ bundle info inspec
  * inspec (2.2.102)
    Summary: Infrastructure and compliance testing.
    Homepage: https://github.com/chef/inspec
    Path: /home/babrams/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-2.2.102

# kitchen config
$ grep -A 2 verifier .kitchen.yml 
verifier:
  name: inspec
  distinct_exit: true

# run the verifier
$ bundle exec kitchen verify
...
Test Summary: 136 successful, 0 failures, 1 skipped
       Finished verifying <default-ubuntu-1404> (0m5.70s).
-----> Kitchen is finished. (0m6.89s)

# it exits with a 0 not a 101
$ echo $?
0
```
