### ISSUE TITLE
Add group members as a property for the group resource

### ISSUE THREAD

**Issue by majormoses** [inspec/inspec#3422]
### 🎛 Description

 🙋 feature request

For the group resource I would like to test that a user is part of a group from looking at the docs it does not expose the list of members. I could spend some time looking into adding it but I will need help if its gonna support windows. For now I am testing with a block like this on linux:
```
inspec> describe command("awk -F':' '/docker/{print $4}' /etc/group") do
inspec>   its('stdout') { should match(/babrams/) }  
inspec> end  

Profile: inspec-shell
Version: (not specified)

  Command: `awk -F':' '/docker/{print $4}' /etc/group`
     ✔  stdout should match /babrams/

Test Summary: 1 successful, 0 failures, 0 skipped
```
We should be able to grab the list of members of the group and expose it as a property to be tested against. 

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version
Platform:
    Name:      ubuntu
    Families:  debian, linux, unix, os
    Release:   18.04
    Arch:      x86_64

Running versions (multiple projects with multile contexts):
- `2.2.102`
- `2.2.112`

### 💁 Possible Solutions

For linux we could look through `/etc/groups` like so:
```
# docker is just an example group
# and awk is just an example of how to parse we would do it in native ruby
awk -F':' '/docker/{print $4}' /etc/group
```
There may very well be a better option than this I just have not had enough time to look at it.

No idea on windows

**Comment by miah** [comment]
Hi @majormoses 

Thanks for reporting this, it looks like a documentation error that needs to be corrected. The `group` resource should support [querying members](https://github.com/inspec/inspec/blob/master/lib/resources/groups.rb#L120) already. I'm putting together a PR that updates the documentation and improves our tests around this feature.
