### ISSUE TITLE
Improve InSpec CLI UX

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#3426]
### 🎛 Description

At this point, we have some cli commands that are sometimes confusing, eg. 

- `inspec archive` and `inspec artifact` are essentially doing the same
- `inspec json` is exporting content from a profile as well as `inspec archive`
- `inspec init profile` has only one option `profile` which makes it very cumbersome to type

### 🌍 InSpec and Platform Version

InSpec 2.x

### 💁 Possible Solutions

InSpec's core commands (managed in inspec repo)

```
inspec init /path # instead of inspec init profile /path
inspec check /path # keeps identical
inspec export archive # existing inspec archive
inspec export archive —sign /path # existing inspec artifact
inspec export json /path # existing inspec json
inspec shell
inspec detect
inspec exec
inspec env
inspec vendor
inspec plugin
inspec version
```

InSpec Extensions (those should be in their own github repo):

```
inspec habitat 
inspec compliance
inspec supermarket
```

**Comment by arlimus** [comment]
Love the idea.
Also if we go with this it's a breaking change on the behavior of `init`. Everything else can be deprecated before removed.

**Comment by clintoncwolfe** [comment]
Overall, I think this is fantastic.

However, I disagree on `inspec init`.  It is useful, but not a frequently used command (does a user create new profiles everyday?), so I do not think `inspec init profile` is burdensome. Brevity should be proportional to frequency of use.

I like having `init` be our task-focused code generator, and making it only handle profiles cuts off opportunities.  There are many other things it could generate.  A plugin, for example (perhaps templatizing the plugin example).  Or `inspec init resource` could generate a skeleton for a new resource in a resource pack (the MITRE team created the beginnings of such a thing, for the AWS resources).

**Comment by chris-rock** [comment]
Do we have an example of the generator from Mitre? Would love to understand the use case better.

**Comment by aaronlippold** [comment]
https://github.com/rx294/inspec_aws_test_doc_generator

Is this what you're referring to?

Or are you looking for our set of parsers and converters?

just let me know what you're looking for and I will add everyone to
anything you need.

Aaron
