### ISSUE TITLE
Improve Integration Testing with Audit Cookbook

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3429]
### 🎛 Description

🐛 bug report

The InSpec project does not currently provide any testing ensuring that integration with the audit cookbook is working.

The audit cookbook is one of the main ways people consume inspec.  Lack of integration testing creates an undelightful experience for our largest community.

Refs #3373.

### 🌍 InSpec and Platform Version

2.2.100

**Comment by jquick** [comment]
The audit cookbook also directly requires some of our plugins. 
https://github.com/chef-cookbooks/audit/blob/master/files/default/handler/audit_report.rb#L122

Adding some travis tests to test audit cookbook and the export would be ideal.

**Comment by jquick** [comment]
This is done.
