### ISSUE TITLE
This and other instances of `ssl-benchmark` should be updated to `ssl-baseline` to reflect the new name

### ISSUE THREAD

**Issue by espoelstra** [inspec/inspec#3430]
While reading the docs I saw the reference to the benchmark and opened the repo to discover that GitHub did redirect, but it had a new name which might cause failures if people use the old name and it gets replaced in the future.

https://github.com/inspec/inspec/blob/d920f1d24a3eee9c02a7ad7c360d012e4f042dd7/docs/resources/ssl.md.erb#L85

**Comment by jquick** [comment]
Thanks for reporting this!
