### ISSUE TITLE
Required attribute error exit code

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#3440]
### 🎛 Description

This a 🐛 bug report

Given this inspec.yml content:
```
name: myattrs
title: InSpec Profile to test attributes
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.4.1
attributes:
  - name: level
    type: numeric
    default: 1
  - name: farm
    type: string
    required: true
```

When I execute the profile without specifying the required value for attribute `farm`, I get a failure, as expected.
```
$ echo '{"attributes":{"level": 5}, "reporters":["json-min"], "backend_cache":true}' | inspec exec ~/git/mycompliance-profile/myattrs --json-config=-
Attribute 'farm' is required and does not have a value.

$ echo $?
0
```
^ exit code, in this case, should be greater than zero.

same as we do here:
```
$ inspec exec ~/git/mycompliance-profile/mygcp -t gcp://
Profile 'mygcp' does not have an attribute with name 'gcp_project_id'

$ echo $?
1
```

### 🌍 InSpec and Platform Version

```
$ inspec version
2.2.116
```

**Comment by jerryaldrichiii** [comment]
Hmmm...very strange. We have a test for that:

https://github.com/inspec/inspec/blob/master/test/functional/attributes_test.rb#L53

Looks like it was added 13 days ago. Maybe update InSpec @alexpop?

**Comment by mnzone-dev** [comment]
Confirm working as expected with:
```
$ inspec version
2.2.118
```

**Comment by alexpop** [comment]
You are right Jerry, bug doesn't exist in master.
Thanks and sorry for the false alarm!
