### ISSUE TITLE
Add resource to test AWS auto scaling groups

### ISSUE THREAD

**Issue by metmajer** [inspec/inspec#3441]
### 🎛 Description

Feature request: add a resource to test AWS auto scaling groups. Thanks!

**Comment by amitsaha** [comment]
hey folks, I am going to take a stab at this.

**Comment by skpaterson** [comment]
`aws_auto_scaling_group(s)` have been added to the new InSpec AWS resource pack: https://github.com/inspec/inspec-aws/pull/9
