### ISSUE TITLE
control desc using two arguments errors

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec#3461]
### 🎛 Description

is this a 🐛 bug report 

If `desc` is using two arguments (desc: 'hello:','world') as given in the docs of the DSL (https://www.inspec.io/docs/reference/dsl_inspec/) an error is raised:
Error message:
```
  ×  default: test
     ×  Control Source Code Error ..../mycontrol.rb:5
     wrong number of arguments (given 2, expected 0..1)
```

### 🌍 InSpec and Platform Version

Using inspec 2.2.78, OS Linux x64

### 🤔 Replication Case

Create a control including `desc 'hello:' , 'world'.
```
control 'default' do
  title  'test'
  desc   'hello:', 'world'
```

### 💁 Possible Solutions

NA

### 💻 Stacktrace

NA

**Comment by jquick** [comment]
Hello @tbugfinder ! Thanks for reporting this. The multiple descriptions require InSpec 2.3.4. You can find the release notes here https://discourse.chef.io/t/inspec-v2-3-4-released

We will try to update our documentation to show which version is required for features.
