### ISSUE TITLE
inspec 3 controls being added for skipped dependent profiles

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#3486]
### 🎛 Description

**Choose one:** is this a 🐛 bug report

When using profile inheritance like here:

```ruby
include_controls 'myprofile1' do
  # skip this control
  skip_control 'pro1-con3'

  # fix this control from the profile we inherit
  control 'pro1-con2' do
    impact 0.888
  end
end
```

And profile `myprofile1` is skipped because of unsupported platform defined in inspec.yaml. 

`pro1-con2` control shows up in the report as:
```json
        {
          "id": "pro1-con2",
          "title": null,
          "desc": null,
          "descriptions": [],
          "impact": 0.888,
          "refs": [],
          "tags": {},
          "code": "  control 'pro1-con2' do\n    impact 0.888\n  end\n",
          "source_location": {
            "line": 21,
            "ref": "/Users/user/git/mycompliance-profile/myrapper-child/controls/defaut.rb"
          },
          "results": []
        }
```

Expected behaviour is not to include `pro1-con2` control since profile `myprofile1` is skipped.

### 🌍 InSpec and Platform Version

`2.3.7` via branch `inspec-3.0`

**Comment by zenspider** [comment]
Looks like this is fixed by #3487. Please reopen if otherwise.
