### ISSUE TITLE
Please add http support on Windows

### ISSUE THREAD

**Issue by michalmiddleton** [inspec/inspec#3496]
### 🎛 Description

 🙋 feature request

Is it possible to add Windows support for http resource? (https://www.inspec.io/docs/reference/resources/http/)

### 💁 Possible Solutions

I'd like to be able to run inspec on my windows VM locally as a part of our automation. 
Current workaround is to use Powershell script to do so..

**Comment by clintoncwolfe** [comment]
I agree 100%, and would like to see this fixed as well.  However, we do have an existing issue open that explores the problem in more detail, so I'm closing this as a duplicate.

Dupe: #2822
