### ISSUE TITLE
v3 - Plugin - Unknown error occured  - installation failed. 

### ISSUE THREAD

**Issue by burdena** [inspec/inspec#3521]
### 🎛 Description

**Choose one:** is this a 🐛 bug report 

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

### 🤔 Replication Case

Unable to install any plugins.

$inspec plugin install inspec-iggy
Unknown error occured  - installation failed

$inspec plugin install inspec-k8s
Unknown error occured  - installation failed.

 $inspec version
3.0.0

$uname -a
Darwin Adams-MBP 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by burdena** [comment]
MAC OSX 10.13.6 (17G65)

**Comment by burdena** [comment]
also tried via the docker image 

docker run -it --rm chef/inspec plugin install inspec-iggy
Unknown error occured  - installation failed.

docker run -it --rm chef/inspec version
3.0.0

**Comment by kmf** [comment]
Same here.

**Comment by jquick** [comment]
Sorry about this. We still have some unsupported plugins showing up as installable. `inspec-iggy` is being updated for plugins system. Once this is released https://github.com/inspec/inspec-iggy/pull/17 you should be able to install this plugin. `inspec-k8s` and `inspec-release` are actually just placeholders and are not real. They will be invalidated on tomorrows release to remove any confusion.

If you do want to test installing a plugin please use:
`inspec-resource-lister`

**Comment by burdena** [comment]
Cheers for the update, any idea when the new iggy release will happen ?

**Comment by jquick** [comment]
inspec iggy `0.4.0` was released last night and should work correctly for you:
```
$ inspec plugin install inspec-iggy
Fetching: inspec-iggy-0.4.0.gem (100%)
inspec-iggy plugin, version 0.4.0, installed from rubygems.org
```

**Comment by burdena** [comment]
I had to explicitly ask for 0.4.0 as only 0.2.0 was showing as availalbe.

$inspec plugin install inspec-iggy
Unknown error occured  - installation failed.

$ inspec plugin search inspec-

 Plugin Name                   Versions Available
-------------------------------------------------------
 inspec-iggy                   (0.2.0)
 inspec-k8s                    (0.0.0)
 inspec-release                (0.0.0)
 inspec-resource-lister        (0.1.0)
-------------------------------------------------------
 4 plugin(s) found

$ inspec plugin install -v 0.4.0 inspec-iggy
Fetching: inspec-iggy-0.4.0.gem (100%)
inspec-iggy plugin, version 0.4.0, installed from rubygems.org

$ inspec plugin list

 Plugin Name                   Version   Via     ApiVer
-------------------------------------------------------
 inspec-iggy                   0.4.0     gem     2
-------------------------------------------------------
 1 plugin(s) total

**Comment by burdena** [comment]
via docker worked fine

$ docker run -it --rm chef/inspec plugin install inspec-iggy
Fetching: inspec-iggy-0.4.0.gem (100%)
inspec-iggy plugin, version 0.4.0, installed from rubygems.org

**Comment by burdena** [comment]
@jquick thanks for the quick fix and keeping me informed.
