### ISSUE TITLE
Support image LABELs in docker_image

### ISSUE THREAD

**Issue by damacus** [inspec/inspec#3524]
### 🎛 Description

 🙋 feature request?

With docker inspect you can get a list of LABELs easily, but the docker_image resource does not support this. 

### 🌍 InSpec and Platform Version

v3.0.0

### 💁 Possible Solutions

💁 some sort of docker inspect feed into the resource.

**Comment by megamorf** [comment]
This is actually possible with `32cdcd3d6093` being your image id (source: https://github.com/inspec/inspec/blob/7313eb781937e459cdf88a9d5064723132bc5c38/lib/resources/docker.rb):

```ruby
describe docker.object('32cdcd3d6093') do
    its('ContainerConfig.Labels.GIT_TAG') { should cmp >= 'v1.2.0' }
end
```

To see all properties, open `inspec shell` and specify your image id `docker.object('32cdcd3d6093')`. E.g.
```
inspec> docker.object('32cdcd3d6093').ContainerConfig.Labels
=> {"BUILD_TIME"=>"2018-10-24T14:30:10Z",
 "GIT_BRANCH"=>"feature/generic-docker-conversion",
 "GIT_COMMIT"=>"29fb6077a394e08d37415c79697ffc23a31f71c2",
 "GIT_TAG"=>"v1.2.0",
 "maintainer"=>"DevOps Team <devops@example.org>",
 "org.opencontainers.image.created"=>"2018-10-24T14:30:10Z",
 "org.opencontainers.image.description"=>"Example customer middleware",
 "org.opencontainers.image.revision"=>"29fb6077a394e08d37415c79697ffc23a31f71c2",
 "org.opencontainers.image.title"=>"Super Awesome Customer Service (SACS)",
 "org.opencontainers.image.vendor"=>"Example Corp",
 "org.opencontainers.image.version"=>"v1.2.0"}
```
