### ISSUE TITLE
Sharing custom resources?

### ISSUE THREAD

**Issue by arothian** [inspec/inspec#353]
I see that you can add your custom resources to a libraries folder within a profile, but is there a way to include custom resources provided by another gem? It seems like you should be able to build up a library of custom resources, publish as a gem, and then include in a variety of inspec situations.

**Comment by chris-rock** [comment]
@arothian At this moment, InSpec does not support this addition of global resource from outside of the InSpec gem. We are thinking about an extension system. Could you share your use case?

**Comment by arothian** [comment]
@chris-rock thanks for the reply. I realize this is outside the original design/use for inspec, but I'd like to be able to develop resources that interact with AWS infrastructure to do some validation/testing. For example, it would be nice to be able to write controls that target AWS resources such as security groups, IAM roles/policies, VPC routing, etc. These inspec resources would just run with the local executor and interact with the AWS sdk. It would be nice to package these as a 'inspec-aws-resources' gem, since I doubt everyone would find them useful.

I'm thinking that from a testing and audit perspective, some of these resources are just as important as a vm/container.

**Comment by arothian** [comment]
@chris-rock So I dug into the code a little but and discovered a working method. If you define a file in your libraries folder of a profile, you can use `require 'yourresourcesgem'` to load a gem that just has other inspec resources. This seems to work just fine. Not sure if you want to close this out or document the 'feature'.

**Comment by chris-rock** [comment]
@arothian Thanks for sharing the use-case. We are currently thinking about a proper plugin system, that would support your use case. One core design goal is to make make profiles portable. 

Your approach is great, but requires the gem to be available on the running machine beforehand, which may leads to problems. Therefore we cannot support your solution officially yet.

I mark your issue as a feature request. Would love to see your inspec resources!

**Comment by chris-rock** [comment]
The only official solution that we offer at this moment is via InSpec profiles: https://github.com/chef/inspec/blob/master/docs/profiles.rst 

Therefore you can write your own resources as part of InSpec profiles

**Comment by arothian** [comment]
@chris-rock This is very much still a work in progress, but some of my initial resources are up at https://github.com/arothian/inspec-aws

**Comment by chris-rock** [comment]
@arothian that looks really good. we work on a solution that will integrate much better. Stay tuned.

**Comment by pburkholder** [comment]
@chris-rock Any update here on how to do tests against the platform, or how to cleanly include something like `inspec-aws`?

**Comment by arlimus** [comment]
@pburkholder I've been hammering on this (parts of which are referenced here https://github.com/chef/inspec/issues/798 as well) for the last couple of weeks for every free minute I found :smile: Getting very close now. Essentially it is dependency resolution and the last major feature for inspec 1.0 (apart from fixes and enhancements).

**Comment by ringods** [comment]
A few months have passed again and this ticket is still open. Does inspec have support to share custom resources?

**Comment by arlimus** [comment]
Sorry for the late response on this. Custom resources are now supported with the InSpec inheritance mechanism. A full guide is here: http://inspec.io/docs/reference/dsl_resource/

I believe there is still a number of improvements we have to make (e.g. calling custom resources for inspec shell). The basics should now work. Please open issues if this is still blocking you!
