### ISSUE TITLE
aws_ecs_cluster documentation

### ISSUE THREAD

**Issue by krystan** [inspec/inspec#3534]
###  Description

This a RFE (documentation) 

The issue is that ecs_cluster is not documented on the website although exists in code on master.

### InSpec and Platform Version

N/A

### Replication Case
N/A

### Possible Solutions

Documentation needs adding.

### 💻 Stacktrace

N/A

**Comment by clintoncwolfe** [comment]
You are correct, it is missing both docs and integration tests; I'm not sure why #3213 was accepted without them.

**Comment by skpaterson** [comment]
These have been added in the new InSpec AWS resource pack e.g. 
https://github.com/inspec/inspec-aws/blob/master/docs/resources/aws_ecs_cluster.md
