### ISSUE TITLE
`inspec compliance login` command gives 'fake' feedback

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#3535]
### 🎛 Description
When using the `inspec compliance cli` plugin, the login information will take all the info you give it and simply store it locally for later use.
This means that if a user inputs a bad token for the command, we will respond with a "configuration stored" message, and then the user, not knowing that the token/login was never validated, thinks something has gone wildly wrong when they try to run `inspec compliance profiles` and receive an unauthorized message.
Maybe the login command could call the automate api to ensure the token is valid?
This would surface the error earlier in the process, and (imo) clear up some confusion.

### 🤔 Replication Case

run the `inspec compliance login` command with a bad token.
try to list profiles, see error.

**Comment by clintoncwolfe** [comment]
Refs #2881

**Comment by vjeffrey** [comment]
dearest stale-bot, I believe we should still do the likely small amount of work that is required to ensure a great ux!

**Comment by clintoncwolfe** [comment]
So, we should make an API call to verify the user's credentials and the reachability of the A2 server. What API call should that be?

One simple option would be to query the [server version](https://github.com/inspec/inspec/blob/b1fc46e883904b2a847c40e1d0ed9f963e315687/lib/plugins/inspec-compliance/lib/inspec-compliance/api.rb#L97), though it looks like our code for the A2 API path is wrong (if such a path exists).

**Comment by vjeffrey** [comment]
```
➜ curl --insecure -H "api-token: good-value" https://a2-local-inplace-upgrade-dev.cd.chef.co/api/v0/version
{"build_timestamp":"20191104205453"}

curl --insecure -H "api-token: bad-value" https://a2-local-inplace-upgrade-dev.cd.chef.co/api/v0/version
{"error":"request not authenticated","message":"request not authenticated","code":16,"details":[]}
```
