### ISSUE TITLE
inspec version  still shows older version 

### ISSUE THREAD

**Issue by pawasthi07** [inspec/inspec#3540]
### 🎛 Description

**Choose one:** is this a 🐛 bug report 

Inspec version does not show the installed version

[root@fvthyd01 ~]# gem install inspec
Fetching: inspec-3.0.9.gem (100%) ----------------->>> InSpec 3.0 got installed
**Successfully installed inspec-3.0.9**
1 gem installed

[root@fvthyd01 ~]# inspec version------------------------->> Still showing older version
1.45.13
Your version of InSpec is out of date! The latest version is 3.0.9.

[root@fvthyd01 ~]# ruby --version
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
[root@fvthyd01 ~]#

[root@fvthyd01 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@fvthyd01 ~]#

**Comment by frezbo** [comment]
@pawasthi07 you must have a previous installation of inspec either as part of inspec rpm installation or chefdk installation. See the inspec path with `which inspec`, It will be using something in `/opt` rather than the local gems

**Comment by pawasthi07** [comment]
Yes I have Chef server , chek workstation installed on the  same server where I have installed InSpec , however rpm -aq | grep inspec does not show any installed packages.
Cant we install InSpec on a server running chefdk.

**Comment by jquick** [comment]
ChefDK includes InSpec. Standalone InSpec and ChefDK will need some bin direction as they will both want to use the same executable. A new ChefDK should be released soon which includes InSpec 3.0. That or you can modify your inspec executable to point to your gem version instead.

**Comment by miah** [comment]
Try `which inspec` from the command line and you'll see where the inspec being executed is installed.

You can then modify your shell environment $PATH to put your gem installed inspec before the other.

```
miah@anorak ~:$ which inspec
/usr/local/bin/inspec

miah@anorak ~:$ echo $PATH
/usr/local/bin:/Users/miah/.gem/ruby/2.5.1/bin:/sbin:/bin

miah@anorak ~:$ PATH=/Users/miah/.gem/ruby/2.5.1/bin:/usr/local/bin:/sbin:/bin

miah@anorak ~:$ which inspec
/Users/miah/.gem/ruby/2.5.1/bin/inspec
```

**Comment by clintoncwolfe** [comment]
It looks like  your question has been answered to your satisfaction.  I'm going to close this, but feel free to re-open it if you have more to discuss on this topic.
