### ISSUE TITLE
apache_conf resource cannot verify env used in config

### ISSUE THREAD

**Issue by darkn3rd** [inspec/inspec#3545]
### 🎛 Description 🐛

On Ubuntu 16.04, apache2 service is run with envvars set in `/etc/apache2/envvars`, where it does, for example:

```
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
```

InSpec cannot verify the behavior, as it only compares the static string.

### 🌍 InSpec and Platform Version

```2.2.70```

### 🤔 Replication Case

And simple InSpec script:

```ruby
control 'ez_apache-security-06' do
  impact 1.0
  title 'User and group should be set properly'
  desc 'For security reasons it is recommended to run Apache in its own non-privileged account.'
  describe apache_conf do
    its('User') { should eq [apache.user] }
    its('Group') { should eq [apache.user] }
  end
end
```

### Actual Results

```
Target:  ssh://kitchen@localhost:32769

  ×  ez_apache-security-06: User and group should be set properly (2 failed)
     ×  Apache Config /etc/apache2/apache2.conf User should eq ["www-data"]

     expected: ["www-data"]
          got: ["${APACHE_RUN_USER}"]

     (compared using ==)

     ×  Apache Config /etc/apache2/apache2.conf Group should eq ["www-data"]

     expected: ["www-data"]
          got: ["${APACHE_RUN_GROUP}"]

     (compared using ==)
```

### Expected Results

If I was doing a manual string compare with a file, that is fine, but with apache_conf resource, I expected that there would be more resource to verify the setting, as Apache2 supports this mechanism.  

### 💁 Possible Solutions

* support resolving env vars if used in configuration
* look in /proc dir to get runtime environment to compare against the configuration

**Comment by clintoncwolfe** [comment]
We discussed this issue internally, and our general consensus went something like this: 

* We can't be in the business of providing the same evaluation semantics as Apache.  We already do so to a very limited degree in pulling in IncludeDirs, etc.
* Your idea of examining /proc is interesting, but introduces some issues: proc is Linux-specific; typically requires sudo; and assumes that you have one (and only one) main apache process running.  All of that gets to be very site-specific.

I think there is value in have the uninterpolated values.

```
×  Apache Config /etc/apache2/apache2.conf Group should eq ["www-data"]

     expected: ["www-data"]
          got: ["${APACHE_RUN_GROUP}"]
```

What if you changed your approach, and wrote your test to expect (literally) "${APACHE_RUN_GROUP}" ? That would show that you expect your apache config to be driven by certain environment variables - an auditable fact that is specific to you and your setup, which you can bake into your profile.

Next, you naturally want to audit the value of those environment variables.  InSpec has no idea how you're setting that up, but you do.  You could source a shell file that sets runtime values, then check output: 

```
describe command('source runtime-env.sh && env') do
  its(stdout) { should include "APACHE_RUN_GROUP=www-data" }
  its(stdout) { should include ... }
end
```

Or perhaps you do prefer to get them from /proc, or from a hypervisor.  However you do it, you could write inspec checks to find the environment variable values, and audit them.

I hope that helps.  Thanks!

**Comment by clintoncwolfe** [comment]
Hi! We've given an approach to this question, and there hasn't been any activity in a few days.  I'm going to close this, but if you would like to discuss further, please feel free to re-open.
