### ISSUE TITLE
inspec check warns if desc is missing but description present for a control

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3550]
### 🎛 Description

🐛 bug report

#3424 added the ability to use the DSL word `description` to add a description with an optional label to controls; the keyword may be repeated.

When used with a single argument, the intent was for the description to be used as the 'default' or main description of the control, replacing `desc`.  `desc` was retained for backwards compatibility.

However, a control file with a call to `description` (and no `desc`) triggers a warning in `inspec check`.

### 🌍 InSpec and Platform Version

3.0.14

### 🤔 Replication Case

Control file:
```
control 'desc-01' do
  impact 1
  title 'desc-01-title-one'
  description 'some words'
  describe true do
    it { should eq true }
  end
end
```

InSpec check output:
```
[cwolfe@lodi inspec-cli]$ be inspec check test/unit/mock/profiles/dupe-controls
Location:    test/unit/mock/profiles/dupe-controls
Profile:     dupe-controls
Controls:    1
Timestamp:   2018-10-29T17:27:25-04:00
Valid:       true

  !  test/unit/mock/profiles/dupe-controls/controls/desc.rb:1: Control desc-01 has no descriptions

Summary:     0 errors, 1 warnings
```

**Comment by clintoncwolfe** [comment]
Hey genius, the keyword is `desc`, `description` isn't a thing.

**Comment by mikelindsey-okta** [comment]
Hey snarky author.  The output says description, it does not mention the key, nor does it come up cleanly in docs or google searches.

What does come up eventually is you opening a bug about it and then closing it without resolving it.

There's a real user-experience fail here.
