### ISSUE TITLE
Add support for `inspec exec` and private Git repos (GitHub or GitLab)

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3555]
### 🎛 Description

🙋 feature request

Currently there is no method to use `inspec exec` and a private GitHub repo. Below are some examples that I think should work but do not:

#### Via SSH (`git@github.com`)

```
inspec exec git@github.com:chef/private-testing-profile.git
```

Fails with:
```
Could not fetch inspec profile in "git@github.com:chef/private-testing-profile.git"
```
This fails since `target` is passes as a String and no fetcher knows how to handle it. I think the Git fetcher should parse this string and do a Git clone.

#### Via `username:password` and HTTPS

```
PASSWORD=hunter2 inspec exec https://jerryaldrichiii:$PASSWORD@github.com/chef/private-testing-profile.git
```

Fails with:

```
userinfo not supported.  [RFC3986]
```

> I think we should also prompt for password if only username is given, but I'll open that for discussion.

#### Via [git-credential-cache](https://git-scm.com/docs/git-credential-cache)

```
git config credential.helper cache
git ls-remote https://jerryaldrichiii@github.com/chef/private-testing-profile
# Auth happens here
inspec exec https://github.com/chef/private-testing-profile
```

Fails with:

```
[2018-10-30T11:19:40-07:00] WARN: URL target https://github.com/chef/private-testing-profile.git transformed to https://github.com/chef/private-testing-profile/archive/master.tar.gz. Consider using the git fetcher
OpenURI::HTTPError: 404 Not Found
```

### 💁 Possible Solutions

I think leveraging the Git fetcher when URLs do not end with `.tar.gz`/`.zip` or when they end with `.git` might be the solution. That will allow all but the username only method to work out of the box (since it uses `git clone`). The username only method does not prompt for a password when ran via InSpec so we will need to capture it somehow.

> Example below requires you to change the Git fetcher to use the `target` as a String and not just a Hash

Example:

```
inspec exec https://jerryaldrichiii@github.com/chef/private-testing-profile.git
```

Fails with:

```
Error running 'git ls-remote "https://jerryaldrichiii@github.com/chef/private-testing-profile.git" "master*"': fatal: could not read Password for 'https://jerryaldrichiii@github.com': No such device or address
```

**Comment by aaronlippold** [comment]
Something to consider is that can and what do we need to pull from kitchen-inspec or kitchen, as, if we use `kitchen-inspec` and have private repos in the depends or in the `inspec_tests` - when I run my kitchen commands, I don't run into issues - kitchen seems to 'take care of it for me' if I for example - have my local git client setup with Private Access Tokens or ssh private keys etc.  Not sure if this is a 'kitchen' proper effect of how they handle things or if it is something in the 'kitchen-inspec' handling of git locally.

**Comment by jerryaldrichiii** [comment]
Yup, basically the Git fetcher expects an array (which is passed when using `inspec.yml`/`kitchen.yml`) but when running `inspec exec` a String is passed. The Git fetcher uses `git clone` which handles all of the ssh things.

See: https://github.com/inspec/inspec/blob/master/lib/fetchers/git.rb#L32

**Comment by chris-rock** [comment]
You cannot just use basic authentication with github, you would need to use your token as the username as described here https://developer.github.com/v3/auth/

**Comment by clintoncwolfe** [comment]
I think there are two issues mixed together, here.

1. Distinguishing between a non-git HTTP-based fetch of a tarball/zipfile profile, and git-based fetches from the command line (git may be git+ssh, git+token, git+basic http auth, or git+no-auth).  We may have to rely on heuristics for that, but that's OK - the fetchers already rely on heuristics to volunteer to handle a profile location (AKA "target").

2. Adding a feature that supports HTTP Authentication to HTTP URL fetches, be they tarball or git.  In github's case, that means passing a token as the username and omitting the password.  In other cases, basic auth, or something involving custom headers, may be needed.

For 1, that's a new feature - we don't claim to support git repos on the command line now, as far as I know. I do think it would be useful.

For 2, if someone were to try to fetch a tarball from a URL that required basic auth, and they embedded username and password in the URL, that "should" work. If you want to specifically test github, as @chris-rock mentioned, you'd just need to use the auth token as the username.  Both of those require no changes.  If we wanted to expose a mechanism by which a user could inject a custom request header....  well, I guess we could, but that seems painful.

**Comment by jquick** [comment]
Lets do the following:
1) Add `git@` to the profile path checks to force the git fetcher
2) Add documentation for `git@` and `https://token@github` and how to use them
3) Add documentation for fetching a `.zip` file over http(s)

**Comment by jerryaldrichiii** [comment]
Can do! Thank you @clintoncwolfe @chris-rock @jquick I verified the following works:

```
inspec exec https://MY_TOKEN@github.com/chef/private-testing-profile
```

**Comment by aaronlippold** [comment]
Very cool guys, thanks. @jquick and @clintoncwolfe have the right path I think, for the interim I will test ensure the above works on the hosted github private repo side as well as the private hosted gitlab side.

**Comment by jerryaldrichiii** [comment]
@aaronlippold @jquick @clintoncwolfe @chris-rock I was wrong...`token@github` also fails with userinfo not supported on master....I had it short circuited on my branch.

I'll add support for `git@`.

Should we also force the Git fetcher when using `https://` and ending in `.git`? I don't think forcing on `.tar.gz`/`.zip` is valid because someone may be doing HTTPS without Git.

EDIT:

More digging, the `userinfo not supported` error is coming from `open-uri` according to [this](http://usefulstuff.io/2013/04/open-uri-and-basic-authentication/).

I'll dig into how we can set https://github.com/inspec/inspec/blob/master/lib/fetchers/url.rb#L228 via URI parsing which "should" fix the HTTPS issues since GitHub supports basic auth.

**Comment by aaronlippold** [comment]
I would think that is logical given that they are giving you a direct uri
to a repo
