### ISSUE TITLE
Document ability for SELinux Role for Production Use

### ISSUE THREAD

**Issue by fcaviggia** [inspec/inspec#3566]
Document ability for SELinux Role for Production Use

**Choose one:**  🙋 feature request.

Document ability to assume a role for SELinux roles - generally done with the '-r' option to sudo. This might be useful in testing systems that require not only elevated privilege, but a specific role to be assumed by the user.

@aaronlippold 
@trevor-vaughan 

### 🌍 InSpec Linux ALL

**Comment by clintoncwolfe** [comment]
Could you elaborate on your intended meaning of "production use"?

**Comment by fcaviggia** [comment]
The term "Production Use" use was Aaron's wording. Basically, for users that implement Role-Based Access Control using SELinux. It can create a situation where root privileges are divided up with several users to manage a system.  Particularly, for Cross Domain Solutions.

**Comment by clintoncwolfe** [comment]
OK, that is pretty site-specific.  Generally speaking, I think you're asking for support for SELinux support to be added to the sudo options for `inspec exec`.  Is that correct?

The issue also mentions 'documenting' the feature, not implementing it.  Do you believe this capability is already present, and if so, could you provide an example?

**Comment by clintoncwolfe** [comment]
It appears that we already support passing extra arguments to sudo, using the [--sudo-options](https://www.inspec.io/docs/reference/cli/#exec) option to `inspec exec`.  

As there are many things one could conceivably pass there, I don't think it makes sense to add usage docs mentioning se_linux specifically.

I do think an example of using this might make a great blog post.

**Comment by trevor-vaughan** [comment]
@clintoncwolfe This is required for STIG control V-71971 https://github.com/simp/inspec-profile-disa_stig-el7/blob/master/controls/V-71971.rb

**Comment by clintoncwolfe** [comment]
Please pardon my density on this, but I'm not clear on how an InSpec CLI option to change sudo behavior (which is already supported) is needed for a profile attempting to assert V-71971.  

What change to the InSpec features, codebase, or documentation is being requested here?

**Comment by trevor-vaughan** [comment]
I think it was just to allow for a commonly used option to be passed natively.

I'm OK with it not being done and just using the `--sudo-options` flag but this should help provide a 'reasonable customer usage' scope around the issue.

**Comment by clintoncwolfe** [comment]
Refs #534

**Comment by clintoncwolfe** [comment]
OK. Based on my understanding of what is being asked for - a CLI flag to specifically enable SElinux roles via sudo - I'm going to go ahead and close this, as it can be done via the `--sudo-options` flag. I do think it's a good use case, and should be showcased, perhaps on #3601.
