### ISSUE TITLE
Clarify `impact` of controls

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#358]
At the moment `impact` is defined as a number from 0 - 1. A couple of things have come up that should be solved (either by implementing, rejecting, or pushing them):
- [x] ~Define impact via names, e.g. `impact critical`.~ This will become a separate RFC!
- [x] Define what impact terms are associated with impact ranges, e.g. 0 - 0.3 minor, 0.3 - 0.7 major, 0.7 - 1.0 critical ==> this is now documented in https://github.com/chef/inspec/pull/1713

**Comment by AnotherNerdHere** [comment]
I would also like to see documentation regarding where this is used. currently If I set a impact 1.0 or 0.1 is doesn't appear to have any effect.

**Comment by arlimus** [comment]
Thank you for pointing to the missing docs, I have added a PR for that. As soon as they are in I'm closing this issue. We will create a separate RFC for the new impact or severity field (or it may not be a breaking change ;) ).

**Comment by chris-rock** [comment]
Besides the documentation, `inspec check` will also return warning for the misuse.
