### ISSUE TITLE
Modify Thor (or alternative) to allow `inspec exec -h`

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3581]
### 🎛 Description

Running `inspec exec -h` produces the following error:

```
Could not fetch inspec profile in "-h".
```

I believe this is coming from Thor and thinking `-h` is an argument to exec. A workaround is to use `inspec help exec` but I don't think that is intuitive. It also is not consistent with the rest of Chef products.

**Comment by clintoncwolfe** [comment]
Thanks for the report! This was fixed on #3553 and released on v3.0.25.
