### ISSUE TITLE
`inspec check` should warn if Inspec  doesn't fit version dependency

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3585]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

It would be helpful for `inspec check` to consider it an error if the profile being checked is not supported by the version of Inspec running the check.

Currently (e.g. with our CIS AWS profile), the profile passes check but fails to exec:

```
➜ ✗ inspec check cis-aws-foundations-level1-1.1.0-2.tar.gz
Location:    cis-aws-foundations-level1-1.1.0-2.tar.gz
Profile:     cis-aws-foundations-level1
Controls:    40
Timestamp:   2018-11-07T13:49:41+00:00
Valid:       true

  !  controls/01-iam.rb:307: Control 1.24 has no tests defined
  !  controls/02-logs.rb:32: Control 2.3 has no tests defined
  !  controls/02-logs.rb:83: Control 2.6 has no tests defined
  !  controls/03-monitoring.rb:43: Control 3.1 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.2 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.3 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.4 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.5 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.6 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.8 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.12 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.13 has no descriptions
  !  controls/03-monitoring.rb:43: Control 3.14 has no descriptions
  !  controls/04-networking.rb:5: Control 4.1 has no tests defined
  !  controls/04-networking.rb:18: Control 4.2 has no tests defined

Summary:     0 errors, 15 warnings
➜ ✗ inspec exec cis-aws-foundations-level1-1.1.0-2.tar.gz
This profile requires InSpec version >= 2.1.48, ~> 2.1. You are running InSpec v3.0.25.
```

### 🌍 InSpec and Platform Version

3.0.25 gem

### 🤔 Replication Case

When using Inspec 3.0.25 

inspec.yml:

```
---
name: my-profile
title: My Profile
maintainer: Chef Software, Inc.
copyright: Chef Software, Inc.
copyright_email: support@chef.io
version: 1.0.0
inspec_version:
- "~> 2.1"
- ">= 2.1.48"
```

**Comment by james-stocks** [comment]
I can do this myself but would like a +1 on it being a valid improvement - or is there any case where being able to check with unsupported Inspec versions is desirable?

**Comment by clintoncwolfe** [comment]
I think we need @arlimus or @chris-rock to weigh in.  To me, the main concern is that we have Automate and Compliance acting as gates (they run `check` on profiles as they are uploaded, using the version of inspec included with Automate/Compliance).  Subsequently, a user might run a different version of inspec, fetching the profile from the compliance / automate server.

Currently, the lack of version checking decouples that relationship; if we start version checking on upload, then that might help in some cases, and hurt in others.

Refs #3549 - named check rules

**Comment by chris-rock** [comment]
As a user I may need to support older environments and it would be a pitty if they could not store the profile in the profile store just because we deny upload profiles (profiles are denied uploading if they have errors). Therefore I see cases where we want to upload a profile that Chef Automate itself cannot execute but older versions of InSpec can.

Issuing a warning that the latest version is not supported by the profile is great because it encourages users to support the latest version of InSpec.

Would that work for you @james-stocks

**Comment by james-stocks** [comment]
That is a very good reason to not error; a warning would be useful if we eventually had https://github.com/inspec/inspec/issues/3549 to configure what warnings are significant for our usage.

I'll raise a PR to add a warning for this case when I find time

**Comment by james-stocks** [comment]
I've come across this again when checking a profile that needs InSpec 4 with InSpec 3.
The check fails because gems present only in InSpec 4 are missing.
Ideally the check should look at the required InSpec version and exit immediately. A custom exit code would be nice so that CI can support this as being an acceptable case.

**Comment by clintoncwolfe** [comment]
refs #3549
