### ISSUE TITLE
apache resource deprecation in Inspec 2 is no longer true

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3587]
While using the dev-sec/apache-baseline profile with Inspec 2.1 I noticed the following warning that was concerning since Inspec 3 is now released:

`[DEPRECATED] The `apache` resource is deprecated and will be removed in InSpec 3.0.`

For the 3.0 release, the deprecation [got bumped forward to 4.0](https://github.com/inspec/inspec/commit/2bbcdbde9b3d6008afc93e581d2a69338af90c8f#diff-6721b1d2c61c88d618404a6bc2cc574eR29)

It would be ideal to backport this deprecation warning to Inspec 2 so people know their profiles are OK until Inspec 4.

**Comment by zenspider** [comment]
Stale. Closing.
