### ISSUE TITLE
version pinning in profiles is a little looser than expected

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#3590]
### 🎛 Description
I have a profile with a version restriction:
```
inspec_version:
- "~> 2.1"
- ">= 2.1.48"
```
Presumably, this profile will not be executed on a system running InSpec version 2.2.x or 2.3.x.

But I'm running InSpec 2.3.5, and it is executing the profile.
Switching to InSpec 3+ gives me the unsupported msg, as expected.

**Comment by jerryaldrichiii** [comment]
I believe this is expected. The `~>` pinning means that the last digit is the significant one. So to get any `2.1.X` you would need to specify `~> 2.1.0` otherwise any `2.X` will be allowed.

The second one just means any version greater or equal to `2.1.48`.
