### ISSUE TITLE
inspec check failed - undefined method 'split' false/positive

### ISSUE THREAD

**Issue by mhackethal** [inspec/inspec#3593]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

This is a :bug: ( i think ) 
Any ideas or help is really welcome !

inspec check detect the following statement in an .rb file as error:

```
host = fqdn.split('.')[0]
entity = entity.gsub('E','Entity')
dc = ''
domain.split('.').each do |dn|
	dc << ",DC="+dn
end
```
I use 'inspec check' as pre-check for my gitlab-runner to deploy my profiles so currently this issues causes that i am not able to deploy the profile.

### 🌍 InSpec and Platform Version

InSpec 2.2.78 on Windows 2016 

### 🤔 Replication Case

During verification of an profile with inspec check .\ i get the following result:

```
AD_CHECK> inspec check .\
./controls/ad-cc.rb:7:in `load_with_context': undefined method `split' for false:FalseClass (NoMethodError)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.2.78/lib/inspec/profile_context.rb:158:in `instance_eval'
```

if i execute the same profile it works as expected:

```
AD_CHECK> inspec exec .\ --attrs attr.yml

Profile: InSpec Profile (AD_CHECK)
Version: 0.1.0
Target:  local://

  [PASS]  Active Directory Target OU Status: Verify the target OU for the server
     [PASS]  Verify AD Object is enabled should eq true
     [PASS]  Verify object is following AD Content Concept should eq true
     [PASS]  Current distingushed name should eq "CN=foo,OU=bar,DC=xxx"


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 3 successful, 0 failures, 0 skipped

```

### 💁 Possible Solutions

Currently i have no idea how to solve this 😭 

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by jquick** [comment]
Thanks @mhackethal, looks like fdqn is not defined during the check run.

**Comment by mhackethal** [comment]
@jquick 
Hi Jarod, Thanks yes youre totally right. I predefined the vars with value false. which leads
to the error that 'split' cannot work. I am sorry for opening a bug request.
I am sorry for beeing blind.
