### ISSUE TITLE
Replace 'Control' object's code block as text

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#3596]
### 🎛 Description

🙋 feature request?

I would like the ability to add a full text block - i.e. the `code{ }` section of the json data to an inspec object. At the moment I can add single tests to the control but if I had the tests in a text block I would like to be able to add that to the control object directly.

@rachelrice what do you think?

**Comment by aaronlippold** [comment]
Use case: 

I want to parse the json data of a profile and perhaps add or update elements in the profile and need a direct way to repopulate the describe blocks.

**Comment by clintoncwolfe** [comment]
When you say "text block", I think you mean a multi-line String, that you could use to assign in one operation the entire innards of the Control. Is that correct?

InSpec does not currently do any source code parsing (it simply evaluates profile code when running), so the text block would be opaque.  You would not be able to assign the code as a String, then adjust one or more properties (such as impact, or title, etc.)  If, as you describe, you were reading in an exported profile, you would need to do the parsing yourself, injecting what you want, then you could use this feature to replace the internals.

Without source code parsing, is the feature still useful to you?

**Comment by zenspider** [comment]
No response. Closing.
