### ISSUE TITLE
Add `only_if` inside describe blocks

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#3597]
### 🎛 Description

🙋 feature request?

There are cases where I have a higher level `only_if` condition that relates to a control. I would also like to be able to use `only_if` inside describe blocks as well to further refine my testing. 

At the moment I am using `if/else` around describe blocks if a control has state conditional tests - I would like to use `only_if` as per our style guide.

@rachelrice would this fit into what you have been working on ?

**Comment by clintoncwolfe** [comment]
Refs #3557

**Comment by zenspider** [comment]
`only_if` is a control-level construct. Extending `describe`  and how a describe is run (ie rspec domain) is outside of our purview.
