### ISSUE TITLE
Feature Request: Checking Linux CVE's

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#3605]
I would love to have the ability to check if a machine is vulnerable to some CVE's
On SUSE : `zypper list-patches --all --cve | grep needed`
On RHEL : `yum --security --sec-severity=Critical check-update`

**Comment by aaronlippold** [comment]
Hi, 

I think we should eventually look into pushing this kind of capability here: https://github.com/dev-sec/linux-patch-baseline, as a work around we have been doing things like this at least on the RHEL side. 

It could be adjusted to fit your platform.

```
control 'cve-scan' do
  impact 0.5
  title 'CVE vulnerabilities - all packages must be up to date on security
    patches'
  desc 'Foundational security requires all system components to be free of
  well-known, patchable vulnerabilities as documented on cve.mitre.org.'
  tag "nist": ["SI-2", "RA-5", "Rev_4"]
  tag "check": "Run the command “yum updateinfo list cves” to list all packages
  that have known cve.mitre.org patchable vulnerabilities"
  tag "fix": "Run the command “yum update -y” to ensure the packages are up to
  date on patches."

  yum_exist_status = command('yum repolist').exit_status
  cve_list = command('yum updateinfo list cves')

  describe 'CVE vulnerabilities' do
    subject { cve_list }
    its('stdout.strip') { should_not match /(CVE-\d{4}-\d{4,7})/ }
  end if yum_exist_status.eql?(0) && cve_list.exit_status.eql?(0)

  describe 'This control must be reviewed manually' do
    skip 'The `yum` command failed.
    Please verify that `yum` is configured correctly on the target system.
    This control must be reviewed manually'
  end if !yum_exist_status.eql?(0) || !cve_list.exit_status.eql?(0)
end
```

**Comment by kmf** [comment]
@aaronlippold I agree, it would be great if this functionality was in the main project

**Comment by aaronlippold** [comment]
Well given MITRE runs the CVE database I will see how we could push on this a bit. What I need from you guys is some thoughts and suggestions on what do we really need for an interface to the CVE database - what makes sense - what would scale etc.
