### ISSUE TITLE
Update Fetcher plugin type from v1 to v2

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3610]
A CLI plugin for `inspec-compliance` was created but not a fetcher plugin. Since there isn't a fetcher plugin type, we added a shim in InSpec 3.0 (See: https://github.com/inspec/inspec/pull/3609)

We should:
  - [ ] Create a fetcher plugin type
  - [ ] Convert the mock fetcher
  - [ ] Convert the url fetcher
  - [ ] Convert/Update/Separate the Compliance fetcher plugin from the core plugin inspec-compliance
  - [ ] Convert the local fetcher
  - [ ] Convert the git fetcher
  - [ ] Remove the lines [here](https://github.com/inspec/inspec/pull/3609/files#diff-3eb6fa730bcc0611ce3b5e83c72bd18fR46)

Aha! Link: https://chef.aha.io/features/SH-2205

**Comment by clintoncwolfe** [comment]
Oh stalebot, you mean so well.

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
