### ISSUE TITLE
user InSpec resource missing comment  

### ISSUE THREAD

**Issue by Bhanukiran117** [inspec/inspec#3615]
### 🎛 Description

I am using chef user resource, 

```ruby
user "Create User" do
  action :create
  username "oracle"
  uid 200
  comment "Oracle Administrator"
end
```
I want to test the user comment using InSpec, I do not see this option is currently available. 

### 🌍 InSpec and Platform Version

```
inspec -v
3.0.12

Your version of InSpec is out of date! The latest version is 3.0.46.
```

```
cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

**Comment by jerryaldrichiii** [comment]
Great suggestion @Bhanukiran117! Both [here](https://github.com/inspec/inspec/blob/master/lib/resources/users.rb#L74) and [here](https://github.com/inspec/inspec/blob/master/lib/resources/users.rb#L380) could use some work for parsing the comment field.
