### ISSUE TITLE
"Expect" command missing from latest version

### ISSUE THREAD

**Issue by JumpSplat96** [inspec/inspec#3616]
### 🎛 Description

This is a feature request. 🙋

In previous versions of inspec (3.0.25 and before) it was possible to run a test using the command `expect`. Eg:

`it 'this test would not fail' do
     expect(3).to eq(3)
end`

Versions newer than 3.0.25 no longer have this feature, so any test which uses `expect` now fails. Our work has a lot of dependencies on this command, and refactoring is out of the question if this can just be put back in.

### 🌍 InSpec and Platform Version

This command works in version 3.0.25 and before. We use RHEL7.3.

### 🤔 Replication Case

To replicate the issue, just try to use the `expect` command for a test.

### 💁 Possible Solutions

Not sure.

### 💻 Stacktrace

`undefined method expect for #<RSpec::ExampleGroups::RhuiREGIONRhelServerRhsclRepo:0x00000003c83a40> Did you mean?  exec`

**Comment by clintoncwolfe** [comment]
Likely related to #3560, which sets the RSpec preferred syntax to `should` mode.  That was shipped in 3.0.46, 3.0.25 was last gem released prior.

**Comment by clintoncwolfe** [comment]
@chris-rock @arlimus - what do you think? We had an edge case on #952 #3560, in which RSpec is noisy, and we can silence the warning by setting the internal DSL mode to `should`.  Evidently that prevents `expect` from working;; if you specify one or the other, you may only use that set.

What do you think should be done? Reverting 3560 is straightforward, and un-breaks a lot of users that were using `expect`.  Few people were affected by #952, and now that we know how to trigger it, we can likely avoid it.

**Comment by jquick** [comment]
We should revert #3560 and figure out a new way to silence warnings.

**Comment by JumpSplat96** [comment]
@jquick @clintoncwolfe Thanks guys, sounds great! Any idea when we could "expect" it to be reverted?

**Comment by jquick** [comment]
Due to the holidays next week we will likely do a bug release early next week for it.

**Comment by phiggins** [comment]
Sorry for jumping in with little context, but could backwards compatibility be kept if you explicitly enabled the should and expect syntax? https://relishapp.com/rspec/rspec-expectations/docs/syntax-configuration#explicitly-enable-both-syntaxes

**Comment by chris-rock** [comment]
Great discussion, in InSpec, both should and expect syntax is expected to work. If we want to change this going forward, I would consider this a breaking change. I have seen both syntax in the wild. expect is mostly used by engineers with rspec background, should is more used by security and compliance experts.

**Comment by ehvidal** [comment]
Hey guys! Thank you for being discussing this. In the meantime, how can I do [this](https://relishapp.com/rspec/rspec-expectations/docs/syntax-configuration#explicitly-enable-both-syntaxes) but for inspec? I mean, in which file should I place `expectations.syntax = [:should, :expect]`? Thank you very much for your help!

**Comment by ehvidal** [comment]
Never mind. I added this content to a file in my `test/integration/<suite>` directory:

```ruby
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.syntax = [:should, :expect]
  end
end
```

and it worked.
