### ISSUE TITLE
Remove deprecated `shadow` resource matchers

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3631]
### 🎛 Description

🐛 bug report?

We have deprecation warnings for some the `shadow` resource matchers. We should remove them.

If we don't remove them before 4.0 we should change `warn` to `Inspec::Log.warn()` to allow hiding the deprecation warnings from the output (otherwise things like the `junit` reporter will be broken).

### 💁 Possible Solutions

Merging: https://github.com/inspec/inspec/pull/3627

Aha! Link: https://chef.aha.io/features/SH-2204

**Comment by clintoncwolfe** [comment]
Attn: @james-stocks 	

Refs: #2992 #2980 #3136

**Comment by james-stocks** [comment]
Thanks for the heads up @clintoncwolfe 

The user/users changes were previously an issue for us, but we're currently only using `shadow.where` and it appears https://github.com/inspec/inspec/pull/3627 won't alter how `where` filtering works at all.
So no objections from our team on making this change.

**Comment by clintoncwolfe** [comment]
Refs #3648 #465

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
