### ISSUE TITLE
Habitat InSpec Package uses BusyBox` rpm` which does not support remote querying

### ISSUE THREAD

**Issue by paul1994** [inspec/inspec#3635]
### 🎛 Description

**Choose one:** is this a 🐛 bug report

BusyBox's `rpm -qi` does not support querying remote packages (only supports local RPMs) (Trust me :D)

The Habitat package `chef/inspec` does not have `core/rpm` so the default `rpm` command is BusyBox's `rpm` this breaks package detection in InSpec because the `package` resource (on RHEL like systems) uses `rpm`. See: https://github.com/inspec/inspec/blob/master/lib/resources/package.rb#L185

### 🌍 InSpec and Platform Version

CentOS 7
Latest InSpec

### 🤔 Replication Case

Use this Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  config.vm.provision "shell", inline: <<-SHELL
    curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash
    sudo hab pkg install chef/inspec
  SHELL
end
```

#### From the OS

Run `vagrant ssh` and the following:

```
[vagrant@localhost ~]$ rpm
RPM version 4.11.3
Copyright (C) 1998-2002 - Red Hat, Inc.
This program may be freely redistributed under the terms of the GNU GPL
```

#### Habitat (via `hab pkg exec`)

Run `vagrant ssh` and the following:

```
[vagrant@localhost ~]$ hab pkg exec chef/inspec inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      centos
    Families:  redhat, linux, unix, os
    Release:   7.3.1611
    Arch:      x86_64

inspec> command('rpm').result
=> #<struct Train::Extras::CommandResult
 stdout="",
 stderr=
  "BusyBox v1.28.1 (2018-06-08 10:27:33 UTC) multi-call binary.\n\nUsage: rpm -i PACKAGE.rpm; rpm -qp[ildc] PACKAGE.rpm\n\nManipulate RPM packages\n\nCommands:\n\t-i\tInstall package\n\t-qp\tQuery package\n\t-qpi\tShow information\n\t-qpl\tList contents\n\t-qpd\tList documents\n\t-qpc\tList config files\n",
 exit_status=1>
```

### 💁 Possible Solutions

Add `core/rpm` as a run time dependency to InSpec Habitat plan

> NOTE: This probably affects other package managers like `dpkg`. Needs more testing.

**Comment by jerryaldrichiii** [comment]
This was fixed via https://github.com/inspec/inspec/pull/3645

Apologies for not closing it until now.
