### ISSUE TITLE
[Stretch] group resource: members returns nil

### ISSUE THREAD

**Issue by walker233** [inspec/inspec#3643]
### 🎛 Description

This is a 🐛 bug report 

On Centos 7.5 the group resource members returns nil, but the equivalent groups resource with members returns the list. 

### 🌍 InSpec and Platform Version

InSpec 2.2.112, Centos 7.5, running through kitchen-inspec 0.24.0

### 🤔 Replication Case

When you have a group named sftpusers exists with a single entry 'sftponly' the following code succeeds for groups resource checking members, but does not for the group resource.
```
describe groups.where { name == 'sftpusers' } do
  it { should exist }
  its('members') { should include 'sftponly' }
end

describe group('sftpusers') do
  it { should exist }
  its('members') { should include 'sftponly'}
end
```

### 💁 Possible Solutions

This did not seem directly obvious. 

### 💻 Stacktrace

Produces:
```
  Groups with name == "sftpusers"
     ✔  should exist
     ✔  members should include "sftponly"
  Group sftpusers
     ✔  should exist
     ×  members should include "sftponly"
     expected nil to include "sftponly", but it does not respond to `include?`
```

**Comment by thePhilGuy** [comment]
This also happens to me with InSpec 3.5.0 on ubuntu 14.04

**Comment by Paul-Michaud** [comment]
This happened to me with InSpec 4.12.0 on fedora 29 with this test : 
```ruby
describe group('root') do
  its('members') { should_not include 'nginx' }
end
```
It produces :
```bash
 ×  Group root members should not include "nginx"
     expected nil not to include "nginx", but it does not respond to `include?`
```

**Comment by clintoncwolfe** [comment]
https://github.com/inspec/inspec/blob/4fa55ebe7181aa790c92b6db4082955ed1af5570/lib/inspec/resources/groups.rb#L114 This line should be modified to always return a (possibly empty) Array, instead of nil. `flatten_entry` is used in many places and should not be modified, though.
