### ISSUE TITLE
docker: "include" labels support for `where`

### ISSUE THREAD

**Issue by amitsaha** [inspec/inspec#3654]
### 🎛 Description

🙋 feature request

One of the examples for the docker resource is:

```
describe docker.containers.where { names == 'flamboyant_colden' } do
  it { should be_running }
end
```

It also mentions that i can use `labels` in the where criteria.  How do I say, select containers which includes a label? Is something like this possible `..where { labels include 'my=label'}` ?

### 🌍 InSpec and Platform Version

NA
### 🤔 Replication Case

NA
### 💁 Possible Solutions

I would try to implement this feature if given some guidance.

**Comment by jerryaldrichiii** [comment]
This (#3673) will make it so you can do ```.where { lables.include?('my=label') }```.

Is that fine?

**Comment by amitsaha** [comment]
Yes, that will work. closing this.
