### ISSUE TITLE
InSpec does not adhere to Semantic Versioning for Minor Versions

### ISSUE THREAD

**Issue by aaron-lane** [inspec/inspec#3658]
### 🎛 Description

This a 🐛 bug report.

Enhancements, new features, and new resources have been added in patch releases of version 3. These releases seem to contradict InSpec's proclaimed adherence to Semantic Versioning.

### 🌍 InSpec Version

[v3.0.12](https://github.com/inspec/inspec/blob/master/CHANGELOG.md#v3012-2018-10-24)
[v3.0.25](https://github.com/inspec/inspec/blob/master/CHANGELOG.md#v3025-2018-11-01)
[v3.0.46](https://github.com/inspec/inspec/blob/master/CHANGELOG.md#v3046-2018-11-08)
[v3.0.52](https://github.com/inspec/inspec/blob/master/CHANGELOG.md#v3052-2018-11-15)
[v3.0.61](https://github.com/inspec/inspec/blob/master/CHANGELOG.md#v3061-2018-11-29)

### 💁 Possible Solutions

Require the version to be manually determined by one or more contributors prior to releasing.

**Comment by clintoncwolfe** [comment]
EDIT:

I had a little defensive message about breaking changes and major versions; re-reading the OP, I absolutely concede the point: we definitely have introduced features on patch releases, which should have been minor version bumps.

We do have a CI engine tag which will bump the minor, but it has to be manually added.  We also have a cultural issue on the team, I think, that a minor version bump is a "big deal".  

I'm not certain that adding a new resource or a new property on a resource justifies a minor version bump; if we said yes to that, we'd have a proliferation of minor versions.  Perhaps that's OK.  @aaron-lane, could you help me understand that impact?

attn: @krasnow

**Comment by miah** [comment]
I don't consider a minor version bump a big deal really. I'm fine with proliferation of minor versions. I for one welcome InSpec version 3.1337.0 =)

I agree that any time we see 'New Feature' in the ChangeLog we should probably be seeing a Minor bump.

As long as we don't have a artificial ceiling on minor version numbers this should never be a issue.

I'm also curious about impact, but I could see a Gemfile allowing minor version bumps being allowed and then being surprised when new features get included as well.

Out of the list above, I could see https://github.com/inspec/inspec/pull/3362 in 3.0.25 being a surprise.

**Comment by clintoncwolfe** [comment]
It would be good to be able to pin properly - say, a new resource you rely on was introduced in 3.1.12, and you could pin your profiles to insist on `~>3.1`, to ensure you get 3.1+ but not 4. That's an argument for including resources in minor bumps.

**Comment by aaron-lane** [comment]
@clintonwolfe no worries; I didn't even see it before you edited it. :wink:

Updating the minor version of the gem when backward compatible features are added would be helpful for projects like Kitchen-Terraform which depend on InSpec as a gem rather than a command-line tool. Semantic versioning makes it easier to ensure dependencies can easily be updated in a predictable way, and end users can choose to update InSpec without us having to test and release a new version.

**Comment by clintoncwolfe** [comment]
I think we're all on-board. Thursday's release will be a 3.1 series, and we'll be bumping minor much more often.  We're still working out how fine-grained that should be in some areas, but I think it will be much more reliable.  Thanks for bringing up a pain point!

**Comment by clintoncwolfe** [comment]
Thanks again for opening this. I've made a small announcement about semver on the 3.1.3 release announcement.  I'm going to go ahead and close this, thanks!

**Comment by aaron-lane** [comment]
@clintoncwolfe thank you for the swift response!
