### ISSUE TITLE
Add supported platforms to resource docs

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3688]
It would be nice to be able to tell what platforms are supported by a specific resource without having to look at the resource code.

Aha! Link: https://chef.aha.io/features/SH-2202

**Comment by clintoncwolfe** [comment]
Refs #3165

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
