### ISSUE TITLE
Investigate relationship between Chef and InSpec attributes

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3697]
A common topic that comes up with our users is how Chef attributes are handled in InSpec. Historically, we've been hesitant to recommend using Chef attributes in InSpec due to the issues inherent is using the same data for both Chef implementation and InSpec verification (e.g. Chef creates user `bobb` from attribute, then InSpec uses that attribute to verify `bobb` exists...but the intention was for the user to be named `bob`).

I'm opening this issue to start a discussion and gather use cases where using Chef attributes in InSpec is preferred.

My personal opinion is we should have an easy to use and well documented integration, but also warn the user about potential pitfalls that may occur.

What do y'all think? 😄

**Comment by jkugler** [comment]
My use case looks like this:

There can be differences in the finished environment based on chef attributes. It would be nice if inspec could branch on a chef attribute to figure out which test to run.

Something easy to access like `chef_attribute()` would be nice.

Even just loading up a `node` object would solve all my chef attribute issues. :)

**Comment by jerryaldrichiii** [comment]
@jkugler, could you elaborate a bit on that? Maybe a simplified example? I'm a bit worried about dynamically defining tests, save for using `only_if`.

**Comment by jkugler** [comment]
One example. When testing, we may point a machine to a testing repository or a stable repository (the branch in the Chef code keys off of attributes in kitchen.yml). When we then run the inspec code and verify the repository to which the machine is pointing, it would be nice to access that Chef attribute to know the repository to which the machine should be pointing. I'm sure I can think of other examples; I'll ad them when I do.

**Comment by clintoncwolfe** [comment]
Refs #3666, new 'attribute_provider' plugin type

**Comment by clintoncwolfe** [comment]
Refs #3837 	#3748

**Comment by thheinen** [comment]
This ticket is quite old, but I would like to add a remark for future reference:

For a project I created the inspec-chef plugin which allows using Chef attributes/data bags as InSpec inputs. If your machine executing the InSpec tests is a Chef node and has access to this, that plugin might solve some problems.

For details see [inspec-chef on Rubygems](https://rubygems.org/gems/inspec-chef)

**Comment by james-stocks** [comment]
That's awesome @tecracer-theinen - thanks!

We now have attributes changed to inputs, and a lot of improvement work has been done. 
`inspec-chef` is also now available.
