### ISSUE TITLE
processes: clarify or simplify commands property

### ISSUE THREAD

**Issue by caarlos0** [inspec/inspec#3699]
### 🎛 Description

🙋feature request: if I have a process `processes` spec like the following:

```rb
describe processes('mtail') do
  its(:commands) { should match %r{-progs /usr/share/mtail/progs/} }
  its(:commands) { should match %r{-logs /var/log/syslog,/var/log/dmesg/} }
end
```

It is not possible to match it, as `commands` is a list and `match` only works against strings.

It can be workaround by wrapping the regex in an array, which is not obvious nor documented.

**Comment by zenspider** [comment]
I'm not sure what you want clarified.

As far as "simplify" goes, I think the answer is "no".

As far as your actual problem goes, you could join the array into a string and then use match, or don't use `match` and check that your two args are in the array. 

Please close your issue if this addresses your problem or expand on it here. Thank you.
