### ISSUE TITLE
New resource: aws_launch_configuration

### ISSUE THREAD

**Issue by amitsaha** [inspec/inspec#3726]
### 🎛 Description

**Choose one:** 🙋 feature request

This issue is to track implementing a new resource `aws_launch_configuration` for inspecting AWS auto scaling launch configuration

### 🌍 InSpec and Platform Version

NA

**Comment by amitsaha** [comment]
PR: https://github.com/inspec/inspec/pull/3727

**Comment by clintoncwolfe** [comment]
Will be implemented in inspec/inspec-aws .
