### ISSUE TITLE
Improve formatting of inspec exec --help

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3730]
### 🎛 Description

🐛 bug report

The output of `inspec exec --help` is pretty ugly.  #3447 adds more exit codes, and it looks bad (80x25):

![screen shot 2019-01-16 at 13 23 58](https://user-images.githubusercontent.com/156460/51270080-0e755180-1992-11e9-84b2-4a8d0c782bb0.png)

### 🌍 InSpec and Platform Version

3.2.x

### 🤔 Replication Case

Run `inspec exec --help`

### 💁 Possible Solutions

See if Thor has custom formatter support?

Separate www processing from thor processing (ouch)?

**Comment by zenspider** [comment]
DONE!
