### ISSUE TITLE
Some unit test files may not run

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3733]
### 🎛 Description

🐛 bug report

We've had a report on https://github.com/inspec/inspec/pull/3729/files#r248246195 that at least one unit test file, `test/unit/profiles/profile_test.rb` is being omitted during `rake test:unit`.

### 🌍 InSpec and Platform Version

3.2.x

### 🤔 Replication Case

`bundle exec rake test`; at the beginning there will be a large block showing the command line invocation, listing all unit test files.  Verify that the file exists. It may exist but have the 'no tests found' issue; try adding a known failing test to it to force detection of that condition.

### 💁 Possible Solutions

Check the Rakefile glob.  Isolate to just that file to check for "no tests found" error.

If it is "no tests found"... well we don't know how to fix that yet :-)

**Comment by jerryaldrichiii** [comment]
I haven't done any work on this, so I'm going to unassign myself so expectations can be managed.

**Comment by zenspider** [comment]
This is fixed.
