### ISSUE TITLE
azure:: how to pass in credentials?

### ISSUE THREAD

**Issue by challs1** [inspec/inspec#3735]
when running in azure where should we keep the profile value to run locally by using "inspec exec test.rb"
? iam getting error as" Could not fetch inspec profile in "test.rb". Kindly help me in this regard thanks

**Comment by challs1** [comment]
when running in azure where should we keep the profile value  to run? iam getting error as" Could not fetch inspec profile in "test.rb".  Kindly help me in this regard thanks

**Comment by clintoncwolfe** [comment]
I'm not sure exactly what you are asking, but our Azure credential information is here - https://www.inspec.io/docs/reference/platforms/

**Comment by clintoncwolfe** [comment]
As this is a support question, and I think I have answered it, I am closing this.  Please re-open if you have any further questions.
