### ISSUE TITLE
yaml-Parser: Can't test hierarchical values

### ISSUE THREAD

**Issue by bwaterkamp** [inspec/inspec#3738]
### 🎛 Description

I'm trying to parse elasticsearch-Config with the YAML ressource. The smallest test file looks like this:

```
node.name: example.com
```

Chris suggested this way to access sub values like name  in #554:

```
describe yaml('/tmp/elasticsearch.yml') do
  its(['node','name']) { should match /example\.com/ }
end
```
I'm getting the following error:

```
     ×  YAML /tmp/elasticsearch.yml ["node", "name"] should match /example\.com/
     expected nil to match /example\.com/
```

If i change the file to this notation, the same test succeeds:

```
node:
  name: example.com
```
The dot notation ("node.name") is the default one in Elasticsearch Config, so it should be quite common. Is there any way to modify the test so that it recognizes values written like this?

### 🌍 InSpec and Platform Version

Inspec 3.2.6 / RHEL 7.6

**Comment by clintoncwolfe** [comment]
Thanks for the report!  However, I don't think your question has anything to do with InSpec, but rather the YAML parser that ships with Ruby.

If I understand you correctly, you are asking for a YAML file which contains text like 'node.name: example.com' to parse as `{ node: { name: 'example.com' } }`.  

However, the YAML parser does not see dots as significant, and so:
![screen shot 2019-01-23 at 11 11 09](https://user-images.githubusercontent.com/156460/51620194-dd4fd080-1eff-11e9-8f41-86cadf7653f8.png)

**Comment by bwaterkamp** [comment]
@clintoncwolfe thanks for your support! Now i get it: I thought this was a YAML syntax element, but the way to flatten config files with "node.name: example.com" instead of writing 

```
node: 
   name: example.com
```
 is built into Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_config_file_format

So "node.name" is valid YAML, parsed like the version shown above. I now understand that it is _not_ an Inspec error, but maybe you can help me with a little hint: How do i test if "node.name" has a certain value? Example:
```
$ cat elasticsearch.yml 
node.name: example.com
-bash-4.2$
```
I was not successful trying it like this:

```
describe yaml('/tmp/elasticsearch.yml') do
 its(['node','name']) { should match /example\.com/ }  
end
# Result: expected nil to match /example\.com/

describe yaml('/tmp/elasticsearch.yml') do
 its('node.name') { should match /example\.com/ }  
end 
# Result: undefined method `name' for nil:NilClass

describe yaml('/tmp/elasticsearch.yml') do
 its('node\.name') { should match /example\.com/ }  
end
# Result: undefined method `name' for nil:NilClass
```

**Comment by clintoncwolfe** [comment]
You can keep playing with the arguments to `its` - those come from https://github.com/rspec/rspec-its , and please refer there for more possibilities.

Much more simply, though, you can call `yaml` outside of a control block.

```
the_info_as_a_big_deep_hash = yaml('/tmp/elasticsearch.yml').params # The method name makes no sense

describe the_info_as_a_big_deep_hash['node.name'] do
  it { should match /example\.com/ }
end
```

**Comment by clintoncwolfe** [comment]
As this is a support question, and I think we've answered it, I'm going to close this issue.  If you have any further questions on this topic, please feel free to re-open.

**Comment by bwaterkamp** [comment]
@clintoncwolfe , is was out of office and now had time to test your suggestion: works as expected. Thanks for your support!
