### ISSUE TITLE
Use deprecation facility throughout code

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3745]
### 🎛 Description

🙋 feature request?

Throughout the code, we have comments and warning messages mentioning to deprecate a feature in the future.  With #3690, we now have a centralized deprecation facility.

 * Search throughout the codebase and find deprecation comments and warning messages.
 * Create groups in etc/deprecations.json
 * Replace the deprecation comments with calls to Inspec.deprecate

### 🌍 InSpec and Platform Version

3.2.x

**Comment by zenspider** [comment]
DONE?
