### ISSUE TITLE
Don't use hardcoded path for sysctl in kernel_parameter resource

### ISSUE THREAD

**Issue by mogthesprog** [inspec/inspec#3746]
### 🎛 Description

 🐛 bug report

I've recently started using the [devsec.io Linux-Baseline](https://github.com/dev-sec/linux-baseline) tests to test our linux infrastructure. The tests make heavy use of the `kernel_parameter` resource to test the linux kernel parameters, which under the hood uses `sysctl` to check kernel configuration.

It looks like the `kernel_parameter` resource [has a hardcoded path for sysctl](https://github.com/inspec/inspec/blob/7deed13425c299ded99ff6e4095b1e0db969a826/lib/resources/kernel_parameter.rb#L22), which isn't always the correct path for sysctl.

### 🌍 InSpec and Platform Version

```
$ inspec version
3.2.6
```

### 🤔 Replication Case

1. Clone the `linux-baseline` inspec tests
```
git clone https://github.com/dev-sec/linux-baseline.git /tmp/linux-baseline
```
1. Run the inspec tests on a linux system, in my case this is a remote system
```
inspec exec \
    -t ssh://${ssh_username}@${instance_ip} \
    --key-files=${ssh_private_key_file} \
    --sudo \
        /tmp/linux-baseline
```

### 💁 Possible Solutions

We could use the `PATH` to resolve a valid instance of `sysctl`, and maybe fall back to the current hardcoded path provided in the code already(?). It's important to note that some operating systems don't make the `sysctl` binary available to unprivileged users, so we'd also need to make sure that we're checking the privileged PATH when `--sudo` is passed.

### 💻 Stacktrace

No stacktrace, but you will see `nil` values where the kernel will always return an integer:

```
   ↺  sysctl-31b: Secure Core Dumps - dump path
      ↺  Skipped control due to only_if condition.
   ×  sysctl-32: kernel.randomize_va_space
      ×  Kernel Parameter kernel.randomize_va_space value should eq 2

   expected: 2
         got: nil
```

`nil` here should be an integer.

**Comment by clintoncwolfe** [comment]
Would it make sense to broaden this issue to cover all `command` invocations when running under sudo?

**Comment by clintoncwolfe** [comment]
attn @miah 	any thoughts?

**Comment by mogthesprog** [comment]
Any news on this? it's a bit of a blocker for security testing if you can't use sysctl.

I may have time in a week or so to get this building locally and fix it myself if nobody gets to it. I'd rather get the thumbs up before spending time implementing it.

**Comment by mogthesprog** [comment]
also, i'd be interested in fixing just this one for now, since changing all commands sounds like a more significant change. :)

**Comment by clintoncwolfe** [comment]
We'd certainly welcome any contribution - thanks!

**Comment by mogthesprog** [comment]
See PR above. I've also included (what i think) seems to be the files that would need changing in order to make the larger change. 

Let me know on the PR if you'd like me to follow through with that, and if i've missed anything. I'm happy to do that based on the size of the list there.
