### ISSUE TITLE
Result from `ulimit -n` is empty

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3749]
### 🎛 Description

**Choose one:** is this a 🐛 bug report

The value of `ulimit -n` is empty but not when redirecting output. See:

```
[~]$ ulimit -n                                                                               
1024
[~]$ inspec shell                                                                               
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      arch
    Families:  linux, unix, os
    Release:   4.18.16-arch1-1-ARCH
    Arch:      x86_64

inspec> command('ulimit -n').result
=> #<struct Train::Extras::CommandResult stdout="", stderr="", exit_status=1>
inspec> command('ulimit -n | cat').result
=> #<struct Train::Extras::CommandResult stdout="1024\n", stderr="", exit_status=0>
inspec> command('ulimit -n 2>&1').result
=> #<struct Train::Extras::CommandResult stdout="1024\n", stderr="", exit_status=0>
```

Other shell built-in commands seem to work as expected. See:

```
inspec> command('printf example').result
=> #<struct Train::Extras::CommandResult stdout="example", stderr="", exit_status=0>
inspec> command('pwd').result
=> #<struct Train::Extras::CommandResult stdout="/home/jerry\n", stderr="", exit_status=0>
```

Also, it works when calling bash specifically see:

```
inspec> command('bash -c "ulimit -n"').result
=> #<struct Train::Extras::CommandResult stdout="1024\n", stderr="", exit_status=0>
```

**Comment by chrisg-fastlane** [comment]
I've found these BASH builtins exhibit similar behaviour: _declare, dirs, enable, help, shopt, typeset, ulimit_.  I get the same behaviour in centos and mac_os_x (if the builtins exist).

    Name:      centos
    Families:  redhat, linux, unix, os
    Release:   7.4.1708
    Arch:      x86_64

    Name:      mac_os_x
    Families:  darwin, bsd, unix, os
    Release:   17.7.0
    Arch:      x86_64
```
control 'test builtins' do
  %w[declare dirs enable help shopt typeset ulimit].each do |cmd|
    describe command(cmd) do
      its(:stdout) { should_not cmp '' }
    end
    describe command("#{cmd} | cat") do
      its(:stdout) { should_not cmp '' }
    end
  end
end
```

**Comment by clintoncwolfe** [comment]
I'm not clear on how this falls under InSpec's purview.  If a shell handles certain builtins differently when they think they are not being redirected, that's a (mis?)feature of that shell.

Is an InSpec resource calling one of these built-ins? If so, we could change its behavior to pipe through `cat` or something.

But if we're just speculating "there are certain builtins that act unexpectedly if a user authors a control using `command('funny_builtin')`", I'm not sure I see how this can be actionable.

**Comment by jerryaldrichiii** [comment]
I think the `command` resource should provide the output of any command that provides output on the shell. I think there is an issue here with the resource (or Train). It is particularly odd that there is neither stdout or stderr is being captured when using those commands (but output is presented when using `bash -c 'ulimit -n'`).

All this being said, I see your point about it's relevance. This might be shell specific.

**Comment by zenspider** [comment]
Closing since this is partially covered in #4548. I would expect the need to use `bash -c` on any platform where ulimit is a builtin.
