### ISSUE TITLE
Reporting expected value vs actual value in JSON

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3752]
An internal employee brought up a neat bit of reporting that would help our users (in this case a customer).

Essentially he is wondering if it is possible to extract the 'Expected value' vs 'Actual value' from the failed tests in an InSpec report.

The data is there...but a possible issue is that currently these values come in a `'message'` string in the JSON.

See:
```
"results": [
  {
    "status": "failed",
    "code_desc": "SSHD Configuration X11Forwarding should eq \"no\"",
    "run_time": 0.001535926,
    "start_time": "2019-01-25T03:14:48-08:00",
    "message": "\nexpected: \"no\"\n     got: \"yes\"\n\n(compared using ==)\n"
   }
]
```

Is there anyway we can coax RSpec into giving us this data in a way that someone (especially Automate) can use?

**Comment by anthonygrees** [comment]
Thanks for raising this issue Jerry.  Customers need this so they can store the actual and expected values for their Audit process.

**Comment by rakheeuob** [comment]
Thanks Anthony and Jerry -this is our precise requirement

**Comment by jerryaldrichiii** [comment]
Digging a bit more in to this and `message` is indeed coming from RSpec. I'm not sure even a custom RSpec formatter can solve this since it comes from the matchers. See:

https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/eql.rb#L10

The only option I see on our end is to parse the string and split, but text processing of strings provided upstream (which are likely slightly different between matchers) is not something I feel comfortable doing in InSpec.

I'd like another opinion, but I think this can be closed since implementing it is not practical.

@clintoncwolfe @miah thoughts?

**Comment by aaronlippold** [comment]
What's the example data structure you'd like to see? Or maybe more
specifically what use case are we trying to cover?

**Comment by jerryaldrichiii** [comment]
The use case is mentioned in the description. The requester is wanting different fields for `expected` vs `actual` values in a report. Something like:

```
"results": [
  {
    "status": "failed",
    "code_desc": "SSHD Configuration X11Forwarding should eq \"no\"",
    "run_time": 0.001535926,
    "start_time": "2019-01-25T03:14:48-08:00",
    "message": "\nexpected: \"no\"\n     got: \"yes\"\n\n(compared using ==)\n"
    "expected_value": "no",
    "actual_value": "yes"
   }
]
```

**Comment by zenspider** [comment]
I don't think this is (reasonably) possible. Closing.
