### ISSUE TITLE
'inspec --help' does not load plugins, so no usage message

### ISSUE THREAD

**Issue by rubycut** [inspec/inspec#3753]
### 🎛 Description

🐛 bug report

When I run ```inspec --help``` the existence of init command is not even mentioned

If I run ```inspec help```, then it is visible.

### 🌍 InSpec and Platform Version

3.2.6

**Comment by clintoncwolfe** [comment]
Bug at https://github.com/inspec/inspec/blob/033d534b47b0211ce89266e9df3eddfccb14edb6/lib/inspec/plugin/v2/loader.rb#L92
