### ISSUE TITLE
Change `inspec compliance` to `inspec automate`

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3780]
The Chef Compliance server is EOL as of December 31, 2018. See: https://blog.chef.io/2018/06/29/end-of-life-announcement-for-chef-compliance-server/

I think we should:
  - Rename `inspec compliance` to `inspec automate`
  - Add an alias and deprecation for `inspec compliance`
  - Update README [here](https://github.com/inspec/inspec/tree/master/lib/plugins/inspec-compliance) and remove mentions of Chef Compliance
  - Rename `CLI: compliance` GitHub label to `CLI: automate`

Thoughts? Objections?

Aha! Link: https://chef.aha.io/features/SH-2201

**Comment by clintoncwolfe** [comment]
Refs #3426 - this could be considered a sub-task

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.
