### ISSUE TITLE
Train 1.7.2 breaks Inspec 2.3.24

### ISSUE THREAD

**Issue by rbclark** [inspec/inspec#3787]
### 🎛 Description

🐛 bug report

After updating to train 1.7.2 I am unable to use the SSH executor with a password provided.

### 🌍 InSpec and Platform Version

MacOS 10.14.3
InSpec 2.3.24 (Installed via bundle install)
Train 1.7.2

### 🤔 Replication Case

    $ bundle exec inspec exec spec-file -b ssh --user root --host [REDACTED] --password [REDACTED]
    Client error, can't connect to 'ssh' backend: You must provide a value for "host".

### 💁 Possible Solutions

If the max version of train compatible with InSpec 2.3.24 is locked to 1.6.3 then the above command begins working again. If it were possible to get a version of InSpec 2.3 released with this one change that may save a lot of people headache.

**Comment by clintoncwolfe** [comment]
How are you installing InSpec?

Also, is there anything preventing you from using 3.6.2?

**Comment by clintoncwolfe** [comment]
Refs https://github.com/inspec/train/issues/404 ; workaround used there briefly was to pin to 1.7.1 of train; and inspec failed-forward on 3.6.2

**Comment by rbclark** [comment]
I am currently dependent on inspec_tools which does not yet support inspec 3.x https://github.com/mitre/inspec_tools/issues/22

I installed using bundler, I assume if this is a known issue then 1.7.1 will work as well, I stopped once I tracked down that 1.6.3 works

**Comment by clintoncwolfe** [comment]
Ok, we have built inspec 2.3.28, which is pinned to train 1.7.1 .  

https://rubygems.org/gems/inspec/versions/2.3.28

Please re-open if trouble persists.

Thanks for the report!
