### ISSUE TITLE
Piping config broken on certain CLI commands in v3.6.2

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3792]
### 🎛 Description

🐛 bug report

@stevendanna reports on #3791 that when reading config from STDIN, certain code paths read STDIN twice, resulting in a failed JSON parse on the second attempt.  The parse exception is caught and the run is gracefully aborted, but expected behavior is to read the config and operate normally.

Config is intended to generally be safe to instantiate multiple times; this is relied upon in several code paths, including anything calling `run_command` (this includes `detect` and `shell`, possibly `check`, but apparently not `exec`; this means our functional test (which calls exec) did not catch it).

### 🌍 InSpec and Platform Version

3.6.2, regressed via #3750 

### 🤔 Replication Case

```
echo '{"backend":"docker","host":"something","reporter":{"json":{}},"backend_cache":true}' | inspec detect --json-config=-
```

### 💁 Possible Solutions

Some alternatives:
 * Add a class var to Inspec::Config; read STDIN into it, and check there next time.
 * After reading STDIN, try to rewind it.
 * Trace each time we call Config.new() multiple times and adjust
 * Make Config a singleton

### 💻 Stacktrace

See #3791 

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by stevendanna** [comment]
> After reading STDIN, try to rewind it.

That's gonna be a no-go since STDIN is usually going to be a pipe.
