### ISSUE TITLE
Make reporting consistent/predictable

### ISSUE THREAD

**Issue by bianxi** [inspec/inspec#3797]
(edited by @zenspider to strike out prescriptive aspects of this issue)

### 🎛 Description

🙋 feature request

~~Sort control files before loading them to allow results to be predictable (This is similar to pull requests [#3887](https://github.com/inspec/inspec/pull/3887))~~

Customer wants reports to be in a consistent order.

### 🌍 InSpec and Platform Version

inspec version: **4.6.9**
Operating System: **RHEL 7**, **AIX 7/6**, **WIN2008/2012/2016**, **SOLARIS 11**

### 🤔 Replication Case

~~The loading order of control files is based on OS **find** command output, it is hard to organize large number of controls into control files, especially when initialing and closing actions are required.~~

### 💁 Possible Solutions

No:

    Add sorting statement as below, and testing had been done.

    ``` git diff
    diff --git a/lib/inspec/profile.rb b/lib/inspec/profile.rb
    index 6f6f3048..be66581a 100644
    --- a/lib/inspec/profile.rb
    +++ b/lib/inspec/profile.rb
    @@ -55,6 +55,7 @@ module Inspec
         def self.for_path(path, opts)
           file_provider = FileProvider.for_path(path)
           rp = file_provider.relative_provider
    +      rp.files.sort!

           # copy embedded dependencies into global cache
           copy_deps_into_cache(rp, opts) unless opts[:vendor_cache].nil?
    ```
    Note: Currently, we patch inspec for all OS mentioned above to perform various actions collectly.

**Comment by bianxi** [comment]
Solution #3887 is also acceptable.

**Comment by aaronlippold** [comment]
I think what the general consensus is is that we would like to just order it at the other end. In other words, the ordering should come out of the reporter not the loader. I think that's completely fair and meets the spirit of what we want of accomplish but implemented in the correct place.

**Comment by aaronlippold** [comment]
Tests must be independent of each other in the compliance space. So implementing on this side leads us to possible bad habits.

**Comment by bianxi** [comment]
Don’t sort is really a lazy and bad habit. Depending on other applications to perform some basic functionalities is not something can be proud at all. It was the old dos way, same habit as creating table without primary key. Sorting doesn’t preventing others sort them again, we all understand.

**Comment by bianxi** [comment]
There is nothing can be real independent, same as the “depends” used in InSpec itself. Unpredictable is the problem bringing many issues during testing, in fact, creates unpredictable environment or system dependent test results.
