### ISSUE TITLE
plugins now install docs

### ISSUE THREAD

**Issue by burdena** [inspec/inspec#3799]
### 🎛 Description

**Choose one:** is this a 🐛 bug report 

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version

3.6.4 ( docker image )

### 🤔 Replication Case

docker run -it --rm chef/inspec:3.6.4  plugin install inspec-iggy

### 💁 Possible Solutions

I don't remember it installing documentation before I imagine this is part of the issue

### 💻 Stacktrace

docker run -it --rm chef/inspec:3.6.4  plugin install inspec-iggy
Unable to find image 'chef/inspec:3.6.4' locally
3.6.4: Pulling from chef/inspec
Digest: sha256:a388bc68eb58b42dceb2b60fed796136004565f40317dec2a15cbe88dd57b202
Status: Downloaded newer image for chef/inspec:3.6.4
Fetching inspec-iggy-0.4.0.gem
Parsing documentation for tins-1.20.2
Installing ri documentation for tins-1.20.2
Parsing documentation for term-ansicolor-1.7.1
Installing ri documentation for term-ansicolor-1.7.1
invalid options: -SHN
(invalid options are ignored)
Parsing documentation for multipart-post-2.0.0
Installing ri documentation for multipart-post-2.0.0
Parsing documentation for htmlentities-4.3.4
Installing ri documentation for htmlentities-4.3.4
Parsing documentation for semverse-3.0.0
Installing ri documentation for semverse-3.0.0
Parsing documentation for parslet-1.8.2
Installing ri documentation for parslet-1.8.2
Parsing documentation for public_suffix-3.0.3
Installing ri documentation for public_suffix-3.0.3
Parsing documentation for addressable-2.6.0
Installing ri documentation for addressable-2.6.0
Parsing documentation for tomlrb-1.2.8
Installing ri documentation for tomlrb-1.2.8
Parsing documentation for faraday-0.15.4
Installing ri documentation for faraday-0.15.4
Parsing documentation for faraday_middleware-0.12.2
Installing ri documentation for faraday_middleware-0.12.2
Parsing documentation for tty-cursor-0.6.0
Installing ri documentation for tty-cursor-0.6.0
Parsing documentation for tty-screen-0.6.5
Installing ri documentation for tty-screen-0.6.5
Parsing documentation for wisper-2.0.0
Installing ri documentation for wisper-2.0.0
Parsing documentation for tty-reader-0.5.0
Installing ri documentation for tty-reader-0.5.0
Parsing documentation for timers-4.3.0
Installing ri documentation for timers-4.3.0
Parsing documentation for tty-color-0.4.3
Installing ri documentation for tty-color-0.4.3
Parsing documentation for equatable-0.5.0
Installing ri documentation for equatable-0.5.0
Parsing documentation for pastel-0.7.2
Installing ri documentation for pastel-0.7.2
Parsing documentation for necromancer-0.4.0
Installing ri documentation for necromancer-0.4.0
Parsing documentation for tty-prompt-0.18.1
Installing ri documentation for tty-prompt-0.18.1
Parsing documentation for unicode-display_width-1.4.1
Installing ri documentation for unicode-display_width-1.4.1
Parsing documentation for unicode_utils-1.4.0
Installing ri documentation for unicode_utils-1.4.0
Parsing documentation for strings-ansi-0.1.0
Installing ri documentation for strings-ansi-0.1.0
Parsing documentation for strings-0.1.4
Installing ri documentation for strings-0.1.4
Parsing documentation for tty-table-0.10.0
Installing ri documentation for tty-table-0.10.0
Parsing documentation for parallel-1.13.0
Installing ri documentation for parallel-1.13.0
Parsing documentation for sslshake-1.3.0
Installing ri documentation for sslshake-1.3.0
Parsing documentation for mixlib-log-3.0.1
Installing ri documentation for mixlib-log-3.0.1
Parsing documentation for hashie-3.6.0
Installing ri documentation for hashie-3.6.0
Parsing documentation for method_source-0.9.2
Installing ri documentation for method_source-0.9.2
invalid options: -SNw2
(invalid options are ignored)
Parsing documentation for coderay-1.1.2
Installing ri documentation for coderay-1.1.2
Parsing documentation for pry-0.12.2
Installing ri documentation for pry-0.12.2
Parsing documentation for diff-lcs-1.3
Couldn't find file to include 'Contributing.rdoc' from README.rdoc
Couldn't find file to include 'License.rdoc' from README.rdoc
Installing ri documentation for diff-lcs-1.3
Parsing documentation for rspec-support-3.8.0
Installing ri documentation for rspec-support-3.8.0
Parsing documentation for rspec-expectations-3.8.2
Installing ri documentation for rspec-expectations-3.8.2
Parsing documentation for rspec-core-3.8.0
Installing ri documentation for rspec-core-3.8.0
Parsing documentation for rspec-its-1.2.0
Installing ri documentation for rspec-its-1.2.0
Parsing documentation for rspec-mocks-3.8.0
Installing ri documentation for rspec-mocks-3.8.0
Parsing documentation for rspec-3.8.0
Installing ri documentation for rspec-3.8.0
Parsing documentation for rubyzip-1.2.2
Installing ri documentation for rubyzip-1.2.2
Parsing documentation for thor-0.20.3
Installing ri documentation for thor-0.20.3
Parsing documentation for inifile-3.0.0
Installing ri documentation for inifile-3.0.0
Parsing documentation for jwt-2.1.0
Installing ri documentation for jwt-2.1.0
Parsing documentation for multi_json-1.13.1
Installing ri documentation for multi_json-1.13.1
Parsing documentation for signet-0.11.0
Installing ri documentation for signet-0.11.0
Parsing documentation for os-1.0.0
Installing ri documentation for os-1.0.0
Parsing documentation for memoist-0.16.0
Installing ri documentation for memoist-0.16.0
Parsing documentation for googleauth-0.6.7
Installing ri documentation for googleauth-0.6.7
Parsing documentation for httpclient-2.8.3
Installing ri documentation for httpclient-2.8.3
Parsing documentation for mime-types-data-3.2018.0812
Installing ri documentation for mime-types-data-3.2018.0812
Parsing documentation for mime-types-3.2.2
Installing ri documentation for mime-types-3.2.2
Parsing documentation for retriable-3.1.2
Installing ri documentation for retriable-3.1.2
Parsing documentation for declarative-option-0.1.0
Installing ri documentation for declarative-option-0.1.0
Parsing documentation for declarative-0.0.10
Installing ri documentation for declarative-0.0.10
Parsing documentation for uber-0.1.0
Installing ri documentation for uber-0.1.0
Parsing documentation for representable-3.0.4
Installing ri documentation for representable-3.0.4
Parsing documentation for google-api-client-0.23.9
Installing ri documentation for google-api-client-0.23.9
Parsing documentation for concurrent-ruby-1.1.4
Installing ri documentation for concurrent-ruby-1.1.4
Parsing documentation for timeliness-0.3.10
Installing ri documentation for timeliness-0.3.10
Parsing documentation for ms_rest-0.7.3
Installing ri documentation for ms_rest-0.7.3
Parsing documentation for unf_ext-0.0.7.5
Installing ri documentation for unf_ext-0.0.7.5
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.20180417
Installing ri documentation for domain_name-0.5.20180417
Parsing documentation for http-cookie-1.0.3
Installing ri documentation for http-cookie-1.0.3
Parsing documentation for faraday-cookie_jar-0.0.6
Installing ri documentation for faraday-cookie_jar-0.0.6
Parsing documentation for ms_rest_azure-0.11.0
Installing ri documentation for ms_rest_azure-0.11.0
Parsing documentation for azure_mgmt_key_vault-0.17.2
Installing ri documentation for azure_mgmt_key_vault-0.17.2
Parsing documentation for azure_graph_rbac-0.17.0
Installing ri documentation for azure_graph_rbac-0.17.0
Parsing documentation for azure_mgmt_resources-0.17.2
Installing ri documentation for azure_mgmt_resources-0.17.2
Parsing documentation for aws-sigv4-1.0.3
Installing ri documentation for aws-sigv4-1.0.3
Parsing documentation for jmespath-1.4.0
Installing ri documentation for jmespath-1.4.0
Parsing documentation for aws-sdk-core-2.11.217
Installing ri documentation for aws-sdk-core-2.11.217
Parsing documentation for aws-sdk-resources-2.11.217
Installing ri documentation for aws-sdk-resources-2.11.217
Parsing documentation for aws-sdk-2.11.217
Installing ri documentation for aws-sdk-2.11.217
Parsing documentation for excon-0.62.0
Installing ri documentation for excon-0.62.0
Parsing documentation for docker-api-1.34.2
Installing ri documentation for docker-api-1.34.2
Parsing documentation for rubyntlm-0.6.2
Installing ri documentation for rubyntlm-0.6.2
Parsing documentation for nori-2.6.0
Installing ri documentation for nori-2.6.0
Parsing documentation for little-plugger-1.1.4
Installing ri documentation for little-plugger-1.1.4
Parsing documentation for logging-2.2.2
Installing ri documentation for logging-2.2.2
Parsing documentation for builder-3.2.3
Installing ri documentation for builder-3.2.3
Parsing documentation for gyoku-1.3.1
Installing ri documentation for gyoku-1.3.1
Parsing documentation for ffi-1.10.0
Installing ri documentation for ffi-1.10.0
Parsing documentation for gssapi-1.2.0
Installing ri documentation for gssapi-1.2.0
Parsing documentation for erubis-2.7.0
Installing ri documentation for erubis-2.7.0
Parsing documentation for winrm-2.3.1
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/local/bin/ruby -c lib/winrm/psrp/powershell_output_decoder.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

Traceback (most recent call last):
	38: from /usr/local/bundle/bin/inspec:23:in `<main>'
	37: from /usr/local/bundle/bin/inspec:23:in `load'
	36: from /usr/local/bundle/gems/inspec-3.6.4/bin/inspec:12:in `<top (required)>'
	35: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	34: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	33: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	32: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	31: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	30: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	29: from /usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	28: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	27: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	26: from /usr/local/bundle/gems/inspec-3.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:98:in `install'
	25: from /usr/local/bundle/gems/inspec-3.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:320:in `install_from_remote_gem'
	24: from /usr/local/bundle/gems/inspec-3.6.4/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:362:in `install_attempt_install'
	23: from /usr/local/bundle/gems/inspec-3.6.4/lib/inspec/plugin/v2/installer.rb:68:in `install'
	22: from /usr/local/bundle/gems/inspec-3.6.4/lib/inspec/plugin/v2/installer.rb:277:in `install_from_remote_gems'
	21: from /usr/local/bundle/gems/inspec-3.6.4/lib/inspec/plugin/v2/installer.rb:321:in `install_gem_to_plugins_dir'
	20: from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:298:in `install_into'
	19: from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:322:in `install_hooks'
	18: from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:322:in `each'
	17: from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:323:in `block in install_hooks'
	16: from /usr/local/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:55:in `generation_hook'
	15: from /usr/local/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:55:in `each'
	14: from /usr/local/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
	13: from /usr/local/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:189:in `generate'
	12: from /usr/local/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:189:in `chdir'
	11: from /usr/local/lib/ruby/2.6.0/rdoc/rubygems_hook.rb:190:in `block in generate'
	10: from /usr/local/lib/ruby/2.6.0/rdoc/rdoc.rb:414:in `parse_files'
	 9: from /usr/local/lib/ruby/2.6.0/rdoc/rdoc.rb:414:in `map'
	 8: from /usr/local/lib/ruby/2.6.0/rdoc/rdoc.rb:416:in `block in parse_files'
	 7: from /usr/local/lib/ruby/2.6.0/rdoc/rdoc.rb:360:in `parse_file'
	 6: from /usr/local/lib/ruby/2.6.0/rdoc/parser.rb:191:in `for'
	 5: from /usr/local/lib/ruby/2.6.0/rdoc/parser.rb:191:in `new'
	 4: from /usr/local/lib/ruby/2.6.0/rdoc/parser/ruby.rb:180:in `initialize'
	 3: from /usr/local/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:578:in `parse'
	 2: from /usr/local/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:346:in `get_squashed_tk'
	 1: from /usr/local/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:473:in `get_heredoc_tk'
/usr/local/lib/ruby/2.6.0/rdoc/parser/ripper_state_lex.rb:496:in `heredoc_end?': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by clintoncwolfe** [comment]
Looks like all plugins are now installing docs due to a change in Rubygems.
