### ISSUE TITLE
Add windows support for `inspec habitat` command

### ISSUE THREAD

**Issue by TheLunaticScripter** [inspec/inspec#3825]
### 🎛 Description

A 🙋 feature request to add a switch or something so that the `inspec habitat` command can support both a Linux and Windows plan.

The `inspec habitat` command is very useful in creating a habitat plan for Linux but not for Windows. It would be nice to be able to use a switch like `--platform` to create either a habitat plan for Linux or Windows.

### 🌍 InSpec and Platform Version

InSpec version 3.6.6

### 💁 Possible Solutions

Adding a Windows template to the plugin and then a switch for `--platform` or a query based on the `supports` tag in the `inspec.yml`.

**Comment by clintoncwolfe** [comment]
Ref #3818
