### ISSUE TITLE
Windows OS Detection

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#383]
Hi there

This might be related to issue #346 but I'm finding that the OS on my workstation is not being detected correctly

```
PS C:\> inspec detect
{"name":null,"family":"unix","release":null,"arch":null}
```

I'm using Windows 10 Version 1511 (OS Build 10586.63)

Thanks

Gary

**Comment by username-is-already-taken2** [comment]
I think this issue is affecting my ability to write and test certain resources

I've written a basic check to test the state of a service.

```
control 'winrm-service-1.0' do
  impact 1.0
  title 'Check the state of the winrm service'
  desc 'The winrm service should exists'
  describe service('WinRM') do
    it { should be_installed }
  end
end
```

Yet I get this

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Service WinRM The `service` resource is not supported on your OS yet.
     # Not yet implemented
     #

Finished in 0 seconds (files took 12.08 seconds to load)
1 example, 0 failures, 1 pending
```

Do you know if there is anyway I can force it (maybe within the inspec shell?) to windows?

Thanks 

Gary

**Comment by chris-rock** [comment]
@username-is-already-taken2 thanks for reporting this. This has high-priority for the next release

**Comment by chris-rock** [comment]
@username-is-already-taken2 I cannot error where InSpec is not able to detect the OS.

```
PS C:\Users\chris> systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10240 N/A Build 10240
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Phoenix Technologies LTD 6.00, 5/20/2014
PS C:\Users\chris> inspec version
0.9.9
PS C:\Users\chris> inspec detect
{"name":null,"family":"windows","release":"10","arch":null}
PS C:\Users\chris>
```

Could you paste the inspec version you are using?

**Comment by chris-rock** [comment]
In combination with a [fix in train](https://github.com/chef/train/pull/57), this works on my machine now. 

```
PS C:\Users\chris\inspec> cat ..\..\service_spec.rb
control 'winrm-service-1.0' do
  impact 1.0
  title 'Check the state of the winrm service'
  desc 'The winrm service should exists'
  describe service('WinRM') do
    it { should be_installed }
  end
end

PS C:\Users\chris\inspec> bundle exec ruby .\bin\inspec exec ..\..\service_spec.rb
.

Finished in 1 second (files took 1.94 seconds to load)
1 example, 0 failures

PS C:\Users\chris\inspec>
```

Please ensure you have `inspec 0.9.9` and `train 0.9.4` installed, otherwise it does not work properly if executed locally. The execution via WinRM was not affected.

**Comment by chris-rock** [comment]
username-is-already-taken2 Please reopen if this is still an issue
