### ISSUE TITLE
Telemetry - Opt In/Out

### ISSUE THREAD

**Issue by miah** [inspec/inspec#3849]
As a user I want to opt in or out of Telemetry Collection. I should be able to do this with command line arguments, as well as through a configuration file. I may want to configure this through the ENVIRONMENT too.

**Comment by clintoncwolfe** [comment]
Here's a screenshot of `hab` asking the user for opt-in:
![screen shot 2019-03-08 at 07 23 19](https://user-images.githubusercontent.com/156460/54028461-12904500-4173-11e9-8f11-ee161c2dcbcb.png)
