### ISSUE TITLE
`inspec-plugin-template` may be on plugin path, causing InSpec to crash

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3867]
### 🎛 Description

🐛 bug report

It's unlikely to affect many people, but it is possible that `lib/plugins/inspec-init/templates/plugins/inspec-plugin-template` may end up on the path(s) used to load plugins and will crash InSpec when it attempts to load the template as an actual plugin.

```
➜  my-project git:(james-stocks/update_windows) ✗ bundle exec inspec shell
bundler: failed to load command: inspec (/Users/jamesstocks/code/my-project/vendor/bundle/ruby/2.3.0/bin/inspec)
LoadError: cannot load such file -- <%= plugin_name %>/plugin
  /Users/jamesstocks/.inspec/plugins/inspec-whatever/vendor/bundle/ruby/2.3.0/gems/inspec-3.7.1/lib/plugins/inspec-init/templates/plugins/inspec-plugin-template/lib/inspec-plugin-template.rb:16:in `require'
  /Users/jamesstocks/.inspec/plugins/inspec-whatever/vendor/bundle/ruby/2.3.0/gems/inspec-3.7.1/lib/plugins/inspec-init/templates/plugins/inspec-plugin-template/lib/inspec-plugin-template.rb:16:in `<top (required)>'
  /Users/jamesstocks/code/my-project/vendor/bundle/ruby/2.3.0/gems/inspec-3.7.1/lib/inspec/plugin/v1/plugins.rb:59:in `require'
```

### 🌍 InSpec and Platform Version

3.7.1 via gem

### 🤔 Replication Case

 * Have an InSpec plugin project checked out on your workstation
 * Ensure the plugin has a Gemfile including inspec as a dependency and run `bundle install --path vendor/bundle` so that the inspec gem is pulled into a subdirectory
 * symlink the plugin project to `~/.inspec/plugins` so it is used by InSpec on your workstation
 * Run `inspec shell` or `detect` (or probably any command)

### 💁 Possible Solutions

Exclude gem bundles from plugin loading. Or exclude template files.
As a workaround for the replication case above (and probably good practice anyway), the bundled gems can be bundled outside of the project directory e.g. `bundle install --path ../bundles/inspec-whatever`

**Comment by clintoncwolfe** [comment]
`inspec plugin install path/to/some/plugin` is the intended way to do development.  I think the symlinking, vendoring, etc. is not supported in this use case.
