### ISSUE TITLE
Add Azure Application Gateway WAF Rules

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#3868]
🙋 feature request?

It would be great to have application gateway WAF rules support. 

Use Case: A Terraform change to our application gateway caused a config change without us realising it. Having these types of tests would enable us to catch these issues immediately.

**Comment by clintoncwolfe** [comment]
Hi! Thanks for the suggestion.  However, Azure resources are being developed on the the inspec/inspec-azure repo.  Please make your suggestion there.  Thanks!
