### ISSUE TITLE
registry_key seems to ignore regex on children

### ISSUE THREAD

**Issue by wiskaso** [inspec/inspec#3872]
### 🎛 Description

**Choose one:** 🐛 bug report

I’m basically using a very vanilla Windows box and wrote a control like this:
```
control "19.1.3.4" do
    registry_key({hive: 'HKEY_USERS'}).children(/^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}\\Software\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop/).each { |entry|
      describe registry_key(entry) do
        it { should exist }
        it { should have_property "ScreenSaveTimeOut" }
        its("ScreenSaveTimeOut") { should be <= 900 }
        its("ScreenSaveTimeOut") { should be >= 1 }
      end
    }
  end
```

Now on this system the screen saver isn’t enabled so I would expect this to fail.. but for whatever reason.  I’m getting this:
```
Registry Key HKEY_USERS\S-1-5-21-400010262-365836842-3094829221-500\Software\Policies\Microsoft\Windows\Control Panel\Desktop
  should exist (FAILED - 4387)
  should have property "ScreenSaveTimeOut" (FAILED - 4388)
  ScreenSaveTimeOut
    should be <= 900 (FAILED - 4389)
  ScreenSaveTimeOut
    should be >= 1 (FAILED - 4390)

Registry Key HKEY_USERS\S-1-5-21-400010262-365836842-3094829221-500\AppEvents\Software\Policies\Microsoft\Windows\Control Panel\Desktop
  should exist (FAILED - 4391)
  should have property "ScreenSaveTimeOut" (FAILED - 4392)
  ScreenSaveTimeOut
    should be <= 900 (FAILED - 4393)
  ScreenSaveTimeOut
    should be >= 1 (FAILED - 4394)

Registry Key HKEY_USERS\S-1-5-21-400010262-365836842-3094829221-500\AppEvents\EventLabels\Software\Policies\Microsoft\Windows\Control Panel\Desktop
  should exist (FAILED - 4395)
  should have property "ScreenSaveTimeOut" (FAILED - 4396)
  ScreenSaveTimeOut
    should be <= 900 (FAILED - 4397)
  ScreenSaveTimeOut
    should be >= 1 (FAILED - 4398)
```
This happens thousands of times as it tests paths that don’t seem to match the regex.  Am I just misunderstanding the use of the children matcher?

The system has 1 user and makes this control alone take 10 minutes to complete.

```
Registry Key HKEY_USERS\S-1-5-21-400010262-365836842-3094829221-500_Classes\Wow6432Node\CLSID\Software\Policies\Microsoft\Windows\Control Panel\Desktop
  should exist (FAILED - 10143)
  should have property "ScreenSaveTimeOut" (FAILED - 10144)
  ScreenSaveTimeOut
    should be <= 900 (FAILED - 10145)
  ScreenSaveTimeOut
    should be >= 1 (FAILED - 10146)
``` 
That is the last time the failure was logged to my documentation file output.

### 🌍 InSpec and Platform Version

```
[vagrant@localhost ~]$ inspec version
3.6.6

Your version of InSpec is out of date! The latest version is 3.7.1.
 [vagrant@localhost ~]$
 [vagrant@localhost ~]$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

### 🤔 Replication Case
Target host is a Windows 2008 R2 server with PS 5.1 installed.

inspec exec profile -t winrm://windowshost --user username --password 'password' --reporter documentation:file.txt

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
