### ISSUE TITLE
add "projects" to pass through metadata

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#3874]
### 🎛 Description

 🙋 feature request

in order to complete the rbac work being done in automate, we're going to need to pass a field called `projects` through on reports, with an array of strings as the value (`projects: ['foo', 'bar']`).
https://github.com/inspec/inspec/blob/master/lib/inspec/reporters/automate.rb#L31

note: while we're at it, maybe correcting the spelling on `recipes` would be good? I don't actually make use of the roles or recipes fields there, just noticed the spelling there.

### 🌍 InSpec and Platform Version

3.7.1

**Comment by clintoncwolfe** [comment]
Where is the value to be passed through desired to be passed in?  Is this through a command line argument, or in the JSON-formatted config file?

**Comment by vjeffrey** [comment]
the JSON-formatted config file

**Comment by clintoncwolfe** [comment]
refs #3181

**Comment by clintoncwolfe** [comment]
OK, I've had a look at this.  @vjeffrey what would you think about, instead of adding `properties` at the top-level, we add `passthrough` at the top-level, and you can put anything you want in there, and InSpec will echo it back, under a top-level key 'passthrough'? 

This approach would do two things:
 1. Eliminate the need to modify InSpec when A2 wants another passthru field
 2. Stop polluting the top-level namespace

**Comment by vjeffrey** [comment]
I like the idea of having a `passthrough` field that we could add anything we want to. the two points you mentioned are definitely good to have.
**however**, that would be a breaking change for Automate.
why?
because our elasticsearch mappings expect certain fields, like node_name, job_id, environment, and projects to be at the top level of the report. changing this would require us to support both formats - the properties being included at the top level _and_ the properties being included in the passthrough field.
that said, i still think passthrough is the way to go.

how would people feel about adding projects to the top level, and then slowly migrating to the passthrough method in the near future? 

another approach could be adding projects to the passthrough only, and keeping the other fields top level _and_ in passthrough. we could modify Automate to check both top level and passthrough for the fields. this could work for us as long as we're careful about checking for those fields.

**Comment by clintoncwolfe** [comment]
I did not intend to suggest that existing top-level fields `node_name`, `job_uuid`, `environment`, and `roles` be moved. I agree we should move toward that in the future.

I will implement a new top-level field, `passthrough`.  If you send a configuration file like this:

```
{
  "reporter": {
    "automate": {
      "passthrough":{
        "projects": [ "alpha", "beta"],
        "anything": "some_other_value",
      },
    },
  },
  # other options
} 
```

Then the top-level fields `node_name`, `job_uuid`, `environment`, `roles`, and `passthrough` will be available. `passthrough` will contain anything you placed in the config file. If you would like me to place a copy of `node_name`, `job_uuid`, `environment`, and `roles` in there as well, please let me know.

I will also remove 'recipies' as you mentioned it is not currently used, as well as misspelled.

This really should be versioned eventually, as proposed on #3905, but that is a project for another day.
