### ISSUE TITLE
Detect windows also with ssh transport

### ISSUE THREAD

**Issue by StefanScherer** [inspec/inspec#3888]
### 🎛 Description

🐛 bug report

InSpec can be used for Windows targets, but it seems that this works only if the communication is down via WinRM. I want to be able to use InSpec with a SSH connection to a Windows target machine.
This doesn't work at the moment and InSpec terminates with an error "Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)".

### 🌍 InSpec and Platform Version

3.7.1
macOS 10.14.3

### 🤔 Replication Case

I found the problem when I wanted to use InSpec with the new release of Packer 1.3.5, but not while building a Linux VM, but instead a Windows VM.
The Packer InSpec plugin creates a local SSH agent to tunnel the commands to the Packer communicator. For the InSpec command it is effectively a Windows SSH session.

See https://github.com/hashicorp/packer/issues/7364

But any Windows machine with OpenSSH (eg. the version from Microsoft) installed can be used to reproduce the problem. I've tried that for the stacktrace below.

### 💁 Possible Solutions

I had a look at the code and adjusted the inspec/train gem to work with a Window SSH connection and sent a pull request https://github.com/inspec/train/pull/416

### 💻 Stacktrace

```
$ inspec exec my_win10 --backend ssh --host 172.16.208.144 --user vagrant
Traceback (most recent call last):
	19: from /usr/local/bin/inspec:121:in `<main>'
	18: from /usr/local/bin/inspec:121:in `load'
	17: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/bin/inspec:12:in `<top (required)>'
	16: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/inspec/cli.rb:262:in `exec'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/inspec/cli.rb:262:in `new'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/inspec/runner.rb:64:in `initialize'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/inspec/runner.rb:72:in `configure_transport'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.7.1/lib/inspec/backend.rb:52:in `create'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/transports/ssh.rb:81:in `connection'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/transports/ssh.rb:208:in `create_new_connection'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/transports/ssh.rb:208:in `new'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/transports/ssh_connection.rb:53:in `initialize'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/extras/command_wrapper.rb:173:in `load'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/plugins/base_connection.rb:110:in `platform'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/platforms/detect.rb:9:in `scan'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/train-1.7.4/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
```

**Comment by clintoncwolfe** [comment]
Refs https://github.com/inspec/train/pull/416

**Comment by clintoncwolfe** [comment]
I think all work for this will occur in train; I'm going to close this. Please do re-open if I am mistaken.

**Comment by StefanScherer** [comment]
@clintoncwolfe Do we want to re-open this issue to track the bug with a bugfix PR that updates train to version 2.1.0 with the better Window detection?
