### ISSUE TITLE
OS detection on debian does not detect versions

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#39]
The new OS detector does not play nice with Debian yet. detect.rb returns the following data:

``` json
{"os_name":null,"os_family":"debian","os_release":null,"os_arch":"x86_64"}
```

The version is missing.

**Comment by arlimus** [comment]
Ouch, can you provide the Debian version you are testing?

Right now, using the the new detect mode via docker backend, I tested these:

``` json
{"os_name":null,"os_family":"debian","os_release":"6.0.10","os_arch":null}
{"os_name":null,"os_family":"debian","os_release":"7.9","os_arch":null}
{"os_name":null,"os_family":"debian","os_release":"8.1","os_arch":null}
```

**Comment by chris-rock** [comment]
Problem identified: only occurs with specinfra backend
