### ISSUE TITLE
profiles with git dependencies on CentOS fail upload to Chef Automate

### ISSUE THREAD

**Issue by v-cardoso** [inspec/inspec#3900]
### 🎛 Description

 🐛 bug report

Description of issue: On a CentOS 7 system, Uploading a profile to Chef Automate that contains a "git" dependency returns success, but the profile is never uploaded.

Expected behavior: Profile should be correctly uploaded to Chef Automate

[Full process without debug](https://gist.github.com/vdvcardoso/39a2d1cedc2bb2da344259579c6701db)

[Vendor debug output](https://gist.github.com/vdvcardoso/5079b2fc1de81384407d4d0eea0d59ae)
[Failed upload debug output](https://gist.github.com/vdvcardoso/96ca57cd0948ec0bbd1ae793a9e27321)
[Successful upload debug output](https://gist.github.com/vdvcardoso/caeccd0e0e31686ab92a0b9ac67a0b97)

Workaround:
1. Modifying the inode of "inspec.yml" (open with vi, type ":wq") and re-upload results in a successful upload.
2. Renaming "inspec.yml" to a different name, and renaming it back and re-upload results in a successful upload.

### 🌍 InSpec and Platform Version
inspec 3.7.1
CentOS Linux release 7.6.1810 (Core)

### 🤔 Replication Case
0. Login to Chef Automate using inspec 
`inspec compliance login $automate_url --user=$user --ent=$ent --token=$token`
1. Create a new inspec profile
2. In "inspec.yml" set a dependency to a profile stored on github
`Or use the profile found` [here](https://github.com/vdvcardoso/inspecCentos/tree/master/profiles/linux-inspec)
3. Vendor the profile
`inspec vendor $path_to_profile`
4. Attempt to upload the profile
`inspec compliance upload path_to_profile`
5. Verify the profile was not uploaded
`inspec compliance profiles`
##### Workaround
6. Rename "inspec.yml" to a different name like "inspec.yml.bak"
`mv /path/to/profile/inspec.yml /path/to/profile/inspec.yml.bak`
7. Rename "inspec.yml.bak" back to "inspec.yml"
`mv /path/to/profile/inspec.yml.bak /path/to/profile/inspec.yml`
8. Upload the profile
`inspec compliance upload path_to_profile`
9. Verify the profile is correctly updated
`inspec compliance profiles`

### 💻 Stacktrace

[Vendor trace](https://github.com/vdvcardoso/inspecCentos/blob/master/traces/vendor_strace.txt)
[Failed upload trace](https://github.com/vdvcardoso/inspecCentos/blob/master/traces/upload_strace.txt)
[Successful upload trace](https://github.com/vdvcardoso/inspecCentos/blob/master/traces/upload_newinode_strace.txt)
[inotify resultst](https://gist.github.com/vdvcardoso/fd074b5173f55a88995e72bb27143519)

**Comment by miah** [comment]
I suspect there might be a timing issue or race condition happening here. Could you try doing this with a added sleep?

something like:

`inspec compliance upload linux-inspec --log-level=debug && sleep 120 && inspec compliance profiles`

**Comment by kekaichinose** [comment]
Moving to Blocked as @miah is dealing with support escalation #4203

**Comment by kekaichinose** [comment]
@vdvcardoso per @miah's comment, can you try and add the sleep and see if you're able to repro? I'll close this as there was no follow-up from the earlier ask. If you're still seeing an issue, feel free to open a new issue with updated repro steps.

Thanks!
__Chef InSpec Team__
