### ISSUE TITLE
Interface resource doesn't implement the name property

### ISSUE THREAD

**Issue by wilrodriguez** [inspec/inspec#3920]
### 🎛 Description

**Choose one:** 🐛 bug report

According to the [documentation](https://www.inspec.io/docs/reference/resources/interface/), there are two parameters for the interface resource, speed and name. Well, it turns out that there's no method to expose the name property, even though it is available in `@interface_provider` from both of the platform providers.

### 🌍 InSpec and Platform Version

3.9.0-1.el7

### 🤔 Replication Case

This example from the documentation doesn't work, it'll result in an undefined method exception:

```ruby
describe interface('eth0') do
  it { should be_up }
  its('speed') { should eq 1000 }
  its('name') { should eq eth0 }
end
```

### 💁 Possible Solutions

Implement a name method for interface. There's probably a sketchy way for me to do this without modifying the source code of the resource... but I don't know how.

### 💻 Stacktrace

```
     ×  Interface eth0 name
     undefined method `name' for Interface eth0:#<Class:0x0000000003934a10>
```

**Comment by apr-1985** [comment]
Just spent ages trying to work out why this wasn't working when it is a documented example :(
At least remove it from the example till this bug is fixed properly
