### ISSUE TITLE
Filesystem resource doesn't work on RHEL 5/6 systems with long filesystem names

### ISSUE THREAD

**Issue by wilrodriguez** [inspec/inspec#3921]
### 🎛 Description

**Choose one:** 🐛 bug report

The filesystem resource tends to break on RHEL 5/6 for devices with a long filesystem name, due to the filesystem wrapping to the next line. This behavior is easily avoidable by adding the `-P` (portable) option to the `df` command that is executed in `LinuxFileSystemResource`

### 🌍 InSpec and Platform Version

3.9.0 on RHEL 5/6/7

### 🤔 Replication Case

On RHEL 7, if you have a long device name, it renders on one line, the way inspec expects, like so:
```
Filesystem                  Type 1K-blocks   Used Available Use% Mounted on
/dev/mapper/root_vg-root_lv xfs    2086912 807600   1279312  39% /
```

But on RHEL 5/6, it renders on two lines, like so:
```
Filesystem    Type   1K-blocks      Used Available Use% Mounted on
/dev/mapper/root_vg-root_lv
              ext3     1904472    972532    833636  54% /
```
Which means that the values that the existing code in `LinuxFileSystemResource` is pulling results in:

`["/dev/mapper/root_vg-root_lv"]`

Instead of (generated by using the existing logic, but changing the command to `df #{partition} -TP`):

`["/dev/mapper/root_vg-root_lv", "ext3", "1904472", "972372", "833796", "54%", "/"]`

### 💁 Possible Solutions

Change [lib/resources/filesystem.rb Line 95](https://github.com/inspec/inspec/blob/master/lib/resources/filesystem.rb#L95) to `cmd = inspec.command("df #{partition} -TP")` (add the P to the end)

### 💻 Stacktrace
```
     ×  FileSystem / percent_free
     divided by 0
```

**Comment by e-mow** [comment]
Just ran into this as well and was going to open a bug. Glad to see someone else has already opened it with the same fix that I was going to suggest.

+1 on the bug.
