### ISSUE TITLE
Feature Request: OS resource should include a End-of-Life option

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#3923]
### 🎛 Description
 🙋 Would love to have a OS resource option that would tell me a system is End-of-Life

### 💁 Possible Solutions

```
describe os.release do
   it { should_not be_eol }
end
```

**Comment by clintoncwolfe** [comment]
Thanks for the idea, but keeping a database of when a particular OS is EOL, or what that specifically means for a particular OS vendor, is well out of scope for the core InSpec project. 

It does sound like a great idea for a resource pack, perhaps providing an interface to an external source of such data.
