### ISSUE TITLE
Improve SSH Sudo Inspec Checks Error Output

### ISSUE THREAD

**Issue by sean-horn** [inspec/inspec#393]
The results are different for the `file` inspec resource when running identical checks against identical systems when the failing system happens to be remote.

Most/all of the checks one would reasonably do against a remote sshd/ssh config are similarly afflicted.
## Versions

```
cat /etc/centos-release
CentOS release 6.7 (Final)

head -1 /opt/chef-compliance/version-manifest.txt
chef-compliance 0.9.11

/opt/chef-compliance/embedded/bin/inspec version
0.9.10
```
## Testing

If I do an inspec run local to the compliance server with the [1] test.rb file shown below, I get a successful run

```
/opt/chef-compliance/embedded/bin/inspec exec test.rb
..

Finished in 0.01783 seconds (files took 0.53516 seconds to load)
2 examples, 0 failures
```

If I do the identical run against a remote CentOS 6.7 system, inspec blows up on both checks

```
/opt/chef-compliance/embedded/bin/inspec exec test.rb -t ssh://dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem
FF

Failures:

  1) File /etc/ssh/ssh_config mode should eq 420
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: 420
            got: nil

       (compared using ==)
     # test.rb:2:in `block (2 levels) in load'

  2) File /etc/ssh/ssh_config mode should cmp "0644"
     Failure/Error: actual = '0' + actual.to_s(8) if octal?(expected)

     ArgumentError:
       wrong number of arguments (1 for 0)
     # test.rb:6:in `block (2 levels) in load'

Finished in 0.01753 seconds (files took 0.71213 seconds to load)
2 examples, 2 failures

Failed examples:

rspec  # File /etc/ssh/ssh_config mode should eq 420
rspec  # File /etc/ssh/ssh_config mode should cmp "0644"
```
## [1] test.rb

```
describe file('/etc/ssh/ssh_config') do
    its('mode') { should eq 0644 }
end

describe file('/etc/ssh/ssh_config') do
    its('mode') { should cmp '0644' }
end
```

**Comment by alexpop** [comment]
Hi Sean, thanks for the bug report. Did you have any test succeed on that remote system?

I tried to reproduce this issue with your `test.rb` from the same source machine against a local CentOS 6.7 VM and an ec2 RHEL 7.2 instance. No issue. Here's what I've got:

```
[root@kitchen-cc bin]# cat /etc/redhat-release
CentOS release 6.7 (Final)

[root@kitchen-cc bin]# head -1 /opt/chef-compliance/version-manifest.txt
chef-compliance 0.9.11

[root@kitchen-cc bin]# head -1 /opt/chef-compliance/version-manifest.txt
chef-compliance 0.9.11

[root@kitchen-cc bin]# /opt/chef-compliance/embedded/bin/inspec version
0.9.10

[root@kitchen-cc bin]# /opt/chef-compliance/embedded/bin/inspec exec test.rb
..

Finished in 0.01592 seconds (files took 0.53998 seconds to load)
2 examples, 0 failures

[root@kitchen-cc bin]# /opt/chef-compliance/embedded/bin/inspec exec test.rb -t ssh://lexa@52.49.23.120 -i ~/.ssh/id_rsa
..

Finished in 0.0373 seconds (files took 1.27 seconds to load)
2 examples, 0 failures

zlib(finalizer): the stream was freed prematurely.

[root@kitchen-cc bin]# ssh lexa@52.49.23.120 -i ~/.ssh/id_rsa 'ls -la /etc/ssh/ssh_config'
-rw-r--r--. 1 root root 2208 Jan 13 10:22 /etc/ssh/ssh_config

[root@kitchen-cc bin]# ssh lexa@52.49.23.120 -i ~/.ssh/id_rsa 'cat /etc/redhat-release'
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

I'm trying with a RHEL 6 in ec2 now...

**Comment by alexpop** [comment]
RHEL 6 remote instance:

```
[root@kitchen-cc bin]# ssh lexa@52.31.84.50 -i ~/.ssh/id_rsa 'cat /etc/redhat-release'
Red Hat Enterprise Linux Server release 6.5 (Santiago)

[root@kitchen-cc bin]# /opt/chef-compliance/embedded/bin/inspec exec test.rb -t ssh://lexa@52.31.84.50 -i ~/.ssh/id_rsa
..

Finished in 0.08808 seconds (files took 1.95 seconds to load)
2 examples, 0 failures

zlib(finalizer): the stream was freed prematurely.

[root@kitchen-cc bin]# ssh lexa@52.31.84.50 -i ~/.ssh/id_rsa 'ls -la /etc/ssh/ssh_config'
-rw-r--r--. 1 root root 2047 Sep 30  2013 /etc/ssh/ssh_config
```

Can you run these two commands on your compliance server?

```
ssh dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem 'cat /etc/redhat-release'
ssh dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem 'ls -la /etc/ssh/ssh_config'
```

**Comment by alexpop** [comment]
Please also attach the `/etc/sudoers`file and `/etc/sudoers.d/` contents from `rhel6-compliance1`

**Comment by chris-rock** [comment]
@sean-horn you are using "inspec exec test.rb -t ssh://dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem". It may be possible that the user `dev-lxc` has no access to `/etc/ssh/ssh_config`. Try the `--sudo` option.

To verify that everything works without inspec:

```
dev-lxc@rhel6-compliance1
cat /etc/ssh/ssh_config
```

If you receive a permission error, the user is not able to read the file. If that is the case we need to improve our error output.

**Comment by sean-horn** [comment]
On the rhel-compliance1 target, I see the following

```
cat /etc/redhat-release
CentOS release 6.7 (Final)

ls -al /etc/ssh/ssh*_config
-rw-r--r-- 1 root root 2016 Jan 27 16:51 /etc/ssh/ssh_config
-rw------- 1 root root 3879 Aug 13 05:58 /etc/ssh/sshd_config
```

Ahhh, thanks for the tip. The dev-lxc user is denied read access to /etc/ssh/ssh_config, but should be able to sudo and cannot.

When I configure sudo with no password in the Compliance console, the system is unable to connect and gives the message

```
Failed to verify connectivity to sshKey://dev-lxc@rhel6-compliance1.lxc:0 using login key dcia-admin/rhel6keypair : exit status 1
```

The following attached files should show that dev-lxc ought to be able to sudo
[sudoer-stuff.zip](https://github.com/chef/inspec/files/108687/sudoer-stuff.zip)

And....I just commented this line out in the /etc/sudoers file :|

```
ssh dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem 'sudo grep require /etc/sudoers'
#Defaults    requiretty
```

And was able to proceed a little further both on the command line and Compliance dashboard. More tests are now marked Compliant. As I get time, I'll go through more of the base/ssh checks to make sure

```
/opt/chef-compliance/embedded/bin/inspec exec test.rb -t ssh://dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem --sudo
....

Finished in 0.02888 seconds (files took 0.75177 seconds to load)
4 examples, 0 failures

zlib(finalizer): the stream was freed prematurely.
```

Here's the output of the run when `Defaults requiretty` is not commented out

```
/opt/chef-compliance/embedded/bin/inspec exec test.rb -t ssh://dev-lxc@rhel6-compliance1 -i /root/dev/rhel6keypair.pem --sudo
/opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/r-train-0.9.5/lib/train/extras/command_wrapper.rb:131:in `load': Sudo failed:  sudo: sorry, you must have a tty to run sudo (Train::UserError)
    from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/r-train-0.9.5/lib/train/transports/ssh_connection.rb:45:in `initialize'
```

I think the take away from this ticket is improving the error messages to make it more obvious what's happening with the remote system's sudo setup, as @chris-rock suggests. Thanks for helping me get setup to test the actual problem :smile: I'll change the title to reflect the intent.

**Comment by clintoncwolfe** [comment]
There are many things that could go wrong here, from file permissions to SELinux contexts to TTY requirements - and I don't think InSpec would be able to differentiate those cases.  If there  is desire for this feature, let's open a new issue to focus on that.
