### ISSUE TITLE
Expose full winrm transport options in inspec cli

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#3933]
### 🎛 Description
🙋 feature request?

Working with a few of our teams / customers. We are doing inspec evalutations of windows systems and the concern of exposing `--password` on the CLI has come up. 

In reviewing the train and winRM gems it seems that the supporting auth methods negociate, ssl, kerberos, and plaintext are coded into the WinRM gem and Train gems already. 

I would like to expose those existing options on the inspec cli and document examples of using those authentication methods which could allow us to provide `inspec exec` examples that would not require us to expose the user password.

- https://github.com/WinRb/WinRM#transports
- https://github.com/inspec/train/blob/master/lib/train/transports/winrm.rb#L51

The end goal the users would like to see is that:
- train / inspec obfuscateses the password in the run and the reports and cli reporter
- train / inspec could consume the existing user creds from the windows login if no user and passoword are provided
- tain / inspec could prompt for the password if they just provide a local or domain user is provided
- train / inspec could perhaps use the Kerberos TGT that exists in the Windows security integration

### 💁 Possible Solutions

expose cli options to use existing winrm authencation in the inspec cli.

**Comment by aaronlippold** [comment]
To make this stable we would have to add a `--prompt-password` flag so that the default behavior is still to error out when `--password` is not supplied.

**Comment by aaronlippold** [comment]
This could really be a useful thing for all transports if we could add a password prompt that has `********` as you type etc. 

We run into this a lot as we are screen sharing with customers etc.

**Comment by nqb** [comment]
See also #2413 on same subject.

**Comment by clintoncwolfe** [comment]
I believe all of this (aside from input masking) would be covered under https://github.com/inspec/inspec/issues/3681, which proposes:

 * allowing inspec to list all options for all transports (train can do that, just a matter of connecting the dots)
 * allow inspec to expose every internal Tranport Option as a (prefixed) CLI option

**Comment by clintoncwolfe** [comment]
Let's open two new issues (or check for existing ones) for
 * prompting for missing but required options
 * input masking for prompted sensitive options

**Comment by aaronlippold** [comment]
Agreed
