### ISSUE TITLE
Misalignment of impact levels to numeric values

### ISSUE THREAD

**Issue by adamday2** [inspec/inspec#3945]
### 🎛 Description

The documentation describes that the impact values are based on CVSS, but do not align correctly the CVSS. The cutoff for low should be 0.1, not 0.01.

InSpec - https://www.inspec.io/docs/reference/dsl_inspec/
> 0.0 to <**0.01** these are controls with no impact, they only provide information
0.01 to <0.4 these are controls with low impact
0.4 to <0.7 these are controls with medium impact
0.7 to <0.9 these are controls with high impact
0.9 to 1.0 these are critical controls

https://github.com/inspec/inspec/blob/1c12a544c76b71d1805579fd91cfb845b5f2be53/lib/inspec/impact.rb#L7

CVSS -https://nvd.nist.gov/vuln-metrics/cvss
> Severity | Base Score Range
None | 0.0
Low | **0.1**-3.9
Medium | 4.0-6.9
High | 7.0-8.9
Critical | 9.0-10.0

**Choose one:**
Bug Report

### 🌍 InSpec and Platform Version

3.9.0

**Comment by clintoncwolfe** [comment]
Thanks for the great description!

**Comment by clintoncwolfe** [comment]
Fixed on #3961

**Comment by adamday2** [comment]
Thanks for fixing this @aaronlippold !
