### ISSUE TITLE
Check whether there is a running instance with a given name, even when there is a terminated instance of the same name

### ISSUE THREAD

**Issue by kief** [inspec/inspec#3949]
### 🎛 Description
 🙋 feature request?

Given that I have terminated and recreated an ec2 instance with a particular name, I want to check that the new instance is running. However, the aws_ec2_instance resource may select the terminated instance, so that the matchers return results on that.

The aws_ec2_instances resource does not provide a way to filter on instances by either name or status, so I can't see how to use that for this.

My use case for this is testing and development of infrastructure code. I frequently make changes that involve rebuilding a server.

### 🌍 InSpec and Platform Version

I'm using Inspec 3.9.3 on MacOS 10.14.4

### 🤔 Replication Case

Control server.rb:
```
describe aws_ec2_instance(name: 'my-server') do
  it { should be_running }
end
```
Create an ec2 instance with the Name tag set to 'my-server'. Run the inspec control, it should pass. Terminate the instance. Create a new instance with the same Name. Run the inspec control. It may(?) fail.

It usually fails for me, but it might not if the AWS API returns the running instance first in the results.

### 💁 Possible Solutions

The issue is that the aws_ec2_instance resource assumes there will only ever be one instance with a given name, which is not the case. When it isn't the case, the results of matchers are not what is expected, and it may be difficult for developers to determine why. So I'm not sure how the resource should be changed to, at the least, make it visible that this assumption has been violated.

The best solution to my use case is probably to modify the aws_ec2_instances resource so that it can filter based on name and/or instance status.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #119](https://github.com/inspec/inspec-aws/issues/119) via [**ZenHub**](https://www.zenhub.com/)
