### ISSUE TITLE
Add Windows support for the http resource

### ISSUE THREAD

**Issue by nellshamrell** [inspec/inspec#3959]
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Feature request, though this feature request came from a Bug Report in #2822

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

A user should be able to use the http resource on windows.

i.e. 

```
describe http('http://localhost:8080', enable_remote_worker: true) do
  its('body') { should match /Tomcat/ }
end
```

should run successfully on Windows, rather than returning an unsupported platform error.

Aha! Link: https://chef.aha.io/features/SH-2620

**Comment by lmayorga1980** [comment]
I get the same error on Windows 2019 Server.

```ruby
describe http('http://localhost', enable_remote_worker: true) do
  its('status') { should cmp 200 }
  its('body') { should contain 'www.mysite.com' }
end
```

` [FAIL]  Resource `http` is not supported on platform windows_server_2019_standard/10.0.17763.`

This worked for me ...

```ruby
describe command('curl http://localhost -UseBasicParsing') do
  its('stdout') { should include "www.mysite.com" }
  its('stderr') { should eq '' }
  its('exit_status') { should eq 0 }
end
```
**output**
```
  Command: `curl http://localhost -UseBasicParsing`
     [PASS]  stdout should include "www.mysite.com"
     [PASS]  stderr should eq ""
     [PASS]  exit_status should eq 0
```

**Comment by clintoncwolfe** [comment]
Implementation notes: as this is done through the remote executioner, we basically either need to assume curl is installed on a Windows machine (as the existing solution is curl-based) or develop a PowerShell solution that is as feature-rich.

**Comment by james-stocks** [comment]
I think we can't assume curl (as in curl.exe) is available.
`curl` (cmdlet) is always available in PowerShell as an alias to `Invoke-WebRequest` - we'll probably need to write new code that works with that.

**Comment by mbaitelman** [comment]
I'm writing this up using Invoke-WebRequest. 
Is there a preference in how to handle multi-platform code? 
Just if/else everwhere, one giant if/else for the whole file or 2 different files for each.

**Comment by Schwad** [comment]
Hi @mbaitelman ! 👋 

Great question. If you look through the `lib/inspec/resources` directory generally and search for `windows?` it appears the most common pattern is to utilize `if/elsif os.windows?`, and if unsupported something like `return skip_resource "The `such_and_such` resource is currently not supported on Windows." if inspec.os.windows?`.

I do think as a personal view that it's helpful to use `if` or `case` statements inside the resource because it clearly communicates to us in the future how the resource is run on various platforms. 👍  Cheers!

**Comment by mbaitelman** [comment]
This issue has been addressed and the resource was updated

**Comment by Vasu1105** [comment]
Yes we have added that in #5697  so closing this one.
