### ISSUE TITLE
Add support for AWS DynamoDB

### ISSUE THREAD

**Issue by robkinyon-roivant** [inspec/inspec#3964]
### 🎛 Description

This is 🙋 feature request

Please support AWS DynamoDB.

### 🌍 InSpec and Platform Version

Running Inspec 3.9.3 (packaged with ChefDK 3.9.0) on AmazonLinux/2

### 🤔 Replication Case

Feature is not documented in https://www.inspec.io/docs/reference/resources/

### 💁 Possible Solutions

This should be a similarly sized PR as adding AWS SQS Queue in https://github.com/inspec/inspec/pull/3674

**Comment by clintoncwolfe** [comment]
Thanks for the request!  However, all new work on AWS resources for InSpec will be performed at [inspec/inspec-aws](https://github.com/inspec/inspec-aws). This repository (inspec/inspec) is no longer accepting contributions for AWS work. This allows the inspec-aws project to proceed at a faster, more independent pace than the main InSpec project.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #81](https://github.com/inspec/inspec-aws/issues/81) via [**ZenHub**](https://www.zenhub.com/)
