### ISSUE TITLE
Improve website+docs Rake tasks

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3966]
### 🎛 Description

The procedure for releasing the website is problematic:

 * It uses a separate Rakefile, though some tasks are shared with the Docs tasks. This is confusing.
 * It has a separate gemfile, which is deeply crufty
 * during execution, it switches the repo to the `gh_pages` branch.
   * If an error occurs, you are stuck on that branch
   * The source code for the task is not on that branch, making debugging hard
   * you can't preview work without committing it
 * The instructions want you manually start up a WeBrick server to preview the side; that could easily be automated
 * (Maybe not a bad thing) it stops and challenges you for confirmation before pushing
 * pushing to the website is a separate procedure than regular CI/CD.
 * The instructions are in a private, now read-only repo

See instructions here: https://github.com/chef/compliance-team/blob/master/maintaining-inspec.md#the-inspecio-website

**Comment by kekaichinose** [comment]
This needs a team chat.

**Comment by kekaichinose** [comment]
How much of this have we gotten fixed? I feel like we've already taken care of a couple of these...

**Comment by james-stocks** [comment]
Going to close this since @inspec/docs-team have done a complete overhaul
