### ISSUE TITLE
Move plugin install tests from unit to functional

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3974]
### 🎛 Description

The unit tests for the inspec-cli-plugin-manager currently perform live-fire installs, upgrades, and uninstalls of gems. This is slow, surprising, noisy (#3742), and requires network connectivity.

### 🌍 InSpec and Platform Version

3.9.x
4.1.x

### 🤔 Replication Case

`bundle exec rake test`

### 💁 Possible Solutions

Determine if the functional tests include such tests.  If not, move the testing there.

Rework the unit tests to stub out the calls.

**Comment by zenspider** [comment]
After studying the tests, these are functional tests. Granted, they're not well isolated, but they do test the classes/methods directly so I think we should keep them. I've marked a number of the slow and noisy ones with a skip such that they will be run only on the CI (or if you set SLOW=1 in your env) and the test time went down to ~0.5s with no noisy output.

See #4031 for more.
