### ISSUE TITLE
Switch from jsonschema to json-schema?

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4002]
jsonschema was last released in 2012 and emits warnings on load.

json-schema was last released in Oct 2018 and has ~16m downloads. It is probably a much better bet for us in the long term.

**Comment by clintoncwolfe** [comment]
It is entirely possible that nothing is consuming the schema we store, and we may not need this functionality at all - need to check with the A2 team.

**Comment by aaronlippold** [comment]
We use it

**Comment by clintoncwolfe** [comment]
@aaronlippold Could you expand a bit - I'm curious as to what exactly your use case is?

**Comment by zenspider** [comment]
A cursory check suggests we might be able to switch over with something as simple as:

```ruby
module JSON
  class Schema
    def self.validate data, schema=nil, _=nil
      JSON::Validator.validate schema, data
    end
  end
end
```

**Comment by aaronlippold** [comment]
https://vuejsexamples.com/schema-based-form-generator-vue-js-2-0-component-based-on-vuetify/

Would be an example of how we plan to use it as well as possibly connections to graph QL and other things. Fundamentally it's very nice to be able to view what the current standard scheme is are for the date of structures of inspec. Is there a particular challenge in maintaining them, we have to maintain them either way don't we?

**Comment by miah** [comment]
We aren't talking about removing the JSON Schemas, just changing the library we use. InSpec needs to define schemas for json files in our configuration, our interaction with automate, and telemetry endpoints.

**Comment by miah** [comment]
I'm going to close this as I did the work. The next steps will be to utilize json-schema for defining JSON schemas inside InSpec =)
