### ISSUE TITLE
Support checking for server timezone settings

### ISSUE THREAD

**Issue by Bak3y** [inspec/inspec#4013]
### 🎛 Description
🙋 feature request?

### 🌍 InSpec Version
Inspec version 3.9.0

Requesting a resource to check for timezone configuration.  Currently we're having to resort to this:

```
control "time-2" do
    impact 1.0
    title "Verify timezone is America/Chicago"
    describe bash('timedatectl status | grep Chicago') do
        its('stdout') { should include 'Time zone: America/Chicago (CDT, -0500)' }
        its('stderr') { should eq '' }
        its('exit_status') { should eq 0 }
    end
end
```

It'd be nice if there was a native resource to check for various time settings including timezone.

**Comment by qubitrenegade** [comment]
This would definitely be a useful feature!
