### ISSUE TITLE
Update 2 deprecated resources with sunsetting info

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4021]
```
1908 % ag "removed in InSpec" docs
docs/resources/apache.md.erb
10:<p class="warning">This resource is deprecated and should not be used. It will be removed in InSpec 3.0.</p>

docs/resources/azure_generic_resource.md.erb
7:<p class="warning">This resource is deprecated and should not be used. It will be removed in InSpec 3.0.</p>
```

**Comment by zenspider** [comment]
@mjingle how long should we keep such references?

**Comment by clintoncwolfe** [comment]
I presume `ag` is an alias of some kind for a recursive grep?

**Comment by clintoncwolfe** [comment]
`apache` was intended to be removed in v3, but actually was deprecated (with a Deprecation system hard exit) in v4. So, at least in v4, I think it makes sense to retain the docs, but update them to be accurate and point them to the replacement, `apache_conf`.

`azure_generic_resource` should refer the user to use the `inspec-azure` resource pack, which has specific resources.

**Comment by zenspider** [comment]
Yes, `ag` is the binary in `the_silver_surfer` which you can get in homebrew. It's blazingly fast, respects `.gitignore` and friends, and does full modern regexps.
