### ISSUE TITLE
CLI command to list all inputs in a profile

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4028]
### 🎛 Description

It would be great to be able to list the Inputs in a profile (or stack of dependent profiles).

It could have JSON output, listing which profile, input name, type, requiredness, and any values seen.

Ideally, the information could be rich enough to drive the generation of a GUI.

This could be a sub-command of the `inspec json` command, which exports a profile in JSON with much of this information.

### 🌍 InSpec and Platform Version

4.3.2

**Comment by aaronlippold** [comment]
👍 agreed.
