### ISSUE TITLE
Http ressource with digest auth

### ISSUE THREAD

**Issue by lpxavi** [inspec/inspec#4049]
### 🎛 Description

It is a 🙋 feature request.

Hi, I am trying to test an http endpoint but I don't find the way to make digest auth with http ressource (https://www.inspec.io/docs/reference/resources/http/)

Does this feature exist ?

Thanks for your help.

### 🌍 InSpec and Platform Version

Inspec 3.0.52
Centos 7

**Comment by miah** [comment]
Thanks for bringing this to our attention. I believe we only currently support basic authentication, but I'll add this to our backlog.

**Comment by davinerd** [comment]
Any news on this? This is currently blocking us to test a SaaS platform which requires digest authentication.
