### ISSUE TITLE
Hashes in inputs from inspec.yml and inputs file loaded differently

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#4057]
### 🎛 Description

This is a 🐛 bug report 

Attribute Hashes loaded from attributes.yml (note lack of : ):
{"us-east-1"=>
{:s3_bucket_name=>"s3_bucket_name_value", :sns_topic_arn=>"sns_topic_arn_value"}
}

Attribute Hashes loaded from inspec.yml (note : ):
{:"us-east-1"=>
{:s3_bucket_name=>"s3_bucket_name_value", :sns_topic_arn=>"sns_topic_arn_value"}
}

Effect: 

Identical hash key reference will fail for one of them and succeed on the other. 

test1['us-east-1'] or test1[:'us-east-1']

### 🌍 InSpec and Platform Version

Seen in inspec -v 3.9.3 and 4.3.2

**Comment by aaronlippold** [comment]
@clintoncwolfe Will this be resolved by the current input refactoring? #3875

**Comment by limitusus** [comment]
@aaronlippold @clintoncwolfe 
It does not seem to be fixed yet even in v4.8.51 in chefdk-4.7.73.
https://gist.github.com/limitusus/4c293df7a6c6c685ed4e29a8ce913e00

**Comment by clintoncwolfe** [comment]
Ideally if an Input is Hash-valued we might want to use something like Thor's HashWithIndifferentAccess to avoid having to choose whether to use a String or a Symbol.
