### ISSUE TITLE
New resource: HashiCorp's Consul resource

### ISSUE THREAD

**Issue by multani** [inspec/inspec#4058]
### 🎛 Description

This is (kind) of a 🙋 feature request!

We are building automation to create Consul clusters and we are interested to test that the creation of these clusters worked correctly.

Things that may be interested to test:

* size of the cluster
* presence of a leader or not
* correctly configured datacenter
* presence or not of some keys in the Key/Value store
* configuration of the ACL system
* etc.

### 💁 Possible Solutions

So, that's the "kind of" of the original paragraph :)
I've started to implement a [custom library](https://github.com/multani/inspec-custom-resources/blob/master/libraries/consul.rb) to provide this type of test, which allows to write something like:

```ruby
describe consul_cluster('http://localhost:8500') do
  it { should be_reachable }
  it { should have_leader }
  its('servers_count'){ should be >= 3 }
  its('datacenter'){ should include 'dc1' }
end
```

I would be interested to contribute this resource upstream in InSpec core if it makes sense. Is it a type of resource that could be merged?

It's obviously not "finished" yet in the sense:
* it misses documentation and reference to the Consul's documentation
* possibly tests: I've seen new resources imported without tests
* completion: it implements only a subset of the features described in the first paragraph but that could be a first start
* I also wonders if the concept of testing remote resources such as a remote Consul cluster makes sense at all in the InSpec concepts. If yes:

  - Is the implementation proposed would be mergeable this way? (being able to describe `consul_cluster('http://some-hostname:8500')`)
  - Is there a better way to query remote HTTP services?

We may also be interested to extend this initial version of this Consul resource and we are also looking at other HashiCorp-related resources for the future (we have some basic tests for [Nomad](https://www.nomadproject.io/) for example), being able to have some feedback on this first one would be great!

**Comment by miah** [comment]
This sounds like a awesome resource, and I'll definitely take a look at your repo.

Testing remote resources as specified is totally valid.

I'm not sure if this is the type of resource we'd merge into Core. We are actually trying to move many resources out of Core and into Resource Packs, and eventually those may be Resource Plugins.

**Comment by multani** [comment]
@miah Thanks for the review, and I totally understand that you want to keep Core leaner :+1: 

Are there any specific resources (documentation, project skeleton) that are recommended to start developing Resource Packs or Resource Plugins?
