### ISSUE TITLE
inspec --chef-license=accept shouldn't output help after

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4064]
```
% inspec --chef-license=accept
...
1 license accepted
...
[inspec usage]
```

it should just print that the license is accepted and quit if there are no other options / commands.

**Comment by orcutt989** [comment]
+1 for this

**Comment by jjcaballero** [comment]
This is indeed still an issue, every time we run CI in a fresh environment the licenses must be accepted and it is annoying and misleading to see the help message after doing that. It would be great if this could be addressed.

**Comment by Nik08** [comment]
I maybe wrong but I think `--chef-license` is one of the options which should be used with the command. So `inspec <COMMAND> --<OPTION>` this is how it should be used and that's why the above mentioned `inspec --chef-license=accept` outputs help because it indicates we might be using it wrong.
