### ISSUE TITLE
License Must Be Accepted Error

### ISSUE THREAD

**Issue by mrnabil82** [inspec/inspec#4067]
### 🎛 Description

when executing inspec i got this message:

Traceback (most recent call last):
	2: from /usr/local/bin/inspec:23:in `<main>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/lib/site_ruby/2.5.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem inspec (>= 0.a) with executable inspec (**Gem::GemNotFoundException**)

### 🌍 InSpec and Platform Version
on ubuntu 18.04
inspec version :: 4.3.2
gem -v :: 3.0.3
ruby -v :: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

**Comment by mrnabil82** [comment]
I removed everything and reinstalled them again.
it worked when testion:
+ inspec -v
+ inspec shell
but when using it as exec it displays the following msg:
'''ERROR: InSpec cannot execute without accepting the license '''

**Comment by clintoncwolfe** [comment]
This is intended behavior; as of v4, a license is required to be accepted to use Chef InSpec. See https://github.com/inspec/inspec/pull/3935 for details.
