### ISSUE TITLE
licensing terms unclear - please clarify

### ISSUE THREAD

**Issue by cruwe** [inspec/inspec#4084]
With #4038, #4071 and #3935, users get pointed at https://www.chef.io/end-user-license-agreement/, which permits the use of InSpec only for non-commercial purposes.

Yet under LICENSE.md and at the end of README.md, the software is licensed under Apache2.0.

For me as a non-legal person, both cannot be true at the same time. Could you please clarify?

**Comment by cruwe** [comment]
Trying not to be rude, but still to gently prod: Is my question that difficult to answer?

**Comment by clintoncwolfe** [comment]
It *is* a bit difficult for me to answer, for I am both an employee of Chef, and I am not a lawyer. None of this is to be taken as legally binding, and all misstatements here are my own, and do not represent the intent of my employer. Here is the gist, however:

 * You can *use* the `inspec` gem as a *library* for free, for any use, period.
 * There are community efforts underway to make an executable that uses the library, which again you could use for any purpose. Chef is fully on-board with making these efforts easy; InSpec in particular should be easy to handle.
 * You can *have* the source code, including the executable, no matter who you are or what your intent. The Apache 2.0 license, as I understand it, is a source code distribution license - not a *usage* license.
 * If you are a major contributor, non-profit, individual, software evaluator, or other entity not generally making money from your use of inspec, while you will need to accept the Chef License (which is about *usage*), you would probably qualify under the non-commercial use clause.
 * If you are not one of those groups, and you want to *use* the inspec executable, you need to accept the Chef License, and so to enjoy support, packaging, etc, then a commercial relationship with Chef is right for you! :-)

I do not know if I have split the proper hairs properly; and again this is my personal understanding of the situation.  Does that help?

**Comment by cruwe** [comment]
Hi, thanks for your kind help. 

I understand your dilemma as an employee as well as as a non-lawyer. I interpret Apache 2.0 differently, because it states "source & object form", but this is an issue we cannot resolve here.

Thanks for your answer anyway!

**Comment by clintoncwolfe** [comment]
You're welcome! I'm going to go ahead and close this :-)
