### ISSUE TITLE
Package resource on Windows finds package by wildcard when exact match exists

### ISSUE THREAD

**Issue by adamkadzban** [inspec/inspec#4117]
This looks to be related to the package lookup logic going from -like to -match, and the introduction of the wildcard logic into the regex from https://github.com/inspec/inspec/pull/3607

Say you have two Windows packages installed, "Foo" version 1 and "Foo Bar" version 2. The logic here will run the query in Powershell, find both packages, and then "pick the first one for now": https://github.com/inspec/inspec/blob/v4.4.27/lib/inspec/resources/package.rb#L288-L309

This makes this test sometimes fail, because the first package in the list isn't always "Foo":

```
control 'installed' do
  title 'packages are installed.'
  [
    'Foo', 
  ].each do |package|
    describe package(package) do
      it { should be_installed }
      its('version') { should eq '1' }
    end
  end
end
```

(I believe Windows is returning the order differently based on which package was installed first, but I have not confirmed that.)

## Possible Solution
The best solution I can think of at the moment would be to have some additional logic here that prioritized an exact match and fell back to picking the first if no exact match existed: https://github.com/inspec/inspec/blob/v4.4.27/lib/inspec/resources/package.rb#L308-L309

**Comment by mhackethal** [comment]
@clintonwolf shall i Look into that. I think Last change was done by me ?

**Comment by Vasu1105** [comment]
This has fixed in the https://github.com/inspec/inspec/pull/5323
