### ISSUE TITLE
SSHv1 falsely detected when not enabled

### ISSUE THREAD

**Issue by scarolan** [inspec/inspec#412]
This is the setting in sshd_config, commented out because it's the default:

```
# Protocol 2
```

This throws a warning about sshv1 until you uncomment that line and explicitly specify SSHv2.  Perhaps we can find a more accurate way to detect whether sshv1 is really enabled or not.

**Comment by chris-rock** [comment]
That is a good discussion. We can have different opinions here:
- the test is right, because `Protocol 2` is not mentioned within the config file
- the test is wrong, because `Protocol 2` is the default for the current openssh package

For reference, CIS is recommending the following test:

```
# grep "^Protocol" /etc/ssh/sshd_config
Protocol 2
```

**Comment by chris-rock** [comment]
Just looked up the defaults for ssh:

```
Protocol
Specifies the protocol versions ssh(1) should support in order of preference. The possible values are '1' and '2'. Multiple versions must be comma-separated. The default is ''2,1''. This means that ssh tries version 2 and falls back to version 1 if version 2 is not available.
```

Therefore the test is actually right, because Version 1 should not be used anymore. It still allows to run a fallback.

The real question: Should `ssh_config` know the defaults for each specific operation system package?

**Comment by chris-rock** [comment]
My current opinion: It should not know the defaults, because that is to much magic. I am open for other opinions.

**Comment by st739** [comment]
sshd provides the -T flag. This emits sshd's parsed output of the sshd_config file.
If the 'Protocol 2' line is missing or commented, sshd -T reports 'protocol 2'. If a valid protocol entry exists in the file, sshd -T will display it.
/etc/ssh/sshd_config is not actually case sensitive. The CIS recommendation is not perfect.
Simon

**Comment by voroniys** [comment]
I'do have an option 
Protocol 2
in sshd_config, but nevertheless Inspec is complaining about it. 
How is it possible?

**Comment by chris-rock** [comment]
@voroniys Could you share the content of the sshd config and the inspec check that you are using?

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
