### ISSUE TITLE
Inspec ignores duplicated tests ?

### ISSUE THREAD

**Issue by obynio** [inspec/inspec#4126]
Hi,

I recently faced an issue with inspec but I'm unsure if that's an actual bug or an expected behaviour and I'm seeking advices about this issue 🙂 

I'm currently developing a load balancer and in order to test all the cases I need to change its behaviour during the test phase and I thus need to reuse the same test multiple times. 

However, I noticed that the same test is not re-executed later but cached. It seems that when you run two times the same exact test, the second is not executed as expected but the second test outputs the results from the first. So you can't re-execute the same test and expect a different output. I managed to replicate the issue in a simple test case.

Here we have 4 `describe commands` that are supposed to run in this order. The `should eq "false"` is only here to allow me to get the output of the `date` command as timestamp.

* `date +"%T.%N" && sleep 1`
* `date +"%T.%N" && sleep 1`
* `date +"%T.%N" && sleep 2`
* `date +"%T.%N" && sleep 2`

Given this, we should expect a different nanosecond timestamps for each commands as the `sleep` guarantees us at least 1 second delay between each command. 

```
control "failing-test" do  
  impact 1.0
  title "Bad test"
  desc "Second test is not executed and date is the same as the first"
  describe command('date +"%T.%N" && sleep 1') do
    its('stdout') { should eq "false" } # just used to get command output
  end
  describe command('date +"%T.%N" && sleep 1') do
    its('stdout') { should eq "false" } # just used to get command output
  end
  describe command('date +"%T.%N" && sleep 2') do
    its('stdout') { should eq "false" } # just used to get command output
  end
  describe command('date +"%T.%N" && sleep 2') do
    its('stdout') { should eq "false" } # just used to get command output
  end
end
```

However as a result for each command we get the following timestamps.

* 10:01:59.151332098
* 10:01:59.151332098
* 10:02:00.264224863
* 10:02:00.264224863

```
×  failing-test: Bad test (4 failed)
     ×  Command: `date +"%T.%N" && sleep 1` stdout should eq "false"

     expected: "false"
          got: "10:01:59.151332098\n"

     (compared using ==)

     Diff:
     @@ -1,2 +1,2 @@
     -false
     +10:01:59.151332098

     ×  Command: `date +"%T.%N" && sleep 1` stdout should eq "false"

     expected: "false"
          got: "10:01:59.151332098\n"

     (compared using ==)

     Diff:
     @@ -1,2 +1,2 @@
     -false
     +10:01:59.151332098

     ×  Command: `date +"%T.%N" && sleep 2` stdout should eq "false"

     expected: "false"
          got: "10:02:00.264224863\n"

     (compared using ==)

     Diff:
     @@ -1,2 +1,2 @@
     -false
     +10:02:00.264224863

     ×  Command: `date +"%T.%N" && sleep 2` stdout should eq "false"

     expected: "false"
          got: "10:02:00.264224863\n"

     (compared using ==)

     Diff:
     @@ -1,2 +1,2 @@
     -false
     +10:02:00.264224863
```

It seems that the results of tests are 'cached' and when we run again the exact same test, this same second test is ignored and inspec output the result of the first test.

My question is, is this a bug or an expected behaviour from inspec and/or rspec ? An is there a feature that could allow me to re-execute a test without caching the result ?

Regards,

**Comment by frezbo** [comment]
@obynio you should probably run with `backend-cache` disabled. From CLI:

**   [--backend-cache], [--no-backend-cache]            # Allow caching for backend command output. (default: true)**

**Comment by obynio** [comment]
That's exactly what I was looking for ! Much thanks !
