### ISSUE TITLE
Things should have names

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4127]
Inspec uses `Class.new` and `Module.new` with wild abandon. This must stop. It's entirely too difficult to debug any of the internals with all the clever code going on and I don't see a single use-case where these dynamic modules or classes are actually necessary. Use accessors instead of closures.

Aha! Link: https://chef.aha.io/features/SH-2322

**Comment by clintoncwolfe** [comment]
Adding search keyword "Anonymous class"

**Comment by clintoncwolfe** [comment]
I'm going to close this as a duplicate of #4211
