### ISSUE TITLE
Stop including RSpec::Matchers

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4139]
We should wrap this, or include our own.

https://github.com/inspec/inspec/blob/master/lib/inspec/rule.rb#L11

**Comment by clintoncwolfe** [comment]
This could be disruptive; many users have used RSpec matchers freely. If we're sure we want to move in this direction, maybe we could add some tooling - like a rule for `inspec check` that detects rspec matchers.

**Comment by clintoncwolfe** [comment]
Refs #3600 #2867
