### ISSUE TITLE
documentation for installing inspec-bin

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec#4145]
# Describe the problem

Inspec v4 requires an additional package installation of inspec-bin.
This is not documented on the website.

## Possible Solution

add documentation to the website.

**Comment by darkn3rd** [comment]
Verified that this is not documented on the website.   There's an announcement page that documents it, but general documentation around installing the gem, does not document it.

**Comment by clintoncwolfe** [comment]
~~Could you provide a link to the location where you expect this to be documented?~~

From the README, here? https://github.com/inspec/inspec#install-it-via-rubygemsorg

Note that 
`inspec-bin` is included when you install from downloads.chef.io and via Chef-DK.

**Comment by clintoncwolfe** [comment]
And yes, on the website [downloads page](https://www.inspec.io/downloads/), as well

**Comment by tbugfinder** [comment]
Correct,
https://github.com/inspec/inspec#install-it-via-rubygemsorg and downloads page.
