### ISSUE TITLE
filesystem Resource in Windows

### ISSUE THREAD

**Issue by SaranrajG01** [inspec/inspec#4146]
Hi Team,

Im planning to use the filesystem Resource to identify all the available Drives and its Filesystem Type.

Currently we can pass the Drive Letter and verify its FileSystem Type. Please let me know if there is any option to discover all Drivers and validate its FileSystem Type.

**Comment by clintoncwolfe** [comment]
Not at this time, no.  You could likely use a PowerShell resource to list drives, and then use that information to call filesystem.

**Comment by clintoncwolfe** [comment]
I beleive this question has been answered - thanks!
