### ISSUE TITLE
HashDiff Constant deprecation warning in TravisCI output

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4162]
Not sure if we need to worry about this?

```
The HashDiff constant used by this gem conflicts with another gem of a similar name.  As of version 1.0 the HashDiff constant will be completely removed and replaced by Hashdiff.  For more information see https://github.com/liufengyun/hashdiff/issues/45.
```

https://travis-ci.org/inspec/inspec/jobs/539050658#L371

```
Gemfile.lock:    hashdiff (0.3.9)
Gemfile.lock:      hashdiff
```

**Comment by clintoncwolfe** [comment]
Please try to use more descriptive issue titles in the future; having to click-through to get context makes it hard to manage issues.

**Comment by peterklogborg** [comment]
Hi Miah.

Would you be able to downgrade it to 0.3.8?
That should get rid of the warning
