### ISSUE TITLE
be_enabled for upstart service on RHEL 6 not working correctly

### ISSUE THREAD

**Issue by fletchowns** [inspec/inspec#417]
I'm running CentOS 6.5 with inspec <x>

I run uwsgi as an upstart service. I had the following inspec test:

```
describe upstart_service('uwsgi') do
    it { should be_installed }
    it { should be_enabled }
    it { should be_running }
end
```

```
Failures:

  1) Service uwsgi should be enabled
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected that `Service uwsgi` is enabled
     # ./test/integration/default/mytest_spec.rb:11:in `block (2 levels) in load'
     # C:/Users/fletchowns/AppData/Local/chefdk/gem/ruby/2.1.0/gems/kitchen-inspec-0.10.1/lib/kitchen/verifier/inspec.b:43:in `call'
```

Apparently it uses [initctl show-config](https://github.com/chef/inspec/blob/07936e965dccd83d99673538142c59b2e67638cb/lib/resources/service.rb#L244) to do this check, but the RHEL 6 version of upstart doesn't seem to support that:

```
# initctl show-config uwsgi
initctl: invalid command: show-config
Try `initctl --help' for more information.
# initctl version
init (upstart 0.6.5)
```

**Comment by chris-rock** [comment]
@fletchowns thanks for reporting. Can you provide installation instructions for upstart on CentOS?

**Comment by fletchowns** [comment]
@chris-rock I don't remember doing anything special to install upstart on CentOS, I think it came with it. I'm using the chef/bento box for centos 6.5: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

**Comment by chris-rock** [comment]
if its in the bento box, that is great, that eases the testing. thanks for sharing.

**Comment by srenatus** [comment]
Yup, seems like [`show-config` was added in 1.3](http://upstart.ubuntu.com/cookbook/#initctl-commands-summary).

**Comment by fletchowns** [comment]
New version works great guys, thanks for the lightning fast turnaround!
