### ISSUE TITLE
Improve Windows account support

### ISSUE THREAD

**Issue by sam1el** [inspec/inspec#4174]
Inspec should support common OS features for windows as it does in Linux

## Detailed Description
Currently, to check things such as the password age of a specific user, a custom powershell block is needed and you have to parse stdout. In linux we can check against /etc/shadow directly

## Context
as a proserve engineer, having to write custom profiles is quite common. Having a shorthand version of the windows side of things would not only make this process smoother but, would make it easier for the customer to learn if they are already familiar with the linux aspect but need to write for windows as well. 

## Possible Implementation
maybe as part of OS detection in inspec, have a case stystem so if it sees something like 
` its "passowrd' should eq 'secretstuff' ' 
it switches to a windows native command like 
`net user {username}  | find /I "Password last set"` or
 `Get-LocalUser -Name {username} | select PasswordLastSet`

**Comment by clintoncwolfe** [comment]
I'd imagine we'd improve portability on the `user` resource, or similar, to handle password settings.

Are there other specific use cases you are looking to simplify?

**Comment by sam1el** [comment]
i'm building a small list. I am seeing issues with current profiles where, though the expected result exists on the local system in policy and registry, the profile sees it as nil. this could just be there profile. That being said, the user resource is complex enough to likely cover a wide array of resources as is. it's a good start. the sub context of local user grabs group etc. i could see a use case to maybe improve the way it reads the legal text as well for gpo'

**Comment by mhackethal** [comment]
I think that fits to my topic. #4432  . Lets link it.
