### ISSUE TITLE
HTML reporter needs re-styling to remove RSpec branding, improve UX

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4178]
Just saw my first screenshot of someone's inspec run and right at the top is "rspec" emblazoned across the top. We should probably wrap that up w/ our own, and restyle it while we're in there. There was also an issue about not finding the right snippet, which was what was originally coming up as it looks like an error w/ no details (because it basically is):

![unnamed](https://user-images.githubusercontent.com/9832/58837772-67781600-8611-11e9-9f6d-7c0b3dde0081.png)

Aha! Link: https://chef.aha.io/features/SH-2390

**Comment by aaronlippold** [comment]
Just my two cents, I would suggest using heimdall-lite/vue as inspiration as the general feedback from the community at large is that the current html is very confusing from a compliance perspective. I would guess - once we  finish refactoring heimdall-vue we would be able to provide an easy template that you could just feed a standard 'results' array to and push out a very useful html file for reporting.

**Comment by aaronlippold** [comment]
https://heimdall-vue.netlify.com/#/

**Comment by aaronlippold** [comment]
https://github.com/mitre/heimdall-vue

**Comment by aaronlippold** [comment]
as a note we are refactoring this to pure web-components with an inspecjs middleware and hope that this will allow folks to reuse tested views and visualizations of our data so that the community as a whole can benefit.

**Comment by kekaichinose** [comment]
Received recent customer feedback on this as well. Will consider for prioritization in the next sprint.

**Comment by amitchettri** [comment]
also can we have check on https://github.com/inspec/inspec/issues/4972#issue-596464264 which very much related with re-styling to remove error message.

**Comment by amitchettri** [comment]
Hi, 
@clintoncwolfe, @kekaichinose is there a update on removing the title and heading name? And also their is extra error added to it as compare to the cli mode. 

Is their a possibility to get it removed as well.
