### ISSUE TITLE
Handle Inspec profiles as Gemfile

### ISSUE THREAD

**Issue by micheelengronne** [inspec/inspec#4196]
It would be interesting to manage Inspec profiles dependencies as Gemfile.

## Context
Currently, many projects can fetch specific informations or create mechanims around Gemfile dependencies.

For instance:

* [renovate](https://github.com/renovatebot/renovate) can update Gemfile dependencies
* [semantic-release](https://github.com/semantic-release/semantic-release) can update a gem package info with a SemVer
* [LicenseFinder](https://github.com/pivotal/LicenseFinder) can find licenses infos from Gemfile dependencies

But, as Inspec does not use Gemfile to handle its profiles dependencies, these projects must implement a specific solution.

## Proposed Solution
The possibility to handle Inspec profiles as gem.

**Comment by zenspider** [comment]
This feels like a dupe of #3636. Please correct me if I'm wrong. Closing.

**Comment by micheelengronne** [comment]
Not quite. The idea is to handle Inspec profiles themselves as gems. And to handle dependencies between profiles to use a Gemfile (as the profiles are gems).
