### ISSUE TITLE
Refactor rake tests to use env vars or other non-file mechanism to temporarily accept license

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4200]
When running the functional tests, we must spawn InSpec processes, which means we must have the license accepted. Our current implementation in the Rakefile writes temporary files to disk, which [is considered distateful](https://github.com/inspec/inspec/pull/4086/files#diff-52c976fc38ed2b4e3b1192f8a8e24cffL79).

One approach would be to globally set an env var, like `CHEF_LICENSE=accept-no-persist`. However, we do have a set of functional tests that require no such env settings, see [functional/license_test.rb](https://github.com/inspec/inspec/blob/d2a491ff3c75dc62df6d0b51569d2cc3db00a048/test/functional/license_test.rb#L65). It's not intractable but a twist; and yes a lot of that could be removed.

Refs #4086

**Comment by zenspider** [comment]
I think this should probably be closed. ENV vars are just as error-prone in a parallel test environment as files in the home directory. I just filed #4676 which I think is a better alternative.
