### ISSUE TITLE
Support for Photon OS

### ISSUE THREAD

**Issue by kclinden** [inspec/inspec#4201]
When I run detect on a Photon OS system I get the following information instead of Photon.
```
Name:      linux
Families:  linux, unix, os
Release:   unknown
Arch:      x86_64
```

## Detailed Description
Add support for Photon OS. 

## Context
I would like to use inspec to check compliance of systems such at the VMware VCSA appliance that uses Photon.

## Possible Implementation
Look at os-release or lsb-release? I am not sure what detect uses currently.

**Comment by clintoncwolfe** [comment]
Hi! Thanks so much for reporting this.  However, the functionality you describe is actually handled by an underlying library, [train](https://github.com/inspec/train), which is used to detect platforms and connect to remote scanning targets. Any new features or fixes would need to be contributed there, so please discuss on Train in a [new issue](https://github.com/inspec/train/issues/new).  Thanks again!
