### ISSUE TITLE
Either VCR all network access or stop doing a version check

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4220]
Another "network" failure. If you're running tests in a branch and @miah goes and does a release, all of a sudden you start to fail out tests because of output from the version test:

```
  1) Failure:
command tests::version#test_0001_provides the version number on stdout [/Users/ryan/Work/git/inspec/inspec/test/functional/inspec_test.rb:17]:
--- expected
+++ actual
@@ -1,2 +1,4 @@
 "4.6.3
+
+Your version of Chef InSpec is out of date! The latest version is 4.6.4.
 "
```

It shouldn't be hitting the network or doing a version check at all.

I think the latter is actually correct because we expect most users to be using omnibus and telling them that there is a gem update doesn't make sense.

**Comment by clintoncwolfe** [comment]
`inspec version` no longer accesses the network.
