### ISSUE TITLE
Blog post on practical usage of Inputs

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4224]
## Detailed Description

We've had a request for a blog post on practical applications of Inputs.

**Comment by Jcsilver69** [comment]
Hell with ordering what I'm looking??

**Comment by kekaichinose** [comment]
Talked with PMM and we'll be looking to post this tomorrow, 11/6/19. Will close out once I confirm post.

**Comment by kekaichinose** [comment]
This has been pushed out: https://blog.chef.io/5-things-you-can-do-with-chef-inspec-input/

Thanks!
