### ISSUE TITLE
Toggle for Deprecation Warnings

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4228]
As a user I would like a way to toggle deprecation warnings off. This could be performed by setting an Environment variable, passing a CLI argument, or setting a configuration option.

**Comment by TheLonelyGhost** [comment]
One thing to distinguish here is "deprecation" needs some context. Is it an InSpec API deprecation warning, or general Ruby library deprecation warnings?

**Comment by mbaitelman** [comment]
Might be interesting to do something similar to https://docs.chef.io/chef_deprecations_client.html as far as functionality goes.

**Comment by clintoncwolfe** [comment]
FWIW, one current workaround to note is that you may edit the `etc/deprecations.json` file in your inspec installation, and set the `action:` field to `ignore` to silence individual warnings.

**Comment by rmoles** [comment]
+1
