### ISSUE TITLE
Ability to mark inputs as sensitive

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#4229]
As an end user, I would like to be able to label an input As sensitive data. Much like the current implementation in controls. I would like to ensure that inputs marked as sensitive will not be rendered in CLI output or the other reporters. this would probably also necessitate that we add a - - show-sensitive flag for possible debugging.

**Comment by clintoncwolfe** [comment]
Can you give some examples of where an input is being output in a reporter or in CLI output?

**Comment by ejaronne** [comment]
From a json reporter, we see the sensitive data in the json file:

          "name": "password",
          "options": {
            "type": "string",
            "required": true,
            "value": "<sensitive_info>"

In the above case, the profile receives the sensitive info via an environment variable and assigns it to an attribute. Unfortunately the attribute value is passed through to the json. We don't need/want that. We'd like a way to define attributes with "sensitive" label such that by default their values do not appear in any of the reporter outputs, especially json.

(See here how we assign the password to the attribute from the environment variable:
https://github.com/mitre/rsa-archer-6-security-configuration-guide-baseline/blob/master/inspec.yml)

Thanks!

**Comment by ejaronne** [comment]
To clarify, when reporters are used, especially json, the request is to remove or obscure the <sensitive_info> from the output. Remove is preferred.

**Comment by aaronlippold** [comment]
@kclinden has an interest as well for the VMWare work

I think we would like to add an option to the inputs object - as we did for controls - to add a `sensitive` field. 

Do we think we can reuse the bulk of the code from the `controls` implementation?

**Comment by aaronlippold** [comment]
related https://github.com/inspec/inspec/pull/2017
