### ISSUE TITLE
Is there a way to do an 'or' statement in chef inspec check?

### ISSUE THREAD

**Issue by nkershaw22** [inspec/inspec#4239]
### 🎛 Description.

How to perform an 'or' statement. For example, if sshd_config its('clientaliveinterval') { should be <= '300' }  ... within the clientaliveinterval setting, the time format may also be set as 'm' for minutes. So it could potentially output '5m', and still pass the check, but I am having trouble figuring out how to incorporate an or statement without breaking the check. Please advise, if possible. 

**Choose one:** is this a 🐛 bug report or 🙋 feature request?
neithedr 
Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using 

### 🤔 Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by nkershaw22** [comment]
describe.one looks promising

**Comment by zenspider** [comment]
`describe.one` is the correct answer. Closing.
