### ISSUE TITLE
Support testing of windows service run as user

### ISSUE THREAD

**Issue by dalee-bis** [inspec/inspec#4240]
## Detailed Description

We are using Chef to configure a windows service to run as a domain account. We would like to add an integration test to ensure the account is being set correctly but from the object at [service.rb line 594](https://github.com/inspec/inspec/blob/a35d37043e65ce5fd528d58cd48ecb369c74a432/lib/inspec/resources/service.rb#L594), it doesn't appear that there is a property to allow this.

## Context

See above.

**Comment by mbaitelman** [comment]
I think #4363 can close this out
