### ISSUE TITLE
Remote targets support for RHEL 8

### ISSUE THREAD

**Issue by PascalJanszWork** [inspec/inspec#4245]
## Detailed Description

When will RHEL8 officially supported as a remote target?

## Context

We want to define and test Security Compliancy on RHEL 8 base images in our landscape.

**Comment by zenspider** [comment]
OP... is this a doco issue for you or are you actually having problems connecting? If the latter, can you please file a similar issue on inspec/train as that is what is doing all connection and platform identification.
