### ISSUE TITLE
Fix functionals on windows

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4249]
Right now most of the windows functional tests are being skipped because of an incompatibility in how we're getting and checking exit codes. They're all time bombed and need to be fixed before 7/31/2019 or the CI will go red.

I've got partial fixes in to change to a custom assertion to check the exit code and on windows they normalize to 0/1. The rest need to be converted over.

**Comment by zenspider** [comment]
Status update: I'm at ~50% fixed on #4390.

**Comment by kekaichinose** [comment]
Closed as part for #4390
