### ISSUE TITLE
Update the MAINTAINERS file

### ISSUE THREAD

**Issue by mjingle** [inspec/inspec#4271]
The MAINTAINERS file needs to be updated.

# Describe the problem
Both [MAINTAINERS.toml](https://github.com/inspec/inspec/blob/master/MAINTAINERS.toml) and the generated [MAINTAINERS.md](https://github.com/inspec/inspec/blob/master/MAINTAINERS.md) in the InSpec repo feature outdated information about InSpec maintainers.

## Possible Solution
Edit the files accordingly with the current MAINTAINERS information.

**Comment by kekaichinose** [comment]
It's a little bit of a nit, but I'd like to add the Project Lead into the doc. However, I'd have to update tasks/maintainers.rb to add that in, and well...I'm still a Ruby white belt.

**Comment by kekaichinose** [comment]
closed by #4287
