### ISSUE TITLE
Missing Plugin Types in InSpec Documentation

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4292]
### 🎛 Description

🐛 bug report

As a user getting started with InSpec plugins, it would be helpful to know the different types of InSpec plugins and how they help enhance the user experience of InSpec (and where related, Train).

### 🌍 InSpec and Platform Version

Current (4.x)

### 🤔 Replication Case
_N/A - this is a documentation issue._
### 💁 Possible Solutions
_N/A_
### 💻 Stacktrace
_N/A_

**Comment by clintoncwolfe** [comment]
https://www.inspec.io/docs/reference/plugins/ describes plugins and plugin types.  It is however out of date, and needs to be updated with information about inputs per #3884
