### ISSUE TITLE
inspec.io mobile site - hamburger menu doesn't work

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#4331]
When I visit inspec.io using Google chrome on OSX (`User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36`) for some reason I get served the mobile version of the site, and the hamburger menu is unusable because it's contents drop down _behind_ the main page:

<img width="1433" alt="Screen Shot 2019-07-25 at 09 39 32" src="https://user-images.githubusercontent.com/12136665/61859678-7e740f80-aec0-11e9-9417-592e09fb9c84.png">

If I try using Chrome (75.0.3770.143) on Android 8.1.0 I see the same bug.

**Comment by clintoncwolfe** [comment]
Verified that the hamburger menu expands "behind the viewport" on Android mobile.

**Comment by james-stocks** [comment]
I think https://github.com/inspec/inspec/issues/4514 is a duplicate of this.

**Comment by james-stocks** [comment]
Closing as duplicate of #4514 which was fixed by https://github.com/inspec/inspec/pull/4515
