### ISSUE TITLE
Separate profile ingestion and reporting configurations

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4333]
### 🎛 Description

🙋 feature request?

In learning more about how the Effortless pattern works, it became apparent that the `compliance` block in config.json is not only not documented, but also is strictly used for communication between Chef InSpec and Chef Automate. This communication can be broken down into two parts: profile ingestion and reporting.

Being that we already have a way to target locations to ingest profile data, as well as reporter functionality, we should look at deprecating the use of the `compliance` config block to reduce complexity and user experience confusion.

### 🌍 InSpec and Platform Version

Current

### 🤔 Replication Case

*N/A*

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

*N/A*

**Comment by zenspider** [comment]
@kekaichinose Please break this up to 3+ issues.

**Comment by kekaichinose** [comment]
@zenspider If I understand this rightly, the three issues we need to cut are:
* ensure profile ingestion from Automate works outside of `compliance` config block of inspec.yaml
* ensure reporting to Automate works outside of `compliance` config block of inspec.yaml
* create deprecation plan (and blog post) for `compliance` config block
  * will need to pitch this to Automate to see when they would be able to consume this; this will set both deprecation and EOL path

**Comment by kekaichinose** [comment]
BTW, @alexpop, @rickmarry, @vjeffrey wanted to give you a heads-up as a key stakeholder on this effort. Get you involved earlier rather than later :)

**Comment by vjeffrey** [comment]
just taking a look at this i'm not clear on what the change being made is -- is this dropping the compliance block that is used for pulling profiles and replacing it with something else closer to the other profile pulling use patterns?  we have some code in Automate that uses the compliance config block: the remote jobs (https://github.com/chef/automate/blob/master/components/compliance-service/inspec-agent/remote/remote.go#L164) -- as long as the entire process of pulling a profile from automate, executing a scan, and sending the report to automate can all be done as one command still, i'm +1 on this, we'll just need to coordinate on timing. should be a small change/quick for us to complete.

**Comment by clintoncwolfe** [comment]
We've had no customer demand for this change, and it would be highly disruptive to the installed base for little tangible benefit. I'm going to close this one.
