### ISSUE TITLE
build on ARM and x86-32bit

### ISSUE THREAD

**Issue by amih90** [inspec/inspec#4336]
I would like to run inspec inside raspberry with `ARM` architecture and also 32bit devices. 
I haven't found any download source for those at https://downloads.chef.io/inspec, so I have tried to build inspec project with omnibus as suggested in the docs.

My device properties:
```
Operating System: Ubuntu 18.04.2 LTS
Kernel: Linux 4.15.0-1041-raspi2
Architecture: arm
```

Following the README.md in /inspec/omnibus https://github.com/inspec/inspec/tree/master/omnibus
when I execute the command 
`bundle exec omnibus build inspec`
it fails with 

> Could not find gem 'rb-readline' in any of the gem sources listed in your Gemfile.
> Run `bundle install` to install missing gems.

and  `bundle install` execution fails with:
```
Using concurrent-ruby 1.1.5
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Using faraday 0.15.4
Fetching unf_ext 0.0.7.2
Installing unf_ext 0.0.7.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20190729-12096-bmll46unf_ext-0.0.7.2/gems/unf_ext-0.0.7.2/ext/unf_ext
/usr/bin/ruby2.5 -r ./siteconf20190729-12096-xdbncz.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /tmp/bundler20190729-12096-bmll46unf_ext-0.0.7.2/gems/unf_ext-0.0.7.2/ext/unf_ext
make "DESTDIR=" clean

current directory: /tmp/bundler20190729-12096-bmll46unf_ext-0.0.7.2/gems/unf_ext-0.0.7.2/ext/unf_ext
make "DESTDIR="
compiling unf.cc
In file included from unf/normalizer.hh:10:0,
                 from unf.cc:1:
unf/table.hh:13539:25: error: narrowing conversion of ‘-27’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
  -77, -39,-124, -39,-123};
                         ^
unf/table.hh:13539:25: error: narrowing conversion of ‘-113’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]

... A LOT OF conversion errors

unf/table.hh:13539:25: error: narrowing conversion of ‘-39’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
unf/table.hh:13539:25: error: narrowing conversion of ‘-123’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
Makefile:210: recipe for target 'unf.o' failed
make: *** [unf.o] Error 1

make failed, exit code 2

Gem files will remain installed in /tmp/bundler20190729-12096-bmll46unf_ext-0.0.7.2/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /tmp/bundler20190729-12096-bmll46unf_ext-0.0.7.2/extensions/arm-linux/2.5.0/unf_ext-0.0.7.2/gem_make.out

An error occurred while installing unf_ext (0.0.7.2), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.2'` succeeds before bundling.

In Gemfile:
  inspec-bin was resolved to 4.7.26, which depends on
    inspec was resolved to 4.7.26, which depends on
      train-aws was resolved to 0.1.7, which depends on
        train was resolved to 2.1.19, which depends on
          azure_graph_rbac was resolved to 0.17.1, which depends on
            ms_rest_azure was resolved to 0.11.1, which depends on
              faraday-cookie_jar was resolved to 0.0.6, which depends on
                http-cookie was resolved to 1.0.3, which depends on
                  domain_name was resolved to 0.5.20190701, which depends on
                    unf was resolved to 0.1.4, which depends on
                      unf_ext

```

1. Is there any inspec version for ARMv7? and other distributions which relies on 32bit?
2. How I can build inspec on ARMv7?

Thank you,
Ami Hollander

**Comment by clintoncwolfe** [comment]
https://github.com/inspec/inspec#supported-os lists two tables of supported architectures and platforms. The first (larger) table lists the remote platforms supported - including several i386 platforms; so you can *scan* 32-bit targets.

The second table lists *runtime* environments - the environments on which you can build and run InSpec. While the architecture is not explicitly listed, this is all x86_64 - there is no support for ARM or i386, and no plans to support them in the future as far as I am aware.

However, you can use your own modified omnibus build plan, and do whatever you like; there is nothing stopping you from working out the details of getting it to build. You can also edit down the Gemfile - removing some of the cloud providers, like, train-azure and train-aws, remove a lot of the build requirements. Good luck!
