### ISSUE TITLE
Docs/Readme should specify testing framework used for testing Inspec itself.

### ISSUE THREAD

**Issue by Mitriol** [inspec/inspec#4340]
I just spent three hours banging my head against a wall trying to use rspec syntax instead of minitest. I had seen "include rspec" in helpers.rb, and assumed I should go ahead and contribute with rspec tests to accompany my pull request. Probably mostly my fault, but still, to have it documented somewhere would be nice!

## Possible Solution
Just document it somewhere I guess? Perhaps in the CONTRIBUTING.md file, under "Pull Request Requirements -> 1. Tests", and in the "Contributing to Inspec" header in the README.

**Comment by aaronlippold** [comment]
Was this issue resolved and clarified
