### ISSUE TITLE
Add InSpec to Cloud Native Landscape

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4357]
### 🎛 Description

🙋 feature request?

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

Per a slack chat with a fellow chef, found that we are not listed in the Cloud Native Landscape project:
https://landscape.cncf.io

We should look at getting ourselves added onto that as a marketing effort.

### 🌍 InSpec and Platform Version

current

### 🤔 Replication Case

_N/A_

### 💁 Possible Solutions

_N/A_

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by zenspider** [comment]
@kekaichinose you probably need to move this to zendesk / aha?

**Comment by kekaichinose** [comment]
@zenspider good point. I just moved this to Aha. I'll close it out from github
