### ISSUE TITLE
Stack Profile Templates

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#4368]
I have a dream, 
it would be cool to have a way to generate a profile based on template( or templating language) for a stack

`inspec init profile profile_name -t template_name`

`inpec init profile my_lamp_stack -t lamp`

Our `lamp` template
```
# Resources specified by new lines
os
apache
apache_conf
mysql_conf
mysql_session
package
port
```

our `profile.rb`

```
# http://inspec.io/docs/reference/resources/os/
describe os[:family] do
  it { should_not eq 'platform' }
end

# http://inspec.io/docs/reference/resources/apache
describe apache('name') do
  it { should_not exist }
end

# http://inspec.io/docs/reference/resources/apache_conf/
describe apache_conf('path') do
  its('setting_name') { should eq 'value' }
end

# http://inspec.io/docs/reference/resources/mysql_conf/
describe mysql_conf('path') do
  its('setting') { should_not eq 'value' }
end

# http://inspec.io/docs/reference/resources/mysql_session/
sql = mysql_session('username', 'password')

describe sql.query('QUERY') do
  its('stdout') { should_not match(/text/) }
end

# http://inspec.io/docs/reference/resources/package/
describe package('name') do
  it { should_not be_installed }
end

# http://inspec.io/docs/reference/resources/port/
describe port(number) do
  it { should_not be_listening }
  its('protocols') { should_not include('protocol') }
end
```

Aha! Link: https://chef.aha.io/features/SH-2147

**Comment by kekaichinose** [comment]
@kmf would this be related to #821?

**Comment by kmf** [comment]
@kekaichinose no not really.

**Comment by james-stocks** [comment]
This is maybe a great candidate for a plugin (following the same pattern as https://github.com/mattray/inspec-iggy/ for example).

It wouldn't get implemented in this repo, so do you mind if I close this issue?
The community Slack is always available for further discussion.

Thanks

**Comment by kmf** [comment]
Looks like something that will work 
https://github.com/inspec/inspec/issues/821
