### ISSUE TITLE
Add resource to test Postfix SMTP server configuration

### ISSUE THREAD

**Issue by dmgasper** [inspec/inspec#4377]
## Detailed Description
Current Inspec implementation provides the INI resource as an easy way to test the content of configuration files, but each test only applies to a single file. It would be useful to have a single resource through which one can test the content of all of Postfix's configuration files, and one that is optimized for parsing those files (such as the table format of master.cf)

## Context
I would use this resource because I configure Postfix SMTP servers and it would simplify the process of doing so.

## Possible Implementation
Create a new resource based on the INI resource that is optimized for testing the configuration files that Postfix uses.

**Comment by clintoncwolfe** [comment]
Merged on #4378
