### ISSUE TITLE
InSpec prompt for interactive password on bad password (SSH)

### ISSUE THREAD

**Issue by mhackethal** [inspec/inspec#4383]
InSpec Version 4.11.3
Source on WIndows 2016
Target Linux by using SSH with Username+Password

# Describe the problem

InSpec runs into an interactive password prompt if a wrong password for linux target is submitted. This causes any automated execution to break. The expected behaviour is that
inspec exit with error and message "Wrong Password". Compareable to the error message
on winRM wrong password.

Sample:
`
inspec detect --target="ssh://username:badpassword@hostname:22" -l debug
username@host´s password:<prompt>

`

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/train #510](https://github.com/inspec/train/issues/510) via [**ZenHub**](https://www.zenhub.com/)
