### ISSUE TITLE
User Survey

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4385]
As a InSpec Developer I would like to perform a user survey to gather more details until Telemetry has been developed and deployed.

**Comment by zenspider** [comment]
👍

**Comment by zenspider** [comment]
@kekaichinose I think we should push on this hard. Probably Q3. This would be much faster than waiting for telemetry.

**Comment by kekaichinose** [comment]
Maybe crib some stuff from Chef Infra's survey: https://www.surveymonkey.com/r/TP8JB72

**Comment by kekaichinose** [comment]
We'll be looking at getting this out on a fresh week, so next week 9/3. The channels we'll hit:
* #inspec, #general, and #announcements channels in respective Slack instances
* discourse feed
* twitter feed (@kekaichinose to find out more about that)

**Comment by zenspider** [comment]
What's left on this? Analysis to see if we can file issues?

**Comment by kekaichinose** [comment]
I created a feedback doc for us to review internally, and from which we can then cut new issues. For the sake of this issue, it's completed.
