### ISSUE TITLE
Support  ability to inspect GCS bucket labels so can assert upon them

### ISSUE THREAD

**Issue by djcoder100** [inspec/inspec#4396]
## Detailed Description
As a secops user I would like to check for GCS label values and perform inspection tests on this in my cicd pipeline and report on any exceptions.

## Context
As secops developer need to check that GCP GCS bucket labels conform to any policies that are set by risk and control functions of an organisation to ensure lables are set on buckets and contents for the Google Cloud platform.  

## Possible Implementation
Add as new property feature to the GCS resource in inspec for GCP: 
https://www.inspec.io/docs/reference/resources/google_storage_bucket/

**Comment by miah** [comment]
Hi, All of the GCP resources are in the inspec-gcp resource pack which can be found here: https://github.com/inspec/inspec-gcp

**Comment by binamov** [comment]
Technically this should already be doable, it's just labels are not documented as a supported property /cc @skpaterson 
@djcoder100 as discussed offline, you can create an issue on the inspec-gcp repo so we can adopt the resource into magic modules workflows
