### ISSUE TITLE
chef-compliance postgres installation

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#440]
Hi there

Sorry if this is the wrong place, I couldn't find a hub for the compliance server itself.

I performed a fresh install today "chef-compliance-0.11.1-1.el6.x86_64.rpm"

I then ran the built in "Basic PostgreSQL" compliance profile (version 1.1.0) against the compliance server itself

the report came back with 8 critical issues, I thought I would share to see if the postgres install could be improved.

![postgresql-issues](https://cloud.githubusercontent.com/assets/13700297/12918736/6e18c06a-cf38-11e5-88d1-2e81a18f51d9.PNG)

Best Regards

Gary

**Comment by chris-rock** [comment]
:facepunch: Thanks @username-is-already-taken2 for reporting this. we will improve this to make our own software compliant with our own profiles :-) It's always good to have visibility.

**Comment by jquick** [comment]
Thanks for this info. Closing this as chef-compliance is EOL.
