### ISSUE TITLE
Add support for Azure PostGreSQL server/DB test

### ISSUE THREAD

**Issue by svangeti** [inspec/inspec#4403]
## Detailed Description
There is no support for Azure Postgres server/databases testing.

## Context
We are currently planning to use InSpec for our Azure Infra testing

## Possible Implementation
If it uses terraform, we can use terraform provider 
azurerm_postgresql_server
azurerm_postgresql_database

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-azure #195](https://github.com/inspec/inspec-azure/issues/195) via [**ZenHub**](https://www.zenhub.com/)
