### ISSUE TITLE
let not available inside of control

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4407]
As it stands, we've documented `subject` as being available, but as I was working on #4372 I noticed that `let` isn't defined inside of `control` scopes. I don't know _how_ `subject` can be available if `let` isn't... but it'd be a bug afaict.

Aha! Link: https://chef.aha.io/features/SH-2276

**Comment by zenspider** [comment]
And it's not going to be anytime soon. Our controls are instances, not classes... and thus totally broken as far as rspec is concerned.

**Comment by james-stocks** [comment]
Going to close this. I think instead of trying to pull in rspec's `let` we could have our own DSL concept called `let` or `define` where users create definitions for code blocks that do not evaluate until tests are being evaluated. 
Will raise a new issue for that.
