### ISSUE TITLE
Convert functional tests for --input to unit tests

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4412]
## Detailed Description

Per [review comments](https://github.com/inspec/inspec/pull/4401/files#r316417141), the `--input` CLI input feature is currently tested using full functional testing in test/functional/inputs_test.rb .

It would increase test performance to keep it within a unit test process, and only verify that the values were read into the input registry.

**Comment by Schwad** [comment]
Hold your horses stalebot, we still want this :)
