### ISSUE TITLE
Include Waivers in reports

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4415]
### User Story
As an Operator, I want to report the status of waived controls so my stakeholders so that I can provide an accurate assessment of my compliance posture.

### Acceptance Criteria
* Control status reporting is updated
  * waiver state is included
  * and if a control is waived, its body of data is included
    * __Control ID_Name__ - the ID and Title of the control to be waived
    * __Expiration Date__ - the date when the waiver is set to expire
    * __Waiver Justification__ *(optional)* - a way to allow users to justify the waiver (i.e. why the given control must be waived)
    * __Skip run switch__ - allow users to skip the evaluating the waived control
* Updated reporting doesn't impact existing reporter performance

**Comment by zenspider** [comment]
Oops. This is step 3 and now a duplicate of #4417. Closing. (why isn't there merge?)
