### ISSUE TITLE
Waivers Step 3: Extend JSON output to include waiver data

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4417]
This is part of epic #4408.

* Changes to output to add extra fields to indicate wavered controls
  * Just adds new fields

Step 3: reporting: we need to add the waiver data to the control, which implies that even if a control is skipped it still has some payload in the report output, the data added is whether this control was skipped, for how long (optionally) and why.

**Comment by zenspider** [comment]
* Changes to output to add extra fields to indicate wavered controls
  * Just adds new fields

Step 3: reporting: we need to add the waiver data to the control, which implies that even if a control is skipped it still has some payload in the report output, the data added is whether this control was skipped, for how long (optionally) and why.

**Comment by zenspider** [comment]
From #4415:

### User Story
As an Operator, I want to report the status of waived controls so my stakeholders so that I can provide an accurate assessment of my compliance posture.

### Acceptance Criteria
* Control status reporting is updated
  * waiver state is included
  * and if a control is waived, its body of data is included
    * __Control ID_Name__ - the ID and Title of the control to be waived
    * __Expiration Date__ - the date when the waiver is set to expire
    * __Waiver Justification__ *(optional)* - a way to allow users to justify the waiver (i.e. why the given control must be waived)
    * __Skip run switch__ - allow users to skip the evaluating the waived control
* Updated reporting doesn't impact existing reporter performance

**Comment by miah** [comment]
Blocked until some design issues are cleared up in #4427
