### ISSUE TITLE
Improving InSpec quality through continuous integration testing.

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4422]
This is a EPIC to improve InSpec by continually testing with our various integrations. Much of this testing exists in full or in part, but has not been updated to work with Buildkite.

The descriptions are basic right now, as I create other issues I'll fill in the details.

This list is very ambitious and not in any specific order.

If anything is missing or should confusing please leave a comment for discussion.

Pull request verification:
 
 - [x] inspec
 - [x] train
 - [x] inspec-azure
 - [x] inspec-aws
 - [x] inspec-gcp
 - [x] inspec-habitat
 - [x] train-aws
 - [x] train-habitat
 - [x] train-winrm
 - [ ] kitchen-inspec
 
Dependencies:

We interface with these projects, we need to ensure they always work.

 - [ ] train
 - [ ] train-habitat
 - [ ] train-winrm
 - [ ] kitchen-inspec
 - [ ] inspec-scap
 - [ ] automate

Integration OS:
We support many Operating Systems, lets improve feature parity, and know where we don't have it.

 - [ ] aix
 - [ ] hpux
 - [ ] linux
 - [ ] macos
 - [ ] solaris
 - [ ] windows 

Integration DB:

We support many databases.

 - [ ] mssql
 - [ ] mysql
 - [ ] oracle
 - [ ] postgresql

Plugins:

We need to ensure a plugin update doesn't break InSpec, and vice-versa. These plugins tests could be triggered when we merge to master.

 - [ ] inspec-aws
 - [ ] inspec-azure
 - [ ] inspec-gcp
 - [ ] inspec-habitat
 - [ ] inspec-vault
 - [ ] inspec-cisco

Cookbooks:

 - [ ] audit

Profiles:

 - [ ] compliance profiles

Packages:

We create several artifacts that are made available to users. We should improve the tests that get run when they are created and ensure functionality.

 - [ ] habitat
 - [ ] omnibus
 - [ ] docker
 - [ ] gem

inspec.io:

Currently the InSpec website lives in the www directory of the main repository. When built, it deploys to the gh-pages branch and pushed to github. This is a manual process helped by a Rake task. Based on discussions with releng, we could be deploying to a different endpoint (maybe a S3 bucket) and have a automated release when the content changes.

 - [ ] build and deploy pipeline
 - [ ] development pipeline
 - [ ] extract www from inspec repository

Performance:

This is mostly an idea at this point. Lets think about what can be done here to improve the performance metrics of InSpec.

 - We need to look at resources that could be performance bottlenecks and benchmark them and measure performance over time.
 - We should consider the impact a resource can have on a system. This is mostly evident in profiles.
 - We should consider the system resources required to run a large profile. What does InSpec keeps in memory?
 - We should consider the speed in executing a large profile.

**Comment by james-stocks** [comment]
https://github.com/inspec/inspec/pull/4895 relates to this and we should probably re-open that PR and get it working and filled out with tests as we plan out tasks for this Epic.
