### ISSUE TITLE
Allow specyfying CloudWatch Alarms via ARN/name or add support of dimensions to search query

### ISSUE THREAD

**Issue by z0rc** [inspec/inspec#4453]
## Detailed Description
Right now aws_cloudwatch_alarm allows to search for alarms by specifying metric name and namespace (https://github.com/inspec/inspec/blob/master/lib/resources/aws/aws_cloudwatch_alarm.rb#L29). In my case this is too broad criteria, which will allays return many alarms. Ideally `metric_dimensions` should be added to this list as only they can help to pinpoint specific alarm.

## Context
I'm creating a lot of lambda functions and need to test that Alarm is set for each of them. But current implementation of `aws_cloudwatch_alarm` resource won't allow to specifically test every single function. Search `metric_name: 'Error', metric_namespace: 'AWS/Lambda'` would return all of the alarms. Adding something like `dimensions: 'FunctionName=foobar'` would allow to pinpoint specific alarm.

## Possible Implementation
Either extend options for CloudWatch Alarm search criterias or allow to specify alarm's ARN or name directly.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #128](https://github.com/inspec/inspec-aws/issues/128) via [**ZenHub**](https://www.zenhub.com/)
