### ISSUE TITLE
Move lib/inspec/objects/*.rb to inspec-scap project

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4455]
InSpec doesn't use _any_ of the code generation facilities. As such, it'd be great to move this to its rightful owner: inspec-scap.

**Comment by zenspider** [comment]
@skpaterson eyeballs/opinions pls.

**Comment by aaronlippold** [comment]
I don't think we would want to move these. if you use inspec as a library
which many people do you need these object classes.

**Comment by aaronlippold** [comment]
I wouldn't object to moving them into a library class such as inspec-libs
etc.

**Comment by skpaterson** [comment]
Given the 'InSpec as a library' use-case I'd be tempted to leave them there, albeit for historical reasons...

**Comment by miah** [comment]
I think we should still move them, if you need them for historic reasons they are in the repository. We are trying to clean up the InSpec code base and if we need a library that provides the functionality of those files a issue should be filed and we can discuss it there.

**Comment by zenspider** [comment]
No. "InSpec as library" isn't a valid reason. This code is NOT used within the project and does not have a use case to remain there. inspec-scap in the proper home for it and would allow the actual users of the code to own it and maintain it without us hindering them.

And if you need them for historical reasons, you can always pin to a specific version.

@kekaichinose... please confer with @skpaterson on this while you're face-to-face if possible.

**Comment by kekaichinose** [comment]
@zenspider my bad, but didn't catch this in time to sync with @skpaterson in-person. I concur with the team that if the code generation feature is only used by inspec-scap, it would make sense to move it over into that code base.

@skpaterson, let's chat about this next week

**Comment by aaronlippold** [comment]
So I would assume that the inspec-scap library will be released under
Apache 2 as well then.

**Comment by aaronlippold** [comment]
My teams use this for code generation outside the scap use case. As I said
before if it needs to be moved it should be moved to either a separate
library and then called by the needed systems or left in place  That's
perfectly reasonable. Inspec-libs world be fine. But moving it into a
closed source library I would not agree with.

**Comment by skpaterson** [comment]
I'd be happy for the libraries to be moved to another open source repository and agree that InSpec is not the ideal place for these.  My main concern is the timing and scope of any refactoring associated with the move as we have a long list of higher priorities at present.

**Comment by btm** [comment]
Moving these into a separate library in https://github.com/inspec/inspec-objects/pull/1.
