### ISSUE TITLE
Lazy loading for plugins

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4460]
I'd like to do similar work for plugins that was done to resources, namely, don't pre-populate the plugin registry if at all possible. This should be the last of our issues that fall under #4133.

**Comment by clintoncwolfe** [comment]
Plugins have a two-stage loading process. The first stage loads the gem, which is intended to be lightweight, but lets the system know what capabilities (Activators) the plugin offers. If needed, the Acivator is lazy-loaded, and that is when the heady loading is intended to happen. See https://github.com/inspec/inspec/blob/master/docs/dev/plugins.md#activation-and-execution .
