### ISSUE TITLE
Ensure contrib resource docs overwrite core

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4471]
# Describe the problem
When we pull in docs from "contrib" resource pack projects (such as inspec-aws, inspec-azure, etc) and there is a naming conflict, the copy from the external project should be assumed to be more up-to-date.

However, currently, it looks like (at least with inspec-aws) core wins.

**Comment by zenspider** [comment]
I did this a while back by deleting the local doco entirely.

#4674
