### ISSUE TITLE
Make a demo video about --input

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4482]
## Detailed Description

Make a short (60-sec) user-experience-focused video about the new feature `--input`. If it goes well, we make more videos for other select features.

## Context

Improve communication about Chef InSpec's capabilities.

**Comment by clintoncwolfe** [comment]
A video has been scripted, shot, edited, and is now being reviewed.

**Comment by kmf** [comment]
Please post a link once it's been released.

**Comment by kekaichinose** [comment]
@kmf the intended audience for this was internal to Chef, but we are already working on a plan to get this out in a consumable fashion to the community. Appreciate the interest, and stay tuned!
