### ISSUE TITLE
Stale URLs in usage help for `inspec compliance login --help`

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4500]
# Describe the problem

`inspec compliance login --help` outputs a usage message including advice to look at URLs to learn how to obtain an auth token for either Automate or Compliance (a product which has been sunsetted). However, the Compliance URL [https://docs.chef.io/api_compliance.html#obtaining-an-api-token](https://docs.chef.io/api_compliance.html#obtaining-an-api-token) is a 404.

Additionally, the Automate URL, while not a 404, links to a large API page and links to a missing anchor, so it's not clear what to do.

Additionally, the server argument is not mentioned in the usage help.

## Possible Solution

Remove the Compliance URL.
Find a better anchor for the Automate link.

**Comment by sean-horn** [comment]
Additionally, the docs at https://www.inspec.io/docs/reference/cli/ do not mention the necessary server argument seen first here `inspec compliance login https://ec2-52-13-18-55.us-west-2.compute.amazonaws.com --insecure --user=admin --token='xxxxxxxx'`
