### ISSUE TITLE
`to_hash` error when running inherited profile with an input

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#4504]
The following error is output when running with an inherited profile:

```
/opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.17.3/lib/inspec/profile.rb:319:in map': undefined method to_hash' for #<Inspec::Input:0x0000000004d67f28> (NoMethodError)
```

# Describe the problem

Using, `inspec` from the Chef YUM repos, this evidenced itself in version `4.16.15`

The code used for inheritance was trivial:

```
require_controls 'disa_stig-el7' do
  @conf['profile'].info[:controls].each do |ctrl|
    tags = ctrl[:tags]
    if tags && tags[:subsystems]
      unless tags[:subsystems].empty?
        control ctrl[:id]
      end
    end
  end
end
```

## Possible Solution

#4502 (extremely naive but does mitigate the issue)

**Comment by clintoncwolfe** [comment]
I'm not able to reproduce this error, using inspec 4.16.5 (as reported) nor 4.17.4 (current tip), a wrapper profile with the above code, and a single dependency tracking master of https://github.com/simp/inspec-profile-disa_stig-el7 . I'm not setting any inputs, though I note that the disa_stig_el7 profile has numerous inputs.  Is there more to this?

**Comment by trevor-vaughan** [comment]
@clintoncwolfe There really shouldn't be. If you have virtualbox and vagrant installed, you can try the following from the https://github.com/simp/inspec-profile-disa_stig-el7 repository:

* `bundle update`
* BEAKER_inspec_version='4.16.15' BEAKER_destroy=no rake beaker:suites

This should fail and leave the VMs running. (It may dump into a `pry` due to accidental debugging items left in one of our gems)

You can then `cd .vagrant/beaker_vagrant_files/default.yml` and run `vagrant ssh el7`.

You should then be able to `sudo su -`, go to `/tmp` and execute an inspec test on the inheriting profile.

**Comment by trevor-vaughan** [comment]
@clintoncwolfe Spoke too soon, still broken even with the change in https://github.com/simp/inspec-profile-disa_stig-el7/pull/106

**Comment by clintoncwolfe** [comment]
Well, following those instructions, the converge failed for me:
```
An error occurred while loading ./spec/acceptance/suites/default/10_oscap_apply_spec.rb.
Failure/Error: install_puppet
TypeError:
  no implicit conversion of Symbol into Integer

# ./spec/spec_helper_acceptance.rb:13:in `block in <top (required)>'
# ./spec/spec_helper_acceptance.rb:8:in `each'
```
which is part of the VM setup, not part of the inspec run.  Several similar errors occurred.

**Comment by trevor-vaughan** [comment]
Hmm...what version of ruby? I'm using 2.5.3 or 2.6.0 via RVM.

**Comment by trevor-vaughan** [comment]
Trying with a completely clean gemset

**Comment by trevor-vaughan** [comment]
@clintoncwolfe No apparent issues with a clean 2.6.0.

**Comment by clintoncwolfe** [comment]
Thanks, I can reproduce the issue on ruby 2.6.2. I'm looking into it.
