### ISSUE TITLE
Improve `inspec compliance`

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4507]
### 🎛 Description

This is an Epic to collect together various improvements to the `inspec compliance` subcommand. Generally, the subcommand has been undermaintained, and could use some attention.

### 🌍
 InSpec and Platform Version

4.16.0

Aha! Link: https://chef.aha.io/features/SH-2530

**Comment by kekaichinose** [comment]
Closing this as we need more detail around the customer outcome we're trying to drive on this or if it's more just an internal improvement, of which we will need to revisit prioritization on.

I'll cut a new epic with proper scoping around this when we revisit this. Closing.
