### ISSUE TITLE
`os` resource not accessible within a `describe`

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#451]
For the purpose of not having to duplicate `describe` items, would it be possible to make the `os` resource available inside a describe?  This way you  can write a concise and elegant test that handles different architectures and releases, all from within a single `describe`. 

For example:

```
describe file('/etc/ssh/sshd_config') do
  its('content') { should match('ChallengeResponseAuthentication no') }
  its('content') { should match('UsePAM yes') }
  its('content') { should match('PasswordAuthentication no') }
  if os.redhat?
    its('content') { should match("Subsystem sftp /usr/libexec/openssh/sftp-server") }
    if os[:release].to_f >= 7
       its('content') { should match("UsePrivilegeSeparation sandbox") }
       its('content') { should match("HostKey /etc/ssh/ssh_host_rsa_key") }
       its('content') { should match("HostKey /etc/ssh/ssh_host_ecdsa_key") }
    end
  end
end
```

**Comment by jeremymv2** [comment]
@chris-rock 
For large organizations that have many existing serverspec tests that may include DSL syntax like the above, this will be enticing; making their conversion from serverspec to inspec easier and more delightful.

**Comment by arlimus** [comment]
Discussion moved to #809 as it potentially solves this problem.
