### ISSUE TITLE
Interface resource cannot check addresses on EC2 instances 

### ISSUE THREAD

**Issue by apr-1985** [inspec/inspec#4522]
Getting the error 
```
expected Interface eth0 to respond to has_an_ipv4_address?
```
when running 

```
inspec> describe interface('eth0') do
inspec>   it { should have_an_ipv4_address }
inspec> end
```
On an EC2 Instance (tried Centos 7.7, RHEL7 and amazon linux 2)

# Describe the problem
The instance I am running against definitely has an IPV4 address as you can see here:
```
inspec> a = interface('eth0')
=> Interface eth0
inspec> a.ipv4_addresses
=> ["10.xxx.xxx.xxx"]
```
So I would expect this test to pass, however it is failing:
```
You are currently running on:

    Name:      redhat
    Families:  redhat, linux, unix, os
    Release:   7.7
    Arch:      x86_64

inspec> describe interface('eth0') do
inspec>   it { should have_an_ipv4_address }
inspec> end

Profile: inspec-shell
Version: (not specified)

  Interface eth0
     ×  should have an ipv4 address
     expected Interface eth0 to respond to `has_an_ipv4_address?`

Test Summary: 0 successful, 1 failure, 0 skipped
```
Cant see why this is happening as the interface object has the data required to answer the question correctly

**Comment by apr-1985** [comment]
```
inspec --version
4.17.7
```

**Comment by apr-1985** [comment]
Looks like another method hasnt been implemented on the interface 
```
inspec> a.has_an_ipv4_address?
NoMethodError: undefined method `has_an_ipv4_address?' for Interface eth0:#<Class:0x00007fe26f369850>
from (pry):7:in `load_with_context
```
along with the name method 
https://github.com/inspec/inspec/issues/3920

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #138](https://github.com/inspec/inspec-aws/issues/138) via [**ZenHub**](https://www.zenhub.com/)
