### ISSUE TITLE
Migrate docs to Hugo

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4528]
### 🎛 Description

Docs team has started an initiative to migrate Inspec's docs to a Hugo template. This will make it much easier for the docs team to keep the Inspec docs up to date and to start making our docs more consistent across Chef.

As part of this project, there's some work that the UI team can help with: building the Hugo template (including html, css, and js) for the Inspec docs (https://www.inspec.io/docs/), which are currently written in Ruby. Most of the work will be learning how to write a Hugo template, then it’s a matter of copy-pasting the content over.

@tduffield worked on the A2 docs Hugo template and has offered to be a resource to whoever works on this.

### Links
* [Inspec Docs](https://www.inspec.io/docs/)
* [Running Inspec Docs locally](https://github.com/chef/compliance-team/blob/master/maintaining-inspec.md#the-inspecio-website)
* [Hugo Template Docs](https://gohugo.io/templates/introduction/)

Aha! Link: https://chef.aha.io/features/SH-346

**Comment by mjingle** [comment]
Chef InSpec Docs was successfully migrated to Hugo, so I am closing this issue.
