### ISSUE TITLE
InSpec 4.17.x breaks only_if on non-os platforms

### ISSUE THREAD

**Issue by slevenick** [inspec/inspec#4541]
# Describe the problem
I'm a contributor to the inspec-gcp resource pack. We frequently use only_if in integration tests to skip tests based on environment variables (if a user needs extra permissions to be able to run certain tests)

Since the 4.17.7 release my integration test pipeline has been broken with the following error message:
`Unsupported resource/backend combination: os / gcp. Exiting.`
This was introduced in this PR: https://github.com/inspec/inspec/pull/4214/files#diff-97cbc2a879b4ce388a6c777552c2b542

This seems to be caused by the resource defaulting to an os resource if a control is to be skipped in the following file:
https://github.com/inspec/inspec/blob/592f091d9571140e0eb272c42b8ddaca353986c3/lib/inspec/rule.rb#L232

I imagine this was silently failing the `check_supports` call and working as intended in previous versions until the error started to be thrown due to PR #4214 

I believe this would cause similar issues on other resource packs that do not support the OS platform and use the skip functionality.

## Possible Solution

I would suggest defaulting to a resource that does not need explicit platform support

**Comment by clintoncwolfe** [comment]
Thanks for the report! As the you suggest, the problem is that the `os` resource has platform restrictions. In several places, when InSpec needs a "generic" resource to do something, `os` is used - but here that adds constraints and breaks your pipeline. 

Maybe we should invent a "generic" resource that does nothing?

**Comment by zenspider** [comment]
The comment right above line 232 is telling:

```ruby
      # TODO: we use os as the carrier here, but should consider
      # a separate resource to do skipping
      resource = rule.os
```
