### ISSUE TITLE
waiver_data hash in control results 

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#4546]
I tried the new `--waiver-file` option with inspec v17.7.0 and noticed that the `waiver_data` object is being added to the results array. Is the `waiver_data` object going to be the same across all results of a control?

# Describe the problem

I'm concerned that the report size will inflate a lot if we add the `waiver_data` object in each result of a control.

Sample output with two results for a control:
```json
{
  "platform": {
    "name": "mac_os_x",
    "release": "17.7.0"
  },
  "profiles": [
        {
          "id": "pro1-con3",
          "title": "Profile 1 - Control 3",
          "desc": null,
          "descriptions": [],
          "impact": 1,
          "refs": [],
          "tags": {},
          "code": "control 'pro1-con3' do\n  impact 1\n  title 'Profile 1 - Control 3'\n  describe file('/tmp/33333') do\n    it { should exist }\n  end\n  describe file('/etc/44444') do\n    it { should exist }\n  end\nend\n",
          "source_location": {
            "line": 18,
            "ref": "/Users/apop/git/mycompliance-profile/myprofile1/controls/profile1.rb"
          },
          "results": [
            {
              "status": "failed",
              "code_desc": "File /tmp/33333 should exist",
              "run_time": 0.015581,
              "start_time": "2019-09-27T18:03:26+01:00",
              "message": "expected File /tmp/33333 to exist",
              "waiver_data": {
                "expiration_date": "1977-06-01",
                "justification": "Necessity",
                "skip": true,
                "skipped_due_to_waiver": false,
                "message": "Waiver expired on 1977-06-01, evaluating control normally"
              }
            },
            {
              "status": "failed",
              "code_desc": "File /etc/44444 should exist",
              "run_time": 0.00019,
              "start_time": "2019-09-27T18:03:26+01:00",
              "message": "expected File /etc/44444 to exist",
              "waiver_data": {
                "expiration_date": "1977-06-01",
                "justification": "Necessity",
                "skip": true,
                "skipped_due_to_waiver": false,
                "message": "Waiver expired on 1977-06-01, evaluating control normally"
              }
            }
          ]
        }
  ]
}
```

I took one of the profiles shipped with Automate: `cis-centos6-level2-server-2.0.2-2.tar.gz` and ran it against a vanilla CentOS 6.7.

I took the result and sorted the controls by the number of results. One control had 120 results, but here are the top 10 controls with the most results:

```
120  xccdf_org.cisecurity.benchmarks_rule_4.2.4_Ensure_permissions_on_all_logfiles_are_configured
63  xccdf_org.cisecurity.benchmarks_rule_6.2.10_Ensure_users_dot_files_are_not_group_or_world_writable
45  xccdf_org.cisecurity.benchmarks_rule_6.2.8_Ensure_users_home_directories_permissions_are_750_or_more_restrictive
42  xccdf_org.cisecurity.benchmarks_rule_5.4.1.2_Ensure_minimum_days_between_password_changes_is_7_or_more
42  xccdf_org.cisecurity.benchmarks_rule_5.4.1.1_Ensure_password_expiration_is_90_days_or_less
37  xccdf_org.cisecurity.benchmarks_rule_6.2.6_Ensure_root_PATH_Integrity
26  xccdf_org.cisecurity.benchmarks_rule_4.1.12_Ensure_use_of_privileged_commands_is_collected
25  xccdf_org.cisecurity.benchmarks_rule_5.4.1.4_Ensure_inactive_password_lock_is_30_days_or_less
25  xccdf_org.cisecurity.benchmarks_rule_5.4.1.3_Ensure_password_expiration_warning_days_is_7_or_more
24  xccdf_org.cisecurity.benchmarks_rule_6.2.1_Ensure_password_fields_are_not_empty
```

Users and password controls(i.e. rule_6.2.10, 6.2.8, 5.4.1.2, 5.4.1.1) can have thousands of results for production systems.

## Possible Solution
Can we add the `waiver_data` object at the control level, same as `id`, `title`, `desc`

**Comment by kekaichinose** [comment]
Going to attach a screenshot of a side-by-side of the profile and it's results
![Screen Shot 2019-09-27 at 9 46 20 AM](https://user-images.githubusercontent.com/50633219/66067470-7eb40b00-e500-11e9-814e-6335f8485b3e.png)

**Comment by kekaichinose** [comment]
@alexpop I'm pushing this up in the priority to get this addressed. Thanks for filing this!

**Comment by clintoncwolfe** [comment]
From discussion with @alexpop and others, we came away with these action items:
 * in the report, move the `waiver_data` from the result-level to the control-level
 * in the input waiver file, rename the `skip: yes` subfield to be `run: no` and invert its meaning
 * in the report, ensure that when waiver data is absent, the data is always represented as `waiver_data: {}`, not as null or as fully absent.
 * Clarify docs to ensure that yes/no/true/false are all accepted for the `run:` subfield option.
