### ISSUE TITLE
lib/inspec/objects/*.rb are problematic

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4555]
1. They're not namespaced properly. They should be `Inspec::Object::*`. As such, they can re-open things.
2. They have inconsistent protocols. `to_hash` is defined in most (tho not tested) but it is not evident that they're needed (until you look at inspec-scap?)
3. They're in the wrong project. This code is only used by inspec-scap, so it should move there. See #4455.

For #1, we need to add the namespace to at least `Inspec::Input` because that definitely collides... but when that happens, we need to duplicate `to_hash` because that is being used in inspec See #4545. 

For #2 ... I think this should be determined by the inspec-scap team. They should probably move over? I think? Again, this is only a problem for #1 wrt Input.

@james-stocks I need your eyeballs and judgement on this (and the others).

**Comment by james-stocks** [comment]
Yes these should move to `inspec-scap` or a separate gem. The latter could be open source and automatically tested each time InSpec changes.
I need to find some time to get this done.

**Comment by zenspider** [comment]
I'm happy to do both PRs and submit them.

**Comment by aaronlippold** [comment]
These should be moved to a separate gem as they are licensed under Apache-2.0 and inspec-scap is not yet apache-2.0

**Comment by zenspider** [comment]
This is fixed in my destination PR and isn't really an issue on InSpec.
