### ISSUE TITLE
Apt is failing to understand urls

### ISSUE THREAD

**Issue by xorima** [inspec/inspec#4559]
# Describe the problem
APT resource to accept urls as valid

## Example:
build:
https://app.circleci.com/jobs/github/sous-chefs/aptly/460
```
Profile: tests from {:path=>"/home/circleci/project/test/integration/default"} (tests from {:path=>".home.circleci.project.test.integration.default"})
Version: (not specified)
Target:  docker://f3dda5e935f286202f91fa45874e71bf2d44651de91c60ef8b004d8c08177a05

  ×  Default actions: Apt Repository http://repo.aptly.info/ (2 failed)
     ×  Apt Repository http://repo.aptly.info/ should exist
     bad URI(is not URI?): "\"http://repo.aptly.info/\""
     ×  Apt Repository http://repo.aptly.info/ should be enabled
     bad URI(is not URI?): "\"http://repo.aptly.info/\""
```
Code: https://github.com/sous-chefs/aptly/blob/master/test/integration/default/default_test.rb#L7
```
  describe apt('http://repo.aptly.info/') do
    it { should exist }
    it { should be_enabled }
  end

```

## Version:
https://packages.chef.io/files/current/chefdk/4.4.37/ubuntu/16.04/chefdk_4.4.37-1_amd64.deb

## Possible Solution
Unsure, will need to look through the code, but appears like you are keeping quotes that are not required?

**Comment by zenspider** [comment]
Bad commit: https://github.com/inspec/inspec/commit/1aebd53314832a8c58134bf0989c4ba08d8a5276

The `URI.parse` call is blowing up because the file format has '"'s in it.
