### ISSUE TITLE
cannot use inspec on a vm with no internet access inside of gcp

### ISSUE THREAD

**Issue by davidmitchell2019** [inspec/inspec#4561]
Hi I am trying to run inspec from a machine inside GCP that has no internet access, I want to run some controls from within the vm to test that gcp resources exist

**Comment by davidmitchell2019** [comment]
seems as though it cannot pull the libraries, get unknown method, can you add the libraries in a local folder and pull them from there?

**Comment by davidmitchell2019** [comment]
Any problems with hitting the API's from within GCP? I have used Terraform in this scenario and that works fine, private Google access is enabled

**Comment by clintoncwolfe** [comment]
This is actually the same problem as #4519 - we'll solve it there, thanks.
