### ISSUE TITLE
Array be_empty Matcher Not Working Inside describe.one Block, "stack level too deep" Error

### ISSUE THREAD

**Issue by tderanek** [inspec/inspec#4582]
The Array be_empty matcher is not working from inside a describe.one block. When attempting to leverage this pattern, it consistently fails with a "stack level too deep" error

# Describe the problem
Here is an inspec shell session which exemplifies the issue.
```
$ inspec version
4.17.17

$ inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    Name:      mac_os_x
    Families:  darwin, bsd, unix, os
    Release:   18.7.0
    Arch:      x86_64

inspec> describe.one do
inspec>   describe [1,2,3] do
inspec>     it { should_not be_empty }
inspec>   end
inspec> end

Profile: inspec-shell
Version: (not specified)

  [1, 2, 3]
     ×  stack level too deep

Test Summary: 0 successful, 1 failure, 0 skipped
```

## Possible Solution
I can work around this issue by comparing the subject array to a new, empty array for now. It would be nice for this to be fixed though. The issue is not present in version 4.16.0 of Inspec. I tested the same pattern in the inspec shell for that version.

**Comment by frezbo** [comment]
Fixed in #4565

**Comment by zenspider** [comment]
That should be released today. Closing.

**Comment by tderanek** [comment]
Truly incredible response time. It has already been handled. Thank you!
