### ISSUE TITLE
Links not working on InSpec.io Home Page

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4589]
### 🎛 Description

🐛 bug report

When you go to the inspec.io home page, the following links do not appear to be clickable:
* The two links in the hero image/banner
  * download inspec 4
  * browse tutorials
* the platform links under section **Features of Chef InSpec**

### 🌍 InSpec and Platform Version

N/A - this is related to the website, not the application

### 🤔 Replication Case

Go to https://www.inspec.io and review the above links

### 💁 Possible Solutions

I believe the function that generates these links was impacted by the recent documentation updates. If we start there, we should be able to figure out where the breakage started.

### 💻 Stacktrace

N/A

**Comment by ejaronne** [comment]
This is confusing a lot of the folks we work with. Is there any kind of ETA you can provide?

**Comment by zenspider** [comment]
Pretty sure this is the same as #4590.

**Comment by kekaichinose** [comment]
I validated this was fixed by #4608

I don't believe the platform links worked before. Perhaps they should just be images, and not clickable, but that's outside the scope of this issue. Closing.
