### ISSUE TITLE
search bar on website broken if you click anywhere

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4590]
When you bring up the doco there is a search bar at the top and the cursor is put into it. If you click anywhere, including in the search bar, you lose focus and can't get it back.

**Comment by kekaichinose** [comment]
@zenspider This was partially fixed by #4608

In verifying this, I found that the search bar button (i.e. magnifying glass) still doesn't work, but you can get around this by using the Enter key. Still, it's UI related, but let me know if you think that should be a different issue.

**Comment by zenspider** [comment]
That seems entirely unrelated. Closing and filing a new issue
