### ISSUE TITLE
move all/most `inspec check` validations to a rubocop plugin

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4593]
Related to the security problems mentioned in #4592, we could just do a simple ruby syntax check (eg literally just `ruby -c #{path}`) and push the checks that it does to an out-of-band static checker like rubocop.

**Comment by zenspider** [comment]
This is a very light weight alternative to #3600.

**Comment by clintoncwolfe** [comment]
@tas50 has suggested this could be a subset of cookstyle rules.

**Comment by aaronlippold** [comment]
We have also talked about writting rubocop plugins for inspec - mainly around a 'styleguide' enforcement of controls. We are going to have some of the summer folks work on it but will reference this issue in ours.

**Comment by clintoncwolfe** [comment]
#5112 covers this, closing
