### ISSUE TITLE
Allow custom profile metadata

### ISSUE THREAD

**Issue by kevin-j-smith** [inspec/inspec#4605]
## Detailed Description
Similar to: https://github.com/inspec/inspec/issues/3181

Allow custom 'tags' to be added to inspec.yml and then reported into json reporter.  We also have the need for ASSET information to be added to the report, much like you did with json-automate.  Having custom reporters would cover that, but not the case where we need to track additional information about the profile (static) and visualize that in the reports.

## Context
Re-compile STIG Benchmark Title as it is in StigViewer.  IE: `Oracle Linux 6 Security Technical Implementation Guide :: Version 1, Release: 16 Benchmark Date: 26 Jul 2019`

I can certainly build, in inspec.yml, the name or title to be this exact line (which is our work-around), but I would like to stitch the pieces together and keep everything separate.   Which I could use `title: Oracle Linux 6 Security Technical Implementation Guide`' and `version: 1.16.20190526`, or some variant`.  What I would like to see is Release and Benchmark Date be available in inspec.yml and any other corporate customization that we are needing for our internal reporting.

## Possible Implementation
As to the linked issue the inspec.yml could have a tags section that would be present in the report.  Or keep managing each specifc key:value and add release and benchmark_date.

**Comment by aaronlippold** [comment]
I think we should just add the passthrough field to the core json reporter and review #3181 and #3906

**Comment by aaronlippold** [comment]
Feel free to drop me an email on Google lippold@gmail.com and we can chat
about it and then put in a proposal.
