### ISSUE TITLE
Feature Request: Check for the newest package 

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#4606]
## Detailed Description

Package resources should have a 
`  its('version') { should be_latest}
`
## Context

Now with a recent `sudo` vulnerability this would be a great way to make sure a package is at it's latest version.

**Comment by kekaichinose** [comment]
@kmf What are you thinking should be the authority here? The local package DB or InSpec?

**Comment by kmf** [comment]
I think it should use the Package DB

**Comment by kmf** [comment]
stale :(
