### ISSUE TITLE
Long execution times when tests are executed remotely via SSH using the --sudo flag.

### ISSUE THREAD

**Issue by roxyland** [inspec/inspec#4614]
A simple control which tests the permissions on a bunch of home directories in a loop, takes a bit over 10 seconds to run without sudo. But with --sudo, it takes over 4 minutes to complete.

`  # Check homedirs for userids > 500
  homedirs = command("lsuser -a id home ALL|sed 's/id=//g;s/home=//g'|awk '{if($2 > 500) {print $NF}}'").stdout.strip.split("\n")

  homedirs.each do |homedir|
    next if homedir =~ /^\/$/ # Skip if /
    next if !Dir.exist?(homedir)
    describe file(homedir) do
      it { should_not be_more_permissive_than('0770') }
    end
  end`

Is inspec calling sudo separately for each iteration of the loop ? If so is there someway to reduce the number of calls to sudo. Our sudo configuration is stored within LDAP, so it would be great if there weren't so many sudo calls because at this rate a full suite of tests will take hours to complete.

InSpec and Platform Version
Inspec Version: 4.18.0 running on RHEL7.5 (3.10.0-862.14.4.el7.x86_64)

Reproduced on:
RedHat Enterprise Linux >7.0
AIX 7.1, 7.2

**Comment by kekaichinose** [comment]
@roxyland How many directories are you iterating over?

**Comment by roxyland** [comment]
There 74 directories for the run above where it took over 4 minutes with sudo and ~10 secs without it.

**Comment by clintoncwolfe** [comment]
This is by design. Each call to command() is a separately authenticated invocation, which makes sense from a security context - we can't tell what you might change in the invocation from one invocation to the next, unless it is exactly the same, in which case we offer to cache the result using the --backend-cache option.
