### ISSUE TITLE
Gem resource failing with undefined method `installed?`

### ISSUE THREAD

**Issue by damacus** [inspec/inspec#4623]
# Describe the problem

The following resource has just started to fail and the only thing we've changed is the Inspec version

```ruby
  describe gem('rake') do
    it { should be_installed }
  end
```

## Output 

```text
     ×  false should be installed
     undefined method `installed?' for false:FalseClass
     Did you mean?  instance_of?
```

## Inspec Version

Latest in the ChefDK as of 2019-10-21

## Related Builds

Here's a related PR that was failing and commenting out the test worked: 

- https://github.com/sous-chefs/nginx/pull/522

**Comment by mcascone** [comment]
I see this is closed, but i see a very similar issue with this gem test, just in case it's a case that wasn't fixed:

```ruby
control 'Gems' do 
  title 'Gems'
  describe gem('knife-vrealize') do 
    it { should be_installed }
  end
end
```

tests as:
```
  [FAIL]  Gems: Gems
     [FAIL]  true should be installed
     undefined method `installed?' for true:TrueClass
     Did you mean?  instance_of?
```

```
> chef -v
ChefDK version: 4.5.0
Chef Infra Client version: 15.4.45
Chef InSpec version: 4.18.0
Test Kitchen version: 2.3.3
Foodcritic version: 16.1.1
Cookstyle version: 5.9.3
```
