### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#464]
Hi there
I just wanted to say a quick “Thank You” for your effort with chef-compliance and inspec.  I’m sold on the product and can see the potential and I’ve been able to successfully demonstrate its value to my manager. 

Even though I wasn’t able to directly add my firewalls as nodes to chef compliance (yet #448 :)  I was able to come up with a method of running my compliance checks via a proxy.

So my policy was made up of just over 50 compliance checks, these checks would take someone just over 30mins to complete manually, inspec did it in 2mins.  When I scale that to review all the firewalls within my env I’m saving about 9MD’s each time I run a report.

So thanks very much for all your effort.

Better get back, I’ve got the bug now :)

Thanks

**Comment by chris-rock** [comment]
@username-is-already-taken2 That is awesome. We would love to ship you some swag like T-Shirts. Please send an email to chartmann@chef.io

**Comment by arlimus** [comment]
@username-is-already-taken2 Thank you for your awesome feedback, much appreciated!! :smile: 
That's some extra incentive for solving that other issue

**Comment by chris-rock** [comment]
:100:

**Comment by conorsch** [comment]
This isn't even my project, but what a heartwarming issue. Thanks for the cheer, @username-is-already-taken2!

**Comment by arlimus** [comment]
I'm currently cleaning up issues back to front.
Somehow can't get to close this one 😁 
Keep it up everyone 🚀 !!

**Comment by miah** [comment]
I do appreciate the sentiment here, but I'm going to close this. Everybody should feel free to re-open and add additional Thank You's in the future <3
