### ISSUE TITLE
The "remote" HTTP resource caches responses across different instances

### ISSUE THREAD

**Issue by multani** [inspec/inspec#4661]
We are using the InSpec HTTP resource to ensure the configuration of our AWS Load Balancer have been set correctly, and that the load balancer is actually capable of reaching its backend.

The creation of the load balancer can take some time, so we wanted to have some kind of retry mechanism using `rspec/retry` and be able to write something like this:

```ruby
control 'ALB configured correctly' do
  describe http(alb_endpoint) do
    # Waits until the ALB is active and targets are registered
    its('status', retry: 60, retry_wait: 5) { should eq 200 }
  end
end
```

This doesn't work, as the `http` resource is executed once, the result is cached, and it never returns the new HTTP responses after the first one (which may be 502 if the backends are not ready yet for example.)

Instead, we wrote a small library which re-executes the HTTP resource every time we want to assert its response status (we are OK with that).

The library:
```ruby
class RetryableHTTP < Inspec.resource(1)
  name 'http_retry'

  def initialize(url)
    @url = url
  end

  def status
    h = inspec.http(@url)
    puts "URL: #{@url}, status: #{h.status}"
    h.status
  end
end
```

Used like this:

```ruby
control 'ALB configured correctly' do
  describe http_retry(alb_endpoint) do
    # Waits until the ALB is active and targets are registered
    its('status', retry: 60, retry_wait: 5) { should eq 200 }
  end
end
```

This works correctly using the "local HTTP resource" (which uses Faraday):

```
[...]

RSpec::Retry: 3rd try inspec/controls/alb.rb:23
getting status
doing request
URL: http://foobar-123456789.eu-central-1.elb.amazonaws.com, status: 502
getting status

3rd Try error in inspec/controls/alb.rb:23:

expected: 200
     got: 502

(compared using ==)


RSpec::Retry: 4th try inspec/controls/alb.rb:23
getting status
doing request
URL: http://foobar-123456789.eu-central-1.elb.amazonaws.com, status: 200
getting status

Profile: default
Version: (not specified)
Target:  local://

  ✔  ALB forwards correctly2: application_load_balancer
     ✔  application_load_balancer status should eq 200

Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 1 successful, 0 failures, 0 skipped
```

However, when using the remote mode of InSpec, it switches to "remote HTTP resource" (which uses curl), which seems to cache the result of these HTTP calls for ever. Thus, when the load balancer status changes, InSpec doesn't pick it up, until the InSpec process restarts completely. 

It looks like the `http(URL)` response is cached for ever, for that specific URL value.

We couldn't really figured out where this cross-instance cache behavior was coming from (my Ruby skills are a bit limited), although [we found a shortcut during the actual curl call](https://github.com/inspec/inspec/blob/a4f4fe5/lib/inspec/resources/http.rb#L193:L197).

## Possible Solution

We don't have any solution right now, but with some guidance, we'd be glad to propose a fix for that problem (ping @kkusmin).

**Comment by zenspider** [comment]
I imagine this is going to be marked as "works as intended", but here are my thoughts:

I don't think you need to write a full new resource. Instead, I think you can pull down the way you're instantiating your resources:

```ruby
#original
  describe http(alb_endpoint) do
    # Waits until the ALB is active and targets are registered
    its('status', retry: 60, retry_wait: 5) { should eq 200 }
  end
```

vs

```ruby
  describe alb_endpoint do
    # Waits until the ALB is active and targets are registered
    it() { http(alb_endpoint).status.should eq 200 }
  end
```

This at the very least wouldn't cache the http resource.

**Comment by kkusmin** [comment]
Thank you for the suggestion. Unfortunately, it doesn't work as it complains about the method `http' being undefined when moving it into the ```it()``` block. I also don't fully understand how it is intended to work, if you could elaborate more, it would be much appreciated.

**Comment by multani** [comment]
We are not using this anymore.
