### ISSUE TITLE
Fix breakage on ruby 2.7

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4669]
We have 2.7 running on CI but it is a soft failure and is breaking in many areas.

**Comment by zenspider** [comment]
## Upstreams:

### In Progress

https://github.com/flori/json/pull/388 or https://github.com/flori/json/pull/389 (merged and backported, but not released)

### Done

https://github.com/bblimke/webmock/issues/861 => https://github.com/bblimke/webmock/pull/860 (merged)

https://github.com/fbernier/tomlrb/pull/22 (merged! & released!!!)

https://github.com/piotrmurach/strings/issues/9 => https://github.com/piotrmurach/strings/pull/10 (merged & released)

https://github.com/piotrmurach/necromancer/issues/6 -> https://github.com/piotrmurach/necromancer/pull/7 (merged & released)


https://github.com/lostisland/faraday/pull/1009 (merged & released!)

**Comment by ixti** [comment]
Please upgrade to master branch or 4.3.0 release (both have fixes for ruby-2.7 support)

**Comment by kekaichinose** [comment]
@james-stocks not sure if this helps, but this was the epic for Ruby 2.7 work. It seemed to have some upstream dependencies that I'm unsure the status of. Not sure if this helps

**Comment by kekaichinose** [comment]
Just chatted with @james-stocks and he'll follow up on this as we think this work has already been completed.

**Comment by james-stocks** [comment]
I checked yesterday, Ruby 2.7 is now running and passing in CI for every commit.
