### ISSUE TITLE
Documentation Improvement: "See Also" Section

### ISSUE THREAD

**Issue by sbonds** [inspec/inspec#4671]
## Detailed Description

While the search works nicely, this can also be somewhat self-limiting as the search terms that come to mind while reading a resource document are likely to lead back to the same resource. The resource documentation would benefit from some human minds providing links between related resources.

## Context

Showing similar resources would be helpful to people new to Inspec since we don't yet know what all is available. This can lead to some creative solutions using excessive regex matching on files when there's a perfectly good resource available, but which we, in our ignorance, don't yet know about. Linking resources via "See Also" allows that exploration to continue in productive directions.

## Possible Implementation

It looks like the doc sections get included in the `Inspec::Resource.registry`, which is more complex than just a simple document-- otherwise this might have been a pull request instead of an Issue.

For example in `shell.rb` I found this code which shows the integration between the resource sections and its documentation:

```ruby
#{mark 'Description:'}

#{Inspec::Resource.registry[resource].desc}

#{mark 'Example:'}
#{print_example(Inspec::Resource.registry[resource].example)}

#{mark 'Web Reference:'}

http://inspec.io/docs/reference/resources/#{resource}
```

This suggested that the actual implementation would benefit from some review by someone familiar with how Inspec documentation works.

While I'm glad to help out, and my Inspec beginner perspective is good for finding documentation improvement opportunities, it's not so great for actually implementing them without quite a bit of guidance.

**Comment by miah** [comment]
What you've found is that resources have DSL methods for `desc`ription and `example`.

If you want to update documentation, take a look at the [docs](https://github.com/inspec/inspec/tree/master/docs) directory. All resources are found under there.

**Comment by sbonds** [comment]
@miah While I'm interested in updating the documentation to provide some information on interrelated items, it wasn't clear from reading some example documents what the best way would be to do that.

Using https://github.com/inspec/inspec/blob/master/docs/resources/file.md.erb as an example, it has sections for Availability, Syntax, Properties, Resource Property Examples, and Matchers. These all seem very specific and none seems like an appropriate place to add references to other resources.

Adding a "See Also" section like the below makes the most sense to me but creates a new heading and that seemed to have possible downstream effects:

```md
## See Also

* [directory](https://www.inspec.io/docs/reference/resources/directory/)
```

Would this be an appropriate change to suggest? If not, what might work better?
