### ISSUE TITLE
Rename inspec/resources/gem to inspec/resources/rubygem

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4672]
We're shadowing the global `gem` method. We should rename our resource and provide a deprecated alias.

**Comment by micheelengronne** [comment]
Would it solve https://github.com/inspec/inspec/issues/4623 ?

**Comment by zenspider** [comment]
Already solved, but yes...

**Comment by micheelengronne** [comment]
Solved in what version ? It is not the case in 4.18.24 (the last published gem).
