### ISSUE TITLE
Support or More Transparent Error Handling for .yaml

### ISSUE THREAD

**Issue by B1ue-W01f** [inspec/inspec#4684]
## Detailed Description
I appreciate this is entirely user error due to not 'reading the manual' essentially but, unless I'm mistaken, using a .yaml extension rather than a .yml results in an error identifying an incorrectly configured profile.

## Context
Purely for new users, and despite as a standard keeping to .yml, I accidentally used inspec.yaml for my profile. As a new user I spent quite a bit of time checking syntax within the files only to eventually notice the difference in the extension. 

Not wanting to start a debate between the two, the YAML [FAQ ](https://yaml.org/faq.html) does state .yaml, so it could be understandable to use the .yaml extension.

I appreciate this issue is entirely minor, however, I'd hope at least one of the resolution options would be simple to implement.

## Possible Implementation
Option A - Error handling to identify that no inspec.yml file was found. 
Hopefully, this would highlight that the issue did not relate to the internal contents of the file, but the actual naming of the file itself.

Option B - Implement support for .yaml

**Comment by zenspider** [comment]
`inspec init profile <name>` creates an `inspec.yml` file and avoids this problem entirely.

If I create a new profile, and rename to `inspec.yaml`, I get the following error message on execute:

```
% bundle exec ./misc/run.sh exec blah 
Don't understand inspec profile in blah, it doesn't look like a supported profile structure.
```

That error message indicates that _something_ is wrong with the profile layout, but not specifically what is wrong (because it could be nearly anything).

**Comment by B1ue-W01f** [comment]
Yeah as I said, I appreciate there are ways to avoid it and its entirely human error that results in it... but nevertheless, the format recommended by YAML isn't supported which increases the chance for it to occur and the error message is quite broad making it difficult to identify, particularly when .yaml doesn't stand out as incorrect. 

Seeing as the inspec.yml is an important part of the profile, would it not be easy to implement a 'no yml file in folder' error message?
