### ISSUE TITLE
Unable to Handle Spaced Windows File Paths

### ISSUE THREAD

**Issue by jdgoins** [inspec/inspec#469]
The file resource is unable resolve a path with any spaces in it like 'C:\Program Files\test.txt'. 

Both of these assertions fail:

```
describe file('C:\Program Files\test.txt') do
    it { should exist }
    it { should be_file }
end
```

```
inspec version
0.10.1
```

```
inspec detect
{"name":null,"family":"windows","release":"7","arch":null}
```

**Comment by chris-rock** [comment]
Hi @jdgoins Thank you very much for your report. We will double-check why this happens.

**Comment by srenatus** [comment]
As mentioned by @username-is-already-taken2 in #491, this seems to also affects directories.

**Comment by jdgoins** [comment]
Has there been any movemnet on this @chris-rock ? This seems like a pretty fundamental capability.

**Comment by chris-rock** [comment]
@jdgoins Thanks for checking the status. We identified the bug in [train](https://github.com/chef/train). This will be solved with the next release next week.
