### ISSUE TITLE
Fix windows tests in test/functional/inputs_test.rb

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4699]
```
test/functional/inputs_test.rb
131-      it "finds the values and does not issue any warnings" do
132-        output = run_result.stdout
133:        skip_windows!
134-        refute_includes output, "DEPRECATION"
135-        structured_output = JSON.parse(output)
--
142-      it "finds the values but issues a DEPRECATION warning" do
143-        output = run_result.stdout
144:        skip_windows!
145-        assert_includes output, "DEPRECATION"
146-        structured_output = JSON.parse(output.lines.reject { |l| l.include? "DEPRECATION" }.join("\n") )
```

**Comment by clintoncwolfe** [comment]
I have learned the following:

* By simply removing the skips and running the two tests individually, they do indeed pass. So, "yay"!
* The test file appears to hang on user keypress. The run will emit progress dots (`.`), then pause forever, but if you press a key, a dot will immediately be emitted.  I don't know enough enough about multithreading, windows, or how those interact with streams to say anything more, other than reporting a peculiar symptom.
