### ISSUE TITLE
inspec exec ssh custom resources doing shell comands are failing.

### ISSUE THREAD

**Issue by Lemming3842** [inspec/inspec#4738]
[ETA: proper formatting—@zenspider]

When using the directive inspec exec ssh as follows:

```
inspec exec --chef-license accept-silent --no-distinct-exit /rute/profiles/files -t ssh://root@domain -i /authorized_key
```

the test seem to be executing correctly on the destination, but custom resources are failing.

The custom resources are executing shell commands. When inspec is executed in the machine locally, they all pass but with exec ssh it seems that the stdout of this custom resources commands are not being taken into account as follows:
"expected "" to match /file.ini/"

I think the stdout may not be taken into account as I said above. The command executed on libraries/file.rb is:
```ruby
def showFiles
   %x[ls /path/to/files] 
```
(also tried with inspec.command(ls /path/to/file).stdout and did not work, on local machine still works but ssh fails) 

and the check: 
```ruby
describe file.rb do
   $files.each do |param|
      its('showFiles') { should match /#{param}/ }
end
```
where $files is the content of a yaml (a regexp per line with the name of all files under /path/to/file):
```ruby
$files = yaml(content: inspec.profile.file('files.yml')).params
```
an option to set the stdout or to export it somewhere where it could be read maybe?

**Comment by zenspider** [comment]
AFAIK, `file.rb` cannot be the subject of your describe... Are you sure that's the code you're trying to run?

**Comment by zenspider** [comment]
Please submit a gist of the code in question so we can diagnose.

**Comment by Lemming3842** [comment]
Where I said "file.rb" I meant the name given to the library custom resource given by the attribute name (check code below). Maybe was not the best option to use. In this case, all files in order to test this issue would be:

control/exec.rb:
```
$files = yaml(content: inspec.profile.file('files.yml')).params
control "dummytest" do
  impact 1.0
  title "this is the title"
  desc "this is the desc"

  describe show_files(/path/to/files) do
   $files.each do |param|
      its('showFiles') { should match /#{param}/ }
  end
end
```

libraries/show_files.rb:
```
class ShowFiles < Inspec.resource(1)
  name 'show_files'
  def initialize(path)
      @path=path
  end
  def showFiles
     %x[ls #@path]
  end
end
```

create also a .yml with the content of the path, you can create a couple of dummy files and add them as follows; files/files.yml:
```
- dummyfile
- anotherfile

```

All this code when executed inside a container as `inspec exec profiles/test` it works. But if outside of the container and performing `inspec exec ssh` it fails (if i did not mess anything whle copying)

**Comment by Lemming3842** [comment]
Please let me know if you need extra info once u verify it, or if while verifying it some problems raise.

**Comment by clintoncwolfe** [comment]
The reason this is failing is because you are using `%x` to execute a shell command. That will run the shell command on the local host, not on the scanning target, and so the files are not found.

Instead, use `inspec.command("ls #{@path}")`.stdout to remotely execute commands.

**Comment by clintoncwolfe** [comment]
I'm going to close this as answered - happy coding!
