### ISSUE TITLE
aws_vpc resource doesn't support tags, contradicting the documentation

### ISSUE THREAD

**Issue by kief** [inspec/inspec#4744]
# Describe the problem

The [documentation](https://www.inspec.io/docs/reference/resources/aws_vpc/) for the aws_vpc resource lists `tags` as a property. It also includes an example:

```
describe aws_vpc do
  its('tags') { should include(:Environment => 'env-name',
                               :Name => 'vpc-name')}
end
```

When I put this into a control and exec it, I get:

```
  VPC vpc-00950178
     ×  tags
     undefined method `tags' for VPC vpc-00950178:#<Class:0x00007fe0af833d48>
```

When I look at the source, I don't see any code for supporting tags.

## Possible Solution

My ideal would be to have the resource support tags. Failing that, it shouldn't be in the documentation.

Entirely possible I'm missing something, though, happy to be set straight!

**Comment by rmoles** [comment]
Hi @kief, thanks for raising this issue. Inspec support for AWS has now moved to https://github.com/inspec/inspec-aws
If this issue is still relevant, please let us know and we can move it across to the inspec-aws repo.

**Comment by kief** [comment]
I'll go ahead and close this. It looks like it may be supported there, I need to dig into how to make sure I'm using the right resources. Thanks.
