### ISSUE TITLE
Profiles with improperly defined dependencies should fail fast

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4767]
"valid" YAML, but a invalid dependency.

```
depends:
  -name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/v1.9.6.tar.gz
```

**Comment by clintoncwolfe** [comment]
Expanding on that a bit, 

We need to validate that the child of `depends` is an array of hashes. As written below, that gets parsed as a hash with two keys, `-name` and `url`:

```
depends:
  -name: inspec-azure
  url: https://github.com/inspec/inspec-azure/archive/v1.9.6.tar.gz
```

whereas proper format is:
```
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.9.6.tar.gz
```
(an array with one entry, a hash with keys `name` and `url`).
