### ISSUE TITLE
Stop using Rexml

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4770]
Switch to the ox gem (which is reportedly wicked fast) or nokogiri for all things xml.

**Comment by aaronlippold** [comment]
We were using nokogiri before but switched to Rexml as it was part of ruby
core - just as an fysa.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by clintoncwolfe** [comment]
We will continue to use the core REXML library because we do not want to ship a compiled dependency.
