### ISSUE TITLE
Inspec version is default 1.51.25 though downloaded and install new version of inspec 4.18.39

### ISSUE THREAD

**Issue by pbnipun** [inspec/inspec#4773]
## Detailed Description
I can't run commands using the latest version of inspec and by default, it's running on 1.51.25 version on inspec. How can I change it to the latest version?

## Context
To run files in linux

![Capture](https://user-images.githubusercontent.com/25146516/70496941-7c40e380-1b37-11ea-95ab-73979424fc99.PNG)

**Comment by clintoncwolfe** [comment]
Hello! Looks like you have an old version of Chef InSpec installed. We recommend using the [Chef Workstation Installer](https://downloads.chef.io/chef-workstation/0.13.35) for your operating system, which includes up to date versions of all the major Chef tools in an easy to install, OS-specific package.

**Comment by clintoncwolfe** [comment]
You may also try running `which inspec` which will identify which Chef InSpec executable is being located by your shell; you can then uninstall the old version.

**Comment by clintoncwolfe** [comment]
As two solutions have been provided and no update has been received in the last two weeks, I'm going to close this. Please comment if more is needed. Thanks!
