### ISSUE TITLE
Add extra diagnostics for /tmp to BK verify script

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4775]
We're seeing intermittent failures and they almost always involve /tmp... I'm wondering if we're filling it up during parallel functionals or something. I'd like to see `mount`, `ls -la /tmp/`, and probably `df /tmp/`... anything to help us figure this out.

**Comment by zenspider** [comment]
example: https://buildkite.com/chef-oss/inspec-inspec-master-verify/builds/1255#_

**Comment by kekaichinose** [comment]
Extra diagnostic was added to satisfy this issue. Closing.
