### ISSUE TITLE
Write a schema validator for expeditor config

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4783]
Got bit again... see #4781 

I think we can reverse engineer one well enough by looking at:

https://github.com/chef/expeditor/blob/master/components/expeditor-ruby/lib/expeditor/agent/config.rb

and 

https://expeditor.chef.io/docs/reference/configuration/

**Comment by james-stocks** [comment]
Closing - we can re-open if we ever get round to it.
I think there are a couple of gotchas with the Expeditor config check - last week I noticed that it doesn't properly re-check if you push new commits to a PR, a fresh PR was needed for it to check properly.
