### ISSUE TITLE
Add package resource support in FreeBSD

### ISSUE THREAD

**Issue by fzipi** [inspec/inspec#4788]
Executing test using inspec on freebsd fails:
```
...
  ↺  Dovecot service: System Package dovecot (1 skipped)
     ↺  The `package` resource is not supported on your OS yet.
....
```

## Detailed Description
```
control 'Dovecot service' do

  describe package('dovecot') do
    it { should be_installed }
  end
...
```
This should work properly on FreeBSD.

## Context
If you have tests in FreeBSD, well, you kinda want this.

## Possible Implementation
Will attach PR.

**Comment by zenspider** [comment]
Fixed via #4789.
