### ISSUE TITLE
Support broader unix platform in postfix_conf resource

### ISSUE THREAD

**Issue by fzipi** [inspec/inspec#4793]
## Detailed Description

Postfix in unix platforms is exactly the same software, the only thing that needs to be changed is where the config files are stored.

Tested with freebsd and works as expected.

## Context

```
     ×  Control Source Code Error <directory>/test/integration/mail-server/controls/postfix.rb:1 
     Unsupported resource/backend combination: postfix_conf / freebsd. Exiting.
```

## Possible Implementation

Just change `supported platform` from `linux` to `unix` in `lib/inspec/resources/postfix_conf.rb`

Will send a PR with this.

**Comment by zenspider** [comment]
Fixed via #4794.
