### ISSUE TITLE
couldn't find login name -- expanding `~' (ArgumentError)

### ISSUE THREAD

**Issue by rahulthescorpion** [inspec/inspec#4803]
Inspec version - 4.18.51

I am trying to inspec target VM by ssh. 

Command used:
inspec exec /path/script.rb --host <host> --port <port> --backend ssh --user <username> --password <password> --reporter json

I am getting expected output when I execute this command with argument values from terminal(ubuntu). I am using python subprocess to call this and got error.

 /usr/local/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/globals.rb:3:in `home': couldn't find login name -- expanding `~' (ArgumentError)

How come the command is working in terminal and why it is not working in script?

Thanks

**Comment by rahulthescorpion** [comment]
Solved

**Comment by AnmSaiful** [comment]
@rahulthescorpion I'm also going through the same issue with another ruby app. Can you please share your solution or the idea? Thanks in advance. :-)

**Comment by ashima15448** [comment]
@rahulthescorpion Can you please provide the solution as I am also stuck in the same issue
Thank you.

**Comment by kvivek1115** [comment]
I don't have permission to leave it as open!!!

The same issue https://github.com/chef/chef/issues/10565 has been observed when the chef-client running in systemd mode.
