### ISSUE TITLE
`attributes` array in JSON reporter is always empty

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4807]
# Describe the problem

When running the JSON reporter, there should be a data structure describing the inputs under `profiles/*/attributes`. However, when executed (using the example profiles), that array is always empty.

```
inspec exec examples/profile-attribute --reporter json --input user=bob password=password | jq '.profiles[0].attributes'
[] 
```

It does not appear to matter how the inputs are provided - you can set them via metadata, and the reporter still does not have them.  Seems to be a reporter issue.  

There is also no "inputs" key, it's not like it has been renamed.

## Possible Solution

Look into the JSON reporter.

**Comment by kekaichinose** [comment]
Closed by #4883
