### ISSUE TITLE
Inspec Habitat Bin Wrapper Breaks custom SSL and cacerts verification

### ISSUE THREAD

**Issue by drakoswraith** [inspec/inspec#4810]
On Linux, the habitat bin wrapper script for inspec breaks the ability to use custom SSL cert verification by requiring the core/cacerts package, and forcing the value of the SSL_CERT_FILE variable. 

This breaks the ability to use "inspec archive" or to build effortless inspec packages where custom CA certs are required.

# Describe the problem
[In habitat/plan.sh, line 70](https://github.com/inspec/inspec/blob/dc278348b6a26304f1f3d3cdd7cc7b62deda4563/habitat/plan.sh#L70):
export SSL_CERT_FILE=$(pkg_path_for cacerts)/ssl/cert.pem

This line prevents custom cacerts packages from being used by not honoring any existing SSL_CERT_FILE values already set and forcing use of the core/cacerts package that chef/inspec depends on.

## Possible Solution
Check whether SSL_CERT_FILE already has a value, and only set if not set. 
Or
Move the value to a default.toml value so that a user config can override what file to use

**Comment by zenspider** [comment]
There is probably a more elegant way to do this in bash (bash? there's no shebang):

```diff
--- a/habitat/plan.sh
+++ b/habitat/plan.sh
@@ -67,7 +67,7 @@ wrap_inspec_bin() {
   build_line "Adding wrapper $bin to $real_bin"
   cat <<EOF > "$bin"
 #!$(pkg_path_for core/bash)/bin/bash
-export SSL_CERT_FILE=$(pkg_path_for cacerts)/ssl/cert.pem
+export SSL_CERT_FILE="${SSL_CERT_FILE:-$(pkg_path_for cacerts)/ssl/cert.pem}"
 set -e
```

**Comment by TheLunaticScripter** [comment]
I don't think that will work I think this line needs to be removed from the plan so that users can specify the `SSL_CERT_FILE` independently.

**Comment by drakoswraith** [comment]
Confirmed
