### ISSUE TITLE
user resource can't get some information from all numeric user

### ISSUE THREAD

**Issue by ugugugug** [inspec/inspec#4838]
# Describe the problem

I use InSpec 3.9.3.
This is quite simple, user resource can't get some information from all numeric user.
Following results are generated from same control, however only the result of all numeric user is failed.

```
     ✔  User oracle should exist
     ✔  User oracle uid should cmp == "2000"
     ✔  User oracle groups should cmp == ["oinstall", "dba"]
     ✔  User oracle home should cmp == "/home/oracle"
     ✔  User oracle shell should cmp == "/bin/bash"
     ✔  User 100101 should exist
     ✔  User 100101 uid should cmp == "2001"
     ✔  User 100101 groups should cmp == ["numeric"]
     ×  User 100101 home should cmp == "/home/100101"
     expected: "/home/100101"
          got: nil
     (compared using `cmp` matcher)
     ×  User 100101 shell should cmp == "/bin/bash"
     expected: "/bin/bash"
          got: nil
     (compared using `cmp` matcher) 
```

Ofcourse 100101 user has the values home directory and user shells.

```
# grep 100101 /etc/passwd
100101:x:2001:2001::/home/100101:/bin/bash
```
Are there any workarounds except upgrading InSpec?

Regards.

**Comment by clintoncwolfe** [comment]
This is just a suspicion, but have you tried using `eq` rather than `cmp`? `cmp` does a lot of type coercion magic, and is likely getting confused.

**Comment by ugugugug** [comment]
@clintoncwolfe 
Thank you for advice. But after that I tried using `eq`, nothing had changed.

By the way, I found the user resource getting two values 'home' and 'shell' by the command `getent`.
https://github.com/inspec/inspec/blob/master/lib/inspec/resources/users.rb#L449

`man 1 getent` says getent handles all numeric key like UID!
```
          passwd    When no key is provided, use setpwent(3), getpwent(3), and endpwent(3)
                    to  enumerate the passwd database.  When one or more key arguments are
                    provided, pass each numeric key to getpwuid(3) and each nonnumeric key
                    to getpwnam(3) and display the result.
```

Yes `getent` does not display all numeric user information.
```
# getent passwd oracle
oracle:x:2000:2000::/home/oracle:/bin/bash
# getent passwd 100101
# 
```

Although it's in a specification for `getent`,  is it Bug or Specification for InSpec?
I hope InSpec to be able to get all numeric username informations...

**Comment by zenspider** [comment]
I think that if the problem is that `getent` doesn't handle numeric usernames, then the problem is with the OS/distro and there is little we can/will do about that. Have you filed an issue with your OS/distro? Can you link it here for reference please?

**Comment by zenspider** [comment]
Also, please provide info like your OS when filing these types of issues... there's a lot of nuance in these types of things.

**Comment by ugugugug** [comment]
@zenspider 
Sorry and all right about your comment.
This is my OS info:

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
# rpm -qf `which getent`
glibc-common-2.17-157.el7_3.4.x86_64
```

I'm not sure about official `getent` references, 
but maybe "The Linux man-pages project" is useful.
http://man7.org/linux/man-pages/man1/getent.1.html

**Comment by clintoncwolfe** [comment]
My reading of the `getent` manpage is that it is behaving as specified. As this is an edge case and the defective behavior is in the OS vendor, we will not be fixing it in InSpec.
