### ISSUE TITLE
aws_auto_scaling_group - undefined method

### ISSUE THREAD

**Issue by SowDeu** [inspec/inspec#4839]
```
title:'auto_scaling_group'
describe aws_auto_scaling_group('MyAutoScalingGroup') do
    it              { should exist }
 end
```

# Describe the problem
```
from asg.rb:3:in `load_with_context'
 1: from /usr/local/bundle/gems/inspec-4.18.59/lib/inspec/dsl.rb:68:in `method_missing'
/usr/local/bundle/gems/inspec-4.18.59/lib/inspec/dsl.rb:71:in `rescue in method_missing': undefined method `aws_auto_scaling_group' for #<Inspec::ControlEvalContext:0x0000556d6195cdf0> (NoMethodError)
```

Not sure why we are getting above error .Please help.

**Comment by clintoncwolfe** [comment]
Thank you for posting! I am sorry you are having difficulty. `aws_auto_scaling_group` is not part of core InSpec - you must use a profile that depends on the [inspec-aws](https://github.com/inspec/inspec-aws) resource pack. [Here is an example](https://github.com/inspec/inspec-aws#use-the-resources) of doing so.

I hope this helps!

**Comment by SowDeu** [comment]
Thank you very much.
