### ISSUE TITLE
Service Resource does not support yocto linux

### ISSUE THREAD

**Issue by michaellihs** [inspec/inspec#4842]
Provide support for the `service` resource on Yocto-based linux systems.

## Detailed Description
When your target is a Yocto-based linux and you test for a service in your controls, e.g.

```ruby
describe service('docker') do
  it { should be_running }
end
```

you get the following output from inspec

```
↺  The `service` resource is not supported on your OS yet.
```

## Context
Service should be supported on Yocto based linux systems

## Possible Implementation
See Pull Request...

**Comment by zenspider** [comment]
#4843 has been merged... but this wasn't linked in for automatic closure...
