### ISSUE TITLE
Need help - how to integrate inspec tests into gitlab pipeline

### ISSUE THREAD

**Issue by sesha27** [inspec/inspec#4851]
Hi ,

I am new to inspec and in my work place we are trying to implement inspec testing framework for aws , we have tests created in gitlab and now we need to run in pipeline .

Kindly help me understand , how this can be achieved. If any post available for this do redirect me .

Thank you in advance.

Thanks sorted..
Regards,
Sesha

**Comment by aaronlippold** [comment]
Please hit me up on slack
