### ISSUE TITLE
Use Windows Ruby Installer image from S3 Cache

### ISSUE THREAD

**Issue by btm** [inspec/inspec#4888]
In https://github.com/chef/release-engineering/issues/864 we manually put a copy of the Windows Ruby Installer in the S3 cache to avoid the rate-limiting from Github. We need to switch to using this URL to download the Installer now:

https://public-cd-buildkite-cache.s3-us-west-2.amazonaws.com/rubyinstaller-devkit-2.6.5-1-x64.exe

- omnibus/omnibus-test.ps1
- .expeditor/buildkite/artifact.habitat.test.ps1

**Comment by james-stocks** [comment]
I believe this is now done - `.expeditor/buildkite/artifact.habitat.test.ps1` gets the installer from S3 via aws cli
`omnibus/omnibus-test.ps1` was changed by @christopher-snapp to simply use the embedded Ruby instead of fetching and installing it.
