### ISSUE TITLE
 undefined method `Transmit Hash Policy' for Bond bond0:#<Class:0x00000000054d9f90>

### ISSUE THREAD

**Issue by jayan800** [inspec/inspec#4890]
# Bond resource and check for bond policy is throwing error
When I'm using the bond resource and check for bond policy, I'm getting a error message.
Error Message: 
undefined method `Transmit Hash Policy' for Bond bond0:#<Class:0x00000000054d9f90> 

The complete output is as following:

```
Profile: tests from 6_network.rb (tests from 6_network.rb)
Version: (4.18.24)
Target:  ssh://test@test.example.com:22

  ×  6.1 Bonding: Ensure bond0 is present (2 failed)
     ✔  Bond bond0 should exist
     ✔  Bond bond0 mode should eq "IEEE 802.3ad Dynamic link aggregation"
     ×  Bond bond0 Transmit Hash Policy
     undefined method `Transmit Hash Policy' for Bond bond0:#<Class:0x00000000054d9f90>
     ×  Bond bond0 MII Status
     undefined method `MII Status' for Bond bond0:#<Class:0x00000000054d9f90>


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 2 successful, 2 failures, 0 skipped
```

Below is the bond output from the system:

```
cat /proc/net/bonding/bond0
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: IEEE 802.3ad Dynamic link aggregation
Transmit Hash Policy: layer3+4 (1)
MII Status: up
```

Inspec Bond profile details:

```
describe bond('bond0') do
    it { should exist }
    its('mode') { should eq 'IEEE 802.3ad Dynamic link aggregation' }
    its('Transmit Hash Policy') { should eq 'layer3+4 (1)' }
    its('MII Status') { should eq 'up' }
  end
end
```

Can any one help on this

**Comment by james-stocks** [comment]
`its('Transmit Hash Policy')` is not valid InSpec
The string passed to `its` needs to be the name of a Ruby method that's supported by the [`bond resource`](https://github.com/inspec/inspec/blob/master/lib/inspec/resources/bond.rb) 

It looks like the properties for the bond are available as a hash via the `params` method.
I think you could try:

```
describe bond('bond0') do
    it { should exist }
    its('mode') { should eq 'IEEE 802.3ad Dynamic link aggregation' }
    its('params') { should have_key 'Transmit Hash Policy' }
    its('params') { should include 'Transmit Hash Policy' => 'layer3+4 (1)' }
    its('params') { should have_key 'MII Status' }
    its('params') { should include 'MII Status' => 'up' }
  end
end
```

Apologies for a slow response; but I hope this solves the problem. Due to the age of this issue I'm going to close it - please re-open if there's any further issue.
