### ISSUE TITLE
File resource `more_permissive_than` matcher file existence check inconsistent

### ISSUE THREAD

**Issue by samcornwell** [inspec/inspec#4891]
When the file does not exist and the `more_permissive_than` matcher is used, an exception and backtrace is generated and written to the reporter JSON.  This is inconsistent with all the other parts of the `file` resource, none of which also do this sort of check. This is taken care of by the resource itself. It caused some confusing behavior in my tools which check the JSON's backtrace attributes for exceptions and interprets it's existence as an error with the control. I don't think this check should exist.

https://github.com/inspec/inspec/blob/40966bc0393131ec4e7d0ec43f7648d66db5cf0f/lib/inspec/resources/file.rb#L139

**Comment by james-stocks** [comment]
Yeah this seems wrong, methods need to return false or nil when `exists` is false.
