### ISSUE TITLE
Question: Cron?

### ISSUE THREAD

**Issue by goncalopereira** [inspec/inspec#490]
Any way to replace the serverspec cron resource? Any plans for it?

**Comment by chris-rock** [comment]
@goncalopereira We highlighted the current state of the Serverspec resources here: https://github.com/chef/inspec/issues/514 We intend to support a smooth migration and `cron` is part of it. We are happy to accept PRs to bring this feature into InSpec

**Comment by goncalopereira** [comment]
Thank you
