### ISSUE TITLE
Audit and clean JSON dumps

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4904]
We have a LOT of duplication in our JSON output. If we do what we can to identify that and clean it up, it should reduce the impact on automate and other report processors.

**Comment by aaronlippold** [comment]
This is a good thing to push into the schema work right?

**Comment by clintoncwolfe** [comment]
I believe this has been addressed through the message truncation and backtrace disable work. Also, I'm not sure what specific duplication was being referred to, and changing the schema would break a lot of consumers, so I don't think this is very actionable.
