### ISSUE TITLE
[directory] when using winrm I'm unable to validate a directory with a space

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#491]
Hi there

I'm been trying to use both the directory and file resources today, to validate that a directories exist.

I seem to have come across an issue if the path has a space in it 

my control works fine if I use the inspec shell on my local machine but if I invoke a shell on another host using winrm as the transport it fails.

`
inspec version = 0.14.2
`

either of these controls will fail over a winrm transport

```
  describe directory('C:\\Program Files\\') do
    it { should be_directory }
  end

  describe file("C:\\Program Files\\") do
    it { should be_directory }
  end
```

if I use this (over winrm) it works fine

```
  describe file("C:\\windows\\") do
    it { should be_directory }
  end
```

Here is my failure error

```
Failures:

  1) File C:\Program Files\ should be directory
     Failure/Error: Unable to find (pry) to read failed line
       expected File C:\Program Files\.directory? to return true, got false
     # (pry):2:in block (2 levels) in load
     # C:/Users/xxxx/AppData/Local/chefdk/gem/ruby/2.1.0/gems/inspec-0.14.2/lib/inspec/runner_rspec.rb:55:in run
     # C:/Users/xxx/AppData/Local/chefdk/gem/ruby/2.1.0/gems/inspec-0.14.2/lib/inspec/shell.rb:20:in start
```

**Comment by username-is-already-taken2** [comment]
Hi it helps anyone else, in the mean time I got round it using the script resource

```
script = <<-EOH
Test-Path 'C:\\Program Files\\' -PathType Container
EOH

describe script(script) do 
  its('stdout') { should match (/True/) }
end
```

This works on both my local shell and a remote winrm host

**Comment by srenatus** [comment]
Thanks for reporting this. #469 already noticed this for `file`, so I'd tend to close this one as a duplicate and we'll pursue this as #469.

Feel free to reopen this issue when you don't agree here :smile:
