### ISSUE TITLE
Add deprecation note to AWS resource docs in resource pack

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#4916]
# Describe the problem

If someone stumbles across the docs for the AWS resources that are in core, we need to point them to using the inspec-aws resource pack. We don't want people relying on or contributing to the AWS resources that remain in core.

**Comment by kekaichinose** [comment]
@skpaterson good call, sir. I needed to think this one through a little more before transferring. I moved it back to InSpec. Thanks!

**Comment by clintoncwolfe** [comment]
This issue is misleading and should be closed. The goal is to put a a note where it will be seen (in the resource pack) since the core doc files are not rendered on the website AFAIK.

**Comment by kekaichinose** [comment]
Let's go ahead and close this out. As @clintoncwolfe mentioned, references to the older resources are no longer linked on the docs site so this might be hit if folks are going through project documentation directly. I'm fine with waving this off till remove the resources from core for future release.
