### ISSUE TITLE
Unable to fetch dependency with http://authToken@path-to-profile.git

### ISSUE THREAD

**Issue by ObiH15** [inspec/inspec#4922]
Hello! I am using test-kitchen in conjunction with inspec profiles for my testing suite. I am able to successfully authenticate to my InSpec profile location to execute inspec tests. 

However, if I include profile dependencies in my .inspec.yml file (referencing other InSpec profile repos), I get the following error: 

`Failed` to complete #verify action: [Profile git dependency failed for http://authToken@path-to-profile.git - error running 'git ls-remote "http://authToken@path-to-profile.git" "master*"': fatal: http://authToken@path-to-profile.git/info/refs not valid: is this a git repository?`

This is how I am authenticating to my profile in my .kitchen.yml
`suites:
  - name: base
    verifier:
      inspec_tests:
        - name: windows-profile
          git: http://authToken@path-to-profile.git`

How I have .inspec.yml dependencies setup (currently failing):

`depends:
- name: win-profile
  url: "http://authToken@path-to-profile.git"`

Is there anyway to authenticate using a token? I'd rather not use basic auth and the ERB option will not meet our needs since this is a dependency. Any help would be greatly appreciated. Thanks.

**Comment by james-stocks** [comment]
Sorry for slow response - I believe you do need to use an ssh key or a stored credential, sorry.
Another alternative is to set up releases on the git repo then give InSpec the URL for a released .tar.gz file.
