### ISSUE TITLE
The "service" resource is not supported on your OS yet - Windows 2016

### ISSUE THREAD

**Issue by akr257** [inspec/inspec#4924]
The service resource no longer works on Windows. I have used this resource quite extensively in the past (about 6-8 months ago)

```
C:\Users\Administrator>inspec detect

Name:      windows_server_2016_datacenter
Families:  windows, os
Release:   10.0.14393
Arch:      x86_64

C:\Users\Administrator>inspec version
4.18.85
```
inspec installed from: https://packages.chef.io/files/stable/inspec/4.18.85/windows/2016/inspec-4.18.85-1-x64.msi

Snippet of my test case

```
describe service('SepMasterService') do
  it { should be_installed }
  it { should be_enabled }
  it { should be_running }
end

describe service('CSFalconService') do
  it { should be_installed }
  it { should be_enabled }
  it { should be_running }
```

Snippet of execution test results

```
  Service SepMasterService
     [SKIP]  The `service` resource is not supported on your OS yet.
  Service CSFalconService
     [SKIP]  The `service` resource is not supported on your OS yet.
```

**Comment by g1ps** [comment]
One more here. Pointing InSpec from this Win10 laptop to both Win2012R2 and Win2019 servers fails with the same message. Service tests were working until recently. It does also appear that my production tests aren't running on one of the same servers, although other servers are working. Those are using a much earlier version of InSpec 4 and service tests are working on one of those same machines. Unfortunately our systems are in a mess at present and I can't access the machines running the tests to verify versions or check manually what's going on there.

**Comment by g1ps** [comment]
It's impossible to tell from the error reported which OS it's actually referring to. I removed the -t arg and tested my own Win10 machine. Same result. Once I can get to the prod. runners I'll do some testing there and report.

**Comment by g1ps** [comment]
My local machine is running 4.18.85 and that breaks. The prod host is running 4.10.4 and that appears to work i.e. it worked when I ran it from the command line. It's also a RHEL 7 VM, rather than Windows. I don't think I have anything between those versions at present. So the problem may be the Windows host although my production tests are still skipping so that seems unlikely. I'll report if I learn more.

**Comment by FilBot3** [comment]
I am getting this same error with a Docker Image `chef/chefdk:4.7.113` using the following command:

```bash
docker run --rm --env CHEF_LICENSE=accept-no-persist --volume ${PWD}:/opt/workspace --workdir /opt/worksapce chef/chefdk:4.7.113 chef exec inspec exec . -t winrm://server@windows2016server.com --password 'secert'
```

I then get the following error:

```
C:\Users\user01\Documents\Development\InSpec\Developer.user01.inspec.sample_control [master +9 ~0 -0 !]
λ  docker run --rm --env CHEF_LICENSE=accept-no-persist --volume ${PWD}:/opt/workspace --workdir /opt/workspace chef/chefdk:4.7.113 chef exec inspec exec . -t winrm://user01@windows2016server.comp.com --password 'secret'

Profile: InSpec Profile (sample_controls)
Version: 0.1.0
Target:  winrm://user01@http://windows2016server.comp.com:5985/wsman:3389

  ↺  dhcp: Dynamic Host Configuration Protocol
     ↺  The `service` resource is not supported on your OS yet.


Profile Summary: 0 successful controls, 0 control failures, 1 control skipped
Test Summary: 0 successful, 0 failures, 1 skipped
```

This is part of a newly created InSpec profile with the contents of:

```ruby
control 'dhcp' do
  impact 0.1
  title 'Dynamic Host Configuration Protocol'
  desc 'Check to make sure that DHCP Client is configured correctly.'
  tag 'dhcp'

  describe service('DHCP Client') do
    it { should be_running }
    it { should be_running }
  end
end
```

**Comment by ghost** [comment]
Same issue with Windows 2019 Datacenter and Core, and 2016 Datacenter and Core.
These tests worked fine with previous versions of Inspec.

```
title 'aws ssm validation'

control 'aws-ssm-1.0' do
  impact 0.8
  title 'AWS ssm agent installed'
  desc 'AWS ssm agent is required for compliance and management'
  tag 'required-agent'

  describe service('Amazon SSM Agent') do
    it { should be_installed }
    it { should be_running }
    it { should be_enabled }
  end

  describe package('Amazon SSM Agent') do
    its('version') { should cmp >= '2.3.871.0' }
  end
end
```
Result:
```
↺  aws-ssm-1.0: AWS ssm agent installed (1 skipped)
     ↺  The `service` resource is not supported on your OS yet.
     ✔  System Package Amazon SSM Agent version is expected to cmp >= "2.3.871.0"
```
Chef Workstation Version (Ubuntu 16.04):
```
chef --version
Chef Workstation version: 0.16.31
Chef Infra Client version: 15.8.23
Chef InSpec version: 4.18.85
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.21.9
```

**Comment by Pablogra** [comment]
It is happening in version 4.18.100

inspec version
4.18.100

**Comment by james-stocks** [comment]
@Pablogra - 4.18.104 was released today with the fix for this issue

**Comment by rakopoul** [comment]
Sorry to post on such an old post.
I get same error on Almalinux-8

InSpec test:
  describe service('docker') do
    it { should be_installed }
    it { should be_enabled }
    it { should be_running }
  end
  
  error:
  ↺  The `service` resource is not supported on your OS yet.
  
  Same test was working on centos-stream-8
