### ISSUE TITLE
Automate integration tests failing with inspec master

### ISSUE THREAD

**Issue by phiggins** [inspec/inspec#4926]
Automate was recently setup to run the Automate scanner tests using inspec from master: https://github.com/chef/automate/pull/2657

Soon after this was rolled out the tests started failing: https://buildkite.com/chef-oss/chef-automate-master-verify/builds/8643#b6c11100-4009-4396-a719-6016f7749cf3

**Comment by clintoncwolfe** [comment]
This should be fixed in train 3.2.23 / inspec 4.18.100

**Comment by clintoncwolfe** [comment]
refs #4899

**Comment by phiggins** [comment]
This is green on current builds of automate: https://buildkite.com/chef-oss/chef-automate-master-verify/builds/9797#_
