### ISSUE TITLE
cached_fetcher.rb error "Could not fetch inspec profile in ..."

### ISSUE THREAD

**Issue by danielcbright** [inspec/inspec#4935]
Inspec `4.18.97` cannot fetch profiles from an Automate server without erroring out fataly.

# Describe the problem
Test command:
```
inspec archive . --overwrite -o test.tar.gz
```
output:
```
Traceback (most recent call last):
	19: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-bin-4.18.97/bin/inspec:11:in `<main>'
	18: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/base_cli.rb:35:in `start'
	17: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	16: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	15: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	14: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	13: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/cli.rb:191:in `archive'
	12: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/base_cli.rb:287:in `vendor_deps'
	11: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/profile_vendor.rb:13:in `vendor!'
	10: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/profile_vendor.rb:58:in `vendor_dependencies!'
	 9: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/profile.rb:540:in `generate_lockfile'
	 8: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/dependency_set.rb:90:in `vendor'
	 7: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/resolver.rb:30:in `resolve'
	 6: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	 5: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/resolver.rb:59:in `each'
	 4: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/resolver.rb:77:in `block in resolve'
	 3: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/requirement.rb:83:in `resolved_source'
	 2: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/requirement.rb:105:in `fetcher'
	 1: from /hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/dependencies/requirement.rb:105:in `new'
/hab/pkgs/chef/inspec/4.18.97/20200224232118/lib/gems/inspec-core-4.18.97/lib/inspec/cached_fetcher.rb:14:in `initialize': Could not fetch inspec profile in {:cwd=>"/src", :backend=>Inspec::Backend::Class @transport=Train::Transports::Mock::Connection, :name=>"linux-patch-baseline", :compliance=>"admin/linux-patch-baseline"}. (RuntimeError)
```

Testing the same command with Inspec `4.18.51` works just fine.

## Possible Solution
Currently I have rolled back to `4.18.51` in my Effortless Audit builds

**Comment by clintoncwolfe** [comment]
Could you include the inspec.yml from the profile you are archiving?

**Comment by stevendanna** [comment]
The following inspec.yml can reproduce this:

```
name: repro
title: InSpec bug reproduction
copyright: Chef Software, Inc.
copyright_email: support@chef.io
license: Apache 2 license
version: 1.0.0
depends:
  - name: bar
  - compliance: foo/bar
```

The problem is that no fetcher is being found. Which I believe is being caused by

https://github.com/inspec/inspec/commit/7d95ece60dd5a5d19e7949d85d258c3cc087938f

The removed require means that the fetcher never gets registered with the fetcher registry.

**Comment by clintoncwolfe** [comment]
regression introduced in in spec 4.18.55

**Comment by shwetabhsuman12** [comment]
I am getting the same error -
Traceback (most recent call last):
	16: from /usr/bin/inspec:204:in `<main>'
	15: from /usr/bin/inspec:204:in `load'
	14: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.24.32/bin/inspec:11:in `<top (required)>'
	13: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/base_cli.rb:35:in `start'
	12: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	11: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	10: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 9: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 8: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/cli.rb:281:in `exec'
	 7: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/runner.rb:135:in `run'
	 6: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/runner.rb:101:in `load'
	 5: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/runner.rb:101:in `each'
	 4: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/runner.rb:107:in `block in load'
	 3: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/profile.rb:263:in `load_libraries'
	 2: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/profile.rb:263:in `each_with_index'
	 1: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/profile.rb:263:in `each'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.24.32/lib/inspec/profile.rb:270:in `block in load_libraries': undefined method

 `[]=' for nil:NilClass (NoMethodError)
--- my inspec version is: 4.24.32
my yaml file -
name: inspecinhritexample
title: AWS InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile For AWS
version: 0.1.0
inspec_version: '~> 4'
attributes:
- name: aws_vpc_id
  required: false
  default: ''
  description: 'Optional Custom AWS VPC Id'
  type: string
depends:
  - name: sampleref
    path: ../iam_get
supports:
  - platform: aws


--- 
Refered iam_get profile is placed in the same parent folder.
