### ISSUE TITLE
Use target value in controls

### ISSUE THREAD

**Issue by micheelengronne** [inspec/inspec#4940]
## Detailed Description
I would like to be able to use the target value (local, ssh://, docker://, etc...) in my controls.

## Context
It provides a way to embed tests that should be executed in the remote and locally in the same profile.

It does not mean multiple targets at once. It is just for packaging consistency.

## Possible Implementation
There may be already a way to achieve that. There is currently nothing in the doc.

**Comment by clintoncwolfe** [comment]
Assuming you used the `-t` option, it ends up in `inspec.backend.uri`, eg

```
inspec> inspec.backend.uri
=> "ssh://vagrant@127.0.0.1:2222"
```

**Comment by micheelengronne** [comment]
Works like a charm. Thanks.
