### ISSUE TITLE
Document special service resources

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#495]

**Comment by srenatus** [comment]
Note that something's here already https://github.com/chef/inspec/pull/463/files

**Comment by chris-rock** [comment]
The following is missing in our current service https://github.com/chef/inspec/blob/master/docs/resources.rst#service documentation:
- `launchd_service` https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L742
- `bsd_service` - https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L742
- `sysv_service` - https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L698
- `systemd_service` - https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L654

Those should be added to the `Override the service manager` section.
