### ISSUE TITLE
postgres_session enhacement : allow custom database port

### ISSUE THREAD

**Issue by akramus** [inspec/inspec#4953]
## Detailed Description
Is it possible to enhance the method postres_session to allow a custom database port ? 
Actual description 
sql = postgres_session('username', 'password', 'host')

## Context
dev-sec-ops  . Rule is to check that defaut port is not used by database

## Possible Implementation
suggested enhancement :
 postgres_session('username', 'password', 'host','port')

**Comment by npirard** [comment]
FWIW, I have been able to work around this limitation by adding  '-p port' to the host parameter :

`sql = postgres_session('username', 'password', 'host -p port')`

**Comment by clintoncwolfe** [comment]
Port setting was added in #5185
