### ISSUE TITLE
TLS1.3 support

### ISSUE THREAD

**Issue by micheelengronne** [inspec/inspec#4956]
TLS1.3 will soon replace TLS1.2.

## Detailed Description
The underlying library does not have it yet. See https://github.com/arlimus/sslshake/issues/9

## Context
This change is important because without it the `ssl` resource will soon be pretty useless.

**Comment by stevendanna** [comment]
@micheelengronne Thanks for the report!

**Comment by stevendanna** [comment]
The following upstream PRs hopefully help get this started:

https://github.com/arlimus/sslshake/pull/11
https://github.com/arlimus/ssl-test-dummies/pull/2

**Comment by micheelengronne** [comment]
Don't close it Bot.
