### ISSUE TITLE
Source install instruction are misleading (I would hesitate to say "wrong")

### ISSUE THREAD

**Issue by douglasawh** [inspec/inspec#4958]
# Describe the problem

This step in the source install instructions is not necessary, and actually does not seem to work:
bundle exec bin/inspec help

When I run that step on my Mac it says:
"bundler: command not found: bin/inspec
Install missing gem executables with `bundle install`

## Possible Solution

My guess is that bin/inspec is actually a path. so maybe change 'bin/inspec' to '</path/to/inspec>' or something of that nature

The Windows instructions are also incomplete, but I am not sure if that is a change in the msys2 installer, or what. I just figured I would mention it in passing if someone was going to give that section some love.

**Comment by douglasawh** [comment]
One of my colleagues was able to get the instructions at https://github.com/chef/chef/blob/master/docs/dev/how_to/building_and_installing.md to work for inspec. Perhaps instead of maintaining two different versions of instructions, you should just point to those instructions.

**Comment by clintoncwolfe** [comment]
I believe this was fixed by #4993
