### ISSUE TITLE
Array inputs don't seem to be loaded correctly via the cli and `--inputs`

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#4963]
Arrays support seems to be working via `inspec.yml` or `input-files` but not the CLI

Thor does not seem to be respecting something like:

`--input foo=[1,2,3]` 

or something even more complex as:

`--input aoh=[{:Subject: "CN=DoD Root CA 2, OU=PKI, OU=DoD, O=U.S. Government, C=US",:Issuer: "CN=US DoD CCEB Interoperability Root CA 1, OU=PKI, OU=DoD, O=U.S. Government, C=US", :Thumbprint: "DA36FAF56B2F6FBA1604F5BE46D864C9FA013BA3", :NotAfter: "Saturday, March 09, 2019"}]`

Aha! Link: https://chef.aha.io/features/SH-2166

**Comment by binamov** [comment]
+1, some clarity on using arrays from `--input` in cli would be helpful.

**Comment by KonradSchieban** [comment]
+1, there is a use case for using arrays for `--input` when you run InSpec in a pipeline. Writing a yml file for this adds quite some effort.

**Comment by clintoncwolfe** [comment]
I don't recall that it does handle complex structures in any way. At the time `--input` was added, it was added as a first step - simple scalar values is all it did, and we left more complicated questions - like how to take JSON on the command line - for a future sprint.

How would you like it to work? How should InSpec distinguish between values that might be complex and might not be (that is, when should it decide to try to parse)?

**Comment by KonradSchieban** [comment]
My suggestion would be to validate the input value and check whether its structure matches a pattern for a complex structure, an array, a string or a numeric value. Ideally, we would be able to create any kind of input from the CLI using `--input` as by declaring them in the `--input-file`.

**Comment by clintoncwolfe** [comment]
What about...
```
If it looks like true or false, treat as boolean
elsif it looks like a number, treat as a numeric (#4977)
elsif it has brackets or curlies
  try to parse as YAML (single-line yaml, but the parser won't care)
  if that fails,
    try to parse as JSON
    if that fails
      give up and complain
else assume it is a string
```
