### ISSUE TITLE
Make use of filter query where testing a single port with ss

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#4965]
Evaluating all [port](https://github.com/inspec/inspec/blob/master/lib/inspec/resources/port.rb data on the target host can take a long time - on some customer systems it might exceed 10 minutes.

Short term, we should at least be filtering the query made to the target host when a single port is being tested (`describe port(80)`) and where the underlying command is `ss`

i.e. 
`ss -tulpen "( dport = 80 or sport = 80 )"

**Comment by mwronka-chef** [comment]
In case port resource call is timing-out, it could be replaced with the following command:

```
describe command('ss -tulpen "( dport = 80 or sport = 80 )"') do
  its('stdout') { should_not match (/:80\s/) }
  its('stderr') { should be_empty }
end
```
