### ISSUE TITLE
include the JSON summary of a profile in any artifact produced

### ISSUE THREAD

**Issue by robbkidd** [inspec/inspec#4973]
The JSON data produced by the `inspec json` command is a more complete record of a profile and its capabilities. A lesson learned fairly early with cookbook artifacts was to include a metadata record that was as complete as possible in the artifact itself. The publishing client performs all the interpretive work to determine the content's complete record of metadata and then stores that complete record within the artifact itself in a data-only format. That data is then available to any system that needs it as the artifact is passed around between systems.

1. The data should be 👍 All Correct 👍 at the time of artifact creation prior to publication.
2. The data does not change for a particular version after version publication.
3. The data is usually the product of interpretation, so for consistency and security's sake, only interpret once by the author/publisher.
4. All downstream systems that use the artifact can rely on a metadata record within the artifact to determine the artifact's capabilities. 

If the resultant JSON includes everything from the profile's YAML, I will go so far as to suggest that eventually tools and services that handle, consume, or use profiles should switch to treating the JSON record as the profile's metadata and _not_ use the YAML.

## Context

The JSON is already able to be produced by `inspec`. The `controls` data within the JSON can be used by downstream tools to inform users of a profile's capabilities and even to provide a list of controls to select from for customized reports.

## Possible Implementation

At a very high level, it seems possible to use the existing logic behind `inspec json` to produce the JSON file during `inspec archive` and `inspec artifact` for inclusion in the resultant tarball or signed IAF.

**Comment by Schwad** [comment]
@robbkidd I have a draft PR up on #5017 - it still requires tests but I have successfully run `archive` and `artifact` against it with the expected behavior locally, I wanted to get it up before the bank holiday UK weekend so you could have a chance to play with it before I come back and try to get it tested. 😄
