### ISSUE TITLE
Resources to test Windows firewall settings

### ISSUE THREAD

**Issue by thheinen** [inspec/inspec#4978]
## Detailed Description
In compliance-related projects, server firewalls must be tested against their intended configuration.

For Linux there are resources like `firewalld` or `iptables`, on Windows platforms there is no such functionality yet.

## Context
To get an insight into if firewall rules are still active and unchanged, it is necessary to inspec Windows Firewall profiles and rules.

The topic has been mentioned in issue #1697 already.

## Possible Implementation
Getting firewall state with the same PowerShell commands as Chef does and expose the returned properties along with some helpers.

I already have the code ready for PR, as it was needed for a project anyway.

**Comment by idiudiuki** [comment]
Thank you for requesting this feature! I was just looking for the same. Hope it will be added soon.

**Comment by thheinen** [comment]
This just got merged into 4.22.11 - thank you :)
