### ISSUE TITLE
How can you use inspec matchers and resources in an existing Rspec project?

### ISSUE THREAD

**Issue by joegoggins** [inspec/inspec#498]
I have an existing cucumber/rspec project that I'd like to use Inspec matchers and resources on, but I'm not sure what `require` and module `include` statements I need to put in my `env.rb`/`spec_helper.rb` to make it work. I tried various different `config.include` statements and permutations against `Inspec` modules and couldn't quite get it to work. Any recommendations here would be much appreciated!

Thanks,

-joe

**Comment by chris-rock** [comment]
@joegoggins How do you call cucumber and rspec? We need to understand the setup, before we are able to provide an answer that works for you.

**Comment by joegoggins** [comment]
Was simply looking to include the inspec DSL and use it in cucumber step definitions. If you could provide a snippet of Ruby that injects the DSL into the current context, I could figure the rest out. I'd be happy to share what that looks like in a cucumber or rspec project.

**Comment by chris-rock** [comment]
The saves way to run inspec tests is to run InSpec directly (`inspec exec`) or use `kitchen-inspec`. Alternatively you can use our Runner interface as used here https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L68-L73, but I'd like to mention, that the Runner interface is an internal API and may change without any further notice.

**Comment by joegoggins** [comment]
Thank you very much, this is exactly what I was looking for, closing this issue.
I'll likely give this a approach whirl in a cucumber context and share my code here if there is anything tricky/worth sharing.

**Comment by chris-rock** [comment]
Thanks @joegoggins that is a great idea

**Comment by pburkholder** [comment]
@joegoggins Curious if you have any examples or experience to share on using Inspec::Runner with Cucumber. I'm poking at the same question. Thanks, P.

**Comment by joegoggins** [comment]
Hey @pburkholder , I ended up using vanilla cucumber and a custom tagging strategy to achieve the main things I was hoping to get out of Inspec for my particular project instead of blending the two. If there were a simple way to use the Inspec _matchers_ inside of Cucumber alongside my other Cucumber matchers + step definitions with the Cucumber CLI, I'd still love to be able to do that. Unfortunately, the proposed route above of shelling out to `inspec exec` from cucumber steps, doesn't add much value relative to the complexity it adds.

**Comment by joegoggins** [comment]
Funny.  I just googled "how to use Inspec resources inside of Rspec" and came across this GH issue I posted almost three years ago...

Here I am again in the same/similar situation.

I want to use the awesome `http`, `port`, `host`, `yaml`, and MANY other Inspec resources in the context of another RSpec project (that doesn't get executed via `inspec exec`)

Is there a `InspecDsl` module I could `include` in my `spec_helper.rb` that would expose these Inspec resources?

:crossed_fingers: this is possible.

**Comment by clintoncwolfe** [comment]
Over the years, InSpec has probed deeper and deeper into RSpec, modifying the Runner behavior as well as the Reporter side, and also 5 total DSLs we inject into RSpec.  Today InSpec uses RSpec as an implementation detail; no parts of that interface are intended to be stable enough for public consumption. 

That's not to say it isn't possible; just that I don't know what it would take to pull off, and future changes in InSpec might break it at any time.

Simplest thing: run cucumber process, then run an inspec process, possibly pos-processing a JSON-formatted report.

**Comment by joegoggins** [comment]
> Today InSpec uses RSpec as an implementation detail; no parts of that interface are intended to be stable enough for public consumption.

Groovy. Thanks. It's very useful to know that. I'm unblocked and should be able to make sensible architecture decisions with that knowledge.
