### ISSUE TITLE
Add `ports` property to the `firewalld` resource

### ISSUE THREAD

**Issue by ljkimmel** [inspec/inspec#4987]
Need the ability to gather a list of ports for validation.

## Detailed Description
Add a ports property to the resource that returns a list of ports configured in a zone.

## Context
Per the DISA STIG we are required to validate what ports are in use. Ports are not always configured only as part of a service. We need the ability to check ports directly.

## Possible Implementation
Adding an entry to the FilterTable to support filtering by ports, updating the `parse_line` method to include setting a `ports` property and adding a method (`ports_bound`) to fetch the list of ports should work.

**Comment by jblaine** [comment]
Pretty sure this was released in 5.7.9 from the implementation done in https://github.com/inspec/inspec/pull/5597

AFAICT this should be closed

**Comment by Vasu1105** [comment]
Thanks @jblaine. Closing as it is addressed in #5697
