### ISSUE TITLE
Add the ability to pass an input.yml file to the inspec shell

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#4989]
This would allow me to more consistently and easily test and work with controls that use shared inputs in my day to day devel work.

**Comment by aaronlippold** [comment]
What I would envision is:

`inspec shell --depends <path> --input-file=<path> -t <target>` 

`inspec shell --depends <path> --input a=[1,2,3] -t <target>`

**Comment by pburkholder** [comment]
This. I was surprised this wasn't here when I tried to do some testing.
