### ISSUE TITLE
http resource should coerce response body into UTF8

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#4996]
Reported in internal Slack.

When using the `http` resource to assert the `body` of a response, you may get the error `"\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)`

Apparently the problem and workaround fit this blog article:
https://megamorf.gitlab.io/2019/06/20/matching-chinese-characters-in-inspec-http-tests.html

The workaround given there is to test `response.body.force_encoding(Encoding::UTF_8)` in your control. Probably we should do this encoding inside the `body` method directly so that people don't need to use this workaround.

**Comment by james-stocks** [comment]
There's an existing issue https://github.com/inspec/inspec/issues/2044 but that relates to calling curl with the `command` resource. 
This issue seems to relate to Ruby's HTTP libs.

**Comment by graham1228** [comment]
Any idea on when this bug will be fixed?
