### ISSUE TITLE
Order/Sequence of Result

### ISSUE THREAD

**Issue by youngee91** [inspec/inspec#4997]
## Detailed Description
Hi,

I'm currently having an issue with the order of the result. Sometimes when I execute the profile, my result will be displayed in an orderly manner based on my controls naming and sometimes it does not. The result will be randomised and not displayed according to the naming of my controls. I tried to change the creation time of the controls file but it does not seem to work either. 

Thus, I would like to ask if there is any way I can make sure the results are always consistent and always display in the naming order of my control files
Example:
```
test-1.rb
test-2.rb
test-3.rb
```
Expecting result:
```
 ✔  test-1
 ✔  test-2
 ✔  test-3
```

## Context
I'm using this for my CIS compliance and it would be easier for me to go thru the result if the result is in sequence order.

**Comment by james-stocks** [comment]
Agreed, when the InSpec profile is for compliance auditing, the results being out of order is very unfriendly.

**Comment by Schwad** [comment]
Is this for results in terminal or do we see this out-of-order across all reporters as well?

**Comment by youngee91** [comment]
Usually i test it out on the terminal first. If the terminal results are out of order, the reporters will be the same. I'm using `json` reporter
