### ISSUE TITLE
Add a flag to limit message size

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4999]
### 🎛 Description

**Choose one:**  🙋 feature request

There are some use cases where a test returns a message body that is several megabytes long. This exceeds certain client's ingestion limits. To better address this, we should be able to set the maximum size for the message, after which point a notice is provided in the message that it has been "truncated" and the user given guidance on how to reproduce the test to get the whole message on the node itself.

### 👍 Acceptance Criteria
* `inspec exec` can take a flag and config value for maximum message size (in char limit)
* existing `inspec exec` runs are not impacted by new flag (e.g. default run is with message size unset)

### 🔗 Related Links

* https://github.com/chef-cookbooks/audit/issues/422

**Comment by james-stocks** [comment]
Implemented in https://github.com/inspec/inspec/pull/4994
