### ISSUE TITLE
Add an option to toggle stack trace data

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#5000]
### 🎛 Description

**Choose one:**  🙋 feature request

Stack traces add a large amount of data to the `message` field. This large amount of data may make the report so large that it is not consumable by a downstream client. InSpec should be flexible enough to allow users to disable stack trace data in test results, thereby making the report more consumable.

### 👍 Acceptance Criteria
* `inspec exec` can take a flag that disables stack trace data as part of tests
* existing `inspec exec` runs are not impacted by new flag (e.g. default run includes stack trace data)

### 🔗 Related Links

* https://github.com/chef-cookbooks/audit/issues/422

**Comment by james-stocks** [comment]
Implemented in https://github.com/inspec/inspec/pull/4994
