### ISSUE TITLE
Unsupported resource/backend combination: file / azure. Exiting.

### ISSUE THREAD

**Issue by Sum123it** [inspec/inspec#5002]
While trying to do inspec exec . -t azure:// getting the above error

# Describe the problem
I am new to Chef Inspec and trying to test my resources.I have set up the credentials file with below:
AZURE_SUBSCRIPTION_ID
AZURE_CLIENT_ID
AZURE_CLIENT_SECRET
AZURE_TENANT_ID
inspec.yml looks like below:

name: inspec-workshop
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '4.18.51'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/v1.10.0.tar.gz
supports:
 # - platform-name: ubuntu
 #    release: 16.04
  - platform: azure 
============================
.rb file:
======================
describe azurerm_resource_groups do
  its('names') { should include 'cloud-shell-storage-centralindia' }
end
==========
Here's a snapshot of the error:

sumit@Azure:~/inspec-workshop$ inspec exec . -t azure://12345667-*****
**Unsupported resource/backend combination: file / azure. Exiting**.
sumit@Azure:~/inspec-workshop$ cd ..
sumit@Azure:~$ inspec check inspec-workshop
Location :   inspec-workshop
Profile :    inspec-workshop
Controls :   3
Timestamp :  2020-04-29T21:46:37+00:00
Valid :      true

No errors or warnings
sumit@Azure:~$

.

## Possible Solution
Not Sure

**Comment by james-stocks** [comment]
Hi @Sum123it -

Is that the entire contents of `inspec.yml` ? It seems to have an incomplete `supports` entry. It should declare support for Azure like

```
supports:
- platform: azure
```

**Comment by james-stocks** [comment]
You also pasted 1 test, but the output of `inspec check` shows 3 controls in the profile. Is there more code in the profile?

**Comment by Sum123it** [comment]
> You also pasted 1 test, but the output of `inspec check` shows 3 controls in the profile. Is there more code in the profile?

Hi James,
Sorry, Here's my yml file:
name: inspec-azure
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '4.18.51'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
  #platform: os
  - platform: azure

and control.rb file is below
# copyright: 2018, The Authors

title "sample section"

# you can also use plain tests
describe file("/tmp") do
  it { should be_directory }
end

describe azurerm_resource_groups do
  its('names') { should include 'cloud-shell-storage-centralindia' }
end

# you add controls here
control "tmp-1.0" do                        # A unique ID for this control
  impact 0.7                                # The criticality, if this control fails.
  title "Create /tmp directory"             # A human-readable title
  desc "An optional description..."
  describe file("/tmp") do                  # The actual test
    it { should be_directory }
  end
end

I have just added a simple code to check an azure resource group.

The error I get always is 

**WARN: Skipping profile: 'inspec-azure' on unsupported platform: 'ubuntu/16.04'.**

Looks like it's not calling the resources of azure from the .tar file.
tried below as well. Also I have created the credentials under .Azure to store all the ids and subscriptions
$ inspec exec inspec-azure -t azure://

**Comment by james-stocks** [comment]
I'm unsure why you are seeing that error, but a possible problem is that your profile is named `inspec-azure` which is already the name of the Chef profile.
Try naming your profile my-company-inspec-azure

You should also delete the `describe file` tests from control.rb - these example tests do not work with Azure

**Comment by Sum123it** [comment]
> I'm unsure why you are seeing that error, but a possible problem is that your profile is named `inspec-azure` which is already the name of the Chef profile.
> Try naming your profile my-company-inspec-azure
> 
> You should also delete the `describe file` tests from control.rb - these example tests do not work with Azure
ok  here it is the code  for 
inspec.yml

`name: dummy-azure
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '4.18.51'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
    
supports:
  #platform: os
  - platform: azure
`
here's inspec.lock:

`lockfile_version: 1
depends:
- name: inspec-azure
  resolved_source:
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz`

her's my .rb file:

`# copyright: 2018, The Authors

title "sample section"

describe azurerm_resource_groups do
  its('names') { should include 'cloud-shell-storage-centralindia' }
end
`
but i am facing below issue:
`sumit@Azure:~/dummy-azure$ inspec check dummy-azure
Traceback (most recent call last):
        12: from /usr/bin/inspec:357:in `<main>'
        11: from /usr/bin/inspec:357:in `load'
        10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.51/bin/inspec:11:in `<top (required)>'
         9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in `start'
         8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:117:in `check'
         3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:72:in `for_target'
         2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:22:in `resolve_target'
         1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:22:in `new'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cached_fetcher.rb:14:in `initialize': Could not fetch inspec profile in "dummy-azure". (RuntimeError)
sumit@Azure:~$ inspec exec dummy-azure
Skipping profile: 'dummy-azure' on unsupported platform: 'ubuntu/16.04'.

Test Summary: 0 successful, 0 failures, 0 skipped`

**Comment by Sum123it** [comment]
`ok here it is the code for
inspec.yml

`name: dummy-azure
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '4.18.51'
depends:

name: inspec-azure
url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
#platform: os

platform: azure
`
here's inspec.lock:
`lockfile_version: 1
depends:

name: inspec-azure
resolved_source:
url: https://github.com/inspec/inspec-azure/archive/master.tar.gz`
her's my .rb file:

`# copyright: 2018, The Authors

title "sample section"

describe azurerm_resource_groups do
its('names') { should include 'cloud-shell-storage-centralindia' }
end
but i am facing below issue:sumit@Azure:/dummy-azure$ inspec check dummy-azure
Traceback (most recent call last):
12: from /usr/bin/inspec:357:in <main>' 11: from /usr/bin/inspec:357:in load'
10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.51/bin/inspec:11:in <top (required)>' 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in start'
8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in start' 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in dispatch'
6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in invoke_command' 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in run'
4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:117:in check' 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:72:in for_target'
2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:22:in resolve_target' 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:22:in new'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cached_fetcher.rb:14:in `initialize': Could not fetch inspec profile in "dummy-azure". (RuntimeError)
sumit@Azure:$ inspec exec dummy-azure
Skipping profile: 'dummy-azure' on unsupported platform: 'ubuntu/16.04'.

Test Summary: 0 successful, 0 failures, 0 skipped``

**Comment by Sum123it** [comment]
> I'm unsure why you are seeing that error, but a possible problem is that your profile is named `inspec-azure` which is already the name of the Chef profile.
> Try naming your profile my-company-inspec-azure
> 
> You should also delete the `describe file` tests from control.rb - these example tests do not work with Azure

`ok here it is the code for
inspec.yml

`name: dummy-azure
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
inspec_version: '4.18.51'
depends:

name: inspec-azure
url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
#platform: os

platform: azure
`
here's inspec.lock:
`lockfile_version: 1
depends:

name: inspec-azure
resolved_source:
url: https://github.com/inspec/inspec-azure/archive/master.tar.gz`
her's my .rb file:

`# copyright: 2018, The Authors

title "sample section"

describe azurerm_resource_groups do
its('names') { should include 'cloud-shell-storage-centralindia' }
end
but i am facing below issue:sumit@Azure:/dummy-azure$ inspec check dummy-azure
Traceback (most recent call last):
12: from /usr/bin/inspec:357:in <main>' 11: from /usr/bin/inspec:357:in load'
10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.18.51/bin/inspec:11:in <top (required)>' 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/base_cli.rb:35:in start'
8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in start' 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in dispatch'
6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in invoke_command' 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in run'
4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cli.rb:117:in check' 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:72:in for_target'
2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:22:in resolve_target' 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/profile.rb:22:in new'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.18.51/lib/inspec/cached_fetcher.rb:14:in `initialize': Could not fetch inspec profile in "dummy-azure". (RuntimeError)
sumit@Azure:$ inspec exec dummy-azure
Skipping profile: 'dummy-azure' on unsupported platform: 'ubuntu/16.04'.

Test Summary: 0 successful, 0 failures, 0 skipped``

**Comment by james-stocks** [comment]
Your output shows you ran the command `sumit@Azure:$ inspec exec dummy-azure`
It should be `sumit@Azure:$ inspec exec dummy-azure -t azure://`
Without `-t azure://` InSpec will default to executing against your own computer.

**Comment by Sum123it** [comment]
> Your output shows you ran the command `sumit@Azure:$ inspec exec dummy-azure`
> It should be `sumit@Azure:$ inspec exec dummy-azure -t azure://`
> Without `-t azure://` InSpec will default to executing against your own computer.

Ok It worked James!. Thanks.But it's working only with the existing azure resources.

Looks like it didn't pick https://github.com/inspec/inspec-azure/archive/master.tar.gz file. 
Any issue with the yml file?

inspec exec dummy-azure -t azure://[subscription] worked for existing 4 azure resource

**Comment by Sum123it** [comment]
It worked now. We should not select master. Instead we need some specific version i guessFor me it was 1.10.1

**Comment by james-stocks** [comment]
Good idea @Sum123it - `master` may get major breaking changes, so you should definitely pin to a specific version. Sorry I didn't spot that.
Can this issue be closed?

**Comment by Sum123it** [comment]
> Good idea @Sum123it - `master` may get major breaking changes, so you should definitely pin to a specific version. Sorry I didn't spot that.
> Can this issue be closed?

Thanks James for support. it can be closed.
