### ISSUE TITLE
Resolve Waiver Extraction

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5005]
## Detailed Description

**RFC: Expanding/refining this request description**

On the fly, it does not appear that there is a straightforward way to identify and manipulate waivers while prying into the codebase. This was captured in issue #5001 where we needed to identify if an input was a waiver, in order to pass it along through the script correctly. 

There was a regression fix put in the PR (simply identifying elements of an input that are `waiveresque`, but more as a bugfix which started this larger discussion as pointed out by @stevendanna : https://github.com/inspec/inspec/pull/5001#discussion_r417934703

## Context

This would allow contributors to be more agile in handling and assisting with future waivers-related development.

## Possible Implementation

I think we should consider implementing here the options @stevendanna  outlined:

```
1. Change waivers to be a specific class we can look for and then look for it here
2. Change the waivers hash to have some sentinel _is_waiver key that we can look for if we have a hash here.
```

**Comment by Schwad** [comment]
I'm hopeful that this can help expand the discussion started in #5001 

I would also appreciate some support on labeling as I'm unsure which would be most appropriate for this issue

**Comment by james-stocks** [comment]
Thanks @Schwad 
I think this is technical debt that will bite us in future if we want to extend either inputs or waivers

**Comment by clintoncwolfe** [comment]
The field `justification` may already be an implicit sentinel value - the docs at https://www.inspec.io/docs/reference/waivers/ seem to imply that it is a required field. If so, simply verifying that an input is a control-named Hash with a key named `justification` would be one option.

Justification is unconditionally used here: https://github.com/inspec/inspec/blob/8b5789004ac31f4b6e7210421b119af41f483e3e/lib/inspec/rule.rb#L372 though there is no safety code to error-check whether it is present in the input.

**Comment by clintoncwolfe** [comment]
This is not a technical priority, I'm going to close this.
