### ISSUE TITLE
Automate Reporter Example Config is invalid JSON

### ISSUE THREAD

**Issue by devopsdina** [inspec/inspec#5006]
The example config located at: https://www.inspec.io/docs/reference/reporters/ for the Automate Report has invalid JSON.

If someone copy/pastes this code and updates it accordingly with their automate information they will receive a parse error

```
Error: Parse error on line 1:
"reporter": {	"automate": {	
----------^
Expecting 'EOF', '}', ',', ']', got ':'
```

Update the documentation to provide validate JSON:

```
{
	"reporter": {
		"automate": {
			"stdout": false,
			"url": "https://YOUR_A2_URL/data-collector/v0/",
			"token": "YOUR_A2_ADMIN_TOKEN",
			"insecure": true,
			"node_name": "inspec_test_node",
			"environment": "prod"
		}
	}
}

```

**Comment by Schwad** [comment]
Hi @devopsdina ! 👋 

Nice catch! Ran it through https://jsonlint.com/ and yep, you are right! It's almost end of Friday here but I'll fix this first thing Monday my time. Thank you! 🙏
