### ISSUE TITLE
describe.one fails when one case uses an unsupported resource

### ISSUE THREAD

**Issue by menewol** [inspec/inspec#5018]
By using a `describe.one` block im trying to audit wether a system has password complexity enabled. 

For Windows this will work by using the `security_policy` resource, and checking wether PasswordComplexity-Matcher compares to 1. For Un*x you will have to take a different approach. For example in ubuntu checking wether the `/etc/pam.d/common-password` contains parameters describing pw-complexity requirements. Im combining these two resources (`security_policy` and `file`) in a `describe.one` block to accomplish successful audit regardless of the system we're currently looking at. 

even though the "windows" describe block will not work for the PAM checks, the `describe.one` block should go on and check wether the second describe-block might audit successful.

my control looks as follows:

```
control 'password-complexity' do
        title 'Windows Password Complexity is Enabled / Un*x MINLEN is set'
        describe.one do
                describe security_policy do
                        its('PasswordComplexity') { should cmp 1 }
                end
                describe file('/etc/pam.d/common-password') do
                        its('content') { should match(%r{minlen=12}) }
                end
        end
end
```

The problem here is that inspec will not take the `Unsupported resource/backend combination` for a particular describe-block as "cant be audited successfully" and try to audit the next describe-block but stop the audit.

Is there any way to force inspec to finish checking a describe.one block regardless of the compatibility of a resource insinde that block? 

From the docs I could find the statement "Chef InSpec will always evaluate all the tests contained within describe.one. It does not short-circuit upon evaluating a passing describe block" [0]. 

While I found the second part to be true, the first part is false as inspec seems to not always evaluate all test

[0] https://www.inspec.io/docs/reference/dsl_inspec/

**Comment by james-stocks** [comment]
The distinction here is that one of the tests is causing an error to be raised during evaluation, rather than evaluating to a failed test result.

Do you mind if I change the title of this issue to `describe.one fails when including unsupported resource` ?

I believe that commonly people keep their Windows and Linux controls in separate profiles (you can then create a wrapper profile that includes both profiles, and run that wrapper profile against your entire fleet).

One workaround is to write the control like

```
control 'password-complexity' do
        title 'Windows Password Complexity is Enabled / Un*x MINLEN is set'
        if os.windows?
                describe security_policy do
                        its('PasswordComplexity') { should cmp 1 }
                end
        else
                describe file('/etc/pam.d/common-password') do
                        its('content') { should match(%r{minlen=12}) }
                end
        end
end
```

**Comment by menewol** [comment]
Hello James,

Totally fine with changing the title!

Thank you very much for clarifying on that issue, as well as providing a
best-practice solution and a workaround to go for the non-best-practice
route.

Best regards,

menewol
