### ISSUE TITLE
Docs for command use eq instead of match

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#502]
The docs for command seem to show a regex against stdout, but they're doing it with eq and the regex in quotes.  This doesn't seem to work.  Changing the commands over to match seems to resolve it.

**Comment by chris-rock** [comment]
@tas50 could you add a reference where you see the error?

**Comment by tas50** [comment]
https://github.com/chef/inspec/blob/master/docs/resources.rst#examples-6

**Comment by chris-rock** [comment]
@tas50 awesome find. Would you like to compose a PR to fix that?

**Comment by chris-rock** [comment]
This is fixed in latest documentation https://github.com/chef/inspec/blob/master/docs/resources.rst#examples-7
