### ISSUE TITLE
Software repository for Ubuntu Focal Fossa (20.04) no more holds an inspec package

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#5030]
## Detailed Description

When following the guidelines from https://docs.chef.io/packages/ using Ubuntu 18.04 bionic it is possible to install inspec via a simple `apt install inspec`. 
When doing the same for using Ubuntu 20.04 focal this no more works. The only available package is `chef`

```
grep ^Package: /var/lib/apt/lists/packages.chef.io_repos_apt_stable_dists_focal_main_binary-amd64_Packages

Package: chef
```

The package itself is available on the server (http://packages.chef.io/repos/apt/stable/ubuntu/20.04/) but its not available via apt. 

It would be great if inspec could be deployed the same way using Ubuntu 20.04 release as known and working for the older Ubuntu 18.04 release.

**Comment by btm** [comment]
Just as a note, I poked around in https://packages.chef.io/repos/apt/stable/dists/bionic/main/binary-amd64/Packages and it has inspec packages, but as reported https://packages.chef.io/repos/apt/stable/dists/focal/main/binary-amd64/Packages does not. The only package in the focal index is Chef 15.9.17, which is old. I'll reach out to release engineering.

**Comment by clintoncwolfe** [comment]
inspec 4.31.0 is present in https://packages.chef.io/repos/apt/stable/dists/focal/main/binary-amd64/Packages as of April 7, 2021. Closing.
