### ISSUE TITLE
AWS NetworkACL Check is missing ?

### ISSUE THREAD

**Issue by macbash** [inspec/inspec#5059]
All - i checked the recent version of inspec in aws testing, found NACL check is missing. Could we get this ?

**Comment by Schwad** [comment]
Hi @macbash  -  would this be something we'd adjust in the `inspec-aws` resource pack? If so it may be worth filing an issue here. https://github.com/inspec/inspec-aws

**Comment by macbash** [comment]
Sure. Thanks

________________________________

**Comment by Schwad** [comment]
Cheers! Will look for it there 👍
