### ISSUE TITLE
Try to Force acceptance of a different license than it gets installed under

### ISSUE THREAD

**Issue by Paladin** [inspec/inspec#5066]
Tried a couple of different ways, installing via Homebrew and installing via the MacOS .dmg

No matter which way I try, and despite the claims of the website *and* the .dmg installer, it demands I contact chef and beg for a license.

Obviously, both those two conditions cannot be correct. Choose a license and stay with it, at least for the life of the installed version. Don't install under a false flag.

# Describe the problem
Installer and website claim Apache2.0 license.
Software won't run without agreeing to a commercial license.

## Possible Solution

Two possible solutions come to mind, there's proably a dozen others.

Remove the pretense to the apache license and update the website and github to reflect it.
or
Pull the license_acceptance check out of the code and let the documented Apache2 license prevail.

Aha! Link: https://chef.aha.io/features/SH-2145

**Comment by clintoncwolfe** [comment]
Thanks for your inquiry. I believe [this comment](https://github.com/inspec/inspec/issues/4084#issuecomment-497389130) in particular may help clarify the situation. If you do not wish to accept the Chef License, yet still wish to use Chef InSpec functionality, you do have other options.

**Comment by Paladin** [comment]
Doesn’t really fix the problem, though, does it? You’re still doing a “false flag” installation, where the installer says it’s one license, and your customer doesn’t find out it’s lying to him until the first time they try to run it.

I did a search for license before I opened this, didn’t see anything. Thanks for the pointer to the other issue. Yes, I know I have other options. I liked using inspec, but I can, and will, switch.

That’s an unfortunate side-effect of suddenly changing the licensing terms. When you’ve done it to me once, I don’t have any reason to believe you won’t do it again, and make it even more restrictive each time. Which means my best option is to move to another tool that I can have a higher expectation of being able to continue using.

Disappointing, though. I like writing ruby and have now wasted a lot of time building custom resources in inspec.

Anyway, thanks for the info. Have fun.

**Comment by aaronlippold** [comment]
Hello, I understand your situation and this is exactly why we also
developed the Cinc project. Please see https://cinc.sh.

Cinc is a fully Apache 2.0 based build of all the open source capabilities
of inspec without the trademark and other things outlined in the end user
license agreement.

This is much akin to other similar enterprise open source projects.

CINC has no licenses other than Apache 2 and should meet your particular
use case and allow you to continue to use all your custom resources and
other existing work without any loss of effort.

I hope this helps as we in the inspec community our focused on making sure
we meet both sets of end-user needs.

**Comment by aaronlippold** [comment]
This was a common question that I got from many of our community members I ended up writing an FAQ on it on our website.


https://saf.mitre.org/#/faq

All Chef software source code, including Chef InSpec, is open source under the Apache-2.0 license.

Use of Chef's binary builds requires a paid license for use in production.

Use of Chef binaries and releases in development, test, evaluation and demonstration do not require a formal support agreement.

This is a common model in Enterprise Open Source software companies. The first major example of this was when Red Hat updated its licensing model. The open-community created the CentOS project to produce distributions of the RedHat OSS licensed code as a fully open-source software distribution.

For more information about Chef's goals and intentions for this update, please see https://blog.chef.io/chef-software-announces-the-enterprise-automation-stack/ and the https://www.chef.io/subscription-model-faq/.

Chef Inc. is working with the Cinc Project and the OSU Open Source Lab in support of the open source community. Chef and Cinc have worked hard to ensure that both the commercial-support and community-support model is easy for the end-user community.

Cinc project is creating community distributions that follow the Apache-2.0 and Chef End User License Agreement (EULA) for the community to use freely and without a license.

If you need Chef support for production use and deployment of Chef binaries, please https://pages.chef.io/2020-OSS-LandingPage.html about their various options.

The Cinc project is not a fork, the Cinc and Chef binaries are functionally identical and build from the exact same OSS code on GitHub.

The Cinc distributions remove all trademarked and Chef owned intellectual property and images, etc. This makes them compliant with the Chef Software Trademark policy and EULA, and provides the community with a freely distributable and purely open-source option to use Chef's open source technology.

The Cinc project's goals are to provide the community with a freely distributable and purely open-source option to use Chef's open source technology.

**Comment by james-stocks** [comment]
@Paladin I believe the bug here is that our dmg and msi packages use an install wizard that includes a step for Apache 2 license acceptance? 

![license](https://user-images.githubusercontent.com/12136665/83759824-0e035680-a66c-11ea-93cb-8c9e61395f96.png)

To be clear, this is wrong and needs removed. The [MLSA](https://www.chef.io/online-master-agreement/) that InSpec asks you to accept at runtime is the correct license.
I'm sorry this is wrong, but it is an unintended oversight in our packaging. 

As Clinton mentions, there are a number of cases where you may accept the MLSA without making a license purchase, e.g. for evaluation, education (of how to use InSpec), or to contribute code to this repo.
And as Aaron points out, you can also use the https://cinc.sh distribution for free.
You can also keep using InSpec as a ruby library or keep using an older version before the license changed.

**Comment by clintoncwolfe** [comment]
Refs #5073
