### ISSUE TITLE
support `mode` what is more than just three octals

### ISSUE THREAD

**Issue by srenatus** [inspec/inspec#507]
Reported by @binamov:
In chef's file resources, the mode can consist of more than just the last three octals, for example it can be `1777`. In inspec, this is not possible because train [cuts of the leading bits](https://github.com/chef/train/blob/968563f246d4b2175e422ef7cb303a546df9b9b6/lib/train/extras/stat.rb#L51).

For users of both systems, this is confusing.

**Comment by justindossey** [comment]
Should be fixed when we get a new release of train.
