### ISSUE TITLE
Support `zfs_pool` and `zfs_dataset` resources on Linux

### ISSUE THREAD

**Issue by mattjmcnaughton** [inspec/inspec#5075]
Would y'all be open to removing the restriction that only allows the `zfs_pool` and `zfs_dataset` commands to run on FreeBSD? With the advent of ZFS on Linux (particularly its inclusion in Ubuntu 20.04), I imagine it'll see greater and greater Linux adoption. It'd be great if folks running ZFS on Linux could use the Inspec ZFS Resources.

## Detailed Description
If folks using Linux can't use the `zfs_pool` and `zfs_dataset`, but still want to test ZFS resources, they are left using `command`, which is less readable and wasted effort.

## Context
My personal use case is that I'm deploying ZFS on some Ubuntu 20.04 machines, and want to test my provisioning via Inspec using the built in `zfs_pool` and `zfs_dataset` resources.

## Possible Implementation
The first step would be removing the guard against any OS other than FreeBSD [here](https://github.com/inspec/inspec/blob/master/lib/inspec/resources/zfs_pool.rb#L18). We may also want to start using `which` to identify the `zfs/zpool` binaries, instead of relying on `/sbin/zfs`. I think that the ideas presented in https://github.com/inspec/inspec/pull/3800 could serve as a starting point.

If y'all are open to this feature, I'm happy to try and implement. Also, happy to have someone else implement it :)

Thanks so much for the great software - Inspec has made testing my infra a joy!

Aha! Link: https://chef.aha.io/features/SH-2190

**Comment by james-stocks** [comment]
Hi @mattjmcnaughton -
Thank you for the kind feedback and this detailed description.

I think your analysis is right, what is needed is:
1. Remove the `unless` condition that restricts zfs resources to BSD.
2. Test carefully on a host that _might_ have zfs but currently doesn't - need to ensure there are no unhandled exceptions. Resources should just return nil/false when they don't exist on the target host.
3. Handle zfs not always being `/sbin/zfs`

**Comment by mattjmcnaughton** [comment]
On Mon, Jun 08, 2020 at 03:13:17AM -0700, James Stocks wrote:
> Hi @mattjmcnaughton -
> Thank you for the kind feedback and this detailed description.
> 
> I think your analysis is right, what is needed is:
> 1. Remove the `unless` condition that restricts zfs resources to BSD.
> 2. Test carefully on a host that _might_ have zfs but currently doesn't - need to ensure there are no unhandled exceptions. Resources should just return nil/false when they don't exist on the target host.
> 3. Handle zfs not always being `/sbin/zfs`
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/inspec/inspec/issues/5075#issuecomment-640510254

Cool - I can take an initial stab at this hopefully within the next week? I must
admit, its been a while since I've worked w/ Ruby so no guarantees haha :P but
hopefully will be able to get a pr for y'all.

Of course, of someone else wants to work on it before then, please do! Maybe
just comment in the issue so I don't also spend time on it?

Thanks!

**Comment by james-stocks** [comment]
If you get a chance, that would be great, thank you! You could set yourself as assignee so anyone else reviewing this issue sees that someone is already looking into the implementation.

Cheers!

**Comment by clintoncwolfe** [comment]
Added on #5523
