### ISSUE TITLE
Upload results to Automate

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5088]
Now that we have a plugin class for reporters, it would be possible for InSpec to directly send reports to Chef Automate.

The audit cookbook currently does this - it has code to [send an InSpec report to Automate](https://github.com/chef-cookbooks/audit/blob/master/libraries/reporters/automate.rb) and also has code to [strip metadata](https://github.com/chef-cookbooks/audit/blob/master/libraries/helper.rb#L163) if the profile is already known to Automate.

The report is sent along with Chef-ish metadata like node name and UUID - InSpec would need to also have this data if it were to send an equivalent report.

Aha! Link: https://chef.aha.io/features/SH-2262

**Comment by james-stocks** [comment]
Some details that need to be taken care of:
 * audit cookbook has solid testing - that level of testing should be moved over to InSpec as well.
 * whatever we do should be usable by effortless as well - that might mean making a separate inspec-automate-upload gem (that is NOT a plugin) then having the reporter plugin simply call this gem.
 * retries need considered and should probably be configurable - some users will run InSpec very frequently and prefer some results get lost rather than keep the InSpec process alive for a long time; other users will run InSpec infrequently and want the results upload to succeed even if it takes many retries.
 * need to agree on the interface where Chef will pass node details that need added into the results (audit cookbook does that [here](https://github.com/chef-cookbooks/audit/blob/master/libraries/reporters/automate.rb#L119)) - this could be piped to InSpec as JSON or assumed to be available at a standard file location.

**Comment by james-stocks** [comment]
[inspec-compliance](https://github.com/inspec/inspec/tree/master/lib/plugins/inspec-compliance) largely does this already, though isn't a reporter plugin.

**Comment by clintoncwolfe** [comment]
As inspec-compliance already supports this, and audit cookbook has been replaced by Chef Infra Compliance Phase, we already have two ways of doing this. So, I think we are going to decline this work.
