### ISSUE TITLE
Please Help me to resolve this Issue In kali linux !

### ISSUE THREAD

**Issue by AShehan** [inspec/inspec#5092]
Please Help me to resolve this Issue !
When I type msfconsole in terminal show this error !
"root@kali:~# msfconsole
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      reline (>= 0)
      Available/installed versions of this gem:
      - 0.1.4
      - 0.1.3
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems."

Please Help me !

Aha! Link: https://chef.aha.io/features/SH-2284

**Comment by kmf** [comment]
`msfconsole` 
Maybe you should log it here: https://github.com/rapid7/metasploit-framework/issues

**Comment by james-stocks** [comment]
@AShehan - this isn't an issue with InSpec, so I'm closing.
@kmf has pointed you to a more suitable project to raise your issue (thank you Karl)
