### ISSUE TITLE
InSpecStyle Epic

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5095]
# Background

We currently have many `Inspec.deprecate` profile deprecations. Some of these [date back to InSpec 2, and were meant to be removed in InSpec 3](https://github.com/inspec/inspec/pull/1857/files). It is not uncommon now to receive requests from InSpec users to extend the lifetime of deprecations into InSpec 5. Removing deprecations is becoming increasingly painful.

We require a utility to not only track deprecations in existing code, but allow users to have these deprecations linted at composition. Where possible, it is also critical to supply autocorrecting functionality.

Additionally, we would benefit from adding agreed upon styles of InSpec to help developers write fast, efficient, secure and easily upgraded InSpec. We have at times received issues or support requests that are the result of InSpec being written in unexpected ways by maintainers. Instead of being reactive we can use the above tooling to be proactive.

NOTE: There have been some interested in having tooling like this replace everything in `check` (#4592). This issue does not take a stance on that issue and will leave it up for future, much later, discussion.

# Related Issues

* https://github.com/inspec/inspec/issues/4593
* https://github.com/inspec/inspec/issues/4592
* https://github.com/inspec/inspec/issues/3600
* https://github.com/inspec/inspec/issues/3549

# Tooling

## InSpecStyle

[InSpecStyle](https://github.com/schwad/inspecstyle) is a ruby gem that accomplishes the above. It is gratefully built upon the architecture of Rubocop, generating your own cops. As it is intended to be used on its own, the name has been branded solely `inspecstyle`.

The current build has four cops developed and will continue to grow leaning hard first on deprecations & autocorrection. [Docs](https://rubydoc.info/gems/inspecstyle)

## InSpec Check

There is a current branch where a minimal version [can be trialed out](https://github.com/inspec/inspec/tree/ns/inspecstyle) with an idea where we can make these code modifications later. This just shells out to the `inspecstyle` call. There are still issues to be resolved which are detailed below.

## InSpecStyle Atom Package

[The package](https://atom.io/packages/inspecstyle) is a fork of `linter-rubocop` with attribution, stripped down out of the box only to run `inspecstyle`.

## InSpecStyle VSCode Extension

TBD after atom is stable

# Epic

These are a list of tasks, which we will tag in future issues, which are required to launch InSpecStyle by the end of the year

## InSpecStyle

* Testing for all cops
* CI Integration passing and live
* All possible deprecations covered by cops

## InSpec Check

* Agreed formatter (Rubocop supports custom formatters, currently branch only pushes out Rubocop format after check)
* Bundle styling within inspec so this works out of the gate with as minimal setup as possible
* Support a flag to trigger InSpecStyle, so InSpec4 users can try it out on the way to InSpec5 (where it will be mandatory)

## InSpecStyle Atom Package

* Uncover why certain cops that appear to function on local runs are not linting in package
* Figure out how to get 'link' to styleguide to work and extra 'docs' to render

## InSpecStyle VSCode extension

* TBD

Aha! Link: https://chef.aha.io/features/SH-2296

**Comment by clintoncwolfe** [comment]
I think this is great! I can help on a VSCode extension, should that come to pass. 

I had a few questions / points to clarify:
- is this intended to lint profile code, or InSpec core code, or both? 
- The deprecation system is intended to deprecate functionality within core code, plugins, and profile code. I'm not sure that seeking to cover "all 66 deprecations" is a reachable goal - not all of them will occur within profile code (if that is indeed the intended scope).
- If this will replace `inspec check`, which currently also performs metadata (YAML) validation, what are your ideas for how will that functionality be preserved?

Again, I think this is a wonderful addition and I can't wait to see where it goes!

**Comment by Schwad** [comment]
@clintoncwolfe thank you so much for the kind words! 🙏 

* At this time, we really just envision this linting profile code
* Thanks for the info! So it seems a chunk of our deprecations actually aren't profile code which is good to know. :) 
* Longer term there may be hearty discussion on this - but my personal opinion would rather not see this replace `inspec check`. I would be happiest if this was a *part* of the `inspec check` run. Open for input as always though!

Thanks again and am excited as well! :D Cheers for the VSCode extension offer, I've *never* played around with VSCode extensions so it's a total blind spot for me at the moment.

**Comment by Schwad** [comment]
We are now tracking this in the formalized epic #5112 

👍
