### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5096]
## Detailed Description

When running `inspec exec`, especially at scale, it is possible to be sitting and waiting a while for a run to complete. For newer users (or even veterans) it is unclear at what point someone would wonder if the run was "hanging", or even if it will be a 2 minute or 20 minute run.

## Possible Implementation

We could implement a progress bar (I've used [progress_bar](https://github.com/paul/progress_bar), but [there are](https://github.com/jfelchner/ruby-progressbar) a host [of options](https://www.ruby-toolbox.com/categories/CLI_Progress_Bars) out there. 

With how InSpec is composed we may not know how many `describe` or `its` blocks there will be prior to runtime... but we should know how many controls there are ahead of time for custom iteration.

Further, there may be the possibility to `puts` out which control is being evaluated at the time with the progress_bar, helping our users be aware of and debug which controls are painfully long to evaluate. (I know there's nothing like true profiling, but that would be a separate issue 😅  )

Aha! Link: https://chef.aha.io/features/SH-2317

**Comment by james-stocks** [comment]
It would be great if the progress bar included phases for loading profiling (including evaluating ruby source) and then running controls. That would illustrate the case where user profiles are Ruby heavy.

**Comment by clintoncwolfe** [comment]
This doesn't tell you how many there will be, but there is this  https://www.inspec.io/docs/reference/reporters/#progress - it's the RSpec built-in.
