### ISSUE TITLE
Plugins are not loaded when InSpec is required as a ruby library

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5102]
https://github.com/inspec/inspec/issues/5099 reported that moving the CLI reporter to a reporter plugin broke kitchen verify.
It looks like this is because reporter plugin loading happens when the CLI is included (see [here](https://github.com/inspec/inspec/blob/439c93b115bfbddcb1fddd5bc9e74994f676bc10/lib/inspec/cli.rb#L432)). When another project just calls `require 'inspec` - no reporter plugins are loaded

We either need to move reporter plugin loading to somewhere where it _always_ happens; or we need all projects like kitchen-inspec to additionally `require 'inspec/cli'` so they run the plugin loading code.

If we want to depend increasingly on the reporter plugin pattern for new functionality, we must do the former.

Aha! Link: https://chef.aha.io/features/SH-2331

**Comment by clintoncwolfe** [comment]
The issue isn't that all reporter plugins need to be loaded - it's that the CLI reporter is always assumed to be available. That one specifically needs to be loaded. So rather than requiring `inspec/cli` (which is pretty heavy) in kitchen-inspec (which would require synchronization of another software release), I'd suggest loading the CLI reporter plugin in the inspec runner. That's the common entry point for both CLI invocation and kitchen-inspec.

**Comment by clintoncwolfe** [comment]
I think a prerequisite is that #5106 (basic test kitchen testing) be in place.

**Comment by clintoncwolfe** [comment]
Looks like this affects v4.22.22 with the pluginized junit reporter as well, so I am officially wrong in my prior statement that only the cli reporter would be affected.

**Comment by Schwad** [comment]
> The issue isn't that all reporter plugins need to be loaded - it's that the CLI reporter is always assumed to be available. That one specifically needs to be loaded. So rather than requiring `inspec/cli` (which is pretty heavy) in kitchen-inspec (which would require synchronization of another software release), I'd suggest loading the CLI reporter plugin in the inspec runner. That's the common entry point for both CLI invocation and kitchen-inspec.

After we merge and are happy with #5204 , could we have a dedicated `LoadInternalPlugins` service/method in the runner where we `autoload` or `require` internal services that have been pluginitized? (For now I'm thinking like CLI/JUnit but we could add more in the future)

I would be curious to hear the history as to why so many of our requires/autoloads aren't handled in `lib/inspec.rb`.
