### ISSUE TITLE
Run test/integration in CI

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5106]
We have a [`test/integration`](https://github.com/inspec/inspec/tree/master/test/integration) directory that we don't run in CI - this could and should be added to BuildKite verification

Acceptance Criteria:
* Get one of the tests within [`test/integration`](https://github.com/inspec/inspec/tree/master/test/integration) working
  * run-context-tk
  * run-context-after-audit
* Cut follow-up issue to get the other one green

Aha! Link: https://chef.aha.io/features/SH-2335

**Comment by james-stocks** [comment]
During or after doing this, take a look at https://github.com/chef/chef/tree/master/kitchen-tests - work has gone into running a kitchen suite across a selection of OS images

**Comment by clintoncwolfe** [comment]
As we a now have kitchen testing in #5204, I'm closing this.
