### ISSUE TITLE
Report a profile that fails to load as "failed" 

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5107]
If you have a profile that raise an exception outside a control e.g. 

```
raise 'oh no!'

control "tmp-1.0" do                        # A unique ID for this control
  impact 0.7                                # The criticality, if this control fails.
  title "Create /tmp directory"             # A human-readable title
  desc "An optional description..."
  describe file("/tmp") do                  # The actual test
    it { should be_directory }
  end
end
```

Then run `inspec exec crash_profile working_profile --reporter=json`...
...currently InSpec will just crash on the invalid code of `crash_profile`, the `working_profile` does not run, and no JSON report is generated.

It would be better than we catch exceptions and report the profile as `errored` (similar to how unsupported profiles still generate a report, with the profile reported as `skipped` )

This should work with all reporters (at least, no reporter should default to glossing over the errored profile).
There should be a non-zero exit code (tbc) for this case.

Aha! Link: https://chef.aha.io/features/SH-136

**Comment by alexpop** [comment]
Thank you @james-stocks, for reference this is how a "skipped" profile is reported at the moment:

```json
inspec exec ~/git/mycompliance-profile/mylinux-success --reporter json-automate | jq .
{
  "platform": {
    "name": "mac_os_x",
    "release": "19.4.0"
  },
  "profiles": [
    {
      "name": "mylinux-success",
      "version": "1.8.9",
      "sha256": "7718189f503eb3207fafcaa6b71e288b96c808c831123a3598602faf0ede8349",
      "title": "My Demo Linux successful profile",
      "maintainer": "Chef Software, Inc.",
      "summary": "Demonstrates the use of InSpec Compliance Profile",
      "license": "Apache 2 license",
      "copyright": "Chef Software, Inc.",
      "copyright_email": "support@chef.io",
      "supports": [
        {
          "platform": "windows"
        }
      ],
      "attributes": [],
      "groups": [],
      "controls": [],
      "status": "skipped",
      "skip_message": "Skipping profile: 'mylinux-success' on unsupported platform: 'mac_os_x/19.4.0'."
    }
  ],
  "statistics": {
    "duration": 0.003059
  },
  "version": "4.20.6"
}
```

**Comment by james-stocks** [comment]
**CASE 1**: control raises at runtime

e.g.

```
control "Test Exception Example" do                        # A unique ID for this control
  describe file("/tmp") do                  # The actual test
    raise 'time to crash lol'
    it { should be_directory }
  end
end
```

inspec/lib/inspec/runner.rb:287 in get_check_example(m, a, b)

**CASE 2**: (not really different from 1): invalid code inside a test

e.g. 

```
control "Test Exception Example" do                        # A unique ID for this control
  describe file("/tmp") do                  # The actual test
    this_method_doesnt_exist
    it { should be_directory }
  end
end
```

**CASE 3**: Invalid code outside a test: 

e.g. 

```
this_method_doesnt_exist

control "Test Exception Example" do                        # A unique ID for this control
  describe file("/tmp") do                  # The actual test
    it { should be_directory }
  end
end
```

(this manifests in /Users/jstocks/code/inspec/lib/inspec/profile.rb:205:in `collect_tests' )

**CASE 4**: Invalid code inside a control but outside a test:

e.g. 

```
control "Test Exception Example" do 
    
  this_method_doesnt_exist
  
  describe file("/tmp") do                  # The actual test
    it { should be_directory }
  end
end
```

This case is OK because it gets reported:

```
Profile: InSpec Profile (test_exception)
Version: 0.1.0
Target:  local://

  ×  Test Exception Example: test/fixtures/profiles/test_exception/controls/raises.rb:1
     ×  Control Source Code Error test/fixtures/profiles/test_exception/controls/raises.rb:1 
     undefined local variable or method `this_method_doesnt_exist' for #<Inspec::Rule:0x00007fd079194cf8>
```


**CASE 5**: Hit a deprecated resource

e.g.

https://github.com/dev-sec/apache-baseline/archive/0b5f21e668940d53e85c2ca36b41ba7ae18fac01.tar.gz uses the `apache` resource

InSpec sends an error to stderr and exits. Any other profiles passed at the CLI do not run.

**CASE 6**: other error we've not seen before

No example - the ways in which InSpec might crash cannot be enumerated.

Generally, InSpec writes an error to stderr and exits

**Comment by james-stocks** [comment]
Case 1 & 2 should report a failed control, if possible.

Case 3 would need to be a "failed profile". 

Case 4 needs no work.

Case 5 needs handled by the program that launches InSpec e.g. audit, automate.

**Comment by galenemery** [comment]
Do these cases catch if the result from a valid control contains invalid characters?  So, it's not the control evaluation, but the actual result is invalid.

For instance, the etc/security/user file has invalid characters in usernames to be parsed.

**Comment by james-stocks** [comment]
Hi @galenemery  - 

Looking at the specific customer issue, this is case 3. A Ruby exception is being thrown outside of an InSpec control.
InSpec doesn't get as far as control evaluation - it crashes before it has collated what controls and tests are inside the profile.

While we should implement this ticket and allow the error to be reported, this can be avoided by steering customers towards always putting raw Ruby code into custom resources.

**Comment by galenemery** [comment]
Aha!  Thanks.  That explains how this didn't get caught cleanly.  We of course can't expect that customers will always follow best practices, so definitely we should do it.  But makes more sense now how we didn't catch the error.
