### ISSUE TITLE
source code is licensed under Apache 2.0, runtime forces to accept Chef EULA

### ISSUE THREAD

**Issue by mvanholsteijn** [inspec/inspec#5109]
This repository is licensed under the Apache 2.0 license, which allows both commercial and private use. However, when I run InSpec, it forces me to accept the EULA which disallows the use of InSpec as a company.

# Describe the problem
As a company I do not want to break a license agreements, but this  promises one form and then forced to accept another at runtime.

## Possible Solution
1. Add --accept-license=apache-2.0?
2. Change the license text in the repository
3. Activate the --accept-license functionality only on chef distributed binaries

Aha! Link: https://chef.aha.io/features/SH-2348

**Comment by aaronlippold** [comment]
Hello,

You are correct, the solution that the community has taken is similar to
other paths taken before.

The binaries built by Chef are what is covered under the EULA which is what
you are agreeing to when accepting the EULA. The source code of the project
is still Apache 2.0. This is very similar to the RHEL managed binary
packages used in their distribution, vs the CentOS Open Source
distribution which does not contain trademarks, non-opensource code, etc.

In the same way, the chef community has created the Cinc project -
https://cinc.sh - which builds fully Apache 2.0 compliant binary
distributions of the Apache 2.0 software.

Please see https://saf.mitre.org/#/faq#5 for a full write-up and see Chef's
Blog articles as well for the full details.

Also note, the EULA only applies if you are using the binaries in
Production, so you are free to use the Chef binaries in Dev, Test,
Demonstration, Pre-Prod etc. without breaking the EULA. Also note, as a
community member, you have many paths to being able to use the EULA
software, contribution, community interaction, etc. without having to
formally pay for a support agreement. I don't recall specifically where we
landing on this tit for tat but there was much discussion and we wanted to
ensure people had many paths.

As a note, (3) is already the default - all chef built binaries do use the
accept-license process. It seems we just need to do a better job of
communication on this to the community. (2) is not needed as if we improve
the clarity on what is under the EULA and what isn't then it should be
clear. (1) would not make sense given that what you are actually using is
not under apache 2.0. - but again this goes back to better communication.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by james-stocks** [comment]
Hi @mvanholsteijn -

Aaron has summarised this perfectly (thanks @aaronlippold :) ).
It is intentional that our source code is Apache 2.0 but our distribution is a commercial license.

Would you consider this issue resolved if the README for this repository made the licensing model clear?

**Comment by mvanholsteijn** [comment]
For me the issue is resolved; I think it is very handy if you were more explicit  in the README.
