### ISSUE TITLE
InSpecStyle Epic

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5112]
This is a redraft as internal tooling requires declaring as epic. See: https://github.com/inspec/inspec/issues/5095

# Background

We currently have many `Inspec.deprecate` profile deprecations. Some of these [date back to InSpec 2, and were meant to be removed in InSpec 3](https://github.com/inspec/inspec/pull/1857/files). It is not uncommon now to receive requests from InSpec users to extend the lifetime of deprecations into InSpec 5. Removing deprecations is becoming increasingly painful.

We require a utility to not only track deprecations in existing code, but allow users to have these deprecations linted at composition. Where possible, it is also critical to supply autocorrecting functionality.

Additionally, we would benefit from adding agreed upon styles of InSpec to help developers write fast, efficient, secure and easily upgraded InSpec. We have at times received issues or support requests that are the result of InSpec being written in unexpected ways by maintainers. Instead of being reactive we can use the above tooling to be proactive.

NOTE: There have been some interested in having tooling like this replace everything in `check` (#4592). This issue does not take a stance on that issue and will leave it up for future, much later, discussion.

# Related Issues

* https://github.com/inspec/inspec/issues/4593
* https://github.com/inspec/inspec/issues/4592
* https://github.com/inspec/inspec/issues/3600
* https://github.com/inspec/inspec/issues/3549

# Tooling

## InSpecStyle

[InSpecStyle](https://github.com/schwad/inspecstyle) is a ruby gem that accomplishes the above. It is gratefully built upon the architecture of Rubocop, generating your own cops. As it is intended to be used on its own, the name has been branded solely `inspecstyle`.

The current build has four cops developed and will continue to grow leaning hard first on deprecations & autocorrection. [Docs](https://rubydoc.info/gems/inspecstyle)

## InSpec Check

There is a current branch where a minimal version [can be trialed out](https://github.com/inspec/inspec/tree/ns/inspecstyle) with an idea where we can make these code modifications later. This just shells out to the `inspecstyle` call. There are still issues to be resolved which are detailed below.

## InSpecStyle Atom Package

[The package](https://atom.io/packages/inspecstyle) is a fork of `linter-rubocop` with attribution, stripped down out of the box only to run `inspecstyle`.

## InSpecStyle VSCode Extension

TBD after atom is stable

# Epic

These are a list of tasks, which we will tag in future issues, which are required to launch InSpecStyle by the end of the year

## InSpecStyle

* Testing for all cops
* CI Integration passing and live
* All possible deprecations covered by cops

## InSpec Check

* Agreed formatter (Rubocop supports custom formatters, currently branch only pushes out Rubocop format after check)
* Bundle styling within inspec so this works out of the gate with as minimal setup as possible
* Support a flag to trigger InSpecStyle, so InSpec4 users can try it out on the way to InSpec5 (where it will be mandatory)

## InSpecStyle Atom Package

* Uncover why certain cops that appear to function on local runs are not linting in package
* Figure out how to get 'link' to styleguide to work and extra 'docs' to render
* https://github.com/Schwad/InSpecStyle-atom/issues/2
* https://github.com/Schwad/InSpecStyle-atom/issues/3

## InSpecStyle VSCode extension

* TBD

Aha! Link: https://chef.aha.io/features/SH-2370

**Comment by james-stocks** [comment]
This is brilliant!

It sounds good to make deprecation cops part of the initial release. 
At some point we will need cops for InSpec coding style - those might need an RFC per-cop to let the community discuss what will start to be enforced.

**Comment by Schwad** [comment]
Thank you! 🙏  I really like that idea!

Hopefully since we have a fair few deprecations they'll help us in shaking out the bugs and making this a robust tool... & I look forward to the robust RFC community discussion on proper InSpec style.

**Comment by Schwad** [comment]
Update - still wrangling with Atom - for some reason it is *only* recognizing one rule.... which is weird.. going to try and make a dummy rule cloning this rule (say matching 'attribute1' instead) to see if the failure is *just* accepting 1 rule or if there's something magical about how I composed the `attribute` rule that I need to copy over to the other rules.

**Comment by Schwad** [comment]
Above comment being tracked here: https://github.com/Schwad/InSpecStyle-atom/issues/2 

Attempting the logic from above of a new dummy cop

**Comment by Schwad** [comment]
NOTE: When developing on the atom, this is a gotcha that I've learned the hard way. Due to caching, simply killing atom and reinstalling the gem is not enough to persist checks on cop changes. 

What I do to fully rebuild the gem and reflush the Atom cache (there's probably a more programmatic way to do this) is:

`rm -rf pkg/inspecstyle-0.2.1.gem; rake build; gem uninstall inspecstyle; gem install --local pkg/inspecstyle-0.2.1.gem`

THEN close atom, reopen it briefly in safe mode (to dump the cache, https://discuss.atom.io/t/clean-cache-when-atom-starts/13196/8 this was the closest I could find to manual ways to do this), then reopen again normally to have a clean slate.

The good news is that once this is up and running this flow of debugging and development will be very rare, we'll just know the cops work.

**Comment by Schwad** [comment]
Final note - to pick up for next week. I was wrong. I completely uninstalled inspecstyle from my system and inspecstyle atom and nuked everything. Upon restart I just installed the atom package and the same behaviour happened so the gem is vendored somewhere. Going to try to either find the vendor or navigate my way through this with different rubies/versions on tuesday.

**Comment by Schwad** [comment]
Great update today for the Atom package but posting on the Epic for visibility.

YES - all the latest updates are available and working. I just reinstalled everything on a clean laptop today and confirmed that we are in fact linting everything. 

I still need to solve the following two issues but this is great progress as anyone stumbling upon the package will have a working instance:

- [ ] determine how to truly kill/update/reload inspecstyle core gem being relied upon by atom package - as I had this bug where it is pinned to an old inspecstyle that I need to locate
- [ ] figure out what I'm missing in formatting to allow me to be able to render the 'examples'/'links' documentation in the linter (though it currently does display the main text of the violation which is our main point) 🎉

**Comment by clintoncwolfe** [comment]
I'm closing this, as we're using cookstyle.
