### ISSUE TITLE
InSpecStyle integration with `inspec check`

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5113]
## Detailed Description

This is one of the key issues to pass the [InSpecStyle Epic](https://github.com/inspec/issues/5112). This will allow us to utilize the InSpecStyle offerings to inform preferred profile code upon running `inspec check`, the main example at the moment being deprecations. 

This is an MVP integration. No existing check functionality should be replaced at this point (that would be a separate future issue). 

## Context
InSpecStyle tooling allows inspec developers to write upgradable, secure, fast, sustainable code. The paths to inform InSpecStyle include editor linters, manual CI-capacity checks with a rubygem, and `inspec check` integration.

## Possible Implementation

For InSpec 4, this should only be enabled with a flag. Such as `inspec check --include-style`. In InSpec 5 the intent is to reverse this, and have the feature be opt-out instead of Opt-In. 

Core InSpecStyle does support autocorrecting functionality, so there may be room for autocorrect functionality within the CI as well. There is a small branch that has started this effort. https://github.com/inspec/inspec/tree/ns/inspecstyle (WIP)

## Tricky Elements

Packaging and running `InSpecStyle` will require setting up a separate rubocop environment that ignores other cop setups that may be present, and only run the InSpecStyle cops.

Aha! Link: https://chef.aha.io/features/SH-2372

**Comment by clintoncwolfe** [comment]
Cookstyle now has support for some inspec Cops. We may want to consider integrating with cookstyle instead.

**Comment by clintoncwolfe** [comment]
Closing in favor of #5611
