### ISSUE TITLE
Resources using wrong os family for FreeBSD

### ISSUE THREAD

**Issue by fzipi** [inspec/inspec#5119]
# Describe the problem

When using the `user` resource in FreeBSD, checks are skipped due to unsupported os. 

The problem resides in `users.rb`:
```
elsif ["freebsd"].include?(os[:family])
```
But that would never match, as family is just `bsd`.
## Possible Solution

Sending patch, just changing there to `bsd` worked.

Aha! Link: https://chef.aha.io/features/SH-2427

**Comment by fzipi** [comment]
Having a second look, when should `os.bsd?` be used vs `os[:family] == 'freebsd'`?

**Comment by fzipi** [comment]
Ok, got it.

If you want `freebsd`, you need to use ``["freebsd"].include?(os[:name])`, not `os[:family]`.

**Comment by Schwad** [comment]
Hi @fzipi - going through your PRs here. It appears that #5120 | #5121 | #5122 here are all related?

Do you still have questions or do you still want to progress with your PRs? As they cover the same issue if so I'd suggest combining them to ensure they pass the test suite.

**Comment by fzipi** [comment]
Sure @Schwad .You want me just to push all in one PR?

**Comment by fzipi** [comment]
@Schwad Merged all in one PR.

**Comment by fzipi** [comment]
This was fixed in #5123 .
