### ISSUE TITLE
Fix Reporting of MacOS Release Version

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#5140]
## **What problem are we solving?**

_Should be a few sentences. Describe the user stories and the target market._

MacOS customers that are running profiles that check against the release version of MacOS currently have the Darwin kernel version returned instead (e.g. '18.7.0' vs '10.14.6' (Mojave)). The expected output should be the latter - 10.14.6. As we don't know which version customers are keying in on currently, this change should be breaking and meant for a major version bump.

Also, to ensure users are still able to retrieve the kernel version if that's what they desire, we need to be able to provide them a way to do that.

- As an IT Operator

    - I want to be able to audit against a given product version of MacOS (e.g. Catalina = 10.15)

## **Objective and Key Results**

_What's the ideal outcome? How will we measure that we're successful?_

**Objective** | **Key Results**
-|-
Change the OS version attribute of a MacOS resource to refer to the product version|Users are able to test against the product version (rather than the kernel version) of a MacOS target
Add an OS kernel version attribute for MacOS resources|Users who currently test against the kernel version of a MacOS target are able to continue doing so

## **Acceptance Criteria**

_How will we know when we're done?_

- User is able to test against a MacOS target's product version
- User is able to test against a MacOS target's kernel version

## **Dependencies**

_What other work needs to come first? What will block us from success?_

## **Out of Scope**

What problems are not included in this epic?

## **Open Questions**

_What questions still need to be addressed?_

- Does the kernel version attribute need to be supported for other platforms? At least other \*nix platforms?

    - A: We should definitely consider other \*nix platforms, but if it's quicker to implement this use case for MacOS specific users, we should aim for that first, with a road map item to cover the others. The motivator should be customer feedback based for the other platforms.

## Related Links

- [https://github.com/inspec/train/pull/560](https://github.com/inspec/train/pull/560)

Aha! Link: https://chef.aha.io/features/SH-157

**Comment by james-stocks** [comment]
This is in platform detection so we need to track an issue in train as well
(track, get it?)

Since detection is also shared with Infra we need to coordinate the change with them as well.

**Comment by kekaichinose** [comment]
Comment added by Lisa Stidham in Aha! - [View](https://chef.aha.io/comments/6928527616451667328)

Noting [Issue 5140](https://github.com/inspec/inspec/issues/5140)

**Comment by clintoncwolfe** [comment]
This feels like a breaking change for the sake of breaking things. This would add a lot of complexity to the existing compliance profiles and would break a lot of customers. I would much prefer to introduce a new field on the platform detection object - call it "os_product" or something - that returns the 10.x number that some users may be looking for.
