### ISSUE TITLE
AWS resource documentation bugs

### ISSUE THREAD

**Issue by kagarmoe** [inspec/inspec#5145]
1. Resource aws_cloudwatch_log_group doesn't seem to exist anymore when using inspec-core-4.18.100
2. Clarify the options needed for the aws_iam_policy In the latest tagged release of inspec-aws. It needs "optionised" arguments. Running a describe aws_iam_policy("somepolicy) fails inspec without any errors but with the warning:  "aws_iam_policy: One of [:policy_arn, :policy_name] must be provided."

Aha! Link: https://chef.aha.io/features/SH-2619

**Comment by mjingle** [comment]
AWS resource documentation is supposed to come from inspec-aws repo, not inspec-core. We're currently working on a docs fix for this.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #299](https://github.com/inspec/inspec-aws/issues/299) via [**ZenHub**](https://www.zenhub.com/)
