### ISSUE TITLE
Update RELEASE_PROCESS.md to cover expeditor retry cases

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5155]
# Describe the problem

Currently, we have a 10-step workload on expeditor when running `/expeditor promote inspec/inspec:master x.x.x`. 

If any of those steps fails, we are given a "retry" button. However, the workload is not inherently "retry-supported". For example, if any step after `built_in:publish_rubygems` fails, then a retry will certainly fail the rubygems step saying that the gem has already been released and break the rest of the workload. Additionally, the steps such as `bash:./expeditor/publish-release-notes.sh` are unlikely to have a case to run twice. 

The current advice is if the workload fails, once we are able to retry (say an external outage is resolved) to make a dummy PR commenting out the succeeding steps and merge to master, then click the retry button. In theory expeditor should see this and only start at the uncommented out steps. In practice the retry still would execute each step, dying on an earlier step like `built_in:publish_rubygems`. It is possible that the advice should be 1. merge dummy pr 2. wait for dummy pr master builds to complete-- but this is unconfirmed due to the difficult nature of testing this in normal uptime.

Without a retry process, the only solution would be __manually__ executing these steps either from support or locally, which is not what it was built for and unsustainable. 

Handling this case with a retry is also undocumented in `RELEASE_PROCESS.md` and could be a valuable addition.

## Possible Solution

Obtain guidance on a working approach for promotion retries. If in any way possible, test it (this will take some thinking) manually at least once. Include guidance in `RELEASE_PROCESS.md`

Aha! Link: https://chef.aha.io/features/SH-2645

**Comment by james-stocks** [comment]
Thanks for making sure we track this @Schwad 

I think some items can/should be directly fixed in Expeditor. Some of the steps (i.e. our own bash scripts) we should add idempotency to.

Short term `RELEASE_PROCESS.md` could have steps for recovering from promotion errors - those this could simply be to raise with RelEng to get their immediate support. There's bits we simply cannot do e.g. only expeditor has permission to promote our Habitat packages.
