### ISSUE TITLE
alias "inspec compliance" with "inspec automate"

### ISSUE THREAD

**Issue by mattray** [inspec/inspec#5157]
Users looking for working with Automate for uploading/downloading/listing profiles have a hard time finding the `inspec compliance` command as the proper command. Conversely, there is now a(nother) Chef Compliance product further confusing the naming. I'd recommend simply providing the alias `inspec automate` for `inspec compliance` and deprecating `compliance` for removal in InSpec 5.

Aha! Link: https://chef.aha.io/features/SH-2656

**Comment by james-stocks** [comment]
cc @kekaichinose 
We should also search the codebase + docs for references to "compliance" (the EOL Chef product), and remove them.

**Comment by Vasu1105** [comment]
Fixed in #5490
