### ISSUE TITLE
Reporter - messages should only be noted as truncated if they were actually truncated

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5162]
https://github.com/inspec/inspec/blob/v4.22.1/lib/inspec/reporters/base.rb#L24-L25

```
            if r.key?(:message) && r[:message] != "" && trunc > -1
              r[:message] = r[:message][0...trunc] + "[Truncated to #{trunc} characters]"
```

If a message truncation length is given in options, then `"[Truncated to #{trunc} characters]"` is appended to every result message, even shorter messages that did not lose any characters to truncation. This looks confusing - it should only be appended when the message was shorter than the truncation limit.

Aha! Link: https://chef.aha.io/features/SH-2692

**Comment by james-stocks** [comment]
@alexpop @Schwad @kekaichinose - this is the bug discussed in Slack.

**Comment by alexpop** [comment]
Agree, thank you @james-stocks
