### ISSUE TITLE
[chef-compliance] Page Refresh using IE or Edge 

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#517]
Hi there

I've come across an issue using IE and Edge with the chef compliance gui.

After successfully adding a profile (or a node) the webpage doesn't refresh, it displays a message at the bottom of the screen saying that it added the profile successfully but it doesn’t refresh the page with the new version number.

If I click off the compliance page, say to dashboard and then back again it still displays the old version

I have to ctrl refresh the page to update it. 

Haven't noticed this with firebox, the page automatically refreshes.

Don't know if you deem this a bug or an IE funny but in the case of adding a node it’s a little confusing as you get the message at the bottom of the screen that its been successfully added yet it doesn’t list it.

Things get a little worse with Microsoft Edge (25.10586.0.0) in that ctrl-refresh doesn’t work, I had to close the browser and re-login to update the page.

My version of chef-compliance is 0.14.5-1
My version of IE is Internet Explorer 11 (11.103.10586.0)

Best Regards

Gary

**Comment by chris-rock** [comment]
Thanks Gary, I understand this is annoying and we will have a look.

**Comment by jquick** [comment]
Thanks for reporting this. Closing this due to the lag time. Please reach out to your account contact if your still having issues.
