### ISSUE TITLE
Piping in custom config with reporter truncation setting does not appear to function

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5172]
# Describe the problem

To reproduce, use this use case: https://github.com/inspec/inspec/pull/5165#issuecomment-665554413

## Possible Solution

Unsure, may require simply running this command whilst prying in.

**Comment by Schwad** [comment]
To replicate against a local inspec build run:

`echo '{"reporter_backtrace_inclusion": false, "reporter_message_truncation": 10, "reporter":["json-automate"], "backend_cache":true}' | bundle exec inspec exec test/fixtures/profiles/failures --json-config=- | python -m json.tool`

**Comment by Schwad** [comment]
@alexpop I did a bit more research on this today.

It appears that `--json-config` [was deprecated in InSpec 3.6](https://github.com/inspec/inspec/pull/3750) and will be removed in InSpec 5. Trying this with `--config` instead of `--json-config` I do appear to get truncation on my machine whilst piping in the config. Can you confirm if this works for you?

`echo '{"reporter_backtrace_inclusion": false, "reporter_message_truncation": 10, "reporter":["json-automate"], "backend_cache":true}' | bundle exec inspec exec test/fixtures/profiles/failures --config=- | python -m json.tool`

**Comment by alexpop** [comment]
Great find @Schwad 
I confirm that truncation works with `--config`

In this case the InSpec scanner in Automate needs updating:

```
[01:00:04 ~/git/automate/components/compliance-service (master)]$ ag '\-\-json-config'
inspec/cli.go
182:		args = append(args, "--json-config=-") // read config from stdin

inspec-agent/remote/remote.go
133:			echo '%s' | sudo CHEF_LICENSE="accept-no-persist" inspec exec %s --json-config=-
151:						if($JsonConfig -ne $null) { $JsonArgument = '--json-config="-"' }
```

**Comment by Schwad** [comment]
Thanks Alex! I'm glad I was able to find it - I had actually set aside more
time than this for this issue so now I'm actually ahead of the game 😂
thank you for raising this though so we could get to the bottom of it 🙏
