### ISSUE TITLE
Filter EC2 instances by Tag

### ISSUE THREAD

**Issue by heldersepu** [inspec/inspec#5174]
Trying to filter EC2 instances by Tag, as shown in the examples:
https://github.com/inspec/inspec/blob/master/www/content/inspec/resources/aws_ec2_instances.md#filter-ec2-instances-with-their-environment-tags-equal-to-dev-then-test-in-depth-using-aws_ec2_instance
but it just errors out

# Describe the problem
Just run 
```
aws_ec2_instances.where(tags: {"Environment" => "Dev"}).instance_ids.each do |id|
  describe aws_ec2_instance(id) do
    it { should be_stopped }
  end
end
```
getting error:
`':tags' is not a recognized criterion - expected one of :instance_id'`

# Version
4.22.1

**Comment by heldersepu** [comment]
Cross post:
https://github.com/inspec/inspec-aws/issues/267

**Comment by omerdemirok** [comment]
@heldersepu, can u have a look at this?
https://github.com/inspec/inspec-aws/issues/255#issuecomment-686426000

Seems like you are using AWS resource in inspec core (soon be depricated), which do not support filtering by `tags`.

**Comment by heldersepu** [comment]
Interesting so by adding the:
`depends` pointing to the correct location that fixes it?

**Comment by heldersepu** [comment]
that is it
