### ISSUE TITLE
Colo[u]r those dots and Fs!

### ISSUE THREAD

**Issue by jjasghar** [inspec/inspec#518]
It's pretty common now to see colo[u]rs for "." and "F"s in tests.

I'd like to ask that this is added to the runs, so something like the following would be colo[u]red.

```
       Search `/Users/jasghar/repo/cookbooks/hipchat-chef-plugin-cookbook/test/integration/default` for tests
......FF........

Failures:
```

This would also put the Failures in RED so you can could identify issues quickly.

**Comment by conorsch** [comment]
It's obviously superficial, but lack of color in the documentation format for inspec test runs is one of the reasons I'm still using serverspec. When performing an extremely repetitious task like running tests, colored output really reduces the cognitive burden for parsing the results.

**Comment by chris-rock** [comment]
+1 lets get this in

**Comment by arlimus** [comment]
Color is the default now; use `--no-color` to deactivate

**Comment by jjasghar** [comment]
Rock on guys! Fast turn around and great thanks!
