### ISSUE TITLE
oracledb_session doesnt work with sqlplus 12.1 or lower. 

### ISSUE THREAD

**Issue by pacopal** [inspec/inspec#5182]
# Describe the problem

Running inspec **from the database servers** and using oracledb_session will fail, when the database server version is 12.1 or 11g. This is because the sqlplus version installed in the database servers will match with the database versions.

oracledb_session is using the following format options:
`format_options = "SET MARKUP CSV ON\nSET PAGESIZE 32000\nSET FEEDBACK OFF"`

Unfortunately "SET MARKUP CSV ON" was introduced in sqlplus version 12.2.0.1. So prior versions will miss it. 
Reference:
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqprn/index.html#SQPRN-GUID-98CEF1F8-FB5A-495F-8771-693546655613

Note: Using sqlcl from the database servers could be considered, but would force to deploy the tool (and deal with the java requirements). Not a desired solution in several cases. Note that the database servers have sqlplus out-of-the-box.

## Possible Solution

A potential workaround is to replace the format options with a more generic set: 
`format_options = "SET PAGESIZE 32000\nSET FEEDBACK OFF\nSET UNDERLINE OFF"`

```
    def query(sql)
      if @sqlcl_bin && inspec.command(@sqlcl_bin).exist?
        @bin = "#{@sqlcl_bin} -S"
        format_options = "set sqlformat csv\nSET FEEDBACK OFF"
      else
        @bin = "#{@sqlplus_bin} -S"
        format_options = "SET PAGESIZE 32000\nSET FEEDBACK OFF\nSET UNDERLINE OFF"
      end
```

Based in the current logic used in parse_csv_result, that approach works. 

NOTE: I have created a copy of oracledb_session as a new class in my Library. I have modified it to use above solution successfully. It works properly in 11g, 12.1, 12.2 and 19c.

**Comment by Schwad** [comment]
Thanks for this @pacopal and for catching this! Would you be able to file a PR to that effect?

**Comment by Nik08** [comment]
@clintoncwolfe This change was already made by @pacopal in PR #5193. This issue could be closed.
