### ISSUE TITLE
postgres_session does not have a param for the `port` to be set

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#5183]
The postgres_session resource needs to allow the user to pass a port for the target db as we do for host and db_name etc

**Comment by Schwad** [comment]
Thanks for filing this, Aaron!

For anyone coming here and interested in this, I think you'll want to make the change here:

https://github.com/inspec/inspec/blob/beaad73586806e93ddab242542205a18aecc2cd3/lib/inspec/resources/postgres_session.rb#L42-L57

And take inspiration from the host resource here:

https://github.com/inspec/inspec/blob/master/lib/inspec/resources/host.rb#L47-L49

(Note, one passes in as params hash and the other as vanilla args, you might want to include port as an optional arg. Then cover with a test)

**Comment by aaronlippold** [comment]
I think this is a good start, I would just want to test that modifying the constructor in this way is backwards compatible with folks code so we don't introduce a breaking change.

**Comment by StylusEaterChef** [comment]
> I think this is a good start, I would just want to test that modifying the constructor in this way is backwards compatible with folks code so we don't introduce a breaking change.

An optional port argument with a sane default (5432?) should be backwards compatible. Or am I missing something?

**Comment by StylusEaterChef** [comment]
@Schwad and @aaronlippold are either of you able to check out the PR?

**Comment by clintoncwolfe** [comment]
Fixed by #5185
