### ISSUE TITLE
Not able to identify cloudwatch alarms from inspec

### ISSUE THREAD

**Issue by ashima15448** [inspec/inspec#5191]
I am trying to ensure that my cloudwatch exists using InSpec. I have created an alarm and am passing its details as input variables. However, inspec fails to identify my alarm and says that it does not exist. I am using the following code:
```
        # Ensure an Alarm exists
        describe aws_cloudwatch_alarm(metric_name: metric_name, metric_namespace: metric_namespace) do
            it { should exist }
        end
```

Output:
```
×  CloudWatch Alarm StatusCheckFailed_Instance AWS/EC2 is expected to exist
     expected CloudWatch Alarm StatusCheckFailed_Instance AWS/EC2 to exist
```
Can someone please help me with the issue.

Thank you.

**Comment by clintoncwolfe** [comment]
I'm going to close this as there is not enough information available to diagnose the issue, and it is fairly old. I'm sorry this was not answered sooner.
