### ISSUE TITLE
Switch from term-ansicolor to pastel

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#5195]
## Detailed Description

We've somewhat standardized on gems from the tty project for handling input and console display in Ruby projects. They're well designed, tested, and documented. Standardizing on these gems also lets us keep our overall package sizes down as we reduce the number of deps we ship for duplicate functionality. Pastel is used by several projects in the chef ecosystem and allows for setting console colors. It's actually already a dep on inspec via the `license-accept` gem. Switching to this would allow us to remove both the `term-ansicolor`, `tins`, and `sync` deps which take up about 600k on disk.

**Comment by clintoncwolfe** [comment]
Resolved by #5201 - term-ansicolor was unused
