### ISSUE TITLE
Determine if we can bump rubyzip dep

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#5200]
We currently rely on a dated version of rubyzip (1.x). We should figure out if we can ship the current release:

https://github.com/rubyzip/rubyzip/blob/v2.3.0/Changelog.md

**Comment by btm** [comment]
This was added as a pessimistic constraint way back at the start of time and appears to have been cargo-culted along.

7a59d9ce76a07fab7ace4b24e43d75ec840f66f4
Date:   Wed Aug 12 22:34:24 2015 -0700

**Comment by Vasu1105** [comment]
@clintoncwolfe I think dependabot already did this update https://github.com/inspec/inspec/pull/5347. Do we still need any updates ?

**Comment by clintoncwolfe** [comment]
Nope, looks good - let's close this.
