### ISSUE TITLE
Invalid UTF-8 error when saving node attributes

### ISSUE THREAD

**Issue by yangpeng-chn** [inspec/inspec#5212]
This is a follow-up of the question: https://github.com/inspec/inspec/issues/541

# Describe the problem

I was trying to save the node attributes as json to file with Chef recipe and use it in my Inspec profiles. However the following error occurs at the time of saving the attributes to file.

Error:
`[2020-08-17T14:24:40+09:00] FATAL: Chef::Exceptions::JSON::EncodeError: ruby_block[save node attributes] (mlj_save_attributes_cb::default line 22) had an error: Chef::Exceptions::JSON::EncodeError: Invalid UTF-8 string '・ｽ・ｽ・ｽ・ｽ (・ｽW・ｽ・ｽ・ｽ・ｽ)': cannot encode to UTF-8`

Recipe:
```
ruby_block "Save node attributes" do
  block do
    File.write("/tmp/kitchen_chef_node.json", node.to_json)
  end
end
```

chef-client OS:
`windows2016`

## Possible Solution
Option 1. save to file using `node.to_hash` won't generate the error, but how do I read it in InSpsec profiles?
Option 2. It turns out the characters in `timezone `caused the issue, how can I generate the json file without `timezone `attribute?
Option 3. any other solution to encode the characters?

output of ohai command from the node.

```
...
  "time": {
    "timezone": "���� (�W����)"
  },
...

```

**Comment by clintoncwolfe** [comment]
Would this work?
```
ruby_block "Save node attributes" do
  block do
    data = node.to_hash
    data["time"].delete("timezone")
    File.write("/tmp/kitchen_chef_node.json", data.to_json)
  end
end
```

**Comment by lamont-granquist** [comment]
`Chef::JSONCompat.to_json(node, validate_utf8: false)` will scrub the node object.

The `to_json` API uses ruby's JSON gem and non-UTF8 characters aren't valid JSON so it correctly throws an exception.

**Comment by yangpeng-chn** [comment]
> Would this work?
> 
> ```
> ruby_block "Save node attributes" do
>   block do
>     data = node.to_hash
>     data["time"].delete("timezone")
>     File.write("/tmp/kitchen_chef_node.json", data.to_json)
>   end
> end
> ```

It worked!

**Comment by yangpeng-chn** [comment]
> `Chef::JSONCompat.to_json(node, validate_utf8: false)` will scrub the node object.
> 
> The `to_json` API uses ruby's JSON gem and non-UTF8 characters aren't valid JSON so it correctly throws an exception.

I think I tried the similar one quite a while ago, it didn't work at that time maybe there was something wrong with my code itself.

**Comment by Schwad** [comment]
Good to know @lamont-granquist && @clintoncwolfe ! :) 

@yangpeng-chn do you feel this has been resolved and we can close this issue?
