### ISSUE TITLE
Filter/Search/Iterate through mountpoints

### ISSUE THREAD

**Issue by unixengineer** [inspec/inspec#5216]
## Detailed Description
We have various kafka machines that have monts points like /app1.../app10  (and this varies by environment). Is it possible to use filter for all /app* and check for things?

## Context
Explained above

**Comment by clintoncwolfe** [comment]
Unfortunately, there is no easy way to glob files or directories - that is asked for on #709.  Right now you need to use a `command` resource with a `ls` or `find` command to get the list. You can't use Rubyism like `Dir`, because that would execute on the local machine - you must use Chef InSpec DSL keywords like `command`.

```
control "check the app mounts" do
  command("ls -d /app*").stdout.split.each do |appdir|
    describe directory(appdir) do
      # Whatever tests you need here
      its("owner") { should cmp "deploy" }
    end
  end
end
```

I hope that helps!

**Comment by unixengineer** [comment]
@clintoncwolfe I need to check if the mount point (not directory) is in RO or RW mode. In the method suggested by you, it checks it (/app*) as a directory, and not a mount right?

**Comment by clintoncwolfe** [comment]
Yes, I gave an example that simply looks at directories; apologies if I misunderstood. To examine mountpoints, you could do:

```
control "check the app mounts" do
  command("ls -d /app*").stdout.split.each do |appdir|
    describe mount(appdir) do
      it { should be_mounted }
      its("options") { should include "ro" } # Note this is an Array, use include
    end
  end
end
```

It's advisable to experiment with the [`mount`](https://docs.chef.io/inspec/resources/mount/) resource in `inspec shell` to determine exactly how the `options` property behaves in your case - on my Mac, I get the string "read-only" as an Array element.

**Comment by Schwad** [comment]
Hi @unixengineer - has this resolved your query so we can close off this issue?

Also, be sure to check out our community InSpec channel (with 1700+ members!) where we love conversations like this about the best way to solve certain problems. https://chefcommunity.slack.com/archives/C1XB6U6MN

**Comment by unixengineer** [comment]
This @Schwad. This has indeed resolved my issue. Thanks for the followup. This can be closed.
