### ISSUE TITLE
Print remediation (tag?) when inspec control fails

### ISSUE THREAD

**Issue by unixengineer** [inspec/inspec#5223]
## Detailed Description
When an inspec control check fail, is there a possibility to print the remediation tag in the console (or report) output, so we can provide guidelines around how to fix that issue. If that exists already, please let me know the docs for it.

## Context
as above.

**Comment by Schwad** [comment]
Hello @unixengineer thanks for the issue!

Are you asking for a way to generally get the value supplied to `tag`? 

If so, the json reporter would definitely give you the tag values!

`inspec exec my_profile.rb --reporter=json`

Docs: https://docs.chef.io/inspec/reporters/#json

Quick note - for a quicker response to queries from a large community (1,700+!) feel free to post any InSpec questions to our community #inspec slack here! https://chefcommunity.slack.com/archives/C1XB6U6MN
