### ISSUE TITLE
command line returned by processes is truncated

### ISSUE THREAD

**Issue by rgeissert** [inspec/inspec#5226]
On some systems the output of ps may be truncated, which may prevent profiles from working as intended.

#1173 intended to fix that issue but it doesn't cover what is a common behaviour. From ps' manpage:

> When specified last, this column will extend to the edge of the display.  If
> ps can not determine display width, as when output is redirected (piped) into
> a file or another command, the output width is undefined (it may be 80,
> unlimited, determined by the TERM variable, and so on).  The COLUMNS
> environment variable or --cols option may be used to exactly determine the
> width in this case.  The w or -w option may be also be used to adjust width.

(ps from procps-ng)

# Describe the problem
Example of a test that should be listing some firefox processes in my machine:

> inspec> processes(/omni/).entries
> => []

By locally passing a COLUMNS env var set to 9999 the problem is noticeable (COLUMNS=9999 inspec shell):
> inspec> processes(/omni/).entries.size
> => 3

## Possible Solution
Call ps with ww, or with a very large COLUMNS parameter. E.g.
```ruby
command = "ps wwaxo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command"
```
Resulting in:

> inspec> processes(/omni/).entries[0].command
> => "/usr/lib/firefox-esr/firefox-esr -contentproc -childID 1 -isForBrowser -prefsLen 1 -prefMapSize 205372 -parentBuildID 20200720181548 -greomni /usr/lib/firefox-esr/omni.ja -appomni /usr/lib/firefox-esr/browser/omni.ja -appdir /usr/lib/firefox-esr/browser 559903 true tab"

**Comment by rgeissert** [comment]
FWIW SUSv4:2018 doesn't mention `w`, but it appears to be implemented on freebsd, openbsd, and possibly others. I haven't verified their default behaviour however.
It is definitely not implemented by the busybox I have at hand, so it looks like it could be used on all linux except for the busybox ps, and maybe extend it to other systems as needed.

**Comment by Schwad** [comment]
@rgeissert thank you for putting together this very well documented bug. 

I haven't been able to grab a process/setup locally that could meet that edge case but if you could recommend a candidate platform and process for reproduction I'm happy to reproduce this myself as well. (Just for testing reasons)

If anybody comes by this issue and is interested in having a crack at a PR I would recommend first finding a test case that reproduces this bug so we can capture it in our specs, and then the change is likely needed here:

https://github.com/inspec/inspec/blob/6f8b48ed263165a6d1cbcfeadcfc49404fdaf195/lib/inspec/resources/processes.rb#L126-L157

As recommended above on line 141. Luckily we already have the `if/else` handling for busybox :) 

Thanks again! 🙏

**Comment by rgeissert** [comment]
I can easily reproduce it locally on a Debian system when running inspec shell interactively:

```shell
$ bash -c 'exec -a "inspec $(echo A{0..100}) issue 5226" sleep 120' &
$ inspec shell
inspec> processes(/issue\ 5226/).entries.length
=> 0
$ #modify processes.rb
$ inspec shell
inspec> processes(/issue\ 5226/).entries.length
=> 1
```

With any of these TERMs: xterm, screen, screen.xterm-256color. I haven't tried with any other.

**Comment by Schwad** [comment]
@rgeissert thanks for circling back with the Debian reproduction - got it ✅
