### ISSUE TITLE
dobi.yml is needed to get docker images updating again

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5227]
# Describe the problem

InSpec has disabled `built_in:tag_docker_images` as it no longer exists in expeditor. We need to replace this functionality.

## Possible Solution

Expeditor now has `built_in:promote_docker_images` which we can use to accomplish this. However, it is not a drop-in replacement and needs a `dobi.yml` to describe how things need to be tagged.

When we get here, might need to conscript the guidance of @nkierpiec

**Comment by clintoncwolfe** [comment]
Docker image generation is working (though labeling is wonky). Closing.
