### ISSUE TITLE
Unable to get the validated report on remote execution 

### ISSUE THREAD

**Issue by esaravanakumar89** [inspec/inspec#5234]
<when I am executing inspec on remote machine, am getting the following error.>

# Describe the problem
Executing scan on remote using ssh executing all the controls and returning error while trying to generate a report.

D, [2020-08-31T18:10:44.714726 #4650] DEBUG -- : [SSH] username@servername<{:user_known_hosts_file=>"/dev/null", :port=>22, :compression=>false, :compression_level=>0, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :auth_methods=>["none", "publickey"], :keys_only=>true, :keys=>["ssh.key"], :password=>"<hidden>", :forward_agent=>nil, :non_interactive=>false, :verify_host_key=>false}> (cat /var/chef/cache/data_collector_metadata.json || echo -n)
Traceback (most recent call last):
        30: from /usr/local/bin/inspec:23:in `<main>'
        29: from /usr/local/bin/inspec:23:in `load'
        28: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/bin/inspec:12:in `<top (required)>'
        27: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        26: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        25: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        24: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        23: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/inspec/cli.rb:168:in `exec'
        22: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/inspec/runner.rb:104:in `run'
        21: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/inspec/runner.rb:132:in `run_tests'
        20: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/inspec/runner_rspec.rb:77:in `run'
        19: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/runner.rb:110:in `run_specs'
        18: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:76:in `report'
        17: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:166:in `finish'
        16: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:186:in `close_after'
        15: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:167:in `block in finish'
        14: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:194:in `stop'
        13: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:200:in `notify'
        12: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:200:in `each'
        11: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:201:in `block in notify'
        10: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/inspec/formatters/base.rb:72:in `stop'
         9: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/inspec/formatters/base.rb:190:in `platform'
         8: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/inspec-2.1.72/lib/resources/platform.rb:41:in `[]'
         7: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/train-1.5.0/lib/train/platforms/platform.rb:60:in `[]'
         6: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/train-1.5.0/lib/train/platforms/platform.rb:53:in `uuid'
         5: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/train-1.5.0/lib/train/platforms/detect/uuid.rb:21:in `find_or_create_uuid'
         4: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/train-1.5.0/lib/train/platforms/detect/helpers/os_common.rb:92:in `unix_uuid'
         3: from /usr/local/ruby_2.5.1/lib/ruby/gems/2.5.0/gems/train-1.5.0/lib/train/platforms/detect/helpers/os_common.rb:102:in `unix_uuid_from_chef'
         2: from /usr/local/ruby_2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
         1: from /usr/local/ruby_2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `new'
/usr/local/ruby_2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `initialize': no implicit conversion of nil into String (TypeError

Inspec version -2.1.72

Train - 1.5.0

Did anyone come across this

**Comment by clintoncwolfe** [comment]
InSpec 2 is not supported - please upgrade to a recent InSpec.
