### ISSUE TITLE
Add a kernel_parameters resource

### ISSUE THREAD

**Issue by tohch4** [inspec/inspec#5253]
## Detailed Description

As an Inspec user and developer, in order to know `kernel_parameters` to see an existing list of `kernel_parameter` resources without previous knowledge one or all of the parameters that might be configured on this target.

## Context

In a training course on Inspec, we reviewed source code to determine I cannot write a `describe` block within a `control` to filter for substring names (maybe all those that begin with `net.`), so partial string filtering on name and other properties. `kernel_parameter` implementation would be exhaustive, and this approach would make control development easier.

## Possible Implementation

Not at this time, but if I will prototype a possible solution and reference this issue in a PR, time permitting.

**Comment by Schwad** [comment]
Thanks for putting together this issue @tohch4 and giving us background. 

Looking forward to seeing prototypes and PRs depending on your bandwidth!
