### ISSUE TITLE
Error testing ec2-instance has no roles

### ISSUE THREAD

**Issue by heldersepu** [inspec/inspec#5258]
Just testing that an ec2-instance has no roles

# Describe the problem
Following the example in the documentation:  
https://docs.chef.io/inspec/resources/aws_ec2_instance/#test-that-an-ec2-instance-has-no-roles

```
control 'ec2_role' do
  title 'Ensure ec2 instance type and tags.'
  impact 1.0

  describe aws_ec2_instance('i-0b54e2b5498ce00ec') do
    it { should_not have_roles }
  end
end
```

It shows an error:
```
×  ec2_role: Ensure ec2 instance type and tags.
     ×  EC2 Instance i-0b54e2b5498ce00ec is expected not to have roles
     undefined method `empty?' for #<Aws::IAM::Role::Collection:0x000000000544ae30>
```

# Versions tested
- 4.22.1
- 4.23.4

**Comment by Schwad** [comment]
Hello @heldersepu ! 👋 

the aws_ec2_instance resource is maintained here: https://github.com/inspec/inspec-aws

If you cross post your issue over there they might be able to offer some insight 👍

**Comment by heldersepu** [comment]
Thank you @Schwad 
cross post: https://github.com/inspec/inspec-aws/issues/266

**Comment by heldersepu** [comment]
This is fixed using depend:
https://github.com/heldersepu/hs-scripts/commit/64149e7d9e1eebd81ac9f884433f3719a73cbebd
