### ISSUE TITLE
Docs for CLI are missing some CLI commands

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#5291]
See https://docs.chef.io/inspec/cli/

The `plugin` and `init` commands are not listed.
`habitat` and `compliance` are also not listed, but arguably those are additional integrations and would be documented elsewhere.
The page does list `nothing` which there's maybe no reason to document.

Aha! Link: https://chef.aha.io/features/SH-407

**Comment by clintoncwolfe** [comment]
Looks like it lists the commands from Thor, but does not load all Command plugins prior to doing so.
