### ISSUE TITLE
InSpec wrapper profile missing results for --reporter json

### ISSUE THREAD

**Issue by anthonygrees** [inspec/inspec#5294]
## Context
Customer has a wrapper profile that depends on 2 other profiles and call only "include_controls". They are using the json reporter (--reporter json). They use this JSON to post to Automate data-collector API directly later.
  
When they run `inspec exec` they can see that the controls for the sub-profiles were executed.
When they look at the resulting json file they can see 3 profiles in the profiles array, one for the wrapper and other 2 for children profile but the wrapper results are empty. `"results": []`
  
## Describe the problem
When you have an InSpec wrapper profile with a number of children profiles and execute it with `inspec exec wrapper --reporter json | jq` the results section of the wrapper payload is empty.
  
```json
{
          "id": "Child 1 - Big Rock Show",
          "title": null,
          "desc": null,
          "descriptions": [],
          "impact": 0.5,
          "refs": [],
          "tags": {},
          "code": "control 'Child 1 - Big Rock Show' do\n  describe input('amplifier_max_volume') do # This line reads the value of the input\n    it { should cmp 11 }\n  end\n\n  describe input('amplifier_max_volume_child_1') do # This line reads the value of the input\n    it { should cmp 110 }\n  end\n\n  describe input('amplifier_text') do # This line reads the value of the input\n    it { should cmp 'anthony' }\n  end\nend",
          "source_location": {
            "line": 3,
            "ref": "/Users/anthonyrees/src/inspec/inspec_wrapper_with_input/child/controls/example.rb"
          },
          "waiver_data": {},
          "results": []
        },
```
  
When using the `--reporter json` the results are wrong and if you `post` the JSON to Chef Automate via the API the GUI does not show the child reports from the run because the wrapper `results` in the JSON payload are empty.
  
However, if you use `inspec exec wrapper --config=reporter.json` the results of the wrapper appear fine in the Automate GUI. (Unfortunately this is NOT a workaround for the customer. )
  
Likewise, if you manually modify the JSON and add the `results` from the children to the wrapper results and then post the JSON to Chef Automate via the API the GUI shows the report correctly.
  
## How to recreate the issue
Here is an example I have created - https://github.com/anthonygrees/inspec_wrapper_with_input
  
## Impact
Customer impact. Ticket #26399
  
## Work-around
@mattray and I found that this works and is a viable work-around
```
inspec exec . --reporter=json-automate | jq
```
The `json-automate.rb` seems to format the wrapper JSON correctly where as `json.rb` does not.

Aha! Link: https://chef.aha.io/features/SH-454

**Comment by james-stocks** [comment]
@anthonygrees thanks a million for giving lots of detail and providing a reproduction profile!

This is how InSpec has aways reported JSON results with the `json` result reporter. It does look odd, but if we change it then we might break JSON consumption for other users.

If the data is for consumption by Chef Automate then the `json-automate` result reporter might be better. It does put the wrapped results directly into the wrapper profile.

**Comment by james-stocks** [comment]
A note on `json-automate` not being a documented feature:

The `json-automate` reporter is technically an internal feature. It's used by the `automate` reporter which _is_ documented [here](https://docs.chef.io/inspec/reporters/#automate-reporter) and it's also used by the audit cookbook (code [here](https://github.com/chef-cookbooks/audit/blob/cc9b5bd2c24027e16f5cab0c09dc2bc725cd8dd4/files/default/handler/audit_report.rb#L75)).

We could document it and add necessary acceptance tests to make it a supported feature, but it would probably be best to get a thumbs up from @kekaichinose  there

**Comment by aaronlippold** [comment]
hello, the results are - or should be - there - you just have to parse down the tree.

**Comment by clintoncwolfe** [comment]
The json-automate reporter is now publicly documented at https://docs.chef.io/inspec/reporters/#json-automate-reporter . I'm going to close this issue.
