### ISSUE TITLE
Pin Parallel gem to 1.19.2

### ISSUE THREAD

**Issue by Schwad** [inspec/inspec#5303]
As we still support ruby 2.4, we will need to pin `parallel` to 1.19.2 to continue this support as the latest release this week breaks (no ruby 2.4 support)

See: https://github.com/inspec/inspec/pull/5302

**Comment by nacc** [comment]
We (DigitalOcean) are also hitting this in our production environment.

**Comment by Schwad** [comment]
@nacc  - are you running Ruby 2.4?

**Comment by nacc** [comment]
@Schwad even older (2.3) sadly via embedded ruby from an eol chef client (folks are working on fixing that fundamental sadness).
