### ISSUE TITLE
SQL session resources should throw an error or warning if you try to execute a query but there is no valid session established

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#5309]
At the moment - if for some reason the sql session of the database resources do not make it clear that you are trying to query a nil sql session and it is cauing invalid results.

We should add some logic in the session and the query resources to protect aginst this case.

**Comment by Vasu1105** [comment]
@aaronlippold can we get more information is this related to mysql_session resource or mssql_session resource or both ?

**Comment by aaronlippold** [comment]
Generally all database session resources should have protections in place for this case. The warning should bubble up to the reporter level given that at the moment we are producing false passes and false fails because many of the database validation queries are based in negative logic, that a query Returns no results or is nil etc.￼￼
