### ISSUE TITLE
Dependency resolution for inheritance and resource packs

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#533]
wip... wip....

**Comment by donwlewis** [comment]
This feature is currently available now correct?  I am attempting to follow what I think is the proper configuration for this to work, and getting the following error message:

```
 ================================================================================
    Error executing action `execute` on resource 'audit_profile[sec-rhel7-0.1.0]'
    ================================================================================

    RuntimeError
    ------------
    Could not fetch inspec profile in {:cwd=>"./", :backend=>#<#<Class:0x00000005d1a8f8>:0x00000005d0abd8>, :name=>"cis-rhel7-level2", :compliance=>"cis/cis-rhel7-level2"}.
```

I am currently just using a simple profile that is using include_controls to include existing profile controls.

**Comment by jquick** [comment]
Closing this. Reopen with details if this is still an issue.
