### ISSUE TITLE
Docker containers are not getting uploaded

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#5359]
The Docker containers on dockerhub are not current: https://hub.docker.com/r/chef/inspec/tags?page=1&ordering=last_updated

We moved the pipeline over to the Dobi based workflow, but it looks like things are not working fully: https://github.com/inspec/inspec/pull/5318

**Comment by clintoncwolfe** [comment]
This has been fixed by #5362 . The images are still not getting tagged properly, but that is tracked by #5384 .
