### ISSUE TITLE
reporter (e.g. junit2) should skip resource packs without test execution

### ISSUE THREAD

**Issue by tbugfinder** [inspec/inspec#5373]
## Detailed Description

My inspec tests might depend on resource packs like inspec-aws, inspec-azure, inspec-* . Those resource packs themselves do not include any tests but provide resources for testing. Therefore it would be beneficial to not include those within the reporter output as those reports require post-processing.

## Context

I don't want to post-process the reporter output in order to skip the rather verbose output in regards to resource packs. By design those do not include or execute tests so it should be skipped within the reporting. If different reporters are used then my custom post-processing requires different techniques like json/xml mangling.

## Possible Implementation

a) Add a configuration option to `inspec.yml` if the tests execution of the resource pack should be included in reporter output.
b) Add a switch to `inspec ... reporter` execution to skip resource packs.

**Comment by clintoncwolfe** [comment]
The best place to implement this would be in lib/utils/run_data_filter . Check to see if a test run has zero controls in a profile (but at least one profile with controls) and if so, delete the empty profiles from the run_data. Control this with a command-line option.

Use `inspec init profile` to generate a set of test profiles under test/fixtures/profiles to test with, and add test cases in test/functional/inspec_exec_json_test.rb
