### ISSUE TITLE
Docker images are not getting tagged "stable" or "latest"

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#5384]
# Describe the problem
On promotion, the docker image on the Docker Hub should be tagged stable, but it is not. It is getting tagged with the major and minor version, however.

## Possible Solution

This may be fixed in `dobi.yaml`?

**Comment by Schwad** [comment]
Hey! 👋 

In the internal #releng-support or #expeditor-support; there should be a thread from 1-2 months ago where we discussed fixing DockerImage release.. 

We followed some of their guidelines and suggestions in there (i.e. moving to `dobi`) but there may be some other valuable notes from releng for anyone looking into this issue. :)

**Comment by nkierpiec** [comment]
@Schwad we think it may have something to do with a race condition between when the packages API knows about the newest version and Expeditor looking for that version as the "latest". We may change course on how we look for those packages to see if we can find a more reliable way to verify the version that was promoted is the "latest".

**Comment by clintoncwolfe** [comment]
Chef InSpec 4.25.1 was successfully tagged as final/stable during its promotion. So, the problem is intermittent, consistent with a race condition.

**Comment by Schwad** [comment]
@nkierpiec @clintoncwolfe - good to know! In the meantime if it does hit the race condition and doesn't tag latest; how painful is it to set your end manually? (ideally automated but you know what I mean!)

**Comment by clintoncwolfe** [comment]
This is working now.
