### ISSUE TITLE
Service resource fails on CentOS 8 due to upstream bug

### ISSUE THREAD

**Issue by bmhughes** [inspec/inspec#5398]
# Describe the problem
Any service tests on CentOS 8 will fail due to this upstream bug:

- https://bugzilla.redhat.com/show_bug.cgi?id=1901449
- https://bugzilla.redhat.com/show_bug.cgi?id=1908275
- https://bugzilla.redhat.com/show_bug.cgi?id=1853736

Which RH aren't being super fast on fixing for some reason.

## Possible Solution

Ansible has applied [this](https://github.com/ansible/ansible/pull/72337) workaround to get the loaded state from list-units which could be a usable solution in the meantime.

**Comment by clintoncwolfe** [comment]
I just tested this on centos8 with systemd 239-41 and inspec 4.26.10 and found that sshd service status was reported accurately. I'm reluctant to put in a workaround for a short-term bug when when it appears a fix is now available.

**Comment by bmhughes** [comment]
On which host platform? Docker being docker the host kernel is relevant too, I can still reproduce this on Fedora 33 and CentOS 8 stream with 5.10.12-200.fc33.x86_64 and 4.18.0-277.el8.x86_64 respectively. 

From the first bugzilla systemd-239-44.el8.x86_64 is possibly the fixed version for stream at least (not sure where vanilla 8 is now), so getting that into the dokken image may be an option.

**Comment by clintoncwolfe** [comment]
After discussion, we've concluded that this is an issue we need to wait for the vendor to fix. From InSpec's perspective, this fix will only be valid for a short time. That would be very difficult to test and not worth maintaining in the long term.

Respectfully, we have to decline this request, and urge CentOS 8 maintainers to release the fix into their package repo.
