### ISSUE TITLE
brew install command is invalid for brew 3.0.0

### ISSUE THREAD

**Issue by almmechanics** [inspec/inspec#5402]
The current install install instructions do not support the updated interface for brew on macos

# Describe the problem
The inspec `cask` is not identified correctly due to a revised interface for brew.

```bash
brew cask install chef/chef/inspec
Error: Unknown command: cask
```

## Possible Solution
Update `install.md` to use `brew install --cask chef/chef/inspec` as the correct install for macos

**Comment by clintoncwolfe** [comment]
Fixed in #5403
