### ISSUE TITLE
`inspec json` command does not populate the attribues/inputs for the profile

### ISSUE THREAD

**Issue by rbclark** [inspec/inspec#5412]
# Describe the problem

When running the `inspec json`, the list of available inputs to the profile is missing from the result. There is an `inputs` array however it is always empty.

An example can be found here https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/profile.json even though we have inputs declared in https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/inspec.yml

I tested this on `4.26.4` and this is still an issue as of that version.

## Possible Solution
It would be great if `inputs` were populated on `inspec json` runs just as `attributes` are properly populated on `inspec exec` runs.

**Comment by tohch4** [comment]
@rbclark and @aaronlippold, is this still the case? Is this a blocker for our current work?

**Comment by aaronlippold** [comment]
Yes and yes as far as I know

**Comment by aaronlippold** [comment]
bump any work on fixing this?

**Comment by Amndeep7** [comment]
Hi @Vasu1105.  This seems to be a simple thing that was missed in the transition from attributes to inputs.  Is this on your roadmap to be fixed?
