### ISSUE TITLE
Failed to load profile-Chef Inspec

### ISSUE THREAD

**Issue by jndirangu85** [inspec/inspec#5431]
Going through the Chef Inspec tutorial, I created a chef inspec .json file that had my resources information. While running the inspec exec aws-security -t aws://us-east-1/default command, I get the error message below: 

[2021-03-13T12:59:48-06:00] ERROR: Failed to load profile aws-security: Failed to load source for controls/instances.rb: 809: unexpected token at '��{'

Profile:         AWS InSpec Profile (aws-security)
Version:         0.1.0
Failure Message: Failed to load source for controls/instances.rb: 809: unexpected token at '��{'
Target:          aws://us-east-1

     No tests executed.

Profile: Amazon Web Services  Resource Pack (inspec-aws)
Version: 1.33.0
Target:  aws://us-east-1

     No tests executed.

Test Summary: 0 successful, 0 failures, 0 skipped

**Comment by clintoncwolfe** [comment]
It looks like you have some bad characters in your configuration .json file. Try checking it at https://jsonlint.com/ or similar.

**Comment by jndirangu85** [comment]
@clintoncwolfe I have validated the .json file and below the results show its a valid json file. I don't believe there is something wrong with the json file. 
![image](https://user-images.githubusercontent.com/40778234/111090438-b567c080-84fd-11eb-98a9-94efc823f1e8.png)

**Comment by clintoncwolfe** [comment]
Have you examined your profile file `controls/instances.rb` around line 809? Are there unexpected characters there?

**Comment by clintoncwolfe** [comment]
As there has been no response to this support request, I'm closing this issue.
