### ISSUE TITLE
undefined method `sockaddr_un' for Socket:Class (NoMethodError)

### ISSUE THREAD

**Issue by israelconesa** [inspec/inspec#5444]
### 🎛 Description

This is a 🐛 bug report.

I am trialling InSpec so totally new for me. I was hoping to verify a container following https://lollyrock.com/posts/inspec-for-docker/.
When I try `inspec exec` against the alpine or any other container I keep having the same issue as per title (stacktrace below).

I can use `inspec shell` without issues (for my limited usage).

### 🌍 InSpec and Platform Version

I'm using InSpec 4.29.3.
Windows 10 Pro. 
I installed Ruby for good measure as well ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]
Docker 3.2.2 (using Linux Containers)
Docker Engine 20.10.5

### 🤔 Replication Case

1. Run `docker run -it alpine /bin/sh`
2. Then `inspec exec https://github.com/dev-sec/linux-baseline -t docker://<container_id>`

### 💻 Stacktrace

`Traceback (most recent call last):
        32: from C:/opscode/inspec/bin/inspec:218:in '<main>'
        31: from C:/opscode/inspec/bin/inspec:218:in 'load'
        30: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.29.3/bin/inspec:11:in '<top (required)>'
        29: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.29.3/lib/inspec/base_cli.rb:35:in 'start'
        28: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in 'start'
        27: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in 'dispatch'
        26: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in 'invoke_command'
        25: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in 'run'
        24: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.29.3/lib/inspec/cli.rb:278:in 'exec'
        23: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.29.3/lib/inspec/cli.rb:278:in 'new'
        22: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.29.3/lib/inspec/runner.rb:78:in 'initialize'
        21: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.29.3/lib/inspec/runner.rb:86:in 'configure_transport'
        20: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.29.3/lib/inspec/backend.rb:38:in 'create'
        19: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.5.5/lib/train/transports/docker.rb:17:in 'connection'
        18: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.5.5/lib/train/transports/docker.rb:36:in 'create_new_connection'
        17: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.5.5/lib/train/transports/docker.rb:36:in 'new'
        16: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/train-3.5.5/lib/train/transports/docker.rb:56:in 'initialize'
        15: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.1.0/lib/docker/container.rb:336:in 'get'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.1.0/lib/docker/connection.rb:109:in 'block (2 levels) in <class:Connection>'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/docker-api-2.1.0/lib/docker/connection.rb:45:in 'request'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:283:in 'request'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/base.rb:22:in 'request_call'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/base.rb:22:in 'request_call'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/base.rb:22:in 'request_call'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/idempotent.rb:19:in 'request_call'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/instrumentor.rb:34:in 'request_call'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/mock.rb:57:in 'request_call'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/middlewares/redirect_follower.rb:15:in 'request_call'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:118:in 'request_call'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:469:in 'socket'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/connection.rb:469:in 'new'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/socket.rb:47:in 'initialize'
C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/excon-0.79.0/lib/excon/unix_socket.rb:12:in 'connect': undefined method 'sockaddr_un' for Socket:Class (NoMethodError)
Did you mean?  sockaddr_in`

**Comment by clintoncwolfe** [comment]
InSpec does not currently support Docker on Windows, but we are adding such support at this very moment. See https://github.com/inspec/train/issues/672

**Comment by israelconesa** [comment]
Thanks for your prompt reply @clintoncwolfe. I'm looking forward to this implementation :)
