### ISSUE TITLE
Filter Active Controls in Profile by Tag

### ISSUE THREAD

**Issue by tohch4** [inspec/inspec#5447]
## Detailed Description

Following up on inspec/inspec#5215, it would be particularly helpful for our use case not only to filter controls individual by their identifier, but groups of controls by tag. In short, enable similar functionality for `--control=foo`, but with `--tag=bar` and zero, one, or more controls with tag `bar` in its `tag` block(s) in that given profile will execute.

## Context

US federal agencies and detailed contractors must meet compliance objectives as defined by government compliance standards, particularly the NIST Risk Management Framework. Grouping one or more control(s) by `tag` block would be very useful and not require building logic outside of `inspec` to filter the tags "by hand." This will allow DevSecOps engineers to map security tests to high-level compliance objectives with less effort.

Example from MITRE:

https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/controls/V-71849.rb#L66

## Possible Implementation

TBD, I will draft a PR, but likely follow the same implementation strategy as the `--controls=foo` sub-command pattern.

**Comment by valancej** [comment]
Hi @tohch4! We're beginning to explore the possible solutions for filtering the controls being evaluated by tag as well, mostly for the same reasons you've described above. Of course, it would be preferable to not build tooling for the filtering logic outside of Inspec to accommodate this. Just curious if you've been able to make any progress on this PR (happy to possibly collaborate here) or you've found a workaround in the meantime. thanks!
