### ISSUE TITLE
error: timed out after 0 seconds

### ISSUE THREAD

**Issue by jasonwbarnett** [inspec/inspec#5454]
# Describe the problem

After upgrading to the latest  v4.31.0 we started to see errors, `timed out after 0 seconds`. We rolled back to v4.29.3 and the issue cleared up.

Example errors:

```text
     ×  is expected to exist
     Command `schtasks /query /v /fo csv /tn 'windows_disk_management' | ConvertFrom-Csv | Select @{N='URI';E={$_.TaskName}},@{N='State';E={$_.Status.ToString()}},'Logon Mode','Last Result','Task To Run','Run As User','Scheduled Task State' | ConvertTo-Json -Compress` timed out after 0 seconds
     ×  is expected to be enabled
     Command `schtasks /query /v /fo csv /tn 'windows_disk_management' | ConvertFrom-Csv | Select @{N='URI';E={$_.TaskName}},@{N='State';E={$_.Status.ToString()}},'Logon Mode','Last Result','Task To Run','Run As User','Scheduled Task State' | ConvertTo-Json -Compress` timed out after 0 seconds
```

## Possible Solution

No ideas

## Extra Information

Inspec v4.31.0

Running from within test-kitchen

**Comment by jasonwbarnett** [comment]
I think this bug may have been introduced in https://github.com/inspec/inspec/pull/5443

**Comment by clintoncwolfe** [comment]
What platform are you targeting? Is this via WinRM?

**Comment by jasonwbarnett** [comment]
> What platform are you targeting? Is this via WinRM?

- RHEL 7
- Windows 2012R2
- Windows 2016
- Windows 2019

Both WinRM and SSH

**Comment by clintoncwolfe** [comment]
OK, I'm able to reproduce under CentOS 8 under Test Kitchen. Working on a fix. Thanks for the report!
