### ISSUE TITLE
File resource `be_more_permissive_than` matcher raises and exception when file is not found

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#5484]
# Describe the problem
File resource `be_more_permissive_than` matcher causes an exception when file is not found.
Other matches such as `owned_by` and `grouped_into` returns a true `failed` status incase file is not found.

## Possible Solution

Please update the matcher to return a `failed` status or a skip_resource, rather than raising and exception.

**Comment by Vasu1105** [comment]
This looks to be duplicate of #4891

**Comment by Vasu1105** [comment]
@Nik08 could you please check is this the same that you fixed in #4891. If yes we can close this.

**Comment by Nik08** [comment]
@Vasu1105 Yes this is the same issue. This has been fixed as you mentioned in #4891

**Comment by Vasu1105** [comment]
Closing this as this fixed in #5519
