### ISSUE TITLE
Inspec resource/Properties to capture data from within a S3 object.

### ISSUE THREAD

**Issue by Aniket281292** [inspec/inspec#5495]
Inspec resource/Properties to capture data from within a S3 object.
## Detailed Description

I am aware of AWS Inspec resource "aws_s3_bucket" and "aws_s3_bucket_object" and their properties that can be used to validate the AWS resources.
I need to know if there is any feature that can help me access a value inside of an S3 object.
Specifically, if there is an S3 object which is a json file. I need to access metadata inside that json file. Is there a way to achieve this at the moment in Inspec by using combination of aws Inspec resource and another ruby method used to parse the data ?

## Context

I think the properties of an AWS Inspec resource specifically S3 bucket might be limited in way that we cannot actually access the metadata inside of an S3 object.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #494](https://github.com/inspec/inspec-aws/issues/494) via [**ZenHub**](https://www.zenhub.com/)
