### ISSUE TITLE
Unable to access multiple regions while running an inspec test on AWS S3 bucket

### ISSUE THREAD

**Issue by Aniket281292** [inspec/inspec#5503]
Unable to access multiple regions while running an inspec test on AWS S3 bucket inspec resource
# Describe the problem

I have written inspec tests to test a AWS S3 bucket using Inspec AWS resource "aws_S3_buckets". Now in S3, i have buckets from different region. However i am not able to access buckets from diff regions , the reason being i can only provide one region while executing the inspec tests.

inspec exec profile_name -t aws://us-east-1.

Error:
**S3 client configured for "us-east-1" but the bucket "abc" is in "eu-central-1"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts.**
How should i be able to utilize aws_S3_buckets resource to scan buckets from diff regions. like us-west-1 and us-east-1 ? Can i mention 2 different regions in inspec exec command, will that not be like working with 2 targets? is that supported  currently with Inspec?

**Comment by clintoncwolfe** [comment]
Please ask inspec-aws specific questions in the inspec-aws repo - I'll move this issue for you.

**Comment by clintoncwolfe** [comment]
Issue moved to [inspec/inspec-aws #345](https://github.com/inspec/inspec-aws/issues/345) via [**ZenHub**](https://www.zenhub.com/)
