### ISSUE TITLE
Allow Inspec to work with non-English language results

### ISSUE THREAD

**Issue by sean-horn** [inspec/inspec#5520]
## Detailed Description

**To Reproduce**

* Install non-US Windows Server 2019
* Enforce Audit policy via GPO
* Run Inspec / check auditpol results manually
* Check Inspec reporting which will result in nil values because the returned, valid, non-english data doesn't make sense to Inspec

## Context
* We install systems with our native language as the default and would like Inspec to handle the output from them when checking the system

**Comment by clintoncwolfe** [comment]
Can you give an example of an InSpec test that is failing?

**Comment by Vasu1105** [comment]
Writing profile in the non-English language does not reproduce this issue but yes if we run Profile written in English for audit_policy resource results in the nil value.
```
describe audit_policy do
  its('Directory service access') { should eq 'Success' }
end
```

```
  Audit Policy
     ×  Directory service access is expected to eq "Success"
     
     expected: "Success"
          got: nil
     
     (compared using ==)
```
vs
```
describe audit_policy do
  its('Verzeichnisdienstzugriff') { should eq 'Erfolg' }
end
```
```
  Audit Policy
     ✔  Verzeichnisdienstzugriff is expected to eq "Erfolg"
```

**Comment by clintoncwolfe** [comment]
After review, we have determined that this is an issue with the way Microsoft Windows handles reporting values from the audit policy tools. If the language is set to anything other than English, the query and response will both be in the new language. That means that the InSpec profile would need to have language lookup tables for all languages and all possible queries, which is not practical.  

At this time, we recommend either using English as the language, or translating the profile into your local language.
