### ISSUE TITLE
Replace use of soon-to-be deprecated WMIC command line utility with PowerShell WMI calls

### ISSUE THREAD

**Issue by jwdean** [inspec/inspec#5538]
Microsoft is deprecating the wmic command line utility used by InSpec's 'wmi' and 'security_identifier' resources. wmic is also used by mock_loader.

"The WMIC tool is deprecated in Windows 10, version 21H1 and the 21H1 semi-annual channel release of Windows Server. This tool is superseded by Windows PowerShell for WMI. Note: This deprecation only applies to the command-line management tool. WMI itself is not affected."
[https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features](https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features)

## Detailed Description
Replace all use of the wmic command line with PowerShell cmdlets that offer the same functionality. 

## Context
Users of InSpec on the Windows platform will continue to want to use the wmi and security_identifier resources reliably across all Windows releases. If this utility is removed from Windows the ability to audit settings using wmi and/or security_identifier resources will not be possible.

## Possible Implementation
The PowerShell cmdlets [https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/?view=powershell-5.1](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/?view=powershell-5.1). Get-CimInstance may map to the wmic command line pretty well. The query, classname and namespace parameters *might* be a direct map.

**Comment by tas50** [comment]
@jwdean Thanks for the heads up on this. I'll make sure we make the same update on the chef side.

**Comment by Vasu1105** [comment]
We have updated the security_identifier and the mock_loader for this change. wmi resource not require any changes to be done. So I am closing this issue as the required PR is merged.
