### ISSUE TITLE
Add resources for Mongo database support

### ISSUE THREAD

**Issue by lokeshk1987** [inspec/inspec#5540]
## Detailed Description
(i)Use the mongodb_session Chef InSpec audit resource to test json queries run against a Mongodb.

(ii)Use the mongodb_ conf Chef InSpec audit resource to test the contents of the configuration file for Mongodb, typically located at
/etc/mongod.conf
/etc/mongos.conf

## Context
Needed for CIS benchmark and customer needs.

**Comment by Vasu1105** [comment]
I am reopening this since mongodb_session resource is in review .
