### ISSUE TITLE
MSSQL Named Instances doesn't work with current code

### ISSUE THREAD

**Issue by da3210** [inspec/inspec#5548]
This issue is here for almost 2 years.
Named instances will not work without port. And MSSQL is capable of established that connection.

you can find the fix:
https://github.com/da3210/inspec/blob/dc/fixmssqlsession/lib/inspec/resources/mssql_session.rb

could you do a PR?

_Originally posted by @da3210 in https://github.com/inspec/inspec/issues/4319#issuecomment-852022224_

**Comment by Vasu1105** [comment]
@da3210 Thanks. Yes we currently has some work in our pipeline related MSSQL. We will check if we can add this into the same and open the PR.

**Comment by da3210** [comment]
@Vasu1105 Thank YOU. if you have any doubt regarding the 2 lines changes please contact me
