### ISSUE TITLE
KernelModule::disabled? regex fails to cover NixOS

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#5560]
The regex for `KernelModule::disabled?` fails to cover NixOS-style pathing to coreutils true/false.

# Describe the problem

On NixOS, absolute pathing, even for basic tooling, comes from the nix store. Because of this, the regex, which expects `/(s?)bin/(true|false)`, will never be able to match a properly disabled module on NixOS.

## Possible Solution

The regex would have to take the nix store pathing into account.

Currently that check is for the following: `^install\s+#{@module}\s+/(s?)bin/(true|false)`

It would have to be modified for something like this: `^install\s+#{@module}\s+(\/nix\/store\/[0123456789abcdfghijklmnpqrsvwxyz]{32}-\w+-[\d\.]+)?\/s?bin\/(true|false)`

Note that the nix store uses a very peculiar character set for its base32 sha256: https://github.com/NixOS/nix/blob/master/src/libutil/hash.cc#L83-L107

It's not clear to me if being extremely prescriptive is the right way to do this. Perhaps it's possible to add a nix store regex to absolute paths if NixOS is detected?

**Comment by clintoncwolfe** [comment]
Support for NixOS is not on our roadmap at this time. If the community wishes to open PRs with test cases, we might be able to accept some code, but otherwise I'm going to close this for now.
