### ISSUE TITLE
Query on Chef Inspec Documentation

### ISSUE THREAD

**Issue by brootware** [inspec/inspec#5565]
### 🎛 Description

This is a query on Chef Inspec Resource Documentation

I am currently looking at this inspec resource `security_policy` and the example described the policy name and what it should do.

```
describe security_policy do
  its('SeRemoteInteractiveLogonRight') { should eq '*S-1-5-32-544' }
end
```
May I know where i can find the list of policy names such as **SeRemoteInteractiveLogonRight** for this particular resource as I could not find it anywhere in the doc? Really appreciate any response.

**Comment by Vasu1105** [comment]
@brootware InSpec is using this resource to verify all the Security Policies. We won't list all of them in InSpec resource doc. You need to look into Microsoft Windows doc for this.

**Comment by Vasu1105** [comment]
@brootware Something like this https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-rights-assignment,
