### ISSUE TITLE
File resource with file_version matcher reports file_version incorrectly on windows

### ISSUE THREAD

**Issue by vinyar** [inspec/inspec#5571]
# Describe the problem
Inspec does not seem to pick up consecutive `.0.0` in the file version and strips the final number if it's 0. If the final digit is a number or a word, things work as expected.

Note - I do not have a file with consecutive 0's for product version, so I can't validate that it's working.

Expected behavior:
File version is reported accurately regardless of what's in the field.

Actual:
File version as seen in the image below is 3.37.0.0. 
File version is modified if there are consecutive zeroes. 

Example test:
```
describe file('C:\jims_binaries\POSFiles\FeatureManager.dll') do
  its('file_version') {should match(%r{'3.37.0.0'})}
  its('file_version') {should eq '3.37.0.0' }
  its('product_version') {should eq '3.37.0' }
end
```

Output:
```
  ×  file_version is expected to match /'3.37.0.0'/
     expected "3.37.0" to match /'3.37.0.0'/
     Diff:
     @@ -1,2 +1,2 @@
     -/'3.37.0.0'/
     +"3.37.0"

     ×  file_version is expected to eq "3.37.0.0"

     expected: "3.37.0.0"
          got: "3.37.0"

     (compared using ==)

     ✔  product_version is expected to eq "3.37.0"
```

Example of failing file:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/5116939/122596943-7dea4200-d01f-11eb-88cf-e06b366dc58d.png">

# versions
inspec --version         4.37.25
inspec --version        4.37.23

Nothing interesting in debug output. Looks like powershell output is no longer visible in debug.

## Possible Solution
I don't have a workaround.

**Comment by Vasu1105** [comment]
@vinyar could you please run this command in PowerShell on that system
```[System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\jims_binaries\POSFiles\FeatureManager.dll").FileVersion```
and check the output is it giving the same i.e `3.37.0.0`
I am trying to find out a similar version example file to reproduce this, but if you can give me the above information, that will be helpful.

**Comment by Vasu1105** [comment]
@vinyar I tried below and it worked for me.  Also as a piece of additional information, I did not found anything in the code which is striping out the additional 0.

```
describe file("C:\\Users\\Vasundhara\\Downloads\\postgresql-13.3-2-windows-x64.exe") do
  its("file_version") { should eq "1.0.0.0"}
  its('file_version') { should match(%r{1.0.0.0})}
  its('product_version') { should eq"13" }
end
```

output
```
Profile: InSpec Profile (opa_test)
Version: 0.1.0
Target:  winrm://vasundhara@http:/xxxx:5985/wsman:3389

 File C:\Users\Vasundhara\Downloads\postgresql-13.3-2-windows-x64.exe
     ✔  file_version is expected to eq "1.0.0.0"
     ✔  file_version is expected to match /1.0.0.0/
     ✔  product_version is expected to eq "13"

Test Summary: 3 successful, 0 failures, 0 skipped
```

<img width="1180" alt="Screenshot 2021-07-08 at 2 50 21 PM" src="https://user-images.githubusercontent.com/4181545/124897950-638efd00-dffc-11eb-8370-056bc0ba90ba.png">

**Comment by Vasu1105** [comment]
I am closing this for now. Feel free to reopen this if the issue exists.

**Comment by vinyar** [comment]
@Vasu1105  - Hi. Thanks for the suggestions. Didnt see these comments until now. I'll validate and reopen if necessary.
