### ISSUE TITLE
Add resources for IBM DB2 support

### ISSUE THREAD

**Issue by lokeshk1987** [inspec/inspec#5591]
## Detailed Description
(i)Use db2_session Chef InSpec audit resource to test json queries run against a IBM DB2.

(ii)Use db2_ conf Chef InSpec audit resource to test the contents of the configuration file for IBM DB2

## Context
Needed for CIS benchmark and customer needs.

**Comment by aaronlippold** [comment]
i would also suggest a base resource for 'mariadb' as well for shared data
between the other two resources.
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
