### ISSUE TITLE
Use text values for `severity`

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#562]
As proposed by @aaronlippold we use human-readable names for `impact`. At the moment a control impact is defined by as following:

```
  control 'my-test-1' do
    impact 1.0
    title '...'
  end
```

It would be nice to use words for it like:
- High, Medium, Low, Critical
- crit, high, med, low

We need to ensure:
- all human-readable numbers are mapped to a number
- the number scheme is well defined (e.g. CVSS score as we use it at the moment)

**Comment by trevor-vaughan** [comment]
I would like to note that having a numeric impact allows for calculation and this is a *good thing*.

The tag for severity should suffice.

**Comment by chris-rock** [comment]
We should use the CVSS 3.0 mapping in inspec https://www.first.org/cvss/specification-document

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1178413/43704538-30d0b722-9960-11e8-9b4c-9a4657bda7b4.png">

**Comment by trevor-vaughan** [comment]
Should there be general discussion around how to adjust the impact based on the environment?

Also, is it currently possible to adjust the impact programmatically?

For instance, I would like to be able to lower the impact of some items if `selinux` is enforcing and active on a daemon.

**Comment by chris-rock** [comment]
You can inherit a control and adapt its impact. The challenge with adjusting the impact per environment is that its reporting may be difficult, because right now we assume that the impact is static for a control.

If I understand you correctly, you essentially want to return a score based on your  findings. Is that correct?

**Comment by trevor-vaughan** [comment]
Yes, this is exactly what I want.

I also want to be able to adjust the score on individual items based on
inspection of the environment at run time to alleviate work on the system
maintainers.

Trevor
