### ISSUE TITLE
Distinguish plugin install errors from "already installed" cases

### ISSUE THREAD

**Issue by thheinen** [inspec/inspec#5624]
## Detailed Description

The InSpec source code states the following in `cli_command.rb`:
"Exit codes are 0 on success, 2 if the plugin is  already installed, and 1 if any other error occurs.

In practice, exit codes are `EXIT_PLUGIN_ERROR` (code 2) even if it's only a warning (`Plugin already installed at requested version`) as opposed to an actual error (`Plugin on Exclusion List - #{plugin_name} is listed as an incompatible gem - refusing to install.`).

I propose to change the exit code to 0, if it is only a warning like in
- [trying to install from path, when plugin is already present](https://github.com/inspec/inspec/blob/001a4d16db99ba29bee42147d7d472d058801dd1/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb#L238)
- [plugin is already at the requested version](https://github.com/inspec/inspec/blob/001a4d16db99ba29bee42147d7d472d058801dd1/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb#L394)
- [asking to upgrade, if there is no newer version](https://github.com/inspec/inspec/blob/001a4d16db99ba29bee42147d7d472d058801dd1/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb#L465)

## Context

A customer pipeline failed due to trying to reinstall a module in a specified version.

## Possible Implementation

Changing from `ui.red` to `ui.bold` and from `ui.exit Inspec::UI::EXIT_PLUGIN_ERROR` to `Inspec::UI::EXIT_NORMAL` in these three instances

**Comment by clintoncwolfe** [comment]
Fixed in #5625
