### ISSUE TITLE
Inspec 4.41 breaks tag processing

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#5631]
Processing of arrays in tags is broken as of 4.41

# Describe the problem

While testing on EL7, prior to using the inspec 4.41.2-1 RPM, [tags containing array items](https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/master/controls/V-71849.rb#L65) worked properly.

As of the 4.41.2 RPM, this syntax is now considered a syntax error.

**Comment by Nik08** [comment]
@trevor-vaughan Can you add error trace with this and some steps? I copy pasted the same control in different profile and was not able to replicate. 
And I ran profile with `--tags` options and also without it, so both ways.

**Comment by rx294** [comment]
@Nik08 Here is a stack trace of inspec check exception for a control containing tag arrays

```
root@9f3dd5c02f9e:/tmp/redhat-enterprise-linux-8-stig-baseline# inspec check .
/usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `instance_eval': (eval):1: syntax error, unexpected ']', expecting end-of-input (SyntaxError)
 'CCI-000366']
             ^
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `block in control_tags'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `map'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `control_tags'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:56:in `control'
	from ./controls/SV-230221.rb:1:in `load_with_context'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:170:in `instance_eval'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:170:in `load_with_context'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:154:in `load_control_file'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:221:in `block in collect_tests'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:216:in `each'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:216:in `collect_tests'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:661:in `load_checks_params'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:654:in `load_params'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:207:in `params'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:493:in `controls_count'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/profile.rb:463:in `check'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/cli.rb:111:in `check'
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/inspec-core-4.41.2/lib/inspec/base_cli.rb:35:in `start'
	from /usr/local/bundle/gems/inspec-bin-4.41.2/bin/inspec:11:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:23:in `load'
	from /usr/local/bundle/bin/inspec:23:in `<main>'
```

**Comment by rx294** [comment]
The update also seems to make generate exceptions when a tag contains punctuations/linefeeds etc...

**Comment by Nik08** [comment]
@rx294 Can you also elaborate on how tags with punctuations or linefeeds were being used? I have been able to replicate the array thing (thanks for that), but just need more information on what kind of tags were being used with **punctuations/linefeeds etc....**

I used some of the dummies tags like this for testing this scenario

  ```
tag severity: 'high'
  tag gtitle: '@@@SRG-OS-000480-GPOS-00227\n!!!'
  tag gid: 'V-230221'
  tag rid: 'SV-230221r627750_rule'
  tag stig_id: 'RHEL-08-010000'
  tag fix_id: '@F-32865r567410_fix'
  tag cci: ["CCI-000366"]
  tag legacy: []
  tag nist: ['CM-6 b']
tag nist: ["AU-9", "AU-9 (3)", "AC-3 (4)", "AC-6 (10)"]
```

**Comment by rx294** [comment]
the following 2 tags generate exceptions... these are the issues I have found so far.

```
  tag error1: "Line with a line-feed
  error"
  tag error2: "Line with a comma,error"
```

**Comment by rlakey** [comment]
Seeing the same issue and I do not see this on 4.38.

````
$ inspec check .
E, [2021-08-30T07:30:56.680944 #155] ERROR -- : Version needs to be in SemVer format
Traceback (most recent call last):
        25: from /usr/bin/inspec:252:in `<main>'
        24: from /usr/bin/inspec:252:in `load'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.41.2/bin/inspec:11:in `<top (required)>'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/base_cli.rb:35:in `start'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/cli.rb:111:in `check'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:463:in `check'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:493:in `controls_count'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:207:in `params'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:654:in `load_params'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:661:in `load_checks_params'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:216:in `collect_tests'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:216:in `each'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile.rb:221:in `block in collect_tests'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:154:in `load_control_file'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:170:in `load_with_context'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/profile_context.rb:170:in `instance_eval'
         5: from /mnt/c/Gitlab/vmware-photon-3.0-stig-inspec-baseline/controls/PHTN-30-000001.rb:3:in `load_with_context'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:56:in `control'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `control_tags'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `map'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `block in control_tags'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/control_eval_context.rb:67:in `instance_eval': (eval):1: syntax error, unexpected ']', expecting end-of-input (SyntaxError)
 'AC-2 (4)']
````

Tags look like this in the control

```
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-OS-000004-GPOS-00004'
  tag gid: nil
  tag rid: nil
  tag stig_id: 'PHTN-30-000001'
  tag fix_id: nil
  tag cci: 'CCI-000018'
  tag nist: ['AC-2 (4)']
```

**Comment by aaronlippold** [comment]
@Nik08 the NIST 800-53 tag formatting is an semi-established format like - not perfect but close 

A[aA]*#[#]*(/s|-|[a)*-#(#)*(a|/s)*(i|/s)*(a)* - This can be in a list / array of one or more items, etc

We are happy to hope on a zoom with you. I would love to get a chance to meet you.

The complexity here is given that the DOD, Federal Gov, CIS etc each have a bit of a style choice on things like:

IA-3(3)a vs IA-3(4) ii b vs AU-4 vs AU-3i, CM-6 etc - we actually have the full regex paterns in the orginal Heimdall Server v1 ruby code if you want the formal full set of supported regexes.

[CCI-##########]* is the other type of array of strings that needs to be supported

CIS CDC Controls has the pattern of [Aa]*-#[#]* in a list of strings

At some point the goal is the is to add regex pattern support to the tags - so we can say the tag has to be an array of this regex. e.g. an array of ip addresses, an array of NIST tags, a list of possible values, etc.

**Comment by aaronlippold** [comment]
This is a huge issue - given this breaks all of DODs / Fed inspec profiles

**Comment by Nik08** [comment]
@aaronlippold Yes this is getting complicated based on the logic that I have used to fetch tags, sure we can connect on this and would love to meet you too. Let's add @clintoncwolfe on this too.

**Comment by aaronlippold** [comment]
> @rx294 Can you also elaborate on how tags with punctuations or linefeeds were being used? I have been able to replicate the array thing (thanks for that), but just need more information on what kind of tags were being used with **punctuations/linefeeds etc....**
> 
> I used some of the dummies tags like this for testing this scenario
> 
> ```
> tag severity: 'high'
> tag gtitle: '@@@SRG-OS-000480-GPOS-00227\n!!!'
> tag gid: 'V-230221'
> tag rid: 'SV-230221r627750_rule'
> tag stig_id: 'RHEL-08-010000'
> tag fix_id: '@F-32865r567410_fix'
> tag cci: ["CCI-000366"]
> tag legacy: []
> tag nist: ['CM-6 b']
> tag nist: ["AU-9", "AU-9 (3)", "AC-3 (4)", "AC-6 (10)"]
> ```
also remember - you should produce a warning when a tag is listed more than once. Inspec does not merge the kv. 

it takes the last value so your above example woiuld just reset the nist tag to the last list used. The above code should produce a warning in the linter.

**Comment by aaronlippold** [comment]
@Nik08 well first and formost - we need to suport tags as an array of objects, hash, etc. aka the listed input supported object types right? 

@clintoncwolfe is of course always welcome :) 

I think we worked this out with the object and pattern support in inputs when @clintoncwolfe coded that. Could we borrow from that perhaps?

Ping me at my mitre email alippold@mitre.org and we can setup a zoom. Everyone on this chain is in my circle so I will add the group.

**Comment by aaronlippold** [comment]
@Nik08 also - you have a huge testing pool at https://saf.mitre.org/#validation
