### ISSUE TITLE
InSpec User and Group resources evaluate Windows Users and Group names case sensitively

### ISSUE THREAD

**Issue by jwdean** [inspec/inspec#5632]
Windows users and group names are case insensitive. 'bob_smith' and 'Bob_Smith' are the same user. 
The InSpec User and Group resource matchers fail if case does not match exactly. 

## Detailed Description
The following check will fail if 'AbC' is a member of Administrators, even though they are the same user but the user name only differs in case. 
```
describe group('Administrators') do
  ## User named AbC exists but this test fails
  its('members') { should_not include 'Abc' } 
end
```
The following check also fails because the Administrators group name differs in case. 
```
describe group('administrators') do
  ## This test fails because the group name is Administrators with a capitol A
  its('members') { should_not include 'Abc' }
end
```
It should be noted that Chef Infra Client's Group resource treat (at least) group and user names case insensitively such that this implementation is successful no matter the case of the user or group name. The user ABC is removed from Administrators.
```
  group 'Removing Abc from the Windows Administrators Group' do
    action                :modify
    append                true
    excluded_members      ['AbC']
    group_name            'administrators'
  end

```

## Context
Our brownfield systems include users that have been created and named manually, though with a common name. The manual creation of these users/groups has created a variety of username / case discrepancies. Being able to do case-insensitive comparisons would make this type of evaluation possible for us. 

## Possible Implementation
I guess there might be a way to implement this in the control rather than resource, however that exceeds my Ruby skills and acts against the desire for the code to be human readable.

Ideally the resource we be aware that it should do case insensitive matches on Windows operating systems.

**Comment by Nik08** [comment]
@jwdean Was this issue raised for case sensitivity in group names only? Or does the case sensitivity of member names also contributes to this problem? The examples that you have mentioned above only seems to be around group name `Administrators` & `administrators` case sensitivity. So just need a clarity around this.
Thanks!

**Comment by jwdean** [comment]
@Nik08 Sorry, no. Both the group names and the member names are case sensitive. In the group resource the group name as well as the members list comparisons are case sensitive. This is also true in the user resource where, the user name and groups list comparisons are case sensitive.

Here is perhaps a little better example. On this system the a group called ALLCAPS exists with a single user User1:

```ruby
describe group('ALLCAPS') do
  its('members') { should include 'USER1' }   ## This fails on Windows when 'User1' is a member
  its('members') { should include 'User1' } 
  its('members') { should include 'user1' }   ## This fails on Windows when 'User1' is a member
end

describe group('allcaps') do
  it { should exist }   ## This fails on Windows when the ALLCAPS group exists
end

describe user('User1') do
  it { should exist }
  its('groups') { should eq ['ALLCAPS'] }
  its('groups') { should eq ['allcaps'] }  ## This fails on Windows
end

describe user('user1') do
  it { should exist }   ## This also fails on Windows when 'User1' is the user name
end
```

**Comment by Nik08** [comment]
@jwdean We have been able to solution a [PR](https://github.com/inspec/inspec/pull/5667) for the cases you mentioned for group and user resources, except for the following example.

```
describe user('User1') do
  its('groups') { should eq ['ALLCAPS'] }
  its('groups') { should eq ['allcaps'] }  ## This fails on Windows
end

```
Here with the usage of `eq` it is difficult to implement case insensitivity. I would rather suggest to use `include` and if that is something that will work for you then we can work on making the check of include to be case insensitive. 
My suggestion :
```
describe user('User1') do
  it { should exist }
  its('groups') { should include 'ALLCAPS' }
  its('groups') { should include 'allcaps' }  
end

```
Let us know if this works for you.

**Comment by jwdean** [comment]
@Nik08 This is a definite improvement! 

As an alternative, would it be possible to use a regex with the `eq` comparison? Perhaps you already considered this, but I thought I'd mention it.

Yes, I can certainly use `include` for most of our use cases. Assuming `not include` is also case insensitive we could address the most common issues. I'd be happy to proceed with this approach.

Thank you.

**Comment by jwdean** [comment]
I should have said: assuming `should_not include` is also case insensitive.

**Comment by Nik08** [comment]
@jwdean Yes `should not include` will be also case insensitive. Thank you for your input :)
