### ISSUE TITLE
Remove Ubuntu 14.04 and 15.04 unit tests which are still there as we don't support them.

### ISSUE THREAD

**Issue by Vasu1105** [inspec/inspec#5644]
# Describe the problem

https://github.com/inspec/inspec/blob/main/test/helpers/mock_loader.rb#L21-L22
Many resources like below using this
https://github.com/inspec/inspec/blob/7415fc11d000dae1813a14ba12d957851fa999b3/test/unit/resources/group_test.rb#L8
https://github.com/inspec/inspec/blob/7415fc11d000dae1813a14ba12d957851fa999b3/test/unit/resources/nginx_conf_test.rb#L10
https://github.com/inspec/inspec/blob/7415fc11d000dae1813a14ba12d957851fa999b3/test/unit/resources/ip6tables_test.rb#L9
https://github.com/inspec/inspec/search?q=Ubuntu1504

**Comment by clintoncwolfe** [comment]
Is it possible to use a more modern version, like 20.04?
