### ISSUE TITLE
--controls does not support dependent profiles

### ISSUE THREAD

**Issue by ejaronne** [inspec/inspec#5647]
I tried the --controls and --tags features on dependent profiles, but they don't seem to work for me.

#5596 , @Nik08 
#5434 , @Vasu1105 

Thanks!

**Comment by aaronlippold** [comment]
Looks like we missed the unit tests for this with our dependant and wrapper profile in the test suite

**Comment by aaronlippold** [comment]
We ran accross this when we were debugging #5643

**Comment by clintoncwolfe** [comment]
Controls and tags are implemented differently - we're going to split this issue and work them separately.
