### ISSUE TITLE
mysql_session: add ability to specify session

### ISSUE THREAD

**Issue by grdnrio** [inspec/inspec#565]
I would like to be able to specify the socket to connect to in the MySQL_session resource.

``` ruby
describe mysql_session('username', 'password').query('QUERY') do
  its('output') { should eq('') }
end
```

**Comment by miah** [comment]
This should be supported, it may have been added after this issue was opened.

From the docs:
```
sql = mysql_session('my_user','password', nil, nil, '/var/lib/mysql-default/mysqld.sock')
```

If this is still a issue I'll re-open.
