### ISSUE TITLE
WinRM Connections don't allow validated SSL/TLS

### ISSUE THREAD

**Issue by ljkimmel** [inspec/inspec#5659]
WinRM connections should be able to connect to remote nodes using SSL and validate the hosts' certificates. By default the ca-trust-file is set to 'nil' in train-winrm/tansport.rb but it IS an accepted parameter. InSpec provides no command-line option to set this value for use in WinRM connections.

Furthermore, in order to connect to WinRM nodes with SSL at all one has to pass the '--self-signed' parameter. This is not intuitive since the problem is not that the certificates are self-signed it is that we are not allowed to tell InSpec how to trust them. There is another command-line parameter (--insecure) that would be much more relevant here. Regardless, users should be able to configure a CA trust location to make SSL/TLS connections be validated correctly.

**Comment by Nik08** [comment]
@ljkimmel For more clarity on this, can you please specify how you were intending to use it with inspec?

**Comment by Nik08** [comment]
@ljkimmel Can you please mention how were you trying to use this? What were the options that you were passing using inspec? Or options you intend to use in this scenario? 
This will create more clarity on the use case. Thanks!

**Comment by paullim29** [comment]
Great! I am also facing this issue.  Even though I have set up an internal ADCS PKI Certificate Authority, I still need to use the "--self-signed" parameter.  E.g.:

inspec exec test1 -t winrm://win2019-3.lab.int --user administrator --password 'secret' --ssl --self-signed
