### ISSUE TITLE
--controls flag should be supported in all inspec commands

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#568]
@arlimus / @chris-rock : Support for the new --controls flag seems to have been left out for the other inspec subcommands. 

My team is using the inspec json subcommand to parse out the elements of a profile for application integration and the ability to slice out specific controls would be very useful.

inspec json <profile> --controls="a b c" 
inspec supermarket <profile>  --controls=...
inspec compliance <profile> --controls=...
...

**Comment by arlimus** [comment]
:+1: , we can tackle it for json fairly quickly ;)
We'll need to collect a list of all the places where this is relevant, but can get started with something as specific as `json` right away.

**Comment by aaronlippold** [comment]
I would say that json, then compliance then supermarket would be the right order. Given that would be the way the product line would want to grow the support.

**Comment by arlimus** [comment]
let's use your list:
- [x] inspec json --controls a b c https://github.com/chef/inspec/pull/589
- [x] inspec supermarket exec --controls a b c
- [x] inspec compliance exec --controls a b c

**Comment by arlimus** [comment]
from cursory checking (@chris-rock is off right now) I can see controls support in both compliance and supermarket:

``` ruby
> inspec compliance help exec
Usage:
  inspec exec PROFILE
...
      [--controls=one two three]           # A list of controls to run. Ignore all other tests.
```

@aaronlippold please let me know if this isn't working, we should track it in a separate issue

**Comment by arlimus** [comment]
Covered all items. Please let us know if there is more to cover. If any of the existing methods have bugs, let's create new issues. Thank you @aaronlippold ! :+1:
