### ISSUE TITLE
New chef/inspec habitat packages are not being released to stable

### ISSUE THREAD

**Issue by collinmcneese** [inspec/inspec#5713]
# Describe the problem

Previously, when new InSpec versions were set to stable the related `chef/inspec` Habitat package would be promoted to the `stable` channel.  It looks like this process is not working currently as there are very different `stable` releases of the `chef/inspec` package:

- linux `chef/inspec/4.41.20/20211029211210`
- linux2 `chef/inspec/4.41.2/20210814000121`
- windows `chef/inspec/4.49.0/20211025233949`

**Comment by clintoncwolfe** [comment]
4.50.3 has successfully been promoted to stable.
