### ISSUE TITLE
tls1.2 and tls1.3 not recognized by ssl resource

### ISSUE THREAD

**Issue by jtonello** [inspec/inspec#5719]
When using the `ssl(port :443).protocols('tls1.1')` resource in a compliance profile, I get the correct result, but not with '`tls1.2`' or '`tls1.3`'.
# Describe the problem
**This control:**
```
control 'nginx-security' do
  impact 1.0
  title 'Nginx TLS security'
  desc 'Do not support TLSv1.1'
  describe ssl(port: 443).protocols('tls1.1') do
    it { should_not be_enabled }
  end
  describe ssl(port: 443).protocols('tls1.2') do
    it { should be_enabled }
  end
end
```

**Returns this result:**
```
Nginx TLS security
         + SSL/TLS on localhost:443 with protocol == "tls1.1" is expected not to be enabled
         - SSL/TLS on localhost:443 with protocol == "tls1.2" is expected to be enabled             <-- failure
            expected that `SSL/TLS on localhost:443 with protocol == "tls1.2"` is enabled
```
However, when running the same control profile using `inspec exec`, it reports correctly.

**Comment by Vasu1105** [comment]
@jtonello you have mentioned that when you are using `nspec exec` it reports correctly. So when the behavior is not correct?

**Comment by Vasu1105** [comment]
@jtonello for tls1.2 the resource is working without any issue. I have added support for tls1.3 in PR #5762 and also added code to raise the error if there is a `Connection error Errno::ECONNREFUSED` error which might help the user to understand why the resource is failed. I am closing this issue as there is already one issue for tls1.3 support.
