### ISSUE TITLE
Ability to evaluate environment variables on target within control

### ISSUE THREAD

**Issue by jakauppila** [inspec/inspec#5729]
## Detailed Description
It'd be great if you could evaluate environment variables on the target system when defining a control. If this is currently possible I haven't been able to find it in the documentation.

## Context
Attempting to verify permissions of the local administrators group on a server:
```
describe file('D:/app') do
  it { should be_directory }
  it { should be_allowed('full-control', by_user: "#{ENV['COMPUTERNAME']}/Administrators") }
end
```

As it stands today, that environment variable is evaluated on the machine running inspec, not the target, so it does not get the correct value I'm looking for.

**Comment by jakauppila** [comment]
As a workaround for this specific local administrators group example, I can just do the following:

```
describe file('D:/app') do
  it { should be_directory }
  it { should be_allowed('full-control', by_user: 'BUILTIN\Administrators') }
end
```

**Comment by clintoncwolfe** [comment]
Have you looked at the `os_env` resource? it is intended to fetch environment variable values on the target.

**Comment by Vasu1105** [comment]
@jakauppila I am closing this as we have an `os_env` resource that users can use to read and test the environment variables on the target. If still you have any issues with it feel free to reopen this issue. Thanks!!
