### ISSUE TITLE
mssql_session fails to parse fields containing newlines

### ISSUE THREAD

**Issue by trickyearlobe** [inspec/inspec#5730]
# Describe the problem
When a result set from `mssql_session` has fields that contain embedded newlines, we get an error
`Unquoted fields do not allow newline <"\n"> in line 3.[Truncated to 10000 characters]`

The underlying cause seems to be that `sqlcmd.exe` doesn't return real CSV output (with quotes around each field) which causes issues with the Ruby CSV parser when line/field delimiters are embedded in fields.

Although I haven't tested, it's very likely that embedded commas will also cause issues.

## Reproduction steps
Try this control on an MSSQL 2016 Standard Edition (SP2-CU15-GDR 13.0.5865.1) database
(Note: It works fine on MSSQL 2017 as there are no embedded newlines in the version field)

```
control 'example failure' do
  impact 0.7
  title 'example failure'
  desc <<~DESC
    Example failure
  DESC

  # Set whichever fields are required by your DB instance for the connection
  connection = {
    host: "127.0.0.1",
    port: "1433",
    instance: "my_db",
    user: "sa",
    password: "pigz_n_chickenz",
  }

  mssql = mssql_session(**connection)

  describe mssql.query('SELECT @@version as sql_ver').row(0).column('sql_ver').value do
     it { should match /2016/ }
  end
end
```

## Possible Solution
It might be possible to have `sqlcmd` supply XML formatted results instead of pseudo-CSV

**Comment by trickyearlobe** [comment]
## Sample problematic output from `SELECT @@version as sql_ver` :-
```
sql_ver\r\n-------\r\nMicrosoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64) \n\tOct 31 2020 02:43:57 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)\n\r\n
```
## Alternate repro

If you don't have the problematic version of MSSQL, you can test this issue by making a table containing fields with embedded newlines using the following SQL script.

```sql
DROP DATABASE inspec_example;
go

CREATE DATABASE inspec_example;
go

USE inspec_example;
go

CREATE TABLE problem (
    name varchar(255)
);
go

INSERT INTO problem VALUES ("This is"+CHAR(10)+"a multiline field");
go
```

## Inspec control for alternate repro (to be run on Windows)

```ruby
connection = {
  #host: "127.0.0.1",
  #port: "1433",
  db_name: "inspec_example",
  user: "sa",
  password: "my secret password",
}

control 'example failure' do
  impact 0.7
  title 'example failure'
  desc <<~DESC
    Example failure
  DESC

  describe mssql_session(**connection).query('SELECT * FROM problem').row(0).column("name").value do
    it { should match /multiline/ }
  end
end
```

**Comment by Nik08** [comment]
@trickyearlobe The multiline output was getting parsed properly for both linux and windows that I have tried. So I was not able to replicate this problem.

But I understand why CSV parser is failing. So, I got the above mentioned error `Unquoted fields do not allow newline <"\n">` when I tried CSV parsing of a sample string `name\r\n----\r\nThis is\na multiline field\r\n`. The `\n` before  "a multiline" makes it faulty while it should have been `\r\n`.

I tried your second way and the data I got was with proper delimiters `name\r\n----\r\nThis is\r\na multiline field\r\n` and hence it did not break for me.

Nevertheless, I have provided a fix based on my assumption and that for any such faulty output that older versions of sql might be generating in certain circumstances. 

And the test is working like this with the fix,

```
sql = mssql_session(db_name: "inspec_example", instance: "MSSQLSERVER16")
describe sql.query('SELECT * FROM problem').row(1).column("name").value do
  it { should match /multiline/ }
end

```
Using row(1) works here.

Let me know if this sounds good.
@clintoncwolfe You too!

**Comment by trickyearlobe** [comment]
I see you're simply converting the `\n` to `\r`, does that work on both Linux and Windows CSV parsers?

I don't have an environment set up right now, but I recall having the reverse problem on Linux while I was trying to simulate this (not allowing \r in unquoted fields, instead of not allowing \n).

**Comment by Nik08** [comment]
Yes this works on both Linux and Windows. I am using `row_sep: "\r"` for CSV parsing, which makes it consistent throughout any platform. And I suppose this should cover the reverse scenario as well.

I have tried these combinations of strings: ( for delimiters `\n`, `\r` and `\r\n` )

- `name\n----\nThis is\ra multiline field\n`
- `name\n----\nThis is\na multiline field\n`
- `name\r\n----\r\nThis is\na multiline field\r\n`
- `name\r\n----\r\nThis is\ra multiline field\r\n`
- `name\r----\rThis is\ra multiline field\r`
- `name\r----\rThis is\na multiline field\r`
