### ISSUE TITLE
The 'size_kb' property of the 'filesystem' resource does not return a conventional value

### ISSUE THREAD

**Issue by GeorgeDuckman** [inspec/inspec#5734]
Hello,

By doing a simple partition size test with the following code:

```ruby
describe filesystem('/dev/vg00/swap') do
  its('size_kb') { should cmp (1024 * 1024) } # Check if size is 1GB
end
```

The test fail : 

```shell
  FileSystem /dev/vg00/swap
     ×  size_kb is expected to cmp == 1048576

     expected: 1048576
          got: 3967580

     (compared using `cmp` matcher)


Test Summary: 0 successful, 1 failure, 0 skipped
```

The value of 'size_kb' here is 3967580, which in my opinion is a value you don't expect when we talk about the size of a 1GB partition in KB.

# Describe the problem

After a quick read of the code that handles this. ([inspec/lib/inspec/resources/filesystem.rb:98](https://github.com/inspec/inspec/blob/main/lib/inspec/resources/filesystem.rb))

We notice that the value of 'size_kb' is retrieved via the use of the 'df -PT' command. And after testing on my server these two values coincide:

```shell
Filesystem     Type     1024-blocks  Used Available Capacity Mounted on
devtmpfs       devtmpfs     3967580     0   3967580       0% /dev
```

Whereas using other commands to retrieve the partition size displays a more conventional value : 

**fdisk -l -u /dev/vg00/swap**
```shell
Disk /dev/vg00/swap: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

Divided by 1024 we get the value in KB : 1048576

**free**
```shell
              total        used        free      shared  buff/cache   available
Mem:        7970820     1326200     3088356      402364     3556264     5936932
Swap:       1048572           0     1048572
```

Not quite precise but pretty near the expected value.

**lvs --units k /dev/vg00/swap**
```shell
LV   VG   Attr       LSize       Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
swap vg00 -wi-ao---- 1048576.00k
```

Please note that I have tested on CentOS 6, CentOS 6, CentOS 8, RedHat 6, RedHat 7, RedHat 8 servers, the error is still present.

## Possible Solution

Use another command to retrieve the size of a partition or specify in the documentation that this value depends on the return of df and explain how we can set the correct value to test.

If this is how it's intended to work, please excuse me and close this incident.

Sincerely,
George.

**Comment by clintoncwolfe** [comment]
InSpec has to use portable solutions as much as possible, as we have support for a vast array of operating systems. When thinking about what command to use to determine the size of a filesystem, `df` is the one that is by far the most standard (as opposed to the specialized `lvs`) and applicable in all situations (as opposed to the swap-specific `free`).  We have to rely on accurate output from standard commands. We try to avoid documenting implementation details as it restricts our ability to try new solutions, and as you experienced, curious users can always read the source, as we are an open-source product.

It appears you have discovered a bug in either `df` or in your filesystem. One option would be to open a bug upstream with your OS or filesystem provider. Another option would be to implement a site-specific workaround by using an inspec `command` resource to execute either `free` or `lvs` and parsing the `stdout` property.

**Comment by GeorgeDuckman** [comment]
I understand, thank you for your answer.

I will close the issue.
