### ISSUE TITLE
Chef InSpec windows_firewall_rule not recognising displayname of rule but Name is unique per machine

### ISSUE THREAD

**Issue by dpower1985** [inspec/inspec#5738]
# Describe the problem

I'm trying to run a windows_firewall_rule InSpec test against multiple Windows servers, however whilst the Displayname of the rule is 'My Rule' on every machine I want to run it against, the 'Name' field is different on every single server and is in the format "{A9753595-752E-4F26-83EE-E4A7376601A1}". This means that the test does not function when run against multiple systems since the name is different every single time.

I can get the actual name of the rule on a machine with this Powershell command,

`    (Get-NetFirewallRule | Where-Object {($_.DisplayName -eq "My Rule") -and ($_.Direction -eq "Inbound")}).Name`

Using the Display Name that is common to all servers in the control just results in the test failing as the rule not existing. If I use the unique name from the above command then the test passes, but that requires the name to be hardcoded and the test to be changed every single time it is run.

Is it at all possible to run a Powershell script in a Chef InSpec control, store the output of that script in a variable and then use that variable in a test within the control?

This is my current test which fails due to using the Display Name rather than the name, so I'd like to substitite 'My Rule' for a variable.

```
    describe windows_firewall_rule('My Rule') do
        it { should exist }
        it { should be_enabled }
        it { should be_inbound }
        it { should be_tcp }
    end
```

## Possible Solution

Ideally I'd like to do something like this where I can run the Powershell command to get the unique name of the rule on the remote server and then use it in the test,

```
## Get the name of the Firewall rule (We cannot use Displayname during the test)
    script = <<-EOH
        (Get-NetFirewallRule | Where-Object {($_.DisplayName -eq "Opsview - Agent") -and ($_.Direction -eq "Inbound")}).Name
    EOH

    ##Windows Firewall Rule checks
    describe windows_firewall_rule(script.output) do
        it { should exist }
        it { should be_enabled }
        it { should be_inbound }
        it { should be_tcp }
        its('local_port') { should eq "5666" }
    end
```

**Comment by Vasu1105** [comment]
@dpower1985  you can use the `powershell` resource for script https://docs.chef.io/inspec/resources/powershell/.

**Comment by dpower1985** [comment]
> @dpower1985 you can use the `powershell` resource for script https://docs.chef.io/inspec/resources/powershell/.

I have seen that, but it seems to be more for just running a script and then comparing the output of it to an expected value. I can't see from that documentation how to get the output of the script and store it in a variable that I can then use elsewhere in the control.

**Comment by Vasu1105** [comment]
try using that as follows
`powershell(script).output`

**Comment by dpower1985** [comment]
> try using that as follows `powershell(script).output`

So I've tried doing that,


    script = <<-EOH
        (Get-NetFirewallRule | Where-Object {($_.DisplayName -eq "My Rule") -and ($_.Direction -eq "Inbound")}).Name
    EOH

    describe powershell(script) do
    end

    ##Windows Firewall Rule checks
    describe windows_firewall_rule(powershell(script).output) do
        it { should exist }
        it { should be_enabled }
        it { should be_inbound }
        it { should be_tcp }
        its('local_port') { should eq "5666" }
    end


But this results in an undefined method error,
`undefined method `output' for #<#<Class:0x000000000eb539f8>:0x000000000cd01c48>`

**Comment by dpower1985** [comment]
Managed to get it working. I just needed to use `.strip` instead of `.output` in my Rule check.
