### ISSUE TITLE
AWS SSM Backend

### ISSUE THREAD

**Issue by nick-doyle-slalom** [inspec/inspec#5743]
I'd love the ability to run Inspec against an EC2 Instance on which I had `ssm:SendCommand` or `ssm:StartSession`

## Detailed Description
Be able to specify --target=ssm://instance_id

## Context
Validate EC2 deployments from my local machine, or a cicd pipeline, when SSH is not available

**Comment by aaronlippold** [comment]
https://github.com/tecracer-chef/train-awsssm
