### ISSUE TITLE
Create architecture diagram for InSpec

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#5754]
## Detailed Description

Create an architecture diagram for at least `inspec exec`. A sequence diagram showing code flow between the major components of inspec would be a good start.

**Comment by clintoncwolfe** [comment]
[InSpec Process Architecture.pdf](https://github.com/inspec/inspec/files/7658936/InSpec.Process.Architecture.pdf)

**Comment by aaronlippold** [comment]
For some reason I can't seem to access this. Would you be able to reattach it
