### ISSUE TITLE
Unsupported resource/backend bash / vmkernel 

### ISSUE THREAD

**Issue by HerbBoy** [inspec/inspec#5766]
# Describe the problem
The issue occurs when any resource is used against a VMWare ESXi host.

**Unsupported resource/backend combination: bash / vmkernel. Exiting.**

here is what one of the control's is trying to do:

```
  describe bash('/usr/lib/vmware/openssh/bin/sshd -T|grep banner', path: '/bin/sh') do
    its('stdout') { should eq '/etc/issue' }
  end
```

I am not sure if this is a "bug" or expected to occur. If this is expected I would like to re-classify this as a feature request.

The question I ask is, what is the dependency of InSpec on the remote hosts to execute these commands? I use Ansible all the time to do specific tasks on an ESXi host without issue. I understand the two are not directly comparable but they are both agentless applications so if i know what is required for the InSpec control to work it could lead to a solution.

**Comment by Vasu1105** [comment]
@HerbBoy - Could you please post steps to reproduce this? Basically, the command that you are running and the error log if available?

**Comment by HerbBoy** [comment]
@Vasu1105 

The control ran by InSpec is:

  describe bash('/usr/lib/vmware/openssh/bin/sshd -T|grep banner', path: '/bin/sh') do
    its('stdout') { should eq '/etc/issue' }
  end

The error it throws to STDERR is: 

Unsupported resource/backend combination: bash / vmkernel. Exiting.


If there is an InSpec Log file you need I can retrieve it. 

Im just running this against an ESXi Host that has SSH enabled.

**Comment by Vasu1105** [comment]
@HerbBoy So are you using ssh transport to execute the InSpec profile on the VMWare ESXi host or you are using vmware transport for e.g.  `inspec exec inspec-vmware-example/ -t vmware://username@host --password 'xxxxx'`

**Comment by HerbBoy** [comment]
@Vasu1105  I was using the SSH transport... I assume this was a mistake on my part and should have used the vmware one?

**Comment by Vasu1105** [comment]
@HerbBoy - Yes for VMWare ESXi host you should use the vmware transport and use inspec-vmware resource pack which uses powercli. You can refer to this https://www.chef.io/blog/moving-forward-with-powercli-instead-of-inspec-vmware and https://github.com/chef-boneyard/inspec-vmware. InSpec core resources do not support this.

**Comment by HerbBoy** [comment]
@Vasu1105 I leverage https://github.com/chef-boneyard/inspec-vmware when possible but there are items that this library does not support that if standard SSH worked then I would be able to fully automate a DoD STIG compliance check.

Any ideas on how this can be done if what i am gathering here is that SSH transport cannot be leveraged against an ESXi Host - even though an ESXi host has the bourne shell and SSH capabilities.

**Comment by Vasu1105** [comment]
@HerbBoy could you please let me know if you run inspec shell command using ssh transport what is the output of platform.family?. Currently we don't have VMWare platform support for InSpec Core resources and it might take time if there is a possible solution to get core resources to work with it.

**Comment by HerbBoy** [comment]
@Vasu1105 I can provide this information tomorrow.

**Comment by HerbBoy** [comment]
@Vasu1105  Apologies for the delay in my response.

Here is a few screenshots:

![Screenshot from 2022-01-04 10-07-08](https://user-images.githubusercontent.com/61263592/148097037-60c3d040-c5a3-4658-84e2-804488a7f361.png)

and for reference if i go to this esxi and echo what my default shell is i get this:

![Screenshot from 2022-01-04 10-10-32](https://user-images.githubusercontent.com/61263592/148097135-7f9b1eb6-e106-4c68-8cec-8438642f9b7f.png)


Again, the reason i have brought this issue up is that when I use Ansible to lockdown the ESXi system I tell it what shell to leverage and it works without issue. So following that same logic I would think I could do the same with InSpec unless InSpec has a dependency requirement that is not being met. Ansible requires python be present on the remote/target host for most modules to work, what does InSpec require?

**Comment by Vasu1105** [comment]
@HerbBoy InSpec doesn't have any such dependency as far as I know. It is just that the platform value which is currently getting returned is not supported in InSpec core resource. So if you run the below command this must be returning you the value as `cloud ` / `esx` please confirm. I right now don't have the same environment to reproduce so if you tell me the value for platform family that will be good. From the shell screenshot that you have shared, I can see it is `esx` but if you can tell exact details that will help me further.
Command to verify : `platform.family` 

And as I mentioned it might take time if there is a possible solution to get core resources to work with it.

**Comment by Vasu1105** [comment]
Hi @HerbBoy I was able to reproduce this and my doubt is right, currently, bash resource does not support the esx platform and due to which you are getting that failure message. We can fix this by adding support for esx platform for bash resource. These are the good blogs that will clarify why we currently can support only bash resource 

https://www.v-front.de/2013/08/a-myth-busted-and-faq-esxi-is-not-based.html
https://blogs.vmware.com/vsphere/2013/06/its-a-unix-system-i-know-this.html

It is recommended to use PowerCLI or other tools to manage VMWare ESXi.

**Comment by HerbBoy** [comment]
@Vasu1105 

To your last statement regarding best practices I completely understand PowerCLI should be leveraged versus direct SSH connections however, for my use case, I am applying DoD STIG's to these systems and need to ensure that certain aspects are done that would otherwise be manual unless something like what I am requesting existed within InSpec.

Overall, thank you for providing the information and your support to resolve this issue.
