### ISSUE TITLE
Resources to support BIND

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#5779]
## Context

Needed for BIND DNS CIS profile

**Comment by lokeshk1987** [comment]
@clintoncwolfe  - These are the 2 resources needed for BIND DNS:

(1) Bind resource - to test the fields and validity of Bind DNS

With below properties:
- Bind version - to return the Bind DNS version
- Bind ServerId - to return the server id of Bind DNS

(2) Bind_conf resource
To test the configuration settings for Bind DNS (/etc/named.conf)
