### ISSUE TITLE
Chef Compliance Server - Users and Roles

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#578]
A user and I ran into an issue where I was able to add them to a team/organization but those changes are not flowing over to their user account. They cannot see profiles that have been uploaded or the changes in their team membership.

On the most current chef compliance.

**Comment by jquick** [comment]
This would be a compliance issue and not the InSpec compliance api plugin. Compliance is EOL at this time but is still getting some support. Please reach out to your account manager if your still having issues.
