### ISSUE TITLE
windows_task 'task_to_run' returning incorrect quoting

### ISSUE THREAD

**Issue by glaisne** [inspec/inspec#5786]
I'm getting the same results as https://github.com/inspec/inspec/issues/5236. Quotes go from 'command.exe -file "path to file"' to 'command.exe -file path to file""'

# Describe the problem
Command configured in task scheduler is below (exact copy):
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -file "C:\Program Files\Amazon\CloudWatch\windowsServiceMonitor.ps1"
```
inspec shell call on system returns incorrect quoting:
```
inspec> windows_task('ReportServicesToCloudWatch').task_to_run
=> "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -file C:\\Program Files\\Amazon\\CloudWatch\\windowsS
erviceMonitor.ps1\"\""
```
(notice no quote before the C:\\ and a double quote at the end of the line.)

Additional info:
pulling the task information with PowerShell reports the correct quoting:
```
PS C:\Users\Administrator> $task = get-scheduledtask ReportServicesToCloudWatch
PS C:\Users\Administrator> $task.CimInstanceProperties['actions'].value


Id               :
Arguments        : -file "C:\Program Files\Amazon\CloudWatch\windowsServiceMonitor.ps1"
Execute          : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
WorkingDirectory : C:\Program Files\Amazon\CloudWatch\
PSComputerName   :
```

Recipe action used to create the scheduled task:
```
###
Attribute:
default['attributes']['common']['variables']['workingpath'] = 'C:\Program Files\Amazon\CloudWatch'
###
taskName = 'ReportServicesToCloudWatch'
workingpath = "#{node['attributes']['common']['variables']['workingpath']}"
scriptFileName = 'windowsServiceMonitor.ps1'
...
windows_task "#{taskName}" do
  action :create
  command "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -file \"#{workingpath}\\#{scriptFileName}\""
  cwd "#{workingpath}\\"
  description "#{taskDescription}"

  execution_time_limit 1800
  force true
  frequency :minute
  frequency_modifier 5
  run_level :highest
end

```

```
PS C:\Users\Administrator> inspec version
4.18.85
updating the chef client (inspec version 4.52.9) on my kitchen system had no change in behavior.
```
## Possible Solution
Unknown.

**Comment by Vasu1105** [comment]
The powershell command `ConvertFrom-Csv` in this command `schtasks /query /v /fo csv /tn <TaskURL> | ConvertFrom-Csv`  itself is returning the incorrect quoting. Using two double quote around the file argument can be used as workaround,
 command  like this  `"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -file \""#{workingpath}\\#{scriptFileName}\"""` should work.  Also without giving quotes to the argument should work.

**Comment by Vasu1105** [comment]
Currently, there doesn't seem to be any way to have any alternative way to get all task details without using `schtask` command and as ConvertFrom-Csv itself has this issue and there is an alternative to set the arguments for now I feel we can close this issue. Feel free to open this issue if you still find it a breaking thing.
