### ISSUE TITLE
aws_rds_instances resource defined in documentation but errors with undefined method

### ISSUE THREAD

**Issue by cameronreyes** [inspec/inspec#5846]
# Describe the problem
Version of Inspec: 4.52.9
While documentation at [here](https://docs.chef.io/inspec/resources/aws_rds_instances/) describes a plural form of `aws_rds_instance`, it does not appear that a lib supporting `aws_rds_instances` is in [source.](https://github.com/inspec/inspec/tree/main/lib/resources/aws)

**Comment by clintoncwolfe** [comment]
Since 2018, all AWS resources have been in their own resource pack, meaning you need to depend on the profile and load them. Please see https://github.com/inspec/inspec-aws#use-the-resources-1
