### ISSUE TITLE
Multiple logins to compliance server

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#586]
The compliance server seems to have issues if you try to login multiple times. I ran into this when I was working with profiles and logged in via the web fronted and via the cli. This also caused challenges when I was working with automating the update of profiles on the server triggered by a git push.

Just a note and perhaps working though a set of workflows could be useful to make sure a seemly good idea - only be logged in once - is not really a blocker for possible common workflows.

**Comment by chris-rock** [comment]
@aaronlippold I use both at the same time, could you describe the errors in more detail?

**Comment by jerryaldrichiii** [comment]
This issue hasn't been updated in quite a while. Therefore, we are closing it to help us remain focused on active issues. We will be more than happy to reopen this issue if needed though, just reach out here.
