### ISSUE TITLE
Additional InSpec status codes

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#587]
InSpec controls can have three outcomes at the moment. This forces a number of _grey_ outcomes to be labeled either:
- Success
- Failure
- Skipped

Here's an example where the execution gave no useful information when the profile was skipped due to unsupported OS:

```
$ bin/inspec exec examples/profile --controls gordon-1.0


Finished in 0.00036 seconds (files took 0.50699 seconds to load)
0 examples, 0 failures

```

Would be great to have the ability to specify additional outcomes for situations like:

```
1. profile doesn't support OS/platform     
2. unsupported test/file due to e.g. commands (only_if)     
3. when the resource skips
3.1 file read permissions (priviledges)
3.2 file is missing, sth is missing, cmd, ...    
3.3 invalid contents, parsing erros  
4. attributes missing
```

**Comment by aaronlippold** [comment]
:+1:

**Comment by AnotherNerdHere** [comment]
The ones @alexpop suggested are good I would also like to add: 
skipped do to app not installed
skipped to due to profile inheritance
failed due to user permissions / privileges
failed - system unavailable. (for example host test,  mysql_session or something like that)

**Comment by jquick** [comment]
We have added specific exit codes for inspec 2.0 for most of the usual cases. We can open up a new issue if they are not covering your needs.

**Comment by jquick** [comment]
Inspec 2.0 added some baseline exit code options. We could enhance this to include others on this list.

**Comment by clintoncwolfe** [comment]
I don't think this is about exit codes, or at least not just about that.  It's about individual test outcomes being able to have more subtle results.

Based on that, I think this a duplicate, in slightly different ways, of:
 * #3174 - what to do when a resource cannot run
 * #3017, an RFC on finer-grained outcomes.

With that, I'm going to close this - please do add more thoughts on either ticket mentioned above.
