### ISSUE TITLE
Unable to run inspec without '--self-signed" option on Windows Server

### ISSUE THREAD

**Issue by paullim29** [inspec/inspec#5879]
Hi,

I'm running inspec from a Windows Server A to another Windows Server B.  I am using an internal ADCS Certificate Authority.  I am not using self-signed certificate.  The  WinRM (HTTPS) is working find and I am able to do the "Enter-PSSession" command:

Enter-PSSession -ComputerName win2019-b -UseSSL -Credential (Get-Credential)

The inspec command I am using from Server A is:
inspec exec test1 -t winrm://win2019-b.lab.int --user administrator --password 'secret' --ssl

However, it will have an error:

C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:103:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)

If I run it with the following command (adding the --self-signed parameter), it works:
inspec exec test1 -t winrm://win2019-b.lab.int --user administrator --password 'secret' --ssl --self-signed

Can someone advise how to set it up such that inspec will verify that the certificates are valid?

Thanks in advance.

**Comment by Nik08** [comment]
Hey! 
Why don't you try `inspec exec test1 -t winrm://win2019-b.lab.int --user administrator --password 'secret' ` just this without --ssl flag?
In my understanding, on using `--ssl` it looks for a certificate to validate this connection. And again using `--self-signed` ignores ssl certificate validation, hence it works. 
So if you already have user and password, just using that should work too.

**Comment by Nik08** [comment]
Hey!
We are aware about this problem. And the change coming in this [PR](https://github.com/inspec/train-winrm/pull/34) should be able to solve this.

Using `self-signed` avoids the ssl certificate validation and hence this works (In a non ssl way).

So to establish an SSL connection using certificates we are introducing options `client-cert`, `client-key` and `ca-trust-file` which will be useful for certificate ssl authentication for client and server depending on the usage.
Thanks!

**Comment by paullim29** [comment]
This is really great news!  Thank you so much.

**Comment by nemonik** [comment]
Has this been resolved because the latest inspec releasw still throws an error even with the `--self-signed` flag when connecting over winrm using a self-signed cert.

**Comment by Nik08** [comment]
Hey you might have to use new flags like,  `client-cert`, `client-key` and `ca-trust-file` which will be useful for certificate ssl authentication for client and server depending on the usage.
Just using `--self-signed` might not solve this issue for you.
