### ISSUE TITLE
`oracledb_session` need to handle zero rows or empty output for select query.

### ISSUE THREAD

**Issue by NAshwini** [inspec/inspec#5932]
# Describe the problem
Facing issue on Inspec version : 4.52.9 while using oracledb_session in case where select query as zero or empty output.
```
[2] pry(#<Inspec::Rule>)> oracledb_session.query("SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS WHERE PRIVILEGE='CREATE ANY LIBRARY' AND GRANTEE NOT IN (SELECT USERNAME FROM DBA_USERS WHERE ORACLE_MAINTAINED='Y') AND GRANTEE NOT IN (SELECT ROLE FROM DBA_ROLES WHERE ORACLE_MAINTAINED='Y')")
Inspec::Exceptions::ResourceFailed: Oracle query with errors: 

from /Users/anehate/.rvm/gems/ruby-3.0.0/gems/inspec-core-4.52.9/lib/inspec/resources/oracledb_session.rb:67:in `rescue in query'
Caused by NoMethodError: undefined method `sub' for nil:NilClass
from /Users/anehate/.rvm/gems/ruby-3.0.0/gems/inspec-core-4.52.9/lib/inspec/resources/oracledb_session.rb:119:in `parse_csv_result'
```
and this happens when inspec_cmd.stdout is empty as:
```
    65:       DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout))
    66:     rescue
    67:       raise Inspec::Exceptions::ResourceFailed, "Oracle query with errors: #{out}"
    68:     end
    69:   end
    70: end

[6] pry(#<#<Class:0x00007fb3edb9e710>>)> inspec_cmd.stdout
=> ""
[8] pry(#<#<Class:0x00007fb3edb9e710>>)> DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout))
NoMethodError: undefined method `sub' for nil:NilClass
from /Users/anehate/.rvm/gems/ruby-3.0.0/gems/inspec-core-4.52.9/lib/inspec/resources/oracledb_session.rb:119:in `parse_csv_result'
````
In older version of inspec the output for below controls was getting as empty now it's giving us the error.
control:
```
          describe oracledb_session.query("SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS WHERE PRIVILEGE='CREATE ANY LIBRARY' AND GRANTEE NOT IN (SELECT USERNAME FROM DBA_USERS WHERE ORACLE_MAINTAINED='Y') AND GRANTEE NOT IN (SELECT ROLE FROM DBA_ROLES WHERE ORACLE_MAINTAINED='Y')") do
            it { should be_empty }
          end
```
## Possible Solution

We need to handle empty string scenario here example something like this `DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout)) unless inspec_cmd.stdout.empty?`or more appropriate
the solution gives us an `nil` output we should get output as `empty` all previously developed controls would not affect.

**Comment by kbaghele** [comment]
Hi,
Any update on this?

**Comment by Nik08** [comment]
@kbaghele We will update you on this shortly.

**Comment by Nik08** [comment]
Thanks @kbaghele & @NAshwini for your help with the replication of this issue. I have raised the PR for this, once reviewed this should be good to go :)

**Comment by kbaghele** [comment]
I have checked  the inspec with the latest changes and it is giving the result as Nil (when there is an empty result.)

As @NAshwini  mentioned in possible solution We need to handle empty string scenario here example something like below 

DatabaseHelper::SQLQueryResult.new(inspec_cmd, parse_csv_result(inspec_cmd.stdout)) unless inspec_cmd.stdout.empty?or more appropriate
the solution gives us an nil output we should get output as empty all previously developed controls would not affect.

Please have a look @Nik08
