### ISSUE TITLE
Unable to run Inspec Shell for Alicloud

### ISSUE THREAD

**Issue by prensoni0143** [inspec/inspec#5939]
I have installed Alicloud plugins(Gems) already with Ruby, however unable to run Inspec Shell Alicloud

# Describe the problem
Following the article & installing via following commands, it says train-alicloud 1.0.0 already been installed.

$ gem install inspec => 198 gems installed

Clone "Inspec-Alicloud" Repo
$ cd GitHub/inspec-alicloud/

=> inspec-alicloud $ bundle install
Using m 1.6.0
Using mocha 1.13.0
**Using train-alicloud 1.0.0**
Bundle complete! 13 Gemfile dependencies, 220 gems now installed.
Bundled gems are installed into `./vendor/bundle`

Then added AliCloud AKs,
ALICLOUD_ACCESS_KEY, ALICLOUD_SECRET_KEY and ALICLOUD_REGION

$ bundle exec inspec plugin install train-alicloud
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
**train-alicloud plugin, version , installed from rubygems.org**

$ bundle exec inspec detect -t alicloud://
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0

Name:      alicloud
Families:  cloud, api
**Release:   train-alicloud: v1.0.0, aliyunsdkcore: v0.0.17**

$ inspec detect -t alicloud://
[2022-03-22T20:17:18+08:00] ERROR: Unable to resolve dependency: user requested **'train-alicloud (> 0)'**
[2022-03-22T20:17:18+08:00] ERROR: Run again with --debug for a stacktrace.

$:inspec-alicloud $ inspec detect -t alicloud:// --debug
[2022-03-22T20:17:40+08:00] ERROR: Unable to resolve dependency: **user requested 'train-alicloud (> 0)'**
[2022-03-22T20:17:40+08:00] ERROR: Inspec::Plugin::V2::LoadError
[2022-03-22T20:17:40+08:00] ERROR: /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/plugin/v2/loader.rb:196:in `rescue in activate_managed_gems_for_plugin'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/plugin/v2/loader.rb:191:in `activate_managed_gems_for_plugin'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/plugin/v2/loader.rb:290:in `fixup_train_plugin_status'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/plugin/v2/loader.rb:40:in `block in initialize'
/opt/inspec/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/opt/inspec/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `each'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/plugin/v2/loader.rb:39:in `initialize'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/cli.rb:482:in `new'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/cli.rb:482:in `<top (required)>'
/opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.52.9/bin/inspec:10:in `<top (required)>'
/usr/local/bin/inspec:288:in `load'
/usr/local/bin/inspec:288:in `<main>'

**Comment by clintoncwolfe** [comment]
As you installed (some of) your gems using bundle, you will need to use bundle to run your commands.

Prefix all commands with "bundle exec".

**Comment by prensoni0143** [comment]
Hi,
I have got to know that the issue isn't about this. I already tried and it didn't work.
Your Inspec-Alicloud is not designed to work on Mac so far, that's what i heard.

**Comment by clintoncwolfe** [comment]
inspec-alicloud was developed on MacOS. It definitely works there. 

Gem installs of InSpec are notoriously brittle. It should only be attempted by experts. We recommend that you install from the OS package from download.chef.io, then run inspec plugin install train-alicloud, and avoid the bundle install entirely.

**Comment by prensoni0143** [comment]
I have cleaned up my system, uninstalled all Ruby, chefworkstation, etc.
I have terraform installed version Terraform v1.0.11
Are you asking me to start with: https://mitre-inspec-developer.netlify.app/installation/macinstall.html ?
I started with: $ curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
what's next do you suggest to install? 

$ inspec plugin install train-alicloud
[2022-04-03T11:22:35+08:00] ERROR: Unable to resolve dependency: user requested 'train-alicloud (> 0)'
[2022-04-03T11:22:35+08:00] ERROR: Run again with --debug for a stacktrace.

**Comment by clintoncwolfe** [comment]
OK, I used the curl | bash approach, and installed 5.10.5 from DMG. 
```
installer: The upgrade was successful.
"disk2" ejected.
[cwolfe@lodi ~]$ /opt/inspec/bin/inspec --version
5.10.5
[cwolfe@lodi ~]$ /opt/inspec/bin/inspec plugin install train-alicloud
Fetching aliyunsdkcore-0.0.17.gem
Fetching nokogiri-1.13.3-x86_64-darwin.gem
Fetching netrc-0.11.0.gem
Fetching mime-types-data-3.2022.0105.gem
Fetching mime-types-3.4.1.gem
Fetching http-accept-1.7.0.gem
Fetching rest-client-2.1.0.gem
Fetching aliyun-sdk-0.8.0.gem
Building native extensions. This could take a while...
Fetching train-alicloud-1.0.0.gem
train-alicloud plugin, version 1.0.0, installed from rubygems.org
```
Two tips:
1. If you encounter problems, you may want to delete your ~/.inspec/gems directory and your ~/.inspec/plugins.json file. This will cause a reset of your plugin configuration.
2. The AliCloud SDK requires compilers. You may need to install XCode and its command line tools. Do this if the "Building native extensions..." step fails.

**Comment by prensoni0143** [comment]
Thanks. It seems worked, here's what I am getting now.

`$ inspec detect -t alicloud://
Ignoring aliyun-sdk-0.8.0 because its extensions are not built. Try: gem pristine aliyun-sdk --version 0.8.0

 ────────────────────────────── Platform Details ────────────────────────────── 

Name:      alicloud
Families:  cloud, api
Release:   train-alicloud: v1.0.0, aliyunsdkcore: v0.0.17`

**Comment by prensoni0143** [comment]
Thanks. It seems working, here's what I am getting now.

**$ inspec detect -t alicloud://**
Ignoring aliyun-sdk-0.8.0 because its extensions are not built. Try: gem pristine aliyun-sdk --version 0.8.0

-─ Platform Details -----
Name:      alicloud
Families:  cloud, api
**Release:   train-alicloud: v1.0.0, aliyunsdkcore: v0.0.17**

**$ gem pristine aliyun-sdk --version 0.8.0**
/Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
Traceback (most recent call last):
	14: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/bin/gem:21:in `<main>'
	13: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/gem_runner.rb:44:in `run'
	12: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/gem_runner.rb:79:in `do_configuration'
	11: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/gem_runner.rb:79:in `new'
	10: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/config_file.rb:182:in `initialize'
	 9: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/config_file.rb:332:in `load_file'
	 8: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems.rb:710:in `load_yaml'
	 7: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'
	 4: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/psych.rb:13:in `<top (required)>'
	 1: from /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': _**dlopen(/Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin21/psych.bundle, 0x0009): Library not loaded: /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (LoadError)
  Referenced from: /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin21/psych.bundle
  Reason: tried: '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' (no such file), '/usr/local/lib/libyaml-0.2.dylib' (no such file), '/usr/lib/libyaml-0.2.dylib' (no such file) - /Users/xxxxxx/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin21/psych.bundle**_

**Comment by clintoncwolfe** [comment]
gem pristine *anything* will never work - inspec uses a private gem installation under ~/.inspec/gems. 

The first error message indicates that extension building failed for aliyun-sdk. You need the error message from plugin install command, which must not have worked. Isuggest you delete your ~/.inspec/gems and ~/.inspec/plugins.json and try `inspec plugin install train-alicloud` again, and paste the error message you got here.

**Comment by clintoncwolfe** [comment]
I also suggest that you use the full path to the installation of inspec, so you guarentee that you are using the fully installed version - run `/opt/inspec/bin/inspec` rather than just inspec
