### ISSUE TITLE
Make profile/example more self-explanatory

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#596]
As highlighted in https://discourse.chef.io/t/inspec-profile-library-classes/8044 the example is not perfect and may open some questions:
- Can I use any ruby code here
- Can I use chef dsl here (regular chef not InSpec)
- Can I put multiple classes in the same file or e.g. gordon_config1, something_else2,etc
- How do I return data to the test case say for example a simple string.
- Who the heck is Gordon? I see his name all over the place.

**Comment by clintoncwolfe** [comment]
Refs #3351
