### ISSUE TITLE
auditd_rules resource does not seem to be working correctly

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#598]
It looks like auditd_rules resource is not working correctly. I don't have any rules but running the following inspec resource, the rule passes. It should have failed.
 describe auditd_rules do
  its('lines') {
    should contain_match(/^exit,always arch=.\* key=time-change syscall=adjtimex,settimeofday/)  }

**Comment by chris-rock** [comment]
Can you do the following on the machine you are inspecting:

```
$ inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

inspec> auditd_conf.lines
=> nil
inspec> 
```

I would like to verify what the output of `lines` is

**Comment by kdshah1** [comment]
inspec> auditd_rules.lines
=> ["No rules"]
inspec> auditd_conf.lines
=> nil
inspec>

**Comment by jerryaldrichiii** [comment]
@kdshah1 I am unable to reproduce this issue; `auditd_conf.lines` shows `[]` and the test you gave fails as expected.

I suspect it has been resolved since this issue was created. Due to this issues age, I'm going to close it.

Please reopen if this is still an issue!

**Comment by jerryaldrichiii** [comment]
Closed accidentally, confirmed this is still an issue. Apologies.

**Comment by miah** [comment]
There are other auditd resource issues here: #2025, #2334, #710

**Comment by kekaichinose** [comment]
@kdshah1 Apologies on the (massively) late follow-up here, but as this issue is fairly stale at this point, can you please see if this is still an issue in the current version of InSpec, and if it is, and repro steps and other details so we can look at this in context?

Thanks!
__Chef InSpec Team__
