### ISSUE TITLE
service resource should better support servicectl scripts in nonstandard locations

### ISSUE THREAD

**Issue by elijah** [inspec/inspec#600]
Today I was trying to use the inspec service resource to test status of services bundled by an enterprise software vendor's software.

I tried using sysv_service('myservice', '/opt/vendor/etc/init.d/myservicescript') as suggested by the docs and a read of the source - this didn't work out, and I'm not completely sure why... but I did find some things in a read-through of the code that I think are ripe for improvement.

1) for installed services -- inspec is hardcoded to only look in /etc/init.d -- https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L349

2) for enabled_services_cmd -- this only looks in /etc/rc.D. -- https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L361

3) Because of the preceding two conditions, the note at https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L373 indicates that my service definition will 'fail' - https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L376 - even though my service_ctl and service_name variables, when substituted, would result in an invocation that would return accurate state as true/successful.   

And yeah, it fails.  :)

 Suggested resolution path:
- Maybe the service resource could support something like a service_root command - pointing the service searches for 'installed' and 'enable' and 'status' to paths under a chroot-like path.
- Having 'running' fail because the links in rc.D don't exist, and because the file isn't present in /etc/init.d, seems counterproductive to me.  Ideally I'd be able to test any service block that I can define in a chef recipe - where I set the init_command and could successfully instantiate a service block (with action :nothing ... because $VENDOR's installer already has copious scripting to make sure that things are in a good state).
- I'm doing this work on CentOS 7.0 - I don't _think_ I'm accidentally tripping across systemd integration issues, but I'm aware that running legacy-style SysV init scripts is definitely suboptimal.

In an ideal world I might rewrite a copy of the bundled service scripts into /etc/init.d - or symlink them - or convert the whole mess to systemd and go on.  But I'm not there yet, with this vendor - and I wanted to take the opportunity to point out the potential improvement to InSpec, which has an approach that I very much like.

**Comment by chris-rock** [comment]
@elijah Thanks for reporting. I agree the run-level support is not perfect yet and this needs to be improved. Could you share or add a test that makes it really easy to reproduce this behavior on our side?

**Comment by kekaichinose** [comment]
@elijah this issue has aged considerably and we apologize that we have not been able to address this in a timely manner. With that said, per @chris-rock's comment, could you share or add a test that makes it really easy to reproduce this behavior on our side?

Once you do, please open a new ticket with repro steps that apply to the current version of InSpec.

Thanks!
__Chef InSpec Team__
