### ISSUE TITLE
Windows: registry_value resource and type matcher? 

### ISSUE THREAD

**Issue by stuartpreston** [inspec/inspec#605]
I'd like to do something like this:

```
describe registry_value('Task Scheduler','HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Schedule\Start') do
  its(:registry_type) { should eq :dword }
end
```

or keeping with registry_key (???)

```
describe registry_key('Task Scheduler','HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Schedule') do
  its('Start') { should be_registry_type :dword }
end
```

We had similar capability in ServerSpec (test by 'name', 'data' and 'type' but would be good to have an InSpec equivalent...)

**Comment by chris-rock** [comment]
Hi Stuart,

have you seen the examples located in https://github.com/chef/inspec/blob/master/test/integration/default/registry_key_spec.rb:

```
describe registry_key('HKLM\System\Test') do
    it { should exist }
    it { should have_value('test') }
    it { should have_property('binary value', :binary) }
    it { should have_property('Binary value', :binary) }
    it { should have_property('string value') }
    it { should have_property('String value') }
    it { should have_property('dword value', :dword) }
    it { should have_property_value('multistring value', :multi_string, ['test', 'multi','string','data']) }
    it { should have_property_value('Multistring Value', :multi_string, ['test', 'multi','string','data']) }
    it { should have_property_value('qword value', :qword, 0) }
    it { should have_property_value('Qword value', :qword, 0) }
    it { should have_property_value('binary value', :binary, 'dfa0f066') }
    it { should have_property_value('Binary value', :binary, 'dfa0f066') }
  end
```

Does it cover your needs? Is that not compatible with Serverspec? Let me know if something is missing

**Comment by stuartpreston** [comment]
Thank you! (I had not thoroughly looked through the integration tests - doh!)  Can we have the docs updated? -they only reference the Name matcher).  

There's still some disjointed terminology...  Registry keys have registry **values** that are objects that hold **data** of a specific **type**.  The term **value** has been overloaded a lot here (and in ServerSpec).  Would be good to get this sorted out as it can be confusing...

**Comment by chris-rock** [comment]
@stuartpreston At this point, we mainly established compatibility with Serverspec. Could you share your view on how that should look like? (e.g. via examples)

**Comment by stuartpreston** [comment]
Understood. I was imagining something like this, so not a million miles away what you have:

```
describe registry_key('HKLM\System\Test') do
    it { should exist }
    it { should have_default_value('test') }
    it { should have_value('binary value', :binary) }
    it { should have_value('Binary value', :binary) }
    it { should have_value('string value') }
    it { should have_value('String value') }
    it { should have_value('dword value', :dword) }
    it { should have_value('multistring value', :multi_sz, ['test', 'multi','string','data']) }
    it { should have_value('Multistring Value', :multi_sz, ['test', 'multi','string','data']) }
    it { should have_value('qword value', :qword, 0) }
    it { should have_value('Qword value', :qword, 0) }
    it { should have_value('binary value', :binary, 'dfa0f066') }
    it { should have_value('Binary value', :binary, 'dfa0f066') }
end
```

`have_value` would need 3 overloads though, one to test the **value** exists, one to test the **value** exists of the required **type**, and one to test the **value** exists of the required type and matching the specified **data**.  There's no such thing as a "property" in registry terminology really...

The reason for the `have_default_value` is to differentiate it from the `have_value` because you can have a value with the name 'test' that is different to the data in the default value for the key... (see screenshot below).

![test](https://cloud.githubusercontent.com/assets/6384654/14252487/80e5ad30-fa7f-11e5-8efd-64f0713aada7.PNG)

Finally I would make the labels match the Windows type names (e.g. :multi_sz instead of :multi_string).  Hope this makes sense!

**Comment by chris-rock** [comment]
@stuartpreston I am not sure about adding more RSpec matchers. I would like to find a more direct access. I need to think further about it...
