### ISSUE TITLE
requried_gems seems to fail when a `version` is not provided

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#6053]
When using the new required gems capability in the `inspec.yml`, the `version` property seems to be expected.

I would have expected if a version was not given, that the lastest version would be installed.

If we are going to require both, then we should document clearly that both are _required_ for things to work and this should be added to the `inspec check` capability.

**Comment by aaronlippold** [comment]
Also, add a `-y` flag to always say to the install if you could as well.

**Comment by Vasu1105** [comment]
User can use --auto-install-gems option it's behaves the same as --y flag here.
