### ISSUE TITLE
inspec creates .lock, breaking "profile structure"

### ISSUE THREAD

**Issue by rjhornsby** [inspec/inspec#6069]
# Describe the problem

Chef workstation 22.5.923 on macOS.

Under some conditions (it's not clear what), running `inspec exec` (or `kitchen verify`) on a cookbook will cause inspec to create an `inspec.lock` file. Inspec, during this run, behaves properly and executes the tests.

However, any further attempts to run `inspec` fail with the message:

```
>>>>>>     Failed to complete #verify action: 

[Don't understand inspec profile in 
.../cookbooks/vault_agent/test/integration/vault_agent, 
it doesn't look like a supported profile structure.] 

on vault-agent-ec2-rocky-8
```

The lockfile itself contains nothing of significance:

```
---
lockfile_version: 1
depends: []
```

Nothing else about the inspec profile/code/etc has changed. The workaround is to delete the lock file, and then inspec runs normally again until a new lockfile is created.

The test directory structure looks like so:

```
test
└── integration
    └── vault_agent
        ├── inspec.lock
        └── profile
            ├── controls
            │   ├── agent.rb
            │   └── secret.rb
            ├── inspec.yml
            └── libraries
                └── secret.rb

5 directories, 5 files
```

Regardless of whether inspec needs to create a lockfile, or is failing to remove it when it should, it doesn't seem to make much sense that `inspec exec` would create a file that causes inspec to break itself.

**Comment by clintoncwolfe** [comment]
Two things of note:

First, you can disable lockfile creation with the `--no-create-lockfile` option to inspec exec. You can also place that in your ~/.inspec/config.json, and it should be respected by kitchen-inspec, as well. So, that may be a workaround.

The second thing is, something odd is going on with your current directory. InSpec should drop that lockfile at the same level as the inspec.yml and controls/ folder - so the fact that it is dropping it one level up is very strange. InSpec is correct in complaining that `cookbooks/vault_agent/test/integration/vault_agent` doesn't look like a profile (it doesn't!) - but `cookbooks/vault_agent/test/integration/vault_agent/profile` **does** look like a profile. InSpec looks for a controls/ directory, among other things.

I'm assuming your filesystem is OK? "." isn't a symlink to ".." or something horrid?

Could you post an excerpt of your kitchen file?

**Comment by rjhornsby** [comment]
Thanks for the suggestion about preventing the lockfile from being written.

There's nothing special about the filesystem, nothing crazy like symlinks between `.` and `..`. Just a typical cookbook:

```
drwxr-xr-x  23 rhornsby  staff   736 May 25 12:36 .
drwxr-xr-x  77 rhornsby  staff  2464 May 17 13:28 ..
-rw-r--r--@  1 rhornsby  staff  6148 Apr  4 10:13 .DS_Store
drwxr-xr-x  13 rhornsby  staff   416 May 25 12:38 .git
-rw-r--r--   1 rhornsby  staff   214 Mar 28 18:33 .gitignore
drwxr-xr-x   9 rhornsby  staff   288 May 25 13:03 .idea
drwxr-xr-x   7 rhornsby  staff   224 May 20 23:37 .kitchen
-rw-r--r--   1 rhornsby  staff  2715 May 16 11:25 .kitchen.yml
...
drwxr-xr-x   3 rhornsby  staff    96 May  9 19:35 resources
drwxr-xr-x   7 rhornsby  staff   224 May  9 16:11 templates
drwxr-xr-x   3 rhornsby  staff    96 Mar 28 18:33 test
```

the `.kitchen.yml` bits I think you're asking for are:
```yaml
verifier:
  name: inspec
...
suites:
- name: vault_agent
  run_list:
  - recipe[vault_agent::default]
  verifier:
    inspec_tests:
    - test/integration/vault_agent
  attributes:
```

**Comment by Vasu1105** [comment]
I am assuming this is resolved by using --no-create-lockfile option and looking at the .kitchen.yml modifying verifier entry to the following should solve the problem without providing --no-create-lockfile option.
```
verifier:
    inspec_tests:
    - test/integration/vault_agent/profile
```
