### ISSUE TITLE
tab-completion support in the inspec command line and in the inspec shell :)

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#607]
Tab-completion ... at least limited support may be good for the release.

I will see if I can grok bash-complete and add it in.

**Comment by chris-rock** [comment]
+1 on that feature!

**Comment by chris-rock** [comment]
We should at least target ZSH and Bash. Not sure if we could find a way to get tab completion for Powershell?

cc @ksubrama

**Comment by ksubrama** [comment]
As one idea of possibly supporting this in powershell, we can write cmdlet wrappers to inspec and load it as a powershell module.  Powershell will try to tab complete cmdlet parameters but this means replicating the parser's logic in a cmdlet and maintaining that.  Also there are some argument parsing and quoting issues between powershell and ruby on windows.  See the comment block below for the chef powershell wrappers on windows which have been a mixed success as far as I can tell.

https://github.com/chef/chef/blob/master/distro/powershell/chef/chef.psm1#L213-L273

**Comment by chris-rock** [comment]
We could also think about reusing our bash completion for https://github.com/mridgers/clink
