### ISSUE TITLE
How to -Check a rule in if then else block / Attributes for profiles

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#611]
Is there a way in inspec to check for a particular rule and only if that rule passes execute the rest of the rules?
trying to do something like if a service exists, only then execute the rest of the rules.

```
only_if do 
  service('dhcpd').exists 
end
```

But this is not the right way. Trying to find the right way ..

**Comment by chris-rock** [comment]
At this point of time, you could do two things:
- `only_if` as highlighted above, but that skips all tests within the same .rb file
- use a ruby syntax to test for the criteria like:

```
if command('sshd').exist?
  describe service('ssh')
     it { should be_running }
  end
end 
```

We should maybe think about something like:

```
condition = command('sshd').exist?
control do
   describe service('ssh') do
      it { should be_running }
   end
   only_if condition
end
```

Would the last example meet your needs?

**Comment by kdshah1** [comment]
@chris-rock yes, it will satisfy one of the use case.
The other use case that I was think was can we assign a boolean value true or false to a test and if that test passed, execute one or more test otherwise execute another set of test.
i.e 

```
result = describe .... do
   ........
end
if result 
{
  describe... do
  .....
  end
  describe .... do
  ....
  end
}
else
{
  describe... do
  .....
  end
  describe .... do
  ....
  end
}
```

**Comment by AnotherNerdHere** [comment]
I would like to be able to so something like the above but for app, service or host for example below in my bad pseudo code. 

#myapp could be mysql, nginx, gpg, tree, ruby, pretty much thing that responds to which

```
if myapp.isinstalled  {
  control "xx"
    describe something
    etc, etc
}

if service.isrunning {       
  control "yy"
    describe something
    etc, etc
}

if host("#{node['myhost']}) is_reachable   # also being able to use something like is reachable on port 123
  control "zz"
    describe something
    etc, etc
}
```

**Comment by chris-rock** [comment]
@kdshah1 I would propose a syntax as following:

```
result = describe .... do
   ........
end

control do
  describe... do
  .....
  end
  describe .... do
  ....
  end
  only_if result == condition
end

control do
  describe... do
     .....
  end
  describe .... do
    ....
  end
  only_if result != condition
end

```

I would try to make a test as flat as possible, by attaching the execution condition to the test, we can display easily why a test has not been executed. Otherwise this will be very difficult to display the reason for non-execution in a compliance report. This would lead to a state, where its hard to debug controls and profiles. I try to avoid that.

@AnotherNerdHere I would write your example slightly different:

```
control "xx"  {
    describe something do
       ...
    end 
    only_if package('myapp').installed? 
}

control "yy" {
    describe something do
       ...
    end
    only_if service('myservice').running?
}

# also being able to use something like is reachable on port 123
control "zz"
    describe something do
    ...
    end
   only_if host("#{node['myhost']}).reachable?
}
```

Currently, we do not have `only_if` exposed as a feature for controls. We started collecting it in #613. Would those examples work for you?

**Comment by aaronlippold** [comment]
@chris-rock does 

if command('sshd').exist? currently work? Or are you suggesting that it can be added?

**Comment by aaronlippold** [comment]
Also, would the more natural logic be:

if service('sshd').exist? ....

Isn't that what we are really asking ?

**Comment by aaronlippold** [comment]
@chris-rock @arlimus I think this ties back to the idea that a profile itself has different logical use cases - i.e. run time options that the profile supports.
- Is the system allowed to use dhcp - or needs to at the moment ...
- is it a web-server
- does it act as a mail relay?
- does it use remote monitoring

Looking at: http://people.redhat.com/swells/scap-security-guide/RHEL/6/output/ssg-centos6-guide-C2S.html 

You will see working like - remove / disable a service if the system isn't a something, remove a package if possible. 

This will also come more into play if we are inheriting profiles. 

Like, I have a web server that is running the base-system profile, the web server profile, the data-center profile. The inherited profiles may have params set that would change the results of the baseline test. i.e. baseline has tests to ensure ntp is setup correctly, that dhcp is disabled for each interface, etc. But those tests could change with the 'run time' options / conditions that we pass either from the command line or from params in inherited profiles.
1. base-system:
   - core checks for linux etc
   - param: uses_dhcp, use_ipv4
   - param: subnet, ipv4_scheme{192.168.1.x/24}
2. web-server:
   - checks for web security configuration
   - param: webserver, apache
3. data-center:
   - checks for data-center configuration elements
   - param: ntp_server == 'myntp'
   - param: syslog_server == 'mysyslog'
   - param: subnet, ipv4_scheme{10.1.0.x/24}

```
control 'dhcp_client-01' do
  impact 0.2
  tag severity: 'low'

  title 'System Must Disable DHCP Client.'
  desc "
   DHCP relies on trusting the local network. If the local network is not trusted,
   then it should not be used. However, the automatic configuration provided by
   DHCP is commonly used and the alternative, manual configuration, presents an
   unacceptable burden in many circumstances.
  "
  tag cce: 'CCE-27021-5'
  tag cci: 'CCI-000366'
  tag nist: 'CM-7'
  tag disa: 'RHEL-06-000292'

  ref 'RHEL6-SG'

  describe 'Disable DHCP Client.' do
    skip 'For each interface on the system (e.g. eth0),
      edit /etc/sysconfig/network-scripts/ifcfg-interface and make the following changes.
      Correct the BOOTPROTO line to read: BOOTPROTO=none.
      Add or correct the following lines, substituting the appropriate values based on
      your site\'s addressing scheme: NETMASK=255.255.255.0 IPADDR=192.168.1.2 
      GATEWAY=192.1.1.1'
  end
end
```

```
ontrol 'ntp-03' do
  impact 0.2
  tag severity: 'low'

  title 'System Must Specify a Remote NTP Server.'
  desc "
   Synchronizing with an NTP server makes it possible to collate system logs 
   from multiple sources or correlate computer events with real time events. 
  "
  tag cce: 'CCE-27098-3'
  tag cci: 'CCI-000160'
  tag nist: 'AU-8(1)'
  tag disa: 'RHEL-06-000248'

  ref 'NSA-RH6-STIG Section 3.10.2.2.3'
  ref 'RHEL6-SG'

  describe 'Specify a Remote NTP Server.' do
   skip 'The /etc/ntp.conf must be verified manually to have a remote hostname for ntp server'
  end
end
```

```
control 'ipv6-01' do
  impact 0.5
  tag severity: 'medium'

  title 'System must disable IPv6, for regular IPv4-only servers'
  desc 'Unless explicitly needed, do not enable IPv6 on the node to reduce the
        attack surface.'

  tag cce: 'CCE-27153-6'
  tag cci: nil
  tag disa: 'DISA FSO RHEL-06-000098'
  tag nist: 'CM-7'

  ref ' NSA-RH6-STIG Section 2.5.3.1.1'

  describe kernel_parameter('net.ipv6.conf.all.disable_ipv6') do
    its('value') { should eq 1 }
  end
end
```

**Comment by kdshah1** [comment]
@AnotherNerdHere , yes, I like what you are suggesting, exposing the only_if as a feature for controls. That will work for the scenarios that I am talking about. Is this feature something you are targeting to add in near future?

**Comment by aaronlippold** [comment]
Note the logic here is: 

If the system is not using NFS mounts ... then ... 

```
control 'nfs-disable-01' do
  impact 0.2
  tag severity: 'low
'

  title 'System Must Disable Network File System Lock Service (nfslock).'
  desc "
    If the local machine is not configured to mount NFS filesystems then this 
    nfslock service with elevated privileges, which starts RPC processes allowing clients to lock files 
    on the server should be disabled to improve security posture.
  "
  tag cce: 'CCE-27104-9'
  tag cci: nil
  tag nist: nil
  tag disa: nil

  ref 'NSA-RH6-STIG Section 3.13.1.1'
  ref 'RHEL6-SG'

  describe service('nfslock') do
    it { should_not be_enabled }
    it { should_not be_running }
  end
end


control 'nfs-disable-02' do
  impact 0.2
  tag severity: 'low'

  title 'System Must Disable Secure RPC Client Service (rpcgssd).'
  desc "
    If the system does not require secure RPC then this service should be disabled. 
  "
  tag cce: 'CCE-26864-9'
  tag cci: nil
  tag nist: nil
  tag disa: nil

  ref 'NSA-RH6-STIG Section 3.13.1.1'
  ref 'RHEL6-SG'

  describe service('rpcgssd') do
    it { should_not be_enabled }
    it { should_not be_running }
  end
end
```

**Comment by chris-rock** [comment]
@aaronlippold  That works already. If you call the resource from ruby directly, you can call all methods that are defined in that resource:

```
if service('myservice').running?
    control "yy" {
       describe something do
       ...
       end
    end 
end
```

IF has some disadvantages compared to `only_if`. Would you prefer to use `if` around the checks compared to an `only_id` condition attached to controls?

I agree, that the params play a role in how we execute profiles, but the params will be well defined before a profile or inherited profile will be executed. Do they have impact on if conditions for controls?

**Comment by arlimus** [comment]
@aaronlippold Great point on inheritance! It's breaking my head too atm, i.e. how does skip behave on inheritance. Let's cover this separately, inheritance + skip is a tricky one to get right :smile: . Love your example, we should use this as the basis.

@AnotherNerdHere I finished that `control do ... only_if xyz?` section on my flight, will have it up later tonight (PDT) and reviewed by @chris-rock a bit later (morning CET). It's coming :+1:

**Comment by kdshah1** [comment]
@AnotherNerdHere , Awesome!

**Comment by arlimus** [comment]
And here it is, cheers to Chris for reviewing so quickly:
https://github.com/chef/inspec/pull/619

It's not yet released, but feel free to use the latest master; We'll have inspec 0.18 out by the end of the week.

**Comment by aaronlippold** [comment]
So, I think we are all on the same page with this. As a first step, I think we should be able to have basic params in profiles so that we can properly implement tests such as these for individual profiles. I think that the complexity of inheritance and overriding can be addressed later. 

```
control 'dhcp_client-01' do
  impact 0.2
  tag severity: 'low'

  title 'System Must Disable DHCP Client.'
  desc "
   DHCP relies on trusting the local network. If the local network is not trusted,
   then it should not be used. However, the automatic configuration provided by
   DHCP is commonly used and the alternative, manual configuration, presents an
   unacceptable burden in many circumstances.
  "
  tag cce: 'CCE-27021-5'
  tag cci: 'CCI-000366'
  tag nist: 'CM-7'
  tag disa: 'RHEL-06-000292'

  ref 'RHEL6-SG'

  describe 'Disable DHCP Client.' do
    skip 'For each interface on the system (e.g. eth0),
      edit /etc/sysconfig/network-scripts/ifcfg-interface and make the following changes.
      Correct the BOOTPROTO line to read: BOOTPROTO=none.
      Add or correct the following lines, substituting the appropriate values based on
      your site\'s addressing scheme: NETMASK=255.255.255.0 IPADDR=192.168.1.2 
      GATEWAY=192.1.1.1'
  end
end

control 'ntp-03' do
  impact 0.2
  tag severity: 'low'

  title 'System Must Specify a Remote NTP Server.'
  desc "
   Synchronizing with an NTP server makes it possible to collate system logs 
   from multiple sources or correlate computer events with real time events. 
  "
  tag cce: 'CCE-27098-3'
  tag cci: 'CCI-000160'
  tag nist: 'AU-8(1)'
  tag disa: 'RHEL-06-000248'

  ref 'NSA-RH6-STIG Section 3.10.2.2.3'
  ref 'RHEL6-SG'

  describe 'Specify a Remote NTP Server.' do
   skip 'The /etc/ntp.conf must be verified manually to have a remote hostname for ntp server'
  end
end
```

**Comment by raghuteja9** [comment]
Hi All,

I have a requirement of converting our bladelogic script to controls.
Blade logic code : 
----------------
if
   "Command:cat /etc/redhat-release".Out_Put is not one of ["x", "y", "z"]
then
   "File:/etc/inittab".Contents contains "id"
end
----------------
Note: Out_put can be considered as stdout.

Inspec code what I have written. 

if describe file('/etc/inittab') do
    its('content') { match 'id' }
end

then
  describe command('cat /etc/redhat-release') do
    its('stdout') { should_not match 'x' }
    its('stdout') { should_not match 'y' }
    its('stdout') { should_not match 'z' }
    end
  end
end

My question here is whether the code I have written is correct or not, or should I use any other way to write the inspec control. Thanks in advance.
