### ISSUE TITLE
Ensure that the package resource operates with the expected names

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#615]
I have noticed that with the package resource we are actually using the service name rather than the formal package name - at least with RHEL - which makes things a bit inconsistent. I think this would also help us better manage how we use the Service resource as well considering the complexity of supporting different init systems.

IMHO:

describe package('dhcpd') do
   it { should_not be_installed }
end

There is no package named dhcpd .... 

==>

describe package('dhcp.x86_64') do
  it { should be_installed }
end 

describe package('openssh-server') do
  it { should be_installed }
  it { should have_arch 'x86_64' }
end

**Comment by aaronlippold** [comment]
I believe this will also improve inspec's overall adherence to establish standards with the package management systems etc - i.e. more gnu-proper.

**Comment by chris-rock** [comment]
@aaronlippold package should always use the same name as you use with yum or dnf. If that is not the behavior, it should be considered as a bug. We've never implemented a way to use a service name for packages, this may just happen coincidental e.g. on Ubuntu systems.

**Comment by aaronlippold** [comment]
Ok. Then it seems to be a bug with the yum packages. I think with openssh-server as an example really wants sshd as the input. I think that is what @kdshah1 told me.

**Comment by chris-rock** [comment]
Could you share the InSpec test and the specific OS, so that I am able to reproduce it?

**Comment by aaronlippold** [comment]
Ok. Will do. Let me see if I can find it.

**Comment by kdshah1** [comment]
So, inspec is working as designed and it does pass the test if a correct package name is given irrespective of version specified or not. 
But this could be future enhancement, the ability to when a required service fails - it returns the needed package to be installed.

**Comment by chris-rock** [comment]
@kdshah1 thanks for your feedback. That behavior is tracked in #616 I close this one. Do not hesitate to reopen, if you think its required

**Comment by jquick** [comment]
Closing this in favor of #616. If that does not fully cover this case we can reopen.
