### ISSUE TITLE
Example of a "user action" test

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#617]
```
control 'nfs-conf-04' do
  impact 0.2
  tag severity: 'low'

  title 'Configure mountd to use static port.'
  desc "Configure the mountd daemon to use a static port as opposed to letting 
   the RPC Bind service dynamically assign a port."
  tag cce: 'CCE-26889-6'
  tag cci: nil
  tag nist: nil
  tag disa: nil

  ref 'NSA-RH6-STIG Section 3.13.2.3'
  ref 'RHEL6-SG'

  describe 'Configure statd to use static port' do
   skip 'Edit the file /etc/sysconfig/nfs. Add or correct the 
         following line: MOUNTD_PORT=statd-port Where mountd-port is a 
         port which is not used by any other service on your network.'
  end
end
```

This really should not be a 'skip' test, does it make sense to have a concept of 'user_action' or a needed profile param?

**Comment by chris-rock** [comment]
@aaronlippold This specific use cases leads to profile attributes. Attributes are assigned to an environment or node and are filled in during execution time. This is something that we have on our agenda for our next releases.

From my perspective, this example would not require a user interaction, since the port must be defined before we run the test.

**Comment by aaronlippold** [comment]
@chris-rock I hear you and we are in agreement. The "user" in this case was the person doing the review, in our case, that is inspec. I think we are on the same page, 'params', 'attributes' etc. all the same concept and would allow us to use inspec answer this test. This was just an example for us to work from to say, how / which data would we need to define in the 'profile structure' to allow this test to work.

**Comment by chris-rock** [comment]
yes @aaronlippold , we are on the same page. That is a very good example!

**Comment by aaronlippold** [comment]
```
#FIXME here all the below test should check if the file size is > 0 and then test all these rule.
control 'nfs-server-01' do
  impact 0.2
  tag severity: 'low'
  title 'Authorization Restrictions Must be Enforced based on Use Access List on Mounts.'
  desc "
    All lines of the exports  le should specify the hosts (or subnets, if needed) 
    which are allowed to access the exported directory, so that unknown or remote 
    hosts will be denied.
  "
  tag cce: nil
  tag cci: nil
  tag nist: nil
  tag disa: nil
  ref 'NSA-RH6-STIG Section 3.13.4.1.1'
  describe 'Use Access Lists to Enforce Authorization Restrictions on Mounts.' do
    skip 'Edit /etc/exports. Ensure that each export line contains a set of IP 
          addresses or hosts which are allowed'
  end
end
```

**Comment by clintoncwolfe** [comment]
As attributes are now present, I'm closing this.
