### ISSUE TITLE
Add custom metadata to result-level

### ISSUE THREAD

**Issue by gtom1985** [inspec/inspec#6251]
## Detailed Description
 Is it possible somehow to create tags or add any metadata to result-level?

## Context
We are creating a report from inspec json output and the requirements is to add error code and a human readable error message to each check in describe block.

## Possible Implementation

I would like something like that: 

"results": [
            {
              "status": "passed",
              "code_desc": "Service firewalld is expected not to be running",
              "run_time": 0.055593887,
              "start_time": "2022-08-30T12:28:54+00:00",
              "error_code" : "0250",
              "error_message" : "Firewall service is running"
            }
          ]

Or are there any workarounds to achieve this goal?

Thanks and Regards,

Tom

**Comment by Vasu1105** [comment]
Maybe using your own custom reporter might help here https://github.com/inspec/inspec/blob/main/dev-docs/plugins.md#implementing-reporter-plugins.
