### ISSUE TITLE
Checking on services on SLES 11 fails

### ISSUE THREAD

**Issue by spuranam** [inspec/inspec#627]
### Description

Checking on services on SLES 11 fails. The services resource as [currently implemented](https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L138) only supports opensuse. SLES 11 uses SysV init whereas SLES 12 like latest version of opensuse uses Systemd.
### InSpec and Platform Version

Insepc Verison: 0.17.1
Chef Compliance: 1.0.4
OS version: SLES 11 SP3
### Replication Case

Sample

```
   describe service('sshd').runlevels(3, 5) do
     it { should be_enabled }
     it { should be_installed }
     it { should be_running }
   end
```

output

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Service sshd The `service` resource is not supported on your OS yet.
     # Not yet implemented
     # /Users/sp/.chefdk/gem/ruby/2.1.0/gems/inspec-0.17.1/lib/inspec/runner.rb:128


Finished in 0.00036 seconds (files took 1.45 seconds to load)
1 example, 0 failures, 1 pending
```
### Possible Solutions

I am not sure if [this would](https://github.com/spuranam/inspec/blob/suse-service/lib/resources/service.rb#L140-L146) be an appropriate fix. Secondly what kind of test cases should be defined since kitchen.yml does not list suse 11 or 12 as supported platforms.
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
@spuranam Thank you very much for reporting. Your fix looks very good, but I would split out arch and let arch just use systemd. That makes the code simpler. Could you open up a PR?
