### ISSUE TITLE
Can't use os helper from example group context

### ISSUE THREAD

**Issue by coderanger** [inspec/inspec#628]
It would be nice to map the `os` method helper in to all contexts. Currently you can't do this:

``` ruby
describe file('/app') do
  it { is_expected.to be_a_directory }
  it { is_expected.to be_owned_by 'root' } unless os.windows?
end
```

It fails with `undefined local variable or method 'os' for RSpec::ExampleGroups::FileApp:Class`. Pulling the `os.windows?` into a local variable from the top level fixes this, but is clunky. I think we can probably define an `os` method in the resource base class that leaves this as a valid alias.

**Comment by chris-rock** [comment]
Thanks Noah for reporting. Indeed that is an issue we need!
