### ISSUE TITLE
Can't use nested describe blocks

### ISSUE THREAD

**Issue by coderanger** [inspec/inspec#630]
InSpec appears to be incompatible with nested example groups like:

``` ruby
describe 'something' do
  describe file('/') do
    # …
  end

  describe command('…') do
    # …
  end
end
```

```
undefined method `file' for RSpec::ExampleGroups::Something:Class
```

The RSpec DSL code should either declare the resource methods more globally or just override `describe` and `context` and inject the DSL there.

**Comment by chris-rock** [comment]
@coderanger we use control for that:

```
control 'something' do
  describe file('/') do
    # …
  end

  describe command('…') do
    # …
  end
end
```

**Comment by coderanger** [comment]
Yes, I'm saying you should fix the standard RSpec syntax to work correctly. Also AFAIK `control` can't be nested and doesn't support the `context` helper.

**Comment by arlimus** [comment]
:+1: good point

**Comment by clintoncwolfe** [comment]
These decisions pre-date me, but the product design for InSpec is to have it be two layers deep at most - control and describe. InSpec != RSpec, though it is based on it.  

So, I'm closing this as Declined.

**Comment by taqtiqa-mark** [comment]
@clintoncwolfe , appreciate any insight into use cases such as the following examples from the sou-chef's:

https://github.com/sous-chefs/ruby_rbenv/blob/master/test/integration/user_install/controls/user_install.rb#L9

More specifically, it seems natural to want to audit/control environment variables using inspec:
```
describe bash('sudo -H -u vagrant bash -c "source /etc/profile.d/rbenv.sh && rbenv global"') do
    describe os_env('PATH') do
      its('split') { should include('/usr/local/rbenv/shims')}
      its('split') { should include('/usr/local/rbenv/bin') }
    end
    describe os_env('RBENV_ROOT') do
    # etc.
    end
end
```
could you point to any example showing how to control/specify this using 1-deep describes
