### ISSUE TITLE
Add warning of missing Powershell 5

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#633]
### Description

Powershell shipped with Windows 2008 R2 does not ship with a Convert-To-JSON command. That is heavily used in our resources
### InSpec and Platform Version

0.17.1
### Replication Case
- Install Windows 2008 R2
### Possible Solutions

Add a Warning that highlights that Windows Management Framework 5.0 https://www.microsoft.com/en-us/download/details.aspx?id=50395 is not installed

Aha! Link: https://chef.aha.io/features/SH-2641

**Comment by kekaichinose** [comment]
@jerryaldrichiii have you heard recent complaints on this issue?

**Comment by clintoncwolfe** [comment]
Windows 2008 R2 reached EOL January 14, 2020. Closing.
