### ISSUE TITLE
Cannot test the resource deployed in another region

### ISSUE THREAD

**Issue by prasuprasobh** [inspec/inspec#6335]
We have  deployed the lambda functions on aws and one of the lambda resource located in us-east-1 region and other resource on the default region (eu-central-1).  All the tests  are successful for the resources deployed on  the default region.  So how can the test the resource other than the default region.

# Controls
control "LambdaFunction" do
  impact 1.0
  title "Ensure AWS Lambda funtion has the correct properties."
  for lambda in aws_lambda
      describe aws_lambda(lambda) do
      it { should exist }
		  its ('state') { should eq 'Active'}
		  # its ('kms_key_arn') { should eq aws_lambda_kms_key_arn }
		  its ('role') { should be_in aws_lambda_role_name }
		  its ('tags') { should include( 'project' => "xxx",
                          'environment' => input('environment'),
                          'map-migrated' => "d-server-xxxxxxxx",
                          'Terraform' => "true"
                        ) }
		  end
    end
 end

inspec_version: '>= 5.18.14'
only one test is failing which is located in us-east-1

**Comment by ahasunos** [comment]
This issue could be closed as the same is raised on inspec-aws, [Issue 956](https://github.com/inspec/inspec-aws/issues/956)
