### ISSUE TITLE
Check if Application is Running with InSpec

### ISSUE THREAD

**Issue by AlwaysTrying2Learn** [inspec/inspec#6336]
## Detailed Description
So there may already be a resource which can do this with InSpec but its not obvious to me. I would like to be able to use InSpec to check if internet explore (iexplore.exe) is disabled and/or deleted. So I would like to be able to just type in a application name e.g. "iexplore.exe" into the resource function in the ruby code and have a matcher such as "should be_installed". I need this mainly for windows but all operating systems will also be preferred. 

## Context
I personally need this as I am trying to meet some compliance requirements which are defined in my workplace. Application Control is a big part of our Cyber Security and having the ability to test if these applications are removed or disabled would be great.

**Comment by ahasunos** [comment]
As applications on windows are installed in the Program Files or Program Files (x86) directories, you could use a combination of `directory` and `file` resources to meet your requirement. . Additionally, you could use the `command` resource to see if the application exists.

Edit: @AlwaysTrying2Learn there is the `package` resource specific for this purpose.

**Comment by clintoncwolfe** [comment]
Closing this as answered.
