### ISSUE TITLE
failing gracefully on missing things in resources

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#634]
We are currently returning nil at some places where things are missing, e.g.

``` ruby
mount('/tmp').options ==> nil
```

inside of tests this really gets us bad output:

``` ruby
describe mount('tmp') do
   its('options') { should include 'noexec' }
end
```

erroring out with `nil` cannot respond to `include?` instead of giving a straight answer.

Use proper resource skipping here.

**Comment by clintoncwolfe** [comment]
Closing in favor of #3174
