### ISSUE TITLE
recent 4.x versions not published

### ISSUE THREAD

**Issue by wyardley** [inspec/inspec#6365]
# Describe the problem
Hi all — I see a `4.56.31` tag cut, but `4.56.20` seems to be the latest available version at https://rubygems.org/gems/inspec/versions

## Possible Solution
It seems like the CI jobs may be failing?

**Comment by Vasu1105** [comment]
Yes, We have not yet released that version.

**Comment by wyardley** [comment]
Got it.

Maybe a dumb question, but is it intentional that tags are getting cut for, e.g., `v4.56.21`, etc. for releases that are not actually going to be published? Even if the version is being updated on a running basis, it seems a little confusing to cut a tag it if it's not being released / published (the fact that so many of the CI builds fail is another part of why I thought it might not be intentional).

Is a release planned for sometime soon?

Also, does Chef use the odd / even convention for dev vs. stable releases? Either way, are there docs somewhere about the difference between inspec 4.x and 5.x? I couldn't find anything in the project readme, and in the changelog, information about 4.x and 5.x releases are just interspersed.
