### ISSUE TITLE
Show error stacktrace only if --debug is used

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#640]
### Description

RSpec errors are displayed with stacktrace by default. This confuses user
### InSpec and Platform Version

All
### Replication Case

Just run a test that fails, eg. 

```
b inspec exec examples/profile/
..*..

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) gordon_config Can't find file "/tmp/gordon/config.yaml"
     # Not yet implemented
     # ./lib/inspec/runner.rb:140  <------ This line


Finished in 0.04023 seconds (files took 0.58184 seconds to load)
5 examples, 0 failures, 1 pending
```
### Possible Solutions

Do not display the stacktrace by default, but we should be able to enable that for debugging

**Comment by clintoncwolfe** [comment]
Refs #874 #3094

**Comment by clintoncwolfe** [comment]
At this point I believe that stacktraces are hidden by default, but I am not sure that `--debug` will cause it to display.
