### ISSUE TITLE
InSpec OS package

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#646]
### Description

Current installation for inspec may be a hassle. It may not work if other gems are installed that use the same dependencies but in different versions.
### InSpec and Platform Version

0.18.0
### Replication Case

As reported in #642, a newer beta version of Rspec is able to break inspec.
### Possible Solutions

InSpec should be shipped as native deb, rpm and msi package, to ease the installation.

**Comment by arlimus** [comment]
Also helpful for https://github.com/chef/inspec/issues/653

**Comment by srenatus** [comment]
This means shipping all of Ruby, right?

**Comment by chris-rock** [comment]
InSpec 1.0 ships with packages for Windows, Mac and Linux
