### ISSUE TITLE
postgres_session : Add support for custom port while using socket

### ISSUE THREAD

**Issue by Taknok** [inspec/inspec#6493]
Currently the inspec ressource `postgres_session.rb` does not support the connection to a postgresql server with a socket and a custom port.

## Detailed Description
The [line handling the connection](https://github.com/inspec/inspec/blob/31d7a56331bc7ad1bf634b385ade9add9cd64684/lib/inspec/resources/postgres_session.rb#L80) with a socket does not use the port :
```ruby
psql -d postgresql://#{@user}:#{@pass}@/#{dbs}?host=#{@socket_path} -A -t -w -c #{escaped_query(query)}
```
Thus, when connecting to a postgresql server listening on port 1234 with the socket /var/run/unusual/path/postgresql the following error is returned:
```
psql: error: connection to server on socket "[...]" failed: No such file or directory
Unix socket "/var/run/ununsual/path/.s.PGSQL.5432 » ?
```
## Context
This would allow to use the socket connection on a server listening on a unusual port.

## Possible Implementation
```ruby
option_port = "-p #{@port} " if @port else ""
```

**Comment by Vasu1105** [comment]
Closing this Fixed in https://github.com/inspec/inspec/pull/6494
