### ISSUE TITLE
gem install failure on RHEL 7.2 Ruby 2.0

### ISSUE THREAD

**Issue by DonPwrShellHunt** [inspec/inspec#653]
### Description

The documented way to install inSpec fails on a fresh install of RHEL 7.2
Similar to #641 

README indicates that inSpec requires ruby (>1.9)
and lists the following command to install via rubygems.org
gem install inspec

The failure output I received follows:
`# gem install inspec`

```
.
.
Building native extensions.  This could take a while...
ERROR:  Error installing inspec:
    ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Gem files will remain installed in /usr/local/share/gems/gems/json-1.8.3 for inspection.
Results logged to /usr/local/share/gems/gems/json-1.8.3/ext/json/ext/generator/gem_make.out

```
### InSpec and Platform Version

$ inspec version
0.18.0

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
### Replication Case

Attempt install using gem method without ruby-devel being installed
### Possible Solutions

yum install ruby-devel

**Comment by arlimus** [comment]
@DonPwrShellHunt We added instructions for installation requirements to the readme:

``` bash
yum -y install ruby ruby-devel make gcc
```

Feel free to reopen if this still fails. Tested on CentOS 7.2.1511

Thank you for reporting this issue! :smile:

**Comment by rameshVeeramani** [comment]
Well in my case there were serveral issues with installation of ruby, versioning .

Followed the steps https://tecadmin.net/install-ruby-latest-stable-centos/ and it fixed the issue

**Comment by glasgowm148** [comment]
> @DonPwrShellHunt We added instructions for installation requirements to the readme:
> 
> ```shell
> yum -y install ruby ruby-devel make gcc
> ```
> 
> Feel free to reopen if this still fails. Tested on CentOS 7.2.1511
> 
> Thank you for reporting this issue! 😄

This fixed my issue on CentOS8.

While troubleshooting I got this, figure it may mean more to you. 

```
❯ dnf -y install ruby`ruby -e 'puts RUBY_VERSION[/\d+\.\d+/]'`-dev
Last metadata expiration check: 0:01:24 ago on Fri 28 Feb 2020 11:56:47 UTC.
No match for argument: ruby2.5-dev
Error: Unable to find a match: ruby2.5-dev
```
