### ISSUE TITLE
Support newest version with ruby 3.2

### ISSUE THREAD

**Issue by wyardley** [inspec/inspec#6537]
# Describe the problem
Installing inspec v5.22.3 via bundler seems to fail on Ruby 3.2, apparently because of dependencies (I can file a bug under https://github.com/inspec/train-kubernetes as well if you'd like). `v5.21.29` seems to work fine as it did previously.

Given the following Gemfile:
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'inspec', '~> 5.22.3'
gem 'inspec-bin', '~> 5.22.3'
```

With older bundler versions, it just hangs forever (https://github.com/rubygems/rubygems/issues/6686)

With the updated bundler version, the error is more helpful:

```
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Could not find compatible versions

Because train-kubernetes < 0.1.3 depends on k8s-client = 0.10.0
  and train-kubernetes >= 0.1.3, < 0.1.4 depends on k8s-client ~> 0.10,
  train-kubernetes < 0.1.4 requires k8s-client >= 0.10.0, < 1.A.
And because every version of k8s-client depends on Ruby ~> 2.4
  and train-kubernetes >= 0.1.4, < 0.1.10 depends on k8s-ruby ~> 0.10,
  train-kubernetes < 0.1.10 requires Ruby ~> 2.4 or k8s-ruby ~> 0.10.
So, because train-kubernetes >= 0.1.10, < 0.1.12 depends on k8s-ruby = 0.10.5
  and k8s-ruby < 0.11.0 depends on Ruby ~> 2.4,
  train-kubernetes < 0.1.12 requires Ruby >= 2.4, < 3.A or k8s-ruby >= 0.11.0, < 1.A.
```

**Comment by wyardley** [comment]
In case this isn't expected, also mentioning https://github.com/jhawthorn/pub_grub/issues/30 here since my original issue with bundler is now closed.

**Comment by luckeyca** [comment]
got the same issue on alpine docker image. ruby version is 3.2.2. inspec-bin version 5.21.29 installed fine, but 5.22.3 failed with dependency error.

**Comment by wyardley** [comment]
FWIW, not sure if a fix finally landed somewhere (since #6622 etc. are still in progress), but it worked for me today with Ruby 3.2 and bundler 2.4.14 for some reason. 🤷

**Comment by Nik08** [comment]
It works out locally with Ruby version 3.2.x because [k8-ruby](https://github.com/k8s-ruby/k8s-ruby/pull/44) changes for 3.2 were pulled in on [inspec/k9s-ruby](https://github.com/inspec/k8s-ruby/pull/5). 
I'm still trying to figure out why it works locally and breaks on CI.
The work is still in progress in PR #6622 because there are certain tick boxes we need to achieve before releasing InSpec with ruby 3.2 support. I have updated the PR description with the list.

**Comment by wyardley** [comment]
Yup, totally understand, and thanks for the explanation about why!

**Comment by wyardley** [comment]
https://github.com/inspec/inspec/blob/06ed411667ef5fe58e7e40dc7d083e5a3fa0c6e5/inspec.gemspec#L24
Seems like 3.1 at least is supported; 3.2 and 3.2 may not be supported yet in Inspec 5.

From my standpoint, I don't need this anymore, so I'm going to close the issue.
