### ISSUE TITLE
inspec : Cannot process the XML from the 'Error' stream of 'C:\opscode\inspec\bin\inspec.bat': Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by TrueAutoAccept** [inspec/inspec#6589]
Running inspec exec on my vmware instances results in:
inspec : Cannot process the XML from the 'Error' stream of 'C:\opscode\inspec\bin\inspec.bat': Data at the root level is invalid. Line 1, position 1.

# Describe the problem
Any time I run the inspec against any targest i get an XML error.

This is on windows 2019 inspe -v: 5.22.3

I looked all over and cant find a way to fix this.

**Comment by clintoncwolfe** [comment]
How have you installed InSpec - from Chef Workstation or from the individual InSpec MSI package? This could be a packaging issue, but it seems unlikely.

How are you running inspec? Is this directly from the CLI? Could you paste the full invocation you are running?
