### ISSUE TITLE
windows_resource requires ConvertTo-Json ( PS3+ ) precluding stock win 2k8r2

### ISSUE THREAD

**Issue by jkerry** [inspec/inspec#660]
### Description

in inspec/lib/resources/windows_feature.rb the value of features_cmd contains the powershell 3+ commandlet: ConvertTo-Json.  This means a stock windows server 2k8r2 install will need to upgrade powershell in order to use the windows_feature inspec resource.
### InSpec and Platform Version

Inspec: 0.15.0
Platform: Windows Server 2k8R2, framework 4.5.2, powershell (win mgmt framework) v2
### Replication Case

Run a windows_feature resource on a stock 2k8r2 image and it'll categorically fail.
### Possible Solutions

include a hand rolled json conversion function (ex: https://gist.github.com/mdnmdn/6936714)  or find another way to bow back the required content from powershell into ruby, thus bypassing ConvertTo-Json
### Stacktrace

N/A

**Comment by jkerry** [comment]
@mwrock Here's the issue

**Comment by mwrock** [comment]
That gist looks promising. Because that function is so widespread in this gem, it might be the simplest approach.

**Comment by chris-rock** [comment]
@jkerry That is a very cool approach. Current recommendation was to upgrade Powershell, since Windows 2008 is already in extended support.

I would like to ensure the following:
- Therefore we should only load it, if powershell 2 is detected
- we only load it once for multiple resources

**Comment by mwrock** [comment]
Fyi: 2008 r2 goes into extended support in 2020. https://support.microsoft.com/en-us/lifecycle?p1=14134

**Comment by clintoncwolfe** [comment]
Looks like this was "fixed" with advisory docs in #1982
