### ISSUE TITLE
failed to check ssh -V command output

### ISSUE THREAD

**Issue by luckeyca** [inspec/inspec#6614]
# Describe the problem

inspec failed to capture "ssh -V" command output correctly. Details as below

1. environment: On ubuntu 22.04, inspec version 5.21.29 installed as ruby gem. ruby version is 3.2.2, openssh client ubuntu package version 1:8.9p1-3ubuntu0.3
2. when running "ssh -V" manually, output is "OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022"
3. with inspec check as below, it failed to validate the output above

  describe command('ssh -V') do
    its('exit_status') { should eq 0 }
    its('stdout') { should match(/OpenSSH_8.9p1/) }
  end

The test result was:

```
 ×  Command: `ssh -V` stdout is expected to match /OpenSSH_8.9p1/
     expected "" to match /OpenSSH_8.9p1/
     Diff:
     @@ -1 +1 @@
     -/OpenSSH_8.9p1/
     +""
```

**Comment by ahasunos** [comment]
The issue is that the command `ssh -V` is printing its output to the stderr stream instead of the stdout stream, despite having an exit status of zero.
```
(byebug) @command
"ssh -V"
(byebug) inspec.backend.run_command(@command, timeout: @timeout)
#<struct Train::Extras::CommandResult stdout="", stderr="OpenSSH_9.0p1, LibreSSL 3.3.6\n", exit_status=0>
```

**Comment by luckeyca** [comment]
Hi @ahasunos, I see. thanks.
