### ISSUE TITLE
RSpec World teardown

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#685]
### Description

@alexpop brought up an issue, where InSpec is used with Serverspec at the same time in chef-client audit mode.
### InSpec and Platform Version

audit cookbook 0.5.0
### Replication Case

See https://github.com/chef-cookbooks/audit/issues/34
### Possible Solutions

Teardown of RSpec world and configuration

**Comment by clintoncwolfe** [comment]
Pretty sure we don't support running ServerSpec and InSpec in the same process.  Please re-open if there is discussion on this point.
