### ISSUE TITLE
License Check issue on 6.6.0

### ISSUE THREAD

**Issue by lmayorga1980** [inspec/inspec#6863]
I am getting this error using the latest version `6.6.0`. Is there a flag to skip this since I am running local profiles and don't need a chef licensing server?

`Unable to connect to the licensing server. InSpec requires server communication to operate`

**Comment by ahasunos** [comment]
@lmayorga1980
Could you provide us the stack-trace?
Additionally, are you running in an air gapped environment?

**Comment by clintoncwolfe** [comment]
Chef InSpec 6 does require communication with a license server to perform any scan, whether local or remote. If you are running offline - without network communication - you will need to run a local license server and connect to that. For further details, please see the troubleshooting entry, https://docs.chef.io/inspec/troubleshooting/#unable-to-connect-to-the-licensing-server-inspec-requires-server-communication-to-operate

**Comment by lmayorga1980** [comment]
I was running Inspec since version 3 and never require a license and now starting version 6 a license server will be needed even though is still open source version? Also, even if you have a license provided, why would i need to go to the internet or set up an external component like a local license server. This can be an overkill configuration for users who just have some profiles locally and want to execute locally inspec.

**Comment by vin01** [comment]
Looks like a license key is required even for using this great open source tool in other open-source projects? wow!

**Comment by clintoncwolfe** [comment]
Since InSpec 4 (2019), InSpec has been under a dual license: the Apache v2 license applies to distribution of the source code, but the Chef EULA applies to the usage of the software - including commercial usage, and limiting most personal usage.  When you execute InSpec since version 4 you must agree to these dual license terms using the license acceptance mechanisms. However, in InSpec 4 and 5, there was no enforcement of the usage aspect of the licensing system. 

Beginning in InSpec 6, we at Progress Chef are starting to enforce tracking of the usage of the license, so that we can better guide our resources in future development of InSpec. This provides better service to our customers and allows us to continue to bring new features to the wider community.

**Comment by lmayorga1980** [comment]
This is sad news for the community.

**Comment by mietzen** [comment]
> License tiers
> We’ve updated the Chef End User License Agreement (EULA). The terms of the EULA are the same as they were before, but we’ve created three license tiers: Free, Trial, and Commercial.
> 
> The Free tier allows personal/non-commercial users to scan 10 targets for an unlimited period of time. The Trial tier allows trial users to scan unlimited targets for 30 days. The Commercial tier gives users the features and benefits that come with the subscription they’ve purchased.
> 
> Users who would like to try Chef InSpec 6 can [request a free or trial license](https://www.chef.io/licensing/inspec/license-generation-free-trial), which comes with product limitations.
> 
> See our [licensing documentation](https://docs.chef.io/release_notes_inspec/://docs.chef.io/licensing/) or contact [Chef Support](https://community.progress.com/s/products/chef) for more information.

Could you explain how you define a "target"?  Do you mean `inspec exe -t`? Does this mean I can only execute `inspec exe -t` 10 times in parallel with a free licence?

**Comment by lokeshk1987** [comment]
Please find the definition of target here : 

Q: What is a target?
A target is an instance of infrastructure, software, configuration, cloud accounts, container hosts or any other technical resource acting as the compliance target of one or more Chef InSpec profiles you use. Each target can access a resource with its credentials and locations.

https://www.chef.io/licensing-tiers-faq

You are limited to 10 different targets (inspec exec -t ) with the free-tier license

**Comment by lmayorga1980** [comment]
> @lmayorga1980 Could you provide us the stack-trace? Additionally, are you running in an air gapped environment?

Is this possible without internet connection?

**Comment by clintoncwolfe** [comment]
> > @lmayorga1980 Could you provide us the stack-trace? Additionally, are you running in an air gapped environment?
> 
> Is this possible without internet connection?

Generally, people will require an internet connection to use InSpec 6.

InSpec 6 requires a network connection to a license server. For most people, that is an internet connection to the Progress Chef global license service. For customers behind an air gap (disconnected from the Internet), Progress Chef offers a standalone private license server.

**Comment by bordencastle** [comment]
> Looks like a license key is required even for using this great open source tool in other open-source projects? wow!

Yeah, very strange. Goss & Ansible FTW.

**Comment by aaronlippold** [comment]
In your particular environment, perhaps the CINC project would be a good
option for you.

Check out http://cinc.sh

It’s a project sponsored by Progress and The OSL.

It’s the pure Apache to build of the inspec Code.

The license covers the Chef built binaries.

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by NeatNerdPrime** [comment]
Sorry to open this up again, but I would like a clarification.

So since 3307ee520cb5cda1b072d6a4deaddbd05753f5fb it is , although licensed as Apache2 / dual Chef EULA , when using the software as a ruby gem library - so *not the binary* - this also involves the license server thing?

https://github.com/inspec/inspec#install-it-via-rubygemsorg

> You may also use `inspec` as a library, with no executable. This does not require accepting the license.

Anyone would like to officially comment?

@aaronlippold  does the CINC project provide for the simple library as well?

**Comment by aaronlippold** [comment]
I believe so. Happy to chat about it over slack and see what we can see.

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
