### ISSUE TITLE
parse_config_file fails when it encounters a '['

### ISSUE THREAD

**Issue by nathenharvey** [inspec/inspec#687]
### Description

The `parse_config_file` resource seems unable to handle lines that start with `[`
### InSpec and Platform Version

0.19.3 on Mac OSX 10.11.4
### Replication Case

Given [this yum.conf](https://gist.github.com/nathenharvey/ac24b5ccabccdfc1282aca0005c05566#file-yum-conf) and this [InSpec test](https://gist.github.com/nathenharvey/ac24b5ccabccdfc1282aca0005c05566#file-gpgcheck-rb), the check fails with [this output](https://gist.github.com/nathenharvey/ac24b5ccabccdfc1282aca0005c05566#file-output).
### Possible Solutions

You can work around this by setting '[' as the comment character as shown in [this updated InSpec check](https://gist.github.com/nathenharvey/ac24b5ccabccdfc1282aca0005c05566#file-fixed_gpgcheck-rb)

**Comment by eyespies** [comment]
+1 on this

**Comment by vjeffrey** [comment]
```
  describe parse_config_file('../yum.conf') do
    its('main') { should include('gpgcheck' => '1') }
  end
```

in our attempt to track down this bug, we found that the file is being parsed correctly, but gpgcheck is part of the hash under 'main'.  A syntax like the above works...
What are people's thoughts?
Is that an ok syntax that just needs to be documented, or should we be doing something more/more specific for the yum.conf?

**Comment by vjeffrey** [comment]
Need to document this example in the resources docs for parse_config
