### ISSUE TITLE
How to run a single unit test within inspec

### ISSUE THREAD

**Issue by mhedgpeth** [inspec/inspec#693]
### Description

When I try to run a single unit test following instructions in README.md, it doesn't work
### InSpec and Platform Version

Latest master code pull
### Replication Case

Run this command:

```
chef exec bundle exec ruby -W -Ilib:test test/unit/fetchers_test.rb
```

I get an error: test/unit/fetchers_test.rb:5:in `require': cannot load such file -- helper (LoadError)
any idea on what I might be doing wrong to get the test working? 
### Possible Solutions

Perhaps I didn't have the right gems installed, but I was able to run this:

```
I was able to execute chef exec bundle exec rake test
```

**Comment by chris-rock** [comment]
Interesting. Haven't used bundler in combination with Chef DK. Have you installed all dependencies before? 

```
chef exec bundle install
chef exec bundle exec ruby -W -Ilib:test test/unit/fetchers_test.rb
```

Bundle is a tool to install gem development dependencies. This includes also build or test depdencies

**Comment by mhedgpeth** [comment]
Yes I did those two commands before coming across the error. I'm using ChefDK 0.12. Is it perhaps a windows thing? Unfortunately I don't understand how the dependencies go together to know how to troubleshoot.

**Comment by chris-rock** [comment]
I just tried this on my machine and it is working. I am going to test this on my windows machine as well.

**Comment by mhedgpeth** [comment]
Were you able to reproduce on a windows machine @chris-rock? I just tried again and it's not working.

**Comment by chris-rock** [comment]
@mhedgpeth I've been successful with `bundle exec ruby -W -Itest test/unit/fetchers_test.rb`
