### ISSUE TITLE
Escape commands before we execute them

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#70]
Use http://ruby-doc.org/stdlib-2.0.0/libdoc/shellwords/rdoc/Shellwords.html for command escape

**Comment by arlimus** [comment]
Great point!

This should actually be done in [train](github.com/chef/train), where it is currently implemented for local (using shellout). The execution in the other backends uses their own method: docker (via docker.exec), ssh (via channel.exec), winrm (via powershell script). We may still need to escape it, especially considering sudo is entering the mix.
