### ISSUE TITLE
docker resources

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#71]
```
    describe docker.container('busybox') do
      it { should exist }
      it { should be_running }
    end

    describe docker.image('busybox:latest') do
      it { should exist }
    end
```

**Comment by walterdolce** [comment]
Hi @chris-rock, I see this is not yet implemented in 1.4.1. 
Should the milestone be updated to something else?

Is there any work being done already by someone else you are aware of?
I ask as I'd like to have this implemented and would be happy to contribute to this by working on it.

**Comment by walterdolce** [comment]
Probably related: given Inspec has ["Serverspec at the core"](https://blog.chef.io/2015/11/04/the-road-to-inspec/), were the [docker related resources implemented in Serverspec](http://serverspec.org/resource_types.html#docker_container) purposefully removed in Inspec? 
(given it's was initially an extension of Serverspec I assume all the resources available in Serverspec would be available out of the box)

**Comment by chris-rock** [comment]
@walterdolce InSpec is not using Serverspec anymore. Part of the docker resource got implemented here: https://github.com/dev-sec/cis-docker-benchmark/blob/master/libraries/docker.rb

**Comment by chris-rock** [comment]
@walterdolce Could you share the specific use case that you would like to run with InSpec. This helps to prioritize the work to get this into InSpec.

**Comment by walterdolce** [comment]
> InSpec is not using Serverspec anymore. Part of the docker resource [...]

I see. Thank you for clarifying.

> Could you share the specific use case

Sure. There are many use cases I can see. From simply verifying a container gets created and its status is asserted (just like you shown above), to going *in* the container and verifying what's _inside_ the container; or to verify two containers are linked; or verifying two containers are part of the same network; etc.

Some examples expressed in [Gherkin](https://github.com/cucumber/cucumber/wiki/Gherkin) language form below.
```
Scenario: docker container is created
   When I provision the node
   Then the docker container "app" is created

Scenario: docker container is running
   When I provision the node
   Then the docker container "app" is running

Scenario: correct version of ruby is installed within the container
   When I provision the node
   Then the "app" container has "ruby 1.9.3p551" installed
```

Hope it makes sense. I would also be happy to contribute if need to.

PS: out of curiosity: why was the code supporting the docker resources implemented in ServerSpec removed from/not used by InSpec?

**Comment by walterdolce** [comment]
Hmm. I think I'm having second thoughts regarding my contributions on this issue.
I suspect I'm treating InSpec as a normal testing tool in my context, while instead it's something which specifically targets security compliance related checks. Please correct me if I'm wrong.

What I wanted in my context is to verify the existence of one or more containers and from there develop more complex scenarios (is the container name correct? does it have i.e. Ruby version N? etc). 
And I think I could just use ServerSpec for that given my requirement is about verifying the existence of components and not whether the infrastructure I'm managing is complying with some security profile.

What do you think?

**Comment by chris-rock** [comment]
@walterdolce Thank you very much for the use case.

> PS: out of curiosity: why was the code supporting the docker resources implemented in ServerSpec removed from/not used by InSpec?

Those resources have never been part of InSpec. We rewrote all resources from scratch. We learned a lot from Serverspec. Defining resources in InSpec is much easier than in Serverspec. Also we allow users to define their own resources outside of the core project, which is especially useful in organizations that have custom applications. We implemented all resources based on demand. Therefore I am very happy to help you to get the docker resources into InSpec. 

> I suspect I'm treating InSpec as a normal testing tool in my context, while instead it's something which specifically targets security compliance related checks. Please correct me if I'm wrong.

InSpec is an integration testing and compliance tool. It is intended and developed for both use cases. You do not need to use the compliance features aka `controls` in InSpec. Therefore my recommendation is to use InSpec (although biased). This allows you to leverage the CLI, the extension mechanisms and the option to use compliance later.

**Comment by chris-rock** [comment]
@atomic111 Do you mind adding the docker resource from https://github.com/dev-sec/cis-docker-benchmark to core inspec. We could work from there then.

**Comment by walterdolce** [comment]
> Defining resources in InSpec is much easier than in Serverspec. Also we allow users to define their own resources outside of the core project, which is especially useful in organizations that have custom applications.

That's great. Am I right in saying this is not currently documented on the official InSpec website, though?
A quick googling gave me only [this](https://tech.spaceapegames.com/2016/09/23/custom-inspec-resources/) (which I haven't read yet). 

I think documenting how to create custom resources it will help boosting the proliferation of those made by the community and to have the same to be potentially merged into the core if you (core maintainers) find they will be of good quality/adopt best practices/etc. Again, I am more than happy to help if needed.

> InSpec is an integration testing and compliance tool. It is intended and developed for both use cases. You do not need to use the compliance features aka controls in InSpec. Therefore my recommendation is to use InSpec (although biased).

I'm glad to hear that, thank you very much. I was under the impression I was not on the right track. 
I think time and resources spent in learning/using/contributing to InSpec is a better investment because the tool has a company behind (Chef) and a whole community (as opposed to Serverspec, AFAIK).

Thanks a lot for the helpful and informative discussion so far. It's been of great value and I'm sure people looking here in the future will benefit from reading the conversation, too. 🍻

**Comment by walterdolce** [comment]
> Am I right in saying this is not currently documented on the official InSpec website, though?

I think I was wrong. I just went through the docs again and [I found this](http://inspec.io/docs/reference/dsl_resource/).
