### ISSUE TITLE
auditd_rules :lines resource not working correctly

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#710]
### Description

 I am using the following test to check one of the auditd rules configuration  and it passes with or without the rule configured.

describe auditd_rules do
    its(:lines) {
      should contain_match(/^exit,always arch=.\* key=audit_time_rules syscall=adjtimex/)
  }
 end
end

.### InSpec and Platform Version
 Inspec version = 0.19.3
auditd version 2.3.7
Platform: Centos 6.7

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
inspec version 0.19.3
### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
1. first delete the auditd rule that you are testing by using auditctl -d 
2. run the above test.
3. add the rule that you are testing by auditctl -a
4. run the same test again.
### Possible Solutions

The first time you run the test after deleting the rule it should fail and the next time you run the test after adding the auditd rule it should pass.
If you have already ideas how to solve the issue, add them here.
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by fcaviggia** [comment]
Here is some example code for testing:

```
describe auditd_rules do
  its('LIST_RULES') {should contain_match(/^[\s]*-a[\s]+always,exit[\s]+(?:.*-F[\s]+arch=(b32|b64)[\s]+)(?:.*-S[\s]+lremovexattr[\s]+)(?:.*-F\s+auid>=500[\s]+)(?:.*-F\s+auid!=4294967295[\s]+).*-k[\s]+[\S]+[\s]*$/) }
end
```

That code is based the regular expressions contained in scap-security-guide content here:

https://github.com/OpenSCAP/scap-security-guide/blob/master/RHEL/6/input/oval/audit_rules_dac_modification_lremovexattr.xml

**Comment by fcaviggia** [comment]
Additional code would be needed because the rules are architecture dependent (e.g. 32- or 64-bit):

``` ruby
if command('uname -p').stdout =~ /x86_64/
  describe file('/etc/audit/audit.rules') do
      its('content') {should match /^[\s]*-a[\s]+always,exit[\s]+(?:.*-F[\s]+arch=b32[\s]+)(?:.*-S[\s]+chmod[\s]+)(?:.*-F\s+auid>=500[\s]+)(?:.*-F\s+auid!=4294967295[\s]+).*-k[\s]+[\S]+[\s]*$/ }
      its('content') {should match /^[\s]*-a[\s]+always,exit[\s]+(?:.*-F[\s]+arch=b64[\s]+)(?:.*-S[\s]+chmod[\s]+)(?:.*-F\s+auid>=500[\s]+)(?:.*-F\s+auid!=4294967295[\s]+).*-k[\s]+[\S]+[\s]*$/ }
  end
else
  describe file('/etc/audit/audit.rules') do
      its('content') {should match /^[\s]*-a[\s]+always,exit[\s]+(?:.*-F[\s]+arch=b32[\s]+)(?:.*-S[\s]+chmod[\s]+)(?:.*-F\s+auid>=500[\s]+)(?:.*-F\s+auid!=4294967295[\s]+).*-k[\s]+[\S]+[\s]*$/ }
  end
end
```

**Comment by kdshah1** [comment]
Thanks, Frank for the workaround. Yes, I agree.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
