### ISSUE TITLE
Chef Compliance Server UI - Need capability to remove an uploaded profile

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#712]
### Description

Once we upload a custom profile, there's no way to remove it. I made some modification to a profile after uploading it and was trying to upload it again which was failing so wanted to remove the profile to start from scratch and there was no way to remove it. So adding that capability will help.

Briefly describe the issue and the expected behavior
### InSpec and Platform Version

Compliance Server Version 1.1.23
Inspec version: 0.20.1
Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
### Possible Solutions

If you have already ideas how to solve the issue, add them here.
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by dh2mom247** [comment]
+1

**Comment by alexpop** [comment]
Thank you for the request. Deleting profiles is available via the [Compliance API](https://docs.chef.io/api_compliance.html#delete), example:

```
curl -X DELETE "$API_URL/owners/john/compliance/ssh" -H "$AUTH"
```

Will try to include a `Delete` button in the Web UI in the next release. Thanks!

**Comment by alexpop** [comment]
A quick update. We've added a profiles delete button in the Web UI and will be available in the next release(planned for next week).

**Comment by kdshah1** [comment]
Awesome! Thanks for the update, Alex!

**Comment by alexpop** [comment]
We've just released a new stable Compliance package with this feature included:
https://discourse.chef.io/t/chef-compliance-1-2-3-released/8494

Thanks again for the feedback!
