### ISSUE TITLE
Chef Compliance UI performance

### ISSUE THREAD

**Issue by devopsrick** [inspec/inspec#713]
We are primarily using Compliance with the audit cookbook submitting to the Compliance server on every chef run.

After enough chef runs submit reports, the Reports tab in the UI becomes very slow/unresponsive due to it loading all reports over all time, rather than paginating after a certain number of results.

This behavior has persisted at least through 1.1.9, though I have not tested 1.1.23 yet.

**Comment by arlimus** [comment]
Sorry for the long wait on this ticket. We improved some of the UI performance in the course of development. Major pieces of new UI have landed with Chef Automate and we will upgrade the entire compliance story with a more lightweight implementation in a few months this year. I'm also closing this and let's move it to the company's bugtracker. Thank you!!
