### ISSUE TITLE
Return IP address of tested node

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#722]
### Description

I would expect, that inspec is providing an easy way to return the node ip address. This was reported by @cwebberOps 
### InSpec and Platform Version

InSpec 0.20.1
### Possible Solutions

At this point, a solution is to run a native command:

```
ip = command("ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'").stdout.strip
```

Serverspec is offering this via the `interface` resource:

```
describe interface('eth0') do
  its(:ipv4_address) { should eq '1.2.3.4/1' }
  its(:ipv6_address) { should eq '2001:db8::1234/1' }
end
```

I would expect the same for InSpec.

Aha! Link: https://chef.aha.io/features/SH-2392

**Comment by kraeml** [comment]
Litle off topic.

How could you test the variable _ip_?

**Comment by darkn3rd** [comment]
This would be nice to have, currently Inspec is not feature parity with ServerSpec for `interface`.  With ServerSpec, you can do:

```ruby
# serverspec
describe interface('eth1') do
  it { should have_ipv4_address('192.168.53.72') }
end
```

I would hope to do something similar with Inspec
```ruby
# Potential Inspec implementation
describe interface('eth1') do
  its('ipv4_address') { should eq '192.168.53.72' }
end
```

**Comment by jgrevich** [comment]
You can simplify the command to grab the ip address with 

```
ip = command("hostname -I").stdout.strip
```

**Comment by jgrevich** [comment]
Nvm, that still requires filtering as well. I didn't check other hosts. +1 for a helper method.

**Comment by xorima** [comment]
I am pretty sure this functionality is in the `interface` resource: https://www.inspec.io/docs/reference/resources/interface/
