### ISSUE TITLE
Chef Compliance Server UI - Need capability to remove reports

### ISSUE THREAD

**Issue by chef09210** [inspec/inspec#728]
### Description

Once we receive a Report, there's no way to remove it. Reports screen in Compliance UI fills up but no way to remove old reports.
### InSpec and Platform Version

Compliance Server Version 1.1.23
Inspec version: 0.20.1
### Possible Solutions

Add Delete button to Reports GUI

**Comment by chris-rock** [comment]
@chef09210 Thanks for the feedback. We scheduled this for our next releases. May I ask, why you would like to delete reports?

**Comment by chef09210** [comment]
Cleaning? The same reason I would want to delete e-mails? Is the request really that strange?

**Comment by clintoncwolfe** [comment]
As this is an old ticket, and the compliance UI is not part of InSpec, I'm closing this.  Thanks!
