### ISSUE TITLE
How to include helper methods in context to inspec file

### ISSUE THREAD

**Issue by viyew** [inspec/inspec#741]
### Description

Currently, self is passed into the helper method in order to be in the correct context.
### InSpec and Platform Version

0.21.3
### Replication Case

[Helper file](https://gist.github.com/viyew/6f930c790a253efadc0f27fff87be250)
[Spec file](https://gist.github.com/viyew/6f930c790a253efadc0f27fff87be250)

Run inspec exec on the spec file with the helper file in the same directory

This will work, but self needs to be passed into the helper method. Is there a better or cleaner way instead?

**Comment by chris-rock** [comment]
@viyew We recommend not to use spec or helper files. Instead we have a concept of custom resources: https://github.com/chef/inspec/blob/master/docs/dsl_resource.rst Is that helping?

**Comment by viyew** [comment]
It does, thanks!

**Comment by jorhett** [comment]
Explicit documentation for this purpose (node attributes) would be useful. Right now one has to struggle through a dozen different pages to figure this out :(

**Comment by chris-rock** [comment]
This should be documented in our Serverspec migration guide https://github.com/chef/inspec/issues/804

@jorhett Can you give us some hints of what is missing and add that to #804?

**Comment by PowerKiKi** [comment]
@jorhett what was the solution you used to access node attributes ?

**Comment by jorhett** [comment]
I used what was outlined in #541 but using a profile as described in #813 may be more consistent and appropriate for documentation
