### ISSUE TITLE
Better informational error message

### ISSUE THREAD

**Issue by dh2mom247** [inspec/inspec#742]
### Description

I was running inspec tests on a docker container, checking that the container was listening on a port. The container was running a minimal centos 7.1 but didn't include the netstat command so the test failed. It would be really helpful to know it failed due to missing command rather than not listening on the port (especially since I could access the UI on the port) 
### InSpec and Platform Version

Inspec version 0.21.3, container OS was a stripped down version of centos 7.1
### Replication Case

testing steps:

inspec exec test.rb -t docker://9323269a27c0 

test.rb is: 

```
describe file('/opt/kibana') do
  it { should be_directory}
end
describe port(5601) do
  it { should be_listening }
end
```
### Possible Solutions

Since docker containers may not have expected OS commands (netstat was not available on this image) it would be helpful to have the error return information if the command doesn't exists, versus a failure of the test itself. Maybe something like ERROR: netstat: command not found
### Stacktrace

result was: 

```
vagrant@localhost ~ $ inspec exec test.rb -t docker://9323269a27c0
.F

Failures:

  1) Port  5601 should be listening
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected `Port  5601.listening?` to return true, got false
     # test.rb:6:in `block (2 levels) in load'
     # ./.rvm/gems/ruby-2.3.1/gems/inspec-0.21.0/lib/inspec/runner_rspec.rb:65:in `run'
     # ./.rvm/gems/ruby-2.3.1/gems/inspec-0.21.0/lib/utils/base_cli.rb:68:in `run_tests'
     # ./.rvm/gems/ruby-2.3.1/gems/inspec-0.21.0/lib/inspec/cli.rb:111:in `exec'
     # ./.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
     # ./.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
     # ./.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
     # ./.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'

Finished in 0.29876 seconds (files took 1.17 seconds to load)
2 examples, 1 failure

Failed examples:

rspec  # Port  5601 should be listening
```

**Comment by tpcwang** [comment]
I have a similar example where it would be useful to print out the stderr when the command fails. The registry_key resource on Windows uses the ConvertTo-Json cmdlet to transfer the results to json, and that cmdlet isn't available on vanilla Windows 7 SP1 because it is using powershell 2 instead of powershell 3.

Having each resource types check the command explicitly doesn't seem to scale well. Perhaps we just need better logging for the powershell/command/etc resources?

**Comment by chris-rock** [comment]
I think we should get a better understanding why a test failed. Therefore we need to report the error in a better way. The challenge that we need to tackle: We want a simple result, so that we can easily see the overall picture, but we need a `debug` view that allows us drill down.

**Comment by chris-rock** [comment]
Thanks for reporting @dh2mom247 and @tpcwang for the additional comment. Both are very helpful

**Comment by tpcwang** [comment]
@chris-rock, python's nosetests handle these type of scenarios by capture stdout during test execution and printing it out if the test fail (or if the user specified --nocapture). This allows the user to get good error reporting without cluttering the output when the test passes. I'm not familiar with ruby and rspec-like test frameworks to know how well this would translate to inspec, but it might be something to consider.

**Comment by TD-4242** [comment]
In addtion to this I would really like to see some type of on_failure way to gather information such as:
```
describe service('app') do
  it { should be_enabled}
  it {should be_running || exec 'cat /var/log/app/app.log' }
end
```
there is likely better syntax to get the same result, but this would be very helpful to find out why the latest build on the CI server didn't start before it was terminated.

**Comment by IRobL** [comment]
Wait... so if I run my test, which is, say just checking if a container with a particular name exists:

```
describe docker_container('kafka') do
  it { should exist }
end
```

And when I list the containers on the VM, I see one named 'kafka' that exists.  

And when I run it, the test fails:

```
  $  inspec exec . -t blah..blah...
  ✔  tmp-1.0: Create /tmp directory
     ✔  File /tmp should be directory

  Docker Container kafka
     ×  should exist
     expected Docker Container kafka to exist
```

And the situation truely is, that there is no way to get any debug information from inspec to help me understand why a test I'm writing would produce a false negative?  I can't see how this could really be the case, but the way this conversation from 2016 ended makes me think that knowing what's going wrong with tests is considered a feature that is planned but hasn't been added yet.  Could someone add more information about this?  I feel like I'm probably missing something important that most people figure out early on as they learn InSpec.

**Comment by miah** [comment]
ref: #3174
