### ISSUE TITLE
etc_group and passwd resources are inconsistent

### ISSUE THREAD

**Issue by lamont-granquist** [inspec/inspec#752]
considering this bit of code:

``` ruby
describe etc_group.where(group_name: 'sysadmin') do
  its('users') { should include 'adam' }
  its('gids') { should eq [2300] }
end

describe passwd.filter(user: 'adam') do
  its('uids') { should eq ["666"] }
end
```

i'd expect:
- consistency around etc_group and etc_passwd (or without the 'etc_' but it looks like 'group' was used/will be used for something else..)
- consistency around `#where` vs `#filter`
- consistency in the uids/gids being either strings or integers

**Comment by lamont-granquist** [comment]
Now I seem to be getting:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #verify action: [undefined method `filter' for /etc/passwd:Inspec::Resource::Registry::Passwd]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

did this get fixed?  if so, docs need updating.

**Comment by chris-rock** [comment]
`passwd` has been updated to the new syntax https://github.com/chef/inspec/pull/699/files Can you point us to the documentation? `passwd.where(user: 'adam')` should work

**Comment by lamont-granquist** [comment]
looks like the docs just got updated:

https://github.com/chef/inspec/blob/master/docs/resources.rst#passwd

EDIT: no actually it looks like it still references `filter` in there.

**Comment by lamont-granquist** [comment]
also if i'm reading it right, this should work:

``` ruby
describe passwd.where(user: "adam") do
  its("uids") { should eq ["666"] }
end
```

but i'm getting:

```
  1) /etc/passwd with user == "adam" uids should eq ["666"]
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: ["666"]
            got: []

       (compared using ==)
```

another strictness issue is that its hard to tell if i'm getting the filter name correct or not:

```
  1) /etc/passwd with lksdjflksdjf == "adam" uids should eq ["666"]
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: ["666"]
            got: []

       (compared using ==)
```

identical error message...

**Comment by lamont-granquist** [comment]
this does work tho:

```
describe passwd.users('adam') do
  its("uids") { should eq ["666"] }
end
```

**Comment by clintoncwolfe** [comment]
refs #2983

**Comment by miah** [comment]
Going to close this in favor of #2983
