### ISSUE TITLE
Add support for alternate sudo command

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#755]
### Description

When an authorization layer such as Centrify is configured on a system a custom 'sudo' command can be required for sudo-like access.

We should be able to support this scenario and allow users to specify an alternative sudo command.

**Comment by jeremymv2** [comment]
There are 3 pull requests that together implement this ':sudo_command' feature.
- [x] Train: https://github.com/chef/train/pull/107
- [x] Inspec: https://github.com/chef/inspec/pull/754
- [x] Kitchen-Inspec: https://github.com/chef/kitchen-inspec/pull/86

**Comment by chris-rock** [comment]
This feature has been released in train 0.12 and inspec 0.22 and kitchen-inspec 0.14

**Comment by chris-rock** [comment]
```
inspec exec test.rb --sudo [--sudo_command ...]
```
