### ISSUE TITLE
Provide test via an http server or other.

### ISSUE THREAD

**Issue by andrewkrug** [inspec/inspec#761]
### Description

Instead of reading in a file on disk it would be nice to be able to drive inspec tests fetching test files from an http server or other central location.  Maybe there is a way to do this now and I don't know?
### InSpec and Platform Version

Latest.  Linux.

**Comment by chris-rock** [comment]
Is this something you are looking for?

```
describe http('http://app') do
    its('body') { should include('Hello Sinatra') }
    its('headers.content-type') { should eq("text/html") }
end
```

**Comment by andrewkrug** [comment]
Not quite.  I'd like to be able to do something like:  inspec exec http://centralstorage.example.com/test.rb -t ssh://user@hostname -i /path/to/key

**Comment by chris-rock** [comment]
@andrewkrug We support that for compliance profiles. You have multiple options. At first, you need to archive a profile.

```
$ inspec archive examples/profile
I, [2016-05-19T22:42:35.094969 #74529]  INFO -- : Checking profile in examples/profile
I, [2016-05-19T22:42:35.095032 #74529]  INFO -- : Metadata OK.
I, [2016-05-19T22:42:35.146661 #74529]  INFO -- : Found 5 controls.
I, [2016-05-19T22:42:35.146722 #74529]  INFO -- : Control definitions OK.
I, [2016-05-19T22:42:35.146891 #74529]  INFO -- : Generate archive /Users/chartmann/inspec/profile.tar.gz.
I, [2016-05-19T22:42:35.154526 #74529]  INFO -- : Finished archive generation.
```

Upload the tar to a webserver http://example.com. Now you can run the profile directly:

```
inspec exec http://example.com/profile.tar.gz
```

Other options you have:

### Use Chef Compliance as profile manager

```
# login to chef compliance
$ inspec compliance login ...
# upload a profile to chef compliance
$ inspec compliance upload examples/profile
# list all profiles available in Chef Compliance
$ inspec exec compliance profiles
# execute a profile from Chef Compliance locally
$ inspec exec compliance://admin/profile
```

### Use Chef Supermarket:

```
# list all profiles
$ inspec supermarket profiles
# execute a profile from supermarket
$ inspec exec supermarket://hardening/ssh-hardening
```

### Run profiles from github

```
https://github.com/dev-sec/tests-ssh-hardening
```

**Comment by clintoncwolfe** [comment]
This appears to be answered.  If you need more information, please feel free to re-open!
