### ISSUE TITLE
support docker container testing to be completed on the docker host only (not in the container) using the docker inspect command

### ISSUE THREAD

**Issue by dh2mom247** [inspec/inspec#763]
### Description

Currently we have issues when running compliance testing against docker containers that don't have the expected toolsets (ex: issue #742). Could we provide an option to instead run container tests on the docker host (not in the container) using docker inspect [container_id]? 

Something like this:

   inspec exec test.rb -hostonly -t docker://container_id

and the results would be based on the values in the output from "docker inspect container_id"

Determining the container id is one potential difficulty and I'm sure there are others but thought I'd throw this out as a possible solution (I'd be happy to work on this if it's feasible)

**Comment by chris-rock** [comment]
@dh2mom247 sure, you can do that.

```
$ cat trials/docker.rb 
control 'docker-1' do
  title 'check that container are running'
  # get inspec data
  ids = command('docker ps --format "{{.ID}}"').stdout.split
  ids.each do |id|
    # get data
    raw = command("docker inspect #{id}").stdout
    # hack, json resource need to be able to load content from string properly
    info = json('').parse(raw)
    # check that each container is running
    describe info[0] do
      # should be its("State.Running") { should cmp 'Running'}
      its(['State','Running']) { should cmp true}
    end
  end
end

```

If you execute the test it would look like

```
$ inspec exec trials/docker.rb
.

Finished in 0.00075 seconds (files took 0.53209 seconds to load)
1 example, 0 failures

```

Is that what you are looking for?

**Comment by chris-rock** [comment]
We need docker resources for InSpec land. PRs are welcome to add some :-)

```
describe docker_container('example') do
  it { should exist }
  it { should be_running }
end

describe docker_image('alpine:latest') do
  it { should exist }
end
```

**Comment by dh2mom247** [comment]
I like this idea (should have thought of the more simple answer) - thanks for the response!

**Comment by chris-rock** [comment]
Please have a look at https://github.com/dev-sec/cis-docker-benchmark, especially https://github.com/dev-sec/cis-docker-benchmark/blob/master/libraries/docker.rb Once we have our dependency management in place, it will be really easy to consume the same resource in different profiles

**Comment by johnjelinek** [comment]
any updates on this?

**Comment by chris-rock** [comment]
With InSpec 1.21.0 we introduced a docker resource. This is documented here: https://www.inspec.io/docs/reference/resources/docker/ A walk-through is available here: http://lollyrock.com/articles/inspec-for-docker/
