### ISSUE TITLE
json / yaml / ... resources vs parse_config for files and strings

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#771]
The current set of resources for parsing (json, yaml, csv, ...) are focused on files:

``` ruby
json('my.json')
```

They don't support parsing strings, e.g. from commands.
(A workaround by @chris-rock is found here: https://github.com/chef/inspec/issues/763#issuecomment-220469834 )

On the other hand, our simple config parser is supports both modes, but targets strings by default + carries a (imho strange) file handler with:

``` ruby
parse_config( ... raw data ... )
parse_config_file('my.config')
```

It would be great, if we (1) simplify resources to do a small task and do it well and (2) unify that data-vs-file between parse_config and the other resources.

**Comment by arlimus** [comment]
(A) One potential solution to this problem might be:

``` ruby
json.file('my.json') ...
json( ... raw data  ... )
```

This ^^ would leave the code very lightweight. e.g. `#file` would come via a mixin and work for all resources + handle errors and edge-cases.

(B) Another idea is to defer file-handling to a ruby-only solution:

``` ruby
json(file('abc').content)
```

and make json read only parseable data. The problem with ^^ is error and edge-case handling, which would effectively get swollowed down the line.

**Comment by mhedgpeth** [comment]
What if when you process the string input to json you try it as a file & if that doesn't work run it as a command. A convention over configuration design would be best from the user's perspective. Make them work only if they do the edge cases.

```
json ('C:/temp/myFile.txt') do # reads a file
end

json('echo "start { value: good }"') do # runs command

end
```

I'd say always make it harder on the coder, never on the writer. You code once, you write many times. :)

**Comment by chris-rock** [comment]
I think this raises a general question, since we may want every resource that deals with content be able to load content from a string or from a file. Personally I would prefer to implement this without any magic.

```
json( ... raw data  ... )
json.file('my.json') ...

parse_config( ... raw data ... )
parse_config.file('my.config')
```

We could also do 

```
json.load( ... raw data  ... )
json('my.json') ...

parse_config.load( ... raw data ... )
parse_config('my.config')
```

Just for reference, Ruby is doing it as following:

```
JSON.parse('{"hello": "goodbye"}')
JSON.parse( IO.read(filename) )
```

cc @aaronlippold

**Comment by arlimus** [comment]
@chris-rock Interestingly ruby has `JSON.load` too, fyi. But yes, this ticket has the purpose to raise the general problem + resolve the conflicts we have in our current resources. afaics either proposed way is good, as long as it is consistent across all resources. Defaulting to `resource('filename')` would help with the current handling, as it would only require `parse_config` to change.

@mhedgpeth That convention should work for json in most cases, as the edge-case of having a filename look like a valid json is very rare. However, it breaks with `yaml` or even `parse_config`:

``` ruby
YAML.load('my.config') # if the file exists
=> { param: value ... }

YAML.load('my.config') # if the file doesn't exist
=> "my.config"         # it returns a string
```

With `describe`-blocks this would result in tests that would fail, if the file wasn't available. But this underlying problem (i.e. the file is missing) is hidden in the context and may be harder to track down:

``` ruby
describe yaml('my.config') do
   its('param') { should eq 'enabled' }
end
```

In this example ^^ we would see `YAML 'my.config' param should be 'enabled', but is nil`, which could point to either (1) the parameter in that file is not configure or (2) the file doesn't exist.

**Comment by chris-rock** [comment]
We could also use an option hash argument:

```
describe yaml('my.config', type: 'file') do
   its('param') { should eq 'enabled' }
end
```

But this approach introduces a programming style that we may not want to have in InSpec

**Comment by mhedgpeth** [comment]
I'm a big confused, where would the string come from? The way I interpreted this, you would either have a file or a command output be the source of your yaml resource. In that sense you could even do it kind of like chef does:

``` ruby
describe yaml('my.config`) do
  source :file # default, if ommitted this is what it gets
  its('param') { should eq 'enabled'}
end

describe json('curl http://localhost:8080/api-call`) do
  source :command # takes the stdout of the command
  its('param') { should eq 'enabled'}
end

describe json('http://localhost:8080/api-call`) do
  source :url # gets the contents of the http return
  its('param') { should eq 'enabled'}
end

describe yaml('config`) do
  source :string # takes the string name
  its('param') { should eq 'enabled'}
end
```

This is without me knowing how I would implement that, but that's probably a good thing.

**Comment by nvtkaszpir** [comment]
Sigh, wasted a bit time today because of this issue. The fact that json() expects a file and not a string was a bit confusing. Did not want to use a hack presented in #763 comment, though... 

Now I'm using kinda 'retarded way' command with output to file and then later on load that json file, for example:

```ruby

control 'docker-info-deferred-removal-enabled' do
  impact 1.0
  title 'docker info Deferred Removal Enabled'
  desc 'docker info Deferred Removal Enabled should be set to true'
  cmd = 'docker info --format \'{{ json . }}\' > /tmp/inspec.docker.info.json'
  out_o = command(cmd).stdout
  out_e = command(cmd).stderr
  out_x = command(cmd).exit_status

  describe json('/tmp/inspec.docker.info.json') do
    its(['DriverStatus']) { should include(['Deferred Removal Enabled', 'true']) }
  end

end
```

Kinda ugly, leaves some content after tests but works.

**Comment by clintoncwolfe** [comment]
Per https://www.inspec.io/docs/reference/resources/json/, you can now use 
```
describe json(content: '{"item1": { "status": "available" } }') do
 # your tests
end
```
YAML has similar support.
