### ISSUE TITLE
File Checksum and Content incorrect with Test Kitchen

### ISSUE THREAD

**Issue by DPD-30** [inspec/inspec#787]
### Description

The InSpec FILE resouce seams to be adding 2 CRLF characters to the end of a file accessed on remote machine.  This does not happen when run against the local machine.  inspec exec works.  kitchen verify fails.  Bellow are the results.  Look at failure 3 results that show the extra \r\n\r\n in the content.  I have verified that those are not present in the file.  If i add them and do a seperate checksum I get the  0b55 result.  Which tells me that yes this is the cause of the checksum issue.  Note this also happens with binary files. 
## inspec exec results

.....

Finished in 0.011 seconds (files took 7.33 seconds to load)
## kitchen verify results

-----> Starting Kitchen (v1.7.3)
-----> Verifying <default-win2012r2>...
       Detected alternative framework tests for `inspec`
       Detected alternative framework tests for `serverspec`
       Search `C:/localdev/chef/test123/test/integration/default/inspec` for tests
..FFF

Failures:

  1) File c:\temp\test.txt sha256sum should eq "2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

```
   expected: "2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c"
        got: "0b557d70e804e60d9cbe7e206507c8c87fded6b7d917fc49c1d4ca5a916f0f9a"

   (compared using ==)
 # ./test/integration/default/inspec/test123.rb:18:in `block (2 levels) in load'
```

  2) File c:\temp\test.txt sha256sum should eq "2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

```
   expected: "2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c"
        got: "0b557d70e804e60d9cbe7e206507c8c87fded6b7d917fc49c1d4ca5a916f0f9a"

   (compared using ==)
 # ./test/integration/default/inspec/test123.rb:19:in `block (2 levels) in load'
```

  3) File c:\temp\test.txt content should eq "this is a test"
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

```
   expected: "this is a test"
        got: "this is a test\r\n\r\n"

   (compared using ==)

   Diff:
   @@ -1,2 +1,3 @@
    this is a test
   +
 # ./test/integration/default/inspec/test123.rb:20:in `block (2 levels) in load'
```

Finished in 16.79 seconds (files took 0.54161 seconds to load)
5 examples, 3 failures

Failed examples:

rspec  # File c:\temp\test.txt sha256sum should eq "2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c"
rspec  # File c:\temp\test.txt sha256sum should eq "2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c"
rspec  # File c:\temp\test.txt content should eq "this is a test"

---
### InSpec and Platform Version

inspec version 0.18.0
### Replication Case

Create a file with notepad that contains "this is a test".  No quotes no CRLF created on a windows 2012r2 box run in virtualbox using testkitchen.   When you run kitchen verify it fails.  Create the same file on the local box and run chef exec inspec exec and it passes.  
## Tests being run.  

require 'digest'
# this checksum was calculated with two differnt programs both gave the same results with an
# ASCII text file that contained "this is a test".  No quotes or cairage returns.
# File created on windows.

thechecksum = '2e99758548972a8e8822ad47fa1017ff72f06f3ff6a016851f45c398732bc50c'
# using ruby digest you get the expected checksum.
# note this only works on the local machines file.

digest_sha256 = Digest::SHA256.file("c:\temp\test.txt").hexdigest
describe digest_sha256 do
  it {should eq thechecksum}
end
# using file and sha256sum from inspect you get a differnt value.
# content check shows why.  Somewhere a pair or CRLF are being added.

describe file('c:\temp\test.txt') do
  it { should exist}
  its(:sha256sum) { should eq thechecksum}
  its(:sha256sum) { should eq digest_sha256}
  its('content') { should eq 'this is a test'}
end

---
### Possible Solutions

find and remove the cause of extra CRLF being added when using kitchen.

**Comment by chris-rock** [comment]
@DPD-30 Thanks for reporting. Have you experienced with Linux/Unix as well? If not, I assume this has something to do with inspec/train/winrm interaction.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
