### ISSUE TITLE
Transport error while trying to ssh to mac osx 

### ISSUE THREAD

**Issue by Cashwini** [inspec/inspec#788]
### Description

Execution of inspec for mac osx fails with transport error
### InSpec and Platform Version

InSpec version 0.23
### Replication Case

Run **_inspec exec -t ssh://username@macip -i password_**

**Comment by chris-rock** [comment]
@Cashwini do you use the mac ssh server or another one from brew and co?

**Comment by Cashwini** [comment]
I use mac ssh server. I have the same problem when I try to scan mac node from Chef compliance server

**Comment by chris-rock** [comment]
I can confirm the issue, this requires a fix in train. The reason is the missing `keyboard-interactive` ssh auth method.

**Comment by chris-rock** [comment]
This is fixed via https://github.com/chef/train/issues/111. It will be available in InSpec 0.24
