### ISSUE TITLE
Proposal: inspec download/report to streamline how profiles are downloaded/reported

### ISSUE THREAD

**Issue by mhedgpeth** [inspec/inspec#798]
# Summary

Streamline how profiles and their dependencies get downloaded by adding a `download` subcommand to `inspec` that all use cases (including compliance during a scan) use. Also add a `report` function for uploading report results to a compliance server.
# Problem

Within the inspec/compliance infrastructure there are multiple ways that inspec runs for different purposes:
1. **Scanning**: running on the compliance server against locally available profiles
2. **audit Cookbook**: running with the `chef-client` run
3. **locally**: during development of a profile
4. **Test Kitchen**: to test that a cookbook meets our expectations.

The cookbooks that each of these use can be accessed a variety of different ways:
1. **local file system**: the only way to run scanning or do it locally
2. **Chef Server** through the audit cookbook
3. **Compliance Server** through the `audit` cookbook, Test Kitchen
4. **Supermarket** through test kitchen or the `audit` cookbook
5. **GitHub** through test kitchen or the `audit` cookbook

This is all very wonderful, but the complexity of which storage options go with which delivery options is too confusing.

This also creates a nonstandard approach to running profiles, as evidence in the overly complicated `audit` cookbook.
# Proposed Solution

I propose that all mechanisms go through a _single workflow_ that:
1. "Downloads" a profile to a cache location on the machine, whether `inspec` is running on the Complianc Server, `audit` cookbook, test kitchen, or even locally
2. All dependent profiles are recursively downloaded to the cache location in a consistent way, so they are locally available
3. The `inspec exec` command runs against this cache location.

Let's go over how this would work in the various environments:
1. Chef Compliance: there would be a separation between the "repository" function of Compliance and the "scanning" function. A separate directory location on the Compliance Server would run `inspec` during a scan and "download" the profiles from itself. On the surface this would seem like a formality, but it drives consistency up by forcing the server to play by the same rules as the other clients below. And it properly creates a client/server relationship between `inspec` and the Compliance Server from a coding standpoint. This will make everything easier and more consistent.
2. `audit` cookbook: this proposal greatly simplifies the `audit` cookbook by removing its responsibilities to connect with the Chef Server/Compliance Server. The cookbook then becomes a very easy wrapper to the `inspec` tool itself. It downloads profile(s) to the cache location and then runs them. Then it uploads the json file to the chef server (which, by the way, should also be a `compliance` function)
3. Test Kitchen: this makes test kitchen easier too. You can build a structure that describes what profiles are needed and then retrieve them from the node. Complexity is driven towards the `inspec` tool, which is where it belongs.
4. Locally: it's tempting to do things the way they've been with running a test against a file that someone just edited for local stuff. But that gets more complicated when dealing with dependencies. It seems like it would be easy to copy it all to a cache folder and thus you have a single streamlined process for everything.

So there would be two new commands to inspec:

`inspec download 'base/windows' --server 'https://mycomplianceserver' --cache-directory 'compliance/cache'`

or in a more complicated use case:

`inspec download 'supermarket://dev-sec/cis-docker-benchmark' --server 'https://chefserver' --cache-directory 'compliance/cache'`

And then for reporting:

`inspec report 'windows.json' --server 'https://chefserver'`

@chris-rock and @anniehedgpeth this is a better written out version of what we were talking about this morning. @jeremymv2 I'm going to try to go down this path instead of make the `audit` cookbook even more complicated than it already is for profile inheritance.

**Comment by mhedgpeth** [comment]
Another motivation for this issue is that the `audit` cookbook isn't easily testable without a broad infrastructure to support it. So we should migrate things to `inspec` and let the audit cookbook be a simple client to `inspec`. We should drive the use cases that the `audit` cookbook uses to the other parts (scanning and running locally).

**Comment by chris-rock** [comment]
@mhedgpeth This is a great summary and related to https://github.com/chef/inspec/issues/533. I think we are already good with inspec/kitchen-inspec relationship, since kitchen-inspec is `just` the kitchen wrapper for inspec. All tasks are handed over to inspec.

The goal is that the audit cookbook will work similar to kitchen-inspec. As discussed with @jeremymv2 already, our intention is to move the compliance api bits from the audit cookbook to the `inspec-compliance` plugin. This allows us to have one place where all api calls are implemented.

Chef Compliance already plays by the same rules, since its using inspec as its engine. I agree that it currently makes some tasks easier like handling profiles and profile inheritance. I also see the need to ease the process to run those inherited profiles with InSpec Cli without the need to understand all details. This will be addressed with https://github.com/chef/inspec/issues/533

**Comment by mhedgpeth** [comment]
@chris-rock thanks for the update. This is a valuable discussion for me. 

I think your approach to dependency management will affect the need for this feature. Consider this use case:

Team 1 wants to inherit profile A, version 1.0
Team 2 wants to inherit profile A, version 2.0

When Team 2 uploads v2.0 of Profile A, Team 1 gets unexpected failures.

This highlights the need (in my mind) of building the dependencies into the profile at a "build" time. This is similar to how policyfiles work in chef. When a profile is built and a dependency is asked for, _embed_ that dependency in the profile and submit _that unit_ to the compliance server. That way all profiles are independent, repeatable, and consistent throughout their lifecycle.

If you do it this way, then you're right, the compliance server doesn't need to change. It also makes the _runtime_ of the compliance server simpler by not exposing the scan to anything outside of the profile.

At the same time, I'm not clear on why you want to move all the bits to the `inspec-compliance` plugin. Why not to `inspec` itself? If you do that, then testability is much simpler. For example, I don't know of a way right now to test chef server connectivity using kitchen. In fact, we're keeping people from running the `audit` cookbook in their test kitchen runs because of this. The compliance server connectivity could be tested, but why not streamline it all within `inspec` and let the other gems/clients have a simple interface into it?

**Comment by chris-rock** [comment]
@mhedgpeth I think we talk about the same and think about different implementations. I would like to drive the discussion to be more use-case driven. We can derive the technical solution from there. I fully agree with you, that the consumption of profiles need to be harmonized. Especially for profile inheritance, the ease of use requires further improvements.

To solve the problem, I think that InSpec needs:
- profile vendoring (downloading all required asset)
- versioning for profiles

Those two points are part of our implementation for dependency management. By having these two methods established, the team 2 can easily use inherit version 2 without affecting team 1. Also it would make the behavior and usage the same across InSpec, Compliance, kitchen-inspec and audit cookbook. Does that make any sense? 

PS. audit cookbook can also be used with test-kitchen. We use this approach to test the audit cookbook with Compliance: https://github.com/chef-cookbooks/audit/tree/master/examples/kitchen Nevertheless I believe, that for most usecases (may not be yours) its better to use kitchen-inspec to verify a converge in test-kitchen. It is a prober extension for kitchen and works well with various kinds of kitchen plugins e.g kitchen-docker, kitchen-puppet, kitchen-ansible and various drivers.

**Comment by mhedgpeth** [comment]
@chris-rock you should talk with @danielsdeleo about his policyfile work and versioning of cookbooks. What you'll find is that versioning, by itself, is not a sufficient mechanism for dependencies. Instead the _content_ of the profile should be the version. If there is a way, like with policyfiles, for you to upload the content hash to the compliance server and _build_ the profile with a hard dependency to that content and where it came from, that would be ideal. This solves the use case:

> I want to trust that the profile we are running is _exactly the same_ as the one we uploaded. This includes dependencies.

If there is _anything_ that can change that, trust is eroded, and in security software it's game over.

Another use case that policyfiles really help for us with the `chef export` command:

> I want to be able to download a profile and all its dependencies into a tar file and upload it to another compliance server

This is needed because we have different compliance servers and will need to manage promotions between them. This is why we use a Policyfile archive that vendors _all_ cookbooks from a previously known _content-driven_ state (NOT the version number).

And I'll throw one more in:

> If I have a Chef Server integration issue with compliance, I want to easily debug it

I struggled with this earlier and is one of the motivations for the `inspec download` command. Don't make me make some changes to the audit cookbook, upload them to the chef server, run the node (keep in mind I have to _identify a node for testing_ as well). Let me run a simple test on something that shows me that I have Chef Server integration working. That part should be easy.

**Comment by mhedgpeth** [comment]
Let me also get a little philosophical about dependency management differences between development and infrastructure.

With development, it's cool to say "depend on this gem here, version X". It's cool **because** you build the thing very early on and promote it through the whole process.

The problem comes with infrastructure when you **don't** build the thing, but keep the cookbooks separated. In those situations, unlike with development stuff, you have something that _only_ runs together for the first time in production. So with infrastructure dependency management you need to provide a mechanism that is build-like for dealing with artifacts. For chef, this is either policyfiles or using delivery. For inspec it has to be a non-version driven, content-based hash that represents that version of the policy connected with other policies through dependencies. With that model you could support the use cases stated above.

**Comment by chris-rock** [comment]
@mhedgpeth Thanks for writing up the validation for our current approach. Our system will not rely on classic version numbers. Instead we opt for the git model, where each change creates a new version aka sha sum automatically. Classic versioning like 1.2.3 is only a tag to a unique sha version and eases the usage for users. Under the hood though, we always will rely on sha sums to uniquely know the specific version we depend on.

**Comment by mhedgpeth** [comment]
@chris-rock that's fantastic. Then to make sure here's what we need to support:

> I want to declare dependencies from github, the supermarket, a compliance server, or locally

This would be in the `inspec.yml` file like this:

``` yaml
depends:
  - https://github.com/anniehedgpeth/inspec-workshop
```

> I can create a snapshot in time of what these dependencies really are, which are based on their SHA hash. The output of this snapshot is a file I can check into version control.

So perhaps I would call `inspec profile install` which would generate an `inspec.json.lock` file with content like this:

``` json
"dependencies": {
    "inspec-workshop": {
        "source": "https://github.com/anniehedgpeth/inspec-workshop",
        "revision": "5e0972c497786b6772aa0a9e13a7892255cf4376",
        "version": "1.3.4",
        "identifier": "1f6c8e5006a81a2a6fdd154a127fcbcfc527288d"
      }
   }
```

If I were to revert source to this version of the profile, I could retrieve _the exact same dependencies_ that I retrieved that day. This satisfies my need for reproduction of a profile build from the code itself and allows me to manage a profile pipeline through the various stages.

> I want to upload this profile with sha2 dependencies to a compliance server

This is with the existing command, but now it would also upload the dependent profile (if it is not already available) as well and ensure that the correct dependency was used. With the policyfile feature, the lock file is also given to the server and provided to the clients as a manifest, which then ask for version 'ABC123' (hash) of each dependency. This reduces load on the server and I think is the better way.

> I want to package a profile with dependencies to a single file

This might be related to commands above but it's important that I can create a _transferrable unit_ that represents the profile so I can move it to another segregated environment as a file transfer. This segregated environment _might not_ have any connectivity to the supermarket or github, so the file that is created here would have to contain all dependencies.

> I want to upload a generated profile package file to a compliance server without accessing any dependencies

This is where we will be inside of a very secure environment where we just copied the policy package file over and then run an upload command. This should work as well.

This roughly copies the policyfile feature that @danielsdeleo worked on and applies it to profiles in compliance. I think this is the right model, because (1) you've already implemented it, so for at least some it will be familiar, (2) it supports predictable dependency management that can be versioned in git, and (3) it supports isolated environments that don't have connectivity to original dependencies.

**Comment by arlimus** [comment]
Hi everyone, wow you are having an awesome discussion in here!! Quick additions since I'm currently implementing this feature:
- there will be a separate lockfile; the resolved list of dependencies will not be added to `inspec.yml` (unless we find reasons to combine it; discussion welcome)
- there will be a vendor feature, which will allow packaging a or a number of profiles; this will also allow for an easy transfer via one file
- dependencies can be local, supermarket, github, chef compliance, or anything else that inspec supports
- inspec will cache dependencies locally before execution

**Comment by mhedgpeth** [comment]
@arlimus thanks for the reply, that approach looks great. In my mind the lockfile needs to be 100% generated, which helps us ensure that it was not tampered with. In fact, as with policyfiles, it's a good idea to make the lockfile content _itself_ have a hash so you know there was no tampering. I believe that's what policyfiles do too.

**Comment by arlimus** [comment]
@mhedgpeth huge :+1: 
Also, once it is generated, the lockfile can be transfered and re-used to get reproducible results. The hashsum can guarantee it is not tempered with and in the mid-term we'll find a way to address signing in inspec as well :smile:

**Comment by chris-rock** [comment]
As a reminder, why flat dependency resolution is preferred: https://github.com/npm/npm/releases/tag/v3.0.0

**Comment by err0** [comment]
I'd love to see this as `inspec compliance download PROFILE` as a counterpart to `inspec compliance upload PROFILE_PATH`

**Comment by jaybrueder** [comment]
Any updates to this?

**Comment by chris-rock** [comment]
We are currently wrapping up InSpec 1.0. Its on the roadmap, once its finished.

**Comment by arlimus** [comment]
@jaybrueder We will complete this in the next couple of weeks (<4weeks). An early version for experimentation will be up soon.

**Comment by arlimus** [comment]
Current progress and design discussion is tracked here: https://github.com/chef/inspec/issues/888

**Comment by miah** [comment]
We believe this is all handled through the vendor command and various reporters, if we are mistaken please reopen.
