### ISSUE TITLE
DISCUSS: Extend inspec exec report summary

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#817]
The `inspec 0.26.0` execution report contains the following format:

``` json
$ inspec exec test.rb --format json
{
  "version": "0.26.0",
  "summary": {
    "duration": 0.011863,
    "example_count": 10,
    "failure_count": 3,
    "skip_count": 3
  },
  "profiles": {
    "profile1": {
...
```

Would be helpful for the json report to provide a scan summary of the controls based on impact. For example:
-  1 failed with criticality of 0.3
-  2 failed with criticality of 0.454
-  4 successful with criticality of 1.0
-  3 skipped with criticality of 0.7

These reports are eventually stored and indexed for future searches and reporting.
Extending the summary will allow node overview queries and aggregations across multiple nodes(potentially thousands) to only look at this summary data instead of having to retrieve and traverse the `profiles` hash. The report generated from running the `cis-centos6-level2` profile, contains a `profiles` field of 750KB in size and 8100 lines of json.

**Comment by miah** [comment]
I think this would be handled through: ref: #3667
