### ISSUE TITLE
Inconsistency with indifferent access

### ISSUE THREAD

**Issue by xTNTx** [inspec/inspec#820]
### Description

Inspec handles options as `HashWithIndifferentAccess` when it comes from [CLI](https://github.com/chef/inspec/blob/master/lib/utils/base_cli.rb#L93). It's not the same when options are passed as legacy Hash from another script, e.g. [from kitchen-inspec](https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L42-L47) verifier. It makes option keys inaccessible when created as symbol but requested as string and vise versa.
### InSpec and Platform Version
- inspec-0.26.0
- kitchen-inspec-0.14.0
### Replication Case

Issues #813 and https://github.com/chef/kitchen-inspec/issues/92 describes one of replication cases, when Inspec audit resource is placed outside of control. It happens because profile option [can't be accessed via string key](https://github.com/chef/inspec/blob/master/lib/inspec/runner.rb#L126-L128) while it [was created as symbol](https://github.com/chef/inspec/blob/master/lib/inspec/runner.rb#L97). As a reminder - in those cases 'options' is just a legacy hash which is passed from `kitchen-inspec`
### Possible Solutions

I'm not sure in concept of fix that should be applied. Should we convert options to indifferent hash in each public `Runner` method as a hotfix? Or there can only complex refactoring of how options are handled?

**Comment by atomic111** [comment]
i got the same issue with postgres_conf.params['data_directory']. i used this in the postgres profile. if i execute it with inspec exec, everything works as expected. but if i use kitchen verify then i get two results: one is `/var/lib/postgresql/9.4/main` and the other value is `nil`.

thanks @xTNTx for the temporary fix `format: progress`. this works for me

**Comment by xTNTx** [comment]
Particular case is fixed by #828 . But it still not secure from differences in other keys.

**Comment by kekaichinose** [comment]
This issue has aged. If you're still experiencing a problem, please open a new issue with repro steps applicable to the current version of InSpec.

Thanks!
__Chef InSpec Team__
