### ISSUE TITLE
RFC - System Security Plan and InSpec

### ISSUE THREAD

**Issue by pburkholder** [inspec/inspec#829]
Hi Inspec Folks,

Welcome back from ChefConf; I hope you had a great time!

In the last few weeks I’ve been working in the FISMA/FedRAMP space to help a client better build out the System Security Plan (SSP) that’s needed to obtain the Federal “authority to operate” in a cloud provider.

To that end, there’s a general need to automate the generation of SSPs that is:
- Composable: can be generated by aggregating how individual components meet the various controls within a standard
- Reusable: can be built by customizing an existing description of a component or system. For example, I should be able to use someone else’s published ELK stack description with some level of customization, w/o just doing copy & paste.
- Verifiable: Embeds something like InSpec that can verify whether the current system state is compliant with its own description
- Interrogatable: Can be queried, or can can generate a system description as, say, HTML or via a Word Doc template. 

Oh, yes, and comes with ponies and rainbows.

I’ve been working some with OpenControl and Compliance-Masonry in this space, and while they are better then a manual process, I’m not convinced that that approach gets much beyond the ‘composability’ question, as the YAML for each component is not designed for easy re-use..

So, with that long intro: Have you been working on, or are you aware of, compliance report generation systems that have some of the features described above?  Have you thought about how InSpec could tie into something generating rich system descriptions? If so, is there work underway to which I could contribute?

cc: @aaronlippold @mhedgepeth
ref: #798 #564 #563

**Comment by mhedgpeth** [comment]
From what I understand about it inspec's job is to give you a structured json response to a test run that can be fed into any system. The json includes the text of the test itself. Have you looked at whether that fits your needs?

Also to make the profiles truly composable we need dependency management, which I'm told will be worked on in the short term.

**Comment by clintoncwolfe** [comment]
This issue hasn't been touched in a while, and I don't know what inspec was like in 2016.  Today, we have vendoring, many different reporters, and profile inheritance.

I think we have covered everything asked for.  Please re-open if you disagree.

**Comment by aaronlippold** [comment]
Actually this is still something we need to work out a little bit. I think in the next few months we will actually have some good answers around how we think these two tool chains could work together.  Fundamentally the alignment comes from tagging of 800-53 controls to the inspect tests and then doing a data transform to help push the results though results through to the compliance masonry details and status sections of the yaml files. The only part inspect could play in this would be perhaps a reporter than output specifically tailor to the ingested by compliance masonry. For anyone interested in this I believe we should outline the boundaries more directly in another PR and work it there.

**Comment by pburkholder** [comment]
I agree it makes sense to close this and take the work to a PR.
