### ISSUE TITLE
cli reporter: choose stoplight colors based on impact

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#839]
As reported by @alexpop : Coloring on some CLIs seems off between critical and major.

What it currently looks like:

![screenshot from 2016-07-22 12-50-30](https://cloud.githubusercontent.com/assets/1307529/17055083/ec4fb1fc-500a-11e6-9a65-eed6e907e9b6.png)

We had a session discussing 256 colors this morning as well.

![screenshot from 2016-07-22 12-47-52](https://cloud.githubusercontent.com/assets/1307529/17055089/f52b7298-500a-11e6-922d-b2c6ed959ec1.png)

Would love to get Mark into this discussion and see his take on everything.

**Comment by chris-rock** [comment]
I prefer the second version! Great improvement @arlimus

**Comment by alexpop** [comment]
My vote goes for `#2` as well

**Comment by aaronlippold** [comment]
#2 👍

**Comment by fcaviggia** [comment]
#2 :+1:
