### ISSUE TITLE
`inspec` binary occasionally exits zero on SSH failures

### ISSUE THREAD

**Issue by schisamo** [inspec/inspec#840]
### Description

If the underlying `ssh` command/transport has an error the `inspec` binary still exits zero. This can prove problematic when CI/CD is driving `inspec` as the job will be marked as green when it actually failed because of underlying config issues.

```
$ inspec exec inspec/package-router-smoke -t ssh://ubuntu@package-router-0-acceptance.es.chef.co -i ~/.ssh/es-infrastructure.pem
ssh: Could not resolve hostname bastion-verify.es.chef.co: nodename nor servname provided, or not known
$ echo $?
0
```

In the scenario above a `ProxyCommand` is configured in `~/.ssh/config` BUT inadvertently pointing at a non-existent bastion/gateway host:

```
Host package-router-*-acceptance.es.chef.co
  ProxyCommand ssh -A ubuntu@bastion-verify.es.chef.co -W %h:%p
```

A similar "raw" `ssh` command does return a non-zero exit code:

```
$ ssh ubuntu@package-router-0-acceptance.es.chef.co
ssh: Could not resolve hostname bastion-verify.es.chef.co: nodename nor servname provided, or not known
ssh_exchange_identification: Connection closed by remote host
$ echo $?
255
```
### InSpec and Platform Version

```
InSpec version: 0.27.1
Train version: 0.15.1
```

**Comment by chris-rock** [comment]
fixed by https://github.com/chef/train/pull/130, will be included in the next version of train

**Comment by schisamo** [comment]
![gif-keyboard-6890706418199973053](https://cloud.githubusercontent.com/assets/6164/17743604/38b70538-6472-11e6-9d26-98f929f8d0eb.gif)
