### ISSUE TITLE
Document all supported Operating Systems

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#842]
### Description

The InSpec readme does not outline a matrix with supported operating systems. It should be very easy to find a list of supported os.

**Comment by vjeffrey** [comment]
wip: https://github.com/chef/inspec/compare/vj/add-supported-os-to-readme ...should I be adding more detail there?  and if so, what details? :)

**Comment by chris-rock** [comment]
A couple of things that come into my mind that we should consider:
- Distinguish between OS where inspec can be executed (aka runtime os) and remote targets
- We should have a list
- we should follow the Chef guideline for tier supporting and adding the information here as well

Some references:
- Remote OS Support: https://github.com/chef/train/blob/master/lib/train/extras/os_common.rb
- Tier Support from Chef: https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md#currently-supported-platforms (lets double check that we support all platforms remotely)
- Runtime Support should be limited to RHEL 6 & 7, Windows 7+ , Windows 2012+,  Ubuntu 12.04+, Debain 8

**Comment by vjeffrey** [comment]
thanks chris! that's what i needed!! :)
