### ISSUE TITLE
Add InSpec habitat plan

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#843]
### Description

Currently, InSpec offers a docker image, Habitat is offering the hab plan https://github.com/habitat-sh/core-plans/blob/master/inspec/plan.sh. From my perspective, this plan should be part of InSpec. As a second step, it would be great to bring this together. eg. export docker via habitat.

**Comment by arlimus** [comment]
Great idea, kudos @chris-rock !

Just following the core idea you presented, to create the habitat package continuously, the acceptance criteria is:
- [x] Create a usable InSpec package in Habitat
- [x] Add documentation on how to use the package and how to get it to our readme
- [x] Create rake task to build and release InSpec for Habitat (semi-manual: user hits rake command and that builds and updates/releases the habitat package)

Shared credentials will be in the private compliance-team repo on gh.

**Comment by arlimus** [comment]
Kudos @metadave for completing this item!
