### ISSUE TITLE
Need warning 'Permission denied. Need to be root' to exec this control. 

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#844]
### Description

Some of the controls fail while running 'inspec exec' on it. This is not because its not compliant, but because you need to be root to access the file via Inspec resource. The test in this circumstances are misleading and a correct message like 'Need to be root to access this resource' will be very helpful.
### InSpec and Platform Version

Inspec version - 0.26.0

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
 Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
### Replication Case

Write a valid test using iptables resource and execute the test with inspec.  The test fails irrespective of the iptable rules are correct or not. This is because it was not executed as root or sudo. If you execute as root the test will pass (if its compliant).

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
### Possible Solutions

Inspec needs to check the permission on the files that Inspec resource are accessing and give a warning upon executing it that we need to be root to execute the test.
If you have already ideas how to solve the issue, add them here.
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by aaronlippold** [comment]
👍

**Comment by chris-rock** [comment]
Thanks for reporting @kdshah1 and @aaronlippold A fix would improve the user experience.

**Comment by clintoncwolfe** [comment]
Refs and partial duplicate of #3174
