### ISSUE TITLE
Address all test related to iptables resource. 

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#845]
### Description

Currently there's  no test for iptables is empty and maybe other test to address all the iptables related policies and rules.
### InSpec and Platform Version

Inspec - 0.26.0
Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
 Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
### Replication Case

Hoe do you check if the iptables INPUT chain is empty?

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
### Possible Solutions

Add is_empty check in the iptables resource.
If you have already ideas how to solve the issue, add them here.
### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by aaronlippold** [comment]
👍

**Comment by chris-rock** [comment]
we use iptables (-f table) -S (chain) https://github.com/chef/inspec/blob/master/lib/resources/iptables.rb#L57

```
iptables-restore < ip_rules 
root@vagrant-ubuntu-trusty-64:/vagrant# iptables -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
DROP       icmp --  anywhere             anywhere             icmp timestamp-request
DROP       icmp --  anywhere             anywhere             icmp timestamp-reply
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy DROP)
target     prot opt source               destination         
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination                  
root@vagrant-ubuntu-trusty-64:/vagrant# iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 13 -j DROP
-A INPUT -p icmp -m icmp --icmp-type 14 -j DROP
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
Essentially you need to use
iptables -S forward
iptables: No chain/target/match by that name.
```

At the moment we do not have a good test to check for empty rules eg:

```
describe iptables({chain: 'FORWARD'}) do
        it { should be_empty }
end
```

Instead the following would work, but does not read great:

```
describe iptables({chain: 'FORWARD'}) do
  it { should have_rule('-P FORWARD DROP') }
  it { should have_rule('-A FORWARD -j REJECT --reject-with icmp-host-prohibited') }
end
```

**Comment by chris-rock** [comment]
A sample iptables rules collection was highlighted by @fcaviggia @kdshah1 in our gitter chat

```
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
# Allow Traffic that is established or related
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
# Allow ICMP (Ping)
-A INPUT -p icmp -j ACCEPT
# Allow Traffic on LOCALHOST/127.0.0.1
-A INPUT -i lo -j ACCEPT
# SSH/SCP/SFTP
-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
# Block timestamp-request and timestamp-reply
-A INPUT -p ICMP --icmp-type timestamp-request -j DROP
-A INPUT -p ICMP --icmp-type timestamp-reply -j DROP
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
```

**Comment by fcaviggia** [comment]
Chris,

Here's a srcipt I was using for IPTables and a presentation that I did at Red Hat that was primer to discuss the differences with IPTables/IP6Tables/EBTables and FirewallD.

https://github.com/fcaviggia/hardening-script-el6-kickstart/blob/master/config/hardening/iptables.sh

[Firewalls.pdf](https://github.com/chef/inspec/files/386126/Firewalls.pdf)

**Comment by chris-rock** [comment]
Thanks Frank for sharing those examples.
