### ISSUE TITLE
Document ini resource

### ISSUE THREAD

**Issue by nvtkaszpir** [inspec/inspec#848]
As a developer I would like to verify ini files within inspec:
- if given sections exist
- if given keys+values exist within sections

This should be as new resource, similar to parse_config.

**Comment by chris-rock** [comment]
@nvtkaszpir That is a great idea! Since we head for InSpec 1.0, I assume we cannot make it within the next two months, but PRs are welcome to add this to InSpec

**Comment by chris-rock** [comment]
Is the current ini resource not working for you? https://github.com/chef/inspec/blob/master/lib/resources/ini.rb

**Comment by nvtkaszpir** [comment]
ah, actually I wasn't aware of this, because I was basing on official docs, which does not have 'ini' type per se.

Will see how it works, but apparently docs needs extension.

**Comment by nvtkaszpir** [comment]
yep it works :D

**Comment by chris-rock** [comment]
@nvtkaszpir Alright, we need to add the ini resource to our documentation. Great to hear it works.
