### ISSUE TITLE
inspec fails to determine file_version for a file on a windows 2012R2

### ISSUE THREAD

**Issue by tejas-shah** [inspec/inspec#858]
### Description

inspec fails to determine file_version for a file on a windows 2012R2 through winrm
### InSpec and Platform Version

Version of InSpec (`0.28.0`) and RHEL 6 
### Replication Case

To replicate, create a test and then use syntax provided in documentation:
https://docs.chef.io/inspec_file.html#file-version

```
   describe file("c:/program files (x86)/windows nt/accessories/wordpad.exe") do
     it { should exist }
    its ('file_version') { should eq '6.3.9600.17415' }
```

**Comment by chris-rock** [comment]
I can confirm that the information is not retrieved properly. It is not restricted to winrm.
