### ISSUE TITLE
Improve integration tests

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#861]
### Description

The current integration tests need some updates to ensure they are running with the latest chef-client and inspec versions.
- fix vagrant integration tests
- fix docker integration tests
### InSpec and Platform Version

0.26.0
### Replication Case

run `bundle exec kitchen test`

**Comment by stevendanna** [comment]
Some more notes on the current situation:
- `bundle exec kitchen test`  works on the ubuntu platforms but only if `DOCKER=true` is set in the environment. Currently, many of our spec files early exit if they find`DOCKER=true` in the environment.
- On `centos` we've observed 3 different behaviors depending on the version of chef-client and the version of the runit cookbook: (1) infinite loop when trying to handle a restart notification on a runit service, (2) indefinitely waiting on the runit service to start up, (3) a crash during the CCR.

**Comment by chris-rock** [comment]
Is done by #863 and #869
