### ISSUE TITLE
Legacy grub configuration incorrectly parsed

### ISSUE THREAD

**Issue by stevendanna** [inspec/inspec#868]
### Description

The current grub_conf configuration parser assume that lines after the `title` entry should be indented:

https://github.com/chef/inspec/blob/master/lib/resources/grub_conf.rb#L107

However, grub configurations in the wild don't seem to follow this pattern. For example, the following configuration from amazon linux:

```
# created by imagebuilder
default=0
fallback=1
timeout=0
hiddenmenu

title Amazon Linux 2016.03 (4.4.11-23.53.amzn1.x86_64)
root (hd0,0)
kernel /boot/vmlinuz-4.4.11-23.53.amzn1.x86_64 root=LABEL=/ console=tty1 console=ttyS0
initrd /boot/initramfs-4.4.11-23.53.amzn1.x86_64.img
```

As a result, no information is collected for by the parser.

**Comment by kekaichinose** [comment]
Hey @stevendanna, sorry for the late follow-up here, but are you still seeing this in the current version of InSpec? If so, I would love to get this prioritized for the next sprint. Thanks!
