### ISSUE TITLE
1.10.2 missing a space in failed test output

### ISSUE THREAD

**Issue by unixorn** [inspec/inspec#872]
With kitchen 1.10.2 as installed by ChefDK, I'm getting weird display errors for failing tests. This is when running tests on a guest Ubuntu 16 hosted in VirtualBox on OS X 10.11.6.

Here's a sample, but it does this on all failing tests, not just package tests

```
✖  System Package lockrun should be installedexpected that `System Package lockrun` is installed
```

**Comment by chris-rock** [comment]
Thanks @unixorn I agree that this is annoying.
