### ISSUE TITLE
Add JSON Schema validation

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#884]
### Description

It is critical that the `inspec exec /path/to/profile` returns stable output, since its a API that is consumed in other applications. The current test coverage can be improved.
### InSpec and Platform Version

0.28.0
### Possible Solutions

Develop a JSON Schema for each operation and validate output against it

**Comment by chris-rock** [comment]
This should be added, once we update the API with #811

**Comment by chris-rock** [comment]
It is quite difficult to verify hash values with JSON Schema, see http://stackoverflow.com/questions/22229250/how-to-create-json-schema-for-name-value-structure

We should stick to http://json-schema.org/documentation.html v4. We could use https://github.com/ruby-json-schema/json-schema in our tests

**Comment by arlimus** [comment]
This would have prevented a mistaken exposure in the `--format json` I merged, fail 🤕
