### ISSUE TITLE
Inspec doesn't respond to `--help`

### ISSUE THREAD

**Issue by stevendanna** [inspec/inspec#885]
### Description

The `inspec` command does not respect the `--help` flag, which can be frustrating when iterating on a command that requires many options.
### InSpec and Platform Version

v0.28.1 (and likely earlier versions as well)
### Replication Case

```
inspec exec --help
inspec detect --help
```

**Comment by chris-rock** [comment]
You can retrieve the help via:

```
inspec help exec
inspec help detect
```

I agree that it would be nice to have standard unix behavior here

**Comment by username-is-already-taken2** [comment]
I know it might sound strange but could we consider also adding
--version 

Which i know is two more chars then if I just typed version but when you are auto pilot ;) 

Would then match chefdk etc.

Also and I really don't know what's involved but having tab complete would be pretty cool :)

**Comment by chris-rock** [comment]
@username-is-already-taken2 tab completion is available via `eval "$(inspec env)"`

**Comment by miah** [comment]
This definitely works now. Closing =)
