### ISSUE TITLE
How get the value of argument 'target' e.g: "ssh://user@host" then print it in Inpec Class Profile

### ISSUE THREAD

**Issue by tanahlayang** [inspec/inspec#886]
### Description

Hi masters, I have a necessary to read arguments '--target' from CLI => chef exec inpec PROFILE_PATH -t "ssh://user@host" into my Inspec Class Profile, do you have a guide how to get that's argument values from code? and is there a ways to add custom argument into inspec CLI command, so I can put some custom arguments from CLI, like in JAVA we can define a variable argument, then run it by put -D in prefix
### InSpec and Platform Version

chef exec inspec version => 0.26.0
flatform:  Ubuntu 14.04 x64 bit

Thanks

**Comment by chris-rock** [comment]
@tanahlayang Could you explain the use-case you are trying to cover?

**Comment by tanahlayang** [comment]
hi @chris-rock actually, I create an inspec profile to check some query in oracle database using library ruby-oci8, I also wish this inspec profile could be run in chef-compliance.  but **the problem is, In that class, I put some variable that should must be read as dynamic variable, (e.g: IP Address, UserDB, or Password), and I have explore but there are no documentations or tutorials about inspec or chef-compliance that can read dynamic variable, except from json file. So I wish inspec have a feature or API that allow user define a variable value by read the arguments from CLI, or anything that applicable from chef-compliance compliance console

**Comment by chris-rock** [comment]
Thanks for sharing the usecase. We added an experimental feature for attributes:

```
$ cat examples/profile-attribute.yml 
user: bob
password: secret

$ cat examples/profile-attribute/controls/example.rb 
# encoding: utf-8
val_user = attribute('user', default: 'alice', description: 'An identification for the user')
val_password = attribute('password', description: 'A value for the password')

describe val_user do
  it { should eq 'bob' }
end

describe val_password do
  it { should eq 'secret' }
end

$ inspec exec examples/profile-attribute --attrs examples/profile-attribute.yml
```
- see https://github.com/chef/inspec/tree/master/examples/profile-attribute
- see https://github.com/chef/inspec/issues/719
  We are going to finalize this for InSpec 1.0. Once we've done that, we are going to add support in Chef Compliance.

Do you intend to share some oracle resources?

**Comment by awim** [comment]
hi @chris-rock [here](https://github.com/awim/inspec_oracledb) my rough sample of my inspec profile for assess oracle db connection and query, I wish the _hardcode_ params in controls code should be able to set via extra arguments from CLI or a feature from chef-compliance console, [_tanahlayang_ = me]

**Comment by chris-rock** [comment]
@awim I think we can help here: Have a look at https://github.com/dev-sec/cis-docker-benchmark as an example. If this is not helping, let me know

**Comment by chris-rock** [comment]
@awim Awesome, thanks for sharing the Oracle DB profile! You can also register it at https://supermarket.chef.io/tools?type=compliance_profile
