### ISSUE TITLE
Add windows MSI packaging support to omnibus

### ISSUE THREAD

**Issue by ksubrama** [inspec/inspec#889]
Supporting windows builds requires a few tweaks to our omnibus setup to include the necessary WiX files and openssl cert files and the like.

This is a follow up to https://github.com/chef/inspec/pull/658 and the comments in there.

**Comment by chris-rock** [comment]
Yeah, Windows is coming:
![giphy](https://cloud.githubusercontent.com/assets/1178413/17509950/db58d336-5e1c-11e6-905d-16ff909e9d8b.gif)
