### ISSUE TITLE
`inspec login help` help text inconsistent with `inspec` CLI usage

### ISSUE THREAD

**Issue by ricardolupo** [inspec/inspec#905]
### Description

The help output of `inspec compliance login --help` makes mention of a `--server=` option to specify the compliance server you want to login to, but the command does not recognize this option. 

12:28:05-rlupo~/profiles$ `inspec compliance login --help`
Usage:
  inspec login SERVER

Options:
      [--server=SERVER]                # Chef Compliance Server URL
  k, [--insecure], [--no-insecure]     # Explicitly allows InSpec to perform "insecure" SSL connections and transfers
      [--user=USER]                    # Chef Compliance Username (for legacy auth)
      [--password=PASSWORD]            # Chef Compliance Password (for legacy auth)
      [--apipath=APIPATH]              # Set the path to the API, defaults to /api
                                       # Default: /api
      [--token=TOKEN]                  # Chef Compliance access token
      [--refresh-token=REFRESH_TOKEN]  # Chef Compliance refresh token

Log in to a Chef Compliance SERVER

The actual command will not work with `--server`:
inspec compliance login https://cad-chef-compliance --insecure --user=admin --token=<redacted>
### InSpec and Platform Version

12:32:40-rlupo~/profiles$ inspec version
0.29.0

12:33:53-rlupo~/profiles$ inspec detect

== Operating System Details

Name:      mac_os_x
Family:    darwin
Release:   10.11.6
Arch:      x86_64
### Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
### Possible Solutions

If you have already ideas how to solve the issue, add them here.
### Stacktrace

inspec compliance login --server=https://cad-chef-compliance --insecure --user=admin --token=<redacted>
ERROR: "inspec login" was called with no arguments
Usage: "inspec login SERVER"

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by chris-rock** [comment]
Verified, thanks for highlighting @ricardolupo
