### ISSUE TITLE
`inspec exec` help option does not provide any context sensitive help

### ISSUE THREAD

**Issue by ricardolupo** [inspec/inspec#906]
### Description

As a user, I want to be able see quickly how I can source Inspec profiles from the command line. Currently there's no facility to do this. 
### InSpec and Platform Version

version: 0.2.9
Platform: OS/X
### Replication Case

12:41:07-rlupo~/profiles$ inspec exec --help
Could not fetch inspec profile in "--help".
12:41:16-rlupo~/profiles$ inspec exec help
Could not fetch inspec profile in "help".
12:41:20-rlupo~/profiles$ inspec help
Commands:
  inspec archive PATH                # archive a profile to tar.gz (default) or zip
  inspec check PATH                  # verify all tests at the specified PATH
  inspec compliance SUBCOMMAND ...   # Chef Compliance commands
  inspec detect                      # detect the target OS
  inspec exec PATHS                  # run all test files at the specified PATH.
  inspec help [COMMAND]              # Describe available commands or one specific...
  inspec init TEMPLATE ...           # Scaffolds a new project
  inspec json PATH                   # read all tests in PATH and generate a JSON ...
  inspec shell                       # open an interactive debugging shell
  inspec supermarket SUBCOMMAND ...  # Supermarket commands
  inspec version                     # prints the version of this tool

**Comment by stevendanna** [comment]
I think this is a dup of https://github.com/chef/inspec/issues/885.  Right now to get command specific help you need to run `inspec help COMMAND` (e.g. `inspec help exec`)

**Comment by ricardolupo** [comment]
@stevendanna thanks and that workaround helps. Happy to close if this is a dupe
