### ISSUE TITLE
Add HighLine or Termios library to docker container

### ISSUE THREAD

**Issue by garrickpeterson-wf** [inspec/inspec#908]
### Description

When prompted for the SSH passphrase, the output is echoed to the terminal, along with the warning "Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text." Expected behavior is to not echo passphrases to the terminal.
### InSpec and Platform Version

0.18.0
### Replication Case

Create a minimal test.rb inspec test case, and generate a ssh keypair with a passphrase, storing the private key in the working directory.

docker run -it --rm -v $(pwd):/share chef/inspec exec test.rb -t ssh://example.com -i ./id_rsa
### Possible Solutions

Add highline gem to run. For example, the image from the following Dockerfile will not echo the passphrase to the terminal:

``` Dockerfile
FROM chef/inspec
RUN gem install --quiet highline
```

**Comment by chris-rock** [comment]
@garrickpeterson-wf Its a great idea to install this in our docker container. Would you like to open a PR for that?
