### ISSUE TITLE
CLI UX review

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#910]
A number of new users have trouble understanding what all the things the inspec shell are doing. The have barriers to work effectively with our CLI and use the different mechanisms to execute tests, find answers, work with profiles, and debug runs.

Solution: Have a UX review of the interface and the way that help menues are structured and provide information. 

Issues which are covered by this:
- https://github.com/chef/inspec/issues/305

**Comment by miah** [comment]
Closing in favor of #3426
