### ISSUE TITLE
Windows Management Framework requirement warning

### ISSUE THREAD

**Issue by rneu31** [inspec/inspec#939]
Does it make sense to check if Windows Management Framework 5 (or Powershell 5 or anything else) is on the machine, and if it is not, provide a useful error? 

I missed the spot in the README:
`For Windows 2008 and 2008 R2 an updated Powershell (Windows Management Framework 5.0) is required.`

Additionally, Windows 7 should be added to that warning (I can make that PR if it makes sense, maybe look into the one mentioned first as well).

**Comment by chris-rock** [comment]
@rneu31 that is a great idea and a PR is very much welcome

**Comment by chris-rock** [comment]
It may work with Powershell 4 https://www.microsoft.com/en-us/download/details.aspx?id=40855 as well

**Comment by rneu31** [comment]
So, I updated to Powershell 4 after digging into the code for Package and noticing that ConvertTo-Json was not available until Powershell 3 (and Windows 7 comes with 2). My package testing started to work, but I was still having quite the problems with registry_key.

Doesn't work in 4.0 but does in 5.0:

```
describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full') do
  its('Release') { should eq 379893 }
end
```

**Comment by chris-rock** [comment]
Lets stick to Powershell 5. We use that version for our integration tests as well

**Comment by SamPosh** [comment]
Many people are still in Powershell v4. While other tools are trying to support as early version as possible , why should inspec goes only to greatest?

**Comment by chris-rock** [comment]
@SamPosh we are not going to the latest, and I am happy to support that effort, but we need to test it properly. I would like to split this ticket up into two parts:
- add warning if powershell is not available
- define what is required to run everything in powershell 4. (I bet most resources will work already)

**Comment by miah** [comment]
Closing in favor of: #633
