### ISSUE TITLE
this is killing my eyes!!!!!!!!!

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#951]
### Description

![hurts my eyes](https://cloud.githubusercontent.com/assets/10341541/17863438/9d49eb5c-6867-11e6-856b-14a254d6d19a.png)

staring at the various font/color stuff that's happening here is killin me.
### InSpec and Platform Version

0.30.0
### Replication Case

exec a profile that has a mixture of controls and standalone describe blocks with a variety of expected failures

**Comment by arlimus** [comment]
Confirmed, these colors are driving me insane as well; Let's find a better design in this ticket...

**Comment by ksubrama** [comment]
:) @vjeffrey wanted some powershell examples.  Here's a beautiful one...
<img width="896" alt="screen shot 2016-08-22 at 14 27 13" src="https://cloud.githubusercontent.com/assets/9382254/17866480/ab5b5af2-6874-11e6-8c7e-599dcaf6fc93.png">

But then again...  this is why we all install conemu or cmder on windows.

**Comment by arlimus** [comment]
@ksubrama Thank you for sharing!! interesting to see that the critical failure is much more readable than the the normal ones (i.e. regular red output).

**Comment by jkerry** [comment]
Anyone have a color palate suggestion that is preferred? Pretty sure this can be toggled pretty easily in the cli rspec formatter class

**Comment by arlimus** [comment]
One more confirmation for this one from this morning: We demoed it via test-kitchen and were running on dark background. Any failed results were so hard to read, that we must really switch this. We'll get our UX expert on it. Let's get this closed quickly.

We have overridden the formatter for reporting, but it should stay very easy :grin:

**Comment by arlimus** [comment]
@jkerry yeah, spot on: https://relishapp.com/rspec/rspec-core/v/2-14/docs/formatters/configurable-colors
I'd love to disconnect it slightly from RSpec core, but have it pull these colors in if they are available.

**Comment by arlimus** [comment]
pulling this ticket into waffle :wink: https://waffle.io/chef/inspec

**Comment by arlimus** [comment]
cc @Hannah-radish

**Comment by hannah-radish** [comment]
<img width="604" alt="screen shot 2016-11-22 at 4 14 07 pm" src="https://cloud.githubusercontent.com/assets/18180779/20547106/c50b51c6-b0ce-11e6-9088-c9e763e0e85a.png">
<img width="566" alt="screen shot 2016-11-22 at 4 14 16 pm" src="https://cloud.githubusercontent.com/assets/18180779/20547107/c5c8cbd4-b0ce-11e6-9a60-d0e08fae8e5a.png">

Updated the style guide here as well: https://github.com/chef/inspec/pull/1313/files

**Comment by vjeffrey** [comment]
fixed by: https://github.com/chef/inspec/commit/91fe22f044b85a55f85078408f3dfbb57e2d90d2

**Comment by chris-rock** [comment]
Thank you @vjeffrey @hannah-radish for the great improvement
