### ISSUE TITLE
Research: determine mechanism for recording + playing back inspec

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#955]
Used for the online demo: https://github.com/chef/inspec/issues/851

**Comment by vjeffrey** [comment]
i've been playing around with this, but i'm not sure we'll go that route: https://github.com/sdether/josh.js

also, looking at this for a quick way to capture shell behavior for commands: http://blog.honeybadger.io/capturing-stdout-stderr-from-shell-commands-via-ruby/
