### ISSUE TITLE
Introduce scoping to the ProfileContext which has a view of all of its dependencies 

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#958]
Part of https://github.com/chef/inspec/issues/888
- [x] create an up-front profile context for every profile that is pulled in (e.g. as dependencies)
- [x] attach profile contexts to the dependency tree
- [x] runner loads content in the context of profile inside the dep tree

**Comment by stevendanna** [comment]
I believe #994 gets us the first level of scoping we wanted.  We still have potential work to do with namespacing to allow people to differentiate between two resources with the same name in the same scope.
