### ISSUE TITLE
Inspec be_linked_to matcher does not return true if linked to a symlink

### ISSUE THREAD

**Issue by brentm5** [inspec/inspec#974]
### Description

The following code snippet above should return true but instead it returns false, the bottom snippet does work however.  It looks like 

``` ruby
# Does not work
 describe file('/usr/java/default') do
   it { should be_symlink }
   it { should be_linked_to '/usr/java/latest' }
end

# Works successfully
 describe file('/usr/java/default') do
   it { should be_symlink }
   it { should be_linked_to '/usr/java/jdk1.8.0_8000' }
end
```
### InSpec and Platform Version

Inspec version 0.29.0
### Replication Case

Setup in a VM

``` bash
echo "Hello" > /file
ln -s /file /symlink
ln -s /symlink  /symlinklink
```

Then run the following inspec case

``` ruby
describe file('/symlinklink') do
   it { should be_symlink }
   it { should be_linked_to '/symlink' }
end
```
### Possible Solutions

Look at the first symlink and not the end target?
### Stacktrace

N/A

**Comment by stevendanna** [comment]
I wonder if it would make more sense to have a new matcher (perhaps `be_deeply_linked_to`) that replicates the current behavior and `be_linked_to` would check the immediate link.

**Comment by clintoncwolfe** [comment]
I agree - I think both behaviors are desirable, but should be distinguished.

**Comment by miah** [comment]
We have `shallow_link_path` now which should resolve this issue.

https://www.inspec.io/docs/reference/resources/file/
