### ISSUE TITLE
Improve CLI report

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#984]
### Description

After we merged https://github.com/chef/inspec/pull/946 the reporting has been improved a lot. Still we have to cover some cases, where the report is not displaying all values properly:

<img width="556" alt="screen shot 2016-08-26 at 10 18 49 am" src="https://cloud.githubusercontent.com/assets/1178413/17998830/8c229e20-6b76-11e6-8991-2c84ae70aacd.png">
### InSpec and Platform Version

0.32.0
### Replication Case

```
# you add controls here
control "tmp-1.0" do
  impact 0.7
  title "Create /tmp directory"
  tag data: "temp data"
  tag "security"
  ref "Document A-12", url: 'http://...'

  describe file('/tmp') do                  # The actual test
    it { should be_directory }
    it { should_not be_directory }
  end
end

control "tmp-1.1" do
  impact 0.7
  title "Second test"
  desc "An optional description..."

  describe file('/tmp') do
    it { should be_directory }
  end
end

describe file('/tmp') do
  it { should be_directory }
  it { should_nota be_directory }
end

# you can also use plain tests
describe file('/tmp') do
  it { should be_directory }
end
```
### Possible Solutions

Update the reporter to capture those cases.

**Comment by vjeffrey** [comment]
@chris-rock what would the desired output be for the `it { should_nota be_directory }` case?  marked as skipped and have some kind of error message?

**Comment by vjeffrey** [comment]
for syntax errors: mark as failed and print exception message.  controls output: single passed test case missing checkmark

**Comment by chris-rock** [comment]
We have to issues:
- Exception messages are not displayed
- success messages do not get a checkmark, if a control includes only one test

**Comment by vjeffrey** [comment]
<img width="831" alt="screen shot 2016-08-31 at 11 00 23 pm" src="https://cloud.githubusercontent.com/assets/10341541/18153970/c882228a-6fce-11e6-9ea5-851872099302.png">

on vj/fix-cli-report
