### ISSUE TITLE
Chef compliance breaks after updating inspec gem 0.32

### ISSUE THREAD

**Issue by samsonkolge** [inspec/inspec#992]
### Description

Chef Compliance: 1.3.1
### InSpec and Platform Version

vagrant@vagrant:/opt/chef-compliance/embedded/bin$ ./gem list | grep inspec
inspec (0.32.0)
inspec-msccm (0.0.1)
inspec-scap (0.6.1)

Ubuntu 14.04

Is there a way to use the latest inspec version (0.32) with Chef Compliance version 1.31?
When I try to fetch the latest inspec gem version manually Chef compliance connectivity with the node breaks and gives the below error:

Failed to verify connectivity to winrm://vagrant@192.168.33.95:0 using login password : exit status 1, WARN: Unresolved specs during Gem::Specification.reset: multi_json (~> 1.10) hashie (~> 3.4) WARN: Clearing out unresolved specs. Please report a bug if this causes problems. /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- utils/base_cli (LoadError) from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:133:in`rescue in require' from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in `require' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-msccm-0.0.1/lib/inspec-msccm/cli.rb:3:in`<top (required)>' from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-msccm-0.0.1/lib/inspec-msccm.rb:7:in `<top (required)>' from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require' from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.32.0/lib/inspec/plugins.rb:57:in`load' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.32.0/lib/inspec/cli.rb:228:in `block in <top (required)>' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.32.0/lib/inspec/cli.rb:228:in`each' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.32.0/lib/inspec/cli.rb:228:in `<top (required)>' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.32.0/bin/inspec:8:in`require_relative' from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.32.0/bin/inspec:8:in `<top (required)>' from /opt/chef-compliance/embedded/bin/inspec:22:in`load' from /opt/chef-compliance/embedded/bin/inspec:22:in `<main>

Please let me know when would I be able to use the latest Inspec version with Chef Compliance?

**Comment by chris-rock** [comment]
@samsonkolge We do not support manual upgrade of inspec in Chef Compliance. A new release is shipping within the next week that will include that update. Nevertheless, it should work, once you remove `inspec-msccm` and `inspec-scap` gems

**Comment by chris-rock** [comment]
An updated release of Chef Compliance is available https://discourse.chef.io/t/chef-compliance-1-4-10-released/9279
