### ISSUE TITLE
kernel_module should support checking module version loaded

### ISSUE THREAD

**Issue by nvtkaszpir** [inspec/inspec#993]
### Description

Currently inspec in 0.32.0 supports checking if kernel module is loaded.
Would be nice to extend it with checking if module version is valid.
### InSpec and Platform Version

inspec 0.32.0
### Possible Solutions

Extend kernel_module with additional methods.

Currently this can be done using other modules, for example command(), and checking its output, like this:

```
control 'aws-sriovNetSupport-001' do
  impact 1.0
  title 'kernel module ixgbevf should be minimum version is 2.14.2'
  desc  'http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sriov-networking.html'
  describe command('modinfo -F version ixgbevf') do
    its('stdout') { should match (/^2.14.2.*/) }
  end
end

```

This can be tested on AWS EC2 instance launched in VPC using AMI with HVM support (for example Amazon Linux AMI).
No sure if possible to test it within docker.
### Stacktrace

No stacktrace.

**Comment by chris-rock** [comment]
That is a great idea @nvtkaszpir Do you want to add the version method to https://github.com/chef/inspec/blob/master/lib/resources/kernel_module.rb#L37?

**Comment by nvtkaszpir** [comment]
sorry but my knowledge of writing in ruby is not sufficient to fulfill this task, and learning how to do it is currently loosing a battle with amount of daily work assigned to me :(

**Comment by chris-rock** [comment]
@nvtkaszpir would the following syntax work for you?

```
describe kernel_module('ixgbevf') do
  it { should be_loaded }
  its('version') { should match (/^2.14.2.*/) }
end
```

**Comment by nvtkaszpir** [comment]
Yeha this looks good.
I was wondering if there is an option to specify minimum version matching, like in Gemfile with '>=2.14.2', because I think this would be the most versatile option (I just don't know if match or eq support this at all).

**Comment by aladmit** [comment]
I will add the version method. And I think we should add **have_version** matcher with the following syntax for compare versions:

```
describe kernel_module('ixgbevf') do
    it { should be_loaded }
    it { should have_version '>= 2.14' }
end
```

**Comment by chris-rock** [comment]
@postgred Do we really need the have_version matcher or would cmp matcher work? cmp already understands version comparison.

```
describe kernel_module('ixgbevf') do
  it { should be_loaded }
  its('version') { should cmp >= 2.14 }
end
```

**Comment by aladmit** [comment]
@chris-rock You are right, cmp will work.

**Comment by nvtkaszpir** [comment]
Good to know, so maybe just update docs with more examples?

**Comment by chris-rock** [comment]
@nvtkaszpir We still need to implement the version method in https://github.com/chef/inspec/blob/master/lib/resources/kernel_module.rb#L23-L37

**Comment by chris-rock** [comment]
```
def version
   inspec.command("modinfo -F version ixgbevf").stdout
end
```
may do the trick

**Comment by clintoncwolfe** [comment]
Done on #1435
