### ISSUE TITLE
Process user should eq ["longusername"]: usernames get truncated with a '+' at the end

### ISSUE THREAD

**Issue by TD-4242** [inspec/inspec#995]
### Description

When testing for a username running a command if it is more than 8 characters it gets truncated as per the default ps command.
### InSpec and Platform Version

inspec 0.29.0 from chefdk 0.17.17
### Replication Case

```
describe processes('process') do
  its('users') { should eq ['longusername'] }
end

  1) Processes users should eq ["longusername"]
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: ["longusername"]
            got: ["longuse+"]
```
### Possible Solutions

http://askubuntu.com/questions/523673/ps-aux-for-long-charactered-usernames-shows-a-plus-sign
### Current workaround

shorten test to first 7 letters and a plus(+) sign:

```
describe processes('process') do
  its('users') { should eq ['longuse+'] }
end
```

**Comment by chris-rock** [comment]
@TD-4242 Thanks for reporting. Are you aware of a solution that works without a fixed character length?

**Comment by TD-4242** [comment]
I don't, but I can dig a little further, I'm sure there is something.

**Comment by chris-rock** [comment]
That would be awesome.

**Comment by TD-4242** [comment]
`ps -C <process_name> -o user=`

might be the trick?

**Comment by alexpop** [comment]
Hey Bill, can you try out the code in this PR?
https://github.com/chef/inspec/pull/1225

Here's how you can try it out:

```
git clone https://github.com/alexpop/inspec
cd inspec
git checkout ag-ap/processes-user-comm
bundle install
bundle exec inspec exec ...
```

**Comment by alexpop** [comment]
I'm going to merge #1225.
Bill, @Anirudh-Gupta and everyone involved with this issue. Your help is greatly appreciated!
